Add SGX enclave signing with Azure Key Vault's Managed HSM
gramineproject/contrib pull request #11
Opened 2022-11-10 13:25 UTC by dimakuv

This adds a plugin `gramine-sgx-akv-sign` to core Gramine. This plugin allows to sign SGX enclaves with AKV's Managed HSM keys.

Co-authored-by: Dmitrii Kuvaiskii <dmitrii.kuvaiskii@intel.com>
Signed-off-by: Sankaranarayanan Venkatasubramanian <sankaranarayanan.venkatasubramanian@intel.com>
Signed-off-by: Dmitrii Kuvaiskii <dmitrii.kuvaiskii@intel.com>

2022-11-10 17:43 UTC, mkow requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/11)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`Integrations/hsm-akv/gramine-sgx-akv-sign` line 25 at r1](https://reviewable.io/reviews/gramineproject/contrib/11#-NGXbUig8QyOqLHc0bsP:-NGXbUig8QyOqLHc0bsQ:b3kre) ([raw file](https://github.com/gramineproject/contrib/blob/ad8077bf3652238962cc29385fb0f02e5c181cec/Integrations/hsm-akv/gramine-sgx-akv-sign#L25)):*
> ```
>     requires that the user has an active subscription to Azure and Azure Key Vault's Managed HSM
>     (MHSM), a 3072-bit RSA key created in the MHSM enabled for signing and the user is logged into
>     Azure CLI. This function qualifies for production signing.
> ```

?



_Code quote:_
```
This function qualifies for production signing.
```
___
*[`Integrations/hsm-akv/gramine-sgx-akv-sign` line 70 at r1](https://reviewable.io/reviews/gramineproject/contrib/11#-NGXakFMAtlo4BbcXFh0:-NGXakFMAtlo4BbcXFh1:b2nicts) ([raw file](https://github.com/gramineproject/contrib/blob/ad8077bf3652238962cc29385fb0f02e5c181cec/Integrations/hsm-akv/gramine-sgx-akv-sign#L70)):*
> ```
>               help='Input libpal file')
> @click.option('--key', '-k', type=click.STRING, required=True,
> 	      help='Signing key in format `vault_url:key_name` for AKV Managed HSM')
> ```

tab
___
*[`Integrations/hsm-akv/gramine-sgx-akv-sign` line 92 at r1](https://reviewable.io/reviews/gramineproject/contrib/11#-NGXceTAEusXLjn46_IK:-NGXceTAEusXLjn46_IL:undefined) ([raw file](https://github.com/gramineproject/contrib/blob/ad8077bf3652238962cc29385fb0f02e5c181cec/Integrations/hsm-akv/gramine-sgx-akv-sign#L92)):*
> ```
>         sigfile += '.sig'
> 
>     if verbose == True:
> ```





_Suggestion:_
```
if verbose:
```
___
*[`Integrations/hsm-akv/README.md` line 3 at r1](https://reviewable.io/reviews/gramineproject/contrib/11#-NGX_zFI4wTEFznmfFed:-NGX_zFI4wTEFznmfFee:bfqwapi) ([raw file](https://github.com/gramineproject/contrib/blob/ad8077bf3652238962cc29385fb0f02e5c181cec/Integrations/hsm-akv/README.md#L3)):*
> ```Markdown
> # Enclave signing with Azure Key Vault's Managed HSM
> 
> SGX enclaves need to build and signed using a 3072-bit RSA key. This key needs
> ```

parse error



_Code quote:_
```Markdown
need to build and signed
```
___
*[`Integrations/hsm-akv/README.md` line 5 at r1](https://reviewable.io/reviews/gramineproject/contrib/11#-NGXa73lBdpf0Dv82QUz:-NGXa73lBdpf0Dv82QV-:undefined) ([raw file](https://github.com/gramineproject/contrib/blob/ad8077bf3652238962cc29385fb0f02e5c181cec/Integrations/hsm-akv/README.md#L5)):*
> ```Markdown
> SGX enclaves need to build and signed using a 3072-bit RSA key. This key needs
> to be protected and must not be disclosed to anyone. Typically for production
> deployments, you must use a key secured in a Hardware Security Module (HSM).
> ```





_Suggestion:_
```Markdown
you should use a key secured in a Hardware Security Module (HSM)
```


<!-- Sent from Reviewable.io -->

2022-11-11 08:52 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/11)* status: 0 of 2 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`Integrations/hsm-akv/gramine-sgx-akv-sign` line 25 at r1](https://reviewable.io/reviews/gramineproject/contrib/11#-NGXbUig8QyOqLHc0bsP:-NG_sFcxCV2_WpEih592:buir4w5) ([raw file](https://github.com/gramineproject/contrib/blob/ad8077bf3652238962cc29385fb0f02e5c181cec/Integrations/hsm-akv/gramine-sgx-akv-sign#L25)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

?
</blockquote></details>

Done. Yes, this was a strange sentence. I don't see how it adds any value, let me remove it.
___
*[`Integrations/hsm-akv/gramine-sgx-akv-sign` line 70 at r1](https://reviewable.io/reviews/gramineproject/contrib/11#-NGXakFMAtlo4BbcXFh0:-NG_sOM9AJDNnDDEuc5Y:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/ad8077bf3652238962cc29385fb0f02e5c181cec/Integrations/hsm-akv/gramine-sgx-akv-sign#L70)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

tab
</blockquote></details>

Done.
___
*[`Integrations/hsm-akv/gramine-sgx-akv-sign` line 92 at r1](https://reviewable.io/reviews/gramineproject/contrib/11#-NGXceTAEusXLjn46_IK:-NG_sRwGEzkwTMGinP13:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/ad8077bf3652238962cc29385fb0f02e5c181cec/Integrations/hsm-akv/gramine-sgx-akv-sign#L92)):*
> ```
>         sigfile += '.sig'
> 
>     if verbose == True:
> ```

Done.
___
*[`Integrations/hsm-akv/README.md` line 3 at r1](https://reviewable.io/reviews/gramineproject/contrib/11#-NGX_zFI4wTEFznmfFed:-NG_sa8v25f6shoVj1yu:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/ad8077bf3652238962cc29385fb0f02e5c181cec/Integrations/hsm-akv/README.md#L3)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

parse error
</blockquote></details>

Done.
___
*[`Integrations/hsm-akv/README.md` line 5 at r1](https://reviewable.io/reviews/gramineproject/contrib/11#-NGXa73lBdpf0Dv82QUz:-NG_sd7T4GmD4nojBvhR:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/ad8077bf3652238962cc29385fb0f02e5c181cec/Integrations/hsm-akv/README.md#L5)):*
> ```Markdown
> SGX enclaves need to build and signed using a 3072-bit RSA key. This key needs
> to be protected and must not be disclosed to anyone. Typically for production
> deployments, you must use a key secured in a Hardware Security Module (HSM).
> ```

Done.


<!-- Sent from Reviewable.io -->

2022-11-11 13:58 UTC, mkow submitted a review, later dismissed
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/11)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-11-11 14:27 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/11)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/11#-NGb4dDs4Nw0Pk0WRTHi:-NGb4dDs4Nw0Pk0WRTHj:b-kvzad3) (no related file):*
Let me block myself until @svenkata9 verifies this PR (or teaches me how to verify this PR).

___


<!-- Sent from Reviewable.io -->

2022-11-11 15:41 UTC, svenkata9 commented
Thanks @dimakuv. I will plan to test it next week.

2022-11-15 13:47 UTC, svenkata9 commented
Thanks @dimakuv. This is now tested. ✅

```
gramine-sgx-akv-sign \
        --manifest helloworld.manifest \
        --verbose \
        --key https://svenkat9-akv-mhsm.managedhsm.azure.net:sv-sgx-sign-key \
        --output helloworld.manifest.sgx
Signing with key `https://svenkat9-akv-mhsm.managedhsm.azure.net:sv-sgx-sign-key`.
Attributes:
    size:        0x10000000
    max_threads: 4
    isv_prod_id: 0
    isv_svn:     0
    attr.flags:  0x6
    attr.xfrm:   0x3
    misc_select: 0x0
SGX remote attestation:
    None
Memory:
    000000000fffd000-0000000010000000 [REG:R--] (manifest) measured
    000000000ffdd000-000000000fffd000 [REG:RW-] (ssa) measured
    000000000ffd9000-000000000ffdd000 [TCS:---] (tcs) measured
    000000000ffd5000-000000000ffd9000 [REG:RW-] (tls) measured
    000000000ff95000-000000000ffd5000 [REG:RW-] (stack) measured
    000000000ff55000-000000000ff95000 [REG:RW-] (stack) measured
    000000000ff15000-000000000ff55000 [REG:RW-] (stack) measured
    000000000fed5000-000000000ff15000 [REG:RW-] (stack) measured
    000000000fec5000-000000000fed5000 [REG:RW-] (sig_stack) measured
    000000000feb5000-000000000fec5000 [REG:RW-] (sig_stack) measured
    000000000fea5000-000000000feb5000 [REG:RW-] (sig_stack) measured
    000000000fe95000-000000000fea5000 [REG:RW-] (sig_stack) measured
    000000000fc3c000-000000000fc8c000 [REG:R-X] (code) measured
    000000000fe8b000-000000000fe95000 [REG:RW-] (data) measured
    0000000000010000-000000000fc3c000 [REG:RWX] (free)
Measurement:
    e72f179a9f6dfd415d699aa2a3a563837a9747f5c62e6a02de3558671d4c7046
gramine-sgx-get-token \
        --output helloworld.token --sig helloworld.sig
Attributes:
    mr_enclave:  e72f179a9f6dfd415d699aa2a3a563837a9747f5c62e6a02de3558671d4c7046
    mr_signer:   c5d5b5d72bce40dd1c9669b3eb47e45c61b33be5d5f810a4e66d3a0cdfd6be53
    isv_prod_id: 0
    isv_svn:     0
    attr.flags:  0000000000000006
    attr.xfrm:   00000000000000e7
    mask.flags:  ffffffffffffffff
    mask.xfrm:   fffffffffff9ff1b
    misc_select: 00000000
    misc_mask:   ffffffff
    modulus:     b5504417d9a194e40c3664d86b9ead85...
    exponent:    3
    signature:   12774cfbf8429ddfc7c200f4b00d20e4...
    date:        2022-11-15

**********************************
helloworld (master) $ gramine-sgx helloworld
Gramine is starting. Parsing TOML manifest file, this may take some time...
-----------------------------------------------------------------------------------------------------------------------
Gramine detected the following insecure configurations:

  - sgx.debug = true                           (this is a debug enclave)

Gramine will continue application execution, but this configuration must not be used in production!
-----------------------------------------------------------------------------------------------------------------------

Hello, world

**********************************
```

2022-11-15 13:57 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/11)* status: 1 of 2 files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/11#-NGb4dDs4Nw0Pk0WRTHi:-NGv_AmxAVcSptbRG8OY:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Let me block myself until @svenkata9 verifies this PR (or teaches me how to verify this PR).
</blockquote></details>

Done.

___


<!-- Sent from Reviewable.io -->

2022-11-15 16:19 UTC, woju requested changes
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/11)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`Integrations/hsm-akv/gramine-sgx-akv-sign` line 42 at r3](https://reviewable.io/reviews/gramineproject/contrib/11#-NH41FKf8mACUKLn3dff:-NH41FKf8mACUKLn3dfg:b5lqzyz) ([raw file](https://github.com/gramineproject/contrib/blob/b3fd1fc3aa9364826012ef0f1776542c26bf53a0/Integrations/hsm-akv/gramine-sgx-akv-sign#L42)):*
> ```
>     key_details = key.rsplit(':', 1)
>     vault_url = key_details[0]
>     key_name = key_details[1]
> ```

Don't do this split manually, better provide API URL and key name as separate arguments.
___
*[`Integrations/hsm-akv/README.md` line 16 at r3](https://reviewable.io/reviews/gramineproject/contrib/11#-NH3v_saAjVNJVnGS-DQ:-NH3v_saAjVNJVnGS-DR:bejj0dj) ([raw file](https://github.com/gramineproject/contrib/blob/b3fd1fc3aa9364826012ef0f1776542c26bf53a0/Integrations/hsm-akv/README.md#L16)):*
> ```Markdown
> `gramine-sgx-akv-sign` into Gramine installation directory like this:
> ```
> cp gramine-sgx-akv-sign $(dirname $(which gramine-sgx-sign))
> ```

Don't do this. It will get overwritten when you upgrade or reinstall gramine. Please use `gramine-sgx-akv-sign` command as it.


<!-- Sent from Reviewable.io -->

2022-11-15 17:30 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/11)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @woju)

___
*[`Integrations/hsm-akv/gramine-sgx-akv-sign` line 42 at r3](https://reviewable.io/reviews/gramineproject/contrib/11#-NH41FKf8mACUKLn3dff:-NGwKXmH7Ppg_BXxvv9Q:b-pmcsnk) ([raw file](https://github.com/gramineproject/contrib/blob/b3fd1fc3aa9364826012ef0f1776542c26bf53a0/Integrations/hsm-akv/gramine-sgx-akv-sign#L42)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Don't do this split manually, better provide API URL and key name as separate arguments.
</blockquote></details>

But I can't, this is the API provided by our core Python scripts. See the signature -- there is only one `key` string arg.
___
*[`Integrations/hsm-akv/README.md` line 16 at r3](https://reviewable.io/reviews/gramineproject/contrib/11#-NH3v_saAjVNJVnGS-DQ:-NGwKe2WCDSKLNjWm_VA:b-yl765j) ([raw file](https://github.com/gramineproject/contrib/blob/b3fd1fc3aa9364826012ef0f1776542c26bf53a0/Integrations/hsm-akv/README.md#L16)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Don't do this. It will get overwritten when you upgrade or reinstall gramine. Please use `gramine-sgx-akv-sign` command as it.
</blockquote></details>

What do you mean by "use `gramine-sgx-akv-sign` command as is"? It can be already used as is, this is just a para in the README on how to make it available in case users want to.

If there is a better way to install this script, what would it be?


<!-- Sent from Reviewable.io -->

2022-11-16 11:49 UTC, woju requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/11)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`Integrations/hsm-akv/gramine-sgx-akv-sign` line 9 at r3](https://reviewable.io/reviews/gramineproject/contrib/11#-NGvWjVI7zQFr10Fn2kx:-NH-GDCl6Aw5jmc37w-V:b-r7z0yp) ([raw file](https://github.com/gramineproject/contrib/blob/b3fd1fc3aa9364826012ef0f1776542c26bf53a0/Integrations/hsm-akv/gramine-sgx-akv-sign#L9)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

FYI: This was detected by @svenkata9 while testing. Thanks!
</blockquote></details>

Should have been detected by `.pylint`, but I guess we don't run pylint in this repo?
___
*[`Integrations/hsm-akv/gramine-sgx-akv-sign` line 42 at r3](https://reviewable.io/reviews/gramineproject/contrib/11#-NH41FKf8mACUKLn3dff:-NH--HIj2plbzjQkWWUM:b-yqrfab) ([raw file](https://github.com/gramineproject/contrib/blob/b3fd1fc3aa9364826012ef0f1776542c26bf53a0/Integrations/hsm-akv/gramine-sgx-akv-sign#L42)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

But I can't, this is the API provided by our core Python scripts. See the signature -- there is only one `key` string arg.
</blockquote></details>

This is different script that `gramine-sgx-sign`. What's the reason to be constrained by its signature?
___
*[`Integrations/hsm-akv/README.md` line 16 at r3](https://reviewable.io/reviews/gramineproject/contrib/11#-NH3v_saAjVNJVnGS-DQ:-NH-0ExJBvkeDmTj57fH:b-n5rpm2) ([raw file](https://github.com/gramineproject/contrib/blob/b3fd1fc3aa9364826012ef0f1776542c26bf53a0/Integrations/hsm-akv/README.md#L16)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What do you mean by "use `gramine-sgx-akv-sign` command as is"? It can be already used as is, this is just a para in the README on how to make it available in case users want to.

If there is a better way to install this script, what would it be?
</blockquote></details>

Just run from current directory `./gramine-sgx-akv-sign` and don't describe installation? Because if you really want to install, you quickly get into issues like prefix, `$PATH` and also `$PYTHONPATH` which isn't discussed here, but it's liable to break. In this case the instruction as described would work, even if you have development setup with non-standard prefix, but correctly setup both `$PATH` and `$PREFIXPATH`, and iff you follow the instruction to the letter. But if for example you've forgot about `$PYTHONPATH`, things will break. Moreover, if you reinstall to another directory, it will break ("Why it stopped working for this another gramine instance? I did install it and I didn't mess with it after!").

The "correct" way would be to add full buildsystem, even if it looks like overkill. Then you can make sure `--prefix` is aligned. But for now I'd suggest to just `./`-run this. (It would be necessary anyway do do "something" when we'll package it).


<!-- Sent from Reviewable.io -->

2022-11-16 12:16 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/11)* status: 1 of 2 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

___
*[`Integrations/hsm-akv/gramine-sgx-akv-sign` line 9 at r3](https://reviewable.io/reviews/gramineproject/contrib/11#-NGvWjVI7zQFr10Fn2kx:-NH-Kw0gAXEWk0dmn-5R:b5nnjml) ([raw file](https://github.com/gramineproject/contrib/blob/b3fd1fc3aa9364826012ef0f1776542c26bf53a0/Integrations/hsm-akv/gramine-sgx-akv-sign#L9)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Should have been detected by `.pylint`, but I guess we don't run pylint in this repo?
</blockquote></details>

Yep, we don't.
___
*[`Integrations/hsm-akv/gramine-sgx-akv-sign` line 42 at r3](https://reviewable.io/reviews/gramineproject/contrib/11#-NH41FKf8mACUKLn3dff:-NH-L6BX8DnWl8XYCAtX:burn258) ([raw file](https://github.com/gramineproject/contrib/blob/b3fd1fc3aa9364826012ef0f1776542c26bf53a0/Integrations/hsm-akv/gramine-sgx-akv-sign#L42)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

This is different script that `gramine-sgx-sign`. What's the reason to be constrained by its signature?
</blockquote></details>

No, again, this is not about the script itself. It is about the Python API that Gramine exposes:
- https://gramine.readthedocs.io/en/latest/python/api.html (there is no `sigstruct.sign()` method described, which is a fail, but you can see it used in the example)
- https://github.com/gramineproject/gramine/blob/670cc12609520d01ca4e73af37d57f975faa215d/python/graminelibos/sigstruct.py#L149-L158

Well, now that I think of it, I could use `args`/`kargs` to provide the additional part (the API URL, I guess). Should I do that?
___
*[`Integrations/hsm-akv/README.md` line 16 at r3](https://reviewable.io/reviews/gramineproject/contrib/11#-NH3v_saAjVNJVnGS-DQ:-NH-MYAJ3hV_3PomyF7T:b1vkua) ([raw file](https://github.com/gramineproject/contrib/blob/b3fd1fc3aa9364826012ef0f1776542c26bf53a0/Integrations/hsm-akv/README.md#L16)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Just run from current directory `./gramine-sgx-akv-sign` and don't describe installation? Because if you really want to install, you quickly get into issues like prefix, `$PATH` and also `$PYTHONPATH` which isn't discussed here, but it's liable to break. In this case the instruction as described would work, even if you have development setup with non-standard prefix, but correctly setup both `$PATH` and `$PREFIXPATH`, and iff you follow the instruction to the letter. But if for example you've forgot about `$PYTHONPATH`, things will break. Moreover, if you reinstall to another directory, it will break ("Why it stopped working for this another gramine instance? I did install it and I didn't mess with it after!").

The "correct" way would be to add full buildsystem, even if it looks like overkill. Then you can make sure `--prefix` is aligned. But for now I'd suggest to just `./`-run this. (It would be necessary anyway do do "something" when we'll package it).
</blockquote></details>

Done. Ok, thanks for explanations!


<!-- Sent from Reviewable.io -->

2022-11-16 13:18 UTC, svenkata9 commented
@woju @dimakuv I am not for providing a separate argument option for URL, and we should maintain it as -key. Couple of reasons -

- This gives us flexibility to change the internal implementation later if something changes in AKV. We can pass the key based on whatever the latest format is and parse it internally.
- Then, this one - I chose something close to this - https://github.com/microsoft/AzureKeyVaultManagedHSMEngine/tree/main/samples/openssl

2022-11-17 12:46 UTC, dimakuv reviewed
I tend to agree with @svenkata9's reasoning. From what I see, OpenSSL has the same logic regarding the `-key <keyname>` argument.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/11#-:-NH4bz3453hmwkSkV0HR:b9fdb26)* status: 1 of 2 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)



<!-- Sent from Reviewable.io -->

2022-11-21 04:59 UTC, svenkata9 commented
@woju Can we please close on this?

2022-11-22 21:22 UTC, woju requested changes
Yes, sorry for the delay. See comments below.

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/11#-:-NHWByVL4SWaSmXBwJJu:biu82py)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`Integrations/hsm-akv/gramine-sgx-akv-sign` line 42 at r3](https://reviewable.io/reviews/gramineproject/contrib/11#-NH41FKf8mACUKLn3dff:-NHWAyFi8qrcvI87pIvP:bn09kn) ([raw file](https://github.com/gramineproject/contrib/blob/b3fd1fc3aa9364826012ef0f1776542c26bf53a0/Integrations/hsm-akv/gramine-sgx-akv-sign#L42)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

No, again, this is not about the script itself. It is about the Python API that Gramine exposes:
- https://gramine.readthedocs.io/en/latest/python/api.html (there is no `sigstruct.sign()` method described, which is a fail, but you can see it used in the example)
- https://github.com/gramineproject/gramine/blob/670cc12609520d01ca4e73af37d57f975faa215d/python/graminelibos/sigstruct.py#L149-L158

Well, now that I think of it, I could use `args`/`kargs` to provide the additional part (the API URL, I guess). Should I do that?
</blockquote></details>

Yes please, url (or is it uri? I'm not sure at this point) by kwargs, all else probably by positional args? Or all arguments by kwargs, won't hurt.

And I agree this is API unwieldy, but I'm not sure how to do it better. We need q1 and q2, and make sure people won't shoot themselves in foot.

I don't understand what happened to `sigstruct.sign()` documentation. It's certainly a bug.


<!-- Sent from Reviewable.io -->

2022-11-23 08:54 UTC, dimakuv reviewed
Ok, so we reverted to Woju's proposal of splitting `--key <key-name>:<vault-url>` into `--key <key-name> --url <vault-url>`. For several reasons:
1. It's more intuitive and user-friendly.
2. It adheres nicely to our `sigstruct.sign()` Gramine Python API (I was wrong previously saying that it was not possible).
3. It's how internal AKV Python API expects the arguments (as separate strings).
4. OpenSSL is a bad example for almost everything :)

> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/11#-:-NHYeiSY2nv9yBjx5EYa:bhtsbpk)* status: 0 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @woju)

___
*[`Integrations/hsm-akv/gramine-sgx-akv-sign` line 42 at r3](https://reviewable.io/reviews/gramineproject/contrib/11#-NH41FKf8mACUKLn3dff:-NHYe4v3E8kBWNfTQole:bnxwp6g) ([raw file](https://github.com/gramineproject/contrib/blob/b3fd1fc3aa9364826012ef0f1776542c26bf53a0/Integrations/hsm-akv/gramine-sgx-akv-sign#L42)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Yes please, url (or is it uri? I'm not sure at this point) by kwargs, all else probably by positional args? Or all arguments by kwargs, won't hurt.

And I agree this is API unwieldy, but I'm not sure how to do it better. We need q1 and q2, and make sure people won't shoot themselves in foot.

I don't understand what happened to `sigstruct.sign()` documentation. It's certainly a bug.
</blockquote></details>

Done.

It is `url`, not `uri`. Even though MS AKV documentation sometimes talks about URIs, I decided to adhere to the Python API that we use here: https://learn.microsoft.com/en-us/azure/key-vault/keys/quick-create-python?tabs=azure-cli. And in this API, they use `vaultUrl`.

Also `*args` seemed better to me than `*kwargs`.


<!-- Sent from Reviewable.io -->

2022-11-23 10:52 UTC, woju approved these changes
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/11)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[`Integrations/hsm-akv/gramine-sgx-akv-sign` line 42 at r3](https://reviewable.io/reviews/gramineproject/contrib/11#-NH41FKf8mACUKLn3dff:-NHZ5Q4u4MFCoZqUEaPo:b-dkpxro) ([raw file](https://github.com/gramineproject/contrib/blob/b3fd1fc3aa9364826012ef0f1776542c26bf53a0/Integrations/hsm-akv/gramine-sgx-akv-sign#L42)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done.

It is `url`, not `uri`. Even though MS AKV documentation sometimes talks about URIs, I decided to adhere to the Python API that we use here: https://learn.microsoft.com/en-us/azure/key-vault/keys/quick-create-python?tabs=azure-cli. And in this API, they use `vaultUrl`.

Also `*args` seemed better to me than `*kwargs`.
</blockquote></details>

OK.

As a rule of thumb `**kwargs` are better, because you might forget the order, so they function as a runtime checker (IIUC linter won't check arguments passed through like that). Here it doesn't really matter, because you supply your own function, so the signature and call is at (relatively) the same place, so can be changed together. And if you swap key id for url, I hope HTTP client will complain.


<!-- Sent from Reviewable.io -->

2022-11-24 05:44 UTC, svenkata9 commented
The latest update is verified now -
```
helloworld (master) $ make SGX=1
cc -Wall -Wextra -O3   -c -o helloworld.o helloworld.c
cc   helloworld.o   -o helloworld
gramine-manifest \
        -Dlog_level=error \
        helloworld.manifest.template helloworld.manifest
./gramine-sgx-akv-sign \
        --manifest helloworld.manifest \
        --url https://svenkat9-akv-mhsm.managedhsm.azure.net\
        --key sv-sgx-sign-key\
        --output helloworld.manifest.sgx
Signing with key `sv-sgx-sign-key` from Azure Key Vault Managed HSM `https://svenkat9-akv-mhsm.managedhsm.azure.net`.
Attributes:
    size:        0x10000000
    max_threads: 4
    isv_prod_id: 0
    isv_svn:     0
    attr.flags:  0x6
    attr.xfrm:   0x3
    misc_select: 0x0
SGX remote attestation:
    None
Memory:
    000000000fffd000-0000000010000000 [REG:R--] (manifest) measured
    000000000ffdd000-000000000fffd000 [REG:RW-] (ssa) measured
    000000000ffd9000-000000000ffdd000 [TCS:---] (tcs) measured
    000000000ffd5000-000000000ffd9000 [REG:RW-] (tls) measured
    000000000ff95000-000000000ffd5000 [REG:RW-] (stack) measured
    000000000ff55000-000000000ff95000 [REG:RW-] (stack) measured
    000000000ff15000-000000000ff55000 [REG:RW-] (stack) measured
    000000000fed5000-000000000ff15000 [REG:RW-] (stack) measured
    000000000fec5000-000000000fed5000 [REG:RW-] (sig_stack) measured
    000000000feb5000-000000000fec5000 [REG:RW-] (sig_stack) measured
    000000000fea5000-000000000feb5000 [REG:RW-] (sig_stack) measured
    000000000fe95000-000000000fea5000 [REG:RW-] (sig_stack) measured
    000000000fc3c000-000000000fc8c000 [REG:R-X] (code) measured
    000000000fe8b000-000000000fe95000 [REG:RW-] (data) measured
    0000000000010000-000000000fc3c000 [REG:RWX] (free)
Measurement:
    e72f179a9f6dfd415d699aa2a3a563837a9747f5c62e6a02de3558671d4c7046
gramine-sgx-get-token \
        --output helloworld.token --sig helloworld.sig
Attributes:
    mr_enclave:  e72f179a9f6dfd415d699aa2a3a563837a9747f5c62e6a02de3558671d4c7046
    mr_signer:   ec4128e3cf2fc1608c1e82737e5c6996ff6b9b04e308f52ac8167fb66faf30e5
    isv_prod_id: 0
    isv_svn:     0
    attr.flags:  0000000000000006
    attr.xfrm:   00000000000000e7
    mask.flags:  ffffffffffffffff
    mask.xfrm:   fffffffffff9ff1b
    misc_select: 00000000
    misc_mask:   ffffffff
    modulus:     bf700e55cd826e0dbc8e8d63ff1ba713...
    exponent:    3
    signature:   9ac79aa2dc5cae4a49664b7f2754911a...
    date:        2022-11-24

**********************************
1494 svenkat9@172.17.0.1
10.219.138.94  Thu Nov 24 11:04
/home/svenkat9/devel/g/gramine/CI-Examples/helloworld
helloworld (master) $ gramine-sgx helloworld
Gramine is starting. Parsing TOML manifest file, this may take some time...
-----------------------------------------------------------------------------------------------------------------------
Gramine detected the following insecure configurations:

  - sgx.debug = true                           (this is a debug enclave)

Gramine will continue application execution, but this configuration must not be used in production!
-----------------------------------------------------------------------------------------------------------------------

Hello, world

**********************************

```

2022-11-24 08:34 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/11)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/11#-NHcl5a19ecY4R2dMD5L:-NHcl5a19ecY4R2dMD5M:b-4x1qsm) (no related file):*
Actually, we didn't agree on the directory structure, introduced with this PR.

The current structure is like this: `contrib repo -> Integrations -> hsm-akv`.

Other possibilities:
- `contrib repo -> Integrations -> hsm -> akv`
- `contrib repo -> Integrations -> azure -> hsm-akv`
- `contrib repo -> Integrations -> azure -> hsm -> akv`

I think I like the **second** option. So in the future, with more plugins, the dir structure will look like this:
```
contrib repo ->
    Integrations ->
        azure ->
            maa ...
            akv ...
            hsm-akv ...
        openssl ->
            hsm-engine ...
```

@svenkata9 @woju @mkow @boryspoplawski WDYT?

___


<!-- Sent from Reviewable.io -->

2022-11-24 08:47 UTC, svenkata9 commented
I like the second one too, and expanding on top of your example structure - should be better like this -
```
contrib repo ->
    Integrations ->
        azure ->
            maa ...
            akv-key-provisioning ...
            akv-sign ...
        openssl ->
            hsm-engine ..
```

2022-11-24 09:06 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/11)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/11#-NHcl5a19ecY4R2dMD5L:-NHcshUJ80q9tgzw9lKo:b-ivom84) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Actually, we didn't agree on the directory structure, introduced with this PR.

The current structure is like this: `contrib repo -> Integrations -> hsm-akv`.

Other possibilities:
- `contrib repo -> Integrations -> hsm -> akv`
- `contrib repo -> Integrations -> azure -> hsm-akv`
- `contrib repo -> Integrations -> azure -> hsm -> akv`

I think I like the **second** option. So in the future, with more plugins, the dir structure will look like this:
```
contrib repo ->
    Integrations ->
        azure ->
            maa ...
            akv ...
            hsm-akv ...
        openssl ->
            hsm-engine ...
```

@svenkata9 @woju @mkow @boryspoplawski WDYT?
</blockquote></details>

I agree with @svenkata9's proposal (see his top-level comment). So for this PR, the suggested dir structure will be like this:
```
contrib repo ->
    Integrations ->
        azure ->
            akv-sign ...
```

___


<!-- Sent from Reviewable.io -->

2022-11-24 12:15 UTC, mkow requested changes
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/11)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski, @svenkata9, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/11#-NHcl5a19ecY4R2dMD5L:-NHdXcS84UylJKkArN5J:brs2w1m) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I agree with @svenkata9's proposal (see his top-level comment). So for this PR, the suggested dir structure will be like this:
```
contrib repo ->
    Integrations ->
        azure ->
            akv-sign ...
```
</blockquote></details>

I'm fine with this structure, and both `akv-hsm` and `akv-sign` sound ok.

@svenkata9: Please use Reviewable discussion threads, backtracing your discussion with Dmitrii was quite confusing because you replied to it in a different thread.

___


<!-- Sent from Reviewable.io -->

2022-11-24 13:31 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/11)* status: 0 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski, @mkow, @svenkata9, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/11#-NHcl5a19ecY4R2dMD5L:-NHdpXqiD9ZQogo4NOwR:b-896fix) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'm fine with this structure, and both `akv-hsm` and `akv-sign` sound ok.

@svenkata9: Please use Reviewable discussion threads, backtracing your discussion with Dmitrii was quite confusing because you replied to it in a different thread.
</blockquote></details>

Done.

___


<!-- Sent from Reviewable.io -->

2022-11-24 19:37 UTC, mkow approved these changes
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/11)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-11-25 06:57 UTC, merged