Curate Scikit-learn
gramineproject/contrib pull request #12
Opened 2022-11-11 10:45 UTC by jkr0103

Updating the Curated script and packages to add `Intel® extension for Scikit-learn` app

2022-11-15 09:10 UTC, dimakuv requested changes
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/12)* status: all files reviewed, 20 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @jkr0103)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/contrib/12#-NGuYG3VDP-ey81qU98R):*
I would change to `[Curated-Apps] Add Scikit-learn` (will do at final rebase)
___
*[`Curated-Apps/curate.py` line 40 at r1](https://reviewable.io/reviews/gramineproject/contrib/12#-NGuR6tx-WF4plH8GxjE:-NGuR6tx-WF4plH8GxjF:bwnlvwm) ([raw file](https://github.com/gramineproject/contrib/blob/4f89ad6460d01146894a4fb4e5002a493b96de23/Curated-Apps/curate.py#L40)):*
> ```Python
> |      |          |                  | for full list of supported workload types) e.g. redis. |
> | 2.   |    Yes   | <base image name>| Base image name to be graminized.                      |
> |      |          |                  |                                                        |
> ```

Please remove this empty line. I don't see how it helps in readability.
___
*[`Curated-Apps/README.md` line 53 at r1](https://reviewable.io/reviews/gramineproject/contrib/12#-NGuRIJdAf8Wcy2pc4ni:-NGuRIJdAf8Wcy2pc4nj:b-7ropln) ([raw file](https://github.com/gramineproject/contrib/blob/4f89ad6460d01146894a4fb4e5002a493b96de23/Curated-Apps/README.md#L53)):*
> ```Markdown
>     |      |          |                  | for full list of supported workload types) e.g. redis. |
>     | 2.   |    Yes   | <base image name>| Base image name to be graminized.                      |
>     |      |          |                  |                                                        |
> ```

ditto
___
*[`Curated-Apps/util/curation_script.sh` line 20 at r1](https://reviewable.io/reviews/gramineproject/contrib/12#-NGuROaaEPwaW3KLQRsb:-NGuROaaEPwaW3KLQRsc:b-6hsplr) ([raw file](https://github.com/gramineproject/contrib/blob/4f89ad6460d01146894a4fb4e5002a493b96de23/Curated-Apps/util/curation_script.sh#L20)):*
> ```Shell
> # The input parameters in sequence are below:
> # -- arg1    : workload type (refer /workload sub-directory for full list of supported workload
> #              types) e.g. redis
> ```

Here I would make it shorter:
```
# -- arg1    : workload type (see /workload sub-directory for list of supported workloads
```
___
*[`Curated-Apps/workloads/sklearn/.gitignore` line 5 at r1](https://reviewable.io/reviews/gramineproject/contrib/12#-NGuRYGgBaRp1ric_Be1:-NGuRYGgBaRp1ric_Be2:b-38txxg) ([raw file](https://github.com/gramineproject/contrib/blob/4f89ad6460d01146894a4fb4e5002a493b96de23/Curated-Apps/workloads/sklearn/.gitignore#L5)):*
> ```ignore
> /sklearn-gsc.dockerfile
> /sklearn.manifest
> ```

Please remove empty line.
___
*[`Curated-Apps/workloads/sklearn/README.md` line 1 at r1](https://reviewable.io/reviews/gramineproject/contrib/12#-NGuUulED50uiVzfI0Lb:-NGuUulED50uiVzfI0Lc:bfabx4p) ([raw file](https://github.com/gramineproject/contrib/blob/4f89ad6460d01146894a4fb4e5002a493b96de23/Curated-Apps/workloads/sklearn/README.md#L1)):*
> ```Markdown
> # Gramine Curated Intel® extension for Scikit-learn
> ```

Please add an empty line after this title, for readability
___
*[`Curated-Apps/workloads/sklearn/README.md` line 2 at r1](https://reviewable.io/reviews/gramineproject/contrib/12#-NGuUzL46o0ztTtIVOBQ:-NGuUzL46o0ztTtIVOBR:bjuv966) ([raw file](https://github.com/gramineproject/contrib/blob/4f89ad6460d01146894a4fb4e5002a493b96de23/Curated-Apps/workloads/sklearn/README.md#L2)):*
> ```Markdown
> # Gramine Curated Intel® extension for Scikit-learn
> In the following two sections, we explain how a Docker image for the Scikit-learn can be built and
> ```

`for the Scikit-learn` -> `for the Scikit-learn machine learning library`
___
*[`Curated-Apps/workloads/sklearn/README.md` line 7 at r1](https://reviewable.io/reviews/gramineproject/contrib/12#-NGuUxV-1MbtUoelga1O:-NGuUxV-1MbtUoelga1P:bfabx4p) ([raw file](https://github.com/gramineproject/contrib/blob/4f89ad6460d01146894a4fb4e5002a493b96de23/Curated-Apps/workloads/sklearn/README.md#L7)):*
> ```Markdown
> both the phases are assumed to be met.
> 
> ## Build a confidential compute image for Scikit-learn
> ```

Please add an empty line after this title, for readability
___
*[`Curated-Apps/workloads/sklearn/README.md` line 24 at r1](https://reviewable.io/reviews/gramineproject/contrib/12#-NGuVXZTBHpwR2Runeqh:-NGuVXZTBHpwR2Runeqi:bhirsks) ([raw file](https://github.com/gramineproject/contrib/blob/4f89ad6460d01146894a4fb4e5002a493b96de23/Curated-Apps/workloads/sklearn/README.md#L24)):*
> ```Markdown
> 
> 4. To generate a preconfigured non-production test `Intel® extension
>    for Scikit-learn` confidential compute image, follow the below steps:
> ```

This reads ugly. Can we replace like this:
```
4. To generate a preconfigured non-production test confidential compute image for Scikit-learn,
   follow the below steps:
```

(please re-wrap the above to 100 chars)
___
*[`Curated-Apps/workloads/sklearn/README.md` line 44 at r1](https://reviewable.io/reviews/gramineproject/contrib/12#-NGuUyFQ9OSRuvB7WXIE:-NGuUyFQ9OSRuvB7WXIF:bfabx4p) ([raw file](https://github.com/gramineproject/contrib/blob/4f89ad6460d01146894a4fb4e5002a493b96de23/Curated-Apps/workloads/sklearn/README.md#L44)):*
> ```Markdown
> - Follow the output of the `curate.py` script to run the generated Docker image(s).
> 
> ## Contents
> ```

Please add an empty line after this title, for readability
___
*[`Curated-Apps/workloads/sklearn/sklearn-gsc.dockerfile.template` line 13 at r1](https://reviewable.io/reviews/gramineproject/contrib/12#-NGuWWbv8C7gP3bfTtBT:-NGuWWbv8C7gP3bfTtBU:b-pb4q6m) ([raw file](https://github.com/gramineproject/contrib/blob/4f89ad6460d01146894a4fb4e5002a493b96de23/Curated-Apps/workloads/sklearn/sklearn-gsc.dockerfile.template#L13)):*
> ```
> COPY entry_script_sklearn.sh /usr/local/bin/entry_script_sklearn.sh
> ENTRYPOINT ["/bin/bash", "/usr/local/bin/entry_script_sklearn.sh"]
> ```

Please remove empty line
___
*[`Curated-Apps/workloads/sklearn/sklearn.manifest.template` line 19 at r1](https://reviewable.io/reviews/gramineproject/contrib/12#-NGuWg8a3_xx3QS3wvp1:-NGuWg8bDzHUGapd42dT:b-pb4q6m) ([raw file](https://github.com/gramineproject/contrib/blob/4f89ad6460d01146894a4fb4e5002a493b96de23/Curated-Apps/workloads/sklearn/sklearn.manifest.template#L19)):*
> ```
>   { type = "tmpfs", path = "/tmp" },
> ]
> ```

Please remove empty line
___
*[`Curated-Apps/workloads/sklearn/base_image_helper/Dockerfile` line 7 at r1](https://reviewable.io/reviews/gramineproject/contrib/12#-NGuXcAo7_dPzREN0uwq:-NGuXcAo7_dPzREN0uwr:b-9xx2p3) ([raw file](https://github.com/gramineproject/contrib/blob/4f89ad6460d01146894a4fb4e5002a493b96de23/Curated-Apps/workloads/sklearn/base_image_helper/Dockerfile#L7)):*
> ```Dockerfile
> ENTRYPOINT ["python3"]
> 
> CMD ["kmeans.py"]
> ```

Why do you use two commands to generate the string `python3 kmeans.py`? Why not like in the PyTorch example: https://github.com/jkr0103/contrib/blob/4f89ad6460d01146894a4fb4e5002a493b96de23/Curated-Apps/workloads/pytorch/base_image_helper/Dockerfile#L7 ?
___
*[`Curated-Apps/workloads/sklearn/base_image_helper/Dockerfile` line 8 at r1](https://reviewable.io/reviews/gramineproject/contrib/12#-NGuX69uBiBfT_XiA-38:-NGuX69uBiBfT_XiA-39:b-pb4q6m) ([raw file](https://github.com/gramineproject/contrib/blob/4f89ad6460d01146894a4fb4e5002a493b96de23/Curated-Apps/workloads/sklearn/base_image_helper/Dockerfile#L8)):*
> ```Dockerfile
> 
> CMD ["kmeans.py"]
> ```

Please remove empty line
___
*[`Curated-Apps/workloads/sklearn/base_image_helper/helper.sh` line 22 at r1](https://reviewable.io/reviews/gramineproject/contrib/12#-NGuXCfz9b7G_wTqPKxh:-NGuXCfz9b7G_wTqPKxi:b-pb4q6m) ([raw file](https://github.com/gramineproject/contrib/blob/4f89ad6460d01146894a4fb4e5002a493b96de23/Curated-Apps/workloads/s [...]

2022-11-15 10:20 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/12)* status: 0 of 11 files reviewed, 20 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`Curated-Apps/curate.py` line 40 at r1](https://reviewable.io/reviews/gramineproject/contrib/12#-NGuR6tx-WF4plH8GxjE:-NGulMDC5A8DR_adHDRb:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/4f89ad6460d01146894a4fb4e5002a493b96de23/Curated-Apps/curate.py#L40)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove this empty line. I don't see how it helps in readability.
</blockquote></details>

Done.
___
*[`Curated-Apps/README.md` line 53 at r1](https://reviewable.io/reviews/gramineproject/contrib/12#-NGuRIJdAf8Wcy2pc4ni:-NGulNHP68VMDal5uN8a:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/4f89ad6460d01146894a4fb4e5002a493b96de23/Curated-Apps/README.md#L53)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`Curated-Apps/util/curation_script.sh` line 20 at r1](https://reviewable.io/reviews/gramineproject/contrib/12#-NGuROaaEPwaW3KLQRsb:-NGulO3ND_NU9ANwu1oN:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/4f89ad6460d01146894a4fb4e5002a493b96de23/Curated-Apps/util/curation_script.sh#L20)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Here I would make it shorter:
```
# -- arg1    : workload type (see /workload sub-directory for list of supported workloads
```
</blockquote></details>

Done.
___
*[`Curated-Apps/workloads/sklearn/.gitignore` line 5 at r1](https://reviewable.io/reviews/gramineproject/contrib/12#-NGuRYGgBaRp1ric_Be1:-NGulOlK32NeC00phE71:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/4f89ad6460d01146894a4fb4e5002a493b96de23/Curated-Apps/workloads/sklearn/.gitignore#L5)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove empty line.
</blockquote></details>

Done.
___
*[`Curated-Apps/workloads/sklearn/README.md` line 1 at r1](https://reviewable.io/reviews/gramineproject/contrib/12#-NGuUulED50uiVzfI0Lb:-NGulPsJAqEE6JR0lsAA:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/4f89ad6460d01146894a4fb4e5002a493b96de23/Curated-Apps/workloads/sklearn/README.md#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add an empty line after this title, for readability
</blockquote></details>

Done.
___
*[`Curated-Apps/workloads/sklearn/README.md` line 2 at r1](https://reviewable.io/reviews/gramineproject/contrib/12#-NGuUzL46o0ztTtIVOBQ:-NGulQbHCSjh4Y4Pc9m9:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/4f89ad6460d01146894a4fb4e5002a493b96de23/Curated-Apps/workloads/sklearn/README.md#L2)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`for the Scikit-learn` -> `for the Scikit-learn machine learning library`
</blockquote></details>

Done.
___
*[`Curated-Apps/workloads/sklearn/README.md` line 7 at r1](https://reviewable.io/reviews/gramineproject/contrib/12#-NGuUxV-1MbtUoelga1O:-NGulRFYEanbNOUvd21h:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/4f89ad6460d01146894a4fb4e5002a493b96de23/Curated-Apps/workloads/sklearn/README.md#L7)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add an empty line after this title, for readability
</blockquote></details>

Done.
___
*[`Curated-Apps/workloads/sklearn/README.md` line 24 at r1](https://reviewable.io/reviews/gramineproject/contrib/12#-NGuVXZTBHpwR2Runeqh:-NGulTWs9f2YEB9UIuHa:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/4f89ad6460d01146894a4fb4e5002a493b96de23/Curated-Apps/workloads/sklearn/README.md#L24)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This reads ugly. Can we replace like this:
```
4. To generate a preconfigured non-production test confidential compute image for Scikit-learn,
   follow the below steps:
```

(please re-wrap the above to 100 chars)
</blockquote></details>

Done.
___
*[`Curated-Apps/workloads/sklearn/README.md` line 44 at r1](https://reviewable.io/reviews/gramineproject/contrib/12#-NGuUyFQ9OSRuvB7WXIE:-NGulV5p7Qe40ECI9Top:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/4f89ad6460d01146894a4fb4e5002a493b96de23/Curated-Apps/workloads/sklearn/README.md#L44)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add an empty line after this title, for readability
</blockquote></details>

Done.
___
*[`Curated-Apps/workloads/sklearn/sklearn-gsc.dockerfile.template` line 13 at r1](https://reviewable.io/reviews/gramineproject/contrib/12#-NGuWWbv8C7gP3bfTtBT:-NGulWG85ZgOf1nfbneK:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/4f89ad6460d01146894a4fb4e5002a493b96de23/Curated-Apps/workloads/sklearn/sklearn-gsc.dockerfile.template#L13)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove empty line
</blockquote></details>

Done.
___
*[`Curated-Apps/workloads/sklearn/sklearn.manifest.template` line 19 at r1](https://reviewable.io/reviews/gramineproject/contrib/12#-NGuWg8a3_xx3QS3wvp1:-NGulWyY5nIiZ-HxS_sE:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/4f89ad6460d01146894a4fb4e5002a493b96de23/Curated-Apps/workloads/sklearn/sklearn.manifest.template#L19)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove empty line
</blockquote></details>

Done.
___
*[`Curated-Apps/workloads/sklearn/base_image_helper/Dockerfile` line 7 at r1](https://reviewable.io/reviews/gramineproject/contrib/12#-NGuXcAo7_dPzREN0uwq:-NGul_XXAMkbyBrfxsIC:b-cn4xm2) ([raw file](https://github.com/gramineproject/contrib/blob/4f89ad6460d01146894a4fb4e5002a493b96de23/Curated-Apps/workloads/sklearn/base_image_helper/Dockerfile#L7)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do you use two commands to generate the string `python3 kmeans.py`? Why not like in the PyTorch example: https://github.com/jkr0103/contrib/blob/4f89ad6460d01146894a4fb4e5002a493b96de23/Curated-Apps/workloads/pytorch/base_image_helper/Dockerfile#L7 ?
</blockquote></details>

This gives flexibility when you have multiple example in image as CMD arguments can be overridden. Earlier I had multiple examples in the image and was testing all by passing command-line arguments to curation app. But now as we have only one example, so ENTRYPOINT itself should be enough.
___
*[`Curated-Apps/workloads/sklearn/base_image_helper/Dockerfile` line 8 at r1](https://reviewable.io/reviews/gramineproject/contrib/12#-NGuX69uBiBfT_XiA-38:-NGumT_p7eD05_3xuYuh:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/4f89ad6460d01146894a4fb4e5002a493b96de23/Curated-Apps/workloads/sklearn/base_image_helper/Dockerfile#L8)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove empty line
</blockquote></details>

Done.
___
*[`Curated-Apps/workloads/sklearn/base_image_helper/helper.sh` line 22 at r1](https://reviewable.io/reviews/gramineproject/contrib/12#-NGuXCfz9b7G_wTqPKxh:-NGumUAP86jej15jLv3W:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/4f89ad6460d01146894a4fb4e5002a493b96de23/Curated-Apps/workloads/sklearn/base_image_helper/helper.sh#L22)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove empty li [...]

2022-11-16 07:51 UTC, dimakuv submitted a review, later dismissed
> Reviewed 11 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/12)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @jkr0103)

___
*[`Curated-Apps/workloads/sklearn/base_image_helper/Dockerfile` line 7 at r1](https://reviewable.io/reviews/gramineproject/contrib/12#-NGuXcAo7_dPzREN0uwq:-NGzPFJ56IXgWZu0vCDP:b2nhktp) ([raw file](https://github.com/gramineproject/contrib/blob/4f89ad6460d01146894a4fb4e5002a493b96de23/Curated-Apps/workloads/sklearn/base_image_helper/Dockerfile#L7)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

This gives flexibility when you have multiple example in image as CMD arguments can be overridden. Earlier I had multiple examples in the image and was testing all by passing command-line arguments to curation app. But now as we have only one example, so ENTRYPOINT itself should be enough.
</blockquote></details>

OK.


<!-- Sent from Reviewable.io -->

2022-11-24 09:10 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r3, 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/12)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @jkr0103)

___
*[`Curated-Apps/workloads/sklearn/sklearn.manifest.template` line 5 at r3](https://reviewable.io/reviews/gramineproject/contrib/12#-NHYw41-3zusmq_jyE0v:-NHctapVE5GeGjsVNYub:bdbcegr) ([raw file](https://github.com/gramineproject/contrib/blob/ab7d6f705412eca7609508bded9858c6caebda80/Curated-Apps/workloads/sklearn/sklearn.manifest.template#L5)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

changes here are to be consistent with Scikit-learn [PR](https://github.com/gramineproject/examples/pull/15)  in examples repo and same examples tested with Scikit-learn curated app as well with these changes.
</blockquote></details>

What about these two?
- `loader.env.PYTHONIOENCODING = "utf-8"`
- `sys.stack.size = "8M"`

I would add them as well.


<!-- Sent from Reviewable.io -->

2022-11-24 09:17 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/12)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`Curated-Apps/workloads/sklearn/sklearn.manifest.template` line 5 at r3](https://reviewable.io/reviews/gramineproject/contrib/12#-NHYw41-3zusmq_jyE0v:-NHcusDbAmEm6kJirzNe:bbrg7ci) ([raw file](https://github.com/gramineproject/contrib/blob/ab7d6f705412eca7609508bded9858c6caebda80/Curated-Apps/workloads/sklearn/sklearn.manifest.template#L5)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What about these two?
- `loader.env.PYTHONIOENCODING = "utf-8"`
- `sys.stack.size = "8M"`

I would add them as well.
</blockquote></details>

We are using `bitnami/scikit-learn-intel` image which have `python3.9.15`. Hence I thought of not including it as PYTHONIOENCODING was required with older versions like python3.6.


<!-- Sent from Reviewable.io -->

2022-11-24 09:26 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/12)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @jkr0103)

___
*[`Curated-Apps/workloads/sklearn/sklearn.manifest.template` line 5 at r3](https://reviewable.io/reviews/gramineproject/contrib/12#-NHYw41-3zusmq_jyE0v:-NHcxLyy29x94rNezwRN:b-iaciqq) ([raw file](https://github.com/gramineproject/contrib/blob/ab7d6f705412eca7609508bded9858c6caebda80/Curated-Apps/workloads/sklearn/sklearn.manifest.template#L5)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

We are using `bitnami/scikit-learn-intel` image which have `python3.9.15`. Hence I thought of not including it as PYTHONIOENCODING was required with older versions like python3.6.
</blockquote></details>

Sounds good. What about `sys.stack.size`?


<!-- Sent from Reviewable.io -->

2022-11-24 09:52 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/12)* status: 12 of 13 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`Curated-Apps/workloads/sklearn/sklearn.manifest.template` line 5 at r3](https://reviewable.io/reviews/gramineproject/contrib/12#-NHYw41-3zusmq_jyE0v:-NHd2Jk-3qTmrekbJZgf:bqmjwcz) ([raw file](https://github.com/gramineproject/contrib/blob/ab7d6f705412eca7609508bded9858c6caebda80/Curated-Apps/workloads/sklearn/sklearn.manifest.template#L5)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Sounds good. What about `sys.stack.size`?
</blockquote></details>

Added.


<!-- Sent from Reviewable.io -->

2022-11-24 09:55 UTC, dimakuv reviewed
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/12)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @jkr0103)



<!-- Sent from Reviewable.io -->

2022-11-24 09:55 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/12)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @jkr0103)



<!-- Sent from Reviewable.io -->

2022-12-02 00:48 UTC, mkow requested changes
> Reviewed 6 of 11 files at r2, 6 of 6 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/12)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @jkr0103)

___
*[`Curated-Apps/curate.py` line 37 at r5](https://reviewable.io/reviews/gramineproject/contrib/12#-NIFFuHjB6g1WzBwiM99:-NIFFuHk9LepHmvGsdYv:undefined) ([raw file](https://github.com/gramineproject/contrib/blob/e95afd36c67d0293f5cae37df4e2b68fcce4d64b/Curated-Apps/curate.py#L37)):*
> ```Python
> | S.No.| Required?| Argument         | Description/Possible values                            |
> |------|----------|------------------|--------------------------------------------------------|
> | 1.   |    Yes   | <workload type>  | Provide type of workload (refer /workload sub-directory|
> ```





_Suggestion:_
```Python
refer to
```
___
*[`Curated-Apps/curate.py` line 37 at r5](https://reviewable.io/reviews/gramineproject/contrib/12#-NIFFwhG8-jitZ2kZM6-:-NIFFwhG8-jitZ2kZM60:undefined) ([raw file](https://github.com/gramineproject/contrib/blob/e95afd36c67d0293f5cae37df4e2b68fcce4d64b/Curated-Apps/curate.py#L37)):*
> ```Python
> | S.No.| Required?| Argument         | Description/Possible values                            |
> |------|----------|------------------|--------------------------------------------------------|
> | 1.   |    Yes   | <workload type>  | Provide type of workload (refer /workload sub-directory|
> ```





_Suggestion:_
```Python
workload/
```
___
*[`Curated-Apps/curate.py` line 37 at r5](https://reviewable.io/reviews/gramineproject/contrib/12#-NIFG1dxATUSCYtr6iWN:-NIFG1dxATUSCYtr6iWO:undefined) ([raw file](https://github.com/gramineproject/contrib/blob/e95afd36c67d0293f5cae37df4e2b68fcce4d64b/Curated-Apps/curate.py#L37)):*
> ```Python
> | S.No.| Required?| Argument         | Description/Possible values                            |
> |------|----------|------------------|--------------------------------------------------------|
> | 1.   |    Yes   | <workload type>  | Provide type of workload (refer /workload sub-directory|
> ```





_Suggestion:_
```Python
Type of workload
```
___
*[`Curated-Apps/README.md` line 51 at r5](https://reviewable.io/reviews/gramineproject/contrib/12#-NIFG6nH-092LNASOg7k:-NIFG6nH-092LNASOg7l:b-7ropln) ([raw file](https://github.com/gramineproject/contrib/blob/e95afd36c67d0293f5cae37df4e2b68fcce4d64b/Curated-Apps/README.md#L51)):*
> ```Markdown
>     |------|----------|------------------|--------------------------------------------------------|
>     | 1.   |    Yes   | <workload type>  | Provide type of workload (refer /workload sub-directory|
>     |      |          |                  | for full list of supported workload types) e.g. redis. |
> ```

ditto
___
*[`Curated-Apps/util/curation_script.sh` line 19 at r5](https://reviewable.io/reviews/gramineproject/contrib/12#-NIFGFQpCbKcrd0OE66r:-NIFGFQpCbKcrd0OE66s:undefined) ([raw file](https://github.com/gramineproject/contrib/blob/e95afd36c67d0293f5cae37df4e2b68fcce4d64b/Curated-Apps/util/curation_script.sh#L19)):*
> ```Shell
> 
> # The input parameters in sequence are below:
> # -- arg1    : workload type (see /workload sub-directory for list of supported workload types)
> ```





_Suggestion:_
```Shell
workload/
```
___
*[`Curated-Apps/workloads/sklearn/sklearn-gsc.dockerfile.template` line 6 at r5](https://reviewable.io/reviews/gramineproject/contrib/12#-NIFH8q441AphuP94Kwk:-NIFH8q441AphuP94Kwl:undefined) ([raw file](https://github.com/gramineproject/contrib/blob/e95afd36c67d0293f5cae37df4e2b68fcce4d64b/Curated-Apps/workloads/sklearn/sklearn-gsc.dockerfile.template#L6)):*
> ```
> 
> # The curation script fills the <base_image_name> during curation.
> From <base_image_name>
> ```





_Suggestion:_
```
FROM
```
___
*[`Curated-Apps/workloads/sklearn/sklearn.manifest.template` line 8 at r5](https://reviewable.io/reviews/gramineproject/contrib/12#-NIFHFgD6N4BJ3jxro1v:-NIFHFgD6N4BJ3jxro1w:b4d5ity) ([raw file](https://github.com/gramineproject/contrib/blob/e95afd36c67d0293f5cae37df4e2b68fcce4d64b/Curated-Apps/workloads/sklearn/sklearn.manifest.template#L8)):*
> ```
> sgx.thread_num = 128
> loader.pal_internal_mem_size = "128M"
> loader.env.OMP_NUM_THREADS = "8"
> ```

Why are you capping threads at 8? What if the user wants to run the workload on a 128-core machine?
___
*[`Curated-Apps/workloads/sklearn/sklearn.manifest.template` line 10 at r5](https://reviewable.io/reviews/gramineproject/contrib/12#-NIFHQ-RBN2n9ON3U89e:-NIFHQ-RBN2n9ON3U89f:b-ktijaz) ([raw file](https://github.com/gramineproject/contrib/blob/e95afd36c67d0293f5cae37df4e2b68fcce4d64b/Curated-Apps/workloads/sklearn/sklearn.manifest.template#L10)):*
> ```
> loader.env.OMP_NUM_THREADS = "8"
> 
> # This is required to run workload as non-root user, any random number works except `0` which
> ```

it doesn't have to be random



_Suggestion:_
```
any number
```


<!-- Sent from Reviewable.io -->

2022-12-02 08:12 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/12)* status: 8 of 14 files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`Curated-Apps/curate.py` line 37 at r5](https://reviewable.io/reviews/gramineproject/contrib/12#-NIFFuHjB6g1WzBwiM99:-NIGpt8i0J_8JilF-wzT:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/e95afd36c67d0293f5cae37df4e2b68fcce4d64b/Curated-Apps/curate.py#L37)):*
> ```Python
> | S.No.| Required?| Argument         | Description/Possible values                            |
> |------|----------|------------------|--------------------------------------------------------|
> | 1.   |    Yes   | <workload type>  | Provide type of workload (refer /workload sub-directory|
> ```

Done.
___
*[`Curated-Apps/curate.py` line 37 at r5](https://reviewable.io/reviews/gramineproject/contrib/12#-NIFFwhG8-jitZ2kZM6-:-NIGq6nqCv5gekHmuyJl:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/e95afd36c67d0293f5cae37df4e2b68fcce4d64b/Curated-Apps/curate.py#L37)):*
> ```Python
> | S.No.| Required?| Argument         | Description/Possible values                            |
> |------|----------|------------------|--------------------------------------------------------|
> | 1.   |    Yes   | <workload type>  | Provide type of workload (refer /workload sub-directory|
> ```

Done.
___
*[`Curated-Apps/curate.py` line 37 at r5](https://reviewable.io/reviews/gramineproject/contrib/12#-NIFG1dxATUSCYtr6iWN:-NIGq7j80xSY-Ah7b64q:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/e95afd36c67d0293f5cae37df4e2b68fcce4d64b/Curated-Apps/curate.py#L37)):*
> ```Python
> | S.No.| Required?| Argument         | Description/Possible values                            |
> |------|----------|------------------|--------------------------------------------------------|
> | 1.   |    Yes   | <workload type>  | Provide type of workload (refer /workload sub-directory|
> ```

Done.
___
*[`Curated-Apps/README.md` line 51 at r5](https://reviewable.io/reviews/gramineproject/contrib/12#-NIFG6nH-092LNASOg7k:-NIGqAME4o_CKQ7Nd9JV:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/e95afd36c67d0293f5cae37df4e2b68fcce4d64b/Curated-Apps/README.md#L51)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`Curated-Apps/util/curation_script.sh` line 19 at r5](https://reviewable.io/reviews/gramineproject/contrib/12#-NIFGFQpCbKcrd0OE66r:-NIGqC6t4pbCUEDlbSYF:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/e95afd36c67d0293f5cae37df4e2b68fcce4d64b/Curated-Apps/util/curation_script.sh#L19)):*
> ```Shell
> 
> # The input parameters in sequence are below:
> # -- arg1    : workload type (see /workload sub-directory for list of supported workload types)
> ```

Done.
___
*[`Curated-Apps/workloads/sklearn/sklearn-gsc.dockerfile.template` line 6 at r5](https://reviewable.io/reviews/gramineproject/contrib/12#-NIFH8q441AphuP94Kwk:-NIGqCmJ9Idd9eLEmuV7:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/e95afd36c67d0293f5cae37df4e2b68fcce4d64b/Curated-Apps/workloads/sklearn/sklearn-gsc.dockerfile.template#L6)):*
> ```
> 
> # The curation script fills the <base_image_name> during curation.
> From <base_image_name>
> ```

Done.
___
*[`Curated-Apps/workloads/sklearn/sklearn.manifest.template` line 8 at r5](https://reviewable.io/reviews/gramineproject/contrib/12#-NIFHFgD6N4BJ3jxro1v:-NIGqDt_0cNVwpr7i0VR:b6o131p) ([raw file](https://github.com/gramineproject/contrib/blob/e95afd36c67d0293f5cae37df4e2b68fcce4d64b/Curated-Apps/workloads/sklearn/sklearn.manifest.template#L8)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why are you capping threads at 8? What if the user wants to run the workload on a 128-core machine?
</blockquote></details>

I tested scikit-learn example on 72 core machine. This particular example created 4-5 subprocesses. I checked the total thread count reaches upto 60 and 84, with OPM_NUM_THREADS 8 and 16 respectively.
If we dpn't use OPM_NUM_THREADS, total thread count reaches 287 and with that execution exceed by 3-4 times and performance also drops. We get best performnce with `OPM_NUM_THREADS=8` on 72 core machine. But I think we can add a comment here for tuning this parameter as per machine configuration?

Proposed Comment:
`# Given example is tested on 72 core machine where it gives best results with default value 8. Please tune this parameter as per your machine configuration.`


<!-- Sent from Reviewable.io -->

2022-12-02 08:15 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/12)* status: 8 of 14 files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`Curated-Apps/workloads/sklearn/sklearn.manifest.template` line 10 at r5](https://reviewable.io/reviews/gramineproject/contrib/12#-NIFHQ-RBN2n9ON3U89e:-NIGtqt23pO6VnUlhHJc:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/e95afd36c67d0293f5cae37df4e2b68fcce4d64b/Curated-Apps/workloads/sklearn/sklearn.manifest.template#L10)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

it doesn't have to be random
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-02 12:03 UTC, mkow requested changes
> Reviewed 5 of 6 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/12)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @jkr0103)

___
*[`Curated-Apps/workloads/sklearn/sklearn.manifest.template` line 8 at r5](https://reviewable.io/reviews/gramineproject/contrib/12#-NIFHFgD6N4BJ3jxro1v:-NIHhvII8D_BlYKUhnn_:bzgg3ce) ([raw file](https://github.com/gramineproject/contrib/blob/e95afd36c67d0293f5cae37df4e2b68fcce4d64b/Curated-Apps/workloads/sklearn/sklearn.manifest.template#L8)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

I tested scikit-learn example on 72 core machine. This particular example created 4-5 subprocesses. I checked the total thread count reaches upto 60 and 84, with OPM_NUM_THREADS 8 and 16 respectively.
If we dpn't use OPM_NUM_THREADS, total thread count reaches 287 and with that execution exceed by 3-4 times and performance also drops. We get best performnce with `OPM_NUM_THREADS=8` on 72 core machine. But I think we can add a comment here for tuning this parameter as per machine configuration?

Proposed Comment:
`# Given example is tested on 72 core machine where it gives best results with default value 8. Please tune this parameter as per your machine configuration.`

</blockquote></details>

Yup, would be better with such a comment.


<!-- Sent from Reviewable.io -->

2022-12-02 12:07 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/12)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`Curated-Apps/workloads/sklearn/sklearn.manifest.template` line 8 at r5](https://reviewable.io/reviews/gramineproject/contrib/12#-NIFHFgD6N4BJ3jxro1v:-NIHilqq-HwRtbkogTkL:b-u8x0fb) ([raw file](https://github.com/gramineproject/contrib/blob/e95afd36c67d0293f5cae37df4e2b68fcce4d64b/Curated-Apps/workloads/sklearn/sklearn.manifest.template#L8)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yup, would be better with such a comment.
</blockquote></details>

Can I add the above comment as is or you suggest some addition/modiciations?


<!-- Sent from Reviewable.io -->

2022-12-05 22:26 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/12)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @jkr0103)



<!-- Sent from Reviewable.io -->

2022-12-06 18:31 UTC, dimakuv submitted a review, later dismissed
> Reviewed 4 of 6 files at r6, 2 of 3 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/12)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @jkr0103)



<!-- Sent from Reviewable.io -->

2022-12-06 19:01 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/12)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/contrib/12#-NGuYG3VDP-ey81qU98R):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would change to `[Curated-Apps] Add Scikit-learn` (will do at final rebase)
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-12-06 19:20 UTC, mkow approved these changes
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/12)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-12-06 21:25 UTC, merged