Support inputs for addition docker flags
gramineproject/contrib pull request #13
Opened 2022-11-17 13:50 UTC by jkr0103

As of now curation app doesn't have provision to input additional docker flags (--name, --rm, -p, etc.). Hence these flags cannot be added to the `docker run` commands generated by curation app in commands.txt. This PR provides option to input these flags which ultimately gets added to `docker run` instructions for running the curated images, please refer the attached screenshot for the UI related changes.
![docker_flags](https://user-images.githubusercontent.com/15154645/202463276-d88ca4c6-c657-4d81-97d7-cd78327868c7.jpg)

2022-11-17 13:58 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/13)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @jkr0103)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/contrib/13#-NH4riNp1B4T7Dp9R7sf):*
```
Curation: add user inputs for additional `docker run` flags
```
___
*[`Curated-Apps/util/constants.py` line 52 at r1](https://reviewable.io/reviews/gramineproject/contrib/13#-NH4sF_L4_H6BoQjKWr3:-NH4sF_L4_H6BoQjKWr4:b-dwfig0) ([raw file](https://github.com/gramineproject/contrib/blob/0bac0af8083f7ff9c7790bdbafbda916d0810714/Curated-Apps/util/constants.py#L52)):*
> ```Python
>          '2. Command-line arguments',
>          '3. Environment variables',
>          '4. Additional docker flags',
> ```

`4. Additional docker run flags`
___
*[`Curated-Apps/util/constants.py` line 127 at r1](https://reviewable.io/reviews/gramineproject/contrib/13#-NH4sJD73XTbilCkl5Dp:-NH4sJD73XTbilCkl5Dq:b-nx69ie) ([raw file](https://github.com/gramineproject/contrib/blob/0bac0af8083f7ff9c7790bdbafbda916d0810714/Curated-Apps/util/constants.py#L127)):*
> ```Python
>              ' docker image.']
> 
> flags_input = ['>> Additional docker flags:','Specify docker flags here in a single string.'
> ```

`>> Additional docker run flags`
___
*[`Curated-Apps/util/constants.py` line 127 at r1](https://reviewable.io/reviews/gramineproject/contrib/13#-NH4sLIR3SvB3mxzM72c:-NH4sLIR3SvB3mxzM72d:bf2ez3o) ([raw file](https://github.com/gramineproject/contrib/blob/0bac0af8083f7ff9c7790bdbafbda916d0810714/Curated-Apps/util/constants.py#L127)):*
> ```Python
>              ' docker image.']
> 
> flags_input = ['>> Additional docker flags:','Specify docker flags here in a single string.'
> ```

`Specify docker run flags`
___
*[`Curated-Apps/util/constants.py` line 128 at r1](https://reviewable.io/reviews/gramineproject/contrib/13#-NH4sNwtChTCNyofzpi1:-NH4sNwtChTCNyofzpi2:brsoi7l) ([raw file](https://github.com/gramineproject/contrib/blob/0bac0af8083f7ff9c7790bdbafbda916d0810714/Curated-Apps/util/constants.py#L128)):*
> ```Python
> 
> flags_input = ['>> Additional docker flags:','Specify docker flags here in a single string.'
>              ' For example, if your docker runtime is ', 'docker run flag1 flag2 <image_name>'
> ```

`docker runtime` -> `docker command`


<!-- Sent from Reviewable.io -->

2022-11-17 14:12 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/13)* status: 0 of 2 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/contrib/13#-NH4riNp1B4T7Dp9R7sf):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

```
Curation: add user inputs for additional `docker run` flags
```
</blockquote></details>

Done.
___
*[`Curated-Apps/util/constants.py` line 52 at r1](https://reviewable.io/reviews/gramineproject/contrib/13#-NH4sF_L4_H6BoQjKWr3:-NH4vbyy1rhVmm3J9f3N:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/0bac0af8083f7ff9c7790bdbafbda916d0810714/Curated-Apps/util/constants.py#L52)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`4. Additional docker run flags`
</blockquote></details>

Done.
___
*[`Curated-Apps/util/constants.py` line 127 at r1](https://reviewable.io/reviews/gramineproject/contrib/13#-NH4sJD73XTbilCkl5Dp:-NH4vcZ80FA3Qp0nDtVC:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/0bac0af8083f7ff9c7790bdbafbda916d0810714/Curated-Apps/util/constants.py#L127)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`>> Additional docker run flags`
</blockquote></details>

Done.
___
*[`Curated-Apps/util/constants.py` line 127 at r1](https://reviewable.io/reviews/gramineproject/contrib/13#-NH4sLIR3SvB3mxzM72c:-NH4vcvs7wdVNWcKvw1J:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/0bac0af8083f7ff9c7790bdbafbda916d0810714/Curated-Apps/util/constants.py#L127)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`Specify docker run flags`
</blockquote></details>

Done.
___
*[`Curated-Apps/util/constants.py` line 128 at r1](https://reviewable.io/reviews/gramineproject/contrib/13#-NH4sNwtChTCNyofzpi1:-NH4vdSx7CBxKvJvL2gM:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/0bac0af8083f7ff9c7790bdbafbda916d0810714/Curated-Apps/util/constants.py#L128)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`docker runtime` -> `docker command`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-17 14:32 UTC, dimakuv submitted a review, later dismissed
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/13)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-12-09 00:47 UTC, mkow requested changes
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/13)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @jkr0103)

___
*[`-- commits` line 3 at r3](https://reviewable.io/reviews/gramineproject/contrib/13#-NIoKO1o3IsP_Iv0QPnz):*
wrong commit message format


<!-- Sent from Reviewable.io -->

2022-12-09 07:47 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/13)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`-- commits` line 3 at r3](https://reviewable.io/reviews/gramineproject/contrib/13#-NIoKO1o3IsP_Iv0QPnz):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

wrong commit message format
</blockquote></details>

modified the commit format for last commit.


<!-- Sent from Reviewable.io -->

2022-12-10 00:40 UTC, mkow requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/13)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @jkr0103)

___
*[`-- commits` line 3 at r3](https://reviewable.io/reviews/gramineproject/contrib/13#-NIoKO1o3IsP_Iv0QPnz):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

modified the commit format for last commit.
</blockquote></details>

That's not how `!fixup`/`--fixup` in git works, now it will break.


<!-- Sent from Reviewable.io -->

2022-12-10 00:49 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/13)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`-- commits` line 3 at r3](https://reviewable.io/reviews/gramineproject/contrib/13#-NIoKO1o3IsP_Iv0QPnz):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

That's not how `!fixup`/`--fixup` in git works, now it will break.
</blockquote></details>

Do you want me to correct the first commit message? Sorry I am not clear here.


<!-- Sent from Reviewable.io -->

2022-12-10 01:03 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/13)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @jkr0103)

___
*[`-- commits` line 3 at r3](https://reviewable.io/reviews/gramineproject/contrib/13#-NIoKO1o3IsP_Iv0QPnz):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

Do you want me to correct the first commit message? Sorry I am not clear here.
</blockquote></details>

Whichever way that works, but the one you used doesn't, please read how `git commit --fixup` works.
Here probably the easiest way will be just squashing the commits and force pushing.
___
*[`-- commits` line 12 at r4](https://reviewable.io/reviews/gramineproject/contrib/13#-NItYZXs2oFOmsGTIrmm):*
You previously used a different tag...



_Code quote:_
```
[Curated Apps]
```


<!-- Sent from Reviewable.io -->

2022-12-10 01:22 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/13)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @jkr0103)

___
*[`-- commits` line 12 at r4](https://reviewable.io/reviews/gramineproject/contrib/13#-NItYZXs2oFOmsGTIrmm):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

We will follow this tag `[Curated Apps]` for all Curated Apps work. we used the same even with Scikit-learn PR #12
</blockquote></details>

No, you used a different one there.


<!-- Sent from Reviewable.io -->

2022-12-10 01:47 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/13)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow)

___
*[`-- commits` line 3 at r3](https://reviewable.io/reviews/gramineproject/contrib/13#-NIoKO1o3IsP_Iv0QPnz):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

Sure, will squash the commits with commit message:
`[Curated Apps] Add user inputs for additional `docker run` flags`
</blockquote></details>

Squashed the commits with new new commit message.
___
*[`-- commits` line 12 at r4](https://reviewable.io/reviews/gramineproject/contrib/13#-NItYZXs2oFOmsGTIrmm):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

No, you used a different one there.
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2022-12-10 01:58 UTC, mkow submitted a review, later dismissed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/13)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2022-12-10 18:00 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/13)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-12-10 18:00 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/13)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-12-10 18:01 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/13)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2022-12-10 23:28 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/13)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-12-10 23:30 UTC, merged