[Curated-Apps] Add tensorflow serving curation app example
gramineproject/contrib pull request #16
Opened 2022-12-05 03:57 UTC by sahason

Updating the Curated script and packages to add tensorflow-serving.

Signed-off-by: Sonali Saha <sonali.saha@intel.com>

2022-12-06 10:43 UTC, svenkata9 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/16)* status: 0 of 8 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @sahason)

___
*[`Curated-Apps/workloads/tensorflow-serving/base_image_helper/Dockerfile` line 4 at r1](https://reviewable.io/reviews/gramineproject/contrib/16#-NIb0zud9HofPmdsRCfk:-NIb0zud9HofPmdsRCfl:bhtwxhu) ([raw file](https://github.com/gramineproject/contrib/blob/a34c9ac95304e8527fed108cd2c10945f537926f/Curated-Apps/workloads/tensorflow-serving/base_image_helper/Dockerfile#L4)):*
> ```Dockerfile
> 
> COPY models/resnet ./models/resnet
> COPY models/mnist ./models/mnist
> ```

I am not entirely convinced that we should add both models at the same time. It has to be based on user preference.


<!-- Sent from Reviewable.io -->

2022-12-07 08:09 UTC, anjalirai-intel commented
*[`Curated-Apps/workloads/tensorflow-serving/README.md` line 28 at r1](https://reviewable.io/reviews/gramineproject/contrib/16#-NIfcI3e28M_9xxzXjnB:-NIfcI3fDryo5gARwOdo:bt92ac1) ([raw file](https://github.com/gramineproject/contrib/blob/a34c9ac95304e8527fed108cd2c10945f537926f/Curated-Apps/workloads/tensorflow-serving/README.md#L28)):*
> ```Markdown
>       `intel/intel-optimized-tensorflow-serving:2.9.1-ubuntu`:
> 
>           $ /bin/bash workloads/tensorflow-serving/base_image_helper/helper.sh
> ```

For other workloads, we are calling helper.sh from their respective folder. Can we do the same here as well


<!-- Sent from Reviewable.io -->

2022-12-07 23:01 UTC, mkow requested changes
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/16)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @sahason)

___
*[`Curated-Apps/workloads/tensorflow-serving/tensorflow-serving-gsc.dockerfile.template` line 6 at r1](https://reviewable.io/reviews/gramineproject/contrib/16#-NIinq-xB426irjZMQkC:-NIinq-xB426irjZMQkD:undefined) ([raw file](https://github.com/gramineproject/contrib/blob/a34c9ac95304e8527fed108cd2c10945f537926f/Curated-Apps/workloads/tensorflow-serving/tensorflow-serving-gsc.dockerfile.template#L6)):*
> ```
> 
> # The curation script fills the <base_image_name> during curation.
> From <base_image_name>
> ```





_Suggestion:_
```
FROM
```
___
*[`Curated-Apps/workloads/tensorflow-serving/base_image_helper/helper.sh` line 19 at r1](https://reviewable.io/reviews/gramineproject/contrib/16#-NIioCjY3rVITa-JVD5Y:-NIioCjY3rVITa-JVD5Z:undefined) ([raw file](https://github.com/gramineproject/contrib/blob/a34c9ac95304e8527fed108cd2c10945f537926f/Curated-Apps/workloads/tensorflow-serving/base_image_helper/helper.sh#L19)):*
> ```Shell
> if [ "$OS" == "20.04" ]
> then  
>     sed -i "1s|.*|FROM ${TF_SERVING_AZ_IMAGE_UBUNTU_20} |" workloads/tensorflow-serving/base_image_helper/Dockerfile
> ```





_Suggestion:_
```Shell
sed
```
___
*[`Curated-Apps/workloads/tensorflow-serving/base_image_helper/helper.sh` line 22 at r1](https://reviewable.io/reviews/gramineproject/contrib/16#-NIioE0A-ewUj84AvNf5:-NIioE0A-ewUj84AvNf6:undefined) ([raw file](https://github.com/gramineproject/contrib/blob/a34c9ac95304e8527fed108cd2c10945f537926f/Curated-Apps/workloads/tensorflow-serving/base_image_helper/helper.sh#L22)):*
> ```Shell
> elif [ "$OS" == "18.04" ]
> then
>     sed -i "1s|.*|FROM ${TF_SERVING_AZ_IMAGE_UBUNTU_18} |" workloads/tensorflow-serving/base_image_helper/Dockerfile
> ```





_Suggestion:_
```Shell
sed
```
___
*[`Curated-Apps/workloads/tensorflow-serving/base_image_helper/helper.sh` line 34 at r1](https://reviewable.io/reviews/gramineproject/contrib/16#-NIioKP6ACvtLCUHi6Cy:-NIioKP6ACvtLCUHi6Cz:undefined) ([raw file](https://github.com/gramineproject/contrib/blob/a34c9ac95304e8527fed108cd2c10945f537926f/Curated-Apps/workloads/tensorflow-serving/base_image_helper/helper.sh#L34)):*
> ```Shell
> fi
> mkdir -p /tmp/resnet
> curl -s http://download.tensorflow.org/models/official/20181001_resnet/savedmodels/resnet_v1_fp32_savedmodel_NCHW_jpg.tar.gz \
> ```





_Suggestion:_
```Shell
https://
```
___
*[`Curated-Apps/workloads/tensorflow-serving/base_image_helper/README.md` line 6 at r1](https://reviewable.io/reviews/gramineproject/contrib/16#-NIioYO0D1PNFLaYDDEi:-NIioYO0D1PNFLaYDDEj:bn6g6rr) ([raw file](https://github.com/gramineproject/contrib/blob/a34c9ac95304e8527fed108cd2c10945f537926f/Curated-Apps/workloads/tensorflow-serving/base_image_helper/README.md#L6)):*
> ```Markdown
> 
> - cd `contrib/Curated-Apps`
>  
> ```

trailing space


<!-- Sent from Reviewable.io -->

2022-12-09 03:51 UTC, sahason reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/16)* status: 4 of 8 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @anjalirai-intel and @mkow)

___
*[`Curated-Apps/workloads/tensorflow-serving/README.md` line 28 at r1](https://reviewable.io/reviews/gramineproject/contrib/16#-NIfcI3e28M_9xxzXjnB:-NIp-8-L87s-g0vwCtSl:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/a34c9ac95304e8527fed108cd2c10945f537926f/Curated-Apps/workloads/tensorflow-serving/README.md#L28)):*
<details><summary><i>Previously, anjalirai-intel wrote…</i></summary><blockquote>

For other workloads, we are calling helper.sh from their respective folder. Can we do the same here as well
</blockquote></details>

Done.
___
*[`Curated-Apps/workloads/tensorflow-serving/tensorflow-serving-gsc.dockerfile.template` line 6 at r1](https://reviewable.io/reviews/gramineproject/contrib/16#-NIinq-xB426irjZMQkC:-NIp-9px045G7PslP0hR:bhcb2dg) ([raw file](https://github.com/gramineproject/contrib/blob/a34c9ac95304e8527fed108cd2c10945f537926f/Curated-Apps/workloads/tensorflow-serving/tensorflow-serving-gsc.dockerfile.template#L6)):*
> ```
> 
> # The curation script fills the <base_image_name> during curation.
> From <base_image_name>
> ```

I see build failure with this change so kept the same.
___
*[`Curated-Apps/workloads/tensorflow-serving/base_image_helper/helper.sh` line 19 at r1](https://reviewable.io/reviews/gramineproject/contrib/16#-NIioCjY3rVITa-JVD5Y:-NIp-K2QERKA3YxLUd5O:b1g9rod) ([raw file](https://github.com/gramineproject/contrib/blob/a34c9ac95304e8527fed108cd2c10945f537926f/Curated-Apps/workloads/tensorflow-serving/base_image_helper/helper.sh#L19)):*
> ```Shell
> if [ "$OS" == "20.04" ]
> then  
>     sed -i "1s|.*|FROM ${TF_SERVING_AZ_IMAGE_UBUNTU_20} |" workloads/tensorflow-serving/base_image_helper/Dockerfile
> ```

Need sed -i to replace the file otherwise it does not work.
___
*[`Curated-Apps/workloads/tensorflow-serving/base_image_helper/helper.sh` line 22 at r1](https://reviewable.io/reviews/gramineproject/contrib/16#-NIioE0A-ewUj84AvNf5:-NIp-THfE1nVt5pmu0yQ:b5w4pm7) ([raw file](https://github.com/gramineproject/contrib/blob/a34c9ac95304e8527fed108cd2c10945f537926f/Curated-Apps/workloads/tensorflow-serving/base_image_helper/helper.sh#L22)):*
> Need sed -i to replace the file otherwise it does not work.
___
*[`Curated-Apps/workloads/tensorflow-serving/base_image_helper/helper.sh` line 34 at r1](https://reviewable.io/reviews/gramineproject/contrib/16#-NIioKP6ACvtLCUHi6Cy:-NIp-VX9DlhmVvGs8Hkp:boz737v) ([raw file](https://github.com/gramineproject/contrib/blob/a34c9ac95304e8527fed108cd2c10945f537926f/Curated-Apps/workloads/tensorflow-serving/base_image_helper/helper.sh#L34)):*
> ```Shell
> fi
> mkdir -p /tmp/resnet
> curl -s http://download.tensorflow.org/models/official/20181001_resnet/savedmodels/resnet_v1_fp32_savedmodel_NCHW_jpg.tar.gz \
> ```

Don't work with https
___
*[`Curated-Apps/workloads/tensorflow-serving/base_image_helper/README.md` line 6 at r1](https://reviewable.io/reviews/gramineproject/contrib/16#-NIioYO0D1PNFLaYDDEi:-NIp-aW2BEBCx1n3BnVL:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/a34c9ac95304e8527fed108cd2c10945f537926f/Curated-Apps/workloads/tensorflow-serving/base_image_helper/README.md#L6)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

trailing space
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-13 12:52 UTC, mkow requested changes
> Reviewed 2 of 4 files at r2, 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/16)* status: all files reviewed, 13 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @anjalirai-intel and @sahason)

___
*[`Curated-Apps/curate.py` line 267 at r3](https://reviewable.io/reviews/gramineproject/contrib/16#-NJAVYbD-gMCNhSU_Vy_:-NJAVYbE13pUN7UjpLPv:undefined) ([raw file](https://github.com/gramineproject/contrib/blob/50c56add07859cb34b989bb0230ce0543bb7f13c/Curated-Apps/curate.py#L267)):*
> ```Python
> 
> def get_insecure_args(workload_type):
>     args = ""
> ```





_Suggestion:_
```Python
''
```
___
*[`Curated-Apps/curate.py` line 268 at r3](https://reviewable.io/reviews/gramineproject/contrib/16#-NJAV_p266sby02GOoNB:-NJAV_p30jOjmNubNaRS:byr74vl) ([raw file](https://github.com/gramineproject/contrib/blob/50c56add07859cb34b989bb0230ce0543bb7f13c/Curated-Apps/curate.py#L268)):*
> ```Python
> def get_insecure_args(workload_type):
>     args = ""
>     insecure_args_file = "workloads/"+workload_type+"/insecure_args.txt"
> ```

please fix formatting in this whole PR
___
*[`Curated-Apps/curate.py` line 270 at r3](https://reviewable.io/reviews/gramineproject/contrib/16#-NJAVfXN8Aq0NwOnMjQ9:-NJAVfXN8Aq0NwOnMjQA:b25gv4j) ([raw file](https://github.com/gramineproject/contrib/blob/50c56add07859cb34b989bb0230ce0543bb7f13c/Curated-Apps/curate.py#L270)):*
> ```Python
>     insecure_args_file = "workloads/"+workload_type+"/insecure_args.txt"
> 
>     if os.path.exists(insecure_args_file):
> ```

You should try-except instead, current way is racy.
___
*[`Curated-Apps/curate.py` line 273 at r3](https://reviewable.io/reviews/gramineproject/contrib/16#-NJAVsfI5AgCycb7ZbIr:-NJAVsfI5AgCycb7ZbIs:b-d39h5f) ([raw file](https://github.com/gramineproject/contrib/blob/50c56add07859cb34b989bb0230ce0543bb7f13c/Curated-Apps/curate.py#L273)):*
> ```Python
>         with open(insecure_args_file, 'r') as pfile:
>             for line in pfile:
>                 if not line.startswith("#"):
> ```

What if someone wants to pass an argument starting with `#`?
___
*[`Curated-Apps/workloads/tensorflow-serving/insecure_args.txt` line 1 at r3](https://reviewable.io/reviews/gramineproject/contrib/16#-NJAW9CZ4oWkYjO1fkUT:-NJAW9CZ4oWkYjO1fkUU:undefined) ([raw file](https://github.com/gramineproject/contrib/blob/50c56add07859cb34b989bb0230ce0543bb7f13c/Curated-Apps/workloads/tensorflow-serving/insecure_args.txt#L1)):*
> ```help
> # At a time only one model can be enabled. Resnet is enabled by default as shown below.
> ```





_Suggestion:_
```help
ResNet
```
___
*[`Curated-Apps/workloads/tensorflow-serving/README.md` line 34 at r3](https://reviewable.io/reviews/gramineproject/contrib/16#-NJAWPUZ75LHzvxHO9U8:-NJAWPUZ75LHzvxHO9U9:undefined) ([raw file](https://github.com/gramineproject/contrib/blob/50c56add07859cb34b989bb0230ce0543bb7f13c/Curated-Apps/workloads/tensorflow-serving/README.md#L34)):*
> ```Markdown
> 
>     2. Generate the test confidential compute image based on the `tf-serving-base` image as shown
>        below. By default, resnet is enabled. To enable other models one can uncomment
> ```





_Suggestion:_
```Markdown
ResNet
```
___
*[`Curated-Apps/workloads/tensorflow-serving/tensorflow-serving-gsc.dockerfile.template` line 6 at r1](https://reviewable.io/reviews/gramineproject/contrib/16#-NIinq-xB426irjZMQkC:-NJAWUGd2X_EGOKvnzrv:bhd5kam) ([raw file](https://github.com/gramineproject/contrib/blob/a34c9ac95304e8527fed108cd2c10945f537926f/Curated-Apps/workloads/tensorflow-serving/tensorflow-serving-gsc.dockerfile.template#L6)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

I see build failure with this change so kept the same.
</blockquote></details>

Then debug and fix that failure.
___
*[`Curated-Apps/workloads/tensorflow-serving/base_image_helper/helper.sh` line 19 at r1](https://reviewable.io/reviews/gramineproject/contrib/16#-NIioCjY3rVITa-JVD5Y:-NJAWk3z20Q94D6ZX0-4:b-n1uc9g) ([raw file](https://github.com/gramineproject/contrib/blob/a34c9ac95304e8527fed108cd2c10945f537926f/Curated-Apps/workloads/tensorflow-serving/base_image_helper/helper.sh#L19)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

Need sed -i to replace the file otherwise it does not work.
</blockquote></details>

Again: then fix the original bug instead of doing random workarounds until it works.
___
*[`Curated-Apps/workloads/tensorflow-serving/base_image_helper/helper.sh` line 22 at r1](https://reviewable.io/reviews/gramineproject/contrib/16#-NIioE0A-ewUj84AvNf5:-NJAX5Ld4t0RIDt39DTw:b-7ropln) ([raw file](https://github.com/gramineproject/contrib/blob/a34c9ac95304e8527fed108cd2c10945f537926f/Curated-Apps/workloads/tensorflow-serving/base_image_helper/helper.sh#L22)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

> Need sed -i to replace the file otherwise it does not work.
</blockquote></details>

ditto
___
*[`Curated-Apps/workloads/tensorflow-serving/base_image_helper/helper.sh` line 34 at r1](https://reviewable.io/reviews/gramineproject/contrib/16#-NIioKP6ACvtLCUHi6Cy:-NJAXEJP-re-IMdeu6ya:btmfcjt) ([raw file](https://github.com/gramineproject/contrib/blob/a34c9ac95304e8527fed108cd2c10945f537926f/Curated-Apps/workloads/tensorflow-serving/base_image_helper/helper.sh#L34)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

Don't work with https
</blockquote></details>

In this case you need to verify its hash after downloading. You can't download code over unencrypted connection and then just execute it.
___
*[`Curated-Apps/workloads/tensorflow-serving/base_image_helper/helper.sh` line 61 at r3](https://reviewable.io/reviews/gramineproject/contrib/16#-NJAXZfg1-Wm4rjH31HR:-NJAXZfg1-Wm4rjH31HS:b-jzdo0d) ([raw file](https://github.com/gramineproject/contrib/blob/50c56add07859cb34b989bb0230ce0543bb7f13c/Curated-Apps/workloads/tensorflow-serving/base_image_helper/helper.sh#L61)):*
> ```Shell
>     -t ${TF_SERVING_IMAGE_FINAL} .
> 
> cd $CUR_DIR
> ```

Why not `pushd`+`popd`?


<!-- Sent from Reviewable.io -->

2022-12-13 14:47 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/16)* status: all files reviewed, 14 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @anjalirai-intel and @sahason)

___
*[`Curated-Apps/workloads/tensorflow-serving/base_image_helper/helper.sh` line 19 at r1](https://reviewable.io/reviews/gramineproject/contrib/16#-NIioCjY3rVITa-JVD5Y:-NJAwjNe7rk0a9oBsS3N:b-acnosd) ([raw file](https://github.com/gramineproject/contrib/blob/a34c9ac95304e8527fed108cd2c10945f537926f/Curated-Apps/workloads/tensorflow-serving/base_image_helper/helper.sh#L19)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Again: then fix the original bug instead of doing random workarounds until it works.
</blockquote></details>

Ah, I see what is happening here. Why are you replacing this file in-place? It will break if you call the script with `18.04` but then would want to switch to `20.04`?
___
*[`Curated-Apps/workloads/tensorflow-serving/base_image_helper/helper.sh` line 21 at r3](https://reviewable.io/reviews/gramineproject/contrib/16#-NJAwbOp3NTxk30F7lUJ:-NJAwbOp3NTxk30F7lUK:b-49p22e) ([raw file](https://github.com/gramineproject/contrib/blob/50c56add07859cb34b989bb0230ce0543bb7f13c/Curated-Apps/workloads/tensorflow-serving/base_image_helper/helper.sh#L21)):*
> ```Shell
> OS=$1
> if [ "$OS" == "20.04" ]
> then  
> ```

Trailing blanks. Please fix in the whole PR.


<!-- Sent from Reviewable.io -->

2022-12-13 17:19 UTC, sahason reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/16)* status: all files reviewed, 14 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @anjalirai-intel and @mkow)

___
*[`Curated-Apps/curate.py` line 267 at r3](https://reviewable.io/reviews/gramineproject/contrib/16#-NJAVYbD-gMCNhSU_Vy_:-NJAqMem3O6vEGu1SREB:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/50c56add07859cb34b989bb0230ce0543bb7f13c/Curated-Apps/curate.py#L267)):*
> ```Python
> 
> def get_insecure_args(workload_type):
>     args = ""
> ```

Done.
___
*[`Curated-Apps/curate.py` line 268 at r3](https://reviewable.io/reviews/gramineproject/contrib/16#-NJAV_p266sby02GOoNB:-NJAqLrb1TBiwN7YZ3b6:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/50c56add07859cb34b989bb0230ce0543bb7f13c/Curated-Apps/curate.py#L268)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

please fix formatting in this whole PR
</blockquote></details>

Done.
___
*[`Curated-Apps/curate.py` line 270 at r3](https://reviewable.io/reviews/gramineproject/contrib/16#-NJAVfXN8Aq0NwOnMjQ9:-NJBO0J6BZ9qpqSmZZ6E:bjsabrw) ([raw file](https://github.com/gramineproject/contrib/blob/50c56add07859cb34b989bb0230ce0543bb7f13c/Curated-Apps/curate.py#L270)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

You should try-except instead, current way is racy.
</blockquote></details>

I have not added `os.path.exists(insecure_args_file):` inside try-except. The reason behind this is to make this logic generic. As of now, only tensorflow-serving has insecure_args file. So if I put try catch for this line other workloads will fail as it will raise an exception.
But I have put  `with open(insecure_args_file, 'r')as pfile: ` inside try-except to address the race condition.
___
*[`Curated-Apps/curate.py` line 273 at r3](https://reviewable.io/reviews/gramineproject/contrib/16#-NJAVsfI5AgCycb7ZbIr:-NJAoiib5w3s3RtDkbr5:b-l9t1a9) ([raw file](https://github.com/gramineproject/contrib/blob/50c56add07859cb34b989bb0230ce0543bb7f13c/Curated-Apps/curate.py#L273)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What if someone wants to pass an argument starting with `#`?
</blockquote></details>

The insecure_args.txt file is already preconfigured with the command line arguments for different models.  Hence there is no scope for passing arguments starting with #. Moreover, each argument begins with '--'.
___
*[`Curated-Apps/workloads/tensorflow-serving/insecure_args.txt` line 1 at r3](https://reviewable.io/reviews/gramineproject/contrib/16#-NJAW9CZ4oWkYjO1fkUT:-NJAf7q18gqyoF5lav4c:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/50c56add07859cb34b989bb0230ce0543bb7f13c/Curated-Apps/workloads/tensorflow-serving/insecure_args.txt#L1)):*
> ```help
> # At a time only one model can be enabled. Resnet is enabled by default as shown below.
> ```

Done.
___
*[`Curated-Apps/workloads/tensorflow-serving/README.md` line 34 at r3](https://reviewable.io/reviews/gramineproject/contrib/16#-NJAWPUZ75LHzvxHO9U8:-NJAfKWfDVTjrHmDnr3N:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/50c56add07859cb34b989bb0230ce0543bb7f13c/Curated-Apps/workloads/tensorflow-serving/README.md#L34)):*
> ```Markdown
> 
>     2. Generate the test confidential compute image based on the `tf-serving-base` image as shown
>        below. By default, resnet is enabled. To enable other models one can uncomment
> ```

Done.
___
*[`Curated-Apps/workloads/tensorflow-serving/tensorflow-serving-gsc.dockerfile.template` line 6 at r1](https://reviewable.io/reviews/gramineproject/contrib/16#-NIinq-xB426irjZMQkC:-NJAfMXp8qwIi3kYtMyt:b-p87hpp) ([raw file](https://github.com/gramineproject/contrib/blob/a34c9ac95304e8527fed108cd2c10945f537926f/Curated-Apps/workloads/tensorflow-serving/tensorflow-serving-gsc.dockerfile.template#L6)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Then debug and fix that failure.
</blockquote></details>

This PR needs to be rebased then this will work. I will rebase and apply this change once  https://github.com/gramineproject/contrib/pull/21 is merged.
___
*[`Curated-Apps/workloads/tensorflow-serving/base_image_helper/helper.sh` line 19 at r1](https://reviewable.io/reviews/gramineproject/contrib/16#-NIioCjY3rVITa-JVD5Y:-NJAvqXrDM4mQkn3fvEw:b-g2gktx) ([raw file](https://github.com/gramineproject/contrib/blob/a34c9ac95304e8527fed108cd2c10945f537926f/Curated-Apps/workloads/tensorflow-serving/base_image_helper/helper.sh#L19)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Ah, I see what is happening here. Why are you replacing this file in-place? It will break if you call the script with `18.04` but then would want to switch to `20.04`?
</blockquote></details>

It will not break at it replaces the content of whole line.
___
*[`Curated-Apps/workloads/tensorflow-serving/base_image_helper/helper.sh` line 22 at r1](https://reviewable.io/reviews/gramineproject/contrib/16#-NIioE0A-ewUj84AvNf5:-NJAw_5D1Hs_muD3Ere6:b-7ropln) ([raw file](https://github.com/gramineproject/contrib/blob/a34c9ac95304e8527fed108cd2c10945f537926f/Curated-Apps/workloads/tensorflow-serving/base_image_helper/helper.sh#L22)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

ditto
___
*[`Curated-Apps/workloads/tensorflow-serving/base_image_helper/helper.sh` line 34 at r1](https://reviewable.io/reviews/gramineproject/contrib/16#-NIioKP6ACvtLCUHi6Cy:-NIpVCuf6AKeu6dQE-4V:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/a34c9ac95304e8527fed108cd2c10945f537926f/Curated-Apps/workloads/tensorflow-serving/base_image_helper/helper.sh#L34)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

In this case you need to verify its hash after downloading. You can't download code over unencrypted connection and then just execute it.
</blockquote></details>

Done.
___
*[`Curated-Apps/workloads/tensorflow-serving/base_image_helper/helper.sh` line 21 at r3](https://reviewable.io/reviews/gramineproject/contrib/16#-NJAwbOp3NTxk30F7lUJ:-NJBQI9VEG5W74sHTDry:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/50c56add07859cb34b989bb0230ce0543bb7f13c/Curated-Apps/workloads/tensorflow-serving/base_image_helper/helper.sh#L21)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Trailing blanks. Please fix in the whole PR.
</blockquote></details>

Done.
___
*[`Curated-Apps/workloads/tensorflow-serving/base_image_helper/helper.sh` line 61 at r3](https://reviewable.io/reviews/gramineproject/contrib/16#-NJAXZfg1-Wm4rjH31HR:-NJAihvm9Ms1A2ySaIZl:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/50c56add07859cb34b989bb0230ce0543bb7f13c/Curated-Apps/workloads/tensorflow-serving/base_image_helper/helper.sh#L61)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why not `pushd`+`popd`?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-13 18:46 UTC, mkow requested changes
> Reviewed 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/16)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @anjalirai-intel and @sahason)

___
*[`Curated-Apps/curate.py` line 268 at r3](https://reviewable.io/reviews/gramineproject/contrib/16#-NJAV_p266sby02GOoNB:-NJBjfyEBoNmlaSCa85P:bfhqml6) ([raw file](https://github.com/gramineproject/contrib/blob/50c56add07859cb34b989bb0230ce0543bb7f13c/Curated-Apps/curate.py#L268)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done.
___
*[`Curated-Apps/curate.py` line 270 at r3](https://reviewable.io/reviews/gramineproject/contrib/16#-NJAVfXN8Aq0NwOnMjQ9:-NJBkHLk0g8HTmeDYdrp:bl7owgh) ([raw file](https://github.com/gramineproject/contrib/blob/50c56add07859cb34b989bb0230ce0543bb7f13c/Curated-Apps/curate.py#L270)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

I have not added `os.path.exists(insecure_args_file):` inside try-except. The reason behind this is to make this logic generic. As of now, only tensorflow-serving has insecure_args file. So if I put try catch for this line other workloads will fail as it will raise an exception.
But I have put  `with open(insecure_args_file, 'r')as pfile: ` inside try-except to address the race condition.
</blockquote></details>

I don't understand what you mean, but the change you made makes no sense. Please read more about Python and its conventions + some guidelines.
___
*[`Curated-Apps/curate.py` line 273 at r3](https://reviewable.io/reviews/gramineproject/contrib/16#-NJAVsfI5AgCycb7ZbIr:-NJBkVwWD2T-a5ceIwRE:bn23g0m) ([raw file](https://github.com/gramineproject/contrib/blob/50c56add07859cb34b989bb0230ce0543bb7f13c/Curated-Apps/curate.py#L273)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

The insecure_args.txt file is already preconfigured with the command line arguments for different models.  Hence there is no scope for passing arguments starting with #. Moreover, each argument begins with '--'.
</blockquote></details>

But you didn't make this change in a workload-specific code, now every workload we'll ever want to curate will silently drop such arguments.
___
*[`Curated-Apps/workloads/tensorflow-serving/base_image_helper/.gitignore` line 4 at r4](https://reviewable.io/reviews/gramineproject/contrib/16#-NJBlIo31nEVsBbbFWxw:-NJBlIo31nEVsBbbFWxx:b-1m9ux7) ([raw file](https://github.com/gramineproject/contrib/blob/392af0ee4dbffd8fa72d1db9da3270c54337d0b5/Curated-Apps/workloads/tensorflow-serving/base_image_helper/.gitignore#L4)):*
> ```ignore
> /serving
> /resnet_v1_fp32_savedmodel_NCHW_jpg.tar.gz
> /check_sum_resnet.txt
> ```

missing newline
___
*[`Curated-Apps/workloads/tensorflow-serving/base_image_helper/.gitignore` line 4 at r4](https://reviewable.io/reviews/gramineproject/contrib/16#-NJBlM43DjIMFDc3Lc3X:-NJBlM43DjIMFDc3Lc3Y:undefined) ([raw file](https://github.com/gramineproject/contrib/blob/392af0ee4dbffd8fa72d1db9da3270c54337d0b5/Curated-Apps/workloads/tensorflow-serving/base_image_helper/.gitignore#L4)):*
> ```ignore
> /serving
> /resnet_v1_fp32_savedmodel_NCHW_jpg.tar.gz
> /check_sum_resnet.txt
> ```





_Suggestion:_
```ignore
hash
```
___
*[`Curated-Apps/workloads/tensorflow-serving/base_image_helper/helper.sh` line 19 at r1](https://reviewable.io/reviews/gramineproject/contrib/16#-NIioCjY3rVITa-JVD5Y:-NJBl_dN-MyRLlOxLP1k:b4zk2a) ([raw file](https://github.com/gramineproject/contrib/blob/a34c9ac95304e8527fed108cd2c10945f537926f/Curated-Apps/workloads/tensorflow-serving/base_image_helper/helper.sh#L19)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

It will not break at it replaces the content of whole line.
</blockquote></details>

Oh, wait, this is always replacing the fourth line in the script, regardless of its contents? Please don't, imagine someone changing this script someday... This is too terrible even for `contrib` repo.


<!-- Sent from Reviewable.io -->

2022-12-14 12:23 UTC, sahason reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/16)* status: 5 of 10 files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @anjalirai-intel and @mkow)

___
*[`Curated-Apps/curate.py` line 268 at r3](https://reviewable.io/reviews/gramineproject/contrib/16#-NJAV_p266sby02GOoNB:-NJEGczqD2yspbgzUKmA:bh735so) ([raw file](https://github.com/gramineproject/contrib/blob/50c56add07859cb34b989bb0230ce0543bb7f13c/Curated-Apps/curate.py#L268)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Not done.
</blockquote></details>

Done. In case I missed anything please let me know.
___
*[`Curated-Apps/curate.py` line 270 at r3](https://reviewable.io/reviews/gramineproject/contrib/16#-NJAVfXN8Aq0NwOnMjQ9:-NJEeDup7SCRmc6jqTXD:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/50c56add07859cb34b989bb0230ce0543bb7f13c/Curated-Apps/curate.py#L270)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I don't understand what you mean, but the change you made makes no sense. Please read more about Python and its conventions + some guidelines.
</blockquote></details>

Done.
___
*[`Curated-Apps/curate.py` line 273 at r3](https://reviewable.io/reviews/gramineproject/contrib/16#-NJAVsfI5AgCycb7ZbIr:-NJE-Y-8AmsXu9vzLlgP:bx9ora3) ([raw file](https://github.com/gramineproject/contrib/blob/50c56add07859cb34b989bb0230ce0543bb7f13c/Curated-Apps/curate.py#L273)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

But you didn't make this change in a workload-specific code, now every workload we'll ever want to curate will silently drop such arguments.
</blockquote></details>

Changed the functionality. By default, ResNet is enabled. The user is expected to modify `model_name` and `model_base_path` based on the model they want to run.
___
*[`Curated-Apps/workloads/tensorflow-serving/base_image_helper/.gitignore` line 4 at r4](https://reviewable.io/reviews/gramineproject/contrib/16#-NJBlIo31nEVsBbbFWxw:-NJE2yHC33gz4nq0_rrC:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/392af0ee4dbffd8fa72d1db9da3270c54337d0b5/Curated-Apps/workloads/tensorflow-serving/base_image_helper/.gitignore#L4)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

missing newline
</blockquote></details>

Done.
___
*[`Curated-Apps/workloads/tensorflow-serving/base_image_helper/.gitignore` line 4 at r4](https://reviewable.io/reviews/gramineproject/contrib/16#-NJBlM43DjIMFDc3Lc3X:-NJE3MgB1poXHNgsSCnX:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/392af0ee4dbffd8fa72d1db9da3270c54337d0b5/Curated-Apps/workloads/tensorflow-serving/base_image_helper/.gitignore#L4)):*
> ```ignore
> /serving
> /resnet_v1_fp32_savedmodel_NCHW_jpg.tar.gz
> /check_sum_resnet.txt
> ```

Done.
___
*[`Curated-Apps/workloads/tensorflow-serving/base_image_helper/helper.sh` line 19 at r1](https://reviewable.io/reviews/gramineproject/contrib/16#-NIioCjY3rVITa-JVD5Y:-NJE7aM65xaFZDsCCcil:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/a34c9ac95304e8527fed108cd2c10945f537926f/Curated-Apps/workloads/tensorflow-serving/base_image_helper/helper.sh#L19)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Oh, wait, this is always replacing the fourth line in the script, regardless of its contents? Please don't, imagine someone changing this script someday... This is too terrible even for `contrib` repo.
</blockquote></details>

Done.
___
*[`Curated-Apps/workloads/tensorflow-serving/base_image_helper/helper.sh` line 22 at r1](https://reviewable.io/reviews/gramineproject/contrib/16#-NIioE0A-ewUj84AvNf5:-NJE7WrEAycn414iAjt2:bb6un1j) ([raw file](https://github.com/gramineproject/contrib/blob/a34c9ac95304e8527fed108cd2c10945f537926f/Curated-Apps/workloads/tensorflow-serving/base_image_helper/helper.sh#L22)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-12-16 16:34 UTC, mkow requested changes
> Reviewed 4 of 5 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/16)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @anjalirai-intel and @sahason)

___
*[`Curated-Apps/workloads/tensorflow-serving/base_image_helper/helper.sh` line 19 at r1](https://reviewable.io/reviews/gramineproject/contrib/16#-NIioCjY3rVITa-JVD5Y:-NJQm67Z9nTWNlGELRH8:bzhwwoh) ([raw file](https://github.com/gramineproject/contrib/blob/a34c9ac95304e8527fed108cd2c10945f537926f/Curated-Apps/workloads/tensorflow-serving/base_image_helper/helper.sh#L19)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Please match the whole line exactly, now you replace also normal FROMs which the writer wouldn't expect to get replaced.


<!-- Sent from Reviewable.io -->

2022-12-17 03:19 UTC, svenkata9 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/16)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @anjalirai-intel, @mkow, and @sahason)

___
*[`Curated-Apps/workloads/tensorflow-serving/base_image_helper/helper.sh` line 19 at r1](https://reviewable.io/reviews/gramineproject/contrib/16#-NIioCjY3rVITa-JVD5Y:-NJT4E5D50t75t3l2JaJ:b995ez7) ([raw file](https://github.com/gramineproject/contrib/blob/a34c9ac95304e8527fed108cd2c10945f537926f/Curated-Apps/workloads/tensorflow-serving/base_image_helper/helper.sh#L19)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please match the whole line exactly, now you replace also normal FROMs which the writer wouldn't expect to get replaced.
</blockquote></details>

Michal, Sonali can make the change that you are suggesting, but I don't understand the issue that you are referring to. This is a custom dockerfile as part of the workload directory, specific to Tensorflow and there is only one FROM in this Dockerfile. This is custom one. If someone adds another FROM, it is not guaranteed to work because we have not validated it.


<!-- Sent from Reviewable.io -->

2022-12-17 03:27 UTC, sahason reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/16)* status: 9 of 10 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @anjalirai-intel and @mkow)

___
*[`Curated-Apps/workloads/tensorflow-serving/base_image_helper/helper.sh` line 19 at r1](https://reviewable.io/reviews/gramineproject/contrib/16#-NIioCjY3rVITa-JVD5Y:-NJT6bfsEFH3kizxogtP:b-yxvt6u) ([raw file](https://github.com/gramineproject/contrib/blob/a34c9ac95304e8527fed108cd2c10945f537926f/Curated-Apps/workloads/tensorflow-serving/base_image_helper/helper.sh#L19)):*
<details><summary><i>Previously, svenkata9 (Sankaranarayanan Venkatasubramanian) wrote…</i></summary><blockquote>

Michal, Sonali can make the change that you are suggesting, but I don't understand the issue that you are referring to. This is a custom dockerfile as part of the workload directory, specific to Tensorflow and there is only one FROM in this Dockerfile. This is custom one. If someone adds another FROM, it is not guaranteed to work because we have not validated it.
</blockquote></details>

I have made changes.


<!-- Sent from Reviewable.io -->

2022-12-17 19:59 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/16)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @anjalirai-intel and @sahason)

___
*[`Curated-Apps/workloads/tensorflow-serving/base_image_helper/helper.sh` line 19 at r1](https://reviewable.io/reviews/gramineproject/contrib/16#-NIioCjY3rVITa-JVD5Y:-NJWcpc1EANjPeNROCOf:b-b1ge9n) ([raw file](https://github.com/gramineproject/contrib/blob/a34c9ac95304e8527fed108cd2c10945f537926f/Curated-Apps/workloads/tensorflow-serving/base_image_helper/helper.sh#L19)):*
> there is only one FROM in this Dockerfile

> This is custom one. If someone adds another FROM, it is not guaranteed to work because we have not validated it.

You could say the same about any other quick hack - you just wrote/reviewed it recently, so you _now_ understand well what happens here. It will be quite confusing if you started to change this example next year, or some user would try to modify it.

Also, this whole idea with in-place templating is really bad, because of such problems. You should have a template file and produce the final one with added changes which has a different name, but I won't block on this, because it's not an official part of Gramine.


<!-- Sent from Reviewable.io -->

2022-12-21 15:30 UTC, sahason reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/16)* status: 6 of 10 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @anjalirai-intel and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/16#-NJpGykU4JgIjuUAv-5d:-NJpGykU4JgIjuUAv-5e:b-uaaq58) (no related file):*
This version of the tensorflow-serving curated app will support only 18.04. I have updated the PR accordingly. Please review.

___


<!-- Sent from Reviewable.io -->

2022-12-23 02:57 UTC, mkow requested changes
> Reviewed 4 of 4 files at r8, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/16)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @anjalirai-intel and @sahason)

___
*[`-- commits` line 2 at r9](https://reviewable.io/reviews/gramineproject/contrib/16#-NJwtdmsAEqB8ZJqUsO8):*
wrong component tag



_Code quote:_
```
[Curated-App]
```


<!-- Sent from Reviewable.io -->

2022-12-23 03:05 UTC, sahason reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/16)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @anjalirai-intel and @mkow)

___
*[`-- commits` line 2 at r9](https://reviewable.io/reviews/gramineproject/contrib/16#-NJwtdmsAEqB8ZJqUsO8):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

wrong component tag
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-23 20:26 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/16)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @anjalirai-intel and @sahason)



<!-- Sent from Reviewable.io -->

2022-12-24 03:29 UTC, svenkata9 reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/16)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @anjalirai-intel and @sahason)



<!-- Sent from Reviewable.io -->

2022-12-24 03:34 UTC, svenkata9 approved these changes

2022-12-24 03:36 UTC, svenkata9 reviewed
> Reviewed 1 of 8 files at r3, 1 of 8 files at r4, 2 of 5 files at r5, 4 of 4 files at r8, 2 of 2 files at r9.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/16)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @anjalirai-intel)



<!-- Sent from Reviewable.io -->

2022-12-24 04:30 UTC, anjalirai-intel reviewed
> Reviewed 1 of 8 files at r3, 1 of 8 files at r4, 2 of 5 files at r5, 4 of 4 files at r8, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/16)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2022-12-24 21:05 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/16)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-12-24 21:07 UTC, merged