[Curation] Support command-line args in non-production case
gramineproject/contrib pull request #18
Opened 2022-12-08 17:02 UTC by jkr0103

Current implementation missing support for command line arguments while generating non-production GSC image. This PR add support for command-line arguments.

2022-12-09 13:02 UTC, mkow requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/18)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @jkr0103)

___
*[`Curated-Apps/util/curation_script.sh` line 85 at r1](https://reviewable.io/reviews/gramineproject/contrib/18#-NIqyN1v0G6zVFcz45nB:-NIqyN1v0G6zVFcz45nC:b204qjl) ([raw file](https://github.com/gramineproject/contrib/blob/d847cce2ebe9a4026eadcbad7b552f17d78fddc0/Curated-Apps/util/curation_script.sh#L85)):*
> ```Shell
> }
> 
> cmdline_flag=""
> ```

please fix formatting
___
*[`Curated-Apps/util/curation_script.sh` line 140 at r1](https://reviewable.io/reviews/gramineproject/contrib/18#-NIqyOzH6hf2D4soFaQx:-NIqyOzH6hf2D4soFaQy:b-7ropln) ([raw file](https://github.com/gramineproject/contrib/blob/d847cce2ebe9a4026eadcbad7b552f17d78fddc0/Curated-Apps/util/curation_script.sh#L140)):*
> ```Shell
> read -r signing_input signing_key_path <<<$(echo "$4 $4")
> if [ "$signing_input" = "test" ]; then
>     cmdline_flag="--insecure-args"
> ```

ditto
___
*[`Curated-Apps/util/curation_script.sh` line 177 at r1](https://reviewable.io/reviews/gramineproject/contrib/18#-NIqyPi219v_-n6IWpwA:-NIqyPi219v_-n6IWpwB:b-7ropln) ([raw file](https://github.com/gramineproject/contrib/blob/d847cce2ebe9a4026eadcbad7b552f17d78fddc0/Curated-Apps/util/curation_script.sh#L177)):*
> ```Shell
> # Test image creation
> if [ "$6" = "test-image" ]; then
>     cmdline_flag="--insecure-args"
> ```

ditto


<!-- Sent from Reviewable.io -->

2022-12-09 14:43 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/18)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow)

___
*[`Curated-Apps/util/curation_script.sh` line 85 at r1](https://reviewable.io/reviews/gramineproject/contrib/18#-NIqyN1v0G6zVFcz45nB:-NIrKSHl3gM1ckT11vCU:b-ilge9x) ([raw file](https://github.com/gramineproject/contrib/blob/d847cce2ebe9a4026eadcbad7b552f17d78fddc0/Curated-Apps/util/curation_script.sh#L85)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

please fix formatting
</blockquote></details>

I did not get it. Do you mean space before and after `=`. Space before and after `=` doesn't work in bash script.


<!-- Sent from Reviewable.io -->

2022-12-10 00:46 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/18)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[`Curated-Apps/util/curation_script.sh` line 85 at r1](https://reviewable.io/reviews/gramineproject/contrib/18#-NIqyN1v0G6zVFcz45nB:-NItU_So-iMIA4go3ETW:bus70l1) ([raw file](https://github.com/gramineproject/contrib/blob/d847cce2ebe9a4026eadcbad7b552f17d78fddc0/Curated-Apps/util/curation_script.sh#L85)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

I did not get it. Do you mean space before and after `=`. Space before and after `=` doesn't work in bash script.
</blockquote></details>

Oops, sorry, brainlag on my side.


<!-- Sent from Reviewable.io -->

2022-12-10 17:55 UTC, dimakuv approved these changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/18)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-12-10 17:57 UTC, merged