[Curated-Apps] Fix Redis regression issue caused by commit `d847cce`
gramineproject/contrib pull request #21
Opened 2022-12-12 13:44 UTC by jkr0103

Redis run fails with below error, with commit `d847cce` which supported supplying command-line arguments.

```Error Produced:
*** FATAL CONFIG FILE ERROR (Redis 7.0.5) ***
Reading the configuration file, at line 3
>>> 'save "" ""'
Invalid save parameters
```
In case of Redis, we hardcode the arguments `--protected-mode no --save` and accepting commandline arguments in `"${@}"` . If there are no arguments, it results in producing double quotes `""` which become invalid parameter for redis. removing `""` around `${@}` fixes the issue.

2022-12-12 18:10 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/21)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/21#-NJ5sEqL9vMn_BtoRRWy:-NJ6TkekAcwvGPuzklu2:bgnwqme) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

The change is incorrect, quoting marks around `"$@"` are necessary in shell (in fact, it's the only correct usage).

The problem is somewhere else. If you run the "curated" container directly (without gramine and gdc), the script runs correctly without arguments. I've run `./curate.py redis redis:7.0.0 test` as per `README.md`, then:

```
% docker build -f redis-gsc.dockerfile .
Sending build context to Docker daemon  258.6kB
Step 1/3 : FROM redis:7.0.0
 ---> 53aa81e8adfa
Step 2/3 : COPY entry_script_redis.sh /usr/local/bin/entry_script_redis.sh
 ---> Using cache
 ---> 9d21b2c84ce7
Step 3/3 : ENTRYPOINT ["/bin/bash", "/usr/local/bin/entry_script_redis.sh"]
 ---> Using cache
 ---> ec891c141b70
Successfully built ec891c141b70
% docker run -it ec891c141b70
8:C 12 Dec 2022 15:07:32.887 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
8:C 12 Dec 2022 15:07:32.887 # Redis version=7.0.0, bits=64, commit=00000000, modified=0, pid=8, just started
8:C 12 Dec 2022 15:07:32.887 # Configuration loaded
8:M 12 Dec 2022 15:07:32.887 * monotonic clock: POSIX clock_gettime
                _._                                                  
           _.-``__ ''-._                                             
      _.-``    `.  `_.  ''-._           Redis 7.0.0 (00000000/0) 64 bit
  .-`` .-```.  ```\/    _.,_ ''-._                                  
 (    '      ,       .-`  | `,    )     Running in standalone mode
 |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
 |    `-._   `._    /     _.-'    |     PID: 8
  `-._    `-._  `-./  _.-'    _.-'                                   
 |`-._`-._    `-.__.-'    _.-'_.-'|                                  
 |    `-._`-._        _.-'_.-'    |           https://redis.io       
  `-._    `-._`-.__.-'_.-'    _.-'                                   
 |`-._`-._    `-.__.-'    _.-'_.-'|                                  
 |    `-._`-._        _.-'_.-'    |                                  
  `-._    `-._`-.__.-'_.-'    _.-'                                   
      `-._    `-.__.-'    _.-'                                       
          `-._        _.-'                                           
              `-.__.-'                                               

8:M 12 Dec 2022 15:07:32.888 # Server initialized
8:M 12 Dec 2022 15:07:32.888 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
8:M 12 Dec 2022 15:07:32.888 * The AOF directory appendonlydir doesn't exist
8:M 12 Dec 2022 15:07:32.888 * Ready to accept connections
^C8:signal-handler (1670857655) Received SIGINT scheduling shutdown...
8:M 12 Dec 2022 15:07:35.403 # User requested shutdown...
8:M 12 Dec 2022 15:07:35.403 # Redis is now ready to exit, bye bye...
```

IDK where did you get that empty argument from.
</blockquote></details>

For performance reasons we add arguments ` --protected-mode no --save ''` to `docker run` command while executing in gramine.

Workflow: we retrieve entrypoints and mandatory args (` --protected-mode no --save ''` in case of redis)`and create`entry_script_<workload_name>.sh` using these parameters which become entrypoint of a wrapper image we create on top of base image. In case of redis contents of this file are `"docker-entrypoint.sh" --protected-mode no --save '' "${@}"` and if no arguments supplied, it becomes `"docker-entrypoint.sh" --protected-mode no --save '' ""`. This is the issue.

You can try below command with the same image you tried above, it should give same issue:
`docker run -it ec891c141b70 --protected-mode no --save '' ""`

___


<!-- Sent from Reviewable.io -->

2022-12-12 18:45 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/21)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @jkr0103)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/21#-NJ5sEqL9vMn_BtoRRWy:-NJ6dglB1aGE6PjP477C:bjwnkod) (no related file):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

Found the issue, it's in GSC.
GSC generates `Docker.build` which have below two lines:

# Define default command
ENTRYPOINT ["/bin/bash", "/gramine/app_files/apploader.sh"]
CMD [ "" ]

`apploader.sh passes `""` to `entry_scrpit_redis.sh`.

so GSC shouldn't add `CMD[""]` if it's empty.
</blockquote></details>

Fix:
{% if cmd %}
CMD [{% if insecure_args %} "{{'", "'.join(cmd)}}" {% endif %}]
{% endif %}

should go in

https://github.com/gramineproject/gsc/blob/dbc17b6a118d0fb13411d3acd1f1dfc032b77b83/templates/Dockerfile.common.build.template#L64

___


<!-- Sent from Reviewable.io -->

2022-12-13 12:02 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/21)* status: 0 of 1 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners

___
*[`Curated-Apps/util/curation_script.sh` line 93 at r2](https://reviewable.io/reviews/gramineproject/contrib/21#-NJALOoI0fowBo8-PUBJ:-NJALOoI0fowBo8-PUBK:bvefrnt) ([raw file](https://github.com/gramineproject/contrib/blob/1129dee5582deef5dd3c71040e843bfe6f249a57/Curated-Apps/util/curation_script.sh#L93)):*
> ```Shell
>     cp $signing_key_path gsc/enclave-key.pem
> 
>     # This is a temporary fix for the issue described in PR #21 and will be removed once fix is
> ```

As described in the comment section, this is a temporary fix and actual fix has to go in GSC repo and can be used after v1.4 release. Hence we will remove this change when we update the branch info in `git clone` line above.


<!-- Sent from Reviewable.io -->

2022-12-13 14:27 UTC, woju requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/21)* status: 0 of 1 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @jkr0103)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/21#-NJ5sEqL9vMn_BtoRRWy:-NJAreZYBjaLbOeExeys:b-5452is) (no related file):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

Fix:
{% if cmd %}
CMD [{% if insecure_args %} "{{'", "'.join(cmd)}}" {% endif %}]
{% endif %}

should go in

https://github.com/gramineproject/gsc/blob/dbc17b6a118d0fb13411d3acd1f1dfc032b77b83/templates/Dockerfile.common.build.template#L64



</blockquote></details>

Nope, that should have been `', '.join(repr(i) for i in cmd)`, without first and last `"` (or `json.dumps()` instead of `repr()` if you want double quotes).

So please fix gsc first, then fix this repo by cloning gsc master instead of 1.3.1 tag.

___


<!-- Sent from Reviewable.io -->

2022-12-13 15:30 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/21)* status: 0 of 1 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @jkr0103)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/21#-NJ5sEqL9vMn_BtoRRWy:-NJB3nnq2j4qwVdWUkVc:b-dpj5tj) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Nope, that should have been `', '.join(repr(i) for i in cmd)`, without first and last `"` (or `json.dumps()` instead of `repr()` if you want double quotes).

So please fix gsc first, then fix this repo by cloning gsc master instead of 1.3.1 tag.
</blockquote></details>

@woju  -  Yes ideally that's how we would want to do it, but we will need to point to stable tagged versions of GSC, which at the moment is 1.3.1.  Curated apps will move to a future 1.4 GSC when thats ready. As of now there are other breaking commits as well in GSC (post 1.3.1). So this will be collectively addressed after 1.4 GSC and gramine. For now - a workaround is our only option. What would be a good one?

___


<!-- Sent from Reviewable.io -->

2022-12-13 15:39 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/21)* status: 0 of 1 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @jkr0103)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/21#-NJ5sEqL9vMn_BtoRRWy:-NJB6TDg40vcMvNnhnu5:b-eb8bmh) (no related file):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

@woju  -  Yes ideally that's how we would want to do it, but we will need to point to stable tagged versions of GSC, which at the moment is 1.3.1.  Curated apps will move to a future 1.4 GSC when thats ready. As of now there are other breaking commits as well in GSC (post 1.3.1). So this will be collectively addressed after 1.4 GSC and gramine. For now - a workaround is our only option. What would be a good one?
</blockquote></details>

Another possible workaround could be checking the arguments `$@` for `""` and ignore it in `entry_script_xxx.sh`

something like `entry_script_xxx.sh`:

#!/bin/bash

if if [[ "$@" = "" ]]; then
    "docker-entrypoint.sh" --protected-mode no --save ''
else
    "docker-entrypoint.sh" --protected-mode no --save '' "${@}"
fi

___


<!-- Sent from Reviewable.io -->

2022-12-14 13:35 UTC, woju requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/21)* status: 0 of 1 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @jkr0103)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/21#-NJ5sEqL9vMn_BtoRRWy:-NJFmxC48bzGbeAmSvKQ:b-2tlw92) (no related file):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

Another possible workaround could be checking the arguments `$@` for `""` and ignore it in `entry_script_xxx.sh`

something like `entry_script_xxx.sh`:

#!/bin/bash

if if [[ "$@" = "" ]]; then
    "docker-entrypoint.sh" --protected-mode no --save ''
else
    "docker-entrypoint.sh" --protected-mode no --save '' "${@}"
fi
</blockquote></details>

@jkr0103 > `if [[ "$@" = "" ]]`

Almost OK, just the conditional is wrong (will break if you have more than one argument). That if should be `if [ $# -gt 0 ]`. But the rest seems OK.

@aneessahib > What would be a good one?

IDK, but original patch as submitted was obviously broken (it breaks when you pass an argument that contains whitespace), so can't be merged anyway even if it works around one case. Simply because it breaks other cases.

Please remember that `"$@"` expansion is special: it causes the word to be split for every argument in argv, even (especially) if it is inside quotes. Here's the specification: https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_05_02 . Cf. `"$*"` which doesn't cause word splitting. For this reason, if you passthrough arguments via shell scripts, `"$@"` is the only correct variant and we can't merge anything else (`$@`, `"$*"` nor any other variant).

If you'd like to see what happens, try this as arguments: `a b "c d"` (the third one with a space inside).

___


<!-- Sent from Reviewable.io -->

2022-12-14 13:42 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/21)* status: 0 of 1 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @jkr0103)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/21#-NJ5sEqL9vMn_BtoRRWy:-NJFrM-YDe8AqNJ53o1i:b-nl7kd3) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

@jkr0103 > `if [[ "$@" = "" ]]`

Almost OK, just the conditional is wrong (will break if you have more than one argument). That if should be `if [ $# -gt 0 ]`. But the rest seems OK.

@aneessahib > What would be a good one?

IDK, but original patch as submitted was obviously broken (it breaks when you pass an argument that contains whitespace), so can't be merged anyway even if it works around one case. Simply because it breaks other cases.

Please remember that `"$@"` expansion is special: it causes the word to be split for every argument in argv, even (especially) if it is inside quotes. Here's the specification: https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_05_02 . Cf. `"$*"` which doesn't cause word splitting. For this reason, if you passthrough arguments via shell scripts, `"$@"` is the only correct variant and we can't merge anything else (`$@`, `"$*"` nor any other variant).

If you'd like to see what happens, try this as arguments: `a b "c d"` (the third one with a space inside).
</blockquote></details>

` if [ $# -gt 0 ]` doesn't work in this case as `$#` in not `0` but `1`where `#$` have `""` that is exactly the issue in hand we are trying to address. Condition `if [[ "$@" = "" ]]` is true in this case.

___


<!-- Sent from Reviewable.io -->

2022-12-14 13:51 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/21)* status: 0 of 1 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @jkr0103)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/21#-NJ5sEqL9vMn_BtoRRWy:-NJFtIun4bO29inDbBY4:b-vp3ltg) (no related file):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

` if [ $# -gt 0 ]` doesn't work in this case as `$#` in not `0` but `1`where `#$` have `""` that is exactly the issue in hand we are trying to address. Condition `if [[ "$@" = "" ]]` is true in this case.
</blockquote></details>

Anyways, I am fixing it in GSC as we can make contrib work with `config.yaml` and other changes. Raised two PRs, one is GSC and other in Contrib repo:

https://github.com/gramineproject/gsc/pull/113
https://github.com/gramineproject/contrib/pull/25

___


<!-- Sent from Reviewable.io -->

2022-12-14 13:54 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/21)* status: 0 of 1 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @jkr0103)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/21#-NJ5sEqL9vMn_BtoRRWy:-NJFuIAyApTpq-VcZ3aB:b-5w1puh) (no related file):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

Anyways, I am fixing it in GSC as we can make contrib work with `config.yaml` and other changes. Raised two PRs, one is GSC and other in Contrib repo:

https://github.com/gramineproject/gsc/pull/113
https://github.com/gramineproject/contrib/pull/25


</blockquote></details>

@woju  - as @jkr0103  mentioned, we are able to fix in GSC itself, while keeping the `config.yaml` pointing at gramine 1.3.1 itself. Take a look at the above PRs

___


<!-- Sent from Reviewable.io -->

2022-12-14 13:58 UTC, woju requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/21)* status: 0 of 1 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @jkr0103)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/21#-NJ5sEqL9vMn_BtoRRWy:-NJFv1NM0qz8pXSMUWgZ:b-qeyrh7) (no related file):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

@woju  - as @jkr0103  mentioned, we are able to fix in GSC itself, while keeping the `config.yaml` pointing at gramine 1.3.1 itself. Take a look at the above PRs
</blockquote></details>

I'll go review them.

___


<!-- Sent from Reviewable.io -->

2022-12-19 15:55 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/21)* status: 0 of 1 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @jkr0103)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/21#-NJ5sEqL9vMn_BtoRRWy:-NJf4MggBF5WguzqhAhd:bogvbqk) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

I'll go review them.
</blockquote></details>

@woju - For now we will go ahead with patching the current PR itself since we would like to use supported combinations of GSC and Gramine (both 1.3.1). 
@jkr0103 has updated fix now. We have tested this as well across all the known workloads. Please review. 
The GSC PR reviews for gramineproject/gsc#113 can continue separately, this will be consumed for v1.4 later when ready. 

___


<!-- Sent from Reviewable.io -->

2022-12-19 21:30 UTC, mkow requested changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/21)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @jkr0103)

___
*[`-- commits` line 2 at r3](https://reviewable.io/reviews/gramineproject/contrib/21#-NJgHRV215lg11tBHdtU):*
Please don't reference anything by a commit hash, they may change if we migrate the repo someday.



_Code quote:_
```
commit `d847cce`
```
___
*[`Curated-Apps/util/curation_script.sh` line 179 at r3](https://reviewable.io/reviews/gramineproject/contrib/21#-NJgHpSJBQOmGPYaFZJC:-NJgHpSJBQOmGPYaFZJD:b2gk0kv) ([raw file](https://github.com/gramineproject/contrib/blob/829c716801792aa5ed06871464203b72385a08b1/Curated-Apps/util/curation_script.sh#L179)):*
> ```Shell
>     '$complete_binary_cmd'
> else
>     '$complete_binary_cmd ' "${@}"
> ```

what's that space after the command?


<!-- Sent from Reviewable.io -->

2022-12-20 05:02 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/21)* status: 0 of 1 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow)

___
*[`-- commits` line 2 at r3](https://reviewable.io/reviews/gramineproject/contrib/21#-NJgHRV215lg11tBHdtU):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please don't reference anything by a commit hash, they may change if we migrate the repo someday.
</blockquote></details>

Done
___
*[`Curated-Apps/util/curation_script.sh` line 179 at r3](https://reviewable.io/reviews/gramineproject/contrib/21#-NJgHpSJBQOmGPYaFZJC:-NJhuCAZBBc8swl4MqA8:b-77y6qx) ([raw file](https://github.com/gramineproject/contrib/blob/829c716801792aa5ed06871464203b72385a08b1/Curated-Apps/util/curation_script.sh#L179)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

what's that space after the command?
</blockquote></details>

that was extra space, removed now.


<!-- Sent from Reviewable.io -->

2022-12-20 14:21 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/21)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @jkr0103)

___
*[`-- commits` line 2 at r3](https://reviewable.io/reviews/gramineproject/contrib/21#-NJgHRV215lg11tBHdtU):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

Done
</blockquote></details>

But now you have both the commit with the old one-liner and the new one. But you can fix this later, while rebasing.


<!-- Sent from Reviewable.io -->

2022-12-21 15:17 UTC, woju approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/21)* status: all files reviewed, 2 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @jkr0103)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/21#-NJ5sEqL9vMn_BtoRRWy:-NJpF_ZN5ve4koi-kaVO:b-7xehw7) (no related file):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

@woju - For now we will go ahead with patching the current PR itself since we would like to use supported combinations of GSC and Gramine (both 1.3.1). 
@jkr0103 has updated fix now. We have tested this as well across all the known workloads. Please review. 
The GSC PR reviews for gramineproject/gsc#113 can continue separately, this will be consumed for v1.4 later when ready. 
</blockquote></details>

OK. Since there's `TODO:` comment, I hope the real fix won't be missed. I'm unblocking.

___


<!-- Sent from Reviewable.io -->

2022-12-21 16:01 UTC, woju approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/21)* status: all files reviewed, 2 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @jkr0103 and @mkow)

___
*[`-- commits` line 2 at r3](https://reviewable.io/reviews/gramineproject/contrib/21#-NJgHRV215lg11tBHdtU):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

But now you have both the commit with the old one-liner and the new one. But you can fix this later, while rebasing.
</blockquote></details>

What? No, commit hashes can't change even if we migrate the repo.


<!-- Sent from Reviewable.io -->

2022-12-21 17:15 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/21)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @jkr0103 and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/21#-NJ5sEqL9vMn_BtoRRWy:-NJpeu4-E4OELmguFgZQ:blxo30c) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

OK. Since there's `TODO:` comment, I hope the real fix won't be missed. I'm unblocking.
</blockquote></details>

Yes, we need the fix with GSC v1.4

___
___
*[`-- commits` line 2 at r3](https://reviewable.io/reviews/gramineproject/contrib/21#-NJgHRV215lg11tBHdtU):*
> But now you have both the commit with the old one-liner and the new one. But you can fix this later, while rebasing.

I have rebased and squashed the commits having new one-liner message.


<!-- Sent from Reviewable.io -->

2022-12-21 17:19 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/21)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @jkr0103)



<!-- Sent from Reviewable.io -->

2022-12-21 18:13 UTC, woju approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/21)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2022-12-21 19:23 UTC, yamahata reviewed
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/21)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2022-12-21 19:23 UTC, yamahata reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/21#-:-NJq7yaO8h6H9FoUONLA:bnfp4nl)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2022-12-21 19:50 UTC, yamahata approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/21#-:-NJqEDk220aa45GTV1Fg:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-12-21 20:27 UTC, merged