[Curated-Apps] Adapt to latest GSC
gramineproject/contrib pull request #25
Opened 2022-12-14 13:29 UTC by jkr0103

This PR have multiple fixes to adapt to latest gramine as described below:

1. Updated prerequisites for tomli in README
2. Droping support for out-of-tree DCAP SGX drivers with commit `0b60fa2` breaks contrib. Had to adapt `/util/config.yaml.template`. In case of non-in-kernel SGX driver, `/dev/sgx_enclave` doesn't exists. changes are made to mount it as `/dev/sgx/enclave`  as it's avaible in both non-in-kernel SGX and in-kernel SGX driver on Azure Confidential Compute VMs.

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/contrib/25)

2022-12-16 16:26 UTC, mkow requested changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/25)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @jkr0103)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/25#-NJQjscv2IJWJ-fAKch0:-NJQjscw5I6nc0ca4x9N:b-poocvu) (no related file):*
> GSC tag v1.3.1 should be moved to the commit of above PR.

?

___
*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/25#-NJQkKpk7pqU7k5E31MI:-NJQkKpk7pqU7k5E31MJ:be2l1lh) (no related file):*
> Droping support for out-of-tree DCAP SGX drivers with commit `0b60fa2` breaks contrib. 

What's that commit? I don't see it in Gramine.

___
___
*[`Curated-Apps/curate.py` line 481 at r1](https://reviewable.io/reviews/gramineproject/contrib/25#-NJQkPKZ4IyiHvqrDlG2:-NJQkPK_CoxNhD7cqxkr:b-v2w32i) ([raw file](https://github.com/gramineproject/contrib/blob/25c4d448cf482ae51a0fac52f23203894e52085e/Curated-Apps/curate.py#L481)):*
> ```Python
> 
>         verifier_run_command = (f'Execute below command to start verifier on a trusted system:\n'
>                                 f'$ docker run {host_net} --device=/dev/sgx/enclave:/dev/sgx_enclave '
> ```

The old code should work? Where, how and on which Gramine it breaks?
___
*[`Curated-Apps/util/constants.py` line 33 at r1](https://reviewable.io/reviews/gramineproject/contrib/25#-NJQkYhUB0gfYVmdxcgQ:-NJQkYhUB0gfYVmdxcgR:b-7ropln) ([raw file](https://github.com/gramineproject/contrib/blob/25c4d448cf482ae51a0fac52f23203894e52085e/Curated-Apps/util/constants.py#L33)):*
> ```Python
>                   'Above command is saved to command.txt as well.'
>                   ' Press any key to exit the app')
> test_run_cmd = ('$ docker run --net=host --device=/dev/sgx/enclave:/dev/sgx_enclave -it {}')
> ```

ditto


<!-- Sent from Reviewable.io -->

2022-12-16 16:57 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/25)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/25#-NJQjscv2IJWJ-fAKch0:-NJQo64nBFuArc9WCx00:b-fb1u2y) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> GSC tag v1.3.1 should be moved to the commit of above PR.

?
</blockquote></details>

Sorry this is wrong statement. I have remove it.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/25#-NJQkKpk7pqU7k5E31MI:-NJQqXLZ98sYRSfIHeHa:by4kr06) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> Droping support for out-of-tree DCAP SGX drivers with commit `0b60fa2` breaks contrib. 

What's that commit? I don't see it in Gramine.
</blockquote></details>

It's in GSC https://github.com/gramineproject/gsc/commit/0b60fa28aab0c9bc1b907230879235870f600b66.

___
___
*[`Curated-Apps/curate.py` line 481 at r1](https://reviewable.io/reviews/gramineproject/contrib/25#-NJQkPKZ4IyiHvqrDlG2:-NJQr-K30mup30mbhAdY:b-val2gv) ([raw file](https://github.com/gramineproject/contrib/blob/25c4d448cf482ae51a0fac52f23203894e52085e/Curated-Apps/curate.py#L481)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

The old code should work? Where, how and on which Gramine it breaks?
</blockquote></details>

Old code here will work with gramine master since you have put the fix https://github.com/gramineproject/gramine/pull/1027. But curated apps can only point to gramine v1.3.1 so we have to do this mounting `--device=/dev/sgx/enclave:/dev/sgx_enclave` manually.
___
*[`Curated-Apps/util/constants.py` line 33 at r1](https://reviewable.io/reviews/gramineproject/contrib/25#-NJQkYhUB0gfYVmdxcgQ:-NJQrbjNEWfQqoGnuNpc:b-7ropln) ([raw file](https://github.com/gramineproject/contrib/blob/25c4d448cf482ae51a0fac52f23203894e52085e/Curated-Apps/util/constants.py#L33)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

ditto


<!-- Sent from Reviewable.io -->

2022-12-17 19:47 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/25)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @jkr0103)

___
*[`Curated-Apps/curate.py` line 481 at r1](https://reviewable.io/reviews/gramineproject/contrib/25#-NJQkPKZ4IyiHvqrDlG2:-NJWbCja0LmK1vcervEr:b-v0i3bi) ([raw file](https://github.com/gramineproject/contrib/blob/25c4d448cf482ae51a0fac52f23203894e52085e/Curated-Apps/curate.py#L481)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

Old code here will work with gramine master since you have put the fix https://github.com/gramineproject/gramine/pull/1027. But curated apps can only point to gramine v1.3.1 so we have to do this mounting `--device=/dev/sgx/enclave:/dev/sgx_enclave` manually.
</blockquote></details>

Wait, I don't understand what's happening here. Neither gramineproject/gsc@0b60fa2, https://github.com/gramineproject/gramine/pull/997 nor https://github.com/gramineproject/gramine/pull/1027 are part of v1.3.1.


<!-- Sent from Reviewable.io -->

2022-12-18 04:06 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/25)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow)

___
*[`Curated-Apps/curate.py` line 481 at r1](https://reviewable.io/reviews/gramineproject/contrib/25#-NJQkPKZ4IyiHvqrDlG2:-NJYM6Fs3VV52zWdRxum:bly8jbz) ([raw file](https://github.com/gramineproject/contrib/blob/25c4d448cf482ae51a0fac52f23203894e52085e/Curated-Apps/curate.py#L481)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Wait, I don't understand what's happening here. Neither gramineproject/gsc@0b60fa2, https://github.com/gramineproject/gramine/pull/997 nor https://github.com/gramineproject/gramine/pull/1027 are part of v1.3.1.
</blockquote></details>

ok lets try again
1) Curated Apps can only point at release Gramine core code - which 1.3.1
2) Hence, the `config.yaml` file in GSC will have to point at 1.3.1
3) GSC master  and V1.3.1 Gramine code wont work anymore due to the commits you have highlighted above.
4) Curated apps can get GSC master and V1.3.1 Gramine core code to work together if this PR is merged.
Clear on the overall idea?


<!-- Sent from Reviewable.io -->

2022-12-18 04:12 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/25)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow)

___
*[`Curated-Apps/curate.py` line 481 at r1](https://reviewable.io/reviews/gramineproject/contrib/25#-NJQkPKZ4IyiHvqrDlG2:-NJYQRSU9HzA86qHifTn:b-llfmsg) ([raw file](https://github.com/gramineproject/contrib/blob/25c4d448cf482ae51a0fac52f23203894e52085e/Curated-Apps/curate.py#L481)):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

ok lets try again
1) Curated Apps can only point at release Gramine core code - which 1.3.1
2) Hence, the `config.yaml` file in GSC will have to point at 1.3.1
3) GSC master  and V1.3.1 Gramine code wont work anymore due to the commits you have highlighted above.
4) Curated apps can get GSC master and V1.3.1 Gramine core code to work together if this PR is merged.
Clear on the overall idea?
</blockquote></details>

Update (corrected some typos - I wish reviewable supported edits) : 

1. Curated Apps can only point at release Gramine core code - which is 1.3.1
2. Hence, the `config.yaml` file in GSC will have to point at 1.3.1
3. GSC master can now no longer build GSC images with V1.3.1 Gramine code due to the commits you have highlighted above.
4. However, Curated apps can get GSC master to build with V1.3.1 Gramine core code if this WA PR is merged.
Clear on the overall idea?


<!-- Sent from Reviewable.io -->

2022-12-18 14:06 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/25)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow)

___
*[`Curated-Apps/curate.py` line 481 at r1](https://reviewable.io/reviews/gramineproject/contrib/25#-NJQkPKZ4IyiHvqrDlG2:-NJ_PE106c3nDvJQti8j:b-fy5jue) ([raw file](https://github.com/gramineproject/contrib/blob/25c4d448cf482ae51a0fac52f23203894e52085e/Curated-Apps/curate.py#L481)):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

Update (corrected some typos - I wish reviewable supported edits) : 

1. Curated Apps can only point at release Gramine core code - which is 1.3.1
2. Hence, the `config.yaml` file in GSC will have to point at 1.3.1
3. GSC master can now no longer build GSC images with V1.3.1 Gramine code due to the commits you have highlighted above.
4. However, Curated apps can get GSC master to build with V1.3.1 Gramine core code if this WA PR is merged.
Clear on the overall idea?

</blockquote></details>

In addition to Anees's points, some technical details about the issue:

Starting from GSC commit https://github.com/gramineproject/gsc/commit/0b60fa28aab0c9bc1b907230879235870f600b66 GSC builds gramine with v1.3.1 in `in-kernel` mode, see changes in `config.yaml.template` and other files which means while running GSC image, gramine look for device `/dev/sgx_enclave`. If we execute this GSC image on `legacy oot dcap machine` which have sgx device mount at `/dev/sgx/enclave` and not at `/dev/sgx_enclave`, gramine reports error `error: Cannot open device /dev/sgx_enclave. Please make sure the Intel SGX kernel module is loaded. error: load_enclave() failed with error -2`.  We won't see this issue if point to latest gramine master which have fixed it with PR https://github.com/gramineproject/gramine/pull/1027.

Azure confidential compute VMs have `legacy oot dcap` as well as `in-kernel` and we need to support both.

Please see issue https://github.com/gramineproject/contrib/issues/24 for more details.

Constrains on using GSC latest master for curation: We need to take some fixes from latest GSC master.
Constrains on using Gramine v1.3.1 for curation: SDL requirements, until v1.4


<!-- Sent from Reviewable.io -->

2022-12-19 02:44 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/25)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @aneessahib and @jkr0103)

___
*[`Curated-Apps/curate.py` line 481 at r1](https://reviewable.io/reviews/gramineproject/contrib/25#-NJQkPKZ4IyiHvqrDlG2:-NJcBgGq1I8dfojlYkd1:bbtwqrh) ([raw file](https://github.com/gramineproject/contrib/blob/25c4d448cf482ae51a0fac52f23203894e52085e/Curated-Apps/curate.py#L481)):*
> I wish reviewable supported edits

https://github.com/Reviewable/Reviewable/issues/836

>  Clear on the overall idea?

Not really. The whole idea of versioning GSC with the same numbers as Gramine was to use matching versions. So, you can use Gramine 1.3.1 with GSC 1.3.1, or Gramine master with GSC master. But here for some reason you want to use Gramine 1.3.1 with GSC master, which are not compatible (and are not intended to be).


<!-- Sent from Reviewable.io -->

2022-12-19 03:10 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/25)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow)

___
*[`Curated-Apps/curate.py` line 481 at r1](https://reviewable.io/reviews/gramineproject/contrib/25#-NJQkPKZ4IyiHvqrDlG2:-NJcKebw0dzUTmDwYHaf:b-kflean) ([raw file](https://github.com/gramineproject/contrib/blob/25c4d448cf482ae51a0fac52f23203894e52085e/Curated-Apps/curate.py#L481)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> I wish reviewable supported edits

https://github.com/Reviewable/Reviewable/issues/836

>  Clear on the overall idea?

Not really. The whole idea of versioning GSC with the same numbers as Gramine was to use matching versions. So, you can use Gramine 1.3.1 with GSC 1.3.1, or Gramine master with GSC master. But here for some reason you want to use Gramine 1.3.1 with GSC master, which are not compatible (and are not intended to be).
</blockquote></details>

Perfect. My sentiments are on similar lines. Ideally what you said is how it should be. But we ran into a critical issue, that we can patch up in `contrib` (and use 1.3.1 GSC/1.3.1 Gramine like you said), but Woju prefers  the fix go in GSC master.  https://github.com/gramineproject/gsc/pull/113 


<!-- Sent from Reviewable.io -->

2022-12-19 11:05 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/25)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @aneessahib and @jkr0103)

___
*[`Curated-Apps/curate.py` line 481 at r1](https://reviewable.io/reviews/gramineproject/contrib/25#-NJQkPKZ4IyiHvqrDlG2:-NJe2Yki6kCav5BxZ2aA:b-12buo1) ([raw file](https://github.com/gramineproject/contrib/blob/25c4d448cf482ae51a0fac52f23203894e52085e/Curated-Apps/curate.py#L481)):*
> Woju prefers the fix go in GSC master

Because the bug is there and you should fix it there :)

But if you are able to create a correct, temporary workaround here (in addition to the GSC fix), then it would be better, because you would be able to use a supported combination of versions.


<!-- Sent from Reviewable.io -->

2022-12-19 15:58 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/25)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow)

___
*[`Curated-Apps/curate.py` line 481 at r1](https://reviewable.io/reviews/gramineproject/contrib/25#-NJQkPKZ4IyiHvqrDlG2:-NJf3eYI0qdEuoR5nR9a:b-4omr25) ([raw file](https://github.com/gramineproject/contrib/blob/25c4d448cf482ae51a0fac52f23203894e52085e/Curated-Apps/curate.py#L481)):*
> Because the bug is there and you should fix it there :)

That was implicit. I should have explained more nicely :D 

>But if you are able to create a correct, temporary workaround here (in addition to the GSC fix), then it would be better, because you would be able to use a supported combination of versions.

Done. Check https://github.com/gramineproject/contrib/pull/21 


<!-- Sent from Reviewable.io -->

2023-01-03 14:22 UTC, dimakuv requested changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/25)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow)

___
*[`Curated-Apps/curate.py` line 481 at r1](https://reviewable.io/reviews/gramineproject/contrib/25#-NJQkPKZ4IyiHvqrDlG2:-NKs-amqDIyKh_RqmcnH:bpvxszg) ([raw file](https://github.com/gramineproject/contrib/blob/25c4d448cf482ae51a0fac52f23203894e52085e/Curated-Apps/curate.py#L481)):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

> Because the bug is there and you should fix it there :)

That was implicit. I should have explained more nicely :D 

>But if you are able to create a correct, temporary workaround here (in addition to the GSC fix), then it would be better, because you would be able to use a supported combination of versions.

Done. Check https://github.com/gramineproject/contrib/pull/21 
</blockquote></details>

So now that we have #21 merged, can we fix GSC version in Curated-Apps at `v1.3.1` tag, and revert all the changes (except README, which is useful anyway) in this PR?


<!-- Sent from Reviewable.io -->

2023-01-04 07:25 UTC, jkr0103 commented
@dimakuv with https://github.com/gramineproject/contrib/pull/21 merged, we don't need changes from this PR, hence closing the PR. I will create a fresh PR for README changes.

2023-01-04 07:25 UTC, closed without merging