[Curated-Apps] Add encryption key in the manifest
gramineproject/contrib pull request #30
Opened 2023-01-13 13:52 UTC by jkr0103

Hard-code encryption key in the manifest. This is useful in cases where user want to test his base image having encrypted files without attestation.

Another changes is developers don't have to modify `curation_script.sh` everytime while curating new apps which have encrypted files added to the base image in test mode. Developers only have to create `encrypted_files.txt` and add encrypted files to the file.

2023-01-23 10:37 UTC, dimakuv requested changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/30)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @jkr0103)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/contrib/30#-NMTB_iM0eZCvQwnmOYr):*
Need to add an empty line after the commit title.
___
*[`Curated-Apps/workloads/pytorch/base_image_helper/encrypted_files.txt` line 1 at r1](https://reviewable.io/reviews/gramineproject/contrib/30#-NMTBdi7158RFbtjL72W:-NMTBdi7158RFbtjL72X:btecvzn) ([raw file](https://github.com/gramineproject/contrib/blob/470caea4384d49db6fc7f1ea05178f1c74edf5ab/Curated-Apps/workloads/pytorch/base_image_helper/encrypted_files.txt#L1)):*
> ```help
> classes.txt:input.jpg:alexnet-pretrained.pt:result.txt
> ```

Can we rename this file to just `encrypted_files`? In other words, drop the `.txt` extension? In Linux world, people don't use this extension...
___
*[`Curated-Apps/workloads/pytorch/base_image_helper/encrypted_files.txt` line 1 at r1](https://reviewable.io/reviews/gramineproject/contrib/30#-NMTBo8yAtJv4T-ppvuW:-NMTBo8yAtJv4T-ppvuX:bj34mhu) ([raw file](https://github.com/gramineproject/contrib/blob/470caea4384d49db6fc7f1ea05178f1c74edf5ab/Curated-Apps/workloads/pytorch/base_image_helper/encrypted_files.txt#L1)):*
> ```help
> classes.txt:input.jpg:alexnet-pretrained.pt:result.txt
> ```

Why not "one file per one line"? Why to use `:` as delimeter?


<!-- Sent from Reviewable.io -->

2023-01-23 14:00 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/30)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @jkr0103)

___
*[`Curated-Apps/workloads/pytorch/base_image_helper/encrypted_files.txt` line 1 at r1](https://reviewable.io/reviews/gramineproject/contrib/30#-NMTBo8yAtJv4T-ppvuW:-NMTvSTGCepSxvfpJ7-V:b-8kf6ic) ([raw file](https://github.com/gramineproject/contrib/blob/470caea4384d49db6fc7f1ea05178f1c74edf5ab/Curated-Apps/workloads/pytorch/base_image_helper/encrypted_files.txt#L1)):*
Ok, unblocking this as @jkr0103 explained to me offline:

> in production case user have to enter list of files on TUI when prompted, there we cannot ask for entering in newlines due to TUI constraints currently it have. Hence I thought of to be consistent with it, otherwise we need different login in both the cases to process these files...

This is not amazing, but I don't mind.


<!-- Sent from Reviewable.io -->

2023-01-23 14:57 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/30)* status: 2 of 4 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), period found at the end of a one-liner, "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/contrib/30#-NMTB_iM0eZCvQwnmOYr):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Need to add an empty line after the commit title.
</blockquote></details>

Done.
___
*[`Curated-Apps/workloads/pytorch/base_image_helper/encrypted_files.txt` line 1 at r1](https://reviewable.io/reviews/gramineproject/contrib/30#-NMTBdi7158RFbtjL72W:-NMU7XYg9FmfiUg3wsUP:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/470caea4384d49db6fc7f1ea05178f1c74edf5ab/Curated-Apps/workloads/pytorch/base_image_helper/encrypted_files.txt#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can we rename this file to just `encrypted_files`? In other words, drop the `.txt` extension? In Linux world, people don't use this extension...
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-24 08:45 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/30)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), period found at the end of a one-liner, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-03-01 13:09 UTC, mkow requested changes
> Reviewed 2 of 4 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/30)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), period found at the end of a one-liner, "fixup! " found in commit messages' one-liners (waiting on @jkr0103)

___
*[`-- commits` line 5 at r3](https://reviewable.io/reviews/gramineproject/contrib/30#-NPSHVPvDYAGYVbyO5ad):*
This generates a completely insecure image, how do you prevent people from accidentally shipping it?
___
*[`Curated-Apps/util/curation_script.sh` line 101 at r3](https://reviewable.io/reviews/gramineproject/contrib/30#-NPS8t4q6ayiahYGJd_a:-NPS8t4q6ayiahYGJd_b:undefined) ([raw file](https://github.com/gramineproject/contrib/blob/58fced2f755e6da79ef4aae8125d929b5c6e7b22/Curated-Apps/util/curation_script.sh#L101)):*
> ```Shell
> add_encryption_key_to_manifest() {
>     if [[ ! -e $1 ]]; then
>         echo "Encryption key is not found!"
> ```





_Suggestion:_
```Shell
was not found
```
___
*[`Curated-Apps/workloads/pytorch/base_image_helper/encrypted_files` line 1 at r3](https://reviewable.io/reviews/gramineproject/contrib/30#-NPSGyuX8KdLCFb-qYEx:-NPSGyuX8KdLCFb-qYEy:bovjz1k) ([raw file](https://github.com/gramineproject/contrib/blob/58fced2f755e6da79ef4aae8125d929b5c6e7b22/Curated-Apps/workloads/pytorch/base_image_helper/encrypted_files#L1)):*
> ```
> classes.txt:input.jpg:alexnet-pretrained.pt:result.txt
> ```

Please re-add the extension


<!-- Sent from Reviewable.io -->

2023-03-01 14:09 UTC, dimakuv submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/30)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), period found at the end of a one-liner, "fixup! " found in commit messages' one-liners (waiting on @jkr0103 and @mkow)

___
*[`-- commits` line 5 at r3](https://reviewable.io/reviews/gramineproject/contrib/30#-NPSHVPvDYAGYVbyO5ad):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This generates a completely insecure image, how do you prevent people from accidentally shipping it?
</blockquote></details>

See my other comment, but basically this will always print a warning due to `fs.insecure__keys`
___
*[`Curated-Apps/util/curation_script.sh` line 104 at r3](https://reviewable.io/reviews/gramineproject/contrib/30#-NPSUwrc282n6PLb_0GR:-NPSUwrd9cbNn3ZElQ6t:blm0qt1) ([raw file](https://github.com/gramineproject/contrib/blob/58fced2f755e6da79ef4aae8125d929b5c6e7b22/Curated-Apps/util/curation_script.sh#L104)):*
> ```Shell
>         exit
>     fi
>     echo -e 'fs.insecure__keys.default = "'$(xxd -p $1)'"' >> $app_image_manifest
> ```

FYI: @mkow This is where we add an insecure manifest option to Gramine, so Gramine prints a big warning on startup. See also https://github.com/gramineproject/gramine/blob/0119fd23ebbc892b33868e9ea9296ba6e8061685/pal/src/host/linux-sgx/pal_main.c#L513-L515
___
*[`Curated-Apps/workloads/pytorch/base_image_helper/encrypted_files` line 1 at r3](https://reviewable.io/reviews/gramineproject/contrib/30#-NPSGyuX8KdLCFb-qYEx:-NPSUnUhA4IVqwbzsyTM:b-43ucci) ([raw file](https://github.com/gramineproject/contrib/blob/58fced2f755e6da79ef4aae8125d929b5c6e7b22/Curated-Apps/workloads/pytorch/base_image_helper/encrypted_files#L1)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please re-add the extension
</blockquote></details>

@mkow Not blocking but why do you want an extension on this file?


<!-- Sent from Reviewable.io -->

2023-03-01 14:53 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/30)* status: 2 of 4 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`-- commits` line 5 at r3](https://reviewable.io/reviews/gramineproject/contrib/30#-NPSHVPvDYAGYVbyO5ad):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

See my other comment, but basically this will always print a warning due to `fs.insecure__keys`
</blockquote></details>

yes indeed Gramine generates below warning:



_Code snippet:_
```
-----------------------------------------------------------------------------------------------------------------------
Gramine detected the following insecure configurations:

  - fs.insecure__keys.* = "..."                (keys hardcoded in manifest)

Gramine will continue application execution, but this configuration must not be used in production!
-----------------------------------------------------------------------------------------------------------------------
```
___
*[`Curated-Apps/util/curation_script.sh` line 101 at r3](https://reviewable.io/reviews/gramineproject/contrib/30#-NPS8t4q6ayiahYGJd_a:-NPSeXhS7rBXTq0LEjNT:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/58fced2f755e6da79ef4aae8125d929b5c6e7b22/Curated-Apps/util/curation_script.sh#L101)):*
> ```Shell
> add_encryption_key_to_manifest() {
>     if [[ ! -e $1 ]]; then
>         echo "Encryption key is not found!"
> ```

Done.
___
*[`Curated-Apps/workloads/pytorch/base_image_helper/encrypted_files` line 1 at r3](https://reviewable.io/reviews/gramineproject/contrib/30#-NPSGyuX8KdLCFb-qYEx:-NPSeZmU4cwTAToFVsfl:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/58fced2f755e6da79ef4aae8125d929b5c6e7b22/Curated-Apps/workloads/pytorch/base_image_helper/encrypted_files#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@mkow Not blocking but why do you want an extension on this file?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-01 15:27 UTC, mkow approved these changes
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/30)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

___
*[`Curated-Apps/workloads/pytorch/base_image_helper/encrypted_files` line 1 at r3](https://reviewable.io/reviews/gramineproject/contrib/30#-NPSGyuX8KdLCFb-qYEx:-NPSlCcE7P9B8ye4iess:bhmintr) ([raw file](https://github.com/gramineproject/contrib/blob/58fced2f755e6da79ef4aae8125d929b5c6e7b22/Curated-Apps/workloads/pytorch/base_image_helper/encrypted_files#L1)):*
> why do you want an extension on this file?

For the same reason you have extensions on all other files? E.g. we keep headers in .h files and you probably wouldn't want to drop the extensions from them.


<!-- Sent from Reviewable.io -->

2023-03-01 17:13 UTC, dimakuv requested changes
> Reviewed 1 of 2 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/30)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @jkr0103)

___
*[`-- commits` line 5 at r5](https://reviewable.io/reviews/gramineproject/contrib/30#-NPT9DbY6AKBCAp2778c):*
`user` -> `users`

`his` -> `their`

I'll fix it now by rebasing.
___
*[`Curated-Apps/workloads/pytorch/base_image_helper/encrypted_files` line 1 at r3](https://reviewable.io/reviews/gramineproject/contrib/30#-NPSGyuX8KdLCFb-qYEx:-NPT9OMZ0CnGWorJCcVa:b-3hyq99) ([raw file](https://github.com/gramineproject/contrib/blob/58fced2f755e6da79ef4aae8125d929b5c6e7b22/Curated-Apps/workloads/pytorch/base_image_helper/encrypted_files#L1)):*
> E.g. we keep headers in .h files and you probably wouldn't want to drop the extensions from them.

But in this example the `.h` extension tells you that this is a C header file.

In this `encrypted_files.txt` case, this is not really a "text" file, this is some CSV-like file. Well, anyway, I'm bikeshedding now.


<!-- Sent from Reviewable.io -->

2023-03-01 17:15 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/30)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`-- commits` line 5 at r5](https://reviewable.io/reviews/gramineproject/contrib/30#-NPT9DbY6AKBCAp2778c):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`user` -> `users`

`his` -> `their`

I'll fix it now by rebasing.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-03-01 19:47 UTC, mkow approved these changes
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/30)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`Curated-Apps/workloads/pytorch/base_image_helper/encrypted_files` line 1 at r3](https://reviewable.io/reviews/gramineproject/contrib/30#-NPSGyuX8KdLCFb-qYEx:-NPThMJ7DWXC1b81dm--:bonbzzo) ([raw file](https://github.com/gramineproject/contrib/blob/58fced2f755e6da79ef4aae8125d929b5c6e7b22/Curated-Apps/workloads/pytorch/base_image_helper/encrypted_files#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> E.g. we keep headers in .h files and you probably wouldn't want to drop the extensions from them.

But in this example the `.h` extension tells you that this is a C header file.

In this `encrypted_files.txt` case, this is not really a "text" file, this is some CSV-like file. Well, anyway, I'm bikeshedding now.
</blockquote></details>

I'd say a CSV file is a sub-type of a text file :P


<!-- Sent from Reviewable.io -->

2023-03-01 19:57 UTC, merged