[Curated-Apps] Add attestation env variables used with debug enclave
gramineproject/contrib pull request #33
Opened 2023-01-25 05:25 UTC by jkr0103

To test debug build with remote attestation, verifier `docker run` command must have  `-e 
 A_TLS_ALLOW_DEBUG_ENCLAVE_INSECURE=1 -e  RA_TLS_ALLOW_OUTDATED_TCB_INSECURE=1` environment variables.

These environment variables were missing for debug builds. This PR add them.

Fixes #32

2023-01-25 08:45 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/33)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @jkr0103)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/33#-NMc5Ks73pkNhqj5RbPt:-NMc5Ks73pkNhqj5RbPu:bgk0aag) (no related file):*
Note: we manually verified that this was the reason for failure in #32. The fix looks good.

___
___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/contrib/33#-NMc4o2J7Wxgp8sZcnxw):*
```
[Curated-Apps] Add `RA_TLS_ALLOW_*` attestation envvars if enclave built in debug mode
```

I can do it during final rebase.


<!-- Sent from Reviewable.io -->

2023-03-01 13:20 UTC, mkow requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/33)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @jkr0103)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/contrib/33#-NMc4o2J7Wxgp8sZcnxw):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

```
[Curated-Apps] Add `RA_TLS_ALLOW_*` attestation envvars if enclave built in debug mode
```

I can do it during final rebase.
</blockquote></details>

`if enclave built in debug mode` -> `if enclave was built in debug mode`
___
*[`Curated-Apps/curate.py` line 460 at r1](https://reviewable.io/reviews/gramineproject/contrib/33#-NPSJmG72dWA_HrBeFhV:-NPSJmG72dWA_HrBeFhW:bfp8acb) ([raw file](https://github.com/gramineproject/contrib/blob/4d820ae36537c74c4596778c54d01cc135d87f16/Curated-Apps/curate.py#L460)):*
> ```Python
>     if attestation_required == 'y':
>         debug_enclave_env_ver_ext = ''
>         if config == 'test' or debug_flag == 'y':
> ```

Is the final image protected anyhow from being used in production accidentally? These options you're adding here disable all the security in attestation.


<!-- Sent from Reviewable.io -->

2023-03-01 13:53 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/33)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @mkow)

___
*[`Curated-Apps/curate.py` line 460 at r1](https://reviewable.io/reviews/gramineproject/contrib/33#-NPSJmG72dWA_HrBeFhV:-NPSQQCo17vMkri48ST9:br6tfy9) ([raw file](https://github.com/gramineproject/contrib/blob/4d820ae36537c74c4596778c54d01cc135d87f16/Curated-Apps/curate.py#L460)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Is the final image protected anyhow from being used in production accidentally? These options you're adding here disable all the security in attestation.
</blockquote></details>

We depend on Gramine warning for using insecure options. For the debug enclave, Gramine issue a warning and for all other test options used in curations (test image, test signing key), we explicitly add 
`loader.file_check_policy = "allow_all_but_log"` so that Gramine produces a warning, something like -



_Code snippet:_
```Python
-----------------------------------------------------------------------------------------------------------------------
Gramine detected the following insecure configurations:

  - sgx.debug = true                           (this is a debug enclave)
  - sgx.allowed_files = [ ... ]                (some files are passed through from untrusted host without verification)

Gramine will continue application execution, but this configuration must not be used in production!
-----------------------------------------------------------------------------------------------------------------------
```


<!-- Sent from Reviewable.io -->

2023-03-01 13:53 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/33)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @mkow)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/contrib/33#-NMc4o2J7Wxgp8sZcnxw):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`if enclave built in debug mode` -> `if enclave was built in debug mode`
</blockquote></details>

@dimakuv , Could you please take care of it while rebasing and merging?


<!-- Sent from Reviewable.io -->

2023-03-01 13:59 UTC, dimakuv submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/33)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @mkow)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/contrib/33#-NMc4o2J7Wxgp8sZcnxw):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

@dimakuv , Could you please take care of it while rebasing and merging?
</blockquote></details>

Yes, I will
___
*[`Curated-Apps/curate.py` line 460 at r1](https://reviewable.io/reviews/gramineproject/contrib/33#-NPSJmG72dWA_HrBeFhV:-NPSSBWH1eZctKyUq9YZ:bcbmnf6) ([raw file](https://github.com/gramineproject/contrib/blob/4d820ae36537c74c4596778c54d01cc135d87f16/Curated-Apps/curate.py#L460)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

We depend on Gramine warning for using insecure options. For the debug enclave, Gramine issue a warning and for all other test options used in curations (test image, test signing key), we explicitly add 
`loader.file_check_policy = "allow_all_but_log"` so that Gramine produces a warning, something like -

</blockquote></details>

Yes, Michal's question got me interested, and I looked into the source code of Curated Apps. @jkr0103 already desribed it, but let me also add my findings:

- For the `test` config, we have this: https://github.com/gramineproject/contrib/blob/0f3416d254b3783eae7b1aaebaad609d130ff74c/Curated-Apps/util/curation_script.sh#L138-L145

- For the `debug` flag, we have this: https://github.com/gramineproject/contrib/blob/0f3416d254b3783eae7b1aaebaad609d130ff74c/Curated-Apps/util/curation_script.sh#L101-L102
  - The `gsc build -d` flag adds `sgx.debug = true` in GSC, you can check [here](https://github.com/gramineproject/gsc/blob/a60a4991d7351c1b7489444c694638ca9cc68e39/templates/entrypoint.common.manifest.template#L16)

So in the first case Gramine will print the "detected insecure configurations" with `sgx.file_check_policy = "allow_all_but_log"`, and in the second case Gramine will print it with `sgx.debug = true`.


<!-- Sent from Reviewable.io -->

2023-03-01 15:19 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/33)* status: all files reviewed, 1 unresolved discussion (waiting on @dimakuv)

___
*[`Curated-Apps/curate.py` line 460 at r1](https://reviewable.io/reviews/gramineproject/contrib/33#-NPSJmG72dWA_HrBeFhV:-NPSk8PwD9cKI32m0-lf:bbqcwjb) ([raw file](https://github.com/gramineproject/contrib/blob/4d820ae36537c74c4596778c54d01cc135d87f16/Curated-Apps/curate.py#L460)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, Michal's question got me interested, and I looked into the source code of Curated Apps. @jkr0103 already desribed it, but let me also add my findings:

- For the `test` config, we have this: https://github.com/gramineproject/contrib/blob/0f3416d254b3783eae7b1aaebaad609d130ff74c/Curated-Apps/util/curation_script.sh#L138-L145

- For the `debug` flag, we have this: https://github.com/gramineproject/contrib/blob/0f3416d254b3783eae7b1aaebaad609d130ff74c/Curated-Apps/util/curation_script.sh#L101-L102
  - The `gsc build -d` flag adds `sgx.debug = true` in GSC, you can check [here](https://github.com/gramineproject/gsc/blob/a60a4991d7351c1b7489444c694638ca9cc68e39/templates/entrypoint.common.manifest.template#L16)

So in the first case Gramine will print the "detected insecure configurations" with `sgx.file_check_policy = "allow_all_but_log"`, and in the second case Gramine will print it with `sgx.debug = true`.
</blockquote></details>

This is rather indirect and may be easily broken in the future accidentally (because the warning isn't generated _because_ of these envs, but because of something else we do together with them). I'm approving this only because this is the `contrib` repo.


<!-- Sent from Reviewable.io -->

2023-03-01 17:17 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/33)* status: all files reviewed, 1 unresolved discussion

___
*[`Curated-Apps/curate.py` line 460 at r1](https://reviewable.io/reviews/gramineproject/contrib/33#-NPSJmG72dWA_HrBeFhV:-NPTAETS3GxiI6pQGWMJ:b-thmxh) ([raw file](https://github.com/gramineproject/contrib/blob/4d820ae36537c74c4596778c54d01cc135d87f16/Curated-Apps/curate.py#L460)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This is rather indirect and may be easily broken in the future accidentally (because the warning isn't generated _because_ of these envs, but because of something else we do together with them). I'm approving this only because this is the `contrib` repo.
</blockquote></details>

@mkow Yes, agreed, this is indirect.

Out of curiosity, what would you imagine as a "protection from using these images in production accidentally"?


<!-- Sent from Reviewable.io -->

2023-03-01 20:09 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/33)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/contrib/33#-NMc4o2J7Wxgp8sZcnxw):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, I will
</blockquote></details>

Done. Significantly changed the commit message (since the proposed version was way too long for a commit title).


<!-- Sent from Reviewable.io -->

2023-03-01 20:19 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/33)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`Curated-Apps/curate.py` line 460 at r1](https://reviewable.io/reviews/gramineproject/contrib/33#-NPSJmG72dWA_HrBeFhV:-NPToWaQ4uIM13krbrYF:b-r2bzs0) ([raw file](https://github.com/gramineproject/contrib/blob/4d820ae36537c74c4596778c54d01cc135d87f16/Curated-Apps/curate.py#L460)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@mkow Yes, agreed, this is indirect.

Out of curiosity, what would you imagine as a "protection from using these images in production accidentally"?
</blockquote></details>

Probably somewhere in the CUI when you try to use this option? But I didn't use curated apps much, so I can't see exactly. Just somewhere in the way when using it.


<!-- Sent from Reviewable.io -->

2023-03-01 20:51 UTC, merged