[Curated-Apps] Add .deb packages instead of `gramine-dcap` in verifier`
gramineproject/contrib pull request #34
Opened 2023-02-03 16:39 UTC by jkr0103

Issue: Verifier installs `gramine-dcap` which will be updated with gramine v1.4 packages and with that Curated-Apps will break because Curated-Apps are not compatible with gramine v1.4. Curates-Apps won't know if underline packages in `gramine-dcap` have changes.

Fix: Use exact underline packages with 1.3.1 version in verifier.

2023-02-06 09:18 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/34)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @jkr0103)

___
*[`Curated-Apps/verifier/verifier.dockerfile.template` line 25 at r1](https://reviewable.io/reviews/gramineproject/contrib/34#-NNa0CqkDx6wamYodbYp:-NNa0CqkDx6wamYodbYq:b5d7lcj) ([raw file](https://github.com/gramineproject/contrib/blob/4f601a7e92bfe869d03e21d8e001b8f6623d826d/Curated-Apps/verifier/verifier.dockerfile.template#L25)):*
> ```
>     > /etc/apt/sources.list.d/intel-sgx.list \
>     && wget https://download.01.org/intel-sgx/sgx_repo/ubuntu/intel-sgx-deb.key \
>     && env APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=DontWarn apt-key add intel-sgx-deb.key
> ```

Why do you need this `WARN_ON_DANGREOUS_USAGE` variable?
___
*[`Curated-Apps/verifier/verifier.dockerfile.template` line 39 at r1](https://reviewable.io/reviews/gramineproject/contrib/34#-NNa-qoFBIOWmRHO9fhg:-NNa-qoFBIOWmRHO9fhh:b-c5emwi) ([raw file](https://github.com/gramineproject/contrib/blob/4f601a7e92bfe869d03e21d8e001b8f6623d826d/Curated-Apps/verifier/verifier.dockerfile.template#L39)):*
> ```
>     ./gramine-ratls-dcap_1.3.1-1_amd64.deb \
>     ./libcjson1_1.7.10-1.1_amd64.deb \
>     ./python3-toml_0.10.0-1_all.deb
> ```

Why do you need to download these packages explicitly (`libcjson`, `python3-toml`)? Isn't it enough to specify the exact version of `gramine-dcap` during apt install?

I mean, why wouldn't this be enough?
```
RUN apt-get install -y gramine-dcap=1.3.1
```


<!-- Sent from Reviewable.io -->

2023-02-06 09:36 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/34)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

___
*[`Curated-Apps/verifier/verifier.dockerfile.template` line 39 at r1](https://reviewable.io/reviews/gramineproject/contrib/34#-NNa-qoFBIOWmRHO9fhg:-NNa3NrV9GUJT5wP01pH:brb6m7c) ([raw file](https://github.com/gramineproject/contrib/blob/4f601a7e92bfe869d03e21d8e001b8f6623d826d/Curated-Apps/verifier/verifier.dockerfile.template#L39)):*
When I tried to use `RUN apt-get install -y gramine-dcap=1.3.1`, got error `E: Version '1.3.1' for 'gramine-dcap' was not found`

>Why do you need to download these packages explicitly (libcjson, python3-toml)
 `gramine-dcap_1.3.1-1_amd64.deb` have dependency on these packages and same packages are part of `gramine-dcap` package also. We did the same to fix the v1.3 package issue when we provided a temporary workaround, if you remember?


<!-- Sent from Reviewable.io -->

2023-02-06 11:02 UTC, mkow requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/34)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @jkr0103)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/contrib/34#-NNaNNyl2Nq_dGhViEg2):*
trailing backtick
___
*[`Curated-Apps/verifier/verifier.dockerfile.template` line 36 at r1](https://reviewable.io/reviews/gramineproject/contrib/34#-NNaNjj0CeF4D3uYLlfP:-NNaNjj10_7JRsu0E8R6:b-svrwy5) ([raw file](https://github.com/gramineproject/contrib/blob/4f601a7e92bfe869d03e21d8e001b8f6623d826d/Curated-Apps/verifier/verifier.dockerfile.template#L36)):*
> ```
> 
> RUN env DEBIAN_FRONTEND=noninteractive apt-get install -y \
>     ./gramine-dcap_1.3.1-1_amd64.deb \
> ```

This doesn't check the PGP signature of the packages, which the previous version did, although in a way which doesn't make much sense. The PGP key should be backed up in the repository, not downloaded over exactly the same channel as the packages.


<!-- Sent from Reviewable.io -->

2023-02-06 17:06 UTC, mkow requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/34)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @jkr0103)

___
*[`Curated-Apps/verifier/verifier.dockerfile.template` line 36 at r1](https://reviewable.io/reviews/gramineproject/contrib/34#-NNaNjj0CeF4D3uYLlfP:-NNbg7mX6gnTCgOekYym:b-a8vwb) ([raw file](https://github.com/gramineproject/contrib/blob/4f601a7e92bfe869d03e21d8e001b8f6623d826d/Curated-Apps/verifier/verifier.dockerfile.template#L36)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

I tried to verify the underlined packages and found these packages are not signed, I see these errors:

`$ dpkg-sig --verify gramine-dcap_1.3.1-1_amd64.deb
Processing gramine-dcap_1.3.1-1_amd64.deb...
NOSIG

$ debsig-verify -v gramine-dcap_1.3.1-1_amd64.deb
debsig: Starting verification for: gramine-dcap_1.3.1-1_amd64.deb
debsig: Origin Signature check failed. This deb might not be signed.
`

</blockquote></details>

I think on Debian the signature is on the whole repository, not the specific .deb files, or something like this. But the current version of the code definitely doesn't check anything.


<!-- Sent from Reviewable.io -->

2023-02-07 04:29 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/34)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @mkow)

___
*[`Curated-Apps/verifier/verifier.dockerfile.template` line 36 at r1](https://reviewable.io/reviews/gramineproject/contrib/34#-NNaNjj0CeF4D3uYLlfP:-NNe4roo8bHE5cQxLmEw:byjjruf) ([raw file](https://github.com/gramineproject/contrib/blob/4f601a7e92bfe869d03e21d8e001b8f6623d826d/Curated-Apps/verifier/verifier.dockerfile.template#L36)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think on Debian the signature is on the whole repository, not the specific .deb files, or something like this. But the current version of the code definitely doesn't check anything.
</blockquote></details>

Yes, with current approach we cannot have any check. I tried the two approaches, mentioned below but have issues:

Approach 1: using `1.3` instead of `bionic` gives error `packages have unmet dependencies`
```
RUN echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/gramine-keyring.gpg] https://packages.gramineproject.io/ 1.3 main' | tee /etc/apt/sources.list.d/gramine.list

RUN apt-get update

RUN  apt-get install -y gramine-dcap
```

Error: 
```
The following packages have unmet dependencies:
 gramine-dcap : Depends: libcjson1 (>= 1.7) but it is not installable
                Depends: python3-toml (>= 0.10) but it is not going to be installed
                Recommends: gramine-ratls-dcap but it is not going to be installed
                Recommends: gramine-ratls-epid but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
The command '/bin/sh -c apt-get install -y gramine-dcap' returned a non-zero code: 100

```

Approach 2: with this approach, packages will change to v1.4 under `bionic`. Hence we cannot stick to v1.3.1.

```
RUN echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/gramine-keyring.gpg] https://packages.gramineproject.io/ bionic main' | tee /etc/apt/sources.list.d/gramine.list

RUN apt-get update

RUN  apt-get install -y gramine-dcap=1.3.1-1~ubuntu0.18.04
```


<!-- Sent from Reviewable.io -->

2023-02-07 04:31 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/34)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @woju)

___
*[`Curated-Apps/verifier/verifier.dockerfile.template` line 36 at r1](https://reviewable.io/reviews/gramineproject/contrib/34#-NNaNjj0CeF4D3uYLlfP:-NNe84QNAHbaej4tqACs:b-o5ipja) ([raw file](https://github.com/gramineproject/contrib/blob/4f601a7e92bfe869d03e21d8e001b8f6623d826d/Curated-Apps/verifier/verifier.dockerfile.template#L36)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

Yes, with current approach we cannot have any check. I tried the two approaches, mentioned below but have issues:

Approach 1: using `1.3` instead of `bionic` gives error `packages have unmet dependencies`
```
RUN echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/gramine-keyring.gpg] https://packages.gramineproject.io/ 1.3 main' | tee /etc/apt/sources.list.d/gramine.list

RUN apt-get update

RUN  apt-get install -y gramine-dcap
```

Error: 
```
The following packages have unmet dependencies:
 gramine-dcap : Depends: libcjson1 (>= 1.7) but it is not installable
                Depends: python3-toml (>= 0.10) but it is not going to be installed
                Recommends: gramine-ratls-dcap but it is not going to be installed
                Recommends: gramine-ratls-epid but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
The command '/bin/sh -c apt-get install -y gramine-dcap' returned a non-zero code: 100

```

Approach 2: with this approach, packages will change to v1.4 under `bionic`. Hence we cannot stick to v1.3.1.

```
RUN echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/gramine-keyring.gpg] https://packages.gramineproject.io/ bionic main' | tee /etc/apt/sources.list.d/gramine.list

RUN apt-get update

RUN  apt-get install -y gramine-dcap=1.3.1-1~ubuntu0.18.04
```
</blockquote></details>

@woju , any suggestions?


<!-- Sent from Reviewable.io -->

2023-02-07 08:50 UTC, dimakuv requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/34)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @jkr0103 and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/34#-NNf2iG58GGGyo2TWJtQ:-NNf2iG58GGGyo2TWJtR:b7q524s) (no related file):*
An alternative change would be to git-clone & build & install Gramine, instead of using `.deb` packages.

I mean:
```
git clone https://github.com/gramineproject/gramine.git
cd gramine
git checkout v1.3.1
meson build ...
sudo ninja -C build/ install
```

This would be probably cleaner than what this PR tries to do.

@mkow Any preference? I don't mind the current PR (I don't care much).

___
___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/gramineproject/contrib/34#-NNf1lxM-WsEicr556b-):*
If we decide to merge this PR, I would change the message like this:
```
[Curated-Apps] Use .deb packages with exact version in verifier

Previously, the verifier dockerfile installed Gramine via `apt install gramine-dcap`.
However, this installs the latest version of Gramine, which may be incompatible with
the rest of Curated Apps project (currently assumes v1.3). There is no way to specify
the older version of Gramine in apt; i.e., `apt install gramine-dcap=1.2` doesn't work.
So this commit replaces `apt install` with a direct download & install of 
good-version `.deb` packages.

Signed-off-by: jkr0103 <jitender.kumar@intel.com>
```
___
*[`Curated-Apps/verifier/verifier.dockerfile.template` line 25 at r1](https://reviewable.io/reviews/gramineproject/contrib/34#-NNa0CqkDx6wamYodbYp:-NNf3B-E4yV52lFoXHFl:bglesdb) ([raw file](https://github.com/gramineproject/contrib/blob/4f601a7e92bfe869d03e21d8e001b8f6623d826d/Curated-Apps/verifier/verifier.dockerfile.template#L25)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

This is to supress the warning `Warning: apt-key output should not be parsed (stdout is not a terminal)`.
</blockquote></details>

I don't mind this, but I wonder if @woju knows how to fix it properly.
___
*[`Curated-Apps/verifier/verifier.dockerfile.template` line 36 at r1](https://reviewable.io/reviews/gramineproject/contrib/34#-NNaNjj0CeF4D3uYLlfP:-NNf0e8qASJGfKRwuazS:b-kol74p) ([raw file](https://github.com/gramineproject/contrib/blob/4f601a7e92bfe869d03e21d8e001b8f6623d826d/Curated-Apps/verifier/verifier.dockerfile.template#L36)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

@woju , any suggestions?
</blockquote></details>

Yes, I also noticed that our repository doesn't allow to install **older versions** of Gramine. I don't know if this was done on purpose (e.g. to force users to update for security reasons), or just nobody required it.

In general, even if we would like to deprecate older versions as quickly as possible, I think we should have a stepped approach to updates -- for example, keep the previous version for ~1 month, to give people time to update their manifests and workflows to the new version of Gramine.

@mkow @woju WDYT?


<!-- Sent from Reviewable.io -->

2023-02-07 16:04 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/34)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @jkr0103 and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/34#-NNf2iG58GGGyo2TWJtQ:-NNgbb6u8Qx3UPu3XhM3:bnebiux) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

An alternative change would be to git-clone & build & install Gramine, instead of using `.deb` packages.

I mean:
```
git clone https://github.com/gramineproject/gramine.git
cd gramine
git checkout v1.3.1
meson build ...
sudo ninja -C build/ install
```

This would be probably cleaner than what this PR tries to do.

@mkow Any preference? I don't mind the current PR (I don't care much).
</blockquote></details>

Outcome of an offline discussion with Woju: yes, the best solution is to git-clone and build manually.

@jkr0103 Sorry, but could you change this PR to use these manual build steps? Downloading .deb packages is too hacky.

___


<!-- Sent from Reviewable.io -->

2023-02-07 17:39 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/34)* status: 0 of 1 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/34#-NNf2iG58GGGyo2TWJtQ:-NNgxOkV7mM_Nw4AlVcq:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Outcome of an offline discussion with Woju: yes, the best solution is to git-clone and build manually.

@jkr0103 Sorry, but could you change this PR to use these manual build steps? Downloading .deb packages is too hacky.
</blockquote></details>

Done.

___


<!-- Sent from Reviewable.io -->

2023-02-08 09:03 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/34)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @jkr0103 and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/34#-NNf2iG58GGGyo2TWJtQ:-NNkFpfY8EPkYIMg0fr3:b-ucfknh) (no related file):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks!

___
___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/gramineproject/contrib/34#-NNf1lxM-WsEicr556b-):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

If we decide to merge this PR, I would change the message like this:
```
[Curated-Apps] Use .deb packages with exact version in verifier

Previously, the verifier dockerfile installed Gramine via `apt install gramine-dcap`.
However, this installs the latest version of Gramine, which may be incompatible with
the rest of Curated Apps project (currently assumes v1.3). There is no way to specify
the older version of Gramine in apt; i.e., `apt install gramine-dcap=1.2` doesn't work.
So this commit replaces `apt install` with a direct download & install of 
good-version `.deb` packages.

Signed-off-by: jkr0103 <jitender.kumar@intel.com>
```
</blockquote></details>

The message got stale now, I suggest this message now:
```
[Curated-Apps] Build Gramine manually with exact version in verifier

Previously, the verifier dockerfile installed Gramine via `apt install gramine-dcap`.
However, this installs the latest version of Gramine, which may be incompatible with
the rest of Curated Apps project (currently assumes v1.3). There is no reliable way to
specify the older version of Gramine in apt. So this commit replaces `apt install` with
a direct git-clone, build & install of Gramine v1.3.1.

Signed-off-by: jkr0103 <jitender.kumar@intel.com>
```
___
*[`Curated-Apps/verifier/verifier.dockerfile.template` line 36 at r1](https://reviewable.io/reviews/gramineproject/contrib/34#-NNaNjj0CeF4D3uYLlfP:-NNkFuG0DKJyLbh56lDq:b7ky3lx) ([raw file](https://github.com/gramineproject/contrib/blob/4f601a7e92bfe869d03e21d8e001b8f6623d826d/Curated-Apps/verifier/verifier.dockerfile.template#L36)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, I also noticed that our repository doesn't allow to install **older versions** of Gramine. I don't know if this was done on purpose (e.g. to force users to update for security reasons), or just nobody required it.

In general, even if we would like to deprecate older versions as quickly as possible, I think we should have a stepped approach to updates -- for example, keep the previous version for ~1 month, to give people time to update their manifests and workflows to the new version of Gramine.

@mkow @woju WDYT?
</blockquote></details>

Orthogonal to this PR, I'm accepting this comment.
___
*[`Curated-Apps/verifier/verifier.dockerfile.template` line 60 at r3](https://reviewable.io/reviews/gramineproject/contrib/34#-NNkF6Qw4h_ehEfH-Kfe:-NNkF6Qx41tcDnrT001I:b7382yg) ([raw file](https://github.com/gramineproject/contrib/blob/5b5e38d2f56901327724cd8ea48d7f250a14bbd5/Curated-Apps/verifier/verifier.dockerfile.template#L60)):*
> ```
>         \
>        -Dsgx_driver=upstream -Dsgx_driver_include_path=/gramine/driver \
>         \
> ```

I'm not sure why you added these empty lines (with only `\`), but I guess for readability? I don't like empty lines here, but I'm not blocking.


<!-- Sent from Reviewable.io -->

2023-02-10 11:00 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/34)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @jkr0103 and @mkow)

___
*[`Curated-Apps/verifier/verifier.dockerfile.template` line 25 at r1](https://reviewable.io/reviews/gramineproject/contrib/34#-NNa0CqkDx6wamYodbYp:-NNuwXHdDem1Yujsy7P2:bnyz26z) ([raw file](https://github.com/gramineproject/contrib/blob/4f601a7e92bfe869d03e21d8e001b8f6623d826d/Curated-Apps/verifier/verifier.dockerfile.template#L25)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't mind this, but I wonder if @woju knows how to fix it properly.
</blockquote></details>

`apt-key` is deprecated. You should rename `.key` to `.asc` and then either:
- drop into `/etc/apt/trusted.gpg.d`,
- drop into `/usr/share/keyrings` and use `[signed-by]` like we do in 1.4 quickstart.rst:

```
   sudo curl -fsSLo /usr/share/keyrings/intel-sgx-deb.asc https://download.01.org/intel-sgx/sgx_repo/ubuntu/intel-sgx-deb.key
   echo "deb [arch=amd64 signed-by=/usr/share/keyrings/intel-sgx-deb.asc] https://download.01.org/intel-sgx/sgx_repo/ubuntu focal main" \
   | sudo tee /etc/apt/sources.list.d/intel-sgx.list
```

Also: if you're building docker image, you shouldn't download the key every time, but you should check it into your repo and `COPY` into the image. That way you can verify it so it suddenly won't change from under you.
___
*[`Curated-Apps/verifier/verifier.dockerfile.template` line 36 at r1](https://reviewable.io/reviews/gramineproject/contrib/34#-NNaNjj0CeF4D3uYLlfP:-NNuxZGh5u4lPYFg64ht:b-4x3mht) ([raw file](https://github.com/gramineproject/contrib/blob/4f601a7e92bfe869d03e21d8e001b8f6623d826d/Curated-Apps/verifier/verifier.dockerfile.template#L36)):*
> I think on Debian the signature is on the whole repository,

This is correct. The packages themselves are usually not signed. I can start doing that from 1.4, but 1.3.1 packages won't be retroactively signed.

> using `1.3` instead of `bionic` gives error `packages have unmet dependencies`

Yes, `1.3` repo is for `bullseye` and `jammy`. It can't be made to work on bionic without messing with glibc, which would amount to just updating the whole distro.

The correct approach would be to fix the packages to work with 1.4. Create a branch, change the repo to `unstable-bionic` and it will give you `1.4~rc` packages. If something breaks, fix it in a separate commits. When 1.4 happens, drop the commit that changed repo to unstable and you'll have a PR ready to be merged just in time.


<!-- Sent from Reviewable.io -->

2023-02-14 09:18 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/34)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`Curated-Apps/verifier/verifier.dockerfile.template` line 36 at r1](https://reviewable.io/reviews/gramineproject/contrib/34#-NNaNjj0CeF4D3uYLlfP:-NOECyf98qL0bwqwKfnK:b-zcjvte) ([raw file](https://github.com/gramineproject/contrib/blob/4f601a7e92bfe869d03e21d8e001b8f6623d826d/Curated-Apps/verifier/verifier.dockerfile.template#L36)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't mind.
</blockquote></details>

Thanks
___
*[`Curated-Apps/verifier/verifier.dockerfile.template` line 21 at r4](https://reviewable.io/reviews/gramineproject/contrib/34#-NOEAzR-CXWLNndk4aen:-NOEC8g4BGYpFIaV4GGD:b1pcn2o) ([raw file](https://github.com/gramineproject/contrib/blob/3366d838121392352d8c03158e78530d329d217d/Curated-Apps/verifier/verifier.dockerfile.template#L21)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This still works, right? You're downloading a version of `az-dcap-client` that was built for Ubuntu 18.04, but we're in a Ubuntu 22.04 Docker. If this works in practice, I have no problems.
</blockquote></details>

yes it works but it required `libssl1.1` dependency whereas `ubuntu22.04` have `libssl1.3` bydefault. I tried `az-dcap-client` based on `20.04` also, but that also reported same issue requiring `libssl1.1`. Both works after installing `libssl1.1`


<!-- Sent from Reviewable.io -->

2023-02-14 13:26 UTC, mkow requested changes
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/34)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @jkr0103)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/34#-NOF5W0c0IY8CdnmXSNo:-NOF5W0c0IY8CdnmXSNp:b6igj35) (no related file):*
FYI: Gramine v1.3 shouldn't be used in production, because v1.4 fixes at least one security issue.

___
___
*[`Curated-Apps/verifier/helper.sh` line 52 at r4](https://reviewable.io/reviews/gramineproject/contrib/34#-NOF5B-988JvxT0clesI:-NOF5B-AEKXijBOUsk74:b-hameu4) ([raw file](https://github.com/gramineproject/contrib/blob/3366d838121392352d8c03158e78530d329d217d/Curated-Apps/verifier/helper.sh#L52)):*
> ```Shell
> fi
> 
> if [ ! -f "gramine-keyring.gpg" ]; then
> ```

These should be included in the repository, not downloaded.


<!-- Sent from Reviewable.io -->

2023-02-14 13:27 UTC, woju requested changes
> also not sure if  gramine-dcap package itself gets depricated with v1.4.

It will be in the repos for the forseeable future. You should change to `gramine` after `1.4`, but there would be no problem if you didn't.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/34#-:-NOF5cgp3qcPZKV73Abh:b-34qpof)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @jkr0103)

___
*[`Curated-Apps/verifier/helper.sh` line 55 at r4](https://reviewable.io/reviews/gramineproject/contrib/34#-NOF3M0IDlmylQIV_TNj:-NOF3M0IDlmylQIV_TNk:b-vx0d8g) ([raw file](https://github.com/gramineproject/contrib/blob/3366d838121392352d8c03158e78530d329d217d/Curated-Apps/verifier/helper.sh#L55)):*
> ```Shell
>     curl -fsSLo gramine-keyring.gpg https://packages.gramineproject.io/gramine-keyring.gpg
> fi
> ```

No, I insist you commit those keys to repo, so we can review them and see if they weren't changed. This thing still relies on just HTTPS on integrity of those keys and packages signed by them. We can do better.
___
*[`Curated-Apps/verifier/verifier.dockerfile.template` line 25 at r1](https://reviewable.io/reviews/gramineproject/contrib/34#-NNa0CqkDx6wamYodbYp:-NOF54eg6I05WxdovFTw:bckj90v) ([raw file](https://github.com/gramineproject/contrib/blob/4f601a7e92bfe869d03e21d8e001b8f6623d826d/Curated-Apps/verifier/verifier.dockerfile.template#L25)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I see that @jkr0103 implemented this (though downloading the key locally, not in one of the system paths).
</blockquote></details>

This diff OK, so resolving, but I've blocked the downloading keys in other thread.
___
*[`Curated-Apps/verifier/verifier.dockerfile.template` line 21 at r4](https://reviewable.io/reviews/gramineproject/contrib/34#-NOF4GhXAtbQtkYvIlhd:-NOF4GhXAtbQtkYvIlhe:bmdx9gt) ([raw file](https://github.com/gramineproject/contrib/blob/3366d838121392352d8c03158e78530d329d217d/Curated-Apps/verifier/verifier.dockerfile.template#L21)):*
Oh, this thing also should be 1) add key, 2) add repo, 3) `apt-get install`, not just `wget`ing `.deb` and `dpkg -i`.

Here are docs of MS' repos: https://packages.microsoft.com/docs/readme.txt , and among them:
> The paths to individual packages are subject to change.

Also, seriously, don't rely on WebPKI on security.

Any other `wget && dpkg -i` or `curl | sudo sh` did I miss?


<!-- Sent from Reviewable.io -->

2023-02-14 13:59 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/34)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @jkr0103 and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/34#-NOF5W0c0IY8CdnmXSNo:-NOFBmH5--cvo7dZW-dy:b-zl4s1) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

FYI: Gramine v1.3 shouldn't be used in production, because v1.4 fixes at least one security issue.
</blockquote></details>

I think the point here is to just make Curated Apps works for now (currently broken), and then move to v1.4 at normal pace.

___
___
*[`Curated-Apps/verifier/helper.sh` line 47 at r4](https://reviewable.io/reviews/gramineproject/contrib/34#-NOFCcibAG3ZQjxwbMNX:-NOFCcibAG3ZQjxwbMNY:bk4yxcp) ([raw file](https://github.com/gramineproject/contrib/blob/3366d838121392352d8c03158e78530d329d217d/Curated-Apps/verifier/helper.sh#L47)):*
> ```Shell
>     echo 'CMD ["'$3'"]' >> verifier.dockerfile
> fi
> ```

We'll also need to commit the `https://packages.microsoft.com/keys/microsoft.asc` key in the repo.
___
*[`Curated-Apps/verifier/verifier.dockerfile.template` line 21 at r4](https://reviewable.io/reviews/gramineproject/contrib/34#-NOF4GhXAtbQtkYvIlhd:-NOFCziF0x5ldcDNbqBQ:b-gxt2v6) ([raw file](https://github.com/gramineproject/contrib/blob/3366d838121392352d8c03158e78530d329d217d/Curated-Apps/verifier/verifier.dockerfile.template#L21)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Oh, this thing also should be 1) add key, 2) add repo, 3) `apt-get install`, not just `wget`ing `.deb` and `dpkg -i`.

Here are docs of MS' repos: https://packages.microsoft.com/docs/readme.txt , and among them:
> The paths to individual packages are subject to change.

Also, seriously, don't rely on WebPKI on security.

Any other `wget && dpkg -i` or `curl | sudo sh` did I miss?
</blockquote></details>

I think what Woju means is to do like this:
```
echo "deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft.asc] https://packages.microsoft.com/ubuntu/20.04/prod focal main" | tee /etc/apt/sources.list.d/msprod.list
apt update
apt install -y az-dcap-client
```

This is just a rought snippet, please make it uniform with all other places in your PR (like adding `DEBIAN_FRONTEND ...`)


<!-- Sent from Reviewable.io -->

2023-02-14 15:06 UTC, dimakuv approved these changes
> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/34)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @jkr0103, @mkow, and @woju)



<!-- Sent from Reviewable.io -->

2023-02-14 15:26 UTC, mkow submitted a review, later dismissed
> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/34)* status: all files reviewed, 3 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @jkr0103 and @woju)



<!-- Sent from Reviewable.io -->

2023-02-14 16:49 UTC, woju requested changes
> Reviewed 4 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/34)* status: all files reviewed, 3 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @jkr0103)

___
*[`Curated-Apps/verifier/verifier.dockerfile.template` line 21 at r4](https://reviewable.io/reviews/gramineproject/contrib/34#-NOF4GhXAtbQtkYvIlhd:-NOFlyJR16W4ExfGzIc_:bjd1eds) ([raw file](https://github.com/gramineproject/contrib/blob/3366d838121392352d8c03158e78530d329d217d/Curated-Apps/verifier/verifier.dockerfile.template#L21)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It says `.../ubuntu/20.04/prod focal main`, but the Dockerfile is `FROM ubuntu:22.04` — is this correct?

Also, you can add all repos at once and then do `apt-get update && apt-get install` all packages. That'll be faster and less hammering the servers.
___
*[`Curated-Apps/verifier/keys/gramine-keyring.gpg` line 0 at r5](https://reviewable.io/reviews/gramineproject/contrib/34#-NOFoE771ijrI5ZP2tpl:-NOFoE771ijrI5ZP2tpm:b-xlg3wo) ([raw file](https://github.com/gramineproject/contrib/blob/b65a33bbfc25a60aa3e5d6f31170d9882be93337/Curated-Apps/verifier/keys/gramine-keyring.gpg#L0)):*
Gramine key matches.
___
*[`Curated-Apps/verifier/keys/gramine-keyring.gpg` line 0 at r5](https://reviewable.io/reviews/gramineproject/contrib/34#-NOFoJNr4YYDZZ4fDQRD:-NOFoJNr4YYDZZ4fDQRE:bdhcu3f) ([raw file](https://github.com/gramineproject/contrib/blob/b65a33bbfc25a60aa3e5d6f31170d9882be93337/Curated-Apps/verifier/keys/gramine-keyring.gpg#L0)):*
Are you sure `Curated-Apps/verifier` would be the only place where you need those keys (esp. gramine)? If not, I'd suggest to put `keys/` directory in the root of the repo. Not blocking.
___
*[`Curated-Apps/verifier/keys/intel-sgx-deb.asc` line 1 at r5](https://reviewable.io/reviews/gramineproject/contrib/34#-NOFom8R3l6BMTt5-KaQ:-NOFom8R3l6BMTt5-KaR:b58hgnu) ([raw file](https://github.com/gramineproject/contrib/blob/b65a33bbfc25a60aa3e5d6f31170d9882be93337/Curated-Apps/verifier/keys/intel-sgx-deb.asc#L1)):*
> ```AsciiDoc
> -----BEGIN PGP PUBLIC KEY BLOCK-----
> ```

Matches my copy, downloaded some time ago.
___
*[`Curated-Apps/verifier/keys/microsoft.asc` line 1 at r5](https://reviewable.io/reviews/gramineproject/contrib/34#-NOFotxY9LpDQc_Qu-1X:-NOFotxY9LpDQc_Qu-1Y:b2wr7gm) ([raw file](https://github.com/gramineproject/contrib/blob/b65a33bbfc25a60aa3e5d6f31170d9882be93337/Curated-Apps/verifier/keys/microsoft.asc#L1)):*
> ```AsciiDoc
> -----BEGIN PGP PUBLIC KEY BLOCK-----
> ```

Can't review, don't have a copy.


<!-- Sent from Reviewable.io -->

2023-02-14 19:03 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/34)* status: 4 of 5 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @woju)

___
*[`Curated-Apps/verifier/verifier.dockerfile.template` line 21 at r4](https://reviewable.io/reviews/gramineproject/contrib/34#-NOF4GhXAtbQtkYvIlhd:-NOGHHnL3FKuXJJCqxTx:bslzyjq) ([raw file](https://github.com/gramineproject/contrib/blob/3366d838121392352d8c03158e78530d329d217d/Curated-Apps/verifier/verifier.dockerfile.template#L21)):*
>It says .../ubuntu/20.04/prod focal main, but the Dockerfile is FROM ubuntu:22.04 — is this correct?
Microsoft doesn't release `az-dcap-client` package for ubuntu22.04. But package intended for ubuntu 20.04 works here on 22.04 requiring additional dependency `libssl1.1`.

>Also, you can add all repos at once and then do apt-get update && apt-get install all packages.

I couldn't combine all `apt-get update && apt-get install`, faced below error but reduced one.
___
*[`Curated-Apps/verifier/keys/gramine-keyring.gpg` line  at r5](https://reviewable.io/reviews/gramineproject/contrib/34#-NOFoJNr4YYDZZ4fDQRD:-NOGIBBq10mLfdrYKzJD:bobhr5a) ([raw file](https://github.com/gramineproject/contrib/blob/b65a33bbfc25a60aa3e5d6f31170d9882be93337/Curated-Apps/verifier/keys/gramine-keyring.gpg#L)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Are you sure `Curated-Apps/verifier` would be the only place where you need those keys (esp. gramine)? If not, I'd suggest to put `keys/` directory in the root of the repo. Not blocking.
</blockquote></details>

As of now we don't see a need at root level, we can see it at later point of time when need arises but moving the key is not straight forward. If we move it to root of repo than it goes out of docker's build context and docker build is not able to find the keys.


<!-- Sent from Reviewable.io -->

2023-02-15 05:01 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/34)* status: 4 of 5 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @woju)

___
*[`Curated-Apps/verifier/verifier.dockerfile.template` line 21 at r4](https://reviewable.io/reviews/gramineproject/contrib/34#-NOF4GhXAtbQtkYvIlhd:-NOIRa-Z7RLLiHnae1j5:b-c8nylk) ([raw file](https://github.com/gramineproject/contrib/blob/3366d838121392352d8c03158e78530d329d217d/Curated-Apps/verifier/verifier.dockerfile.template#L21)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

>It says .../ubuntu/20.04/prod focal main, but the Dockerfile is FROM ubuntu:22.04 — is this correct?
Microsoft doesn't release `az-dcap-client` package for ubuntu22.04. But package intended for ubuntu 20.04 works here on 22.04 requiring additional dependency `libssl1.1`.

>Also, you can add all repos at once and then do apt-get update && apt-get install all packages.

I couldn't combine all `apt-get update && apt-get install`, faced below error but reduced one.
</blockquote></details>

Err:1 https://packages.microsoft.com/ubuntu/20.04/prod focal InRelease
  Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown.  Could not handshake: Error in the certificate verification. [IP: 10.1.192.48 912]
Err:3 https://download.01.org/intel-sgx/sgx_repo/ubuntu jammy InRelease
  Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown.  Could not handshake: Error in the certificate verification. [IP: 10.1.192.48 912]
Fetched 28.2 MB in 8s (3726 kB/s)
Reading package lists...
W: https://packages.microsoft.com/ubuntu/20.04/prod/dists/focal/InRelease: No system certificates available. Try installing ca-certificates.
W: https://download.01.org/intel-sgx/sgx_repo/ubuntu/dists/jammy/InRelease: No system certificates available. Try installing ca-certificates.
W: https://packages.microsoft.com/ubuntu/20.04/prod/dists/focal/InRelease: No system certificates available. Try installing ca-certificates.
W: https://download.01.org/intel-sgx/sgx_repo/ubuntu/dists/jammy/InRelease: No system certificates available. Try installing ca-certificates.
W: https://packages.microsoft.com/ubuntu/20.04/prod/dists/focal/InRelease: No system certificates available. Try installing ca-certificates.
W: https://download.01.org/intel-sgx/sgx_repo/ubuntu/dists/jammy/InRelease: No system certificates available. Try installing ca-certificates.
W: https://packages.microsoft.com/ubuntu/20.04/prod/dists/focal/InRelease: No system certificates available. Try installing ca-certificates.
W: https://download.01.org/intel-sgx/sgx_repo/ubuntu/dists/jammy/InRelease: No system certificates available. Try installing ca-certificates.
W: Failed to fetch https://download.01.org/intel-sgx/sgx_repo/ubuntu/dists/jammy/InRelease  Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown.  Could not handshake: Error in the certificate verification. [IP: 10.1.192.48 912]
W: Failed to fetch https://packages.microsoft.com/ubuntu/20.04/prod/dists/focal/InRelease  Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown.  Could not handshake: Error in the certificate verification. [IP: 10.1.192.48 912]
W: Some index files failed to download. They have been ignored, or old ones used instead.


<!-- Sent from Reviewable.io -->

2023-02-15 09:39 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/34)* status: 4 of 5 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @woju)

___
*[`Curated-Apps/verifier/verifier.dockerfile.template` line 21 at r4](https://reviewable.io/reviews/gramineproject/contrib/34#-NOF4GhXAtbQtkYvIlhd:-NOJPkdRBYrb3T_dRgkj:b-civr8y) ([raw file](https://github.com/gramineproject/contrib/blob/3366d838121392352d8c03158e78530d329d217d/Curated-Apps/verifier/verifier.dockerfile.template#L21)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

Err:1 https://packages.microsoft.com/ubuntu/20.04/prod focal InRelease
  Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown.  Could not handshake: Error in the certificate verification. [IP: 10.1.192.48 912]
Err:3 https://download.01.org/intel-sgx/sgx_repo/ubuntu jammy InRelease
  Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown.  Could not handshake: Error in the certificate verification. [IP: 10.1.192.48 912]
Fetched 28.2 MB in 8s (3726 kB/s)
Reading package lists...
W: https://packages.microsoft.com/ubuntu/20.04/prod/dists/focal/InRelease: No system certificates available. Try installing ca-certificates.
W: https://download.01.org/intel-sgx/sgx_repo/ubuntu/dists/jammy/InRelease: No system certificates available. Try installing ca-certificates.
W: https://packages.microsoft.com/ubuntu/20.04/prod/dists/focal/InRelease: No system certificates available. Try installing ca-certificates.
W: https://download.01.org/intel-sgx/sgx_repo/ubuntu/dists/jammy/InRelease: No system certificates available. Try installing ca-certificates.
W: https://packages.microsoft.com/ubuntu/20.04/prod/dists/focal/InRelease: No system certificates available. Try installing ca-certificates.
W: https://download.01.org/intel-sgx/sgx_repo/ubuntu/dists/jammy/InRelease: No system certificates available. Try installing ca-certificates.
W: https://packages.microsoft.com/ubuntu/20.04/prod/dists/focal/InRelease: No system certificates available. Try installing ca-certificates.
W: https://download.01.org/intel-sgx/sgx_repo/ubuntu/dists/jammy/InRelease: No system certificates available. Try installing ca-certificates.
W: Failed to fetch https://download.01.org/intel-sgx/sgx_repo/ubuntu/dists/jammy/InRelease  Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown.  Could not handshake: Error in the certificate verification. [IP: 10.1.192.48 912]
W: Failed to fetch https://packages.microsoft.com/ubuntu/20.04/prod/dists/focal/InRelease  Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown.  Could not handshake: Error in the certificate verification. [IP: 10.1.192.48 912]
W: Some index files failed to download. They have been ignored, or old ones used instead.
</blockquote></details>

I analyzed if further and found that `update-ca-certificates`  program should execute before making any change to `/etc/apt/sources.list.d`.  I am not sure if that's specific to `ubuntu:22.04` docker image.

`update-ca-certificates` get triggered automatically  with installation of packages `ca-certificates/curl/git`.

Hence we cannot combine all `apt-get update && apt-get install` into one, and need atleast two.


<!-- Sent from Reviewable.io -->

2023-02-15 10:06 UTC, jkr0103 reviewed
yes, we have that in plan, when `Curated-Apps` starts pointing to v1.4 gramine.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/34#-:-NOJX2YeAxL1U2rw08Gd:b-rueyow)* status: 0 of 5 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @woju)

___
*[`Curated-Apps/verifier/keys/gramine-keyring.gpg` line  at r5](https://reviewable.io/reviews/gramineproject/contrib/34#-NOFoJNr4YYDZZ4fDQRD:-NOJXGmb48rgbAqk4eCU:b1vkl8y) ([raw file](https://github.com/gramineproject/contrib/blob/b65a33bbfc25a60aa3e5d6f31170d9882be93337/Curated-Apps/verifier/keys/gramine-keyring.gpg#L)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

As of now we don't see a need at root level, we can see it at later point of time when need arises but moving the key is not straight forward. If we move it to root of repo than it goes out of docker's build context and docker build is not able to find the keys.
</blockquote></details>

I changed the docker build context directory to root directory, that worked, hence I moved the `keys` to root directory that is `Curated-Apps`.


<!-- Sent from Reviewable.io -->

2023-02-15 11:23 UTC, woju approved these changes
> Reviewed 1 of 1 files at r6, 3 of 4 files at r7.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/34)* status: 4 of 5 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`Curated-Apps/verifier/verifier.dockerfile.template` line 21 at r4](https://reviewable.io/reviews/gramineproject/contrib/34#-NOF4GhXAtbQtkYvIlhd:-NOJnpbh5_bDjDXegGju:b-hyce3g) ([raw file](https://github.com/gramineproject/contrib/blob/3366d838121392352d8c03158e78530d329d217d/Curated-Apps/verifier/verifier.dockerfile.template#L21)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

I analyzed if further and found that `update-ca-certificates`  program should execute before making any change to `/etc/apt/sources.list.d`.  I am not sure if that's specific to `ubuntu:22.04` docker image.

`update-ca-certificates` get triggered automatically  with installation of packages `ca-certificates/curl/git`.

Hence we cannot combine all `apt-get update && apt-get install` into one, and need atleast two.
</blockquote></details>

This is OK. You need `ca-certificates` package installed before you use any `https://` repos (all three custom repos used here are served over https). So yes, there will be `apt-get update` twice.


<!-- Sent from Reviewable.io -->

2023-02-15 12:07 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r6, 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/34)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`Curated-Apps/verifier/verifier.dockerfile.template` line 21 at r4](https://reviewable.io/reviews/gramineproject/contrib/34#-NOF4GhXAtbQtkYvIlhd:-NOJxpwr1qKaZ_32Kp1q:baw9j0o) ([raw file](https://github.com/gramineproject/contrib/blob/3366d838121392352d8c03158e78530d329d217d/Curated-Apps/verifier/verifier.dockerfile.template#L21)):*
> It says `.../ubuntu/20.04/prod focal main`, but the Dockerfile is `FROM ubuntu:22.04` — is this correct?

Yes, that's correct (Jitender missed to answer this part). That's because `az-dcap-client` is not available among 22.04 packages. So we must install from 20.04.


<!-- Sent from Reviewable.io -->

2023-02-15 12:12 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/34)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/gramineproject/contrib/34#-NNf1lxM-WsEicr556b-):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

And new message again:

```
[Curated-Apps] Use .deb packages with exact version in verifier

Previously, the verifier dockerfile installed Gramine from the repo
`https://packages.gramineproject.io/ bionic` (Ubuntu 20.04). However, now this
repo contains Gramine v1.4, which is incompatible with the rest of Curated
Apps project (currently assumes v1.3). So update the dockerfile to install from
the repo `https://packages.gramineproject.io/ 1.3`.

Signed-off-by: jkr0103 <jitender.kumar@intel.com>
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-15 14:06 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r6, 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/34)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-02-15 14:50 UTC, merged