[Curated-Apps] Update Tensorflow base image to Ubuntu 20.04; Copyright to 2023
gramineproject/contrib pull request #37
Opened 2023-03-07 06:41 UTC by svenkata9

This PR updates the TFS base image to use Ubuntu 20.04 (since Ubuntu 18.04 will be seeing EOL soon). It also updates the copyright header to 2023.

2023-03-07 09:38 UTC, dimakuv requested changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/37)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @svenkata9)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/contrib/37#-NPvQlZ06N1cTPFcFLf2):*
The line is too long. I would move the second part to the commit body message, since it's less important. Like this:
```
[Curated-Apps] Update Tensorflow base image to Ubuntu 20.04

Also change copyright to 2023.
```

We can do it during final rebase, or you can do it now (via rebase + force-push).


<!-- Sent from Reviewable.io -->

2023-03-07 09:44 UTC, svenkata9 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/37)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/contrib/37#-NPvQlZ06N1cTPFcFLf2):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The line is too long. I would move the second part to the commit body message, since it's less important. Like this:
```
[Curated-Apps] Update Tensorflow base image to Ubuntu 20.04

Also change copyright to 2023.
```

We can do it during final rebase, or you can do it now (via rebase + force-push).
</blockquote></details>

ACK. Can we do during final rebase?


<!-- Sent from Reviewable.io -->

2023-03-07 09:49 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/37)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @svenkata9)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/contrib/37#-NPvQlZ06N1cTPFcFLf2):*
<details><summary><i>Previously, svenkata9 (Sankaranarayanan Venkatasubramanian) wrote…</i></summary><blockquote>

ACK. Can we do during final rebase?
</blockquote></details>

Sure


<!-- Sent from Reviewable.io -->

2023-03-07 17:57 UTC, woju submitted a review, later dismissed
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/37)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @svenkata9)



<!-- Sent from Reviewable.io -->

2023-03-07 23:57 UTC, mkow requested changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/37)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @svenkata9)

___
*[`Curated-Apps/workloads/tensorflow-serving/tensorflow-serving-gsc.dockerfile.template` line 2 at r1](https://reviewable.io/reviews/gramineproject/contrib/37#-NPyU6fs0fbsxowI1KAK:-NPyU6fs0fbsxowI1KAL:byrryb4) ([raw file](https://github.com/gramineproject/contrib/blob/52b9c04dfd52254ce1682a34071bc7c48281803a/Curated-Apps/workloads/tensorflow-serving/tensorflow-serving-gsc.dockerfile.template#L2)):*
> ```
> # SPDX-License-Identifier: LGPL-3.0-or-later
> # Copyright (C) 2023 Intel Corporation
> ```

Wait, that's not how copyrights work. You can't arbitrarily change the year when the copyrighted material was created. This would be ok only if Intel changed this file significantly in 2023, is that the case? If so, then the change is ok, but the description is not - please describe in the commit message that some other commit accidentally forgot to update the copyrights and quote its one-liner (and in such case this PR such be split into 2 commits).

Some more info about how it works: https://gramine.readthedocs.io/en/latest/devel/contributing.html#copyrights-and-licenses


<!-- Sent from Reviewable.io -->

2023-03-08 10:17 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/37)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @svenkata9)

___
*[`Curated-Apps/workloads/tensorflow-serving/tensorflow-serving-gsc.dockerfile.template` line 2 at r1](https://reviewable.io/reviews/gramineproject/contrib/37#-NPyU6fs0fbsxowI1KAK:-NQ-ht9Z4NpnkGEW-I4A:b-bgwyar) ([raw file](https://github.com/gramineproject/contrib/blob/52b9c04dfd52254ce1682a34071bc7c48281803a/Curated-Apps/workloads/tensorflow-serving/tensorflow-serving-gsc.dockerfile.template#L2)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Wait, that's not how copyrights work. You can't arbitrarily change the year when the copyrighted material was created. This would be ok only if Intel changed this file significantly in 2023, is that the case? If so, then the change is ok, but the description is not - please describe in the commit message that some other commit accidentally forgot to update the copyrights and quote its one-liner (and in such case this PR such be split into 2 commits).

Some more info about how it works: https://gramine.readthedocs.io/en/latest/devel/contributing.html#copyrights-and-licenses
</blockquote></details>

@mkow is right, I didn't pay close attention.

What I can see is this:
- `tensorflow-serving-gsc.dockerfile.template` was last changed in 2022 (**no copyright change**)
-  `tensorflow-serving.manifest.template` had significant changes in 2023 (**copyright change ok**)
-  `base_image_helper/Dockerfile` is changed in this PR  (**copyright change ok**)
-  `base_image_helper/helper` was last changed in 2022 (**no copyright change**)

@svenkata9 Could we revert the copyright changes in the two unmodified files mentioned above?

(I based this on looking at git history here: https://github.com/gramineproject/contrib/tree/master/Curated-Apps/workloads/tensorflow-serving)


<!-- Sent from Reviewable.io -->

2023-03-13 08:52 UTC, dimakuv submitted a review, later dismissed
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/37)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2023-03-13 10:36 UTC, mkow submitted a review, later dismissed
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/37)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-03-13 11:21 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/37)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/contrib/37#-NPvQlZ06N1cTPFcFLf2):*
<details><summary><i>Previously, svenkata9 (Sankaranarayanan Venkatasubramanian) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

Also, Michal requested two split into two commits, since these are independent changes. So I did that.


<!-- Sent from Reviewable.io -->

2023-03-13 11:33 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/37)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-03-13 11:49 UTC, merged