[Integrations/azure] Add RA-TLS/SecretProv libs for MAA
gramineproject/contrib pull request #38
Opened 2023-03-09 10:34 UTC by dimakuv

This PR adds the sources, documentation and tests for `libra_tls_verify_maa.so` and `libsecret_prov_verify_maa.so` libraries, used for integration of Gramine with Microsoft Azure Attestation.

This PR is a re-creation of https://github.com/gramineproject/gramine/pull/652. That original PR added MAA versions of RA-TLS and SecretProv libs **inside core Gramine**. Now this new PR adds MAA versions as **plugins**, which are currently hosted in the `contrib` repo.

For design and other useful info, see https://github.com/gramineproject/gramine/issues/626

I manually verified this PR on a MS Azure CC VM, with the `https://sharedcus.cus.attest.azure.net` default attestation provider. See the README with explanations on `ra-tls-mbedtls` and `ra-tls-secret-prov` examples.

2023-03-09 10:39 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/38)* status: 0 of 19 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/38#-NQ4w7y62gvCdHEQJTRn:-NQ4w7y62gvCdHEQJTRo:b-8owrxy) (no related file):*
This PR requires https://github.com/gramineproject/gramine/pull/1218 from core Gramine.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/38#-NQ4wJeO9ECGChxKZhVj:-NQ4wJeO9ECGChxKZhVk:bby2qqt) (no related file):*
Note that MAA version of RA-TLS and SecretProv requires `libcurl` to send HTTPS requests. Since I wanted a statically linked and minimized `libcurl` as a dependency, I re-used the Meson Subprojects functionality from core Gramine (the files under `subprojects/` are almost identical to the ones used in core Gramine).

Also, because `libcurl` needs to use some SSL/TLS library, I used the same trick as in core Gramine -- I'm building a minimized `mbedtls` lib and supply it as a dependency library for `libcurl`.

This is code duplication, but this is what @woju requested me to do, see https://github.com/gramineproject/gramine/pull/1218#pullrequestreview-1330724995

___


<!-- Sent from Reviewable.io -->

2023-03-09 12:42 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/38)* status: 0 of 19 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/38#-NQ5Nz3eClMk2__AI8dN:-NQ5Nz3fAqSwHqOvfiHD:b-is4uic) (no related file):*
I verified that this PR works and that the README is correct.

I tested on a MS Azure VM with `https://sharedcus.cus.attest.azure.net` default MAA provider.

___


<!-- Sent from Reviewable.io -->

2023-03-14 14:10 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/38)* status: 0 of 19 files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/38#-NQ4w7y62gvCdHEQJTRn:-NQVSKwdCcv4eEeuErsz:bk64ati) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This PR requires https://github.com/gramineproject/gramine/pull/1218 from core Gramine.
</blockquote></details>

That PR was merged, so I'm resolving this comment.

___


<!-- Sent from Reviewable.io -->

2023-03-16 03:26 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/38)* status: 0 of 19 files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`Integrations/azure/ra_tls_maa/README.md` line 96 at r2](https://reviewable.io/reviews/gramineproject/contrib/38#-NQc5J618-Ip-MQsvGZu:-NQc5J618-Ip-MQsvGZv:b-81pw60) ([raw file](https://github.com/gramineproject/contrib/blob/f2f485b2b81faaaeac06576e5b99c155b7ba9416/Integrations/azure/ra_tls_maa/README.md#L96)):*
> ```Markdown
> we use the meson build system:
> ```sh
> meson setup build/ --buildtype=release
> ```

If we install Gramine into other places w/ `--prefix`, we may require here to have the same input. Similar for `libdir`.



_Code quote:_
```Markdown
meson setup build/ --buildtype=release
```
___
*[`Integrations/azure/ra_tls_maa/README.md` line 117 at r2](https://reviewable.io/reviews/gramineproject/contrib/38#-NQbyp1w12G_6KJSvY_D:-NQbyp1x3DHAOXi_g1Ws:b32wxs) ([raw file](https://github.com/gramineproject/contrib/blob/f2f485b2b81faaaeac06576e5b99c155b7ba9416/Integrations/azure/ra_tls_maa/README.md#L117)):*
> ```Markdown
> examples available in Gramine.
> 
> To be able tu run these tests, the machine must run on the Azure cloud, with
> ```

to



_Code quote:_
```Markdown
tu
```
___
*[`Integrations/azure/ra_tls_maa/README.md` line 120 at r2](https://reviewable.io/reviews/gramineproject/contrib/38#-NQbz_Sw6kSoPJeN8vG2:-NQbz_Sw6kSoPJeN8vG3:bctz1zc) ([raw file](https://github.com/gramineproject/contrib/blob/f2f485b2b81faaaeac06576e5b99c155b7ba9416/Integrations/azure/ra_tls_maa/README.md#L120)):*
> ```Markdown
> access to the MAA attestation provider service.
> 
> For this, we provide a patch that should be applied on top of Gramine v1.4 repo:
> ```

Q: Then do we plan to update this every time we have a new Gramine release? Similar question for all the other dependencies (w/ patches) below.



_Code quote:_
```Markdown
Gramine v1.4
```
___
*[`Integrations/azure/ra_tls_maa/helpers/gramine-v1.4-ci-examples.patch` line 47 at r2](https://reviewable.io/reviews/gramineproject/contrib/38#-NQc160D-52kQy-kvd2o:-NQc160D-52kQy-kvd2p:bp27x6d) ([raw file](https://github.com/gramineproject/contrib/blob/f2f485b2b81faaaeac06576e5b99c155b7ba9416/Integrations/azure/ra_tls_maa/helpers/gramine-v1.4-ci-examples.patch#L47)):*
> ```Diff
> +	gramine-sgx server >/dev/null & SERVER_ID=$$!; \
> +	sleep 30; \
> +	./client maa > OUTPUT; \
> ```

We use `sgx.remote_attestation = "dcap"` almost everywhere but here we introduce `ra_type=maa`. I kind of understand why we make this choice, but can we either stick to `dcap` for `maa` or just use `maa` as a new type?



_Code quote:_
```Diff
./client maa
```
___
*[`Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c` line 20 at r2](https://reviewable.io/reviews/gramineproject/contrib/38#-NQcFzqA5k5pJTJ9MMS3:-NQcFzqA5k5pJTJ9MMS4:b2nhes1) ([raw file](https://github.com/gramineproject/contrib/blob/f2f485b2b81faaaeac06576e5b99c155b7ba9416/Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c#L20)):*
> ```C
>  *
>  * The HTTPS "Get set of JWKs" request is sent to the URL in the format:
>  *     POST {instanceUrl}/certs/
> ```

GET



_Code quote:_
```C
POST
```
___
*[`Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c` line 447 at r2](https://reviewable.io/reviews/gramineproject/contrib/38#-NQcJwA80PMR_qF4kRk4:-NQcJwA80PMR_qF4kRk5:b-6vkeu5) ([raw file](https://github.com/gramineproject/contrib/blob/f2f485b2b81faaaeac06576e5b99c155b7ba9416/Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c#L447)):*
> ```C
>     size_t quote_b64_size = 0;
>     ret = mbedtls_base64url_encode(/*dest=*/NULL, /*dlen=*/0, &quote_b64_size, quote, quote_size);
>     if (ret != MBEDTLS_ERR_BASE64_BUFFER_TOO_SMALL) {
> ```

Can we hide this error (when we explicity want to get the buffer size) within `mbedtls_base64url_encode()` as it's already a wrapper? Similar for `mbedtls_base64url_decode()`.



_Code quote:_
```C
MBEDTLS_ERR_BASE64_BUFFER_TOO_SMALL
```
___
*[`Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c` line 485 at r2](https://reviewable.io/reviews/gramineproject/contrib/38#-NQcKnOp-yRIP7WNmDkQ:-NQcKnOp-yRIP7WNmDkR:b-z34op5) ([raw file](https://github.com/gramineproject/contrib/blob/f2f485b2b81faaaeac06576e5b99c155b7ba9416/Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c#L485)):*
> ```C
>     /* construct JSON string with the attestation request to MAA */
>     const char* request_json_fmt = "{\"quote\": \"%s\", \"runtimeData\": "
>                            "  {\"data\": \"%s\", \"dataType\": \"Binary\"}  }";
> ```

Pls align.
___
*[`Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c` line 918 at r2](https://reviewable.io/reviews/gramineproject/contrib/38#-NQcQdDV9MryyE3FhwR2:-NQcQdDV9MryyE3FhwR3:b-wwy8gn) ([raw file](https://github.com/gramineproject/contrib/blob/f2f485b2b81faaaeac06576e5b99c155b7ba9416/Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c#L918)):*
> ```C
>      *      x-ms-sgx-collateral, x-ms-policy-hash */
> 
>     if (!cJSON_IsString(x_ms_ver) || strcmp(x_ms_ver->valuestring, "1.0") ||
> ```

Any specific reason that we verify `x-ms-ver`?
___
*[`Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c` line 973 at r2](https://reviewable.io/reviews/gramineproject/contrib/38#-NQcRtmC778J4fHrZ1FX:-NQcRtmC778J4fHrZ1FY:b-qu3f38) ([raw file](https://github.com/gramineproject/contrib/blob/f2f485b2b81faaaeac06576e5b99c155b7ba9416/Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c#L973)):*
> ```C
>     quote_body->report_body.isv_prod_id = sgx_product_id->valueint;
> 
>     if (sgx_svn->valueint == INT_MAX || sgx_svn->valueint == INT_MIN) {
> ```

So we allow negative values?



_Code quote:_
```C
if (sgx_svn->valueint == INT_MAX || sgx_svn->valueint == INT_MIN)
```


<!-- Sent from Reviewable.io -->

2023-03-17 10:48 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/38)* status: 0 of 19 files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`Integrations/azure/ra_tls_maa/README.md` line 96 at r2](https://reviewable.io/reviews/gramineproject/contrib/38#-NQc5J618-Ip-MQsvGZu:-NQj0Ycv6WWITj5HkknQ:bi0fjuk) ([raw file](https://github.com/gramineproject/contrib/blob/f2f485b2b81faaaeac06576e5b99c155b7ba9416/Integrations/azure/ra_tls_maa/README.md#L96)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

If we install Gramine into other places w/ `--prefix`, we may require here to have the same input. Similar for `libdir`.
</blockquote></details>

I didn't want to mention it in this README. I think this will get way too complex. Also, it is always possible to specify the installation path of this plugin in the Gramine manifest itself, as the plugin doesn't need to be placed in the same dir where Gramine was installed.

Basically, my point is: this is rather technical documentation, and I would expect users who work with this MAA plugin to know how to correctly add the MAA plugin library to Gramine-SGX environment.
___
*[`Integrations/azure/ra_tls_maa/README.md` line 117 at r2](https://reviewable.io/reviews/gramineproject/contrib/38#-NQbyp1w12G_6KJSvY_D:-NQj15lxAa9J0i8n2lw5:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/f2f485b2b81faaaeac06576e5b99c155b7ba9416/Integrations/azure/ra_tls_maa/README.md#L117)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

to
</blockquote></details>

Done.
___
*[`Integrations/azure/ra_tls_maa/README.md` line 120 at r2](https://reviewable.io/reviews/gramineproject/contrib/38#-NQbz_Sw6kSoPJeN8vG2:-NQj18vR63WZFEiE-7pI:b1di7l0) ([raw file](https://github.com/gramineproject/contrib/blob/f2f485b2b81faaaeac06576e5b99c155b7ba9416/Integrations/azure/ra_tls_maa/README.md#L120)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Q: Then do we plan to update this every time we have a new Gramine release? Similar question for all the other dependencies (w/ patches) below.
</blockquote></details>

Yes... This will be a bit of a pain to maintain, but yes, the plan is to update the patch for every release.

Do you mean I should mention it somewhere, or what?
___
*[`Integrations/azure/ra_tls_maa/helpers/gramine-v1.4-ci-examples.patch` line 47 at r2](https://reviewable.io/reviews/gramineproject/contrib/38#-NQc160D-52kQy-kvd2o:-NQj1YwN17FNGZgBYfhM:b-c8gscd) ([raw file](https://github.com/gramineproject/contrib/blob/f2f485b2b81faaaeac06576e5b99c155b7ba9416/Integrations/azure/ra_tls_maa/helpers/gramine-v1.4-ci-examples.patch#L47)):*
> here we introduce `ra_type=maa`

I don't understand you. I do **not** introduce a new `RA_TYPE` option. `RA_TYPE` can still be only one of two: EPID-based or DCAP-based.

MAA technology is a wrapper around DCAP-based attestation. So that's why we need to specify `RA_TYPE=dcap` for core Gramine. But the example's client (the user program) has the ability to choose between different libraries:
- `epid` (`libra_tls_verify_epid.so`, uses IAS attestation)
- `dcap` (`libra_tls_verify_dcap.so`, uses Intel DCAP Quote Verification + PCCS infrastructure)
- `maa` (`libra_tls_verify_dcap.so`, uses Azure DCAP client infrastructure)

I know it's quite confusing, but I don't know how to fix it properly. To reformulate:
- There are only two formats of attestation available for SGX: EPID and ECDSA/DCAP
- There are multiple attestation infrastructures: IAS (EPID-specific), Intel reference DCAP, Azure MAA, and maybe more...

How to untangle this mess of names, I don't know. I think it will become simpler in the future, if/when EPID is removed, and then the world will make sense again: there will only be DCAP attestation format and infrastructures that "build on top" of this DCAP format.

---

My point is: given the above mess, do you have a proposal how to make names easier for users?
___
*[`Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c` line 20 at r2](https://reviewable.io/reviews/gramineproject/contrib/38#-NQcFzqA5k5pJTJ9MMS3:-NQj3QEn7FVoZeD5oqHN:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/f2f485b2b81faaaeac06576e5b99c155b7ba9416/Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c#L20)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

GET
</blockquote></details>

Done.
___
*[`Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c` line 447 at r2](https://reviewable.io/reviews/gramineproject/contrib/38#-NQcJwA80PMR_qF4kRk4:-NQj3rOl60e-nAOx4j7C:b-lp4nsm) ([raw file](https://github.com/gramineproject/contrib/blob/f2f485b2b81faaaeac06576e5b99c155b7ba9416/Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c#L447)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Can we hide this error (when we explicity want to get the buffer size) within `mbedtls_base64url_encode()` as it's already a wrapper? Similar for `mbedtls_base64url_decode()`.
</blockquote></details>

No. I based these functions on similar and already-existing `mbedtls_base64_encode()` and `mbedtls_base64_decode()`. And these functions have this exact behavior. See:
- https://siliconlabs.github.io/Gecko_SDK_Doc/mbedtls/html/base64_8h.html#a87c42fcb843b964e68015a46aad5bffd
- https://github.com/wolfeidau/mbedtls/blob/4c7eb1131c185cb44d76d43342398882c5c485db/source/base64.c#L198-L202

I do not want to change the behavior. I assume that in the future, mbedTLS will introduce `mbedtls_base64url_encode()` and `mbedtls_base64url_decode()`, and these functions will behave exactly the same as my current functions.
___
*[`Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c` line 485 at r2](https://reviewable.io/reviews/gramineproject/contrib/38#-NQcKnOp-yRIP7WNmDkQ:-NQj3XuhCizIyVpc67-8:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/f2f485b2b81faaaeac06576e5b99c155b7ba9416/Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c#L485)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Pls align.
</blockquote></details>

Done.
___
*[`Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c` line 918 at r2](https://reviewable.io/reviews/gramineproject/contrib/38#-NQcQdDV9MryyE3FhwR2:-NQj4bS72_omo9k6vDPW:b-cyhams) ([raw file](https://github.com/gramineproject/contrib/blob/f2f485b2b81faaaeac06576e5b99c155b7ba9416/Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c#L918)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Any specific reason that we verify `x-ms-ver`?
</blockquote></details>

The Microsoft Azure Attestation specification tells us to check this value, and that it currently should be equal to `1.0`: https://learn.microsoft.com/en-us/azure/attestation/claim-sets#common-for-all-attestation-types

For example, if the version would be bumped to e.g. `2.0`, it may deprecate and remove some fields (this happened to fields `sgx-mrsigner`, `sgx-mrenclave`, etc., search the above-linked web page for "deprecated"). And thus my code would become wrong, and it won't loudly complain but fail in strange ways.
___
*[`Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c` line 973 at r2](https://reviewable.io/reviews/gramineproject/contrib/38#-NQcRtmC778J4fHrZ1FX:-NQj72Ll6-00a9SKmWP4:bvop6tg) ([raw file](https://github.com/gramineproject/contrib/blob/f2f485b2b81faaaeac06576e5b99c155b7ba9416/Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c#L973)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

So we allow negative values?
</blockquote></details>

Done. Good catch. `isv_s [...]

2023-03-20 03:02 UTC, kailun-qin reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/38#-:-NQwxuoh6cCda1W8F0sR:bnfp4nl)* status: 0 of 19 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`Integrations/azure/ra_tls_maa/README.md` line 96 at r2](https://reviewable.io/reviews/gramineproject/contrib/38#-NQc5J618-Ip-MQsvGZu:-NQwsz9v4pslMJOdOG8p:b-joa0hk) ([raw file](https://github.com/gramineproject/contrib/blob/f2f485b2b81faaaeac06576e5b99c155b7ba9416/Integrations/azure/ra_tls_maa/README.md#L96)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I didn't want to mention it in this README. I think this will get way too complex. Also, it is always possible to specify the installation path of this plugin in the Gramine manifest itself, as the plugin doesn't need to be placed in the same dir where Gramine was installed.

Basically, my point is: this is rather technical documentation, and I would expect users who work with this MAA plugin to know how to correctly add the MAA plugin library to Gramine-SGX environment.
</blockquote></details>

OK, make sense. Resolving.
___
*[`Integrations/azure/ra_tls_maa/README.md` line 120 at r2](https://reviewable.io/reviews/gramineproject/contrib/38#-NQbz_Sw6kSoPJeN8vG2:-NQwt5q_B4bjeYajAj2Q:b-er2zle) ([raw file](https://github.com/gramineproject/contrib/blob/f2f485b2b81faaaeac06576e5b99c155b7ba9416/Integrations/azure/ra_tls_maa/README.md#L120)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes... This will be a bit of a pain to maintain, but yes, the plan is to update the patch for every release.

Do you mean I should mention it somewhere, or what?
</blockquote></details>

Thanks for the clarification! No, I don't mean to have it mentioned somewhere - just a pure question.
___
*[`Integrations/azure/ra_tls_maa/helpers/gramine-v1.4-ci-examples.patch` line 47 at r2](https://reviewable.io/reviews/gramineproject/contrib/38#-NQc160D-52kQy-kvd2o:-NQwtaB94c1QRPHqCKMZ:b-5mf3wa) ([raw file](https://github.com/gramineproject/contrib/blob/f2f485b2b81faaaeac06576e5b99c155b7ba9416/Integrations/azure/ra_tls_maa/helpers/gramine-v1.4-ci-examples.patch#L47)):*
>  I do not introduce a new RA_TYPE option. RA_TYPE can still be only one of two: EPID-based or DCAP-based.

Right, I fully understand the current proposal and implementation (and the mess). My initial concern was only about this `maa` argument of client (I'd like to propose `./client dcap` to just keep it consistent w/ `RA_TYPE=dcap` since users won't apply the patch to example if they're not w/ MAA). But I got your point (below) now.

> But the example's client (the user program) has the ability to choose between different libraries

I think you're right - we cannot achieve this by having a new `maa` argument.

> given the above mess, do you have a proposal how to make names easier for users?

No, I don't have a simpler/better proposal.
___
*[`Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c` line 447 at r2](https://reviewable.io/reviews/gramineproject/contrib/38#-NQcJwA80PMR_qF4kRk4:-NQwx9NYCyDF5zF7H5vN:bcr5s2o) ([raw file](https://github.com/gramineproject/contrib/blob/f2f485b2b81faaaeac06576e5b99c155b7ba9416/Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c#L447)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

No. I based these functions on similar and already-existing `mbedtls_base64_encode()` and `mbedtls_base64_decode()`. And these functions have this exact behavior. See:
- https://siliconlabs.github.io/Gecko_SDK_Doc/mbedtls/html/base64_8h.html#a87c42fcb843b964e68015a46aad5bffd
- https://github.com/wolfeidau/mbedtls/blob/4c7eb1131c185cb44d76d43342398882c5c485db/source/base64.c#L198-L202

I do not want to change the behavior. I assume that in the future, mbedTLS will introduce `mbedtls_base64url_encode()` and `mbedtls_base64url_decode()`, and these functions will behave exactly the same as my current functions.
</blockquote></details>

Got it, thanks!
___
*[`Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c` line 918 at r2](https://reviewable.io/reviews/gramineproject/contrib/38#-NQcQdDV9MryyE3FhwR2:-NQwxQYnCtkwrZGm1Uil:bd5mis0) ([raw file](https://github.com/gramineproject/contrib/blob/f2f485b2b81faaaeac06576e5b99c155b7ba9416/Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c#L918)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The Microsoft Azure Attestation specification tells us to check this value, and that it currently should be equal to `1.0`: https://learn.microsoft.com/en-us/azure/attestation/claim-sets#common-for-all-attestation-types

For example, if the version would be bumped to e.g. `2.0`, it may deprecate and remove some fields (this happened to fields `sgx-mrsigner`, `sgx-mrenclave`, etc., search the above-linked web page for "deprecated"). And thus my code would become wrong, and it won't loudly complain but fail in strange ways.
</blockquote></details>

Make sense to me.


<!-- Sent from Reviewable.io -->

2023-03-20 03:08 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/38)* status: 0 of 19 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c` line 823 at r3](https://reviewable.io/reviews/gramineproject/contrib/38#-NQwyYFH2r8hA9MdqwFs:-NQwyYFH2r8hA9MdqwFt:b-z34op5) ([raw file](https://github.com/gramineproject/contrib/blob/bf5d929aa8068f5c8ca33f03ac39110704c51741/Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c#L823)):*
> ```C
>         if (!cJSON_IsString(key_kty) || strcmp(key_kty->valuestring, "RSA")) {
>             ERROR("MAA JWK's `kty` field contains an unexpected value (got `%s`, expected `%s`)\n",
>                     key_kty->valuestring, "RSA");
> ```

Pls align.
___
*[`Integrations/azure/ra_tls_maa/src/secret_prov_verify_maa.c` line 20 at r3](https://reviewable.io/reviews/gramineproject/contrib/38#-NQwzApX-F_3RQV5l8vh:-NQwzApX-F_3RQV5l8vi:b-s1t5si) ([raw file](https://github.com/gramineproject/contrib/blob/bf5d929aa8068f5c8ca33f03ac39110704c51741/Integrations/azure/ra_tls_maa/src/secret_prov_verify_maa.c#L20)):*
> ```C
>   secret_provision_read,
>   secret_provision_write,
>   secret_provision_close,
> ```

Not blocking... But why 2-space indent?



_Code quote:_
```C
  secret_provision_start_server,
  secret_provision_read,
  secret_provision_write,
  secret_provision_close,
```


<!-- Sent from Reviewable.io -->

2023-03-20 08:36 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/38)* status: 0 of 19 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`Integrations/azure/ra_tls_maa/helpers/gramine-v1.4-ci-examples.patch` line 47 at r2](https://reviewable.io/reviews/gramineproject/contrib/38#-NQc160D-52kQy-kvd2o:-NQy8cTy8UOcz8P270Be:b-n68plk) ([raw file](https://github.com/gramineproject/contrib/blob/f2f485b2b81faaaeac06576e5b99c155b7ba9416/Integrations/azure/ra_tls_maa/helpers/gramine-v1.4-ci-examples.patch#L47)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

>  I do not introduce a new RA_TYPE option. RA_TYPE can still be only one of two: EPID-based or DCAP-based.

Right, I fully understand the current proposal and implementation (and the mess). My initial concern was only about this `maa` argument of client (I'd like to propose `./client dcap` to just keep it consistent w/ `RA_TYPE=dcap` since users won't apply the patch to example if they're not w/ MAA). But I got your point (below) now.

> But the example's client (the user program) has the ability to choose between different libraries

I think you're right - we cannot achieve this by having a new `maa` argument.

> given the above mess, do you have a proposal how to make names easier for users?

No, I don't have a simpler/better proposal.
</blockquote></details>

Ok. I understand your confusion, but unfortunately I don't see a good way around this mess.
___
*[`Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c` line 823 at r3](https://reviewable.io/reviews/gramineproject/contrib/38#-NQwyYFH2r8hA9MdqwFs:-NQy9A8DDtSVr7j5wT8E:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/bf5d929aa8068f5c8ca33f03ac39110704c51741/Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c#L823)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Pls align.
</blockquote></details>

Done.
___
*[`Integrations/azure/ra_tls_maa/src/secret_prov_verify_maa.c` line 20 at r3](https://reviewable.io/reviews/gramineproject/contrib/38#-NQwzApX-F_3RQV5l8vh:-NQy9O3t0qyDbJ92Gv9M:b3eyy39) ([raw file](https://github.com/gramineproject/contrib/blob/bf5d929aa8068f5c8ca33f03ac39110704c51741/Integrations/azure/ra_tls_maa/src/secret_prov_verify_maa.c#L20)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Not blocking... But why 2-space indent?
</blockquote></details>

Done. Something went wrong with my Vim indentation settings :)


<!-- Sent from Reviewable.io -->

2023-03-24 02:17 UTC, kailun-qin reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/38#-:-NRGP5NS4WBusevhLW9v:bnfp4nl)* status: 0 of 19 files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-04-25 12:30 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/38)* status: 0 of 19 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/38#-NTsO1NBDewTNeMM54cx:-NTsO1NBDewTNeMM54cy:b-nb1ety) (no related file):*
Need to expose JWT (and maybe also those JWT sets) from RA-TLS. See https://github.com/gramineproject/gramine/discussions/1292.

If nothing will be decided, I will stash the received JWT into the envvar `RA_TLS_MAA_JWT`.

___


<!-- Sent from Reviewable.io -->

2023-04-26 13:28 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/38)* status: 0 of 20 files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/38#-NTsO1NBDewTNeMM54cx:-NTxjB8i0zcj8USHYVa0:bu7rjmt) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Need to expose JWT (and maybe also those JWT sets) from RA-TLS. See https://github.com/gramineproject/gramine/discussions/1292.

If nothing will be decided, I will stash the received JWT into the envvar `RA_TLS_MAA_JWT`.
</blockquote></details>

Done. I now expose the following envvars:
- `RA_TLS_MAA_JWT` -- contains the JWT (MAA-sent JSON Web Token) in base64-format; the decoded human-readable version you can check at https://jwt.io/
- `RA_TLS_MAA_SET_OF_JWKS` -- contains the set of JWKs (JSON Web Key), one of them is used to sign the JWT. This set is in JSON format.

For more info on these terms and formats, browse https://learn.microsoft.com/en-us/azure/attestation/

___
___
*[`Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c` line 1044 at r4](https://reviewable.io/reviews/gramineproject/contrib/38#-NTsMwTsB1YdyClUTuCl:-NTxjn6q92FIWt0NXYUa:bb6un1j) ([raw file](https://github.com/gramineproject/contrib/blob/adf338e8eb18acb75e19dedd90abb6e002ee33e3/Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c#L1044)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Should update similar to this: https://github.com/gramineproject/gramine/pull/1215

I.e., must do similar to: https://github.com/gramineproject/gramine/pull/1215/files#diff-9d4561aeaacd250d6b7b91858eaec04822304ee67edb7844f9dc30a5bfa07d36
</blockquote></details>

Done
___
*[`Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c` line 1150 at r4](https://reviewable.io/reviews/gramineproject/contrib/38#-NTsNbcr1s7kpka-ShSA:-NTxjoqVBIy_LiXm7VvM:b-igl1xe) ([raw file](https://github.com/gramineproject/contrib/blob/adf338e8eb18acb75e19dedd90abb6e002ee33e3/Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c#L1150)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Blocking myself: check if I need to introduce new envvars from https://github.com/gramineproject/gramine/pull/1286/
</blockquote></details>

Done. No need to introduce those envvars, since MAA does this heavy-lifting for us.
___
*[`Integrations/azure/ra_tls_maa/subprojects/mbedtls-mbedtls-3.4.0.wrap` line 1 at r5](https://reviewable.io/reviews/gramineproject/contrib/38#-NTxjsxu4HsLAI87Eoj-:-NTxjsxu4HsLAI87Eoj0:b-venm8x) ([raw file](https://github.com/gramineproject/contrib/blob/70f22d8f222a75c58716a9b2514fe24646d468a7/Integrations/azure/ra_tls_maa/subprojects/mbedtls-mbedtls-3.4.0.wrap#L1)):*
> ```
> [wrap-file]
> ```

FYI: Note that I updated to latest mbedTLS (copy-pasted from core Gramine)


<!-- Sent from Reviewable.io -->

2023-07-27 15:01 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/38)* status: 0 of 20 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/38#-NaMqKx51vSvQtd5KFXo:-NaMqKx51vSvQtd5KFXp:b-sm0va7) (no related file):*
I rebased this PR to use Gramine v1.5.

Note several things:
- mbedTLS version used in core Gramine didn't change in the meantime (still 3.4.0)
- curl version used in core Gramine didn't change in the meantime (still 7.84)
- I updated the patch with CI-Examples from v1.4 to v1.5
- I removed the `fcntl.patch` from mbedTLS because it was used for Ubuntu 18.04 and in Gramine v1.5 it was removed (because 18.04 is deprecated fully)
- MAA REST API is still version `2022-08-01`, see e.g. https://learn.microsoft.com/en-us/rest/api/attestation/attestation/attest-sgx-enclave?tabs=HTTP

___


<!-- Sent from Reviewable.io -->

2023-07-28 08:04 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/38)* status: 0 of 22 files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/38#-NaMqKx51vSvQtd5KFXo:-NaQWD2s5llZe7hHZOLM:b-xfa07r) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I rebased this PR to use Gramine v1.5.

Note several things:
- mbedTLS version used in core Gramine didn't change in the meantime (still 3.4.0)
- curl version used in core Gramine didn't change in the meantime (still 7.84)
- I updated the patch with CI-Examples from v1.4 to v1.5
- I removed the `fcntl.patch` from mbedTLS because it was used for Ubuntu 18.04 and in Gramine v1.5 it was removed (because 18.04 is deprecated fully)
- MAA REST API is still version `2022-08-01`, see e.g. https://learn.microsoft.com/en-us/rest/api/attestation/attestation/attest-sgx-enclave?tabs=HTTP
</blockquote></details>

I tested the rebased version on MS Azure. I added a fixup commit to use a static cJSON library, similarly to how core Gramine does it (in fact, copy-pasted the Meson logic from core Gramine).

___


<!-- Sent from Reviewable.io -->

2023-09-04 17:03 UTC, omeg reviewed
> Reviewed 5 of 19 files at r1, 1 of 2 files at r4, 5 of 10 files at r5, 10 of 11 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/38)* status: 21 of 22 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`Integrations/azure/ra_tls_maa/subprojects/packagefiles/mbedtls/enforce-aes-ni.patch` line 0 at r7](https://reviewable.io/reviews/gramineproject/contrib/38#-NdW7Jy83wXjMUgdSHa0:-NdW7Jy83wXjMUgdSHa1:b-hzj4u3) ([raw file](https://github.com/gramineproject/contrib/blob/393c4975ca061a8450d20e4cf8fbf417018de574/Integrations/azure/ra_tls_maa/subprojects/packagefiles/mbedtls/enforce-aes-ni.patch#L0)):*
Just a note for the future: it seems that in mbedtls 3.4.2 (not finalized yet) there will be a define for this (`MBEDTLS_AES_USE_HARDWARE_ONLY`).


<!-- Sent from Reviewable.io -->

2023-09-04 17:26 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/38)* status: 21 of 22 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @omeg)

___
*[`Integrations/azure/ra_tls_maa/subprojects/packagefiles/mbedtls/enforce-aes-ni.patch` line  at r7](https://reviewable.io/reviews/gramineproject/contrib/38#-NdW7Jy83wXjMUgdSHa0:-NdWDbtZ39BKFPeEfMI6:b-x5l0fj) ([raw file](https://github.com/gramineproject/contrib/blob/393c4975ca061a8450d20e4cf8fbf417018de574/Integrations/azure/ra_tls_maa/subprojects/packagefiles/mbedtls/enforce-aes-ni.patch#L)):*
<details><summary><i>Previously, omeg (Rafał Wojdyła) wrote…</i></summary><blockquote>

Just a note for the future: it seems that in mbedtls 3.4.2 (not finalized yet) there will be a define for this (`MBEDTLS_AES_USE_HARDWARE_ONLY`).
</blockquote></details>

Nice! We will be able to drop my patches from Gramine then :)


<!-- Sent from Reviewable.io -->

2023-09-04 17:28 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/38)* status: 21 of 22 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @omeg)

___
*[`Integrations/azure/ra_tls_maa/subprojects/packagefiles/mbedtls/enforce-aes-ni.patch` line  at r7](https://reviewable.io/reviews/gramineproject/contrib/38#-NdW7Jy83wXjMUgdSHa0:-NdWDqMhEe-5If1EwA51:bhasxtn) ([raw file](https://github.com/gramineproject/contrib/blob/393c4975ca061a8450d20e4cf8fbf417018de574/Integrations/azure/ra_tls_maa/subprojects/packagefiles/mbedtls/enforce-aes-ni.patch#L)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Nice! We will be able to drop my patches from Gramine then :)
</blockquote></details>

btw: seems they did it for performance reasons (code size), not security, lol :)
https://github.com/Mbed-TLS/mbedtls/pull/7384
https://github.com/Mbed-TLS/mbedtls/issues/7141


<!-- Sent from Reviewable.io -->

2023-09-05 16:06 UTC, omeg reviewed
> Reviewed 1 of 11 files at r7.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/38)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c` line 87 at r7](https://reviewable.io/reviews/gramineproject/contrib/38#-Nd_5BeV0A0ifjmYM_ht:-Nd_5BeV0A0ifjmYM_hu:b-r9kd72) ([raw file](https://github.com/gramineproject/contrib/blob/393c4975ca061a8450d20e4cf8fbf417018de574/Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c#L87)):*
> ```C
> struct maa_response {
>     char* data;              /*!< response (JSON string) */
>     size_t data_size;        /*!< size of \a token string */
> ```

There's no `token` member here, should be `data`?
___
*[`Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c` line 341 at r7](https://reviewable.io/reviews/gramineproject/contrib/38#-Nd_xLpuENLL7keoxn-i:-Nd_xLpuENLL7keoxn-j:undefined) ([raw file](https://github.com/gramineproject/contrib/blob/393c4975ca061a8450d20e4cf8fbf417018de574/Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c#L341)):*
> ```C
> 
> /*! Send GET request (empty) to MAA attestation provider's `certs/` API endpoint and save the
>  * resulting set of JWKs \a out_set_of_jwks; caller is responsible for its cleanup */
> ```





_Suggestion:_
```C
resulting set of JWKs in \a out_set_of_jwks;
```
___
*[`Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c` line 940 at r7](https://reviewable.io/reviews/gramineproject/contrib/38#-Nd_uHsg12ffXW7HAFfS:-Nd_uHsg12ffXW7HAFfT:b45h) ([raw file](https://github.com/gramineproject/contrib/blob/393c4975ca061a8450d20e4cf8fbf417018de574/Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c#L940)):*
> ```C
>     }
> 
>     /* construct a dummy SGX quote (body) with contents takes from the JWT payload; this is for
> ```





_Suggestion:_
```C
taken
```
___
*[`Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c` line 1057 at r7](https://reviewable.io/reviews/gramineproject/contrib/38#-Nd_w_g93Oigx5EBAuGh:-Nd_w_g93Oigx5EBAuGi:undefined) ([raw file](https://github.com/gramineproject/contrib/blob/393c4975ca061a8450d20e4cf8fbf417018de574/Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c#L1057)):*
> ```C
> }
> 
> /*! parse the public key \p pk into DER format and copy it into \p pk_der */
> ```





_Suggestion:_
```C
out_pk_der
```


<!-- Sent from Reviewable.io -->

2023-09-06 07:29 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/38)* status: 21 of 22 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @omeg)

___
*[`Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c` line 87 at r7](https://reviewable.io/reviews/gramineproject/contrib/38#-Nd_5BeV0A0ifjmYM_ht:-NddNdel1su-14A6dDwk:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/393c4975ca061a8450d20e4cf8fbf417018de574/Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c#L87)):*
<details><summary><i>Previously, omeg (Rafał Wojdyła) wrote…</i></summary><blockquote>

There's no `token` member here, should be `data`?
</blockquote></details>

Done.
___
*[`Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c` line 341 at r7](https://reviewable.io/reviews/gramineproject/contrib/38#-Nd_xLpuENLL7keoxn-i:-NddNnQS77a_dm1Hrzkq:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/393c4975ca061a8450d20e4cf8fbf417018de574/Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c#L341)):*
> ```C
> 
> /*! Send GET request (empty) to MAA attestation provider's `certs/` API endpoint and save the
>  * resulting set of JWKs \a out_set_of_jwks; caller is responsible for its cleanup */
> ```

Done.
___
*[`Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c` line 940 at r7](https://reviewable.io/reviews/gramineproject/contrib/38#-Nd_uHsg12ffXW7HAFfS:-NddNssY3PRX2DMqlfIA:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/393c4975ca061a8450d20e4cf8fbf417018de574/Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c#L940)):*
> ```C
>     }
> 
>     /* construct a dummy SGX quote (body) with contents takes from the JWT payload; this is for
> ```

Done.
___
*[`Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c` line 1057 at r7](https://reviewable.io/reviews/gramineproject/contrib/38#-Nd_w_g93Oigx5EBAuGh:-NddNyL1Dzit6z8otQ9_:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/393c4975ca061a8450d20e4cf8fbf417018de574/Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c#L1057)):*
> ```C
> }
> 
> /*! parse the public key \p pk into DER format and copy it into \p pk_der */
> ```

Done.


<!-- Sent from Reviewable.io -->

2023-09-06 08:51 UTC, omeg reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/38#-:-NddgCEn1vMTSLJK4wbc:bnfp4nl)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-09-19 04:34 UTC, kailun-qin requested changes
> Reviewed 5 of 19 files at r1, 1 of 2 files at r4, 5 of 10 files at r5, 10 of 11 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/38)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`Integrations/azure/ra_tls_maa/helpers/maa.svg` line 0 at r8](https://reviewable.io/reviews/gramineproject/contrib/38#-NefOT0m-Fa09tdhOWcs:-NefOT0m-Fa09tdhOWct:bkszp2d) ([raw file](https://github.com/gramineproject/contrib/blob/bd74f1243b26a66ad4dcfa2147433c987be46c4f/Integrations/azure/ra_tls_maa/helpers/maa.svg#L0)):*
Should it be "Provisioning Certificate Enclave (PCE)" in the diagram?
___
*[`Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c` line 70 at r8](https://reviewable.io/reviews/gramineproject/contrib/38#-NefVd0h6c7aPl93NAlX:-NefVd0h6c7aPl93NAlY:b-a4ey0h) ([raw file](https://github.com/gramineproject/contrib/blob/bd74f1243b26a66ad4dcfa2147433c987be46c4f/Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c#L70)):*
> ```C
> #define DEFAULT_MAA_PROVIDER_API_VERSION "2022-08-01"
> 
> /* Environment variables exposed by successful RA-TLS verification API */
> ```

Do we want to doc this somewhere?



_Code quote:_
```C
Environment variables exposed by successful RA-TLS verification API
```
___
*[`Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c` line 79 at r8](https://reviewable.io/reviews/gramineproject/contrib/38#-NefaAuY4cUb_lTxOJy6:-NefaAuY4cUb_lTxOJy7:be647n7) ([raw file](https://github.com/gramineproject/contrib/blob/bd74f1243b26a66ad4dcfa2147433c987be46c4f/Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c#L79)):*
> ```C
> /*! Context used in maa_*() calls */
> struct maa_context_t {
>     bool curl_global_init_done;
> ```

If curl APIs can handle uninitialized (NULL) correctly (pls see my other comment), do we still need to keep this field?



_Code quote:_
```C
    bool curl_global_init_done;
```
___
*[`Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c` line 81 at r8](https://reviewable.io/reviews/gramineproject/contrib/38#-NefafCi7ZBLrpNPL3Kv:-NefafCi7ZBLrpNPL3Kw:b-7ropln) ([raw file](https://github.com/gramineproject/contrib/blob/bd74f1243b26a66ad4dcfa2147433c987be46c4f/Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c#L81)):*
> ```C
>     bool curl_global_init_done;
>     CURL* curl;                 /*!< CURL context for this session */
>     struct curl_slist* headers; /*!< Request headers sent to MAA attestation provider */
> ```

ditto



_Code quote:_
```C
    struct curl_slist* headers; /*!< Request headers sent to MAA attestation provider */
```
___
*[`Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c` line 260 at r8](https://reviewable.io/reviews/gramineproject/contrib/38#-Nef_UwqAcZUvr1vSdba:-Nef_UwqAcZUvr1vSdbb:b-ez2oy0) ([raw file](https://github.com/gramineproject/contrib/blob/bd74f1243b26a66ad4dcfa2147433c987be46c4f/Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c#L260)):*
> ```C
> 
>     if (context->headers)
>         curl_slist_free_all(context->headers);
> ```

curl APIs should've handled NULL internally IIRC. Would you pls double check?



_Code quote:_
```C
    if (context->headers)
        curl_slist_free_all(context->headers);
```
___
*[`Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c` line 262 at r8](https://reviewable.io/reviews/gramineproject/contrib/38#-Nef_oNM9UegGv_Tm9Yg:-Nef_oNM9UegGv_Tm9Yh:b-7ropln) ([raw file](https://github.com/gramineproject/contrib/blob/bd74f1243b26a66ad4dcfa2147433c987be46c4f/Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c#L262)):*
> ```C
>         curl_slist_free_all(context->headers);
> 
>     if (context->curl)
> ```

ditto



_Code quote:_
```C
    if (context->curl)
```
___
*[`Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c` line 266 at r8](https://reviewable.io/reviews/gramineproject/contrib/38#-Nef_q7070Bocgdv5JHC:-Nef_q7070Bocgdv5JHD:b-7ropln) ([raw file](https://github.com/gramineproject/contrib/blob/bd74f1243b26a66ad4dcfa2147433c987be46c4f/Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c#L266)):*
> ```C
> 
>     /* every curl_global_init() must have a corresponding curl_global_cleanup() */
>     if (context->curl_global_init_done)
> ```

ditto



_Code quote:_
```C
    if (context->curl_global_init_done)
```
___
*[`Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c` line 286 at r8](https://reviewable.io/reviews/gramineproject/contrib/38#-NefdQRHDHUjWJIJaTye:-NefdQRHDHUjWJIJaTyf:b5vrg3) ([raw file](https://github.com/gramineproject/contrib/blob/bd74f1243b26a66ad4dcfa2147433c987be46c4f/Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c#L286)):*
> ```C
>         ret = MBEDTLS_ERR_X509_FATAL_ERROR;
>         goto out;
>     }
> ```

Not blocking, just wondering if it's better to introduce a macro for such checks?



_Code quote:_
```C
    if (curl_ret != CURLE_OK) {
        ret = MBEDTLS_ERR_X509_FATAL_ERROR;
        goto out;
    }
```
___
*[`Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c` line 1192 at r8](https://reviewable.io/reviews/gramineproject/contrib/38#-NefghQB3xrK5ZfB3KIn:-NefghQB3xrK5ZfB3KIo:bocnxoq) ([raw file](https://github.com/gramineproject/contrib/blob/bd74f1243b26a66ad4dcfa2147433c987be46c4f/Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c#L1192)):*
> ```C
> 
>     /* verify enclave attributes from the SGX quote body, including the user-supplied verification
>      * parameter "allow debug enclave"; NOTE: "allow outdated TCB" parameter is not used in MAA */
> ```

Several questions:
1. We also have other params like `allow_hw_config_needed`, `allow_sw_hardening_needed`, do we also need to mention them here?
2. This is not reflected in doc and/or our patch to the ra-tls-mbedtls example, do we want to mention this (w/ some explanations) somewhere?
3. In the doc, it's said that we'll `receive back the set of claims describing this enclave`, do we need to elaborate (or to add a pointer to some ref) somewhere what exactly is this set of claims?



_Code quote:_
```C
NOTE: "allow outdated TCB" parameter is not used in MAA
```


<!-- Sent from Reviewable.io -->

2023-09-19 15:09 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/38)* status: all files reviewed, 11 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

___
*[`Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c` line 888 at r8](https://reviewable.io/reviews/gramineproject/contrib/38#-NehykvNDpyUfZu8MeFw:-NehykvO71eiL_mPxXXZ:bo2n08) ([raw file](https://github.com/gramineproject/contrib/blob/bd74f1243b26a66ad4dcfa2147433c987be46c4f/Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c#L888)):*
> ```C
>         goto out;
>     }
> ```

At this point I have a (chain of) `token_signing_crt`. I mention below that this is a self-signed certificate, but Woju pointed out that he would expect this chain to end up in some Microsoft root cert.

If this is so, then I need to verify this chain `token_signing_crt` against the Microsoft root cert (which I should get from somewhere?).

If this is not so, then I need to put a comment explaining why we can trust this `token_signing_crt` unconditionally. (Maybe because we connected via HTTPS to the MS-owned endpoint, so this is already good enough for us?)


<!-- Sent from Reviewable.io -->

2023-09-20 01:06 UTC, mkow requested changes
> Reviewed 5 of 19 files at r1, 1 of 2 files at r4, 5 of 10 files at r5, 10 of 11 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/38)* status: all files reviewed, 18 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`Integrations/azure/ra_tls_maa/.gitignore` line 2 at r8](https://reviewable.io/reviews/gramineproject/contrib/38#-Nejq2OFBxe0mFgVpfGp:-Nejq2OFBxe0mFgVpfGq:b-simrzu) ([raw file](https://github.com/gramineproject/contrib/blob/bd74f1243b26a66ad4dcfa2147433c987be46c4f/Integrations/azure/ra_tls_maa/.gitignore#L2)):*
> ```ignore
> /build
> /built
> ```

built?
___
*[`Integrations/azure/ra_tls_maa/meson.build` line 41 at r8](https://reviewable.io/reviews/gramineproject/contrib/38#-NejqexS7NjIYe_tHiyb:-NejqexS7NjIYe_tHiyc:b-r76c9m) ([raw file](https://github.com/gramineproject/contrib/blob/bd74f1243b26a66ad4dcfa2147433c987be46c4f/Integrations/azure/ra_tls_maa/meson.build#L41)):*
> ```Meson
> debug = get_option('buildtype') == 'debug' or get_option('buildtype') == 'debugoptimized'
> if debug
>     add_project_arguments('-DDEBUG', language: 'c')
> ```

Seems unused in the code?
___
*[`Integrations/azure/ra_tls_maa/meson.build` line 42 at r8](https://reviewable.io/reviews/gramineproject/contrib/38#-Nejqh0PCYGSxZbvERhx:-Nejqh0PCYGSxZbvERhy:b-m7drqw) ([raw file](https://github.com/gramineproject/contrib/blob/bd74f1243b26a66ad4dcfa2147433c987be46c4f/Integrations/azure/ra_tls_maa/meson.build#L42)):*
> ```Meson
> if debug
>     add_project_arguments('-DDEBUG', language: 'c')
> endif
> ```

btw. if you want to compile-out standard library asserts from the code in release builds, then you need to define `NDEBUG`. See https://en.cppreference.com/w/c/error/assert.
___
*[`Integrations/azure/ra_tls_maa/src/ra_tls.map` line 4 at r8](https://reviewable.io/reviews/gramineproject/contrib/38#-Nek4RX95BC_sonr-yi2:-Nek4RXAE_APm9J73dDv:b-jw3j0p) ([raw file](https://github.com/gramineproject/contrib/blob/bd74f1243b26a66ad4dcfa2147433c987be46c4f/Integrations/azure/ra_tls_maa/src/ra_tls.map#L4)):*
> ```
>     global: ra_tls_set_measurement_callback; ra_tls_verify_callback_der; ra_tls_verify_callback_extended_der; ra_tls_create_key_and_crt_der;
>     local: *;
> };
> ```

Why did you need a custom linker map?
___
*[`Integrations/azure/ra_tls_maa/src/secret_prov_verify_maa.c` line 9 at r8](https://reviewable.io/reviews/gramineproject/contrib/38#-Nek53-vBQNddRgnlF-b:-Nek53-vBQNddRgnlF-c:bmdrg25) ([raw file](https://github.com/gramineproject/contrib/blob/bd74f1243b26a66ad4dcfa2147433c987be46c4f/Integrations/azure/ra_tls_maa/src/secret_prov_verify_maa.c#L9)):*
> ```C
>  * This file contains the dummy references to secret_prov_verify exported functions (this is to
>  * force symbols from libsecret_prov_verify.a to be exported in our MAA version; note that by
>  * default unused symbols from a linked static library are *not* exported).
> ```

Shouldn't you instead add some attributes to these symbols to export them?
___
*[`Integrations/azure/ra_tls_maa/helpers/gramine-v1.5-ci-examples.patch` line 46 at r8](https://reviewable.io/reviews/gramineproject/contrib/38#-Nek3SWS0Gj0iJ78jrD_:-Nek3SWS0Gj0iJ78jrDa:b-pola0e) ([raw file](https://github.com/gramineproject/contrib/blob/bd74f1243b26a66ad4dcfa2147433c987be46c4f/Integrations/azure/ra_tls_maa/helpers/gramine-v1.5-ci-examples.patch#L46)):*
> ```Diff
> +check_maa: app maa
> +	gramine-sgx server >/dev/null & SERVER_ID=$$!; \
> +	sleep 30; \
> ```

Can't we use `wait_for_server`? I hate these sleeps :)
___
*[`Integrations/azure/ra_tls_maa/helpers/gramine-v1.5-ci-examples.patch` line 59 at r8](https://reviewable.io/reviews/gramineproject/contrib/38#-Nek3j7cE6S0MWq0ud1E:-Nek3j7cE6S0MWq0ud1F:b-7ropln) ([raw file](https://github.com/gramineproject/contrib/blob/bd74f1243b26a66ad4dcfa2147433c987be46c4f/Integrations/azure/ra_tls_maa/helpers/gramine-v1.5-ci-examples.patch#L59)):*
> ```Diff
> +check_maa_fail: app maa
> +	gramine-sgx server --test-malicious-quote >/dev/null & SERVER_ID=$$!; \
> +	sleep 30; \
> ```

ditto


<!-- Sent from Reviewable.io -->

2023-09-20 14:08 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/38)* status: 16 of 22 files reviewed, 18 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin, @mkow, and @omeg)

___
*[`Integrations/azure/ra_tls_maa/.gitignore` line 2 at r8](https://reviewable.io/reviews/gramineproject/contrib/38#-Nejq2OFBxe0mFgVpfGp:-NemHYAx5iInR4IallBZ:b-xha0y1) ([raw file](https://github.com/gramineproject/contrib/blob/bd74f1243b26a66ad4dcfa2147433c987be46c4f/Integrations/azure/ra_tls_maa/.gitignore#L2)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

built?
</blockquote></details>

Done. Leftover from my local `meson build --prefix=built` invocations.
___
*[`Integrations/azure/ra_tls_maa/meson.build` line 41 at r8](https://reviewable.io/reviews/gramineproject/contrib/38#-NejqexS7NjIYe_tHiyb:-NemIzxb7TEQnX-mL-p8:b-m5jxp4) ([raw file](https://github.com/gramineproject/contrib/blob/bd74f1243b26a66ad4dcfa2147433c987be46c4f/Integrations/azure/ra_tls_maa/meson.build#L41)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Seems unused in the code?
</blockquote></details>

Done. Fair enough, leftover from core Gramine's meson.build.
___
*[`Integrations/azure/ra_tls_maa/meson.build` line 42 at r8](https://reviewable.io/reviews/gramineproject/contrib/38#-Nejqh0PCYGSxZbvERhx:-NemJ39q-vCpPXkTb3xv:b-hrm1eo) ([raw file](https://github.com/gramineproject/contrib/blob/bd74f1243b26a66ad4dcfa2147433c987be46c4f/Integrations/azure/ra_tls_maa/meson.build#L42)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

btw. if you want to compile-out standard library asserts from the code in release builds, then you need to define `NDEBUG`. See https://en.cppreference.com/w/c/error/assert.
</blockquote></details>

Done. Good catch.

FYI: Meson doesn't specify this flag: https://github.com/mesonbuild/meson/issues/2566. So need to do it explicitly.
___
*[`Integrations/azure/ra_tls_maa/helpers/maa.svg` line  at r8](https://reviewable.io/reviews/gramineproject/contrib/38#-NefOT0m-Fa09tdhOWcs:-NemMnVF3t72XazNACVy:b-376vyb) ([raw file](https://github.com/gramineproject/contrib/blob/bd74f1243b26a66ad4dcfa2147433c987be46c4f/Integrations/azure/ra_tls_maa/helpers/maa.svg#L)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Should it be "Provisioning Certificate Enclave (PCE)" in the diagram?
</blockquote></details>

Done. Good catch.
___
*[`Integrations/azure/ra_tls_maa/src/ra_tls.map` line 4 at r8](https://reviewable.io/reviews/gramineproject/contrib/38#-Nek4RX95BC_sonr-yi2:-NemMupsAM1NGSx8k3GX:b7mo1pe) ([raw file](https://github.com/gramineproject/contrib/blob/bd74f1243b26a66ad4dcfa2147433c987be46c4f/Integrations/azure/ra_tls_maa/src/ra_tls.map#L4)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why did you need a custom linker map?
</blockquote></details>

It specifies the list of exported functions. That's the most clean way of generating shared libraries, no? We do the same in RA-TLS proper: https://github.com/gramineproject/gramine/blob/master/tools/sgx/ra-tls/ra_tls.map

We also do the same for the PAL library: https://github.com/gramineproject/gramine/blob/master/pal/src/host/linux/pal.map.template (where PAL_SYMBOLS are taken from https://github.com/gramineproject/gramine/blob/master/pal/src/pal_symbols)
___
*[`Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c` line 70 at r8](https://reviewable.io/reviews/gramineproject/contrib/38#-NefVd0h6c7aPl93NAlX:-NemWUA39eQ0xT-1BhPF:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/bd74f1243b26a66ad4dcfa2147433c987be46c4f/Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c#L70)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Do we want to doc this somewhere?
</blockquote></details>

Done.
___
*[`Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c` line 79 at r8](https://reviewable.io/reviews/gramineproject/contrib/38#-NefaAuY4cUb_lTxOJy6:-NemX-668ULdLbS7u5J_:b-u6wowl) ([raw file](https://github.com/gramineproject/contrib/blob/bd74f1243b26a66ad4dcfa2147433c987be46c4f/Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c#L79)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

If curl APIs can handle uninitialized (NULL) correctly (pls see my other comment), do we still need to keep this field?
</blockquote></details>

Yes, I think we need this field. Check the documentation:
- https://curl.se/libcurl/c/curl_global_init.html
- https://curl.se/libcurl/c/curl_global_cleanup.html

To me, it feels like every `curl_global_init()` call must have one and only one `curl_global_cleanup()` call. This is exactly what I do in my code.
___
*[`Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c` line 81 at r8](https://reviewable.io/reviews/gramineproject/contrib/38#-NefafCi7ZBLrpNPL3Kv:-NemXVOf8IZ9fHCha6lY:bqce69l) ([raw file](https://github.com/gramineproject/contrib/blob/bd74f1243b26a66ad4dcfa2147433c987be46c4f/Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c#L81)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

I think we need this field. Check the docs:
- https://curl.se/libcurl/c/curl_slist_append.html
- https://curl.se/libcurl/c/curl_slist_free_all.html

But you're right that `curl_slist_free_all(NULL)` works fine. So I removed the check in `maa_cleanup()` function. (Similarly, I removed the check for `ccurl_easy_cleanup(NULL)` in that function.)
___
*[`Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c` line 260 at r8](https://reviewable.io/reviews/gramineproject/contrib/38#-Nef_UwqAcZUvr1vSdba:-NemY5pj-so3ehuz3yi5:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/bd74f1243b26a66ad4dcfa2147433c987be46c4f/Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c#L260)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

curl APIs should've handled NULL internally IIRC. Would you pls double check?
</blockquote></details>

Done.
___
*[`Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c` line 262 at r8](https://reviewable.io/reviews/gramineproject/contrib/38#-Nef_oNM9UegGv_Tm9Yg:-NemY6RGEYtA971gCq4j:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/bd74f1243b26a66ad4dcfa2147433c987be46c4f/Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c#L262)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c` line 266 at r8](https://reviewable.io/reviews/gramineproject/contrib/38#-Nef_q7070Bocgdv5JHC:-NemY73LBsgAh8zmNVAu:b2fiww) ([raw file](https://github.com/gramineproject/contrib/blob/bd74f1243b26a66ad4dcfa2147433c987be46c4f/Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c#L266)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

No, I don't think we can remove it. See my other comment.
___
*[`Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c` line 286 at r8](https://reviewable.io/reviews/gramineproject/contrib/38#-NefdQRHDHUjWJIJaTye:-NemYCG8Esv8sjWpEI_N:b-ntjtol) ([raw file](https://github.com/gramineproject/contrib/blob/bd74f1243b26a66ad4dcfa2147433c987be46c4f/Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c#L286)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Not blocking, just wondering if it's better to introduce a macro for such checks?
</blockquote></details>

I hate macros that change control flow (e.g. contain a `goto` s [...]

2023-09-20 14:49 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/38)* status: 16 of 22 files reviewed, 18 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin, @mkow, and @omeg)

___
*[`-- commits` line 31 at r10](https://reviewable.io/reviews/gramineproject/contrib/38#-Nen35ajD_TsTcgshmzq):*
Tested the latest changes on a MS Azure virtual machine with MAA.

Did a small fixup for the `ra-tls-mbedtls` example. Everything works now.


<!-- Sent from Reviewable.io -->

2023-09-21 04:52 UTC, kailun-qin requested changes
> Reviewed 4 of 6 files at r9, 1 of 2 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/38)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`Integrations/azure/ra_tls_maa/README.md` line 109 at r11](https://reviewable.io/reviews/gramineproject/contrib/38#-Neq3WAyCkodW8_5odeI:-Neq3WAzCCpxQ4jMl9-T:b-w57dr9) ([raw file](https://github.com/gramineproject/contrib/blob/bbd8e60b8eee481626ebb364350acfbecb26c6fe/Integrations/azure/ra_tls_maa/README.md#L109)):*
> This is because MAA generates a JWT for the SGX enclave with a possibly-insecure status depending on the used MAA policy.

Yes, but how is this related w/ `RA_TLS_ALLOW_OUTDATED_TCB_INSECURE`, `RA_TLS_ALLOW_HW_CONFIG_NEEDED` and `RA_TLS_ALLOW_SW_HARDENING_NEEDED`?

I'm wondering if MAA provider/policy supports TCB level management at all?


<!-- Sent from Reviewable.io -->

2023-09-21 07:20 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/38)* status: 21 of 22 files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

___
*[`Integrations/azure/ra_tls_maa/README.md` line 109 at r11](https://reviewable.io/reviews/gramineproject/contrib/38#-Neq3WAyCkodW8_5odeI:-NeqZvrg762MC--wPtI8:bbqm102) ([raw file](https://github.com/gramineproject/contrib/blob/bbd8e60b8eee481626ebb364350acfbecb26c6fe/Integrations/azure/ra_tls_maa/README.md#L109)):*
> I'm wondering if MAA provider/policy supports TCB level management at all?

Yes, I think so. MAA documentation has this article: https://learn.microsoft.com/en-us/azure/attestation/custom-tcb-baseline-enforcement

The article is a bit hazy on the details, but I think their "custom TCB baselines" contain the TCB level management. So I would say "yes" to your question.

> Yes, but how is this related w/ `RA_TLS_ALLOW_OUTDATED_TCB_INSECURE`, `RA_TLS_ALLOW_HW_CONFIG_NEEDED` and `RA_TLS_ALLOW_SW_HARDENING_NEEDED`?

I reformulated this sentence. Please check if this sounds better to you.


<!-- Sent from Reviewable.io -->

2023-09-21 07:57 UTC, kailun-qin approved these changes
> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/38)* status: all files reviewed, 8 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`Integrations/azure/ra_tls_maa/README.md` line 109 at r11](https://reviewable.io/reviews/gramineproject/contrib/38#-Neq3WAyCkodW8_5odeI:-Neqhe28AF6K2z_fNJEE:b-fac8dh) ([raw file](https://github.com/gramineproject/contrib/blob/bbd8e60b8eee481626ebb364350acfbecb26c6fe/Integrations/azure/ra_tls_maa/README.md#L109)):*
> Yes, I think so. MAA documentation has this article: [https://learn.microsoft.com/en-us/azure/attestation/custom-tcb-baseline-enforcement](https://learn.microsoft.com/en-us/azure/attestation/custom-tcb-baseline-enforcement)
> The article is a bit hazy on the details, but I think their "custom TCB baselines" contain the TCB level management. So I would say "yes" to your question.

Great, thanks for the reference! I haven't read this article before -- the claim `x-ms-sgx-tcbidentifier` mentioned in it is not listed in the [claim sets doc](https://learn.microsoft.com/en-us/azure/attestation/claim-sets) so I missed it.

> I reformulated this sentence. Please check if this sounds better to you.

Definitely better, thanks!


<!-- Sent from Reviewable.io -->

2023-09-22 01:19 UTC, mkow requested changes
> Reviewed 3 of 6 files at r9, 1 of 2 files at r10, 1 of 1 files at r11, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/38)* status: all files reviewed, 3 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`Integrations/azure/ra_tls_maa/README.md` line 118 at r12](https://reviewable.io/reviews/gramineproject/contrib/38#-NesSjpT6qeb4TCtIQFR:-NesSjpT6qeb4TCtIQFS:biwacrq) ([raw file](https://github.com/gramineproject/contrib/blob/c267b52a2ba27c5ebff140dc6df9e9183d8e7962/Integrations/azure/ra_tls_maa/README.md#L118)):*
> ```Markdown
> 
> The library sets the following MAA-specific environment variables: (the library
> does not overwrite these environment variables, so you may want to unset them
> ```

Why not? Seems to be error-prone. Or at least we should fail in such case, warning is IMO not enough. I just don't want the user to accidentally use stale results from some other invocation.



_Code quote:_
```Markdown
does not overwrite these environment variables
```
___
*[`Integrations/azure/ra_tls_maa/src/ra_tls.map` line 4 at r8](https://reviewable.io/reviews/gramineproject/contrib/38#-Nek4RX95BC_sonr-yi2:-NesT5klDs6b_hquGRUN:b320dow) ([raw file](https://github.com/gramineproject/contrib/blob/bd74f1243b26a66ad4dcfa2147433c987be46c4f/Integrations/azure/ra_tls_maa/src/ra_tls.map#L4)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

It specifies the list of exported functions. That's the most clean way of generating shared libraries, no? We do the same in RA-TLS proper: https://github.com/gramineproject/gramine/blob/master/tools/sgx/ra-tls/ra_tls.map

We also do the same for the PAL library: https://github.com/gramineproject/gramine/blob/master/pal/src/host/linux/pal.map.template (where PAL_SYMBOLS are taken from https://github.com/gramineproject/gramine/blob/master/pal/src/pal_symbols)
</blockquote></details>

Hmm, ok. I think In PAL we just use linker script for multiple reasons, thus we also export using it. Anyways, I see the reason from the other discussion thread here, resolving.
___
*[`Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c` line 3 at r12](https://reviewable.io/reviews/gramineproject/contrib/38#-NeseLiO-5r4SpGc82Bg:-NeseLiO-5r4SpGc82Bh:b-3qyhhj) ([raw file](https://github.com/gramineproject/contrib/blob/c267b52a2ba27c5ebff140dc6df9e9183d8e7962/Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c#L3)):*
> ```C
> /* SPDX-License-Identifier: LGPL-3.0-or-later */
> /* Copyright (C) 2023 Intel Corporation */
> ```

FYI: I only did a light review of this code, will do a more thorough one if we decide to move it out of contrib someday.
___
*[`Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c` line 79 at r12](https://reviewable.io/reviews/gramineproject/contrib/38#-Nes_1BTCDCkz6lQvdIx:-Nes_1BTCDCkz6lQvdIy:b9ylxrg) ([raw file](https://github.com/gramineproject/contrib/blob/c267b52a2ba27c5ebff140dc6df9e9183d8e7962/Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c#L79)):*
> ```C
> 
> /*! Context used in maa_*() calls */
> struct maa_context_t {
> ```

Conventionally, in C you use `_t` suffix for "tagged structs", i.e. the typedefed ones where you don't need to add `struct` each time.



_Code quote:_
```C
struct maa_context_t
```
___
*[`Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c` line 151 at r12](https://reviewable.io/reviews/gramineproject/contrib/38#-Nesbba45KBh8zywLIlp:-Nesbba45KBh8zywLIlq:bat5zsp) ([raw file](https://github.com/gramineproject/contrib/blob/c267b52a2ba27c5ebff140dc6df9e9183d8e7962/Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c#L151)):*
> ```C
> 
> static int init_from_env(char** ptr, const char* env_name, const char* default_val) {
>     assert(ptr == &g_maa_base_url || ptr == &g_maa_api_version);
> ```

Why such an assert? Seems weird and quite useless.
___
*[`Integrations/azure/ra_tls_maa/src/secret_prov_verify_maa.c` line 9 at r8](https://reviewable.io/reviews/gramineproject/contrib/38#-Nek53-vBQNddRgnlF-b:-NesTiz13-iww6NMg14_:b-jpenv5) ([raw file](https://github.com/gramineproject/contrib/blob/bd74f1243b26a66ad4dcfa2147433c987be46c4f/Integrations/azure/ra_tls_maa/src/secret_prov_verify_maa.c#L9)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Unfortunately I don't find a way to do this in Meson.

First of all, symbols from static libs (even if they are exported) are NOT exported in the final shared library. The only way to export these symbols is to use the `--whole-archive` option. See e.g. https://stackoverflow.com/questions/2193944/convert-a-static-library-to-a-shared-library-create-libsome-so-from-libsome-a

Second, we need to add this `--whole-archive` option in Meson. And guess what -- it's a terrible mess in Meson:
- We must use the `.link_whole()` method: https://mesonbuild.com/Reference-manual_functions.html#library_link_whole
- But we have an object of a `dep` class, that is created by Meson from the `cc.find_library()` method: https://mesonbuild.com/Reference-manual_returned_compiler.html#compilerfind_library
- Now objects of the `dep` class have a method that we need called `.as_link_whole()`: https://mesonbuild.com/Reference-manual_returned_dep.html#depas_link_whole
- But I can't use this method, because `.as_link_whole()` applies **only** to `dep` objects that were created from the `declare_dependency()` method.

TLDR: My Meson code has an object `dep = cc.find_library()`, but I can't use `dep.as_link_whole()` because that method would only be applicable if I would do `dep = declare_dependency()`. So I need now to transform my dependency object from `cc.find_library()` into `declare_dependency()`, and at this point I am tired of fighting Meson, and give up.
</blockquote></details>

Hmm, interesting. Ok, let's stay with linker scripts then.


<!-- Sent from Reviewable.io -->

2023-09-22 07:10 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/38)* status: 20 of 22 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

___
*[`Integrations/azure/ra_tls_maa/README.md` line 118 at r12](https://reviewable.io/reviews/gramineproject/contrib/38#-NesSjpT6qeb4TCtIQFR:-Neve5cV9vSEJdrJbQeZ:bn51jah) ([raw file](https://github.com/gramineproject/contrib/blob/c267b52a2ba27c5ebff140dc6df9e9183d8e7962/Integrations/azure/ra_tls_maa/README.md#L118)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why not? Seems to be error-prone. Or at least we should fail in such case, warning is IMO not enough. I just don't want the user to accidentally use stale results from some other invocation.
</blockquote></details>

Done. I thought like this condition doesn't deserve to error out, but Ok.
___
*[`Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c` line 79 at r12](https://reviewable.io/reviews/gramineproject/contrib/38#-Nes_1BTCDCkz6lQvdIx:-NevfW9EEeaEeNjxyxg_:b6bwjoz) ([raw file](https://github.com/gramineproject/contrib/blob/c267b52a2ba27c5ebff140dc6df9e9183d8e7962/Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c#L79)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Conventionally, in C you use `_t` suffix for "tagged structs", i.e. the typedefed ones where you don't need to add `struct` each time.
</blockquote></details>

Done. The `_t` suffix was here because I based this PR on our IAS code: https://github.com/gramineproject/gramine/blob/ac8fc770d1004dbcaf43a5b805a7928b7c4fb90f/tools/sgx/common/ias.c#L46

But I agree, that code is old and doesn't use our typical conventions.
___
*[`Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c` line 151 at r12](https://reviewable.io/reviews/gramineproject/contrib/38#-Nesbba45KBh8zywLIlp:-NeveVoD0MX7C9eBfq4K:b-65216t) ([raw file](https://github.com/gramineproject/contrib/blob/c267b52a2ba27c5ebff140dc6df9e9183d8e7962/Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c#L151)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why such an assert? Seems weird and quite useless.
</blockquote></details>

Done. Removed. This assert was just to make sure we only initialize these two particular envvars. But I see your point.


<!-- Sent from Reviewable.io -->

2023-09-22 07:36 UTC, kailun-qin approved these changes
> This PR is a re-creation of [gramineproject/gramine#652](https://github.com/gramineproject/gramine/pull/652). That original PR added MAA versions of RA-TLS and SecretProv libs **inside core Gramine**. Now this new PR adds MAA versions as **plugins**, which are currently hosted in the `contrib` repo.

Should we add somewhere in core Gramine that point to the MAA versions of RA-TLS and SecretProv libs here in the `contrib` repo?

> Reviewed 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/38#-:-NevnfcyC1RiD7t-mxKW:b-bqqnpv)* status: all files reviewed, 3 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2023-09-22 07:45 UTC, dimakuv reviewed
> Should we add somewhere in core Gramine that point to the MAA versions of RA-TLS and SecretProv libs here in the `contrib` repo?

I'm not sure. If yes, then my proposal will be to add a new sub-section "Vendor-specific plugins" in the "Attestation" docs page, right-before the "Third Party solutions" sub-section (https://gramine.readthedocs.io/en/stable/attestation.html#third-party-solutions). And in this new sub-section have a list with only one item (currently) which is Microsoft Azure Attestation and a link to the corresponding `contrib` subdirectory.

@mkow WDYT?

> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/38#-:-Nevpp6-0B8X5no6g3T3:b-tw0q3b)* status: all files reviewed, 3 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2023-09-22 12:57 UTC, mkow approved these changes
I'd rather wait a bit until more users test this, but I'm also fine with mentioning it if you want. But please add a disclaimer that this is not an official part of the project yet and wasn't thoroughly reviewed in terms of security.

> Reviewed 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/38#-:-NewwHl2DCnu5SNoWs0l:bqsdixb)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[`Integrations/azure/ra_tls_maa/README.md` line 118 at r12](https://reviewable.io/reviews/gramineproject/contrib/38#-NesSjpT6qeb4TCtIQFR:-NewwggX6dl1pVOF1_HT:b-u73n6t) ([raw file](https://github.com/gramineproject/contrib/blob/c267b52a2ba27c5ebff140dc6df9e9183d8e7962/Integrations/azure/ra_tls_maa/README.md#L118)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. I thought like this condition doesn't deserve to error out, but Ok.
</blockquote></details>

IMO it's always a bug if such a condition happens, and the user shouldn't be able to overlook it.
___
*[`Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c` line 79 at r12](https://reviewable.io/reviews/gramineproject/contrib/38#-Nes_1BTCDCkz6lQvdIx:-NewxB2f1NR2Y7LdmX9u:bhuv269) ([raw file](https://github.com/gramineproject/contrib/blob/c267b52a2ba27c5ebff140dc6df9e9183d8e7962/Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c#L79)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. The `_t` suffix was here because I based this PR on our IAS code: https://github.com/gramineproject/gramine/blob/ac8fc770d1004dbcaf43a5b805a7928b7c4fb90f/tools/sgx/common/ias.c#L46

But I agree, that code is old and doesn't use our typical conventions.
</blockquote></details>

I don't think this is "our" convention, it's rather a general convention in C?


<!-- Sent from Reviewable.io -->

2023-09-25 07:14 UTC, dimakuv reviewed
Ok, I won't create such a PR now. I created a GitHub issue instead, not to forget about this in the future: https://github.com/gramineproject/gramine/issues/1569

> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/38#-:-NfAAseI2BOa6lPuun4y:bihjhgb)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[`Integrations/azure/ra_tls_maa/README.md` line 118 at r12](https://reviewable.io/reviews/gramineproject/contrib/38#-NesSjpT6qeb4TCtIQFR:-NfAAzST2lg2OtREj5rZ:bz9z37b) ([raw file](https://github.com/gramineproject/contrib/blob/c267b52a2ba27c5ebff140dc6df9e9183d8e7962/Integrations/azure/ra_tls_maa/README.md#L118)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

IMO it's always a bug if such a condition happens, and the user shouldn't be able to overlook it.
</blockquote></details>

OK, fair enough
___
*[`Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c` line 79 at r12](https://reviewable.io/reviews/gramineproject/contrib/38#-Nes_1BTCDCkz6lQvdIx:-NfAB-zY3inBwDHwL-s2:bwrgouw) ([raw file](https://github.com/gramineproject/contrib/blob/c267b52a2ba27c5ebff140dc6df9e9183d8e7962/Integrations/azure/ra_tls_maa/src/ra_tls_verify_maa.c#L79)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I don't think this is "our" convention, it's rather a general convention in C?
</blockquote></details>

Yes, true, it's a general C convention.


<!-- Sent from Reviewable.io -->

2023-09-25 07:18 UTC, merged