[Curated-Apps] Add MySQL
gramineproject/contrib pull request #40
Opened 2023-03-15 09:14 UTC by jkr0103

Curate MySQL server.

PR https://github.com/gramineproject/contrib/pull/39 is prerequisite for this PR.

2023-03-16 09:31 UTC, dimakuv requested changes
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/40)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @jkr0103)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/40#-NQdizukBprZXbWb2EFM:-NQdizul-rkqkr0qKM40:b-lovid1) (no related file):*
Blocking until #39 is merged.

___
___
*[`Curated-Apps/workloads/mysql/mysql.manifest.template` line 18 at r1](https://reviewable.io/reviews/gramineproject/contrib/40#-NQdkWEPAdnKxKc9MKrc:-NQdkWEPAdnKxKc9MKrd:b-wdc6bf) ([raw file](https://github.com/gramineproject/contrib/blob/4a4ef141d3caca83c49b8e554eda516418d6a913/Curated-Apps/workloads/mysql/mysql.manifest.template#L18)):*
> ```
> 
> fs.mounts = [
>   { path = "/var/run/mysqld", uri = "file:/var/run/mysqld", type = "encrypted" },
> ```

How can this work? Shouldn't it be `/var/run/test_db_encrypted`?
___
*[`Curated-Apps/workloads/mysql/README.md` line 8 at r1](https://reviewable.io/reviews/gramineproject/contrib/40#-NQdjESW84d7cvXCQTAV:-NQdjESW84d7cvXCQTAW:b2z7i) ([raw file](https://github.com/gramineproject/contrib/blob/4a4ef141d3caca83c49b8e554eda516418d6a913/Curated-Apps/workloads/mysql/README.md#L8)):*
> ```Markdown
> 
> ## Build a confidential compute image for MySQL
> Execute the below commands on the VM.
> ```

`on the VM` -> `on your system`?

By the way, if we had this sentence in other (already-existing) workloads, could we also change for them in this PR (or in a separate PR, if you feel so).
___
*[`Curated-Apps/workloads/mysql/README.md` line 29 at r1](https://reviewable.io/reviews/gramineproject/contrib/40#-NQdkGnJ4ocxKNMJaCEe:-NQdkGnJ4ocxKNMJaCEf:b-737j46) ([raw file](https://github.com/gramineproject/contrib/blob/4a4ef141d3caca83c49b8e554eda516418d6a913/Curated-Apps/workloads/mysql/README.md#L29)):*
> ```Markdown
>    ```
> 
> 3. Encrypt MySQL database (optional)
> ```

Why do you say it's `(optional)`? Looks like this whole PR assumes that MySQL works on `/var/run/test_db_encrypted`?
___
*[`Curated-Apps/workloads/mysql/README.md` line 33 at r1](https://reviewable.io/reviews/gramineproject/contrib/40#-NQdjVjTEPudkIzR6BRi:-NQdjVjTEPudkIzR6BRj:ba3pcgp) ([raw file](https://github.com/gramineproject/contrib/blob/4a4ef141d3caca83c49b8e554eda516418d6a913/Curated-Apps/workloads/mysql/README.md#L33)):*
> ```Markdown
>    1. Install prerequisites for encrypting MySQL database
> 
>       [Install Gramine](https://gramine.readthedocs.io/en/latest/quickstart.html#install-gramine): Encryption is done using `gramine-sgx-pf-crypt` tool which is part of Gramine installation.
> ```

Please fix to 100-chars-per-line
___
*[`Curated-Apps/workloads/mysql/README.md` line 44 at r1](https://reviewable.io/reviews/gramineproject/contrib/40#-NQdjgOy1lQNpdthNnlS:-NQdjgOy1lQNpdthNnlT:b-h309vv) ([raw file](https://github.com/gramineproject/contrib/blob/4a4ef141d3caca83c49b8e554eda516418d6a913/Curated-Apps/workloads/mysql/README.md#L44)):*
> ```Markdown
>           -i workloads/mysql/test_db -o /var/run/test_db_encrypted
>       ```
>       The above commands encrypts MySQL database `workloads/mysql/test_db` to
> ```

`encrypts` -> `encrypt`
___
*[`Curated-Apps/workloads/mysql/README.md` line 50 at r1](https://reviewable.io/reviews/gramineproject/contrib/40#-NQdjoMT9kxnRAMi7eDs:-NQdjoMT9kxnRAMi7eDt:b-alg58r) ([raw file](https://github.com/gramineproject/contrib/blob/4a4ef141d3caca83c49b8e554eda516418d6a913/Curated-Apps/workloads/mysql/README.md#L50)):*
> ```Markdown
> 
> 4. Generate the test confidential compute image based on the `mysql:8.0.32-debian` image as shown
>       below:
> ```

The indentation is wrong (should be just 3 spaces)
___
*[`Curated-Apps/workloads/mysql/README.md` line 73 at r1](https://reviewable.io/reviews/gramineproject/contrib/40#-NQdk0Wm8sAjE-1n3DS6:-NQdk0Wm8sAjE-1n3DS7:bz5f7nb) ([raw file](https://github.com/gramineproject/contrib/blob/4a4ef141d3caca83c49b8e554eda516418d6a913/Curated-Apps/workloads/mysql/README.md#L73)):*
> ```Markdown
>    ```
> 
>    Connect client to the MySQL server created using test confidential compute image using command:
> ```

Too hard to read. Maybe simply `Connect the client to the MySQL server created above:`


<!-- Sent from Reviewable.io -->

2023-03-16 10:34 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/40)* status: 7 of 12 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`Curated-Apps/workloads/mysql/mysql.manifest.template` line 18 at r1](https://reviewable.io/reviews/gramineproject/contrib/40#-NQdkWEPAdnKxKc9MKrc:-NQdx-6rAk_PmsQdkojX:b-6vstrc) ([raw file](https://github.com/gramineproject/contrib/blob/4a4ef141d3caca83c49b8e554eda516418d6a913/Curated-Apps/workloads/mysql/mysql.manifest.template#L18)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

How can this work? Shouldn't it be `/var/run/test_db_encrypted`?
</blockquote></details>

No, this is to allow creation of `/var/run/mysqld/mysqld.sock` file along with some other files. `/var/run/mysqld/mysqld.sock` is used for socket connections by MySQL.

Mounting of `/var/run/test_db_encrypted` in test mode is handled by this code:https://github.com/gramineproject/contrib/blob/94f110c30088f29d6cc523a9527e11161024b60e/Curated-Apps/util/curation_script.sh#L107
___
*[`Curated-Apps/workloads/mysql/README.md` line 8 at r1](https://reviewable.io/reviews/gramineproject/contrib/40#-NQdjESW84d7cvXCQTAV:-NQdxmeBANTctL6ND5Y2:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/4a4ef141d3caca83c49b8e554eda516418d6a913/Curated-Apps/workloads/mysql/README.md#L8)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`on the VM` -> `on your system`?

By the way, if we had this sentence in other (already-existing) workloads, could we also change for them in this PR (or in a separate PR, if you feel so).
</blockquote></details>

Done.
___
*[`Curated-Apps/workloads/mysql/README.md` line 29 at r1](https://reviewable.io/reviews/gramineproject/contrib/40#-NQdkGnJ4ocxKNMJaCEe:-NQdxphZ32WUPdw5BJwt:bv2m799) ([raw file](https://github.com/gramineproject/contrib/blob/4a4ef141d3caca83c49b8e554eda516418d6a913/Curated-Apps/workloads/mysql/README.md#L29)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do you say it's `(optional)`? Looks like this whole PR assumes that MySQL works on `/var/run/test_db_encrypted`?
</blockquote></details>

Not exactly, user may also use non-encrypted database but with non-test mode as mentioned in Step 5 in README.
___
*[`Curated-Apps/workloads/mysql/README.md` line 33 at r1](https://reviewable.io/reviews/gramineproject/contrib/40#-NQdjVjTEPudkIzR6BRi:-NQdyFli6ZjACJ4kW49h:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/4a4ef141d3caca83c49b8e554eda516418d6a913/Curated-Apps/workloads/mysql/README.md#L33)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please fix to 100-chars-per-line
</blockquote></details>

Done.
___
*[`Curated-Apps/workloads/mysql/README.md` line 44 at r1](https://reviewable.io/reviews/gramineproject/contrib/40#-NQdjgOy1lQNpdthNnlS:-NQdyGQz0-n2LhLmo396:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/4a4ef141d3caca83c49b8e554eda516418d6a913/Curated-Apps/workloads/mysql/README.md#L44)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`encrypts` -> `encrypt`
</blockquote></details>

Done.
___
*[`Curated-Apps/workloads/mysql/README.md` line 50 at r1](https://reviewable.io/reviews/gramineproject/contrib/40#-NQdjoMT9kxnRAMi7eDs:-NQdyH2b3LNt5DmDcRvZ:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/4a4ef141d3caca83c49b8e554eda516418d6a913/Curated-Apps/workloads/mysql/README.md#L50)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The indentation is wrong (should be just 3 spaces)
</blockquote></details>

Done.
___
*[`Curated-Apps/workloads/mysql/README.md` line 73 at r1](https://reviewable.io/reviews/gramineproject/contrib/40#-NQdk0Wm8sAjE-1n3DS6:-NQdyHrZ-8L2NQwyAKnD:b-y0jlpg) ([raw file](https://github.com/gramineproject/contrib/blob/4a4ef141d3caca83c49b8e554eda516418d6a913/Curated-Apps/workloads/mysql/README.md#L73)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Too hard to read. Maybe simply `Connect the client to the MySQL server created above:`
</blockquote></details>

Actually same command might not apply with custome image created using step 5 in README. User might have set password for root or even removed remote access for root user, in that case same command will not work.


<!-- Sent from Reviewable.io -->

2023-03-16 10:46 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/40)* status: 7 of 12 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @jkr0103)

___
*[`Curated-Apps/workloads/mysql/README.md` line 73 at r1](https://reviewable.io/reviews/gramineproject/contrib/40#-NQdk0Wm8sAjE-1n3DS6:-NQe0RZ983mSxiEEv-OP:b1399c7) ([raw file](https://github.com/gramineproject/contrib/blob/4a4ef141d3caca83c49b8e554eda516418d6a913/Curated-Apps/workloads/mysql/README.md#L73)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

Actually same command might not apply with custome image created using step 5 in README. User might have set password for root or even removed remote access for root user, in that case same command will not work.
</blockquote></details>

How about `To connect the client to the test MySQL server created at step 4: `


<!-- Sent from Reviewable.io -->

2023-03-16 10:56 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/40)* status: 7 of 12 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`Curated-Apps/workloads/mysql/README.md` line 73 at r1](https://reviewable.io/reviews/gramineproject/contrib/40#-NQdk0Wm8sAjE-1n3DS6:-NQe329D36WAUQr6xAF9:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/4a4ef141d3caca83c49b8e554eda516418d6a913/Curated-Apps/workloads/mysql/README.md#L73)):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

How about `To connect the client to the test MySQL server created at step 4: `
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-16 12:50 UTC, dimakuv requested changes
> Reviewed 4 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/40)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @jkr0103)

___
*[`Curated-Apps/workloads/mysql/mysql.manifest.template` line 18 at r1](https://reviewable.io/reviews/gramineproject/contrib/40#-NQdkWEPAdnKxKc9MKrc:-NQeSD8hDT8JBeNbeTJf:b-g0xmm1) ([raw file](https://github.com/gramineproject/contrib/blob/4a4ef141d3caca83c49b8e554eda516418d6a913/Curated-Apps/workloads/mysql/mysql.manifest.template#L18)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

No, this is to allow creation of `/var/run/mysqld/mysqld.sock` file along with some other files. `/var/run/mysqld/mysqld.sock` is used for socket connections by MySQL.

Mounting of `/var/run/test_db_encrypted` in test mode is handled by this code:https://github.com/gramineproject/contrib/blob/94f110c30088f29d6cc523a9527e11161024b60e/Curated-Apps/util/curation_script.sh#L107
</blockquote></details>

Ah, that's how it works. Thanks for explanation.
___
*[`Curated-Apps/workloads/mysql/README.md` line 29 at r1](https://reviewable.io/reviews/gramineproject/contrib/40#-NQdkGnJ4ocxKNMJaCEe:-NQeSb9yEI2TJ30aoBqW:b-v0z6zh) ([raw file](https://github.com/gramineproject/contrib/blob/4a4ef141d3caca83c49b8e554eda516418d6a913/Curated-Apps/workloads/mysql/README.md#L29)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

Not exactly, user may also use non-encrypted database but with non-test mode as mentioned in Step 5 in README.
</blockquote></details>

Do we actually want to mention this flexibility? I would just assume that the database must be encrypted, and then we wouldn't need all these `(optional)` and `step 3 is mandatory` in the description.

Right now it's really hard to understand that there are two different ways of curating MySQL for a "normal user".
___
*[`Curated-Apps/workloads/mysql/README.md` line 51 at r3](https://reviewable.io/reviews/gramineproject/contrib/40#-NQeSx-CDqIOrKNqLRsb:-NQeSx-CDqIOrKNqLRsc:b-h83she) ([raw file](https://github.com/gramineproject/contrib/blob/9336b5b738742a0d11e1d7f1f83aa7b09e710998/Curated-Apps/workloads/mysql/README.md#L51)):*
> ```Markdown
> 
> 4. Generate the test confidential compute image with encrypted database. Step 3 is mandatory before
>    proceeding here:
> ```

If we go with "always encrypted database" logic that I propose, this additional "Step 3 is mandatory..." won't be needed.


<!-- Sent from Reviewable.io -->

2023-03-17 07:17 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/40)* status: 11 of 12 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`Curated-Apps/workloads/mysql/README.md` line 29 at r1](https://reviewable.io/reviews/gramineproject/contrib/40#-NQdkGnJ4ocxKNMJaCEe:-NQiQTbC5X8NnAklIaQi:b-ct0hq4) ([raw file](https://github.com/gramineproject/contrib/blob/4a4ef141d3caca83c49b8e554eda516418d6a913/Curated-Apps/workloads/mysql/README.md#L29)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Do we actually want to mention this flexibility? I would just assume that the database must be encrypted, and then we wouldn't need all these `(optional)` and `step 3 is mandatory` in the description.

Right now it's really hard to understand that there are two different ways of curating MySQL for a "normal user".
</blockquote></details>

agree, done!
___
*[`Curated-Apps/workloads/mysql/README.md` line 51 at r3](https://reviewable.io/reviews/gramineproject/contrib/40#-NQeSx-CDqIOrKNqLRsb:-NQiQW8M1S5YNjUdE891:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/9336b5b738742a0d11e1d7f1f83aa7b09e710998/Curated-Apps/workloads/mysql/README.md#L51)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

If we go with "always encrypted database" logic that I propose, this additional "Step 3 is mandatory..." won't be needed.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-17 09:26 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/40)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @jkr0103)



<!-- Sent from Reviewable.io -->

2023-03-20 16:01 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/40)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @jkr0103)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/40#-NQdizukBprZXbWb2EFM:-NQzkETl3tL90iprdFk6:b-wn3ar9) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Blocking until #39 is merged.
</blockquote></details>

PR was merge now, please update your PR and verify that it works correctly.

___


<!-- Sent from Reviewable.io -->

2023-03-21 06:59 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/40)* status: 7 of 12 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/40#-NQdizukBprZXbWb2EFM:-NR1xOSrEhCDSG4ddgHy:b-owk0mb) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

PR was merge now, please update your PR and verify that it works correctly.
</blockquote></details>

I have rebase it and run sanity, all tests passed. But it should be blocked until PR https://github.com/gramineproject/gsc/pull/136 gets merged

___


<!-- Sent from Reviewable.io -->

2023-03-21 08:22 UTC, dimakuv requested changes
> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/40)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @jkr0103)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/40#-NQdizukBprZXbWb2EFM:-NR2FiiY1fDApSUjCXsL:b-sgb5kp) (no related file):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

I have rebase it and run sanity, all tests passed. But it should be blocked until PR https://github.com/gramineproject/gsc/pull/136 gets merged
</blockquote></details>

Ok, let's keep this blocking comment until PR 136 in GSC repo is merged.

___


<!-- Sent from Reviewable.io -->

2023-03-21 12:50 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/40)* status: 11 of 13 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/40#-NQdizukBprZXbWb2EFM:-NR3ChTiAILP63pMY7B7:b-vzh2h7) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ok, let's keep this blocking comment until PR 136 in GSC repo is merged.
</blockquote></details>

it can be unblocked now. Curated-Apps is using out of tree GSC brach `v1.4-for-curated-apps` to take LD_LIBRARY_PATH related fix for debian entrypoint manifest.

___


<!-- Sent from Reviewable.io -->

2023-03-22 08:29 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/40)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @jkr0103)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/40#-NQdizukBprZXbWb2EFM:-NR7PivQ7MKQbJqIzyXF:b-by07d8) (no related file):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

it can be unblocked now. Curated-Apps is using out of tree GSC brach `v1.4-for-curated-apps` to take LD_LIBRARY_PATH related fix for debian entrypoint manifest.
</blockquote></details>

Just a bit of context:
- Curated Apps (in particular, this MySQL workload) required the bug fix that was done in https://github.com/gramineproject/gsc/pull/136
- Unfortunately, this bug fix happened after the release v1.4 of Gramine/GSC
- We cannot just move the GSC tag `v1.4` to the latest GSC master (where https://github.com/gramineproject/gsc/pull/136 is merged): mainly because we also need to modify the `config.yaml.template` file (in the master branch, it always has [`Branch: master` field](https://github.com/gramineproject/gsc/blob/fa5a07385ac205d89fb6ddb2bc5505ebe97d0539/config.yaml.template#L22), but we need to point to `v1.4` core Gramine repo)
- So I created a temporary branch `v1.4-for-curated-apps`, that is based on the master branch, but also modifies the `config.yaml.template` to point to `v1.4` core Gramine version, see https://github.com/gramineproject/gsc/tree/v1.4-for-curated-apps

Once we have a new release of Gramine/GSC, Curated Apps will move to this new release, and I will remove the temporary branch `v1.4-for-curated-apps`.

___
___
*[`Curated-Apps/util/curation_script.sh` line 124 at r6](https://reviewable.io/reviews/gramineproject/contrib/40#-NR7QnUl0UFaBXlATrVP:-NR7QnUl0UFaBXlATrVQ:b-6i6z8a) ([raw file](https://github.com/gramineproject/contrib/blob/cd4028fe225aa4c552c81532c6f98b65b3f294a0/Curated-Apps/util/curation_script.sh#L124)):*
> ```Shell
>     rm -rf gsc >/dev/null 2>&1
>     # Using out of tree GSC brach `v1.4-for-curated-apps` to take the fix with commit
>     # fa5a07385ac205d89fb6ddb2bc5505ebe97d0539
> ```

Can you make add a `FIXME: ` in the beginning? So that it's obvious in the future that this place needs special attention (that we'll need to remove this comment once we move to a proper `v1.5` ).


<!-- Sent from Reviewable.io -->

2023-03-22 10:51 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/40)* status: 12 of 13 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`Curated-Apps/util/curation_script.sh` line 124 at r6](https://reviewable.io/reviews/gramineproject/contrib/40#-NR7QnUl0UFaBXlATrVP:-NR7wSJR4UtHqKiWTMk4:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/cd4028fe225aa4c552c81532c6f98b65b3f294a0/Curated-Apps/util/curation_script.sh#L124)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can you make add a `FIXME: ` in the beginning? So that it's obvious in the future that this place needs special attention (that we'll need to remove this comment once we move to a proper `v1.5` ).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-22 11:04 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/40)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-03-22 14:43 UTC, aneessahib reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/40#-:-NR8lSw444hI2zltSSsK:bnfp4nl)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-03-24 01:25 UTC, mkow requested changes
> Reviewed 7 of 8 files at r1, 4 of 5 files at r5, 1 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/40)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @jkr0103)

___
*[`Curated-Apps/workloads/mysql/mysql.manifest.template` line 13 at r7](https://reviewable.io/reviews/gramineproject/contrib/40#-NRG4Zt3834_XXEQ6N7A:-NRG4Zt3834_XXEQ6N7B:b-ak3vb6) ([raw file](https://github.com/gramineproject/contrib/blob/696f81ce784d9b2c2469af11ebf31199c7715dde/Curated-Apps/workloads/mysql/mysql.manifest.template#L13)):*
> ```
> # This is required to run workload as non-root user, any number works except `0` which is for root.
> loader.uid=999
> loader.gid=999
> ```

spaces around `=`
___
*[`Curated-Apps/workloads/mysql/README.md` line 1 at r7](https://reviewable.io/reviews/gramineproject/contrib/40#-NRG5dCLBa3HAjodj5CJ:-NRG5dCMC9JPH9_xny9E:bu83s0p) ([raw file](https://github.com/gramineproject/contrib/blob/696f81ce784d9b2c2469af11ebf31199c7715dde/Curated-Apps/workloads/mysql/README.md#L1)):*
> ```Markdown
> # Gramine Curated MySQL
> ```

please add empty lines after headings
___
*[`Curated-Apps/workloads/mysql/README.md` line 61 at r7](https://reviewable.io/reviews/gramineproject/contrib/40#-NRGBg5v1XWGqsLXTM04:-NRGBg5v1XWGqsLXTM05:bhnhilf) ([raw file](https://github.com/gramineproject/contrib/blob/696f81ce784d9b2c2469af11ebf31199c7715dde/Curated-Apps/workloads/mysql/README.md#L61)):*
> ```Markdown
>    ```
> 
>    Please provide below inputs on UI:
> ```

(or "using")



_Suggestion:_
```Markdown
inputs via UI
```


<!-- Sent from Reviewable.io -->

2023-03-24 04:59 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/40)* status: 11 of 17 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`Curated-Apps/workloads/mysql/mysql.manifest.template` line 13 at r7](https://reviewable.io/reviews/gramineproject/contrib/40#-NRG4Zt3834_XXEQ6N7A:-NRGz-Gy8MMERcHVC9wu:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/696f81ce784d9b2c2469af11ebf31199c7715dde/Curated-Apps/workloads/mysql/mysql.manifest.template#L13)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

spaces around `=`
</blockquote></details>

Done.
___
*[`Curated-Apps/workloads/mysql/README.md` line 1 at r7](https://reviewable.io/reviews/gramineproject/contrib/40#-NRG5dCLBa3HAjodj5CJ:-NRGz-zA1h6fbSokLOgd:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/696f81ce784d9b2c2469af11ebf31199c7715dde/Curated-Apps/workloads/mysql/README.md#L1)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

please add empty lines after headings
</blockquote></details>

Done.
___
*[`Curated-Apps/workloads/mysql/README.md` line 61 at r7](https://reviewable.io/reviews/gramineproject/contrib/40#-NRGBg5v1XWGqsLXTM04:-NRGz4xA4Q67J--kUHc7:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/696f81ce784d9b2c2469af11ebf31199c7715dde/Curated-Apps/workloads/mysql/README.md#L61)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

(or "using")
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-24 08:27 UTC, dimakuv approved these changes
> Reviewed 6 of 6 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/40)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2023-03-27 00:44 UTC, mkow submitted a review, later dismissed
> Reviewed 6 of 6 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/40)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/40#-NQdizukBprZXbWb2EFM:-NRVVNhI1eX49aY8ADnk:brin23q) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Just a bit of context:
- Curated Apps (in particular, this MySQL workload) required the bug fix that was done in https://github.com/gramineproject/gsc/pull/136
- Unfortunately, this bug fix happened after the release v1.4 of Gramine/GSC
- We cannot just move the GSC tag `v1.4` to the latest GSC master (where https://github.com/gramineproject/gsc/pull/136 is merged): mainly because we also need to modify the `config.yaml.template` file (in the master branch, it always has [`Branch: master` field](https://github.com/gramineproject/gsc/blob/fa5a07385ac205d89fb6ddb2bc5505ebe97d0539/config.yaml.template#L22), but we need to point to `v1.4` core Gramine repo)
- So I created a temporary branch `v1.4-for-curated-apps`, that is based on the master branch, but also modifies the `config.yaml.template` to point to `v1.4` core Gramine version, see https://github.com/gramineproject/gsc/tree/v1.4-for-curated-apps

Once we have a new release of Gramine/GSC, Curated Apps will move to this new release, and I will remove the temporary branch `v1.4-for-curated-apps`.
</blockquote></details>

I think basing Curated Apps on GSC was one of the Curated Apps' biggest design mistakes... (and I'm not saying here that this is a GSC's fault in any way, it just wasn't designed to be used as a framework with an API, but as a manual tool for end-users).

___


<!-- Sent from Reviewable.io -->

2023-03-27 07:53 UTC, dimakuv approved these changes
> Reviewed 6 of 6 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/40)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/40#-NQdizukBprZXbWb2EFM:-NRX21wK0VZwSMEWzi9o:biwkunm) (no related file):*
> I think basing Curated Apps on GSC was one of the Curated Apps' biggest design mistakes...

Interesting point.

I wonder if Curated Apps really requires only a subset of GSC functionality (e.g. only Ubuntu/Debian Dockerfiles + a subset of GSC python scripts). This way, I can imagine Curated Apps just copy-pasting the GSC sources into a subdirectory, and then there is no explicit dependency on GSC, and one level of indirection less. And the problems with GSC could be fixed inside Curated Apps themselves...

Just thinking out loud. I also see benefits from Curated Apps using GSC -- first of all, it's a great testing ground for GSC :)

___


<!-- Sent from Reviewable.io -->

2023-03-27 09:53 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/40)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @jkr0103)

___
*[`Curated-Apps/workloads/mysql/mysql.manifest.template` line 8 at r9](https://reviewable.io/reviews/gramineproject/contrib/40#-NRXU6YO65M1EdPE8Ca2:-NRXU6YO65M1EdPE8Ca3:b-oqj3c8) ([raw file](https://github.com/gramineproject/contrib/blob/d216b62ee6b1073dd3f3794f0bafcacf7440383c/Curated-Apps/workloads/mysql/mysql.manifest.template#L8)):*
> ```
> 
> sgx.nonpie_binary = true
> sgx.enclave_size = "8G"
> ```

@jkr0103 is experimenting currently with `4G` enclave size (to reduce startup time). He is currently running the tests, to see if it will work. Blocking until he finishes the experiments.


<!-- Sent from Reviewable.io -->

2023-03-27 16:14 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/40)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @jkr0103)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/40#-NQdizukBprZXbWb2EFM:-NRYoRkW1tdiG6lXRUZp:bw7mrw5) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

GSC is rather simple by itself, you could reimplement its functionality here and adjust to Curated Apps needs easily.
</blockquote></details>

Actually, part of the objective of using GSC with Curated Apps is to strengthen GSC itself (as this is the only docker container solution we have for Gramine). IMO, reimplementing GSC in Curated apps is highly redundant. Instead, maybe its better to have GSC expose some python APIs that can be consumed by Curated apps?

___


<!-- Sent from Reviewable.io -->

2023-03-27 18:56 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/40)* status: 14 of 21 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`Curated-Apps/workloads/mysql/mysql.manifest.template` line 8 at r9](https://reviewable.io/reviews/gramineproject/contrib/40#-NRXU6YO65M1EdPE8Ca2:-NRZQLtc6mucLK93yLwE:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/d216b62ee6b1073dd3f3794f0bafcacf7440383c/Curated-Apps/workloads/mysql/mysql.manifest.template#L8)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@jkr0103 is experimenting currently with `4G` enclave size (to reduce startup time). He is currently running the tests, to see if it will work. Blocking until he finishes the experiments.
</blockquote></details>

Done.
___
*[`Curated-Apps/workloads/pytorch/pytorch-gsc.dockerfile.template` line 11 at r9](https://reviewable.io/reviews/gramineproject/contrib/40#-NRXYv0U3nP2H8Lk3z5m:-NRZQSC98uw3v3pWSgRh:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/d216b62ee6b1073dd3f3794f0bafcacf7440383c/Curated-Apps/workloads/pytorch/pytorch-gsc.dockerfile.template#L11)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This is terrible, why are these custom-made templates using `<asdf>` above as a template syntax, but an ordinary comment here?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-28 07:54 UTC, dimakuv approved these changes
> Reviewed 6 of 7 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/40)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/40#-NQdizukBprZXbWb2EFM:-NRbCGRQC70pa9GRnO5n:b-ercff7) (no related file):*
> Instead, maybe its better to have GSC expose some python APIs that can be consumed by Curated apps?

Yes, that would also be an option.

___


<!-- Sent from Reviewable.io -->

2023-03-28 12:59 UTC, mkow approved these changes
> Reviewed 6 of 7 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/40)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/40#-NQdizukBprZXbWb2EFM:-NRcDZas0QImoCTjtjZF:be4vufl) (no related file):*
> part of the objective of using GSC with Curated Apps is to strengthen GSC itself

The problem here is that GSC is intended to be a simple tool for the end users which allows them to quickly test Gramine on a Docker image they already have, without much configuration (at least that's how I understand it). Adding such features and additional APIs makes it more complex without making anything user-facing in GSC better. It feels like implementing a half of curated apps in GSC and a half here.

But I agree that GSC benefits from more testing via curated apps, although I think that's the _only_ benefit.

> reimplementing GSC in Curated apps is highly redundant

GSC is literally a couple of lines in Python if you strip all user interactions and similar things which don't apply to curated apps :)

___


<!-- Sent from Reviewable.io -->

2023-03-28 15:05 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/40)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2023-03-28 16:50 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/40)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-03-28 17:02 UTC, merged