[Curated-Apps] Add MariaDB
gramineproject/contrib pull request #41
Opened 2023-03-17 13:19 UTC by sahason

Curate MariaDB server.

PR #39 is a prerequisite for this PR.

2023-03-20 16:01 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/41)* status: 0 of 8 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @sahason)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/41#-NQzkDL92OF-kTt9_zbw:-NQzkDLA9iD_PwCt-867:b-wn3ar9) (no related file):*
PR was merge now, please update your PR and verify that it works correctly.

___


<!-- Sent from Reviewable.io -->

2023-03-21 07:14 UTC, sahason reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/41)* status: 0 of 8 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/41#-NQzkDL92OF-kTt9_zbw:-NR208AVDnC61ZED66W0:btldmsj) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

PR was merge now, please update your PR and verify that it works correctly.
</blockquote></details>

I have updated this PR and verified that it works correctly.

___


<!-- Sent from Reviewable.io -->

2023-03-22 08:47 UTC, dimakuv requested changes
> Reviewed 7 of 8 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/41)* status: all files reviewed, 18 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @sahason)

___
*[`Curated-Apps/workloads/mariadb/insecure_args.txt` line 1 at r2](https://reviewable.io/reviews/gramineproject/contrib/41#-NR7Uv2T8ciprVZjhq24:-NR7Uv2T8ciprVZjhq25:b-2mmlz3) ([raw file](https://github.com/gramineproject/contrib/blob/c5f129db0c30bb75da1ca6cf2988c3936057ad55/Curated-Apps/workloads/mariadb/insecure_args.txt#L1)):*
> ```help
> --datadir /var/run/test_db_encrypted
> ```

I just noticed it now, but why is this file called `insecure_args.txt`? Why **insecure**? Probably this is a question to @jkr0103 
___
*[`Curated-Apps/workloads/mariadb/mariadb.manifest.template` line 18 at r2](https://reviewable.io/reviews/gramineproject/contrib/41#-NR7SX-kB0FRSusRaQTJ:-NR7SX-lBnIt98nhJgKr:b-rasy4i) ([raw file](https://github.com/gramineproject/contrib/blob/c5f129db0c30bb75da1ca6cf2988c3936057ad55/Curated-Apps/workloads/mariadb/mariadb.manifest.template#L18)):*
> ```
> 
> fs.mounts = [
>   { type = "encrypted", path = "/run/mysqld", uri = "file:/run/mysqld" },
> ```

I always get confused between MariaDB and MySQL... Why do we have `/run/mysqld` here as an encrypted directory? Is that the path name that MariaDB uses by default?
___
*[`Curated-Apps/workloads/mariadb/README.md` line 1 at r2](https://reviewable.io/reviews/gramineproject/contrib/41#-NR7T4YCB1P517ImWte6:-NR7T4YCB1P517ImWte7:bp8dnky) ([raw file](https://github.com/gramineproject/contrib/blob/c5f129db0c30bb75da1ca6cf2988c3936057ad55/Curated-Apps/workloads/mariadb/README.md#L1)):*
> ```Markdown
> # Gramine Curated MariaDB
> ```

Please add an empty line after this one (to visually separate the title from the body)
___
*[`Curated-Apps/workloads/mariadb/README.md` line 7 at r2](https://reviewable.io/reviews/gramineproject/contrib/41#-NR7T9po2BBRe-qlgndd:-NR7T9po2BBRe-qlgnde:b-7ropln) ([raw file](https://github.com/gramineproject/contrib/blob/c5f129db0c30bb75da1ca6cf2988c3936057ad55/Curated-Apps/workloads/mariadb/README.md#L7)):*
> ```Markdown
> both the phases are assumed to be met.
> 
> ## Build a confidential compute image for MariaDB
> ```

ditto
___
*[`Curated-Apps/workloads/mariadb/README.md` line 27 at r2](https://reviewable.io/reviews/gramineproject/contrib/41#-NR7TBvAEYTAUIOLbnQz:-NR7TBvAEYTAUIOLbnR-:b-3pdnan) ([raw file](https://github.com/gramineproject/contrib/blob/c5f129db0c30bb75da1ca6cf2988c3936057ad55/Curated-Apps/workloads/mariadb/README.md#L27)):*
> ```Markdown
>    # Stop MariaDB server container using below command when database is initialized
>    docker stop init_test_db
>    # To allow running MariaDB server under the current non-root user.
> ```

Please remove the dot (`.`) at the end
___
*[`Curated-Apps/workloads/mariadb/README.md` line 31 at r2](https://reviewable.io/reviews/gramineproject/contrib/41#-NR7TFXp5N4WkPeiIt2i:-NR7TFXp5N4WkPeiIt2j:bxeq3hl) ([raw file](https://github.com/gramineproject/contrib/blob/c5f129db0c30bb75da1ca6cf2988c3936057ad55/Curated-Apps/workloads/mariadb/README.md#L31)):*
> ```Markdown
>    ```
> 
> 3. Encrypt MariaDB database
> ```

Please add `:` at the end
___
*[`Curated-Apps/workloads/mariadb/README.md` line 33 at r2](https://reviewable.io/reviews/gramineproject/contrib/41#-NR7TIif4EFGGnz2-JpJ:-NR7TIif4EFGGnz2-JpK:b-dl3p79) ([raw file](https://github.com/gramineproject/contrib/blob/c5f129db0c30bb75da1ca6cf2988c3936057ad55/Curated-Apps/workloads/mariadb/README.md#L33)):*
> ```Markdown
> 3. Encrypt MariaDB database
> 
>    1. Install prerequisites for encrypting MariaDB database
> ```

This is confusing. What are the prerequisites? Is it only Gramine? Then this first sentence is confusing: it reads like there are many dependencies, but there is only one (Gramine).

Maybe reprase to
```
1. Install the only prerequisite required for encrypting MariaDB database: [Gramine] 
   (https://gramine.readthedocs.io/en/latest/quickstart.html#install-gramine). Encryption
   is done using `gramine-sgx-pf-crypt` tool which is part of Gramine installation.
```

Something like this (also, please rewrap to 100 chars per line)
___
*[`Curated-Apps/workloads/mariadb/README.md` line 53 at r2](https://reviewable.io/reviews/gramineproject/contrib/41#-NR7TsIJBbIfTQxwKhdt:-NR7TsIJBbIfTQxwKhdu:b-mpd91x) ([raw file](https://github.com/gramineproject/contrib/blob/c5f129db0c30bb75da1ca6cf2988c3936057ad55/Curated-Apps/workloads/mariadb/README.md#L53)):*
> ```Markdown
>       support in Gramine.
> 
> 4. Generate the test confidential compute image with encrypted database.
> ```

Please use `:` instead of `.`
___
*[`Curated-Apps/workloads/mariadb/README.md` line 59 at r2](https://reviewable.io/reviews/gramineproject/contrib/41#-NR7Tu5c1qgHaQlgYwLB:-NR7Tu5c1qgHaQlgYwLC:b-mpd91x) ([raw file](https://github.com/gramineproject/contrib/blob/c5f129db0c30bb75da1ca6cf2988c3936057ad55/Curated-Apps/workloads/mariadb/README.md#L59)):*
> ```Markdown
> 
> 5. Or, to generate a custom confidential compute image based on a user-provided MariaDB image,
>    execute the following to launch an interactive setup script.
> ```

Please use `:` instead of `.`
___
*[`Curated-Apps/workloads/mariadb/README.md` line 65 at r2](https://reviewable.io/reviews/gramineproject/contrib/41#-NR7TyNa839r8s8TDNHX:-NR7TyNa839r8s8TDNHY:bnxs3sr) ([raw file](https://github.com/gramineproject/contrib/blob/c5f129db0c30bb75da1ca6cf2988c3936057ad55/Curated-Apps/workloads/mariadb/README.md#L65)):*
> ```Markdown
> 
>    Please provide below inputs on UI:
>    - --datadir <database_abs_path> when prompted for command-line arguments
> ```

Can you put all these in backticks? Otherwise hard to read: https://github.com/sahason/contrib/tree/sahason/mariadb/Curated-Apps/workloads/mariadb
___
*[`Curated-Apps/workloads/mariadb/README.md` line 66 at r2](https://reviewable.io/reviews/gramineproject/contrib/41#-NR7U4P2-ciXDtdSQDWo:-NR7U4P2-ciXDtdSQDWp:bmkpn7r) ([raw file](https://github.com/gramineproject/contrib/blob/c5f129db0c30bb75da1ca6cf2988c3936057ad55/Curated-Apps/workloads/mariadb/README.md#L66)):*
> ```Markdown
>    Please provide below inputs on UI:
>    - --datadir <database_abs_path> when prompted for command-line arguments
>    - -v <abs_path_to_encrypted_database>:<abs_path_to_encrypted_database> when prompted for additional docker flags
> ```

Please rewrap too 100 chars per line
___
*[`Curated-Apps/workloads/mariadb/README.md` line 67 at r2](https://reviewable.io/reviews/gramineproject/contrib/41#-NR7U5r5AtVPGpO6VTR9:-NR7U5r5AtVPGpO6VTRA:bmkpn7r) ([raw file](https://github.com/gramineproject/contrib/blob/c5f129db0c30bb75da1ca6cf2988c3936057ad55/Curated-Apps/workloads/mariadb/README.md#L67)):*
> ```Markdown
>    - --datadir <database_abs_path> when prompted for command-line arguments
>    - -v <abs_path_to_encrypted_database>:<abs_path_to_encrypted_database> when prompted for additional docker flags
>    - <abs_path_to_encrypted_database> and <encryption_key> when prompted for encrypted files and encryption key respectively
> ```

Please rewrap too 100 chars per line
___
*[`Curated-Apps/workloads/mariadb/README.md` line 76 at r2](https://reviewable.io/reviews/gramineproject/contrib/41#-NR7U9Op6__A8ifSPZZx:-NR7U9Op6__A8ifSPZZy:bmzhfse) ([raw file](https://github.com/gramineproject/contrib/blob/c5f129db0c30bb75da1ca6cf2988c3936057ad55/Curated-Apps/workloads/mariadb/README.md#L76)):*
> ```Markdown
> ## Connect MySQL client
> 
>    Install MySQL client using command:
> ```

There is no need for this indentation level. Please remove the spaces. Here and below.
___
*[`Curated-Apps/workloads/mariadb/README.md` line 76 at r2](https://reviewable.io/reviews/gramineproject/contrib/41#-NR7UI668BVKZTT4iv59:-NR7UI668BVKZTT4iv5A:bv1qlqr) ([raw file](https://github.com/graminepr [...]

2023-03-22 11:01 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/41)* status: all files reviewed, 18 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @sahason)

___
*[`Curated-Apps/workloads/mariadb/insecure_args.txt` line 1 at r2](https://reviewable.io/reviews/gramineproject/contrib/41#-NR7Uv2T8ciprVZjhq24:-NR7x42P-eLg_wwSGLCi:b-1a28ki) ([raw file](https://github.com/gramineproject/contrib/blob/c5f129db0c30bb75da1ca6cf2988c3936057ad55/Curated-Apps/workloads/mariadb/insecure_args.txt#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I just noticed it now, but why is this file called `insecure_args.txt`? Why **insecure**? Probably this is a question to @jkr0103 
</blockquote></details>

Test mode in curations need all the required parameters upfront/hardcoded somewhere, there is not user intervention required. Parameters from `insecure_args.txt` are direclty added to `docker run` command formed at the end of curation and any command line argument used is insecure in Gramine, hence named the filename based on that. Arguments from this file are not used in production case. Parameters in most of the `.txt` files are used in test mode only.


<!-- Sent from Reviewable.io -->

2023-03-23 04:10 UTC, sahason reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/41)* status: all files reviewed, 18 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

___
*[`Curated-Apps/workloads/mariadb/mariadb.manifest.template` line 18 at r2](https://reviewable.io/reviews/gramineproject/contrib/41#-NR7SX-kB0FRSusRaQTJ:-NRBTZuA9k5Lo4aFT0P8:b77qxru) ([raw file](https://github.com/gramineproject/contrib/blob/c5f129db0c30bb75da1ca6cf2988c3936057ad55/Curated-Apps/workloads/mariadb/mariadb.manifest.template#L18)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I always get confused between MariaDB and MySQL... Why do we have `/run/mysqld` here as an encrypted directory? Is that the path name that MariaDB uses by default?
</blockquote></details>

Yes, path is mentioned in the default configuration file 50-server.cnf as pid-file  = /run/mysqld/mysqld.pid. If not marked as encrypted have to keep as allowed files which makes it insecure and not recommended.
___
*[`Curated-Apps/workloads/mariadb/README.md` line 1 at r2](https://reviewable.io/reviews/gramineproject/contrib/41#-NR7T4YCB1P517ImWte6:-NRBVkEiA1knL6dvs09a:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/c5f129db0c30bb75da1ca6cf2988c3936057ad55/Curated-Apps/workloads/mariadb/README.md#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add an empty line after this one (to visually separate the title from the body)
</blockquote></details>

Done.
___
*[`Curated-Apps/workloads/mariadb/README.md` line 7 at r2](https://reviewable.io/reviews/gramineproject/contrib/41#-NR7T9po2BBRe-qlgndd:-NRBVtLU417GT-om0PWN:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/c5f129db0c30bb75da1ca6cf2988c3936057ad55/Curated-Apps/workloads/mariadb/README.md#L7)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`Curated-Apps/workloads/mariadb/README.md` line 27 at r2](https://reviewable.io/reviews/gramineproject/contrib/41#-NR7TBvAEYTAUIOLbnQz:-NRBW-lz2_pLUtLVX6gJ:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/c5f129db0c30bb75da1ca6cf2988c3936057ad55/Curated-Apps/workloads/mariadb/README.md#L27)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove the dot (`.`) at the end
</blockquote></details>

Done.
___
*[`Curated-Apps/workloads/mariadb/README.md` line 31 at r2](https://reviewable.io/reviews/gramineproject/contrib/41#-NR7TFXp5N4WkPeiIt2i:-NRBW2IrDHyY-P3LmC_j:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/c5f129db0c30bb75da1ca6cf2988c3936057ad55/Curated-Apps/workloads/mariadb/README.md#L31)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add `:` at the end
</blockquote></details>

Done.
___
*[`Curated-Apps/workloads/mariadb/README.md` line 33 at r2](https://reviewable.io/reviews/gramineproject/contrib/41#-NR7TIif4EFGGnz2-JpJ:-NRBWUd-1dXx3EOIal6R:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/c5f129db0c30bb75da1ca6cf2988c3936057ad55/Curated-Apps/workloads/mariadb/README.md#L33)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is confusing. What are the prerequisites? Is it only Gramine? Then this first sentence is confusing: it reads like there are many dependencies, but there is only one (Gramine).

Maybe reprase to
```
1. Install the only prerequisite required for encrypting MariaDB database: [Gramine] 
   (https://gramine.readthedocs.io/en/latest/quickstart.html#install-gramine). Encryption
   is done using `gramine-sgx-pf-crypt` tool which is part of Gramine installation.
```

Something like this (also, please rewrap to 100 chars per line)
</blockquote></details>

Done.
___
*[`Curated-Apps/workloads/mariadb/README.md` line 53 at r2](https://reviewable.io/reviews/gramineproject/contrib/41#-NR7TsIJBbIfTQxwKhdt:-NRBWYLODnsKSinMed5x:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/c5f129db0c30bb75da1ca6cf2988c3936057ad55/Curated-Apps/workloads/mariadb/README.md#L53)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please use `:` instead of `.`
</blockquote></details>

Done.
___
*[`Curated-Apps/workloads/mariadb/README.md` line 59 at r2](https://reviewable.io/reviews/gramineproject/contrib/41#-NR7Tu5c1qgHaQlgYwLB:-NRBWZfl6blcwaxyMC-1:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/c5f129db0c30bb75da1ca6cf2988c3936057ad55/Curated-Apps/workloads/mariadb/README.md#L59)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please use `:` instead of `.`
</blockquote></details>

Done.
___
*[`Curated-Apps/workloads/mariadb/README.md` line 65 at r2](https://reviewable.io/reviews/gramineproject/contrib/41#-NR7TyNa839r8s8TDNHX:-NRBXPwQBWnv8Bc4w8_2:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/c5f129db0c30bb75da1ca6cf2988c3936057ad55/Curated-Apps/workloads/mariadb/README.md#L65)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can you put all these in backticks? Otherwise hard to read: https://github.com/sahason/contrib/tree/sahason/mariadb/Curated-Apps/workloads/mariadb
</blockquote></details>

Done.
___
*[`Curated-Apps/workloads/mariadb/README.md` line 66 at r2](https://reviewable.io/reviews/gramineproject/contrib/41#-NR7U4P2-ciXDtdSQDWo:-NRBXPST6Esk0UI7xvYe:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/c5f129db0c30bb75da1ca6cf2988c3936057ad55/Curated-Apps/workloads/mariadb/README.md#L66)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please rewrap too 100 chars per line
</blockquote></details>

Done.
___
*[`Curated-Apps/workloads/mariadb/README.md` line 67 at r2](https://reviewable.io/reviews/gramineproject/contrib/41#-NR7U5r5AtVPGpO6VTR9:-NRBXR7_3gD6Jx9-nGLL:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/c5f129db0c30bb75da1ca6cf2988c3936057ad55/Curated-Apps/workloads/mariadb/README.md#L67)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please rewrap too 100 chars per line
</blockquote></details>

Done.
___
*[`Curated-Apps/workloads/mariadb/README.md` line 76 at r2](https://reviewable.io/reviews/gramineproject/contrib/41#-NR7U9Op6__A8ifSPZZx:-NRBY0saBxan1iNge8oV:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/c5f129db0c30bb75da1ca6cf2988c3936057ad55/Curated-Apps/workloads/mariadb/README.md#L76)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

There is no need for this indentation level. Please remove the spaces. Here and below.
</blockquote></details>

Done.
___
*[`Curated-Apps/workloads/mariadb/README.md` line 76 at r2](https://reviewable.io/reviews/gramineproject/contrib/41#-NR7UI668BVKZTT4iv59:-NRB_k0JBBXY3eccqmZ0:bb6un1j) ([raw file](https://github.com/gramineproject/contrib/blob/c5f129db0c30bb75da1ca6cf2988c3936057ad55/Curated-Apps/workloads/mariadb/README.md#L76)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Again, there is this confusion about MariaDB and MySQL. Apparently, MariaDB is fully compatible with MySQL clients? Could you please add a sentence on this here?
</blockquote></details>

Done
___
*[`Curated-Apps/workloads/mariadb/README.md` line 81 at r2](https://reviewable.io/reviews/gramineproject/contrib/41#-NR7USHV3QDUsBiHk4OK:-NRBYReeCZnjgs6sNZvN:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/c5f129db0c30bb75da1ca6cf2988c3936057ad55/Curated-Apps/ [...]

2023-03-23 07:45 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/41)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

___
*[`Curated-Apps/workloads/mariadb/insecure_args.txt` line 1 at r2](https://reviewable.io/reviews/gramineproject/contrib/41#-NR7Uv2T8ciprVZjhq24:-NRCPzV96MJnxKqSJY4F:b-wsvasg) ([raw file](https://github.com/gramineproject/contrib/blob/c5f129db0c30bb75da1ca6cf2988c3936057ad55/Curated-Apps/workloads/mariadb/insecure_args.txt#L1)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

Arguments in this file are used in test mode only where all the required parameters are hard coded. These parameters are added directly to `docker run` command formed at the end of curation and any command line argument used is insecure, hence named the filename based on that. Arguments from this file are not used on UI or in production case. Parameters in `.txt` are used in test mode only.
</blockquote></details>

Thanks for the explanation!
___
*[`Curated-Apps/workloads/mariadb/mariadb.manifest.template` line 18 at r2](https://reviewable.io/reviews/gramineproject/contrib/41#-NR7SX-kB0FRSusRaQTJ:-NRCQ3xm-YjgFMOmTJiO:b-a81j6n) ([raw file](https://github.com/gramineproject/contrib/blob/c5f129db0c30bb75da1ca6cf2988c3936057ad55/Curated-Apps/workloads/mariadb/mariadb.manifest.template#L18)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

Yes, path is mentioned in the default configuration file 50-server.cnf as pid-file  = /run/mysqld/mysqld.pid. If not marked as encrypted have to keep as allowed files which makes it insecure and not recommended.
</blockquote></details>

Thanks for the explanation


<!-- Sent from Reviewable.io -->

2023-03-28 17:11 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/41)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @sahason)

___
*[`Curated-Apps/workloads/mariadb/mariadb-gsc.dockerfile.template` line 11 at r3](https://reviewable.io/reviews/gramineproject/contrib/41#-NRdBp1OD1waST2iidqH:-NRdBp1OD1waST2iidqI:bawsadd) ([raw file](https://github.com/gramineproject/contrib/blob/afc188d45dc9097212779a23a9c069a2ecca3f91/Curated-Apps/workloads/mariadb/mariadb-gsc.dockerfile.template#L11)):*
> ```
> FROM <base_image_name>
> 
> # COPY ca.crt /ca.crt
> ```

This should be changed, according to the latest commit in the master
___
*[`Curated-Apps/workloads/mariadb/mariadb.manifest.template` line 13 at r3](https://reviewable.io/reviews/gramineproject/contrib/41#-NRdBwOR1jRewLvR537L:-NRdBwOR1jRewLvR537M:blbdheu) ([raw file](https://github.com/gramineproject/contrib/blob/afc188d45dc9097212779a23a9c069a2ecca3f91/Curated-Apps/workloads/mariadb/mariadb.manifest.template#L13)):*
> ```
> # This is required to run workload as non-root user, any number works except `0` which is for root.
> loader.uid=999
> loader.gid=999
> ```

Please add spaces around `=` (in both these lines)


<!-- Sent from Reviewable.io -->

2023-03-29 02:08 UTC, sahason reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/41)* status: 6 of 8 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`Curated-Apps/workloads/mariadb/mariadb-gsc.dockerfile.template` line 11 at r3](https://reviewable.io/reviews/gramineproject/contrib/41#-NRdBp1OD1waST2iidqH:-NRf6txC3dViyEC04ECx:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/afc188d45dc9097212779a23a9c069a2ecca3f91/Curated-Apps/workloads/mariadb/mariadb-gsc.dockerfile.template#L11)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This should be changed, according to the latest commit in the master
</blockquote></details>

Done.
___
*[`Curated-Apps/workloads/mariadb/mariadb.manifest.template` line 13 at r3](https://reviewable.io/reviews/gramineproject/contrib/41#-NRdBwOR1jRewLvR537L:-NRf6v7i-M01i_4UB46I:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/afc188d45dc9097212779a23a9c069a2ecca3f91/Curated-Apps/workloads/mariadb/mariadb.manifest.template#L13)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add spaces around `=` (in both these lines)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-29 08:28 UTC, dimakuv submitted a review, later dismissed
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/41)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-03-29 09:00 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/41)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @sahason)

___
*[`Curated-Apps/workloads/mariadb/README.md` line 81 at r2](https://reviewable.io/reviews/gramineproject/contrib/41#-NR7USHV3QDUsBiHk4OK:-NRg_e6-6_SAm7MN93Fb:bo9ok08) ([raw file](https://github.com/gramineproject/contrib/blob/c5f129db0c30bb75da1ca6cf2988c3936057ad55/Curated-Apps/workloads/mariadb/README.md#L81)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Exact command won't work for the MariaDB server created in step 5 if user have set the root password, disabled remote login for root user etc.. So this command should only be applicable for step 4.
___
*[`Curated-Apps/workloads/mariadb/README.md` line 65 at r4](https://reviewable.io/reviews/gramineproject/contrib/41#-NRg_OxxE7pb5th1bJio:-NRg_OxxE7pb5th1bJip:b1udk0k) ([raw file](https://github.com/gramineproject/contrib/blob/f275fea88cdff39ce281808b5a2c5febca9c8092/Curated-Apps/workloads/mariadb/README.md#L65)):*
> on UI

via UI


<!-- Sent from Reviewable.io -->

2023-03-30 05:00 UTC, sahason reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/41)* status: 7 of 8 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @jkr0103)

___
*[`Curated-Apps/workloads/mariadb/README.md` line 81 at r2](https://reviewable.io/reviews/gramineproject/contrib/41#-NR7USHV3QDUsBiHk4OK:-NRksOJL-BX3IGMXo0ig:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/c5f129db0c30bb75da1ca6cf2988c3936057ad55/Curated-Apps/workloads/mariadb/README.md#L81)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

Exact command won't work for the MariaDB server created in step 5 if user have set the root password, disabled remote login for root user etc.. So this command should only be applicable for step 4.
</blockquote></details>

Done.
___
*[`Curated-Apps/workloads/mariadb/README.md` line 65 at r4](https://reviewable.io/reviews/gramineproject/contrib/41#-NRg_OxxE7pb5th1bJio:-NRksMGx8rDfHl0DFby9:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/f275fea88cdff39ce281808b5a2c5febca9c8092/Curated-Apps/workloads/mariadb/README.md#L65)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

> on UI

via UI
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-30 05:04 UTC, jkr0103 reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/41#-:-NRktnwc0x0hhvVEP7IU:bnfp4nl)* status: 7 of 8 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2023-04-03 12:45 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/41)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-07-18 11:02 UTC, dimakuv requested changes
> Reviewed 10 of 10 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/41)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @sahason)

___
*[`Intel-Confidential-Compute-for-X/workloads/mariadb/README.md` line 37 at r6](https://reviewable.io/reviews/gramineproject/contrib/41#-N_ce6Ri7bWsHrmkT8mh:-N_ce6Ri7bWsHrmkT8mi:b-tof2u) ([raw file](https://github.com/gramineproject/contrib/blob/4fc6c5b12787c8a132a87c737424fa2fbdc5be0a/Intel-Confidential-Compute-for-X/workloads/mariadb/README.md#L37)):*
> ```Markdown
> 4. Encrypt MariaDB database:
> 
>    1. [Install Gramine](https://gramine.readthedocs.io/en/stable/quickstart.html#install-gramine)
> ```

This link is dead now. Please use https://gramine.readthedocs.io/en/stable/installation.html
___
*[`Intel-Confidential-Compute-for-X/workloads/mariadb/README.md` line 86 at r6](https://reviewable.io/reviews/gramineproject/contrib/41#-N_ceSs48lQlLYS7GZX2:-N_ceSs48lQlLYS7GZX3:b-p8dd1o) ([raw file](https://github.com/gramineproject/contrib/blob/4fc6c5b12787c8a132a87c737424fa2fbdc5be0a/Intel-Confidential-Compute-for-X/workloads/mariadb/README.md#L86)):*
> ```Markdown
> ```
> 
> Connect the client to the test MariaDB server:
> ```

`to the test` -> `to test the`


<!-- Sent from Reviewable.io -->

2023-07-18 12:06 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/41)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-07-21 23:59 UTC, mkow requested changes
> Reviewed 9 of 10 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/41)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @sahason)

___
*[`Intel-Confidential-Compute-for-X/workloads/mariadb/README.md` line 29 at r7](https://reviewable.io/reviews/gramineproject/contrib/41#-N_usEZQBE-roMDHCMBB:-N_usEZRAWdcrOnGMIPP:b-bawje7) ([raw file](https://github.com/gramineproject/contrib/blob/e4882a67e7851c37af0fe672aa7f189b1046626f/Intel-Confidential-Compute-for-X/workloads/mariadb/README.md#L29)):*
> ```Markdown
>    docker run --rm --net=host --name init_test_db \
>        -v $PWD/workloads/mariadb/test_db:/test_db \
>        -e MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=true -e MARIADB_DATABASE=test_db mariadb:10.7 \
> ```

This sets up a database fully accessible to the untrusted host. First, this is a very bad idea, second, I can't find any warning about this in the text.



_Code quote:_
```Markdown
-e MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=true
```
___
*[`Intel-Confidential-Compute-for-X/workloads/mariadb/README.md` line 42 at r7](https://reviewable.io/reviews/gramineproject/contrib/41#-N_urcJu2pQzXGRWsfJd:-N_urcJu2pQzXGRWsfJe:bjl1o70) ([raw file](https://github.com/gramineproject/contrib/blob/e4882a67e7851c37af0fe672aa7f189b1046626f/Intel-Confidential-Compute-for-X/workloads/mariadb/README.md#L42)):*
> ```Markdown
> 
>    2. Use the `gramine-sgx-pf-crypt` tool to encrypt the MariaDB database `workloads/mariadb/test_db`.
>       The following command with generate a weak encryption key, which must not be used in
> ```

Something is wrong with English here, a typo maybe?
Anyways, why would `/dev/urandom` output be weak? It generates cryptographically-suitable bytes.



_Code quote:_
```Markdown
The following command with generate a weak encryption key
```


<!-- Sent from Reviewable.io -->

2023-07-24 13:06 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/41)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @sahason)

___
*[`Intel-Confidential-Compute-for-X/workloads/mariadb/README.md` line 29 at r7](https://reviewable.io/reviews/gramineproject/contrib/41#-N_usEZQBE-roMDHCMBB:-Na6zYUaDT-XEijYExIU:b-p771pz) ([raw file](https://github.com/gramineproject/contrib/blob/e4882a67e7851c37af0fe672aa7f189b1046626f/Intel-Confidential-Compute-for-X/workloads/mariadb/README.md#L29)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This sets up a database fully accessible to the untrusted host. First, this is a very bad idea, second, I can't find any warning about this in the text.
</blockquote></details>

+1 to Michal. Why do you need this variable?

According to https://mariadb.com/kb/en/mariadb-server-docker-official-image-environment-variables/, you should use `MARIADB_ROOT_PASSWORD` or even better `MARIADB_RANDOM_ROOT_PASSWORD` and ask the user to memorize the password and type it whenever this password is requested.
___
*[`Intel-Confidential-Compute-for-X/workloads/mariadb/README.md` line 42 at r7](https://reviewable.io/reviews/gramineproject/contrib/41#-N_urcJu2pQzXGRWsfJd:-Na6zVF55kw7T-wpWAm9:bh0allw) ([raw file](https://github.com/gramineproject/contrib/blob/e4882a67e7851c37af0fe672aa7f189b1046626f/Intel-Confidential-Compute-for-X/workloads/mariadb/README.md#L42)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Something is wrong with English here, a typo maybe?
Anyways, why would `/dev/urandom` output be weak? It generates cryptographically-suitable bytes.
</blockquote></details>

+1, I suggest to just remove this sentence.
___
*[`Intel-Confidential-Compute-for-X/workloads/mariadb/mariadb.manifest.template` line 7 at r7](https://reviewable.io/reviews/gramineproject/contrib/41#-Na7-KQxASddO9_ojLcy:-Na7-KQxASddO9_ojLcz:b-9lwbte) ([raw file](https://github.com/gramineproject/contrib/blob/e4882a67e7851c37af0fe672aa7f189b1046626f/Intel-Confidential-Compute-for-X/workloads/mariadb/mariadb.manifest.template#L7)):*
> ```
> # is used by `curation_script.sh` to create the user manifest file that will be passed to GSC.
> 
> sgx.nonpie_binary = true
> ```

What Gramine version do you target? If it's v1.4 or v1.5, you should remove this line -- it got completely deprecated and useless starting from even v1.3 I think.


<!-- Sent from Reviewable.io -->

2023-07-25 06:49 UTC, sahason reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/41)* status: 8 of 10 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`Intel-Confidential-Compute-for-X/workloads/mariadb/README.md` line 29 at r7](https://reviewable.io/reviews/gramineproject/contrib/41#-N_usEZQBE-roMDHCMBB:-NaAldGJ0HFaBYcAzx55:b59yjsd) ([raw file](https://github.com/gramineproject/contrib/blob/e4882a67e7851c37af0fe672aa7f189b1046626f/Intel-Confidential-Compute-for-X/workloads/mariadb/README.md#L29)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1 to Michal. Why do you need this variable?

According to https://mariadb.com/kb/en/mariadb-server-docker-official-image-environment-variables/, you should use `MARIADB_ROOT_PASSWORD` or even better `MARIADB_RANDOM_ROOT_PASSWORD` and ask the user to memorize the password and type it whenever this password is requested.
</blockquote></details>

I have updated the change. I was aligning with MySQL where MYSQL_ALLOW_EMPTY_PASSWORD makes sense.
___
*[`Intel-Confidential-Compute-for-X/workloads/mariadb/README.md` line 42 at r7](https://reviewable.io/reviews/gramineproject/contrib/41#-N_urcJu2pQzXGRWsfJd:-NaAW-g-Eg0TBw-KRXOm:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/e4882a67e7851c37af0fe672aa7f189b1046626f/Intel-Confidential-Compute-for-X/workloads/mariadb/README.md#L42)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1, I suggest to just remove this sentence.
</blockquote></details>

Done.
___
*[`Intel-Confidential-Compute-for-X/workloads/mariadb/README.md` line 47 at r7](https://reviewable.io/reviews/gramineproject/contrib/41#-Na7DH_89IDK51jQsLDJ:-NaAOCJP-t4MmF6-3d-s:bw1cjnx) ([raw file](https://github.com/gramineproject/contrib/blob/e4882a67e7851c37af0fe672aa7f189b1046626f/Intel-Confidential-Compute-for-X/workloads/mariadb/README.md#L47)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do you have sudo everywhere?
</blockquote></details>

As the owner of the /var/run directory is root so removing files or adding encrypted files to this location requires root privileges. The data directory path needs to be absolute as the path is encrypted. And if we have a data directory path in the home directory the user needs to be created inside the docker image to access the database so we need to make changes to the Dockerfile. Making /tmp directory a data directory fails the MariaDB server to start. So we are left with directory with root access. For MySQL also we are doing the same.
___
*[`Intel-Confidential-Compute-for-X/workloads/mariadb/README.md` line 52 at r7](https://reviewable.io/reviews/gramineproject/contrib/41#-Na7DFoS4YRHeijzhYkv:-NaANwH54XE_O9ZRgbpV:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/e4882a67e7851c37af0fe672aa7f189b1046626f/Intel-Confidential-Compute-for-X/workloads/mariadb/README.md#L52)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Remove trailing whitespace
</blockquote></details>

Done.
___
*[`Intel-Confidential-Compute-for-X/workloads/mariadb/mariadb.manifest.template` line 7 at r7](https://reviewable.io/reviews/gramineproject/contrib/41#-Na7-KQxASddO9_ojLcy:-NaAf51DDesnO_SF-REm:b-sezr51) ([raw file](https://github.com/gramineproject/contrib/blob/e4882a67e7851c37af0fe672aa7f189b1046626f/Intel-Confidential-Compute-for-X/workloads/mariadb/mariadb.manifest.template#L7)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What Gramine version do you target? If it's v1.4 or v1.5, you should remove this line -- it got completely deprecated and useless starting from even v1.3 I think.
</blockquote></details>

v1.5. I have updated.


<!-- Sent from Reviewable.io -->

2023-07-25 08:17 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/41)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @sahason)

___
*[`Intel-Confidential-Compute-for-X/workloads/mariadb/README.md` line 47 at r7](https://reviewable.io/reviews/gramineproject/contrib/41#-Na7DH_89IDK51jQsLDJ:-NaB6VEy7mGpidOrJOQj:brnbzj1) ([raw file](https://github.com/gramineproject/contrib/blob/e4882a67e7851c37af0fe672aa7f189b1046626f/Intel-Confidential-Compute-for-X/workloads/mariadb/README.md#L47)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

As the owner of the /var/run directory is root so removing files or adding encrypted files to this location requires root privileges. The data directory path needs to be absolute as the path is encrypted. And if we have a data directory path in the home directory the user needs to be created inside the docker image to access the database so we need to make changes to the Dockerfile. Making /tmp directory a data directory fails the MariaDB server to start. So we are left with directory with root access. For MySQL also we are doing the same.
</blockquote></details>

Ok, I'll resolve my comment, though this seems sub-optimal.
___
*[`Intel-Confidential-Compute-for-X/workloads/mariadb/README.md` line 29 at r8](https://reviewable.io/reviews/gramineproject/contrib/41#-NaB6hoX1MDjRq90K3CI:-NaB6hoX1MDjRq90K3CJ:b-1cn6x6) ([raw file](https://github.com/gramineproject/contrib/blob/6f445288d1516d5598d79406d28bd1b258861bf4/Intel-Confidential-Compute-for-X/workloads/mariadb/README.md#L29)):*
> ```Markdown
>    docker run --rm --net=host --name init_test_db \
>        -v $PWD/workloads/mariadb/test_db:/test_db \
>        -e MARIADB_ROOT_PASSWORD=my-root-pw -e MARIADB_DATABASE=test_db mariadb:10.7 \
> ```

Please add a sentence at this step that the user is supposed to replace `my-root-pw` with the user's own password.
___
*[`Intel-Confidential-Compute-for-X/workloads/mariadb/README.md` line 41 at r8](https://reviewable.io/reviews/gramineproject/contrib/41#-NaB6-ZOE9o6cRndF49G:-NaB6-ZOE9o6cRndF49H:bw9dxsf) ([raw file](https://github.com/gramineproject/contrib/blob/6f445288d1516d5598d79406d28bd1b258861bf4/Intel-Confidential-Compute-for-X/workloads/mariadb/README.md#L41)):*
> ```Markdown
>       installation.
> 
>    2. Use the `gramine-sgx-pf-crypt` tool to encrypt the MariaDB database `workloads/mariadb/test_db`.
> ```

This sentence exceeds the limit of 100 chars per line. I suggest to remove the word `MariaDB` on this line, to get back into the limit (and it's obvious that we're talking about the MariaDB database, so no harm in removing the word).
___
*[`Intel-Confidential-Compute-for-X/workloads/mariadb/README.md` line 87 at r8](https://reviewable.io/reviews/gramineproject/contrib/41#-NaB6qCj7eG1z4RE1qnC:-NaB6qCj7eG1z4RE1qnD:b82wkln) ([raw file](https://github.com/gramineproject/contrib/blob/6f445288d1516d5598d79406d28bd1b258861bf4/Intel-Confidential-Compute-for-X/workloads/mariadb/README.md#L87)):*
> ```Markdown
> Connect the client to test the MariaDB server:
> ```sh
> mysql -h 127.0.0.1 -uroot -pmy-root-pass
> ```

Please add something like this:
```
mysql -h 127.0.0.1 -uroot -pmy-root-pass  # replace my-root-pass with your password
```


<!-- Sent from Reviewable.io -->

2023-07-25 10:12 UTC, sahason reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/41)* status: 9 of 10 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`Intel-Confidential-Compute-for-X/workloads/mariadb/README.md` line 29 at r8](https://reviewable.io/reviews/gramineproject/contrib/41#-NaB6hoX1MDjRq90K3CI:-NaBXHE7EyOjwJCpFYsB:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/6f445288d1516d5598d79406d28bd1b258861bf4/Intel-Confidential-Compute-for-X/workloads/mariadb/README.md#L29)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add a sentence at this step that the user is supposed to replace `my-root-pw` with the user's own password.
</blockquote></details>

Done.
___
*[`Intel-Confidential-Compute-for-X/workloads/mariadb/README.md` line 41 at r8](https://reviewable.io/reviews/gramineproject/contrib/41#-NaB6-ZOE9o6cRndF49G:-NaBXGQ29sBKCMnKapSY:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/6f445288d1516d5598d79406d28bd1b258861bf4/Intel-Confidential-Compute-for-X/workloads/mariadb/README.md#L41)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This sentence exceeds the limit of 100 chars per line. I suggest to remove the word `MariaDB` on this line, to get back into the limit (and it's obvious that we're talking about the MariaDB database, so no harm in removing the word).
</blockquote></details>

Done.
___
*[`Intel-Confidential-Compute-for-X/workloads/mariadb/README.md` line 87 at r8](https://reviewable.io/reviews/gramineproject/contrib/41#-NaB6qCj7eG1z4RE1qnC:-NaBX7Q11QEJyCeaw3hP:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/6f445288d1516d5598d79406d28bd1b258861bf4/Intel-Confidential-Compute-for-X/workloads/mariadb/README.md#L87)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add something like this:
```
mysql -h 127.0.0.1 -uroot -pmy-root-pass  # replace my-root-pass with your password
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-07-25 11:18 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/41)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2023-07-26 10:48 UTC, mkow requested changes
> Reviewed 1 of 2 files at r8, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/41)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @sahason)

___
*[`Intel-Confidential-Compute-for-X/workloads/mariadb/README.md` line 29 at r7](https://reviewable.io/reviews/gramineproject/contrib/41#-N_usEZQBE-roMDHCMBB:-NaGnXIS8CEEWvlwAXym:bfp8wzp) ([raw file](https://github.com/gramineproject/contrib/blob/e4882a67e7851c37af0fe672aa7f189b1046626f/Intel-Confidential-Compute-for-X/workloads/mariadb/README.md#L29)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

I have updated the change. I was aligning with MySQL where MYSQL_ALLOW_EMPTY_PASSWORD makes sense.
</blockquote></details>

This is a bad practice, you shouldn't use weak default passwords anywhere. Please use `MARIADB_RANDOM_ROOT_PASSWORD` instead, as Dmitrii suggested.
___
*[`Intel-Confidential-Compute-for-X/workloads/mariadb/README.md` line 88 at r10](https://reviewable.io/reviews/gramineproject/contrib/41#-NaGo3mqCRlWh7GCpN9S:-NaGo3mqCRlWh7GCpN9T:b-7ropln) ([raw file](https://github.com/gramineproject/contrib/blob/e3903034ec3da8f55a0c14f6d82bb363ada37fe5/Intel-Confidential-Compute-for-X/workloads/mariadb/README.md#L88)):*
> ```Markdown
> Connect the client to test the MariaDB server:
> ```sh
> mysql -h 127.0.0.1 -uroot -pmy-root-pw # replace my-root-pw with your password
> ```

ditto


<!-- Sent from Reviewable.io -->

2023-07-26 10:52 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/41)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @sahason)

___
*[`Intel-Confidential-Compute-for-X/workloads/mariadb/README.md` line 47 at r7](https://reviewable.io/reviews/gramineproject/contrib/41#-Na7DH_89IDK51jQsLDJ:-NaGoE08C943BI34JXns:b-1fnzy1) ([raw file](https://github.com/gramineproject/contrib/blob/e4882a67e7851c37af0fe672aa7f189b1046626f/Intel-Confidential-Compute-for-X/workloads/mariadb/README.md#L47)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ok, I'll resolve my comment, though this seems sub-optimal.
</blockquote></details>

I don't understand this explanation, no other workload in Gramine has problems with using files from the current directory. Placing the database in a global, root-only dir is a bad practice in this case, e.g. you won't be able to start 2 instances of this workload on a single system (or rather you will be able, but they'll start overwriting each other's state).


<!-- Sent from Reviewable.io -->

2023-07-26 12:13 UTC, sahason reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/41)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @jkr0103)

___
*[`Intel-Confidential-Compute-for-X/workloads/mariadb/README.md` line 47 at r7](https://reviewable.io/reviews/gramineproject/contrib/41#-Na7DH_89IDK51jQsLDJ:-NaH39aF6XIJvj7d2Mhd:b-mc19ed) ([raw file](https://github.com/gramineproject/contrib/blob/e4882a67e7851c37af0fe672aa7f189b1046626f/Intel-Confidential-Compute-for-X/workloads/mariadb/README.md#L47)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I don't understand this explanation, no other workload in Gramine has problems with using files from the current directory. Placing the database in a global, root-only dir is a bad practice in this case, e.g. you won't be able to start 2 instances of this workload on a single system (or rather you will be able, but they'll start overwriting each other's state).
</blockquote></details>

@mkow It's not true that no other workload is doing the same. You can check https://github.com/gramineproject/contrib/tree/master/Intel-Confidential-Compute-for-X/workloads/mysql. We are doing this approach for both MariaDB and MySQL because we are encrypting the database on host and mounting it for that we need absolute path. Adding @jkr0103 for commenting on the experiments he tried for MySQL and arrived to this solution.


<!-- Sent from Reviewable.io -->

2023-07-26 14:14 UTC, sahason reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/41)* status: 9 of 10 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @jkr0103 and @mkow)

___
*[`Intel-Confidential-Compute-for-X/workloads/mariadb/README.md` line 29 at r7](https://reviewable.io/reviews/gramineproject/contrib/41#-N_usEZQBE-roMDHCMBB:-NaHYAUc2Sps9vAIDWDQ:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/e4882a67e7851c37af0fe672aa7f189b1046626f/Intel-Confidential-Compute-for-X/workloads/mariadb/README.md#L29)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This is a bad practice, you shouldn't use weak default passwords anywhere. Please use `MARIADB_RANDOM_ROOT_PASSWORD` instead, as Dmitrii suggested.
</blockquote></details>

Done.
___
*[`Intel-Confidential-Compute-for-X/workloads/mariadb/README.md` line 88 at r10](https://reviewable.io/reviews/gramineproject/contrib/41#-NaGo3mqCRlWh7GCpN9S:-NaHY7Ze9u3GovJDwcfX:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/e3903034ec3da8f55a0c14f6d82bb363ada37fe5/Intel-Confidential-Compute-for-X/workloads/mariadb/README.md#L88)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-07-26 20:14 UTC, mkow requested changes
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/41)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @jkr0103)

___
*[`Intel-Confidential-Compute-for-X/workloads/mariadb/README.md` line 47 at r7](https://reviewable.io/reviews/gramineproject/contrib/41#-Na7DH_89IDK51jQsLDJ:-NaIoh_TECqnz6y1OYaX:b-72yrm6) ([raw file](https://github.com/gramineproject/contrib/blob/e4882a67e7851c37af0fe672aa7f189b1046626f/Intel-Confidential-Compute-for-X/workloads/mariadb/README.md#L47)):*
> @mkow It's not true that no other workload is doing the same.

I meant that no other workload has such problems, I don't know why you did the same for other databases in curated apps, it doesn't seem justified.

> because we are encrypting the database on host and mounting it for that we need absolute path.

I don't see why this would require root permissions...


<!-- Sent from Reviewable.io -->

2023-07-27 07:19 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/41)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @jkr0103)

___
*[`Intel-Confidential-Compute-for-X/workloads/mariadb/README.md` line 47 at r7](https://reviewable.io/reviews/gramineproject/contrib/41#-Na7DH_89IDK51jQsLDJ:-NaLC3Zi6MkXEnoxT56o:bcjfm1q) ([raw file](https://github.com/gramineproject/contrib/blob/e4882a67e7851c37af0fe672aa7f189b1046626f/Intel-Confidential-Compute-for-X/workloads/mariadb/README.md#L47)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> @mkow It's not true that no other workload is doing the same.

I meant that no other workload has such problems, I don't know why you did the same for other databases in curated apps, it doesn't seem justified.

> because we are encrypting the database on host and mounting it for that we need absolute path.

I don't see why this would require root permissions...
</blockquote></details>

@mkow `/var/lib` is the default data directory path for MariaDB and MySQL. What we can do is to not mention `sudo` in our recipes. And let the user figure out the permissions. Sounds good? 


<!-- Sent from Reviewable.io -->

2023-07-27 13:46 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/41)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @sahason)

___
*[`Intel-Confidential-Compute-for-X/workloads/mariadb/README.md` line 47 at r7](https://reviewable.io/reviews/gramineproject/contrib/41#-Na7DH_89IDK51jQsLDJ:-NaM_OemCfZ73jKsmOLH:b78zgss) ([raw file](https://github.com/gramineproject/contrib/blob/e4882a67e7851c37af0fe672aa7f189b1046626f/Intel-Confidential-Compute-for-X/workloads/mariadb/README.md#L47)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

By the way, if you don't want to modify MariaDB's default path of `/var/run/`, then you can use the Gramine manifest trick of rewiring the host path to another path inside Gramine, like this:
```
fs.mounts = [
  { path = "/var/run/", uri = "file:./helper-files/var_run_dir/" },
]
```

And you can create all files on the host inside the normal directory `./helper-files/var_run_dir/`.
</blockquote></details>

Current directory path would have been the good option but container need to have/mounted the same path because encrypted files required to use the same path what was used during encryption. It would have easy if it wasn't encrypted.


<!-- Sent from Reviewable.io -->

2023-07-27 14:03 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/41)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @sahason)

___
*[`Intel-Confidential-Compute-for-X/workloads/mariadb/README.md` line 47 at r7](https://reviewable.io/reviews/gramineproject/contrib/41#-Na7DH_89IDK51jQsLDJ:-NaMdcISA7DUMv-yQyRQ:b-iq5u2o) ([raw file](https://github.com/gramineproject/contrib/blob/e4882a67e7851c37af0fe672aa7f189b1046626f/Intel-Confidential-Compute-for-X/workloads/mariadb/README.md#L47)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

Current directory path would have been the good option but container need to have/mounted the same path because encrypted files required to use the same path what was used during encryption. It would have easy if it wasn't encrypted.
</blockquote></details>

Ouch, good point from @jkr0103. Indeed, our `gramine-sgx-pf-crypt` tool doesn't allow for the encrypted file to have a different name than specified in the `--output` argument. We even have this note:
```
NOTE: Files encrypted using the 'encrypt' mode embed the output path string, exactly
      as specified in '-o PATH'. Therefore, the Gramine manifest must specify this
      exact path in encrypted files list.
```

So yeah, the trick with rewiring the path in the Gramine manifest cannot be applied.

---

So @aneessahib  and @jkr0103, why is it **required** to use the `/var/run/` path for MariaDB? Isn't it possible to specify in the MariaDB's command-line arguments a non-special path (I mean under `--datadir`)?


<!-- Sent from Reviewable.io -->

2023-07-27 15:29 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/41)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @sahason)

___
*[`Intel-Confidential-Compute-for-X/workloads/mariadb/README.md` line 47 at r7](https://reviewable.io/reviews/gramineproject/contrib/41#-Na7DH_89IDK51jQsLDJ:-NaMx2qL0Yk6JJzGIMoN:b3rtur) ([raw file](https://github.com/gramineproject/contrib/blob/e4882a67e7851c37af0fe672aa7f189b1046626f/Intel-Confidential-Compute-for-X/workloads/mariadb/README.md#L47)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ouch, good point from @jkr0103. Indeed, our `gramine-sgx-pf-crypt` tool doesn't allow for the encrypted file to have a different name than specified in the `--output` argument. We even have this note:
```
NOTE: Files encrypted using the 'encrypt' mode embed the output path string, exactly
      as specified in '-o PATH'. Therefore, the Gramine manifest must specify this
      exact path in encrypted files list.
```

So yeah, the trick with rewiring the path in the Gramine manifest cannot be applied.

---

So @aneessahib  and @jkr0103, why is it **required** to use the `/var/run/` path for MariaDB? Isn't it possible to specify in the MariaDB's command-line arguments a non-special path (I mean under `--datadir`)?
</blockquote></details>

Technically yes - we can do any other directory. The advantage of keeping `/var` is that it is tmpfs file system - and this configuration results in much faster data transactions. So any other path is sub-optimal from a perf angle. This could also be why this is the default path for MariaDB and MySQL.


<!-- Sent from Reviewable.io -->

2023-07-28 04:30 UTC, sahason reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/41)* status: 9 of 10 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`Intel-Confidential-Compute-for-X/workloads/mariadb/README.md` line 34 at r12](https://reviewable.io/reviews/gramineproject/contrib/41#-NaMYL_34-BLD7NFczbl:-NaPkgZGDOObvTZxDNYc:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/887a2f7a107024986be59c7711ab723c28224126/Intel-Confidential-Compute-for-X/workloads/mariadb/README.md#L34)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`remember`
</blockquote></details>

Done.
___
*[`Intel-Confidential-Compute-for-X/workloads/mariadb/README.md` line 35 at r12](https://reviewable.io/reviews/gramineproject/contrib/41#-NaMYNr_6RlqlvRnkR5u:-NaPkgsl9lX8bWwu2rrS:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/887a2f7a107024986be59c7711ab723c28224126/Intel-Confidential-Compute-for-X/workloads/mariadb/README.md#L35)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please put it into backticks.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-07-28 06:55 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/41)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`Intel-Confidential-Compute-for-X/workloads/mariadb/README.md` line 47 at r7](https://reviewable.io/reviews/gramineproject/contrib/41#-Na7DH_89IDK51jQsLDJ:-NaQGZqx2sAmNbTmslI1:b-y9cnfo) ([raw file](https://github.com/gramineproject/contrib/blob/e4882a67e7851c37af0fe672aa7f189b1046626f/Intel-Confidential-Compute-for-X/workloads/mariadb/README.md#L47)):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

Technically yes - we can do any other directory. The advantage of keeping `/var` is that it is tmpfs file system - and this configuration results in much faster data transactions. So any other path is sub-optimal from a perf angle. This could also be why this is the default path for MariaDB and MySQL.
</blockquote></details>

Hm, we could also create a tmpfs mount point on the host and create our own directory under this mount point (and explain it in this README).

But I will stop here, I see that this all is cumbersome and I don't care much.


<!-- Sent from Reviewable.io -->

2023-07-29 15:07 UTC, mkow requested changes
> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/41)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @jkr0103, and @sahason)

___
*[`-- commits` line 45 at r13](https://reviewable.io/reviews/gramineproject/contrib/41#-NaX9S8rAMKIcfO451PL):*
@sahason: Please don't force push until the review is finished.
___
*[`Intel-Confidential-Compute-for-X/workloads/mariadb/README.md` line 47 at r7](https://reviewable.io/reviews/gramineproject/contrib/41#-Na7DH_89IDK51jQsLDJ:-NaXALNG9PAwydG8B6yV:bwkubkm) ([raw file](https://github.com/gramineproject/contrib/blob/e4882a67e7851c37af0fe672aa7f189b1046626f/Intel-Confidential-Compute-for-X/workloads/mariadb/README.md#L47)):*
> `/var` is that it is tmpfs file system

Are you sure about that? On which distros? On my Ubuntu it's just a part of the rootfs.

> But I will stop here, I see that this all is cumbersome and I don't care much.

But I _do_ care about not forcing users to use root account when not really needed.


<!-- Sent from Reviewable.io -->

2023-07-31 06:48 UTC, dimakuv submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/41)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`Intel-Confidential-Compute-for-X/workloads/mariadb/README.md` line 47 at r7](https://reviewable.io/reviews/gramineproject/contrib/41#-Na7DH_89IDK51jQsLDJ:-Naegl9YCZZpSHBnxXPV:b-zaryie) ([raw file](https://github.com/gramineproject/contrib/blob/e4882a67e7851c37af0fe672aa7f189b1046626f/Intel-Confidential-Compute-for-X/workloads/mariadb/README.md#L47)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> `/var` is that it is tmpfs file system

Are you sure about that? On which distros? On my Ubuntu it's just a part of the rootfs.

> But I will stop here, I see that this all is cumbersome and I don't care much.

But I _do_ care about not forcing users to use root account when not really needed.
</blockquote></details>

Anees meant `/var/run` -- https://unix.stackexchange.com/questions/175345/difference-between-run-and-var-run

@aneessahib Since Michal is strongly opposed to using `/var/run/`, you can create a tmpfs mount point (add a new step in the README), create a normal user-accessible directory under this mount point, and use `--datadir` in MariaDB's command-line arguments (i.e. this created non-special path).


<!-- Sent from Reviewable.io -->

2023-07-31 11:09 UTC, sahason reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/41)* status: 6 of 10 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`Intel-Confidential-Compute-for-X/workloads/mariadb/README.md` line 47 at r7](https://reviewable.io/reviews/gramineproject/contrib/41#-Na7DH_89IDK51jQsLDJ:-NafSBidC0tE3If0Ots6:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/e4882a67e7851c37af0fe672aa7f189b1046626f/Intel-Confidential-Compute-for-X/workloads/mariadb/README.md#L47)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Anees meant `/var/run` -- https://unix.stackexchange.com/questions/175345/difference-between-run-and-var-run

@aneessahib Since Michal is strongly opposed to using `/var/run/`, you can create a tmpfs mount point (add a new step in the README), create a normal user-accessible directory under this mount point, and use `--datadir` in MariaDB's command-line arguments (i.e. this created non-special path).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-07-31 15:47 UTC, mkow approved these changes
> Reviewed 4 of 4 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/41)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @sahason)



<!-- Sent from Reviewable.io -->

2023-08-01 02:31 UTC, kailun-qin approved these changes
> Reviewed 5 of 10 files at r6, 1 of 2 files at r8, 4 of 4 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/41)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @sahason)



<!-- Sent from Reviewable.io -->

2023-08-01 06:21 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/41)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-08-01 06:28 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/41)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-08-01 06:41 UTC, kailun-qin approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/41)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-08-01 07:52 UTC, merged