Adjust Curated-Apps related files to new name of the project
gramineproject/contrib pull request #43
Opened 2023-04-05 09:28 UTC by BFuhry

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/contrib/43)

2023-04-06 06:56 UTC, dimakuv requested changes
> Reviewed 69 of 69 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/43)* status: all files reviewed, 20 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @BFuhry)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/43#-NSKKEAx37pLliM_bSeM:-NSKKEAx37pLliM_bSeN:b-njokdm) (no related file):*
@jkr0103 @aneessahib Could you review this PR too?

___
*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/43#-NSKLTiv2foYJ3BfRxRS:-NSKLTiv2foYJ3BfRxRT:blcjjbw) (no related file):*
I did a rather light review, by checking raw contents and by browsing through rendered contents here: https://github.com/BFuhry/contrib/tree/currated-apps-rename/Intel-Confidential-Compute-for-X

Looks good to me, bar some comments.

___
___
*[`Intel-Confidential-Compute-for-X/README.md` line 35 at r1](https://reviewable.io/reviews/gramineproject/contrib/43#-NSKKe4h9tNyT0jcXpH6:-NSKKe4h9tNyT0jcXpH7:bx0roxe) ([raw file](https://github.com/gramineproject/contrib/blob/57eac4d10e82a3afc3ef6cec7532036260820809/Intel-Confidential-Compute-for-X/README.md#L35)):*
> ```Markdown
> - Any regular system with a Linux distribution is sufficient.
> - Install the necessary build dependencies and adjust the permissions of `/var/run/docker.sock` for the current user:
>    - Ubuntu 18.04
> ```

Do we need a one-item list? Maybe just mention support for only Ubuntu 18.04 currently above?
___
*[`Intel-Confidential-Compute-for-X/README.md` line 54 at r1](https://reviewable.io/reviews/gramineproject/contrib/43#-NSKKl1nCweaUFTpokhJ:-NSKKl1nCweaUFTpokhK:b-445uml) ([raw file](https://github.com/gramineproject/contrib/blob/57eac4d10e82a3afc3ef6cec7532036260820809/Intel-Confidential-Compute-for-X/README.md#L54)):*
> ```Markdown
> 
> - Install the necessary build dependencies:
>     - Ubuntu 18.04:
> ```

ditto (here but also everywhere else)
___
*[`Intel-Confidential-Compute-for-X/README.md` line 80 at r1](https://reviewable.io/reviews/gramineproject/contrib/43#-NSKIsbE8dTsUk6T4hsP:-NSKIsbF8UNOOL389BuV:b-epugxh) ([raw file](https://github.com/gramineproject/contrib/blob/57eac4d10e82a3afc3ef6cec7532036260820809/Intel-Confidential-Compute-for-X/README.md#L80)):*
> ```Markdown
>     |    Yes   | <app name>        | Name of the application, e.g., redis or pytorch. Name has to  |
>     |          |                   | correspond to the application's folder name in 'workloads/'.  |
>     |    Yes   | <base image name> | Name of the base image to be graminized.                       |
> ```

Misaligned closing `|`
___
*[`Intel-Confidential-Compute-for-X/README.md` line 83 at r1](https://reviewable.io/reviews/gramineproject/contrib/43#-NSKLIwT1-HgHKLwbxXE:-NSKLIwT1-HgHKLwbxXF:b-ilqkgd) ([raw file](https://github.com/gramineproject/contrib/blob/57eac4d10e82a3afc3ef6cec7532036260820809/Intel-Confidential-Compute-for-X/README.md#L83)):*
> ```Markdown
>     | Optional | 'debug'           | To generate an insecure image with debug symbols.             |
>     | Optional | 'test'            | To generate an insecure image with a test enclave signing key.|
>     |----------------------------------------------------------------------------------------------|
> ```

Actually, since you're changing the README file, do you want to change this from a mono-table to a more nicely rendered list, for example?
___
*[`Intel-Confidential-Compute-for-X/workloads/memcached/README.md` line 3 at r1](https://reviewable.io/reviews/gramineproject/contrib/43#-NSKJ1u_2yrN5K7U-4et:-NSKJ1u_2yrN5K7U-4eu:b-2ubfmo) ([raw file](https://github.com/gramineproject/contrib/blob/57eac4d10e82a3afc3ef6cec7532036260820809/Intel-Confidential-Compute-for-X/workloads/memcached/README.md#L3)):*
> ```Markdown
> # Intel® Confidential Compute for Memcached
> 
> In the following two sections, we explain how a Docker image for a Gramine-protected Memcached version
> ```

Please re-wrap this to 100-chars-per-line
___
*[`Intel-Confidential-Compute-for-X/workloads/mysql/README.md` line 37 at r1](https://reviewable.io/reviews/gramineproject/contrib/43#-NSKL-3yAbGBjnWTze_d:-NSKL-3yAbGBjnWTze_e:bxeq3hl) ([raw file](https://github.com/gramineproject/contrib/blob/57eac4d10e82a3afc3ef6cec7532036260820809/Intel-Confidential-Compute-for-X/workloads/mysql/README.md#L37)):*
> ```Markdown
>     ```
> 
> 4. Encrypt MySQL database
> ```

Please add `:` at the end
___
*[`Intel-Confidential-Compute-for-X/workloads/pytorch/README.md` line 9 at r1](https://reviewable.io/reviews/gramineproject/contrib/43#-NSKJFC90jYRRl5tTPdx:-NSKJFC90jYRRl5tTPdy:b-ibqpnv) ([raw file](https://github.com/gramineproject/contrib/blob/57eac4d10e82a3afc3ef6cec7532036260820809/Intel-Confidential-Compute-for-X/workloads/pytorch/README.md#L9)):*
> ```Markdown
> 
> 
> ## Build a Gramine-protected PyTorch image
> ```

Please add an empty line after this section title
___
*[`Intel-Confidential-Compute-for-X/workloads/pytorch/base_image_helper/README.md` line 24 at r1](https://reviewable.io/reviews/gramineproject/contrib/43#-NSKJOs08UxNrlR0FG3C:-NSKJOs08UxNrlR0FG3D:b-9l9zu8) ([raw file](https://github.com/gramineproject/contrib/blob/57eac4d10e82a3afc3ef6cec7532036260820809/Intel-Confidential-Compute-for-X/workloads/pytorch/base_image_helper/README.md#L24)):*
> ```Markdown
> 
> This script clones Gramine's [PyTorch example](https://github.com/gramineproject/examples/blob/master/pytorch/),
> downloads a pre-trainer model; generates a weak encryption key (that must not be used in
> ```

`pre-trainer`? I guess this should be `pre-trained`

Why do we have `,` in one place in this sentence, but `;` in all other places? Looks like we should just use a comma (`,`) everywhere in this sentence.
___
*[`Intel-Confidential-Compute-for-X/workloads/redis/README.md` line 3 at r1](https://reviewable.io/reviews/gramineproject/contrib/43#-NSKJaTl1CMZbQwGZQHx:-NSKJaTl1CMZbQwGZQHy:bslkk8a) ([raw file](https://github.com/gramineproject/contrib/blob/57eac4d10e82a3afc3ef6cec7532036260820809/Intel-Confidential-Compute-for-X/workloads/redis/README.md#L3)):*
> ```Markdown
> # Intel® Confidential Compute for Redis
> 
> In the following two sections, we explain how a Docker image for a Gramine-protected Redis version 
> ```

This file contains a couple places where trailing whitespace is visible. Please remove it.
___
*[`Intel-Confidential-Compute-for-X/workloads/redis/README.md` line 24 at r1](https://reviewable.io/reviews/gramineproject/contrib/43#-NSKJf5v4YhSTlugk_eq:-NSKJf5v4YhSTlugk_er:bkhiok4) ([raw file](https://github.com/gramineproject/contrib/blob/57eac4d10e82a3afc3ef6cec7532036260820809/Intel-Confidential-Compute-for-X/workloads/redis/README.md#L24)):*
> ```Markdown
> 
> 3. Perform one of the following alternatives:
>     - To generate a Gramine-protected, pre-configured, non-production ready, test image for Redis, 
> ```

Trailing whitespace here
___
*[`Intel-Confidential-Compute-for-X/workloads/redis/README.md` line 29 at r1](https://reviewable.io/reviews/gramineproject/contrib/43#-NSKJhHl6B1ZB71l25Xr:-NSKJhHl6B1ZB71l25Xs:bkhiok4) ([raw file](https://github.com/gramineproject/contrib/blob/57eac4d10e82a3afc3ef6cec7532036260820809/Intel-Confidential-Compute-for-X/workloads/redis/README.md#L29)):*
> ```Markdown
>         python3 ./curate.py redis redis:7.0.0 test
>         ```
>    - To generate a Gramine-protected, pre-configured Redis image based on a user-provided Redis 
> ```

Trailing whitespace here
___
*[`Intel-Confidential-Compute-for-X/workloads/redis/README.md` line 45 at r1](https://reviewable.io/reviews/gramineproject/contrib/43#-NSKJiV89GwRgfUd8yd6:-NSKJiV89GwRgfUd8yd7:bkhiok4) ([raw file](https://github.com/gramineproject/contrib/blob/57eac4d10e82a3afc3ef6cec7532036260820809/Intel-Confidential-Compute-for-X/workloads/redis/README.md#L45)):*
> ```Markdown
> ## Contents
> 
> This directory contains the following artifac [...]

2023-04-06 19:42 UTC, BFuhry reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/43)* status: 57 of 69 files reviewed, 20 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

___
*[`Intel-Confidential-Compute-for-X/README.md` line 35 at r1](https://reviewable.io/reviews/gramineproject/contrib/43#-NSKKe4h9tNyT0jcXpH6:-NSMxjVK0ORCQtdjQehs:b-ozhtqo) ([raw file](https://github.com/gramineproject/contrib/blob/57eac4d10e82a3afc3ef6cec7532036260820809/Intel-Confidential-Compute-for-X/README.md#L35)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Do we need a one-item list? Maybe just mention support for only Ubuntu 18.04 currently above?
</blockquote></details>

I like to have this very explicit. Once anybody validates the commands for other versions, it will be very easy to add a version (if the same commands work) or to add a new block (if other commands are necessary).
___
*[`Intel-Confidential-Compute-for-X/README.md` line 54 at r1](https://reviewable.io/reviews/gramineproject/contrib/43#-NSKKl1nCweaUFTpokhJ:-NSMyF4X5uVS6WXHDJY7:b1bztb8) ([raw file](https://github.com/gramineproject/contrib/blob/57eac4d10e82a3afc3ef6cec7532036260820809/Intel-Confidential-Compute-for-X/README.md#L54)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto (here but also everywhere else)
</blockquote></details>

same response (here but also everywhere else)
___
*[`Intel-Confidential-Compute-for-X/README.md` line 80 at r1](https://reviewable.io/reviews/gramineproject/contrib/43#-NSKIsbE8dTsUk6T4hsP:-NSMySfKDlPonTlnUDH1:b-349zs1) ([raw file](https://github.com/gramineproject/contrib/blob/57eac4d10e82a3afc3ef6cec7532036260820809/Intel-Confidential-Compute-for-X/README.md#L80)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Misaligned closing `|`
</blockquote></details>

See below
___
*[`Intel-Confidential-Compute-for-X/README.md` line 83 at r1](https://reviewable.io/reviews/gramineproject/contrib/43#-NSKLIwT1-HgHKLwbxXE:-NSMzumT4PA1uxLXl77m:b-ckiqe1) ([raw file](https://github.com/gramineproject/contrib/blob/57eac4d10e82a3afc3ef6cec7532036260820809/Intel-Confidential-Compute-for-X/README.md#L83)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Actually, since you're changing the README file, do you want to change this from a mono-table to a more nicely rendered list, for example?
</blockquote></details>

I changed it to a proper Markdown table. I know that you will complain about the 100 chars per line, but I don't see a way to properly do it otherwise.
___
*[`Intel-Confidential-Compute-for-X/workloads/memcached/README.md` line 3 at r1](https://reviewable.io/reviews/gramineproject/contrib/43#-NSKJ1u_2yrN5K7U-4et:-NSN-Ovt1uk6DOGhXEvJ:bxgb70t) ([raw file](https://github.com/gramineproject/contrib/blob/57eac4d10e82a3afc3ef6cec7532036260820809/Intel-Confidential-Compute-for-X/workloads/memcached/README.md#L3)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please re-wrap this to 100-chars-per-line
</blockquote></details>

Done as it matches the rules of the project, but under slight protest. In pure documentation files, I consider such an arbitrary word wrap counter-productive. Personally, I would wrap at the end of a sentence. As a result, minor text updates will result in a nice diff showing only the changed words. With an arbitrary wrap, the change might unnecessarily cascade for a few lines and it leads to a lot of avoidable effort. Besides, everybody using a somewhat recent editor can just set wrapping to the viewport or an arbitrary border. But I know, this is a touchy subject ;-)
___
*[`Intel-Confidential-Compute-for-X/workloads/mysql/README.md` line 37 at r1](https://reviewable.io/reviews/gramineproject/contrib/43#-NSKL-3yAbGBjnWTze_d:-NSN14dK5iMKiTfD8UxJ:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/57eac4d10e82a3afc3ef6cec7532036260820809/Intel-Confidential-Compute-for-X/workloads/mysql/README.md#L37)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add `:` at the end
</blockquote></details>

Done.
___
*[`Intel-Confidential-Compute-for-X/workloads/pytorch/README.md` line 9 at r1](https://reviewable.io/reviews/gramineproject/contrib/43#-NSKJFC90jYRRl5tTPdx:-NSN1D7OBx07oTu_yqaz:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/57eac4d10e82a3afc3ef6cec7532036260820809/Intel-Confidential-Compute-for-X/workloads/pytorch/README.md#L9)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add an empty line after this section title
</blockquote></details>

Done.
___
*[`Intel-Confidential-Compute-for-X/workloads/pytorch/base_image_helper/README.md` line 24 at r1](https://reviewable.io/reviews/gramineproject/contrib/43#-NSKJOs08UxNrlR0FG3C:-NSN1La05Ejalz-ye3fi:b-790h62) ([raw file](https://github.com/gramineproject/contrib/blob/57eac4d10e82a3afc3ef6cec7532036260820809/Intel-Confidential-Compute-for-X/workloads/pytorch/base_image_helper/README.md#L24)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`pre-trainer`? I guess this should be `pre-trained`

Why do we have `,` in one place in this sentence, but `;` in all other places? Looks like we should just use a comma (`,`) everywhere in this sentence.
</blockquote></details>

Changed `pre-trainer` to `pre-trained`.

I changed the sentence to use `;` everywhere. I tend to do this whenever one of the items in an enumeration contains `and` or `,`.
___
*[`Intel-Confidential-Compute-for-X/workloads/redis/README.md` line 3 at r1](https://reviewable.io/reviews/gramineproject/contrib/43#-NSKJaTl1CMZbQwGZQHx:-NSN1ywWE2SSLFwziql1:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/57eac4d10e82a3afc3ef6cec7532036260820809/Intel-Confidential-Compute-for-X/workloads/redis/README.md#L3)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This file contains a couple places where trailing whitespace is visible. Please remove it.
</blockquote></details>

Done.



_Code quote:_
```Markdown
onfigured, non-production ready, te
```
___
*[`Intel-Confidential-Compute-for-X/workloads/redis/README.md` line 24 at r1](https://reviewable.io/reviews/gramineproject/contrib/43#-NSKJf5v4YhSTlugk_eq:-NSN1zChDKbpQci-mQGB:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/57eac4d10e82a3afc3ef6cec7532036260820809/Intel-Confidential-Compute-for-X/workloads/redis/README.md#L24)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Trailing whitespace here
</blockquote></details>

Done.
___
*[`Intel-Confidential-Compute-for-X/workloads/redis/README.md` line 29 at r1](https://reviewable.io/reviews/gramineproject/contrib/43#-NSKJhHl6B1ZB71l25Xr:-NSN1zgACsOpTe6upAIH:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/57eac4d10e82a3afc3ef6cec7532036260820809/Intel-Confidential-Compute-for-X/workloads/redis/README.md#L29)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Trailing whitespace here
</blockquote></details>

Done.
___
*[`Intel-Confidential-Compute-for-X/workloads/redis/README.md` line 45 at r1](https://reviewable.io/reviews/gramineproject/contrib/43#-NSKJiV89GwRgfUd8yd6:-NSN2-BRD0nHwdJYTpM8:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/57eac4d10e82a3afc3ef6cec7532036260820809/Intel-Confidential-Compute-for-X/workloads/redis/README.md#L45)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Trailing whitespace here
</blockquote></details>

Done.
___
*[`In [...]

2023-04-11 09:14 UTC, dimakuv requested changes
> Reviewed 12 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/43)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @BFuhry)

___
*[`Intel-Confidential-Compute-for-X/README.md` line 35 at r1](https://reviewable.io/reviews/gramineproject/contrib/43#-NSKKe4h9tNyT0jcXpH6:-NSjZIZb6thrQU-9HA3U:b32w1t) ([raw file](https://github.com/gramineproject/contrib/blob/57eac4d10e82a3afc3ef6cec7532036260820809/Intel-Confidential-Compute-for-X/README.md#L35)):*
<details><summary><i>Previously, BFuhry wrote…</i></summary><blockquote>

I like to have this very explicit. Once anybody validates the commands for other versions, it will be very easy to add a version (if the same commands work) or to add a new block (if other commands are necessary).
</blockquote></details>

Ok
___
*[`Intel-Confidential-Compute-for-X/README.md` line 83 at r1](https://reviewable.io/reviews/gramineproject/contrib/43#-NSKLIwT1-HgHKLwbxXE:-NSjZd1mAqdAvq-ChixV:b57dwbn) ([raw file](https://github.com/gramineproject/contrib/blob/57eac4d10e82a3afc3ef6cec7532036260820809/Intel-Confidential-Compute-for-X/README.md#L83)):*
<details><summary><i>Previously, BFuhry wrote…</i></summary><blockquote>

I changed it to a proper Markdown table. I know that you will complain about the 100 chars per line, but I don't see a way to properly do it otherwise.
</blockquote></details>

The argument names are not visible now: https://github.com/BFuhry/contrib/tree/currated-apps-rename/Intel-Confidential-Compute-for-X#usage-of-the-interactive-script

I think Markdown thinks of `<` and `>` as special characters. You may want to just remove these symbols.
___
*[`Intel-Confidential-Compute-for-X/README.md` line 78 at r2](https://reviewable.io/reviews/gramineproject/contrib/43#-NSjZkYfBPORiYOMXFqq:-NSjZkYfBPORiYOMXFqr:b-ea5hdg) ([raw file](https://github.com/gramineproject/contrib/blob/26d4fdae84330c140b15865ca32a16b9372efbd5/Intel-Confidential-Compute-for-X/README.md#L78)):*
> ```Markdown
> | Required?| Argument | Description/Possible values |
> | :----: | :----: | :--- |
> | Yes | <app name> | Name of the application, e.g., redis or pytorch. Name has to correspond to the application's folder name in 'workloads/'. |
> ```

This name looks wrong -- in the command line above, you have `workload type`, not `app name`. Please fix it.
___
*[`Intel-Confidential-Compute-for-X/workloads/memcached/README.md` line 3 at r1](https://reviewable.io/reviews/gramineproject/contrib/43#-NSKJ1u_2yrN5K7U-4et:-NSjZzQGDy1ByTubrQ6d:b-cey4z5) ([raw file](https://github.com/gramineproject/contrib/blob/57eac4d10e82a3afc3ef6cec7532036260820809/Intel-Confidential-Compute-for-X/workloads/memcached/README.md#L3)):*
> With an arbitrary wrap, the change might unnecessarily cascade for a few lines and it leads to a lot of avoidable effort.

I agree with this part -- it's a bit cumbersome.

> Besides, everybody using a somewhat recent editor can just set wrapping to the viewport or an arbitrary border.

"Somewhat recent editor" doesn't map to my reality :) I routinely need to log into mupltiple very different Linux machines every day, and sometimes I only have `cat`, `less` and `nano` tools. So reading e.g. READMEs becomes a pain. My point is: there are very different circumstances in which people need to read text files...
___
*[`Intel-Confidential-Compute-for-X/workloads/tensorflow-serving/README.md` line 40 at r1](https://reviewable.io/reviews/gramineproject/contrib/43#-NSKJzduExKFKTd7z3K1:-NSj_pmh94KOPDbh4g04:blhiiu5) ([raw file](https://github.com/gramineproject/contrib/blob/57eac4d10e82a3afc3ef6cec7532036260820809/Intel-Confidential-Compute-for-X/workloads/tensorflow-serving/README.md#L40)):*
<details><summary><i>Previously, BFuhry wrote…</i></summary><blockquote>

Done. Reviewable has huge problems with this little re-wrap ;-)
</blockquote></details>

Does it? Looks fine to me.
___
*[`Intel-Confidential-Compute-for-X/workloads/tensorflow-serving/base_image_helper/helper.sh` line 57 at r2](https://reviewable.io/reviews/gramineproject/contrib/43#-NSj_zvL-DqYh9X1wzI4:-NSj_zvL-DqYh9X1wzI5:b-kfhg0c) ([raw file](https://github.com/gramineproject/contrib/blob/26d4fdae84330c140b15865ca32a16b9372efbd5/Intel-Confidential-Compute-for-X/workloads/tensorflow-serving/base_image_helper/helper.sh#L57)):*
> ```Shell
> 
> echo -e '\n\nCreated base image `'$TF_SERVING_IMAGE_FINAL'`.'
> echo -e 'Please refer to `' \
> ```

Looks like you have too many backtick symbols now?


<!-- Sent from Reviewable.io -->

2023-04-11 10:08 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/43)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @BFuhry and @jkr0103)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/43#-NSKKEAx37pLliM_bSeM:-NSjm-rj95CZZof0aumu:b-hpctsi) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@jkr0103 @aneessahib Could you review this PR too?
</blockquote></details>

Yes doing it right now. Finding it hard to compare contents of new folder with the old one.

___


<!-- Sent from Reviewable.io -->

2023-04-11 17:28 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/43)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @BFuhry, @dimakuv, and @jkr0103)

___
*[`Intel-Confidential-Compute-for-X/README.md` line 24 at r1](https://reviewable.io/reviews/gramineproject/contrib/43#-NSlKzpPBgNrbPDmfnm8:-NSlKzpPBgNrbPDmfnm9:b9sxbhe) ([raw file](https://github.com/gramineproject/contrib/blob/57eac4d10e82a3afc3ef6cec7532036260820809/Intel-Confidential-Compute-for-X/README.md#L24)):*
> ```Markdown
> 
> The interactive script also provides a test feature.
> With a single command, users can generate a non-production, Gramine-protected Docker image.
> ```

I think we should also call out that the test Gramine-protected Docker image feature is available only for the supported workloads mentioned above. 
___
*[`Intel-Confidential-Compute-for-X/README.md` line 83 at r1](https://reviewable.io/reviews/gramineproject/contrib/43#-NSKLIwT1-HgHKLwbxXE:-NSlLtcq7TKxtiUB3C08:bcd2urc) ([raw file](https://github.com/gramineproject/contrib/blob/57eac4d10e82a3afc3ef6cec7532036260820809/Intel-Confidential-Compute-for-X/README.md#L83)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The argument names are not visible now: https://github.com/BFuhry/contrib/tree/currated-apps-rename/Intel-Confidential-Compute-for-X#usage-of-the-interactive-script

I think Markdown thinks of `<` and `>` as special characters. You may want to just remove these symbols.
</blockquote></details>

Agree, looks a bit odd.


<!-- Sent from Reviewable.io -->

2023-04-11 17:38 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/43)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @BFuhry, @dimakuv, and @jkr0103)

___
*[`Intel-Confidential-Compute-for-X/workloads/tensorflow-serving/README.md` line 57 at r2](https://reviewable.io/reviews/gramineproject/contrib/43#-NSlNjY0-tdEnJKTb-X2:-NSlNNRn5JizI2V9XJXd:b-zgxl69) ([raw file](https://github.com/gramineproject/contrib/blob/26d4fdae84330c140b15865ca32a16b9372efbd5/Intel-Confidential-Compute-for-X/workloads/tensorflow-serving/README.md#L57)):*
> ```Markdown
> 
> ## Prepared Models
> ```

@svenkata9 Can you review these TF parts of the PR


<!-- Sent from Reviewable.io -->

2023-04-11 21:43 UTC, BFuhry reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/43)* status: 67 of 69 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @dimakuv, and @jkr0103)

___
*[`Intel-Confidential-Compute-for-X/README.md` line 24 at r1](https://reviewable.io/reviews/gramineproject/contrib/43#-NSlKzpPBgNrbPDmfnm8:-NSmFvFh-Ac004d8zXju:bwm2f60) ([raw file](https://github.com/gramineproject/contrib/blob/57eac4d10e82a3afc3ef6cec7532036260820809/Intel-Confidential-Compute-for-X/README.md#L24)):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

I think we should also call out that the test Gramine-protected Docker image feature is available only for the supported workloads mentioned above. 
</blockquote></details>

Feel free to directly adjust the text. Alternatively, propose a sentence I should insert.
___
*[`Intel-Confidential-Compute-for-X/README.md` line 83 at r1](https://reviewable.io/reviews/gramineproject/contrib/43#-NSKLIwT1-HgHKLwbxXE:-NSjxPEQDQQoOupdTkM1:bw78bnp) ([raw file](https://github.com/gramineproject/contrib/blob/57eac4d10e82a3afc3ef6cec7532036260820809/Intel-Confidential-Compute-for-X/README.md#L83)):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

Agree, looks a bit odd.
</blockquote></details>

Done, escaped `<` and `>`
___
*[`Intel-Confidential-Compute-for-X/README.md` line 78 at r2](https://reviewable.io/reviews/gramineproject/contrib/43#-NSjZkYfBPORiYOMXFqq:-NSjxGS3Cvgy0eBshhm7:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/26d4fdae84330c140b15865ca32a16b9372efbd5/Intel-Confidential-Compute-for-X/README.md#L78)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This name looks wrong -- in the command line above, you have `workload type`, not `app name`. Please fix it.
</blockquote></details>

Done.
___
*[`Intel-Confidential-Compute-for-X/workloads/memcached/README.md` line 3 at r1](https://reviewable.io/reviews/gramineproject/contrib/43#-NSKJ1u_2yrN5K7U-4et:-NSjxvOd4BzXTEWPfxLs:bc2y6d2) ([raw file](https://github.com/gramineproject/contrib/blob/57eac4d10e82a3afc3ef6cec7532036260820809/Intel-Confidential-Compute-for-X/workloads/memcached/README.md#L3)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> With an arbitrary wrap, the change might unnecessarily cascade for a few lines and it leads to a lot of avoidable effort.

I agree with this part -- it's a bit cumbersome.

> Besides, everybody using a somewhat recent editor can just set wrapping to the viewport or an arbitrary border.

"Somewhat recent editor" doesn't map to my reality :) I routinely need to log into mupltiple very different Linux machines every day, and sometimes I only have `cat`, `less` and `nano` tools. So reading e.g. READMEs becomes a pain. My point is: there are very different circumstances in which people need to read text files...
</blockquote></details>

I have some opinion on that, but I'm fully aware that this is a fruitless discussion and does don't go on here.
___
*[`Intel-Confidential-Compute-for-X/workloads/tensorflow-serving/README.md` line 40 at r1](https://reviewable.io/reviews/gramineproject/contrib/43#-NSKJzduExKFKTd7z3K1:-NSjy92E5G5lU-mXIOJp:bss0nrv) ([raw file](https://github.com/gramineproject/contrib/blob/57eac4d10e82a3afc3ef6cec7532036260820809/Intel-Confidential-Compute-for-X/workloads/tensorflow-serving/README.md#L40)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Does it? Looks fine to me.
</blockquote></details>

Today, Reviewable looks different to me and I can't get back the old view. But it showed ~100 lines as changed instead of 1 word.
___
*[`Intel-Confidential-Compute-for-X/workloads/tensorflow-serving/base_image_helper/helper.sh` line 57 at r2](https://reviewable.io/reviews/gramineproject/contrib/43#-NSj_zvL-DqYh9X1wzI4:-NSmEny19omnJMJvoNry:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/26d4fdae84330c140b15865ca32a16b9372efbd5/Intel-Confidential-Compute-for-X/workloads/tensorflow-serving/base_image_helper/helper.sh#L57)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Looks like you have too many backtick symbols now?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-12 05:33 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/43)* status: 67 of 69 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @BFuhry, @dimakuv, and @jkr0103)

___
*[`Intel-Confidential-Compute-for-X/README.md` line 24 at r1](https://reviewable.io/reviews/gramineproject/contrib/43#-NSlKzpPBgNrbPDmfnm8:-NSnakuB01C5JaR04QKa:b90f6tx) ([raw file](https://github.com/gramineproject/contrib/blob/57eac4d10e82a3afc3ef6cec7532036260820809/Intel-Confidential-Compute-for-X/README.md#L24)):*
<details><summary><i>Previously, BFuhry wrote…</i></summary><blockquote>

Feel free to directly adjust the text. Alternatively, propose a sentence I should insert.
</blockquote></details>

"The interactive script also comes with a test feature for the supported applications listed above."


<!-- Sent from Reviewable.io -->

2023-04-12 08:39 UTC, dimakuv submitted a review, later dismissed
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/43)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @BFuhry)



<!-- Sent from Reviewable.io -->

2023-04-12 09:01 UTC, svenkata9 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/43)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @BFuhry)

___
*[`Intel-Confidential-Compute-for-X/workloads/tensorflow-serving/README.md` line 57 at r2](https://reviewable.io/reviews/gramineproject/contrib/43#-NSlNjY0-tdEnJKTb-X2:-NSogSaj6AxHs9S2M6ap:b-85i649) ([raw file](https://github.com/gramineproject/contrib/blob/26d4fdae84330c140b15865ca32a16b9372efbd5/Intel-Confidential-Compute-for-X/workloads/tensorflow-serving/README.md#L57)):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

@svenkata9 Can you review these TF parts of the PR
</blockquote></details>

LGTM 


<!-- Sent from Reviewable.io -->

2023-04-12 09:41 UTC, BFuhry reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/43)* status: 68 of 69 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @dimakuv)

___
*[`Intel-Confidential-Compute-for-X/README.md` line 24 at r1](https://reviewable.io/reviews/gramineproject/contrib/43#-NSlKzpPBgNrbPDmfnm8:-NSopn3o3n4bCRQ1-Zko:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/57eac4d10e82a3afc3ef6cec7532036260820809/Intel-Confidential-Compute-for-X/README.md#L24)):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

"The interactive script also comes with a test feature for the supported applications listed above."
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-12 09:50 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/43)* status: 68 of 69 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/43#-NSKLTiv2foYJ3BfRxRS:-NSorYb1-xzCHiZmF8si:b-ad8w8c) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I did a rather light review, by checking raw contents and by browsing through rendered contents here: https://github.com/BFuhry/contrib/tree/currated-apps-rename/Intel-Confidential-Compute-for-X

Looks good to me, bar some comments.
</blockquote></details>

Validation team will now start validating this PR. We should get some results in the next couple of days. Pls block merge till we get some good initial data.

___


<!-- Sent from Reviewable.io -->

2023-04-13 06:56 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/43)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/43#-NSKLTiv2foYJ3BfRxRS:-NStOQ036A8dQ6iJeNVu:bdya4l7) (no related file):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

Validation team will now start validating this PR. We should get some results in the next couple of days. Pls block merge till we get some good initial data.
</blockquote></details>

I put a blocking comment now, to not merge this PR accidentally.

___


<!-- Sent from Reviewable.io -->

2023-04-17 07:13 UTC, anjalirai-intel commented
*[`Intel-Confidential-Compute-for-X/README.md` line 84 at r4](https://reviewable.io/reviews/gramineproject/contrib/43#-NTD2peU3o18FwFmQzJ-:-NTD2peU3o18FwFmQzJ0:b-cebbzt) ([raw file](https://github.com/gramineproject/contrib/blob/eb11386fd7b8d92ae811bfb023b509637608103a/Intel-Confidential-Compute-for-X/README.md#L84)):*
> ```Markdown
> 
> 
> ## Contents
> ```

Keys folder is missing from contents. It should also be added


<!-- Sent from Reviewable.io -->

2023-04-17 07:16 UTC, anjalirai-intel commented
*[`Intel-Confidential-Compute-for-X/README.md` line 54 at r4](https://reviewable.io/reviews/gramineproject/contrib/43#-NTD3IRR7We52xVRt8u3:-NTD3IRR7We52xVRt8u4:bufq14x) ([raw file](https://github.com/gramineproject/contrib/blob/eb11386fd7b8d92ae811bfb023b509637608103a/Intel-Confidential-Compute-for-X/README.md#L54)):*
> ```Markdown
> 
> - Install the necessary build dependencies:
>     - Ubuntu 18.04:
> ```

The dependencies are common for Ubuntu 18.04 and Ubuntu 20.04,  is it okay to mention only Ubuntu 18.04


<!-- Sent from Reviewable.io -->

2023-04-17 07:18 UTC, anjalirai-intel commented
*[`Intel-Confidential-Compute-for-X/README.md` line 45 at r4](https://reviewable.io/reviews/gramineproject/contrib/43#-NTD3jYh5TrmysIzEemc:-NTD3jYh5TrmysIzEemd:bqv4soi) ([raw file](https://github.com/gramineproject/contrib/blob/eb11386fd7b8d92ae811bfb023b509637608103a/Intel-Confidential-Compute-for-X/README.md#L45)):*
> ```Markdown
> ### For executing an "Intel® Confidential Compute for X" image
> 
> - Hardware requirements: An Intel® SGX-enabled bare metal machine or a VM.
> ```

Currently, this repo is enabled only for Azure VM's not for any Intel SGX enabled bare metal machine


<!-- Sent from Reviewable.io -->

2023-04-17 07:19 UTC, anjalirai-intel commented
*[`Intel-Confidential-Compute-for-X/workloads/pytorch/README.md` line 48 at r4](https://reviewable.io/reviews/gramineproject/contrib/43#-NTD43Mi5lCpWSHlMcIy:-NTD43Mi5lCpWSHlMcIz:b-w5n618) ([raw file](https://github.com/gramineproject/contrib/blob/eb11386fd7b8d92ae811bfb023b509637608103a/Intel-Confidential-Compute-for-X/workloads/pytorch/README.md#L48)):*
> ```Markdown
>         4. Run the generated PyTorch image using below command:
>             ```sh
>             docker run --net=host --device=/dev/sgx/enclave -it gsc-pytorch-encrypted
> ```

This step is not required, and also not mentioned as part of other workloads, It is covered in next step


<!-- Sent from Reviewable.io -->

2023-04-17 07:25 UTC, anjalirai-intel commented
*[`Intel-Confidential-Compute-for-X/workloads/sklearn/README.md` line 5 at r4](https://reviewable.io/reviews/gramineproject/contrib/43#-NTD4kLH6gbgWALSZMXX:-NTD4kLH6gbgWALSZMXY:bjhwf7t) ([raw file](https://github.com/gramineproject/contrib/blob/eb11386fd7b8d92ae811bfb023b509637608103a/Intel-Confidential-Compute-for-X/workloads/sklearn/README.md#L5)):*
> ```Markdown
> In the following two sections, we explain how a Docker image for a Gramine-protected Scikit-learn
> version can be built and how the image can be executed.
> We assume that the [prerequisites](https://github.com/gramineproject/contrib/tree/master/Intel-Confidential-Compute-for-X/README.md)
> ```

Currently, all hyperlinks are relative path, but this path is absolute path and when you refer it is returning 404 error. Should this also be relative path instead of absolute path?


<!-- Sent from Reviewable.io -->

2023-04-17 07:28 UTC, anjalirai-intel commented
*[`Intel-Confidential-Compute-for-X/workloads/sklearn/base_image_helper/README.md` line 7 at r4](https://reviewable.io/reviews/gramineproject/contrib/43#-NTD5k3g9eDDBTMQIBJl:-NTD5k3g9eDDBTMQIBJm:b-3kgqb7) ([raw file](https://github.com/gramineproject/contrib/blob/eb11386fd7b8d92ae811bfb023b509637608103a/Intel-Confidential-Compute-for-X/workloads/sklearn/base_image_helper/README.md#L7)):*
> ```Markdown
> 
> - Install dependencies:
>     - Ubuntu 18.04:
> ```

This section here implies that this workload is specific only for Ubuntu 18.04, can we rephrase this in order to avoid confusion


<!-- Sent from Reviewable.io -->

2023-04-17 07:39 UTC, anjalirai-intel reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/43)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @BFuhry and @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/43#-NSKLTiv2foYJ3BfRxRS:-NTD6vfE2LraqhKSf2tc:b-bj4rqd) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I put a blocking comment now, to not merge this PR accidentally.
</blockquote></details>

Contents of Redis, mysql and tensorflow-serving is incorrect

___
*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/43#-NTD7_pjDWvteQrudtdo:-NTD7_pjDWvteQrudtdp:b-48zsae) (no related file):*
There are couple of other things as well
1. Should we also rename also curate.py?
2. Nothing related to base os is mentioned, should we mention also something related to it? 

___
___
*[`Intel-Confidential-Compute-for-X/README.md` line 38 at r4](https://reviewable.io/reviews/gramineproject/contrib/43#-NTD7Cd0CTMtQbnXZH73:-NTD7Cd0CTMtQbnXZH74:b-8xt7v7) ([raw file](https://github.com/gramineproject/contrib/blob/eb11386fd7b8d92ae811bfb023b509637608103a/Intel-Confidential-Compute-for-X/README.md#L38)):*
> ```Markdown
>         ```sh
>         sudo apt-get update && sudo apt-get install jq docker.io python3 python3-pip
>         python3 -m install docker jinja2 toml pyyaml
> ```

toml should be replaced with tomli tomli-w


<!-- Sent from Reviewable.io -->

2023-04-17 09:23 UTC, BFuhry reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/43)* status: 62 of 69 files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @anjalirai-intel and @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/43#-NSKLTiv2foYJ3BfRxRS:-NTDVnar9ZWq3f1KMZMR:b14n27o) (no related file):*
<details><summary><i>Previously, anjalirai-intel wrote…</i></summary><blockquote>

Contents of Redis, mysql and tensorflow-serving is incorrect
</blockquote></details>

I've done all changed that should be part of this PR.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/43#-NTD7_pjDWvteQrudtdo:-NTDT7zpEMqnu2hNJYCK:b-63q8xv) (no related file):*
<details><summary><i>Previously, anjalirai-intel wrote…</i></summary><blockquote>

There are couple of other things as well
1. Should we also rename also curate.py?
2. Nothing related to base os is mentioned, should we mention also something related to it? 
</blockquote></details>

Please do that in a subsequent PR. This PR and I is not there for any content changes. It is "just" a rewrite of the docu.

___
___
*[`Intel-Confidential-Compute-for-X/README.md` line 38 at r4](https://reviewable.io/reviews/gramineproject/contrib/43#-NTD7Cd0CTMtQbnXZH73:-NTDROc86Q-8EUPSZ7W6:b-63q8xv) ([raw file](https://github.com/gramineproject/contrib/blob/eb11386fd7b8d92ae811bfb023b509637608103a/Intel-Confidential-Compute-for-X/README.md#L38)):*
<details><summary><i>Previously, anjalirai-intel wrote…</i></summary><blockquote>

toml should be replaced with tomli tomli-w
</blockquote></details>

Please do that in a subsequent PR. This PR and I is not there for any content changes. It is "just" a rewrite of the docu.
___
*[`Intel-Confidential-Compute-for-X/README.md` line 45 at r4](https://reviewable.io/reviews/gramineproject/contrib/43#-NTD3jYh5TrmysIzEemc:-NTDT1ccALwvP9UvXEUu:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/eb11386fd7b8d92ae811bfb023b509637608103a/Intel-Confidential-Compute-for-X/README.md#L45)):*
<details><summary><i>Previously, anjalirai-intel wrote…</i></summary><blockquote>

Currently, this repo is enabled only for Azure VM's not for any Intel SGX enabled bare metal machine
</blockquote></details>

Done.
___
*[`Intel-Confidential-Compute-for-X/README.md` line 54 at r4](https://reviewable.io/reviews/gramineproject/contrib/43#-NTD3IRR7We52xVRt8u3:-NTDRnqj5L0ixUdFtwRs:b-f381jr) ([raw file](https://github.com/gramineproject/contrib/blob/eb11386fd7b8d92ae811bfb023b509637608103a/Intel-Confidential-Compute-for-X/README.md#L54)):*
<details><summary><i>Previously, anjalirai-intel wrote…</i></summary><blockquote>

The dependencies are common for Ubuntu 18.04 and Ubuntu 20.04,  is it okay to mention only Ubuntu 18.04
</blockquote></details>

I did just rewrite what was there before. If somebody has validated it with Ubuntu 20.04, feel free to add Ubuntu 20.04.

However, please do that in a subsequent PR. This PR and I is not there for any content changes. It is "just" a rewrite of the docu.
___
*[`Intel-Confidential-Compute-for-X/README.md` line 84 at r4](https://reviewable.io/reviews/gramineproject/contrib/43#-NTD2peU3o18FwFmQzJ-:-NTDS1192iltAWvs34lR:b-63q8xv) ([raw file](https://github.com/gramineproject/contrib/blob/eb11386fd7b8d92ae811bfb023b509637608103a/Intel-Confidential-Compute-for-X/README.md#L84)):*
<details><summary><i>Previously, anjalirai-intel wrote…</i></summary><blockquote>

Keys folder is missing from contents. It should also be added
</blockquote></details>

Please do that in a subsequent PR. This PR and I is not there for any content changes. It is "just" a rewrite of the docu.
___
*[`Intel-Confidential-Compute-for-X/workloads/pytorch/README.md` line 48 at r4](https://reviewable.io/reviews/gramineproject/contrib/43#-NTD43Mi5lCpWSHlMcIy:-NTDTRS-1mBIBu-7VgN9:b-ukkkik) ([raw file](https://github.com/gramineproject/contrib/blob/eb11386fd7b8d92ae811bfb023b509637608103a/Intel-Confidential-Compute-for-X/workloads/pytorch/README.md#L48)):*
<details><summary><i>Previously, anjalirai-intel wrote…</i></summary><blockquote>

This step is not required, and also not mentioned as part of other workloads, It is covered in next step
</blockquote></details>

I did not change anything on this step (https://github.com/gramineproject/contrib/pull/43/commits/57eac4d10e82a3afc3ef6cec7532036260820809#diff-b62f685a082fab7586e27653b9c3f0f2dc10e6ceaa30c97f0c584a16a1516c2e). If there is something wrong with it, please do that in a subsequent PR. This PR and I is not there for any content changes. It is "just" a rewrite of the docu.

Besides, this is the last step so there cannot be any next step that covers it. The next step is a completely different alternative.
___
*[`Intel-Confidential-Compute-for-X/workloads/sklearn/README.md` line 5 at r4](https://reviewable.io/reviews/gramineproject/contrib/43#-NTD4kLH6gbgWALSZMXX:-NTDUcJSDDrw0Rww9_fU:bs7wumb) ([raw file](https://github.com/gramineproject/contrib/blob/eb11386fd7b8d92ae811bfb023b509637608103a/Intel-Confidential-Compute-for-X/workloads/sklearn/README.md#L5)):*
<details><summary><i>Previously, anjalirai-intel wrote…</i></summary><blockquote>

Currently, all hyperlinks are relative path, but this path is absolute path and when you refer it is returning 404 error. Should this also be relative path instead of absolute path?
</blockquote></details>

Done.
___
*[`Intel-Confidential-Compute-for-X/workloads/sklearn/base_image_helper/README.md` line 7 at r4](https://reviewable.io/reviews/gramineproject/contrib/43#-NTD5k3g9eDDBTMQIBJl:-NTDUlYG7C3RlWT9vLLz:bhdc8f7) ([raw file](https://github.com/gramineproject/contrib/blob/eb11386fd7b8d92ae811bfb023b509637608103a/Intel-Confidential-Compute-for-X/workloads/sklearn/base_image_helper/README.md#L7)):*
<details><summary><i>Previously, anjalirai-intel wrote…</i></summary><blockquote>

This section here implies that this workload is specific only for Ubuntu 18.04, can we rephrase this in order to avoid confusion
</blockquote></details>

This is on purpose to 100%. Before, only a somewhat hidden comment stated that this is only for Ubuntu 18.04 (https://github.com/gramineproject/contrib/pull/43/commits/57eac4d10e82a3afc3ef6cec7532036260820809#diff-735c8765720822dec12be0350fa195369ae712579348a5293d190f560bdec340). 

If somebody has validated it with Ubuntu 20.04, feel free to add Ubuntu 20.04.

However, please do that in a subsequent PR. This PR and I is not there for any content changes. It is "just" a rewrite of the docu.


<!-- Sent from Reviewable.io -->

2023-04-17 10:18 UTC, anjalirai-intel reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/43)* status: 62 of 69 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @BFuhry and @dimakuv)

___
*[`Intel-Confidential-Compute-for-X/README.md` line 38 at r4](https://reviewable.io/reviews/gramineproject/contrib/43#-NTD7Cd0CTMtQbnXZH73:-NTDhoxUCZ6i99qz3Wg2:bthm5dg) ([raw file](https://github.com/gramineproject/contrib/blob/eb11386fd7b8d92ae811bfb023b509637608103a/Intel-Confidential-Compute-for-X/README.md#L38)):*
<details><summary><i>Previously, BFuhry wrote…</i></summary><blockquote>

Please do that in a subsequent PR. This PR and I is not there for any content changes. It is "just" a rewrite of the docu.
</blockquote></details>

It was already done. Your PR reverted it


<!-- Sent from Reviewable.io -->

2023-04-17 10:34 UTC, BFuhry reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/43)* status: 62 of 69 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @anjalirai-intel and @dimakuv)

___
*[`Intel-Confidential-Compute-for-X/README.md` line 38 at r4](https://reviewable.io/reviews/gramineproject/contrib/43#-NTD7Cd0CTMtQbnXZH73:-NTDlKQU5bVC1P1CzZU4:b-or7kf3) ([raw file](https://github.com/gramineproject/contrib/blob/eb11386fd7b8d92ae811bfb023b509637608103a/Intel-Confidential-Compute-for-X/README.md#L38)):*
<details><summary><i>Previously, anjalirai-intel wrote…</i></summary><blockquote>

It was already done. Your PR reverted it
</blockquote></details>

Done. I stand corrected. 


<!-- Sent from Reviewable.io -->

2023-04-18 04:11 UTC, anjalirai-intel commented
*[`Intel-Confidential-Compute-for-X/workloads/pytorch/README.md` line 15 at r6](https://reviewable.io/reviews/gramineproject/contrib/43#-NTHYX_WA22q2PVmrjWZ:-NTHYX_WA22q2PVmrjW_:b-fr9pwe) ([raw file](https://github.com/gramineproject/contrib/blob/80f1b68970783fc6b80d99c39ba14afca691d58e/Intel-Confidential-Compute-for-X/workloads/pytorch/README.md#L15)):*
> ```Markdown
> 1. Clone the Gramine Contrib repository:
>     ```sh
>     $ git clone --depth 1 https://github.com/gramineproject/contrib.git
> ```

Sorry, I missed this earlier, But there was one commit which removed $ symbol from sh commands. So, this should also be taken care back again

https://github.com/gramineproject/contrib/commit/0deede256f2dcbc5f6c2216483979e9830bcf15e


<!-- Sent from Reviewable.io -->

2023-04-18 07:05 UTC, BFuhry reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/43)* status: 62 of 69 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @anjalirai-intel and @dimakuv)

___
*[`Intel-Confidential-Compute-for-X/workloads/pytorch/README.md` line 15 at r6](https://reviewable.io/reviews/gramineproject/contrib/43#-NTHYX_WA22q2PVmrjWZ:-NTIAgyq4Lehab7uUI8Q:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/80f1b68970783fc6b80d99c39ba14afca691d58e/Intel-Confidential-Compute-for-X/workloads/pytorch/README.md#L15)):*
<details><summary><i>Previously, anjalirai-intel wrote…</i></summary><blockquote>

Sorry, I missed this earlier, But there was one commit which removed $ symbol from sh commands. So, this should also be taken care back again

https://github.com/gramineproject/contrib/commit/0deede256f2dcbc5f6c2216483979e9830bcf15e
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-18 07:55 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/43)* status: 62 of 69 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/43#-NSKLTiv2foYJ3BfRxRS:-NTILwOc9fcPVJkg_X75:bby6304) (no related file):*
<details><summary><i>Previously, BFuhry wrote…</i></summary><blockquote>

I've done all changed that should be part of this PR.
</blockquote></details>

@dimakuv - All good from validation. We can proceed now.

___


<!-- Sent from Reviewable.io -->

2023-04-19 07:56 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r6, 6 of 6 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/43)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @BFuhry)

___
*[`Intel-Confidential-Compute-for-X/README.md` line 45 at r7](https://reviewable.io/reviews/gramineproject/contrib/43#-NTNVeoB4OzV1J5Bj53y:-NTNVeoCCbDZ0iYej3ga:b-dd1s8i) ([raw file](https://github.com/gramineproject/contrib/blob/de001e0d56ab0e714ea7f93ee7aaaf2795d51766/Intel-Confidential-Compute-for-X/README.md#L45)):*
> ```Markdown
> ### For executing an "Intel® Confidential Compute for X" image
> 
> - Hardware requirements: This project currently only works for SGX-enabled Azure VMs. With some modifications, it will work on any Intel® SGX-enabled bare metal machine or VM.
> ```

This should be rewrapped to 100 chars per line. Actually, the other two items below should be rewrapped too.
___
*[`Intel-Confidential-Compute-for-X/workloads/memcached/README.md` line 6 at r7](https://reviewable.io/reviews/gramineproject/contrib/43#-NTNVq705uo3FxW1CbuA:-NTNVq705uo3FxW1CbuB:by0f2wn) ([raw file](https://github.com/gramineproject/contrib/blob/de001e0d56ab0e714ea7f93ee7aaaf2795d51766/Intel-Confidential-Compute-for-X/workloads/memcached/README.md#L6)):*
> ```Markdown
> version can be built and how the image can be executed.
> We assume that the [prerequisites](../../README.md)
> for the build and the execution phase are met.
> ```

This sentence is wrapped incorrectly now.
___
*[`Intel-Confidential-Compute-for-X/workloads/mysql/README.md` line 6 at r7](https://reviewable.io/reviews/gramineproject/contrib/43#-NTNVuHoE2lNOhPOUyB2:-NTNVuHoE2lNOhPOUyB3:b-7ropln) ([raw file](https://github.com/gramineproject/contrib/blob/de001e0d56ab0e714ea7f93ee7aaaf2795d51766/Intel-Confidential-Compute-for-X/workloads/mysql/README.md#L6)):*
> ```Markdown
> can be built and how the image can be executed.
> We assume that the [prerequisites](../../README.md)
> for the build and the execution phase are met.
> ```

ditto
___
*[`Intel-Confidential-Compute-for-X/workloads/pytorch/README.md` line 6 at r7](https://reviewable.io/reviews/gramineproject/contrib/43#-NTNVvkK9o9KyyxQ_OXm:-NTNVvkK9o9KyyxQ_OXn:b-7ropln) ([raw file](https://github.com/gramineproject/contrib/blob/de001e0d56ab0e714ea7f93ee7aaaf2795d51766/Intel-Confidential-Compute-for-X/workloads/pytorch/README.md#L6)):*
> ```Markdown
> can be built and how the image can be executed.
> We assume that the [prerequisites](../../README.md)
> for the build and the execution phase are met.
> ```

ditto
___
*[`Intel-Confidential-Compute-for-X/workloads/redis/README.md` line 6 at r7](https://reviewable.io/reviews/gramineproject/contrib/43#-NTNVyzi5fagbc4h0CYo:-NTNVyzi5fagbc4h0CYp:b-7ropln) ([raw file](https://github.com/gramineproject/contrib/blob/de001e0d56ab0e714ea7f93ee7aaaf2795d51766/Intel-Confidential-Compute-for-X/workloads/redis/README.md#L6)):*
> ```Markdown
> can be built and how the image can be executed.
> We assume that the [prerequisites](../../README.md)
> for the build and the execution phase are met.
> ```

ditto
___
*[`Intel-Confidential-Compute-for-X/workloads/sklearn/README.md` line 6 at r7](https://reviewable.io/reviews/gramineproject/contrib/43#-NTNW-VZAhWYY322s6CQ:-NTNW-VZAhWYY322s6CR:b-7ropln) ([raw file](https://github.com/gramineproject/contrib/blob/de001e0d56ab0e714ea7f93ee7aaaf2795d51766/Intel-Confidential-Compute-for-X/workloads/sklearn/README.md#L6)):*
> ```Markdown
> version can be built and how the image can be executed.
> We assume that the [prerequisites](../../README.md)
> for the build and the execution phase are met.
> ```

ditto
___
*[`Intel-Confidential-Compute-for-X/workloads/tensorflow-serving/README.md` line 6 at r7](https://reviewable.io/reviews/gramineproject/contrib/43#-NTNW0lu-r0Ohdl74VD0:-NTNW0lu-r0Ohdl74VD1:b-7ropln) ([raw file](https://github.com/gramineproject/contrib/blob/de001e0d56ab0e714ea7f93ee7aaaf2795d51766/Intel-Confidential-Compute-for-X/workloads/tensorflow-serving/README.md#L6)):*
> ```Markdown
> Serving version can be built and how the image can be executed.
> We assume that the [prerequisites](../../README.md)
> for the build and the execution phase are met.
> ```

ditto


<!-- Sent from Reviewable.io -->

2023-04-19 09:10 UTC, dimakuv approved these changes
> Reviewed 7 of 7 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/43)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`Intel-Confidential-Compute-for-X/README.md` line 45 at r7](https://reviewable.io/reviews/gramineproject/contrib/43#-NTNVeoB4OzV1J5Bj53y:-NTNgs-g2XCVeqyA64k7:bb6un1j) ([raw file](https://github.com/gramineproject/contrib/blob/de001e0d56ab0e714ea7f93ee7aaaf2795d51766/Intel-Confidential-Compute-for-X/README.md#L45)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This should be rewrapped to 100 chars per line. Actually, the other two items below should be rewrapped too.
</blockquote></details>

Done
___
*[`Intel-Confidential-Compute-for-X/workloads/memcached/README.md` line 6 at r7](https://reviewable.io/reviews/gramineproject/contrib/43#-NTNVq705uo3FxW1CbuA:-NTNj58U-ZFAQzzwYpNx:b-5spiok) ([raw file](https://github.com/gramineproject/contrib/blob/de001e0d56ab0e714ea7f93ee7aaaf2795d51766/Intel-Confidential-Compute-for-X/workloads/memcached/README.md#L6)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This sentence is wrapped incorrectly now.
</blockquote></details>

Done. Also fixed wrappings in other places.
___
*[`Intel-Confidential-Compute-for-X/workloads/mysql/README.md` line 6 at r7](https://reviewable.io/reviews/gramineproject/contrib/43#-NTNVuHoE2lNOhPOUyB2:-NTNj8whCUbMIAkLmuUO:b-5spiok) ([raw file](https://github.com/gramineproject/contrib/blob/de001e0d56ab0e714ea7f93ee7aaaf2795d51766/Intel-Confidential-Compute-for-X/workloads/mysql/README.md#L6)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done. Also fixed wrappings in other places.
___
*[`Intel-Confidential-Compute-for-X/workloads/pytorch/README.md` line 6 at r7](https://reviewable.io/reviews/gramineproject/contrib/43#-NTNVvkK9o9KyyxQ_OXm:-NTNjA-c0yu_k1RnZ_Ib:b-5spiok) ([raw file](https://github.com/gramineproject/contrib/blob/de001e0d56ab0e714ea7f93ee7aaaf2795d51766/Intel-Confidential-Compute-for-X/workloads/pytorch/README.md#L6)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done. Also fixed wrappings in other places.
___
*[`Intel-Confidential-Compute-for-X/workloads/redis/README.md` line 6 at r7](https://reviewable.io/reviews/gramineproject/contrib/43#-NTNVyzi5fagbc4h0CYo:-NTNjBZ--sQAcDhbKSmF:b-5spiok) ([raw file](https://github.com/gramineproject/contrib/blob/de001e0d56ab0e714ea7f93ee7aaaf2795d51766/Intel-Confidential-Compute-for-X/workloads/redis/README.md#L6)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done. Also fixed wrappings in other places.
___
*[`Intel-Confidential-Compute-for-X/workloads/sklearn/README.md` line 6 at r7](https://reviewable.io/reviews/gramineproject/contrib/43#-NTNW-VZAhWYY322s6CQ:-NTNjCEP3y4G07r9AJzY:b-5spiok) ([raw file](https://github.com/gramineproject/contrib/blob/de001e0d56ab0e714ea7f93ee7aaaf2795d51766/Intel-Confidential-Compute-for-X/workloads/sklearn/README.md#L6)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done. Also fixed wrappings in other places.
___
*[`Intel-Confidential-Compute-for-X/workloads/tensorflow-serving/README.md` line 6 at r7](https://reviewable.io/reviews/gramineproject/contrib/43#-NTNW0lu-r0Ohdl74VD0:-NTNjDgk5OMUdViAnLa8:b-5spiok) ([raw file](https://github.com/gramineproject/contrib/blob/de001e0d56ab0e714ea7f93ee7aaaf2795d51766/Intel-Confidential-Compute-for-X/workloads/tensorflow-serving/README.md#L6)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done. Also fixed wrappings in other places.


<!-- Sent from Reviewable.io -->

2023-04-19 09:14 UTC, anjalirai-intel reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/43)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2023-04-19 09:17 UTC, anjalirai-intel reviewed
> Reviewed 56 of 69 files at r1, 5 of 12 files at r2, 1 of 2 files at r3, 7 of 7 files at r8.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/43)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2023-04-25 21:26 UTC, mkow approved these changes
> Reviewed 56 of 69 files at r1, 5 of 12 files at r2, 1 of 2 files at r3, 7 of 7 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/43)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`Intel-Confidential-Compute-for-X/README.md` line 60 at r8](https://reviewable.io/reviews/gramineproject/contrib/43#-NTuFPXd2S-gbepl1Zhb:-NTuFPXd2S-gbepl1Zhc:bdsbvbs) ([raw file](https://github.com/gramineproject/contrib/blob/f277f77e96f240ac8d2cd51404e6a13d5f1248c8/Intel-Confidential-Compute-for-X/README.md#L60)):*
> ```Markdown
>         ```sh
>         sudo apt-get update && sudo apt-get install -y docker.io
>         sudo chown $USER /var/run/docker.sock
> ```

Unrelated to this PR, but FYI: this line effectively gives permanent root permission to the current user.


<!-- Sent from Reviewable.io -->

2023-04-26 07:40 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/43)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-04-26 07:41 UTC, merged