[Curated-Apps] Support curation of apps on premise machines
gramineproject/contrib pull request #44
Opened 2023-05-11 08:43 UTC by jkr0103

Currently we support curation of apps only on Azure VMs.

This PR add support for curation of apps on premise machine as well.

2023-05-15 12:41 UTC, dimakuv requested changes
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/44)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @jkr0103)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/contrib/44#-NVUOvDr6r8HS9GSqhlN):*
`the` should be removed
___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/contrib/44#-NVUOySkAfcfZuU2Aoda):*
Maybe better `on non-VM machines`?
___
*[`Intel-Confidential-Compute-for-X/README.md` line 49 at r1](https://reviewable.io/reviews/gramineproject/contrib/44#-NVUPKJq5vj39zUEG572:-NVUPKJq5vj39zUEG573:b-6914wv) ([raw file](https://github.com/gramineproject/contrib/blob/297205ce3c1699f80cbf65edf7a092000eb8edb6/Intel-Confidential-Compute-for-X/README.md#L49)):*
> ```Markdown
> - SGX-enabled Azure VMs:
> 
>     At Azure, VMs of the [DCsv3 and DCdsv3-series](https://learn.microsoft.com/en-us/azure/virtual-machines/dcv3-series)
> ```

Please make it 2-spaces indentation for each line
___
*[`Intel-Confidential-Compute-for-X/README.md` line 57 at r1](https://reviewable.io/reviews/gramineproject/contrib/44#-NVUP8XtECMFMI-0t8C5:-NVUP8XtECMFMI-0t8C6:b-djqxc6) ([raw file](https://github.com/gramineproject/contrib/blob/297205ce3c1699f80cbf65edf7a092000eb8edb6/Intel-Confidential-Compute-for-X/README.md#L57)):*
> ```Markdown
>     [DCsv3 and DCdsv3-series overview](https://learn.microsoft.com/en-us/azure/virtual-machines/dcv3-series).
> 
> - On Premise system:
> ```

`Non-VM systems`? Or maybe `Bare-metal systems`
___
*[`Intel-Confidential-Compute-for-X/README.md` line 59 at r1](https://reviewable.io/reviews/gramineproject/contrib/44#-NVUPVrz5oOHwJEM_ovM:-NVUPVrz5oOHwJEM_ovN:b-6914wv) ([raw file](https://github.com/gramineproject/contrib/blob/297205ce3c1699f80cbf65edf7a092000eb8edb6/Intel-Confidential-Compute-for-X/README.md#L59)):*
> ```Markdown
> - On Premise system:
> 
>     User is expected to have DCAP Remote attestation infrastructure with PCCS setup and system
> ```

Please make it 2-spaces indentation for each line
___
*[`Intel-Confidential-Compute-for-X/README.md` line 59 at r1](https://reviewable.io/reviews/gramineproject/contrib/44#-NVUPdZl2b5JcpBOWkpY:-NVUPdZl2b5JcpBOWkpZ:b-ealmg3) ([raw file](https://github.com/gramineproject/contrib/blob/297205ce3c1699f80cbf65edf7a092000eb8edb6/Intel-Confidential-Compute-for-X/README.md#L59)):*
> ```Markdown
> - On Premise system:
> 
>     User is expected to have DCAP Remote attestation infrastructure with PCCS setup and system
> ```

`DCAP remote attestation` (no need to capitalize the word `remote`)
___
*[`Intel-Confidential-Compute-for-X/README.md` line 60 at r1](https://reviewable.io/reviews/gramineproject/contrib/44#-NVUP_Bz7kreIBuVC7Fk:-NVUP_Bz7kreIBuVC7Fl:b-naswk7) ([raw file](https://github.com/gramineproject/contrib/blob/297205ce3c1699f80cbf65edf7a092000eb8edb6/Intel-Confidential-Compute-for-X/README.md#L60)):*
> ```Markdown
> 
>     User is expected to have DCAP Remote attestation infrastructure with PCCS setup and system
>     provisioned. Please follow instructions [here](https://www.intel.com/content/www/us/en/developer/articles/guide/intel-software-guard-extensions-data-center-attestation-primitives-quick-install-guide.html) for
> ```

Please rewrap (`for` should be on the next line)
___
*[`Intel-Confidential-Compute-for-X/README.md` line 61 at r1](https://reviewable.io/reviews/gramineproject/contrib/44#-NVUPbp85MELC0prUFvc:-NVUPbp85MELC0prUFvd:bwdunjc) ([raw file](https://github.com/gramineproject/contrib/blob/297205ce3c1699f80cbf65edf7a092000eb8edb6/Intel-Confidential-Compute-for-X/README.md#L61)):*
> ```Markdown
>     User is expected to have DCAP Remote attestation infrastructure with PCCS setup and system
>     provisioned. Please follow instructions [here](https://www.intel.com/content/www/us/en/developer/articles/guide/intel-software-guard-extensions-data-center-attestation-primitives-quick-install-guide.html) for
>     DCAP remote attestation setup
> ```

Add a dot.
___
*[`Intel-Confidential-Compute-for-X/README.md` line 68 at r1](https://reviewable.io/reviews/gramineproject/contrib/44#-NVUPjpT1ZT12AZRA424:-NVUPjpT1ZT12AZRA425:b-kht1t5) ([raw file](https://github.com/gramineproject/contrib/blob/297205ce3c1699f80cbf65edf7a092000eb8edb6/Intel-Confidential-Compute-for-X/README.md#L68)):*
> ```Markdown
>     sudo apt-get update && sudo apt-get install -y docker.io
>     sudo chown $USER /var/run/docker.sock
>     # Below commands are specific to ubuntu 20.04. Please see instructions under
> ```

`Ubuntu` (capitalize)
___
*[`Intel-Confidential-Compute-for-X/README.md` line 75 at r1](https://reviewable.io/reviews/gramineproject/contrib/44#-NVUPnl-2lnF9u4IcCJT:-NVUPnl-2lnF9u4IcCJU:bsll5lh) ([raw file](https://github.com/gramineproject/contrib/blob/297205ce3c1699f80cbf65edf7a092000eb8edb6/Intel-Confidential-Compute-for-X/README.md#L75)):*
> ```Markdown
>         sudo apt-key add -
>     sudo apt-get install -y -f libsgx-dcap-ql libsgx-dcap-default-qpl=1.16.100.2-focal1
>     # Execute below command (only on Azure VM) to changes PCCS_URL to Azure PCCS
> ```

`to changes` -> `to change`
___
*[`Intel-Confidential-Compute-for-X/keys/microsoft.asc` line 0 at r1](https://reviewable.io/reviews/gramineproject/contrib/44#-NVUPyns-nf24dwguP58:-NVUPyns-nf24dwguP59:b6yhgn9) ([raw file](https://github.com/gramineproject/contrib/blob/297205ce3c1699f80cbf65edf7a092000eb8edb6/Intel-Confidential-Compute-for-X/keys/microsoft.asc#L0)):*
Why don't you need this key anymore?
___
*[`Intel-Confidential-Compute-for-X/verifier/verifier.dockerfile.template` line 22 at r1](https://reviewable.io/reviews/gramineproject/contrib/44#-NVUQLuhE6fx-CfNf6c9:-NVUQLuhE6fx-CfNf6cA:b-3uya39) ([raw file](https://github.com/gramineproject/contrib/blob/f277f77e96f240ac8d2cd51404e6a13d5f1248c8/Intel-Confidential-Compute-for-X/verifier/verifier.dockerfile.template#L22)):*
> ```
> # latest package.
> RUN echo "deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft.asc] https://packages.microsoft.com/ubuntu/20.04/prod focal main" \
>     | tee /etc/apt/sources.list.d/msprod.list
> ```

Why don't you need to install `az-dcap-client`?

How do you preserve Azure VM deployments with this PR? Looks like you're replacing all Azure-specific stuff with bare-metal stuff? How can the user switch between Azure VM usage and the non-VM usage?


<!-- Sent from Reviewable.io -->

2023-06-21 10:34 UTC, dimakuv requested changes
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/44)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @jkr0103)

___
*[`Intel-Confidential-Compute-for-X/keys/microsoft.asc` line  at r1](https://reviewable.io/reviews/gramineproject/contrib/44#-NVUPyns-nf24dwguP58:-NYSVa3q02q1vTbfEFvY:b2u9zyx) ([raw file](https://github.com/gramineproject/contrib/blob/297205ce3c1699f80cbf65edf7a092000eb8edb6/Intel-Confidential-Compute-for-X/keys/microsoft.asc#L)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

That key was required for installing `az-dcap-client` but we don't need to install it now as we have generic verifier which uses `libsgx-dcap-default-qpl` and eliminates the need of `az-dcap-client` and work on Azure VMs as well as on Bare-metal systems.
</blockquote></details>

Nice, thanks for explanation. Indeed, `az-dcap-client` is deprecated now.
___
*[`Intel-Confidential-Compute-for-X/verifier/ca_config.conf` line 15 at r2](https://reviewable.io/reviews/gramineproject/contrib/44#-NYSW3hL4tXcCHsTAcgn:-NYSW3hL4tXcCHsTAcgo:bjm6uzf) ([raw file](https://github.com/gramineproject/contrib/blob/99c1fea1f9a756530df8fe4a6a4266cdce15c1e4/Intel-Confidential-Compute-for-X/verifier/ca_config.conf#L15)):*
> ```
> organizationalUnitName = "Department"     # OU=
> commonName             = "localhost"      # CN=
> emailAddress           = "me@example.com" # email
> ```

Actually, why do you have this totally dummy config for the auto-generated server cert? Don't you want to have a more specific one? Or is it the responsibility of the user to update the fields here (especially the `CN` field)? Or is it purely for demo purposes?


<!-- Sent from Reviewable.io -->

2023-06-21 10:37 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/44)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @jkr0103)

___
*[`Intel-Confidential-Compute-for-X/README.md` line 65 at r2](https://reviewable.io/reviews/gramineproject/contrib/44#-NYSWW_M7RknSZq9DQhP:-NYSWW_M7RknSZq9DQhQ:b63k5gf) ([raw file](https://github.com/gramineproject/contrib/blob/99c1fea1f9a756530df8fe4a6a4266cdce15c1e4/Intel-Confidential-Compute-for-X/README.md#L65)):*
> ```Markdown
> #### Install the necessary build dependencies:
> 
>     ```sh
> ```

You either don't need the indentation here, or you don't need the triple backticks. See how incorrectly it renders currently: https://github.com/jkr0103/contrib/tree/jkr0103/generic_verifier/Intel-Confidential-Compute-for-X#install-the-necessary-build-dependencies
___
*[`Intel-Confidential-Compute-for-X/README.md` line 69 at r2](https://reviewable.io/reviews/gramineproject/contrib/44#-NYSWk4FBMyMbCgzp3v4:-NYSWk4FBMyMbCgzp3v5:b86rwwh) ([raw file](https://github.com/gramineproject/contrib/blob/99c1fea1f9a756530df8fe4a6a4266cdce15c1e4/Intel-Confidential-Compute-for-X/README.md#L69)):*
> ```Markdown
>     sudo chown $USER /var/run/docker.sock
>     # Below commands are specific to Ubuntu 20.04. Please see instructions under
>     # `Intel® SGX Application User` in document [here](https://download.01.org/intel-sgx/latest/dcap-latest/linux/docs/Intel_SGX_SW_Installation_Guide_for_Linux.pdf)
> ```

The link doesn't work as you wanted (it is not Markdown rendered because you're in the code snippet)
___
*[`Intel-Confidential-Compute-for-X/README.md` line 76 at r2](https://reviewable.io/reviews/gramineproject/contrib/44#-NYSWflJADT6p8LvNMM8:-NYSWflJADT6p8LvNMM9:b-89dpbn) ([raw file](https://github.com/gramineproject/contrib/blob/99c1fea1f9a756530df8fe4a6a4266cdce15c1e4/Intel-Confidential-Compute-for-X/README.md#L76)):*
> ```Markdown
>     sudo apt-get install -y -f libsgx-dcap-ql libsgx-dcap-default-qpl=1.16.100.2-focal1
>     # Execute below command (only on Azure VM) to change PCCS_URL to Azure PCCS
>     sudo sed -i "s|^\(  \"pccs_url\": \"https://\).*\(/sgx/certification.*\)|\1global.acccache.azure.net\2|g" /etc/sgx_default_qcnl.conf
> ```

Could you add empty lines in-between these commands? It's hard to read.
___
*[`Intel-Confidential-Compute-for-X/README.md` line 76 at r2](https://reviewable.io/reviews/gramineproject/contrib/44#-NYSWqnK1duOsz0UE6ds:-NYSWqnK1duOsz0UE6dt:b-4l55q4) ([raw file](https://github.com/gramineproject/contrib/blob/99c1fea1f9a756530df8fe4a6a4266cdce15c1e4/Intel-Confidential-Compute-for-X/README.md#L76)):*
> ```Markdown
>     sudo apt-get install -y -f libsgx-dcap-ql libsgx-dcap-default-qpl=1.16.100.2-focal1
>     # Execute below command (only on Azure VM) to change PCCS_URL to Azure PCCS
>     sudo sed -i "s|^\(  \"pccs_url\": \"https://\).*\(/sgx/certification.*\)|\1global.acccache.azure.net\2|g" /etc/sgx_default_qcnl.conf
> ```

This command is very long, it is not nicely rendered. Can you split into two lines?


<!-- Sent from Reviewable.io -->

2023-07-17 07:21 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/44)* status: 5 of 8 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`Intel-Confidential-Compute-for-X/README.md` line 65 at r2](https://reviewable.io/reviews/gramineproject/contrib/44#-NYSWW_M7RknSZq9DQhP:-N_Xh-EY4SSx5IrD2DNw:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/99c1fea1f9a756530df8fe4a6a4266cdce15c1e4/Intel-Confidential-Compute-for-X/README.md#L65)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You either don't need the indentation here, or you don't need the triple backticks. See how incorrectly it renders currently: https://github.com/jkr0103/contrib/tree/jkr0103/generic_verifier/Intel-Confidential-Compute-for-X#install-the-necessary-build-dependencies
</blockquote></details>

Done.
___
*[`Intel-Confidential-Compute-for-X/README.md` line 69 at r2](https://reviewable.io/reviews/gramineproject/contrib/44#-NYSWk4FBMyMbCgzp3v4:-N_Xh2R-9IkDcfWVfLXJ:biwvmji) ([raw file](https://github.com/gramineproject/contrib/blob/99c1fea1f9a756530df8fe4a6a4266cdce15c1e4/Intel-Confidential-Compute-for-X/README.md#L69)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The link doesn't work as you wanted (it is not Markdown rendered because you're in the code snippet)
</blockquote></details>

moved it up
___
*[`Intel-Confidential-Compute-for-X/README.md` line 76 at r2](https://reviewable.io/reviews/gramineproject/contrib/44#-NYSWflJADT6p8LvNMM8:-N_Xh4V41IxmPk8JGD9q:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/99c1fea1f9a756530df8fe4a6a4266cdce15c1e4/Intel-Confidential-Compute-for-X/README.md#L76)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you add empty lines in-between these commands? It's hard to read.
</blockquote></details>

Done.
___
*[`Intel-Confidential-Compute-for-X/README.md` line 76 at r2](https://reviewable.io/reviews/gramineproject/contrib/44#-NYSWqnK1duOsz0UE6ds:-N_Xh5ZV8gkgNAkjuhld:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/99c1fea1f9a756530df8fe4a6a4266cdce15c1e4/Intel-Confidential-Compute-for-X/README.md#L76)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This command is very long, it is not nicely rendered. Can you split into two lines?
</blockquote></details>

Done.
___
*[`Intel-Confidential-Compute-for-X/verifier/ca_config.conf` line 15 at r2](https://reviewable.io/reviews/gramineproject/contrib/44#-NYSW3hL4tXcCHsTAcgn:-N_Xh9r390-86soFG8nZ:b-b90bgs) ([raw file](https://github.com/gramineproject/contrib/blob/99c1fea1f9a756530df8fe4a6a4266cdce15c1e4/Intel-Confidential-Compute-for-X/verifier/ca_config.conf#L15)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Actually, why do you have this totally dummy config for the auto-generated server cert? Don't you want to have a more specific one? Or is it the responsibility of the user to update the fields here (especially the `CN` field)? Or is it purely for demo purposes?
</blockquote></details>

This is used only when we use  `test` option for Remote attestation which uses test certs. This file is copied from `gramine/CI-Examples/ra-tls-secret-prov/ssl/ca_config.conf`. Earlier we were generating tests certs from `ra-tls-secret-prov` example and using here. Hence I feel we don't have to change this file as it's used only for test usage.


<!-- Sent from Reviewable.io -->

2023-07-17 08:04 UTC, dimakuv requested changes
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/44)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @jkr0103)

___
*[`Intel-Confidential-Compute-for-X/README.md` line 65 at r3](https://reviewable.io/reviews/gramineproject/contrib/44#-N_XrhVM3j6WqBj79tfe:-N_XrhVM3j6WqBj79tff:b1r204h) ([raw file](https://github.com/gramineproject/contrib/blob/c311ad49480d9162d9d5fc28ec580c1effbff76b/Intel-Confidential-Compute-for-X/README.md#L65)):*
> ```Markdown
> #### Install the necessary build dependencies:
> 
>   Below commands are specific to Ubuntu 20.04. Please follow the instructions under
> ```

What's the reason for the 2-space indentation? Please remove everywhere in this sub-section (including in the code snippet with triple backticks)
___
*[`Intel-Confidential-Compute-for-X/README.md` line 66 at r3](https://reviewable.io/reviews/gramineproject/contrib/44#-N_XrlXHACTlcPtS0qnQ:-N_XrlXHACTlcPtS0qnR:b-l3jb6v) ([raw file](https://github.com/gramineproject/contrib/blob/c311ad49480d9162d9d5fc28ec580c1effbff76b/Intel-Confidential-Compute-for-X/README.md#L66)):*
> ```Markdown
> 
>   Below commands are specific to Ubuntu 20.04. Please follow the instructions under
>   `"Intel® SGX Application User"` section in document [here](https://download.01.org/intel-sgx/latest/dcap-latest/linux/docs/Intel_SGX_SW_Installation_Guide_for_Linux.pdf) for other distro specific commands.
> ```

Please split into 100-chars-per-line
___
*[`Intel-Confidential-Compute-for-X/README.md` line 80 at r3](https://reviewable.io/reviews/gramineproject/contrib/44#-N_Xrxn8B9qv1pZOTJA1:-N_Xrxn8B9qv1pZOTJA2:b-dkpf8a) ([raw file](https://github.com/gramineproject/contrib/blob/c311ad49480d9162d9d5fc28ec580c1effbff76b/Intel-Confidential-Compute-for-X/README.md#L80)):*
> ```Markdown
>   # Execute below command (only on Azure VM) to change PCCS_URL to Azure PCCS
>   sudo sed -i "s|^\(  \"pccs_url\": \"https://\).*\(/sgx/certification.*\)|\1global.acccache.azure.net\2|g" \
>   /etc/sgx_default_qcnl.conf
> ```

Please add 4 spaces for this "continuation of command on previous line", just like you did with other places.
___
*[`Intel-Confidential-Compute-for-X/verifier/ca_config.conf` line 15 at r2](https://reviewable.io/reviews/gramineproject/contrib/44#-NYSW3hL4tXcCHsTAcgn:-N_XsHYn4oJ87bMaWrbV:b32w1t) ([raw file](https://github.com/gramineproject/contrib/blob/99c1fea1f9a756530df8fe4a6a4266cdce15c1e4/Intel-Confidential-Compute-for-X/verifier/ca_config.conf#L15)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

This is used only when we use  `test` option for Remote attestation which uses test certs. This file is copied from `gramine/CI-Examples/ra-tls-secret-prov/ssl/ca_config.conf`. Earlier we were generating tests certs from `ra-tls-secret-prov` example and using here. Hence I feel we don't have to change this file as it's used only for test usage.
</blockquote></details>

Ok


<!-- Sent from Reviewable.io -->

2023-07-17 10:06 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/44)* status: 7 of 8 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`Intel-Confidential-Compute-for-X/README.md` line 65 at r3](https://reviewable.io/reviews/gramineproject/contrib/44#-N_XrhVM3j6WqBj79tfe:-N_YIuyrEY4MHPkQMcKm:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/c311ad49480d9162d9d5fc28ec580c1effbff76b/Intel-Confidential-Compute-for-X/README.md#L65)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What's the reason for the 2-space indentation? Please remove everywhere in this sub-section (including in the code snippet with triple backticks)
</blockquote></details>

Done.
___
*[`Intel-Confidential-Compute-for-X/README.md` line 66 at r3](https://reviewable.io/reviews/gramineproject/contrib/44#-N_XrlXHACTlcPtS0qnQ:-N_YIwvOBDppVGFUZLK2:b96leq4) ([raw file](https://github.com/gramineproject/contrib/blob/c311ad49480d9162d9d5fc28ec580c1effbff76b/Intel-Confidential-Compute-for-X/README.md#L66)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please split into 100-chars-per-line
</blockquote></details>

Splitted after link as link cannot be split.
___
*[`Intel-Confidential-Compute-for-X/README.md` line 80 at r3](https://reviewable.io/reviews/gramineproject/contrib/44#-N_Xrxn8B9qv1pZOTJA1:-N_YJ9Y_DNHDcFkIkdgE:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/c311ad49480d9162d9d5fc28ec580c1effbff76b/Intel-Confidential-Compute-for-X/README.md#L80)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add 4 spaces for this "continuation of command on previous line", just like you did with other places.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-07-17 10:48 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/44)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

___
*[`Intel-Confidential-Compute-for-X/README.md` line 66 at r3](https://reviewable.io/reviews/gramineproject/contrib/44#-N_XrlXHACTlcPtS0qnQ:-N_YSZoa-q0YbFvyWb_7:bs5ed97) ([raw file](https://github.com/gramineproject/contrib/blob/c311ad49480d9162d9d5fc28ec580c1effbff76b/Intel-Confidential-Compute-for-X/README.md#L66)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

Splitted after link as link cannot be split.
</blockquote></details>

Yes, that's what I meant.


<!-- Sent from Reviewable.io -->

2023-07-23 22:50 UTC, mkow approved these changes
> Reviewed 3 of 8 files at r1, 2 of 3 files at r2, 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/44)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-07-23 22:51 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/44)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @jkr0103)

___
*[`Intel-Confidential-Compute-for-X/curate.py` line 473 at r4](https://reviewable.io/reviews/gramineproject/contrib/44#-Na3w_tAAOO_741l0gTV:-Na3w_tAAOO_741l0gTW:b85lz3o) ([raw file](https://github.com/gramineproject/contrib/blob/f32f89002c056faa68db3f5419183c1ca863af8d/Intel-Confidential-Compute-for-X/curate.py#L473)):*
> ```Python
>         # RA_TLS_ALLOW_OUTDATED_TCB_INSECURE only when attestation_input is `test` after
>         # gramine v1.5 release
>         verifier_env_vars = ' -e RA_TLS_ALLOW_OUTDATED_TCB_INSECURE=1 '
> ```

Why are you ignoring a security warning by default?
Btw. 1.5 was already released.


<!-- Sent from Reviewable.io -->

2023-07-24 00:13 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/44)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`Intel-Confidential-Compute-for-X/curate.py` line 473 at r4](https://reviewable.io/reviews/gramineproject/contrib/44#-Na3w_tAAOO_741l0gTV:-Na49Vpm109fjk09_xj3:b-rjho10) ([raw file](https://github.com/gramineproject/contrib/blob/f32f89002c056faa68db3f5419183c1ca863af8d/Intel-Confidential-Compute-for-X/curate.py#L473)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why are you ignoring a security warning by default?
Btw. 1.5 was already released.
</blockquote></details>

We are not ignoring but warning will still be printed on screen. And I have a separate PR (drafted) which move contrib to use Gramine/GSC v1.5. I already have made this change there. I will submit the PR soon.


<!-- Sent from Reviewable.io -->

2023-07-24 00:15 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/44)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`Intel-Confidential-Compute-for-X/curate.py` line 473 at r4](https://reviewable.io/reviews/gramineproject/contrib/44#-Na3w_tAAOO_741l0gTV:-Na4ElCk8eSKm484Kkck:b8rwcwf) ([raw file](https://github.com/gramineproject/contrib/blob/f32f89002c056faa68db3f5419183c1ca863af8d/Intel-Confidential-Compute-for-X/curate.py#L473)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

We are not ignoring but warning will still be printed on screen. And I have a separate PR (drafted) which move contrib to use Gramine/GSC v1.5. I already have made this change there. I will submit the PR soon.
</blockquote></details>

Gramine PR https://github.com/gramineproject/gramine/pull/1286 introduces new set of evnvironment variables for these kind of warnings.


<!-- Sent from Reviewable.io -->

2023-07-24 07:46 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/44)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @jkr0103)

___
*[`Intel-Confidential-Compute-for-X/curate.py` line 473 at r4](https://reviewable.io/reviews/gramineproject/contrib/44#-Na3w_tAAOO_741l0gTV:-Na5qi7hDP669DdAn4Aa:b-el1u5t) ([raw file](https://github.com/gramineproject/contrib/blob/f32f89002c056faa68db3f5419183c1ca863af8d/Intel-Confidential-Compute-for-X/curate.py#L473)):*
> We are not ignoring but warning will still be printed on screen.

But the attestation will still pass, and you added this as the default. IMO no insecure option should be enabled by default.

> Gramine PR #1286 introduces new set of evnvironment variables for these kind of warnings.

I know, I reviewed it and merged myself ;)


<!-- Sent from Reviewable.io -->

2023-07-24 12:58 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/44)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`Intel-Confidential-Compute-for-X/curate.py` line 473 at r4](https://reviewable.io/reviews/gramineproject/contrib/44#-Na3w_tAAOO_741l0gTV:-Na6yWl88nLA2liT-45n:b-3bglt6) ([raw file](https://github.com/gramineproject/contrib/blob/f32f89002c056faa68db3f5419183c1ca863af8d/Intel-Confidential-Compute-for-X/curate.py#L473)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> We are not ignoring but warning will still be printed on screen.

But the attestation will still pass, and you added this as the default. IMO no insecure option should be enabled by default.

> Gramine PR #1286 introduces new set of evnvironment variables for these kind of warnings.

I know, I reviewed it and merged myself ;)
</blockquote></details>

@jkr0103 Can you move Curated Apps to v1.5 of Gramine, so that we merged the "move-to-v1.5" PR first and then we can modify this PR to use a good envvar?


<!-- Sent from Reviewable.io -->

2023-07-25 06:16 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/44)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`Intel-Confidential-Compute-for-X/curate.py` line 473 at r4](https://reviewable.io/reviews/gramineproject/contrib/44#-Na3w_tAAOO_741l0gTV:-NaAg5np5oPSadWACmrX:brb3jbo) ([raw file](https://github.com/gramineproject/contrib/blob/f32f89002c056faa68db3f5419183c1ca863af8d/Intel-Confidential-Compute-for-X/curate.py#L473)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@jkr0103 Can you move Curated Apps to v1.5 of Gramine, so that we merged the "move-to-v1.5" PR first and then we can modify this PR to use a good envvar?
</blockquote></details>

Create PR https://github.com/gramineproject/contrib/pull/52 for moving Curated-Apps to v1.5 of Gramine


<!-- Sent from Reviewable.io -->

2023-07-27 00:05 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/44)* status: 4 of 8 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`Intel-Confidential-Compute-for-X/curate.py` line 473 at r4](https://reviewable.io/reviews/gramineproject/contrib/44#-Na3w_tAAOO_741l0gTV:-NaJe2Yh3taH_7BL-JKQ:bu6h1xw) ([raw file](https://github.com/gramineproject/contrib/blob/f32f89002c056faa68db3f5419183c1ca863af8d/Intel-Confidential-Compute-for-X/curate.py#L473)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

Create PR https://github.com/gramineproject/contrib/pull/52 for moving Curated-Apps to v1.5 of Gramine
</blockquote></details>

Curated-Apps moved to v1.5 of Gramine and hence we have new env variable `RA_TLS_ALLOW_SW_HARDENING_NEEDED` available now and used it here.


<!-- Sent from Reviewable.io -->

2023-07-27 11:04 UTC, dimakuv approved these changes
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/44)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2023-07-30 14:56 UTC, mkow approved these changes
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/44)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-08-01 02:04 UTC, kailun-qin approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/44)* status: all files reviewed, 3 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @jkr0103)

___
*[`Intel-Confidential-Compute-for-X/util/constants.py` line 29 at r5](https://reviewable.io/reviews/gramineproject/contrib/44#-Naifz595BSTbmAGOHBE:-Naifz595BSTbmAGOHBF:b-355id5) ([raw file](https://github.com/gramineproject/contrib/blob/9769d5826980b01789c2f9ba7c6cddbc63b1ada6/Intel-Confidential-Compute-for-X/util/constants.py#L29)):*
> ```Python
>                    ' used in production\n')
> 
> test_run_instr = ('Run the {} docker image in a SGX enabled'
> ```

nit: an



_Code quote:_
```Python
a
```
___
*[`Intel-Confidential-Compute-for-X/util/constants.py` line 49 at r5](https://reviewable.io/reviews/gramineproject/contrib/44#-Naig0n7DObNYuZj5tjD:-Naig0n7DObNYuZj5tjE:b-7ropln) ([raw file](https://github.com/gramineproject/contrib/blob/9769d5826980b01789c2f9ba7c6cddbc63b1ada6/Intel-Confidential-Compute-for-X/util/constants.py#L49)):*
> ```Python
>                 'Press CTRL+G to get started!']
> 
> index = ['The target deployment environment is assumed to be a SGX enabled system'
> ```

ditto



_Code quote:_
```Python
a
```
___
*[`Intel-Confidential-Compute-for-X/util/constants.py` line 136 at r5](https://reviewable.io/reviews/gramineproject/contrib/44#-NaigL9tCrT8QGdagGNk:-NaigL9tCrT8QGdagGNl:b-7ropln) ([raw file](https://github.com/gramineproject/contrib/blob/9769d5826980b01789c2f9ba7c6cddbc63b1ada6/Intel-Confidential-Compute-for-X/util/constants.py#L136)):*
> ```Python
> wait_message = ['Image Creation:', 'Your Gramine Shielded Container image is being created.'
>                 ' This might take a few minutes.']
> system_config_message = ['System config by default is assumed to be a SGX enabled system.']
> ```

ditto



_Code quote:_
```Python
a
```


<!-- Sent from Reviewable.io -->

2023-08-01 02:12 UTC, kailun-qin requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/44)* status: all files reviewed, 4 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @jkr0103)

___
*[`Intel-Confidential-Compute-for-X/verifier/helper.sh` line 10 at r5](https://reviewable.io/reviews/gramineproject/contrib/44#-Naiq4aF6Ytd-UoVg91S:-Naiq4aF6Ytd-UoVg91T:b-iadyoj) ([raw file](https://github.com/gramineproject/contrib/blob/9769d5826980b01789c2f9ba7c6cddbc63b1ada6/Intel-Confidential-Compute-for-X/verifier/helper.sh#L10)):*
> ```Shell
> # The input parameters in sequence are below:
> # -- arg1    : 'done' means user provided his own certs in verifier/ssl directory or
> #              'test' means non-production ready certs will be used.
> ```

Sorry I'm a bit confused -- how is this change reflected in the script? What about `"$1" = ""` then?



_Code quote:_
```Shell
'test' means
```


<!-- Sent from Reviewable.io -->

2023-08-01 02:21 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/44)* status: all files reviewed, 5 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @jkr0103)

___
*[`Intel-Confidential-Compute-for-X/curate.py` line 502 at r5](https://reviewable.io/reviews/gramineproject/contrib/44#-Naisj6l1Mfkgsc4478t:-Naisj6l1Mfkgsc4478u:btspg0s) ([raw file](https://github.com/gramineproject/contrib/blob/1fb5d6bac050c32aefd052b471874e621937d786/Intel-Confidential-Compute-for-X/curate.py#L502)):*
> ```Python
>     if attestation_required == 'y':
>         debug_enclave_env_ver_ext = ''
>         if config == 'test' or debug_flag == 'y':
> ```

What about `config == 'test'`? And in your previous revision, you also had a FIXME -- "use `RA_TLS_ALLOW_OUTDATED_TCB_INSECURE` only when attestation_input is `test`".



_Code quote:_
```Python
config == 'test'
```


<!-- Sent from Reviewable.io -->

2023-08-01 07:49 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/44)* status: 6 of 8 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, and @mkow)

___
*[`Intel-Confidential-Compute-for-X/curate.py` line 502 at r5](https://reviewable.io/reviews/gramineproject/contrib/44#-Naisj6l1Mfkgsc4478t:-Nak3Z52E2N0y7qVqsxm:bz5pnla) ([raw file](https://github.com/gramineproject/contrib/blob/1fb5d6bac050c32aefd052b471874e621937d786/Intel-Confidential-Compute-for-X/curate.py#L502)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

What about `config == 'test'`? And in your previous revision, you also had a FIXME -- "use `RA_TLS_ALLOW_OUTDATED_TCB_INSECURE` only when attestation_input is `test`".
</blockquote></details>

discussed with team internally and are ok to add `RA_TLS_ALLOW_OUTDATED_TCB_INSECURE` if `Attestation Input` is `test`.
___
*[`Intel-Confidential-Compute-for-X/util/constants.py` line 49 at r5](https://reviewable.io/reviews/gramineproject/contrib/44#-Naig0n7DObNYuZj5tjD:-Nak2nCx8sV1ztjuYYDc:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/9769d5826980b01789c2f9ba7c6cddbc63b1ada6/Intel-Confidential-Compute-for-X/util/constants.py#L49)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`Intel-Confidential-Compute-for-X/util/constants.py` line 136 at r5](https://reviewable.io/reviews/gramineproject/contrib/44#-NaigL9tCrT8QGdagGNk:-Nak2nn31WkefRMcyOO9:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/9769d5826980b01789c2f9ba7c6cddbc63b1ada6/Intel-Confidential-Compute-for-X/util/constants.py#L136)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`Intel-Confidential-Compute-for-X/verifier/helper.sh` line 10 at r5](https://reviewable.io/reviews/gramineproject/contrib/44#-Naiq4aF6Ytd-UoVg91S:-Nak2uZ377Z_qTXmqzzL:b-2ywxbg) ([raw file](https://github.com/gramineproject/contrib/blob/9769d5826980b01789c2f9ba7c6cddbc63b1ada6/Intel-Confidential-Compute-for-X/verifier/helper.sh#L10)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Sorry I'm a bit confused -- how is this change reflected in the script? What about `"$1" = ""` then?
</blockquote></details>

`$1` will be either `done` or `test`. With `Remote Attestation input` as test, we create test certificates and use it, here `else` block handle that scenario. `done` user input means use have provided his certificates.


<!-- Sent from Reviewable.io -->

2023-08-01 07:53 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/44)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)



<!-- Sent from Reviewable.io -->

2023-08-01 08:26 UTC, kailun-qin approved these changes
> Reviewed 3 of 8 files at r1, 1 of 1 files at r4, 2 of 4 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/44)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-08-02 10:05 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/44)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2023-08-02 10:45 UTC, kailun-qin approved these changes
> Reviewed 2 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/44)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2023-08-02 13:24 UTC, mkow approved these changes
> Reviewed 1 of 2 files at r6, 2 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/44)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-08-02 13:35 UTC, merged