[Curated-Apps] Add OpenVINO Model Server
gramineproject/contrib pull request #46
Opened 2023-06-08 10:48 UTC by sahason

Curate OpenVINO Model Server.

2023-07-24 14:21 UTC, dimakuv requested changes
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/46)* status: all files reviewed, 33 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @sahason)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/46#-Na7EVWPE0WGq8lSCRmz:-Na7EVWQ8oRGPrKTM-2a:bh74mzn) (no related file):*
Aren't you supposed to add the OpenVINO item in the list in the top-level README?

___
___
*[`Intel-Confidential-Compute-for-X/util/curation_script.sh` line 201 at r1](https://reviewable.io/reviews/gramineproject/contrib/46#-Na7A85t27QhXvmxzwb5:-Na7A85t27QhXvmxzwb6:bj2ea31) ([raw file](https://github.com/gramineproject/contrib/blob/defaeba250af828823f6ddf39f2e6660228b576d/Intel-Confidential-Compute-for-X/util/curation_script.sh#L201)):*
> ```Shell
> 	sed -i "s|\(loader.env.LD_PRELOAD = .*\)\"|\1:/gramine/meson_build_output/lib/x86_64-linux-gnu/libsecret_prov_attest.so\"|g" \
>             $app_image_manifest
>     fi
> ```

This is a change to the main logic of the Curation script. It must not be in this PR. Please separate it into a new PR.

@jkr0103 Could you do it? You're the main author of the Curation script, and I will trust your modifications more.

If I understand correctly, this change is required to NOT overwrite the `LD_PRELOAD` variable, but to concatenate the two parts: the common part (with `libsecret_prov_attest.so`) and the workload-specific part.

I highly dislike the current hack... Why does this workload need `LD_PRELOAD` at all? See my other comment.
___
*[`Intel-Confidential-Compute-for-X/workloads/openvino-model-server/.gitignore` line 5 at r1](https://reviewable.io/reviews/gramineproject/contrib/46#-Na7B_ETDenI-ziKbAXM:-Na7B_ETDenI-ziKbAXN:b-iofwn3) ([raw file](https://github.com/gramineproject/contrib/blob/defaeba250af828823f6ddf39f2e6660228b576d/Intel-Confidential-Compute-for-X/workloads/openvino-model-server/.gitignore#L5)):*
> ```ignore
> /openvino-model-server.manifest
> /models
> ```

Please remove the empty line
___
*[`Intel-Confidential-Compute-for-X/workloads/openvino-model-server/docker_run_flags.txt` line 1 at r1](https://reviewable.io/reviews/gramineproject/contrib/46#-Na7BvWN8DV9FXRbAs6e:-Na7BvWN8DV9FXRbAs6f:b-tmwh94) ([raw file](https://github.com/gramineproject/contrib/blob/defaeba250af828823f6ddf39f2e6660228b576d/Intel-Confidential-Compute-for-X/workloads/openvino-model-server/docker_run_flags.txt#L1)):*
> ```help
> -u 0:0 -p 9000:9000 -v /var/run/model_encrypted:/var/run/model_encrypted
> ```

What's the deal with `-u 0:0`? Does it mean that the Docker container will run with root privileges on the host? Why?
___
*[`Intel-Confidential-Compute-for-X/workloads/openvino-model-server/insecure_args.txt` line 1 at r1](https://reviewable.io/reviews/gramineproject/contrib/46#-Na7CCvODXX0MFSZVp-E:-Na7CCvODXX0MFSZVp-F:bvbsqaj) ([raw file](https://github.com/gramineproject/contrib/blob/defaeba250af828823f6ddf39f2e6660228b576d/Intel-Confidential-Compute-for-X/workloads/openvino-model-server/insecure_args.txt#L1)):*
> ```help
> --model_path /var/run/model_encrypted --model_name face-detection --port 9000 --plugin_config '{"CPU_THROUGHPUT_STREAMS": "1"}' --shape auto
> ```

What's this `CPU_THROUGHPUT_STREAMS`? Why is it set to 1?
___
*[`Intel-Confidential-Compute-for-X/workloads/openvino-model-server/openvino-model-server-gsc.dockerfile.template` line 5 at r1](https://reviewable.io/reviews/gramineproject/contrib/46#-Na7CHZj1kEWyxAQ11WX:-Na7CHZj1kEWyxAQ11WY:b-yzdick) ([raw file](https://github.com/gramineproject/contrib/blob/defaeba250af828823f6ddf39f2e6660228b576d/Intel-Confidential-Compute-for-X/workloads/openvino-model-server/openvino-model-server-gsc.dockerfile.template#L5)):*
> ```
> 
> # This template is used by `curation_script.sh` to create a wrapper dockerfile
> # `mysql-gsc.dockerfile` that includes user provided inputs e.g. `ca.cert` file etc.
> ```

`MySQL`? Please fix it to OpenVINO everywhere in this PR.
___
*[`Intel-Confidential-Compute-for-X/workloads/openvino-model-server/openvino-model-server.manifest.template` line 4 at r1](https://reviewable.io/reviews/gramineproject/contrib/46#-Na7CSEd5ejKolOQF5Fu:-Na7CSEd5ejKolOQF5Fv:bbvr2wk) ([raw file](https://github.com/gramineproject/contrib/blob/defaeba250af828823f6ddf39f2e6660228b576d/Intel-Confidential-Compute-for-X/workloads/openvino-model-server/openvino-model-server.manifest.template#L4)):*
> ```
> # Copyright (C) 2023 Intel Corporation
> 
> # This file has basic set of values defined for graminizing mysql images. This manifest template
> ```

ditto (MySQL)
___
*[`Intel-Confidential-Compute-for-X/workloads/openvino-model-server/openvino-model-server.manifest.template` line 7 at r1](https://reviewable.io/reviews/gramineproject/contrib/46#-Na7CUaj-KEj8I16Xt_k:-Na7CUaj-KEj8I16Xt_l:brxuidk) ([raw file](https://github.com/gramineproject/contrib/blob/defaeba250af828823f6ddf39f2e6660228b576d/Intel-Confidential-Compute-for-X/workloads/openvino-model-server/openvino-model-server.manifest.template#L7)):*
> ```
> # is used by `curation_script.sh` to create the user manifest file that will be passed to GSC.
> 
> sgx.nonpie_binary = true
> ```

This is not required starting from Gramine v1.3, so just remove this line.
___
*[`Intel-Confidential-Compute-for-X/workloads/openvino-model-server/openvino-model-server.manifest.template` line 21 at r1](https://reviewable.io/reviews/gramineproject/contrib/46#-Na7C_0O1AwUltoA20J0:-Na7C_0O1AwUltoA20J1:bqxafhm) ([raw file](https://github.com/gramineproject/contrib/blob/defaeba250af828823f6ddf39f2e6660228b576d/Intel-Confidential-Compute-for-X/workloads/openvino-model-server/openvino-model-server.manifest.template#L21)):*
> ```
> ]
> 
> loader.env.LD_PRELOAD = "/ovms/lib/libazurestorage.so:/ovms/lib/libcpprest.so:/ovms/lib/libopenvino.so:/ovms/lib/libopencv_core.so:/ovms/lib/libopencv_imgcodecs.so:/ovms/lib/libopencv_imgproc.so:/ovms/lib/libopencv_calib3d.so:/ovms/lib/libopencv_features2d.so:/ovms/lib/libopencv_highgui.so:/ovms/lib/libopencv_optflow.so:/ovms/lib/libopencv_video.so:/ovms/lib/libopencv_videoio.so"
> ```

What's the point of all these preloaded libs? Why are they not a part of the normal application? Are you sure this is all needed? What happens if you don't preload them?

If this trick is described in some official documentation, please give us a link.
___
*[`Intel-Confidential-Compute-for-X/workloads/openvino-model-server/README.md` line 28 at r1](https://reviewable.io/reviews/gramineproject/contrib/46#-Na7Ct1jD-QsLezwVfbW:-Na7Ct1jD-QsLezwVfbX:bms2pnu) ([raw file](https://github.com/gramineproject/contrib/blob/defaeba250af828823f6ddf39f2e6660228b576d/Intel-Confidential-Compute-for-X/workloads/openvino-model-server/README.md#L28)):*
> ```Markdown
>    ```
>    mkdir workloads/openvino-model-server/models
>    curl --create-dirs https://storage.openvinotoolkit.org/repositories/open_model_zoo/2022.1/models_bin/2/face-detection-retail-0004/FP32/face-detection-retail-0004.xml https://storage.openvinotoolkit.org/repositories/open_model_zoo/2022.1/models_bin/2/face-detection-retail-0004/FP32/face-detection-retail-0004.bin -o workloads/openvino-model-server/models/1/face-detection-retail-0004.xml -o workloads/openvino-model-server/models/1/face-detection-retail-0004.bin
> ```

Why are we talking about version 2022.1? Isn't it a bit too old now? Can you update to a newer version?

OpenVINO itself seems to be of version 2023.0, which is good to me. So why are the models old? Or there is nothing newer?
___
*[`Intel-Confidential-Compute-for-X/workloads/openvino-model-server/README.md` line 38 at r1](https://reviewable.io/reviews/gramineproject/contrib/46#-Na7CzZ63ZE5CWbsAQ0M:-Na7CzZ63ZE5CWbsAQ0N:b-8jdm6w) ([raw file](https://github.com/gramineproject/contrib/blob/defaeba250af828823f6ddf39f2e6660228b576d/Intel-Confidential-Compute-for-X/workloads/openvino-m [...]

2023-07-24 18:43 UTC, mkow requested changes
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/46)* status: all files reviewed, 38 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @sahason)

___
*[`Intel-Confidential-Compute-for-X/util/curation_script.sh` line 199 at r1](https://reviewable.io/reviews/gramineproject/contrib/46#-Na6-ccU7ToEPI3nRS-I:-Na6-ccU7ToEPI3nRS-J:bql3c1y) ([raw file](https://github.com/gramineproject/contrib/blob/defaeba250af828823f6ddf39f2e6660228b576d/Intel-Confidential-Compute-for-X/util/curation_script.sh#L199)):*
> ```Shell
> 	$app_image_manifest
>     else
> 	sed -i "s|\(loader.env.LD_PRELOAD = .*\)\"|\1:/gramine/meson_build_output/lib/x86_64-linux-gnu/libsecret_prov_attest.so\"|g" \
> ```

tabs -> spaces
Please either configure your text editor to show them or review commits before pushing (ideally, do both).
___
*[`Intel-Confidential-Compute-for-X/workloads/openvino-model-server/.gitignore` line 5 at r1](https://reviewable.io/reviews/gramineproject/contrib/46#-Na6sdRI2QtH3l7nOyZi:-Na6sdRI2QtH3l7nOyZj:bpx6rl9) ([raw file](https://github.com/gramineproject/contrib/blob/defaeba250af828823f6ddf39f2e6660228b576d/Intel-Confidential-Compute-for-X/workloads/openvino-model-server/.gitignore#L5)):*
> ```ignore
> /openvino-model-server.manifest
> /models
> ```

2 newlines?
___
*[`Intel-Confidential-Compute-for-X/workloads/openvino-model-server/openvino-model-server.manifest.template` line 4 at r1](https://reviewable.io/reviews/gramineproject/contrib/46#-Na78keYEkI7cRMZRNJt:-Na78keYEkI7cRMZRNJu:b-n8r9we) ([raw file](https://github.com/gramineproject/contrib/blob/defaeba250af828823f6ddf39f2e6660228b576d/Intel-Confidential-Compute-for-X/workloads/openvino-model-server/openvino-model-server.manifest.template#L4)):*
> ```
> # Copyright (C) 2023 Intel Corporation
> 
> # This file has basic set of values defined for graminizing mysql images. This manifest template
> ```

mysql?
___
*[`Intel-Confidential-Compute-for-X/workloads/openvino-model-server/README.md` line 39 at r1](https://reviewable.io/reviews/gramineproject/contrib/46#-Na8B1YzAMscbhWRURqK:-Na8B1YzAMscbhWRURqL:b-u6x3ub) ([raw file](https://github.com/gramineproject/contrib/blob/defaeba250af828823f6ddf39f2e6660228b576d/Intel-Confidential-Compute-for-X/workloads/openvino-model-server/README.md#L39)):*
> a weak encryption key

Why do you say it's weak?
___
*[`Intel-Confidential-Compute-for-X/workloads/openvino-model-server/base_image_helper/encrypted_files.txt` line 1 at r1](https://reviewable.io/reviews/gramineproject/contrib/46#-Na8CCp55ztSIeh2kFjK:-Na8CCp55ztSIeh2kFjL:ba1y7vc) ([raw file](https://github.com/gramineproject/contrib/blob/defaeba250af828823f6ddf39f2e6660228b576d/Intel-Confidential-Compute-for-X/workloads/openvino-model-server/base_image_helper/encrypted_files.txt#L1)):*
> ```help
> /var/run/model_encrypted
> ```

Why is a system directory used here?


<!-- Sent from Reviewable.io -->

2023-07-26 10:21 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/46)* status: all files reviewed, 38 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @sahason)

___
*[`Intel-Confidential-Compute-for-X/util/curation_script.sh` line 201 at r1](https://reviewable.io/reviews/gramineproject/contrib/46#-Na7A85t27QhXvmxzwb5:-NaGbMM18pA3cso2S9j8:b-jvulx8) ([raw file](https://github.com/gramineproject/contrib/blob/defaeba250af828823f6ddf39f2e6660228b576d/Intel-Confidential-Compute-for-X/util/curation_script.sh#L201)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is a change to the main logic of the Curation script. It must not be in this PR. Please separate it into a new PR.

@jkr0103 Could you do it? You're the main author of the Curation script, and I will trust your modifications more.

If I understand correctly, this change is required to NOT overwrite the `LD_PRELOAD` variable, but to concatenate the two parts: the common part (with `libsecret_prov_attest.so`) and the workload-specific part.

I highly dislike the current hack... Why does this workload need `LD_PRELOAD` at all? See my other comment.
</blockquote></details>

@dimakuv your understanding on concatenation logic is correct. Best approach would have been to use `/ovms/lib` directory with `LD_LIBRARY_PATH` in the manifest but currently GSC restricts us doing so as GSC templates already have `LD_LIBRARY_PATH`.  GSC is missing the concatenation logic. But because of current limitations in GSC, we have to go with `LD_PRELOAD` only.

This PR have to wait again if we create separate PR for this logic. I you still want a separate PR, I can create.


<!-- Sent from Reviewable.io -->

2023-07-26 11:39 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/46)* status: all files reviewed, 38 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @jkr0103 and @sahason)

___
*[`Intel-Confidential-Compute-for-X/util/curation_script.sh` line 201 at r1](https://reviewable.io/reviews/gramineproject/contrib/46#-Na7A85t27QhXvmxzwb5:-NaGzP0EDbALCL9ibNM0:b32f2g0) ([raw file](https://github.com/gramineproject/contrib/blob/defaeba250af828823f6ddf39f2e6660228b576d/Intel-Confidential-Compute-for-X/util/curation_script.sh#L201)):*
> Best approach would have been to use `/ovms/lib` directory with `LD_LIBRARY_PATH` in the manifest but currently GSC restricts us doing so as GSC templates already have `LD_LIBRARY_PATH`.

I would very much prefer this approach. It will make everything simpler.

> This PR have to wait again if we create separate PR for this logic. I you still want a separate PR, I can create.

Yes, I definitely want a separate PR. And as part of that PR, can you do two things: 
1. Concatenate `LD_LIBRARY_PATH` (which can be used then in this PR for simplicity)
2. Concatenate `LD_PRELOAD` (which is currently used in this PR, but may be useful for the future)


<!-- Sent from Reviewable.io -->

2023-07-28 00:10 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/46)* status: all files reviewed, 38 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @sahason)

___
*[`Intel-Confidential-Compute-for-X/workloads/openvino-model-server/openvino-model-server.manifest.template` line 21 at r1](https://reviewable.io/reviews/gramineproject/contrib/46#-Na7C_0O1AwUltoA20J0:-NaOoH5t7rKlarQGQ67A:b-utfj7t) ([raw file](https://github.com/gramineproject/contrib/blob/defaeba250af828823f6ddf39f2e6660228b576d/Intel-Confidential-Compute-for-X/workloads/openvino-model-server/openvino-model-server.manifest.template#L21)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What's the point of all these preloaded libs? Why are they not a part of the normal application? Are you sure this is all needed? What happens if you don't preload them?

If this trick is described in some official documentation, please give us a link.
</blockquote></details>

Please add a comment as below:

```
# FIXME: `LD_PRELOAD` should be replaced with `loader.env.LD_LIBRARY_PATH = "/ovms/lib"` when GSC have the concat logic for `loader.env.LD_LIBRARY_PATH`.
```


<!-- Sent from Reviewable.io -->

2023-07-28 06:58 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/46)* status: all files reviewed, 38 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @jkr0103 and @sahason)

___
*[`Intel-Confidential-Compute-for-X/workloads/openvino-model-server/openvino-model-server.manifest.template` line 21 at r1](https://reviewable.io/reviews/gramineproject/contrib/46#-Na7C_0O1AwUltoA20J0:-NaQHSAe0Xr-odU9fsJC:b-y9w3vl) ([raw file](https://github.com/gramineproject/contrib/blob/defaeba250af828823f6ddf39f2e6660228b576d/Intel-Confidential-Compute-for-X/workloads/openvino-model-server/openvino-model-server.manifest.template#L21)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

Please add a comment as below:

```
# FIXME: `LD_PRELOAD` should be replaced with `loader.env.LD_LIBRARY_PATH = "/ovms/lib"` when GSC have the concat logic for `loader.env.LD_LIBRARY_PATH`.
```
</blockquote></details>

+1 to Jitender's proposal, but also fix a typo in his proposal: `GSC have` -> `GSC has`


<!-- Sent from Reviewable.io -->

2023-08-01 04:57 UTC, sahason reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/46)* status: 2 of 11 files reviewed, 38 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/46#-Na7EVWPE0WGq8lSCRmz:-NaGXK8W1m6oWklh5TB9:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Aren't you supposed to add the OpenVINO item in the list in the top-level README?
</blockquote></details>

Done.

___
___
*[`Intel-Confidential-Compute-for-X/workloads/openvino-model-server/.gitignore` line 5 at r1](https://reviewable.io/reviews/gramineproject/contrib/46#-Na6sdRI2QtH3l7nOyZi:-NaGYCeM8GqkTPOACGAt:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/defaeba250af828823f6ddf39f2e6660228b576d/Intel-Confidential-Compute-for-X/workloads/openvino-model-server/.gitignore#L5)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

2 newlines?
</blockquote></details>

Done.
___
*[`Intel-Confidential-Compute-for-X/workloads/openvino-model-server/.gitignore` line 5 at r1](https://reviewable.io/reviews/gramineproject/contrib/46#-Na7B_ETDenI-ziKbAXM:-NaGY7Vq3DYVvh-ByNn_:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/defaeba250af828823f6ddf39f2e6660228b576d/Intel-Confidential-Compute-for-X/workloads/openvino-model-server/.gitignore#L5)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove the empty line
</blockquote></details>

Done.
___
*[`Intel-Confidential-Compute-for-X/workloads/openvino-model-server/docker_run_flags.txt` line 1 at r1](https://reviewable.io/reviews/gramineproject/contrib/46#-Na7BvWN8DV9FXRbAs6e:-Naj0vKB0n3KPYSTfmiU:b-5ut8zn) ([raw file](https://github.com/gramineproject/contrib/blob/defaeba250af828823f6ddf39f2e6660228b576d/Intel-Confidential-Compute-for-X/workloads/openvino-model-server/docker_run_flags.txt#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What's the deal with `-u 0:0`? Does it mean that the Docker container will run with root privileges on the host? Why?
</blockquote></details>

It was written this way as the model directory had root access. As we moved to tmpfs logic I have replaced it.
___
*[`Intel-Confidential-Compute-for-X/workloads/openvino-model-server/insecure_args.txt` line 1 at r1](https://reviewable.io/reviews/gramineproject/contrib/46#-Na7CCvODXX0MFSZVp-E:-Naj2VeS1b_WsdgIokv6:b-chaaj) ([raw file](https://github.com/gramineproject/contrib/blob/defaeba250af828823f6ddf39f2e6660228b576d/Intel-Confidential-Compute-for-X/workloads/openvino-model-server/insecure_args.txt#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What's this `CPU_THROUGHPUT_STREAMS`? Why is it set to 1?
</blockquote></details>

I have followed the demo described here in official website https://github.com/openvinotoolkit/model_server/blob/main/docs/ovms_quickstart.md to show how it can be enabled in GSC. This is an example where CPU_THROUGHPUT_STREAMS  specifies number of CPU “execution” streams for the throughput mode.
___
*[`Intel-Confidential-Compute-for-X/workloads/openvino-model-server/openvino-model-server-gsc.dockerfile.template` line 5 at r1](https://reviewable.io/reviews/gramineproject/contrib/46#-Na7CHZj1kEWyxAQ11WX:-NaGZPyhDUqrVxueY_SZ:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/defaeba250af828823f6ddf39f2e6660228b576d/Intel-Confidential-Compute-for-X/workloads/openvino-model-server/openvino-model-server-gsc.dockerfile.template#L5)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`MySQL`? Please fix it to OpenVINO everywhere in this PR.
</blockquote></details>

Done.
___
*[`Intel-Confidential-Compute-for-X/workloads/openvino-model-server/openvino-model-server.manifest.template` line 4 at r1](https://reviewable.io/reviews/gramineproject/contrib/46#-Na78keYEkI7cRMZRNJt:-NaGZTQbDWujaQPO6w2S:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/defaeba250af828823f6ddf39f2e6660228b576d/Intel-Confidential-Compute-for-X/workloads/openvino-model-server/openvino-model-server.manifest.template#L4)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

mysql?
</blockquote></details>

Done.
___
*[`Intel-Confidential-Compute-for-X/workloads/openvino-model-server/openvino-model-server.manifest.template` line 4 at r1](https://reviewable.io/reviews/gramineproject/contrib/46#-Na7CSEd5ejKolOQF5Fu:-NaGZRskExGpc7ZxvHcT:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/defaeba250af828823f6ddf39f2e6660228b576d/Intel-Confidential-Compute-for-X/workloads/openvino-model-server/openvino-model-server.manifest.template#L4)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto (MySQL)
</blockquote></details>

Done.
___
*[`Intel-Confidential-Compute-for-X/workloads/openvino-model-server/openvino-model-server.manifest.template` line 7 at r1](https://reviewable.io/reviews/gramineproject/contrib/46#-Na7CUaj-KEj8I16Xt_k:-NaGZagT0HQmc75Fz5wU:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/defaeba250af828823f6ddf39f2e6660228b576d/Intel-Confidential-Compute-for-X/workloads/openvino-model-server/openvino-model-server.manifest.template#L7)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is not required starting from Gramine v1.3, so just remove this line.
</blockquote></details>

Done.
___
*[`Intel-Confidential-Compute-for-X/workloads/openvino-model-server/openvino-model-server.manifest.template` line 21 at r1](https://reviewable.io/reviews/gramineproject/contrib/46#-Na7C_0O1AwUltoA20J0:-Naj4QUBCk1ICzlVnhZ1:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/defaeba250af828823f6ddf39f2e6660228b576d/Intel-Confidential-Compute-for-X/workloads/openvino-model-server/openvino-model-server.manifest.template#L21)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1 to Jitender's proposal, but also fix a typo in his proposal: `GSC have` -> `GSC has`
</blockquote></details>

Done.
___
*[`Intel-Confidential-Compute-for-X/workloads/openvino-model-server/README.md` line 28 at r1](https://reviewable.io/reviews/gramineproject/contrib/46#-Na7Ct1jD-QsLezwVfbW:-Naj4fCK1WjcHiU99rtN:b-26e75q) ([raw file](https://github.com/gramineproject/contrib/blob/defaeba250af828823f6ddf39f2e6660228b576d/Intel-Confidential-Compute-for-X/workloads/openvino-model-server/README.md#L28)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why are we talking about version 2022.1? Isn't it a bit too old now? Can you update to a newer version?

OpenVINO itself seems to be of version 2023.0, which is good to me. So why are the models old? Or there is nothing newer?
</blockquote></details>

I have followed the demo described here in official website https://github.com/openvinotoolkit/model_server/blob/main/docs/ovms_quickstart.md to show how it can be enabled in GSC. I have updated to newer version now.
___
*[`Intel-Confidential-Compute-for-X/workloads/openvino-model-server/README.md` line 38 at r1](https://reviewable.io/reviews/gramineproject/contrib/46#-Na7CzZ63ZE5CWbsAQ0M:-Naj5JJB3zpe456VE041:bei42dc) ([raw file](https://github.com/gramineproject/contrib/blob/defaeba250af828823f6ddf39f2e6660228b576d/Intel-Confidential-Compute-for-X/workloads/openvino-model-server/README.md#L38)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

But `.../models` is a common director [...]

2023-08-01 06:41 UTC, dimakuv requested changes
> Reviewed 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/46)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @sahason)

___
*[`Intel-Confidential-Compute-for-X/workloads/openvino-model-server/docker_run_flags.txt` line 1 at r1](https://reviewable.io/reviews/gramineproject/contrib/46#-Na7BvWN8DV9FXRbAs6e:-NajmULJ2exvl0nD5pax:b-6hxixp) ([raw file](https://github.com/gramineproject/contrib/blob/defaeba250af828823f6ddf39f2e6660228b576d/Intel-Confidential-Compute-for-X/workloads/openvino-model-server/docker_run_flags.txt#L1)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

It was written this way as the model directory had root access. As we moved to tmpfs logic I have replaced it.
</blockquote></details>

Thanks, looks good to me now!
___
*[`Intel-Confidential-Compute-for-X/workloads/openvino-model-server/insecure_args.txt` line 1 at r1](https://reviewable.io/reviews/gramineproject/contrib/46#-Na7CCvODXX0MFSZVp-E:-Najmy7g8B47wK1qLBrd:bjh4g6z) ([raw file](https://github.com/gramineproject/contrib/blob/defaeba250af828823f6ddf39f2e6660228b576d/Intel-Confidential-Compute-for-X/workloads/openvino-model-server/insecure_args.txt#L1)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

I have followed the demo described here in official website https://github.com/openvinotoolkit/model_server/blob/main/docs/ovms_quickstart.md to show how it can be enabled in GSC. This is an example where CPU_THROUGHPUT_STREAMS  specifies number of CPU “execution” streams for the throughput mode.
</blockquote></details>

Sorry, but I don't see `CPU_THROUGHPUT_STREAMS` anywhere in the specified link?

What happens if you just remove this argument?
___
*[`Intel-Confidential-Compute-for-X/workloads/openvino-model-server/README.md` line 68 at r1](https://reviewable.io/reviews/gramineproject/contrib/46#-Na7Dpnc967M9XIFbP_T:-NajnqxL6xNvyoJ234n3:bvs67uc) ([raw file](https://github.com/gramineproject/contrib/blob/defaeba250af828823f6ddf39f2e6660228b576d/Intel-Confidential-Compute-for-X/workloads/openvino-model-server/README.md#L68)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

I have followed the demo described here in official website https://github.com/openvinotoolkit/model_server/blob/main/docs/ovms_quickstart.md to show how it can be enabled in GSC. This is an example where CPU_THROUGHPUT_STREAMS  specifies number of CPU “execution” streams for the throughput mode.
</blockquote></details>

ditto, I don't see `CPU_THROUGHPUT_STREAMS` on that link.
___
*[`Intel-Confidential-Compute-for-X/workloads/openvino-model-server/README.md` line 99 at r1](https://reviewable.io/reviews/gramineproject/contrib/46#-Na7F7gnBJoEX4putUA2:-NajogGR2T0PdE9dbes7:btyj5fw) ([raw file](https://github.com/gramineproject/contrib/blob/defaeba250af828823f6ddf39f2e6660228b576d/Intel-Confidential-Compute-for-X/workloads/openvino-model-server/README.md#L99)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Now I understand that here you're asking the Python client to trigger inference on the OpenVINO Model Server (that runs in a separate GSC container). Could you expand this sentence to this then:
```
- Trigger inference run in the GSC OpenVINO server from a Python client:
```
___
*[`Intel-Confidential-Compute-for-X/workloads/openvino-model-server/README.md` line 107 at r1](https://reviewable.io/reviews/gramineproject/contrib/46#-Na7FzvoD_K0kYcj9fcu:-Najo8dS2iaZ-9dDPUA5:b-qx3ggc) ([raw file](https://github.com/gramineproject/contrib/blob/defaeba250af828823f6ddf39f2e6660228b576d/Intel-Confidential-Compute-for-X/workloads/openvino-model-server/README.md#L107)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

Removed. If no_proxy is not set the command will fail and it's difficult for a user to understand why this is failing. Do you suggest to add a note such that in case of failure the user can set up no_proxy?
</blockquote></details>

Yes, you can add an inline comment here, something like this:
```
# if you are behind a corporate proxy, export `no_proxy` envvar to avoid Python failure below
```


<!-- Sent from Reviewable.io -->

2023-08-01 10:17 UTC, sahason reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/46)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`Intel-Confidential-Compute-for-X/workloads/openvino-model-server/insecure_args.txt` line 1 at r1](https://reviewable.io/reviews/gramineproject/contrib/46#-Na7CCvODXX0MFSZVp-E:-NakUeVT1ztSnpyXmGER:boiw2ve) ([raw file](https://github.com/gramineproject/contrib/blob/defaeba250af828823f6ddf39f2e6660228b576d/Intel-Confidential-Compute-for-X/workloads/openvino-model-server/insecure_args.txt#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Sorry, but I don't see `CPU_THROUGHPUT_STREAMS` anywhere in the specified link?

What happens if you just remove this argument?
</blockquote></details>

I remember doing this from some official document but can't find now. I have removed it now. It works fine.
___
*[`Intel-Confidential-Compute-for-X/workloads/openvino-model-server/README.md` line 68 at r1](https://reviewable.io/reviews/gramineproject/contrib/46#-Na7Dpnc967M9XIFbP_T:-NakVPkg1xM8QNkNlLtb:boiw2ve) ([raw file](https://github.com/gramineproject/contrib/blob/defaeba250af828823f6ddf39f2e6660228b576d/Intel-Confidential-Compute-for-X/workloads/openvino-model-server/README.md#L68)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto, I don't see `CPU_THROUGHPUT_STREAMS` on that link.
</blockquote></details>

I remember doing this from some official document but can't find now. I have removed it now. It works fine.
___
*[`Intel-Confidential-Compute-for-X/workloads/openvino-model-server/README.md` line 99 at r1](https://reviewable.io/reviews/gramineproject/contrib/46#-Na7F7gnBJoEX4putUA2:-NakVSj0EyWlBDcZmMgT:bb6un1j) ([raw file](https://github.com/gramineproject/contrib/blob/defaeba250af828823f6ddf39f2e6660228b576d/Intel-Confidential-Compute-for-X/workloads/openvino-model-server/README.md#L99)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Now I understand that here you're asking the Python client to trigger inference on the OpenVINO Model Server (that runs in a separate GSC container). Could you expand this sentence to this then:
```
- Trigger inference run in the GSC OpenVINO server from a Python client:
```
</blockquote></details>

Done
___
*[`Intel-Confidential-Compute-for-X/workloads/openvino-model-server/README.md` line 107 at r1](https://reviewable.io/reviews/gramineproject/contrib/46#-Na7FzvoD_K0kYcj9fcu:-NakVUsrAVIRNeViSOcP:bb6un1j) ([raw file](https://github.com/gramineproject/contrib/blob/defaeba250af828823f6ddf39f2e6660228b576d/Intel-Confidential-Compute-for-X/workloads/openvino-model-server/README.md#L107)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, you can add an inline comment here, something like this:
```
# if you are behind a corporate proxy, export `no_proxy` envvar to avoid Python failure below
```
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-08-01 12:40 UTC, dimakuv approved these changes
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/46)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2023-08-02 14:15 UTC, mkow requested changes
> Reviewed 5 of 9 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/46)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @sahason)

___
*[`Intel-Confidential-Compute-for-X/workloads/openvino-model-server/openvino-model-server.manifest.template` line 22 at r3](https://reviewable.io/reviews/gramineproject/contrib/46#-Naq_6Vd6oFw19MuIht7:-Naq_6VeDqMOHNFHu3Xj:b-hai8x4) ([raw file](https://github.com/gramineproject/contrib/blob/e8c60ac1bbc454b6cd50d9fe8ec06a57b2fa7d30/Intel-Confidential-Compute-for-X/workloads/openvino-model-server/openvino-model-server.manifest.template#L22)):*
> ```
> 
> # FIXME: `LD_PRELOAD` should be replaced with `loader.env.LD_LIBRARY_PATH = "/ovms/lib"` when GSC
> # has the concat logic for `loader.env.LD_LIBRARY_PATH`.
> ```

Blocking until that PR is merged and this one is rebased on top of it.


<!-- Sent from Reviewable.io -->

2023-08-02 14:24 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/46)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @jkr0103)

___
*[`Intel-Confidential-Compute-for-X/workloads/openvino-model-server/openvino-model-server.manifest.template` line 22 at r3](https://reviewable.io/reviews/gramineproject/contrib/46#-Naq_6Vd6oFw19MuIht7:-NaqcbD0CzutXZywqr2W:bfbcxgd) ([raw file](https://github.com/gramineproject/contrib/blob/e8c60ac1bbc454b6cd50d9fe8ec06a57b2fa7d30/Intel-Confidential-Compute-for-X/workloads/openvino-model-server/openvino-model-server.manifest.template#L22)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Blocking until that PR is merged and this one is rebased on top of it.
</blockquote></details>

Actually, I don't think anyone planned to work on such GSC PR yet. So this FIXME is more for a not-so-near future.

On the other hand, this is probably rather trivial? @jkr0103 Have you tried implementing it in GSC?


<!-- Sent from Reviewable.io -->

2023-08-02 14:26 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/46)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[`Intel-Confidential-Compute-for-X/workloads/openvino-model-server/openvino-model-server.manifest.template` line 22 at r3](https://reviewable.io/reviews/gramineproject/contrib/46#-Naq_6Vd6oFw19MuIht7:-Naqd1uB-pWrw3yvTujz:b-43ihw8) ([raw file](https://github.com/gramineproject/contrib/blob/e8c60ac1bbc454b6cd50d9fe8ec06a57b2fa7d30/Intel-Confidential-Compute-for-X/workloads/openvino-model-server/openvino-model-server.manifest.template#L22)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Actually, I don't think anyone planned to work on such GSC PR yet. So this FIXME is more for a not-so-near future.

On the other hand, this is probably rather trivial? @jkr0103 Have you tried implementing it in GSC?
</blockquote></details>

Ah, ok, then I'm not blocking.


<!-- Sent from Reviewable.io -->

2023-08-03 07:13 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/46)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-08-03 07:14 UTC, merged