[Curated-Apps] Fetch distro from image and use with curation
gramineproject/contrib pull request #47
Opened 2023-06-09 15:46 UTC by jkr0103

Currently user have to input distro of their base image for curation, also `ubuntu:18.04` distro is used in curation test mode for all the workloads which is wrong.

With this PR, distro is retrieved from the base image being curated and used while durating it.

2023-06-13 12:38 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/47)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @jkr0103)

___
*[`Intel-Confidential-Compute-for-X/curate.py` line 298 at r1](https://reviewable.io/reviews/gramineproject/contrib/47#-NXoj1eM-tzU454r0rEn:-NXoj1eM-tzU454r0rEo:b7f10ia) ([raw file](https://github.com/gramineproject/contrib/blob/a7f310fbdad167750c856ea8e29c9bfa54f5c9bc/Intel-Confidential-Compute-for-X/curate.py#L298)):*
> ```Python
> 
> def get_image_distro(docker_socket, image_name):
>     output = docker_socket.containers.run(image_name, entrypoint='cat /etc/os-release', remove=True).decode('UTF-8')
> ```

Can you split this line into two? (E.g. first do `.run()` and then do `.decode()`)

Otherwise it's hard to read and it overflows 100 chars per line
___
*[`Intel-Confidential-Compute-for-X/curate.py` line 300 at r1](https://reviewable.io/reviews/gramineproject/contrib/47#-NXok6VlBP_LGK3qR90_:-NXok6VlBP_LGK3qR90a:bzcyjrp) ([raw file](https://github.com/gramineproject/contrib/blob/a7f310fbdad167750c856ea8e29c9bfa54f5c9bc/Intel-Confidential-Compute-for-X/curate.py#L300)):*
> ```Python
>     output = docker_socket.containers.run(image_name, entrypoint='cat /etc/os-release', remove=True).decode('UTF-8')
> 
>     pattern_id = re.compile('^ID=(.*)', flags=re.MULTILINE | re.VERBOSE)
> ```

Why do you need `re.VERBOSE`?
___
*[`Intel-Confidential-Compute-for-X/curate.py` line 301 at r1](https://reviewable.io/reviews/gramineproject/contrib/47#-NXok8zP8KNvi53BPSfi:-NXok8zQ4DOH0ktyBaSI:b-6s0wlu) ([raw file](https://github.com/gramineproject/contrib/blob/a7f310fbdad167750c856ea8e29c9bfa54f5c9bc/Intel-Confidential-Compute-for-X/curate.py#L301)):*
> ```Python
> 
>     pattern_id = re.compile('^ID=(.*)', flags=re.MULTILINE | re.VERBOSE)
>     distro_id_list = pattern_id.findall(output)
> ```

Why do you need to `findall()`? There is always only one `ID=...` line. So why not use `search()`, and fail loudly if search returns None.
___
*[`Intel-Confidential-Compute-for-X/curate.py` line 305 at r1](https://reviewable.io/reviews/gramineproject/contrib/47#-NXokM0941vpwRxg0f1s:-NXokM0941vpwRxg0f1t:b-7ropln) ([raw file](https://github.com/gramineproject/contrib/blob/a7f310fbdad167750c856ea8e29c9bfa54f5c9bc/Intel-Confidential-Compute-for-X/curate.py#L305)):*
> ```Python
> 
>     pattern_version_id = re.compile('^VERSION_ID=\"(.*)\"', flags=re.MULTILINE)
>     distro_version_id_list = pattern_version_id.findall(output)
> ```

ditto
___
*[`Intel-Confidential-Compute-for-X/curate.py` line 308 at r1](https://reviewable.io/reviews/gramineproject/contrib/47#-NXokPQ5Cif5dhf0SiyU:-NXokPQ5Cif5dhf0SiyV:bkjpdi2) ([raw file](https://github.com/gramineproject/contrib/blob/a7f310fbdad167750c856ea8e29c9bfa54f5c9bc/Intel-Confidential-Compute-for-X/curate.py#L308)):*
> ```Python
>     if len(distro_version_id_list) > 0: distro_version_id = distro_version_id_list[0]
> 
>     return distro_id + ':' + distro_version_id
> ```

What's the point of doing the check `if len(distro_id_list) > 0:` if you access `distro_id` here -- and if this variable wasn't set because of the check, then Python will fail with exception.

Same for `distro_version_id`
___
*[`Intel-Confidential-Compute-for-X/curate.py` line 339 at r1](https://reviewable.io/reviews/gramineproject/contrib/47#-NXokeFN8zGmCCdPoH9K:-NXokeFN8zGmCCdPoH9L:bz2e4k5) ([raw file](https://github.com/gramineproject/contrib/blob/a7f310fbdad167750c856ea8e29c9bfa54f5c9bc/Intel-Confidential-Compute-for-X/curate.py#L339)):*
> ```Python
>     if image_distro not in supported_distros:
>         print(f'Error: Unsupported distro "{image_distro}".')
>         exit()
> ```

Shouldn't you `exit(1)` or something? Otherwise you're exiting with `0` which is considered "success".


<!-- Sent from Reviewable.io -->

2023-06-19 06:56 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/47)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @jkr0103)

___
*[`Intel-Confidential-Compute-for-X/curate.py` line 300 at r2](https://reviewable.io/reviews/gramineproject/contrib/47#-NYHRCgrASwbVBzUSJvi:-NYHRCgrASwbVBzUSJvj:b-jcn9lz) ([raw file](https://github.com/gramineproject/contrib/blob/28ecd0cdb6af1172b1d27c8943809314c8f2acc3/Intel-Confidential-Compute-for-X/curate.py#L300)):*
> ```Python
>     output = docker_socket.containers.run(image_name, entrypoint='cat /etc/os-release', remove=True)
> 
>     # convert from bytes to str for further string handling
> ```

I would remove this comment, it is useless
___
*[`Intel-Confidential-Compute-for-X/curate.py` line 305 at r2](https://reviewable.io/reviews/gramineproject/contrib/47#-NYHQkBx2k92L2Snv8cH:-NYHQkBx2k92L2Snv8cI:b-70d4x7) ([raw file](https://github.com/gramineproject/contrib/blob/28ecd0cdb6af1172b1d27c8943809314c8f2acc3/Intel-Confidential-Compute-for-X/curate.py#L305)):*
> ```Python
>     pattern_id = re.compile('^ID=(.*)', flags=re.MULTILINE)
>     match = pattern_id.search(output)
>     if match == None:
> ```

The idiomatic way in Python is `if match is None:`
___
*[`Intel-Confidential-Compute-for-X/curate.py` line 306 at r2](https://reviewable.io/reviews/gramineproject/contrib/47#-NYHQnfK5-UoPZ8LgXHX:-NYHQnfK5-UoPZ8LgXHY:b-ugcc5h) ([raw file](https://github.com/gramineproject/contrib/blob/28ecd0cdb6af1172b1d27c8943809314c8f2acc3/Intel-Confidential-Compute-for-X/curate.py#L306)):*
> ```Python
>     match = pattern_id.search(output)
>     if match == None:
>         print(f'Error: Could not find ditro ID')
> ```

`ditro` -> `distro`
___
*[`Intel-Confidential-Compute-for-X/curate.py` line 312 at r2](https://reviewable.io/reviews/gramineproject/contrib/47#-NYHQmyk7quhtW_0ffCX:-NYHQmyk7quhtW_0ffCY:b-7ropln) ([raw file](https://github.com/gramineproject/contrib/blob/28ecd0cdb6af1172b1d27c8943809314c8f2acc3/Intel-Confidential-Compute-for-X/curate.py#L312)):*
> ```Python
>     pattern_version_id = re.compile('^VERSION_ID=\"(.*)\"', flags=re.MULTILINE)
>     match = pattern_version_id.search(output)
>     if match == None:
> ```

ditto
___
*[`Intel-Confidential-Compute-for-X/curate.py` line 313 at r2](https://reviewable.io/reviews/gramineproject/contrib/47#-NYHQplx4-pIh4K_SONb:-NYHQplx4-pIh4K_SONc:b-ugcc5h) ([raw file](https://github.com/gramineproject/contrib/blob/28ecd0cdb6af1172b1d27c8943809314c8f2acc3/Intel-Confidential-Compute-for-X/curate.py#L313)):*
> ```Python
>     match = pattern_version_id.search(output)
>     if match == None:
>         print(f'Error: Could not find ditro VERSION_ID')
> ```

`ditro` -> `distro`


<!-- Sent from Reviewable.io -->

2023-06-19 07:10 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/47)* status: 1 of 2 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`Intel-Confidential-Compute-for-X/curate.py` line 300 at r2](https://reviewable.io/reviews/gramineproject/contrib/47#-NYHRCgrASwbVBzUSJvi:-NYHUPQf8rivmxxrJxkT:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/28ecd0cdb6af1172b1d27c8943809314c8f2acc3/Intel-Confidential-Compute-for-X/curate.py#L300)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would remove this comment, it is useless
</blockquote></details>

Done.
___
*[`Intel-Confidential-Compute-for-X/curate.py` line 305 at r2](https://reviewable.io/reviews/gramineproject/contrib/47#-NYHQkBx2k92L2Snv8cH:-NYHUQnw36aBJKF20LbR:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/28ecd0cdb6af1172b1d27c8943809314c8f2acc3/Intel-Confidential-Compute-for-X/curate.py#L305)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The idiomatic way in Python is `if match is None:`
</blockquote></details>

Done.
___
*[`Intel-Confidential-Compute-for-X/curate.py` line 306 at r2](https://reviewable.io/reviews/gramineproject/contrib/47#-NYHQnfK5-UoPZ8LgXHX:-NYHUSG6AvMliPY9FDHV:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/28ecd0cdb6af1172b1d27c8943809314c8f2acc3/Intel-Confidential-Compute-for-X/curate.py#L306)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`ditro` -> `distro`
</blockquote></details>

Done.
___
*[`Intel-Confidential-Compute-for-X/curate.py` line 312 at r2](https://reviewable.io/reviews/gramineproject/contrib/47#-NYHQmyk7quhtW_0ffCX:-NYHUShr7LZOjWifoJuI:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/28ecd0cdb6af1172b1d27c8943809314c8f2acc3/Intel-Confidential-Compute-for-X/curate.py#L312)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`Intel-Confidential-Compute-for-X/curate.py` line 313 at r2](https://reviewable.io/reviews/gramineproject/contrib/47#-NYHQplx4-pIh4K_SONb:-NYHUULGCkkw9gGjc2iW:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/28ecd0cdb6af1172b1d27c8943809314c8f2acc3/Intel-Confidential-Compute-for-X/curate.py#L313)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`ditro` -> `distro`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-06-20 13:46 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/47)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-07-10 17:57 UTC, mkow requested changes
> Reviewed 1 of 2 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/47)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @jkr0103)

___
*[`Intel-Confidential-Compute-for-X/curate.py` line 298 at r3](https://reviewable.io/reviews/gramineproject/contrib/47#-N_-h_GL7MehXswVevnR:-N_-h_GL7MehXswVevnS:bief13k) ([raw file](https://github.com/gramineproject/contrib/blob/8bcd1bf51a33c6ade3765846f4317f6751cc320e/Intel-Confidential-Compute-for-X/curate.py#L298)):*
> ```
> docker_socket.containers.run(image_name, entrypoint='cat /etc/os-release'
> ```

Why not `get_archive()`?
___
*[`Intel-Confidential-Compute-for-X/util/constants.py` line 25 at r3](https://reviewable.io/reviews/gramineproject/contrib/47#-N_-wdEXDDQAxmx1UjDP:-N_-wdEXDDQAxmx1UjDQ:bgln67r) ([raw file](https://github.com/gramineproject/contrib/blob/8bcd1bf51a33c6ade3765846f4317f6751cc320e/Intel-Confidential-Compute-for-X/util/constants.py#L25)):*
> ```Python
> color_set = '::reverse'
> 
> supported_distros = ('ubuntu:18.04', 'ubuntu:20.04', 'debian:10', 'debian:11')
> ```

FYI: not supported by Gramine anymore.



_Code quote:_
```Python
'ubuntu:18.04'
```


<!-- Sent from Reviewable.io -->

2023-07-17 11:41 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/47)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`Intel-Confidential-Compute-for-X/curate.py` line 298 at r3](https://reviewable.io/reviews/gramineproject/contrib/47#-N_-h_GL7MehXswVevnR:-N_YdfY1AiBKMI-DFZ5W:b-lsugmm) ([raw file](https://github.com/gramineproject/contrib/blob/8bcd1bf51a33c6ade3765846f4317f6751cc320e/Intel-Confidential-Compute-for-X/curate.py#L298)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> docker_socket.containers.run(image_name, entrypoint='cat /etc/os-release'
> ```

Why not `get_archive()`?
</blockquote></details>

Actually, why `get_archive()`? What does it make simpler? We'll need to untar afterwards.

But also, why do we need this `entrypoint`? Why not just:
```
   output = docker_socket.containers.run(image_name, 'cat /etc/os-release', remove=True)
```


<!-- Sent from Reviewable.io -->

2023-07-17 22:45 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/47)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`Intel-Confidential-Compute-for-X/curate.py` line 298 at r3](https://reviewable.io/reviews/gramineproject/contrib/47#-N_-h_GL7MehXswVevnR:-N_a-VnV5j9v4-ON-Dkj:br0pq5q) ([raw file](https://github.com/gramineproject/contrib/blob/8bcd1bf51a33c6ade3765846f4317f6751cc320e/Intel-Confidential-Compute-for-X/curate.py#L298)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Actually, why `get_archive()`? What does it make simpler? We'll need to untar afterwards.

But also, why do we need this `entrypoint`? Why not just:
```
   output = docker_socket.containers.run(image_name, 'cat /etc/os-release', remove=True)
```
</blockquote></details>

Because right now, instead of just extracting the file from the image, this code:
1. Spawns a new container.
2. Starts Bash inside the container.
3. Bash forks and starts `/bin/cat`.
4. `cat` prints `/etc/os-release` to stdout.
5. Code here reads from the pipe.

`get_archive()` just reads the contents of that file. tar shouldn't be a problem, you can just unpack it in-memory with some (probably built-in) Python library.


<!-- Sent from Reviewable.io -->

2023-07-18 10:20 UTC, dimakuv submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/47)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @jkr0103)

___
*[`Intel-Confidential-Compute-for-X/curate.py` line 298 at r3](https://reviewable.io/reviews/gramineproject/contrib/47#-N_-h_GL7MehXswVevnR:-N_cVtXcBX77PzjRYxi2:b-b2ag0r) ([raw file](https://github.com/gramineproject/contrib/blob/8bcd1bf51a33c6ade3765846f4317f6751cc320e/Intel-Confidential-Compute-for-X/curate.py#L298)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Because right now, instead of just extracting the file from the image, this code:
1. Spawns a new container.
2. Starts Bash inside the container.
3. Bash forks and starts `/bin/cat`.
4. `cat` prints `/etc/os-release` to stdout.
5. Code here reads from the pipe.

`get_archive()` just reads the contents of that file. tar shouldn't be a problem, you can just unpack it in-memory with some (probably built-in) Python library.
</blockquote></details>

I feel like way too much hassle for a small non-performance-critical thing, but if you insist, then @jkr0103 please switch to `get_archive()` code.


<!-- Sent from Reviewable.io -->

2023-07-18 11:17 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/47)* status: 1 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`Intel-Confidential-Compute-for-X/curate.py` line 298 at r3](https://reviewable.io/reviews/gramineproject/contrib/47#-N_-h_GL7MehXswVevnR:-N_cfdBU8YLxjPE511kC:b-eeuqbz) ([raw file](https://github.com/gramineproject/contrib/blob/8bcd1bf51a33c6ade3765846f4317f6751cc320e/Intel-Confidential-Compute-for-X/curate.py#L298)):*
> `output = docker_socket.containers.run(image_name, 'cat /etc/os-release', remove=True)`

This one works.

Also I tried the `get_archive` which also works with below code snippet but that also required a container to be created and destroyed after file is read/fetched but with the older approach, container creation and destruction is done in single step but with `get_archive` we need more line of code.



_Code snippet:_
```Python
import tarfile
from io import BytesIO

docker_client = docker.APIClient(timeout=600)
container = docker_client.create_container('ubuntu:20.04')

(strm, _) = docker_client.get_archive(container, '/usr/lib/os-release')
pw_tar = tarfile.TarFile(fileobj=BytesIO(next(strm)))
os_release_file_contents = pw_tar.extractfile("os-release").read().decode('utf-8')

docker_client.remove_container(container, force=True)
```
___
*[`Intel-Confidential-Compute-for-X/util/constants.py` line 25 at r3](https://reviewable.io/reviews/gramineproject/contrib/47#-N_-wdEXDDQAxmx1UjDP:-N_cgqSe2VzJPpOzT-nq:b-fm3w7m) ([raw file](https://github.com/gramineproject/contrib/blob/8bcd1bf51a33c6ade3765846f4317f6751cc320e/Intel-Confidential-Compute-for-X/util/constants.py#L25)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

FYI: not supported by Gramine anymore.
</blockquote></details>

This is still supported with as Curated-Apps still uses v1.4 version of Gramine and GSC. There are other places also where we use `ubuntu:18.04`. We will remove all these instances from once we move to use Gramine/GSC v1.4, will be taken in separate PR.


<!-- Sent from Reviewable.io -->

2023-07-18 11:58 UTC, dimakuv reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/47)* status: 1 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`Intel-Confidential-Compute-for-X/curate.py` line 298 at r3](https://reviewable.io/reviews/gramineproject/contrib/47#-N_-h_GL7MehXswVevnR:-N_cr68qA1oS2xSv1NF3:b-oardzy) ([raw file](https://github.com/gramineproject/contrib/blob/8bcd1bf51a33c6ade3765846f4317f6751cc320e/Intel-Confidential-Compute-for-X/curate.py#L298)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

@mkow Please let me know preferred approach now as we have code for both here.
</blockquote></details>

I agree with Jitender. Given that steps 1,2,5 from Michal's list are anyway done by `get_archive()`, I see no benefit in Michal's proposal. (Probably `get_archive()` does even more random stuff under the hood, I have a feeling that it's just a wrapper around "spawn a container, do some bash magic, pipe the resulting bit sequence back to the host".)


<!-- Sent from Reviewable.io -->

2023-07-19 11:15 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/47)* status: 1 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`Intel-Confidential-Compute-for-X/curate.py` line 298 at r3](https://reviewable.io/reviews/gramineproject/contrib/47#-N_-h_GL7MehXswVevnR:-N_hqZA25w8of5fVHmjr:bbpppau) ([raw file](https://github.com/gramineproject/contrib/blob/8bcd1bf51a33c6ade3765846f4317f6751cc320e/Intel-Confidential-Compute-for-X/curate.py#L298)):*
> `output = docker_socket.containers.run(image_name, 'cat /etc/os-release', remove=True)`

Removing entrypoint works partially, means for some image which doesn't have entrypoint. If some image have entrypoint, we need to override that. `cat /etc/os-release'` without `entrypoint` did not work for `pytorch-entrypted` image as it have entrypoint defined. Hence I have to `entrypoint` back.


<!-- Sent from Reviewable.io -->

2023-07-19 13:50 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/47)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2023-07-21 08:55 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/47)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2023-07-21 09:02 UTC, jkr0103 commented
Based on the discussion with team, I have rebased the PR and also removed the `ubuntu:18.04` and added `ubuntu:22.04` from supported distros list.

2023-07-24 08:00 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/47)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[`Intel-Confidential-Compute-for-X/curate.py` line 298 at r3](https://reviewable.io/reviews/gramineproject/contrib/47#-N_-h_GL7MehXswVevnR:-Na5uQkf96btP2ICDdkw:b2nhll9) ([raw file](https://github.com/gramineproject/contrib/blob/8bcd1bf51a33c6ade3765846f4317f6751cc320e/Intel-Confidential-Compute-for-X/curate.py#L298)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

> `output = docker_socket.containers.run(image_name, 'cat /etc/os-release', remove=True)`

Removing entrypoint works partially, means for some image which doesn't have entrypoint. If some image have entrypoint, we need to override that. `cat /etc/os-release'` without `entrypoint` did not work for `pytorch-entrypted` image as it have entrypoint defined. Hence I have to `entrypoint` back.
</blockquote></details>

Ok.


<!-- Sent from Reviewable.io -->

2023-07-24 14:31 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/47)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2023-07-24 18:30 UTC, mkow approved these changes
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/47)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-07-25 06:14 UTC, merged