[Curated-Apps] Concat LD_PRELOAD if exists in workload manifest file
gramineproject/contrib pull request #53
Opened 2023-07-27 08:56 UTC by jkr0103

We preload `libsecret_prov_attest.so` library if remote attestation is selected by user. But if `LD_PRELOAD` exists in workload specific manifest, then we will have two LD_PRELOAD which will result in `Duplicate Key` error.

This PR fixes this by concatenating the LD_PRELOAD with workload specific manifest.

2023-07-27 11:01 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/53)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @jkr0103)

___
*[`Intel-Confidential-Compute-for-X/util/curation_script.sh` line 189 at r1](https://reviewable.io/reviews/gramineproject/contrib/53#-NaLzf6mBXUMgCKpKYQ-:-NaLzf6mBXUMgCKpKYQ0:b-7cj6zg) ([raw file](https://github.com/gramineproject/contrib/blob/1fb5d6bac050c32aefd052b471874e621937d786/Intel-Confidential-Compute-for-X/util/curation_script.sh#L189)):*
> ```Shell
>     echo '' >> $app_image_manifest
>     echo '# Attestation related entries' >> $app_image_manifest
>     echo 'sgx.remote_attestation = "dcap"' >> $app_image_manifest
> ```

Why did you remove this line which adds `sgx.remote_attestation = "dcap"` in the manifest file?
___
*[`Intel-Confidential-Compute-for-X/util/curation_script.sh` line 190 at r1](https://reviewable.io/reviews/gramineproject/contrib/53#-NaM-8GJ50-yR5BpmqT1:-NaM-8GJ50-yR5BpmqT2:b-r91zeg) ([raw file](https://github.com/gramineproject/contrib/blob/b27853b3e6b5338245ce9f709106715de2f1c07b/Intel-Confidential-Compute-for-X/util/curation_script.sh#L190)):*
> ```Shell
>     echo '# Attestation related entries' >> $app_image_manifest
> 
>     secret_prov_attest="/gramine/meson_build_output/lib/x86_64-linux-gnu/libsecret_prov_attest.so"
> ```

Please add a comment before this whole snippet like this:
```
# Preload `libsecret_prov_attest.so` library. But if `LD_PRELOAD` exists in workload
# specific manifest, then we must concatenate our lib with already-listed libs.
# FIXME: This should be actually done somewhere in GSC.
```
___
*[`Intel-Confidential-Compute-for-X/util/curation_script.sh` line 194 at r1](https://reviewable.io/reviews/gramineproject/contrib/53#-NaLzpxf8QinCDtCIfWy:-NaLzpxf8QinCDtCIfWz:b-omhbnj) ([raw file](https://github.com/gramineproject/contrib/blob/b27853b3e6b5338245ce9f709106715de2f1c07b/Intel-Confidential-Compute-for-X/util/curation_script.sh#L194)):*
> ```Shell
>         echo 'loader.env.LD_PRELOAD = "'$secret_prov_attest'"' >> $app_image_manifest
>     else
>         sed -i "s|\(loader.env.LD_PRELOAD = .*\)\"|\1:$secret_prov_attest\"|g" \
> ```

You have spaces around `=`. Doesn't it mean that your hack won't catch manifest files like any of these:
```
loader.env.LD_PRELOAD="bla"
loader.env.LD_PRELOAD   =   "bla"
loader.env.LD_PRELOAD=     "bla"
loader.env.LD_PRELOAD      ="bla"
```


<!-- Sent from Reviewable.io -->

2023-07-28 00:11 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/53)* status: 0 of 1 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`Intel-Confidential-Compute-for-X/util/curation_script.sh` line 189 at r1](https://reviewable.io/reviews/gramineproject/contrib/53#-NaLzf6mBXUMgCKpKYQ-:-NaOmKC06OG6VO6UpD6M:bekf558) ([raw file](https://github.com/gramineproject/contrib/blob/1fb5d6bac050c32aefd052b471874e621937d786/Intel-Confidential-Compute-for-X/util/curation_script.sh#L189)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why did you remove this line which adds `sgx.remote_attestation = "dcap"` in the manifest file?
</blockquote></details>

It was by mistake, added it back now.
___
*[`Intel-Confidential-Compute-for-X/util/curation_script.sh` line 190 at r1](https://reviewable.io/reviews/gramineproject/contrib/53#-NaM-8GJ50-yR5BpmqT1:-NaOnlS349WVodiO69w2:b-thfjwr) ([raw file](https://github.com/gramineproject/contrib/blob/b27853b3e6b5338245ce9f709106715de2f1c07b/Intel-Confidential-Compute-for-X/util/curation_script.sh#L190)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add a comment before this whole snippet like this:
```
# Preload `libsecret_prov_attest.so` library. But if `LD_PRELOAD` exists in workload
# specific manifest, then we must concatenate our lib with already-listed libs.
# FIXME: This should be actually done somewhere in GSC.
```
</blockquote></details>

Last comment is not true. There can still be `LD_PRELOAD` library. `FIXME` comment is application in OpenVINO manifest in PR https://github.com/gramineproject/contrib/pull/46. I have added comment there.
___
*[`Intel-Confidential-Compute-for-X/util/curation_script.sh` line 194 at r1](https://reviewable.io/reviews/gramineproject/contrib/53#-NaLzpxf8QinCDtCIfWy:-NaOpONNEf5V1cwFPRFS:b-qssebl) ([raw file](https://github.com/gramineproject/contrib/blob/b27853b3e6b5338245ce9f709106715de2f1c07b/Intel-Confidential-Compute-for-X/util/curation_script.sh#L194)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You have spaces around `=`. Doesn't it mean that your hack won't catch manifest files like any of these:
```
loader.env.LD_PRELOAD="bla"
loader.env.LD_PRELOAD   =   "bla"
loader.env.LD_PRELOAD=     "bla"
loader.env.LD_PRELOAD      ="bla"
```
</blockquote></details>

fixed.


<!-- Sent from Reviewable.io -->

2023-07-28 06:56 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/53)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-07-29 14:43 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/53)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

___
*[`Intel-Confidential-Compute-for-X/util/curation_script.sh` line 197 at r2](https://reviewable.io/reviews/gramineproject/contrib/53#-NaX2xgKC7vTHrYRlKxX:-NaX2xgKC7vTHrYRlKxY:b-b0nc8o) ([raw file](https://github.com/gramineproject/contrib/blob/5c16c70b08e79cd00ed07f4a89e0f77f6429a7d2/Intel-Confidential-Compute-for-X/util/curation_script.sh#L197)):*
> ```Shell
>         echo 'loader.env.LD_PRELOAD = "'$secret_prov_attest'"' >> $app_image_manifest
>     else
>         sed -i "s|\(^loader.env.LD_PRELOAD[[:space:]]*=[[:space:]]*.*\)\"|\1:$secret_prov_attest\"|g" \
> ```

This is a terrible hack, I'm approving it only because it's in the `contrib` repo...


<!-- Sent from Reviewable.io -->

2023-07-31 06:38 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/53)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2023-07-31 09:50 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/53)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2023-08-01 00:34 UTC, kailun-qin approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/53)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-08-01 06:19 UTC, merged