[Curated-Apps] Use latest image tags
gramineproject/contrib pull request #54
Opened 2023-08-16 08:04 UTC by jkr0103

Some curated apps uses old image tags for which latest tags exists. This PR changes image tags for some apps, some are already using upto date image tags.

2023-08-16 08:30 UTC, kailun-qin requested changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/54)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @jkr0103)

___
*[`Intel-Confidential-Compute-for-X/workloads/redis/README.md` line 26 at r1](https://reviewable.io/reviews/gramineproject/contrib/54#-NbxS9sT6d52sXtHB7ar:-NbxS9sUEcGBAQs4FJ1a:bwwni2k) ([raw file](https://github.com/gramineproject/contrib/blob/8217c7a6afadc6de395be241c598a8034dcb1ae3/Intel-Confidential-Compute-for-X/workloads/redis/README.md#L26)):*
> ```Markdown
>      execute the following script:
>      ```sh
>      python3 ./curate.py redis redis:7.0.10 test
> ```

Is this the latest image? I see there is [7.0.12](https://hub.docker.com/layers/library/redis/7.0.12/images/sha256-6e30a37f91041a24ed52fce0c1330bb11b867ecf0f154168e28f9fc65898f610?context=explore).



_Code quote:_
```Markdown
redis:7.0.10
```


<!-- Sent from Reviewable.io -->

2023-08-16 08:31 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/54)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @kailun-qin)

___
*[`Intel-Confidential-Compute-for-X/workloads/redis/README.md` line 26 at r1](https://reviewable.io/reviews/gramineproject/contrib/54#-NbxS9sT6d52sXtHB7ar:-NbxT--K4aCVnwgZqun9:bxmhgs4) ([raw file](https://github.com/gramineproject/contrib/blob/8217c7a6afadc6de395be241c598a8034dcb1ae3/Intel-Confidential-Compute-for-X/workloads/redis/README.md#L26)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Is this the latest image? I see there is [7.0.12](https://hub.docker.com/layers/library/redis/7.0.12/images/sha256-6e30a37f91041a24ed52fce0c1330bb11b867ecf0f154168e28f9fc65898f610?context=explore).
</blockquote></details>

redis:7.0.11 onwards images are based on debian12 which is not supported in GSC and we have a PR for supporting that.


<!-- Sent from Reviewable.io -->

2023-08-16 08:34 UTC, kailun-qin approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/54)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`Intel-Confidential-Compute-for-X/workloads/redis/README.md` line 26 at r1](https://reviewable.io/reviews/gramineproject/contrib/54#-NbxS9sT6d52sXtHB7ar:-NbxTiuU83R8SKCMSO6m:b9ylvn6) ([raw file](https://github.com/gramineproject/contrib/blob/8217c7a6afadc6de395be241c598a8034dcb1ae3/Intel-Confidential-Compute-for-X/workloads/redis/README.md#L26)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

redis:7.0.11 onwards images are based on debian12 which is not supported in GSC and we have a PR for supporting that.
</blockquote></details>

Ah I see, thanks for the info!


<!-- Sent from Reviewable.io -->

2023-08-21 05:47 UTC, dimakuv requested changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/54)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @jkr0103)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/54#-NcLbyZu0E5aFaQMpb4Z:-NcLbyZvE9Q4iRauKd6e:b-s3c1fc) (no related file):*
What about Memcached? I see 1.6.21 but you only have 1.5 in your README.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/54#-NcLcKBB-ezMI99nmBrW:-NcLcKBB-ezMI99nmBrX:bmdrogc) (no related file):*
What about Redis? I see 7.2.0 but you only have 7.0.0 in your README.

___
___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/gramineproject/contrib/54#-NcLagGx2514ySbFr9jW):*
Could you also add a commit body message that lists which workloads exactly were updated (MariaDB, MySQL, ...). Plus another sentence why Redis is only of version `redis:7.0.10` (as you explained to Kailun in the other comment).
___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/gramineproject/contrib/54#-NcLb09g7XPV75G4pFDy):*
Is this correct? The author of the PR is Jitender, but the signed-off line has Anjali.


<!-- Sent from Reviewable.io -->

2023-08-24 10:28 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/54)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/54#-NcLcKBB-ezMI99nmBrW:-Ncb4BXP3nv4VP58lqGr:b-1skhx) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What about Redis? I see 7.2.0 but you only have 7.0.0 in your README.
</blockquote></details>

redis:7.0.11 onwards images are based on debian12 which is not supported in GSC yet. Hence using redis:7.0.10 which is based on debian 11.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/54#-NcLbyZu0E5aFaQMpb4Z:-Ncb4MUG3t6jMzUzIZ27:b-54wt5e) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What about Memcached? I see 1.6.21 but you only have 1.5 in your README.
</blockquote></details>

Memcached uses eventfd syscall starting from 1.6, which is considered insecure in Gramine, hence keeping the old image tag.

___
___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/gramineproject/contrib/54#-NcLagGx2514ySbFr9jW):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you also add a commit body message that lists which workloads exactly were updated (MariaDB, MySQL, ...). Plus another sentence why Redis is only of version `redis:7.0.10` (as you explained to Kailun in the other comment).
</blockquote></details>

Done.
___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/gramineproject/contrib/54#-NcLb09g7XPV75G4pFDy):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Is this correct? The author of the PR is Jitender, but the signed-off line has Anjali.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-24 14:11 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/54)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @jkr0103)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/54#-NcLbyZu0E5aFaQMpb4Z:-NcbsMjG-xrCU74Eo793:b-yfd3hv) (no related file):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

Memcached uses eventfd syscall starting from 1.6, which is considered insecure in Gramine, hence keeping the old image tag.
</blockquote></details>

Ok, fine with me.

___
___
*[`-- commits` line 16 at r2](https://reviewable.io/reviews/gramineproject/contrib/54#-NcbsYRf1YTMeFU9mg0h):*
I will slightly improve the commit message during final rebase. Other than that, the PR looks good to me.


<!-- Sent from Reviewable.io -->

2023-08-24 14:19 UTC, woju approved these changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/54)* status: all files reviewed, 1 unresolved discussion (waiting on @jkr0103)



<!-- Sent from Reviewable.io -->

2023-08-24 14:21 UTC, mkow approved these changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/54)* status: all files reviewed, 1 unresolved discussion (waiting on @jkr0103)



<!-- Sent from Reviewable.io -->

2023-08-24 14:25 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/54)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`-- commits` line 16 at r2](https://reviewable.io/reviews/gramineproject/contrib/54#-NcbsYRf1YTMeFU9mg0h):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I will slightly improve the commit message during final rebase. Other than that, the PR looks good to me.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-08-24 14:26 UTC, merged