[Curated-Apps] Exit curation script on error
gramineproject/contrib pull request #55
Opened 2023-09-29 06:03 UTC by jkr0103

This PR fixes two issues as explained below:
1. Curation script doesn't exit immediatly on any error, we have seen it multiple cases when `gsc build` fails but curation proceed to next spte of signing the image.
2. Curation script executed by non-root user doesn't override the files `<workload>.manifest`, `<workload>-gsc.dockerfile` etc files  already created by root user. Code lines: [here](https://github.com/gramineproject/contrib/blob/be92cdebc212e38690366aa7d7d3c2e2b78d86be/Intel-Confidential-Compute-for-X/util/curation_script.sh#L49-L50).

In such cases curation script should report the error and should not continue execution.

2023-09-29 08:25 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/55)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @jkr0103)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/contrib/55#-NfV1Krq-bdSEoB2GGJp):*
You forgot to add the DCO line (`Signed-off-by:`)
___
*[`Intel-Confidential-Compute-for-X/util/curation_script.sh` line 37 at r1](https://reviewable.io/reviews/gramineproject/contrib/55#-NfV1OcSDObAu3_grOCG:-NfV1OcSDObAu3_grOCH:b1zp209) ([raw file](https://github.com/gramineproject/contrib/blob/cff37f9f5f9b1fbb6588d8a11798673d86c5df07/Intel-Confidential-Compute-for-X/util/curation_script.sh#L37)):*
> ```Shell
> # -- arg13   : encryption key used for encrypting sensitive files such as models, data etc.
> # -- arg14   : Passphrase to the enclave signing key (if applicable)
> set -e
> ```

Could you add an empty line before this line, to visually separate from the comment?
___
*[`Intel-Confidential-Compute-for-X/util/curation_script.sh` line 50 at r1](https://reviewable.io/reviews/gramineproject/contrib/55#-NfV1ZUEDx3bv0YtPUOz:-NfV1ZUEDx3bv0YtPUP-:bpi4c7e) ([raw file](https://github.com/gramineproject/contrib/blob/cff37f9f5f9b1fbb6588d8a11798673d86c5df07/Intel-Confidential-Compute-for-X/util/curation_script.sh#L50)):*
Hm, how does `-f` help in your explained problem?

> Curation script executed by non-root user doesn't override the files `<workload>.manifest`, `<workload>-gsc.dockerfile` etc files already created by root user.

I currently don't understand what this `-f` option changes.


<!-- Sent from Reviewable.io -->

2023-09-29 13:10 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/55)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

___
*[`Intel-Confidential-Compute-for-X/util/curation_script.sh` line 50 at r1](https://reviewable.io/reviews/gramineproject/contrib/55#-NfV1ZUEDx3bv0YtPUOz:-NfW1tU33Ihg7DXx_JYu:b-k7htz) ([raw file](https://github.com/gramineproject/contrib/blob/cff37f9f5f9b1fbb6588d8a11798673d86c5df07/Intel-Confidential-Compute-for-X/util/curation_script.sh#L50)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Hm, how does `-f` help in your explained problem?

> Curation script executed by non-root user doesn't override the files `<workload>.manifest`, `<workload>-gsc.dockerfile` etc files already created by root user.

I currently don't understand what this `-f` option changes.
</blockquote></details>

I have seen cases where same repo is used by two different users and if one use have already created these temporary files, other user was not able to re-create them and it went unreported but with `-f` option I did not see the issue.


<!-- Sent from Reviewable.io -->

2023-09-29 14:33 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/55)* status: 1 of 2 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/contrib/55#-NfV1Krq-bdSEoB2GGJp):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You forgot to add the DCO line (`Signed-off-by:`)
</blockquote></details>

Done.
___
*[`Intel-Confidential-Compute-for-X/util/curation_script.sh` line 37 at r1](https://reviewable.io/reviews/gramineproject/contrib/55#-NfV1OcSDObAu3_grOCG:-NfWLxB869URqz4kYjjP:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/cff37f9f5f9b1fbb6588d8a11798673d86c5df07/Intel-Confidential-Compute-for-X/util/curation_script.sh#L37)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you add an empty line before this line, to visually separate from the comment?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-02 07:41 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/55)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

___
*[`Intel-Confidential-Compute-for-X/util/curation_script.sh` line 50 at r1](https://reviewable.io/reviews/gramineproject/contrib/55#-NfV1ZUEDx3bv0YtPUOz:-NfjKEZt4kV2SVXD4I3h:bpric0d) ([raw file](https://github.com/gramineproject/contrib/blob/cff37f9f5f9b1fbb6588d8a11798673d86c5df07/Intel-Confidential-Compute-for-X/util/curation_script.sh#L50)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

I have seen cases where same repo is used by two different users and if one use have already created these temporary files, other user was not able to re-create them and it went unreported but with `-f` option I did not see the issue.
</blockquote></details>

Ah, I guess I was confused by what `cp -f` really does, and why it is allowed to delete the file. See https://unix.stackexchange.com/questions/627690/how-does-the-cp-f-work-in-unix.


<!-- Sent from Reviewable.io -->

2023-10-17 22:31 UTC, mkow approved these changes
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/55)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-10-18 06:35 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/55)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-10-18 06:36 UTC, merged