Add example to deploy a gsc python image to AKS cluster
gramineproject/contrib pull request #6
Opened 2022-06-01 10:44 UTC by aneessahib

Signed-off-by: aneessahib <anees.a.sahib@intel.com>
Add example to deploy a gsc python image to AKS cluster

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/contrib/6)

2022-06-01 12:03 UTC, dimakuv requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/6)* status: all files reviewed, 11 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @aneessahib)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/contrib/6#-N3U4fTg9fjaVDnueaHT):*
`GSC Python` (capital letters)
___
*[`Examples/aks-python-helloworld/python.manifest` line 1 at r1](https://reviewable.io/reviews/gramineproject/contrib/6#-N3U4v4-1LxlzkXyjKHV:-N3U4v403eNEPPO60hAw:bpp0dyk) ([raw file](https://github.com/gramineproject/contrib/blob/78f548c7c1fab987b5e8cbfd2d1348374ca01d86/Examples/aks-python-helloworld/python.manifest#L1)):*
> ```
> sgx.enclave_size = "256M"
> ```

Could we increase to `512M`? 256MB feels too small, and may suddenly result in memory errors. I'd feel safer with a slightly bigger enclave size.
___
*[`Examples/aks-python-helloworld/python.manifest` line 6 at r1](https://reviewable.io/reviews/gramineproject/contrib/6#-N3U53g-1wplLPpDUtxL:-N3U53g-1wplLPpDUtxM:butrbhg) ([raw file](https://github.com/gramineproject/contrib/blob/78f548c7c1fab987b5e8cbfd2d1348374ca01d86/Examples/aks-python-helloworld/python.manifest#L6)):*
> ```
> sgx.trusted_files = [
>   "file:/entrypoint.manifest",  # unused entry, only to test merging of manifests
> ]
> ```

Let's just remove these three lines. They are only confusing. And we already have this "test" manifest in the proper GSC repo, so we don't need these testing lines in here.
___
*[`Examples/aks-python-helloworld/README.rst` line 1 at r1](https://reviewable.io/reviews/gramineproject/contrib/6#-N3U6iF95mEiRT9pJ-Nv:-N3U6iF95mEiRT9pJ-Nw:bxpih3a) ([raw file](https://github.com/gramineproject/contrib/blob/78f548c7c1fab987b5e8cbfd2d1348374ca01d86/Examples/aks-python-helloworld/README.rst#L1)):*
> ```reStructuredText
> Graminizing Python Docker image
> ```

Why RST? We typically have `.md` (Markdown) formatting for these files.

This example will be typically read on GitHub, and GitHub is not very good at rendering RST files: https://github.com/aneessahib/contrib/tree/aks-python/Examples/aks-python-helloworld (see how the `warning` snippet got incorrectly rendered).

Please change to MD.
___
*[`Examples/aks-python-helloworld/README.rst` line 4 at r1](https://reviewable.io/reviews/gramineproject/contrib/6#-N3U71A79Q9AZjLGlMYu:-N3U71A79Q9AZjLGlMYv:b-qdjw3z) ([raw file](https://github.com/gramineproject/contrib/blob/78f548c7c1fab987b5e8cbfd2d1348374ca01d86/Examples/aks-python-helloworld/README.rst#L4)):*
> ```reStructuredText
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
> This section demonstrates how to translate the Python Docker Hub image to a
> ```

`section` -> `example`
___
*[`Examples/aks-python-helloworld/README.rst` line 5 at r1](https://reviewable.io/reviews/gramineproject/contrib/6#-N3U6YwFAHzzYCPMhyJc:-N3U6YwFAHzzYCPMhyJd:b-r870d5) ([raw file](https://github.com/gramineproject/contrib/blob/78f548c7c1fab987b5e8cbfd2d1348374ca01d86/Examples/aks-python-helloworld/README.rst#L5)):*
> ```reStructuredText
> 
> This section demonstrates how to translate the Python Docker Hub image to a
> graminized image, which can be readily to deployed to a confidential compute AKS
> ```

`readily to` -> `readily`
___
*[`Examples/aks-python-helloworld/README.rst` line 12 at r1](https://reviewable.io/reviews/gramineproject/contrib/6#-N3U7Cc51hvr2wz1E4Bg:-N3U7Cc51hvr2wz1E4Bh:b7bk8qy) ([raw file](https://github.com/gramineproject/contrib/blob/78f548c7c1fab987b5e8cbfd2d1348374ca01d86/Examples/aks-python-helloworld/README.rst#L12)):*
> ```reStructuredText
>    This example relies on insecure arguments provided at runtime and should not
>    be used production. To use trusted arguments, please see the `manpage of GSC
>    <https://gramine.readthedocs.io/projects/gsc/en/latest/index.html?highlight=python#using-gramine-s-trusted-command-line-arguments>`__.
> ```

I would just point to the `GSC documentation` (https://gramine.readthedocs.io/projects/gsc)
___
*[`Examples/aks-python-helloworld/README.rst` line 18 at r1](https://reviewable.io/reviews/gramineproject/contrib/6#-N3U7LQ45qQo0tRZpMke:-N3U7LQ45qQo0tRZpMkf:b-1bvnw1) ([raw file](https://github.com/gramineproject/contrib/blob/78f548c7c1fab987b5e8cbfd2d1348374ca01d86/Examples/aks-python-helloworld/README.rst#L18)):*
> ```reStructuredText
>        docker pull python
> 
> #. Create the application-specific Manifest file :file:`python.manifest`::
> ```

But you already have this file. Delete this bullet item.
___
*[`Examples/aks-python-helloworld/README.rst` line 23 at r1](https://reviewable.io/reviews/gramineproject/contrib/6#-N3U7Xjt-Dx1LU1q0SVT:-N3U7Xjt-Dx1LU1q0SVU:brn9hxq) ([raw file](https://github.com/gramineproject/contrib/blob/78f548c7c1fab987b5e8cbfd2d1348374ca01d86/Examples/aks-python-helloworld/README.rst#L23)):*
> ```reStructuredText
>        sgx.thread_num = 4
> 
> #. Graminize the Python image using gsc <https://github.com/gramineproject/gsc> 
> ```

`using GSC`, and no need to put the link -- we already provided the link above.
___
*[`Examples/aks-python-helloworld/README.rst` line 26 at r1](https://reviewable.io/reviews/gramineproject/contrib/6#-N3U7rScCL7s8reyIRku:-N3U7rScCL7s8reyIRkv:b2uvgfq) ([raw file](https://github.com/gramineproject/contrib/blob/78f548c7c1fab987b5e8cbfd2d1348374ca01d86/Examples/aks-python-helloworld/README.rst#L26)):*
> ```reStructuredText
>    and allow insecure runtime arguments::
> 
>        ./gsc build --insecure-args -c python python.manifest
> ```

`-c` is wrong here, should be just removed.
___
*[`Examples/aks-python-helloworld/README.rst` line 42 at r1](https://reviewable.io/reviews/gramineproject/contrib/6#-N3U8Gf72jxmqK1fhXfZ:-N3U8Gf72jxmqK1fhXf_:b-60bbah) ([raw file](https://github.com/gramineproject/contrib/blob/78f548c7c1fab987b5e8cbfd2d1348374ca01d86/Examples/aks-python-helloworld/README.rst#L42)):*
> ```reStructuredText
> #. Create job deployment file :file:`gsc-aks-python-deployment.yaml` for AKS. It specifies
>    the underlying Docker image and the insecure arguments (in this case Python
>    code to print "HelloWorld!")::
> ```

You already have this file with exactly the same contents. Please just remove this bullet item and the corresponding code snippet.


<!-- Sent from Reviewable.io -->

2022-06-01 12:50 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/6)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @aneessahib)

___
*[`Examples/aks-python-helloworld/gsc-aks-python-deployment.yaml` line 20 at r1](https://reviewable.io/reviews/gramineproject/contrib/6#-N3UEXZQ1AHgg7JD7bcB:-N3UJHDL0BaBRJo_An0O:be27df7) ([raw file](https://github.com/gramineproject/contrib/blob/78f548c7c1fab987b5e8cbfd2d1348374ca01d86/Examples/aks-python-helloworld/gsc-aks-python-deployment.yaml#L20)):*
<details><summary><i>Previously, mythi (Mikko Ylinen) wrote…</i></summary><blockquote>

The AKS documentation uses two different resource names. It's better to use "sgx.intel.com/epc: 256Mi" (or 512). Ideally, the resource requests matches the targeted EPC consumption (from sgx.enclave_size).
</blockquote></details>

@aneessahib Please also fix this line, according to Mikko's comment.


<!-- Sent from Reviewable.io -->

2022-06-01 16:06 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/6)* status: 0 of 4 files reviewed, 12 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @dimakuv, and @mythi)

___
*[`Examples/aks-python-helloworld/gsc-aks-python-deployment.yaml` line 20 at r1](https://reviewable.io/reviews/gramineproject/contrib/6#-N3UEXZQ1AHgg7JD7bcB:-N3Uzq6o5toah6cipQAS:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/78f548c7c1fab987b5e8cbfd2d1348374ca01d86/Examples/aks-python-helloworld/gsc-aks-python-deployment.yaml#L20)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@aneessahib Please also fix this line, according to Mikko's comment.
</blockquote></details>

Done.
___
*[`Examples/aks-python-helloworld/python.manifest` line 1 at r1](https://reviewable.io/reviews/gramineproject/contrib/6#-N3U4v4-1LxlzkXyjKHV:-N3UzrDV8Q-Nw6oOUTp1:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/78f548c7c1fab987b5e8cbfd2d1348374ca01d86/Examples/aks-python-helloworld/python.manifest#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could we increase to `512M`? 256MB feels too small, and may suddenly result in memory errors. I'd feel safer with a slightly bigger enclave size.
</blockquote></details>

Done.
___
*[`Examples/aks-python-helloworld/python.manifest` line 6 at r1](https://reviewable.io/reviews/gramineproject/contrib/6#-N3U53g-1wplLPpDUtxL:-N3Uzs_p7jNiIuOopD3U:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/78f548c7c1fab987b5e8cbfd2d1348374ca01d86/Examples/aks-python-helloworld/python.manifest#L6)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Let's just remove these three lines. They are only confusing. And we already have this "test" manifest in the proper GSC repo, so we don't need these testing lines in here.
</blockquote></details>

Done.
___
*[`Examples/aks-python-helloworld/README.rst` line 1 at r1](https://reviewable.io/reviews/gramineproject/contrib/6#-N3U6iF95mEiRT9pJ-Nv:-N3Uzy_LCHOeD-RquHaa:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/78f548c7c1fab987b5e8cbfd2d1348374ca01d86/Examples/aks-python-helloworld/README.rst#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why RST? We typically have `.md` (Markdown) formatting for these files.

This example will be typically read on GitHub, and GitHub is not very good at rendering RST files: https://github.com/aneessahib/contrib/tree/aks-python/Examples/aks-python-helloworld (see how the `warning` snippet got incorrectly rendered).

Please change to MD.
</blockquote></details>

Done.
___
*[`Examples/aks-python-helloworld/README.rst` line 4 at r1](https://reviewable.io/reviews/gramineproject/contrib/6#-N3U71A79Q9AZjLGlMYu:-N3UzzAd0A73Xc470byb:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/78f548c7c1fab987b5e8cbfd2d1348374ca01d86/Examples/aks-python-helloworld/README.rst#L4)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`section` -> `example`
</blockquote></details>

Done.
___
*[`Examples/aks-python-helloworld/README.rst` line 5 at r1](https://reviewable.io/reviews/gramineproject/contrib/6#-N3U6YwFAHzzYCPMhyJc:-N3V-0Sh6YPZVPITcxwQ:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/78f548c7c1fab987b5e8cbfd2d1348374ca01d86/Examples/aks-python-helloworld/README.rst#L5)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`readily to` -> `readily`
</blockquote></details>

Done.
___
*[`Examples/aks-python-helloworld/README.rst` line 12 at r1](https://reviewable.io/reviews/gramineproject/contrib/6#-N3U7Cc51hvr2wz1E4Bg:-N3V-8fp0baTXh6gtdsQ:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/78f548c7c1fab987b5e8cbfd2d1348374ca01d86/Examples/aks-python-helloworld/README.rst#L12)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would just point to the `GSC documentation` (https://gramine.readthedocs.io/projects/gsc)
</blockquote></details>

Done.
___
*[`Examples/aks-python-helloworld/README.rst` line 18 at r1](https://reviewable.io/reviews/gramineproject/contrib/6#-N3U7LQ45qQo0tRZpMke:-N3V0-da2l0hrh6Wxmh5:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/78f548c7c1fab987b5e8cbfd2d1348374ca01d86/Examples/aks-python-helloworld/README.rst#L18)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

But you already have this file. Delete this bullet item.
</blockquote></details>

Done.
___
*[`Examples/aks-python-helloworld/README.rst` line 23 at r1](https://reviewable.io/reviews/gramineproject/contrib/6#-N3U7Xjt-Dx1LU1q0SVT:-N3V00rM173pkjYll0fb:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/78f548c7c1fab987b5e8cbfd2d1348374ca01d86/Examples/aks-python-helloworld/README.rst#L23)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`using GSC`, and no need to put the link -- we already provided the link above.
</blockquote></details>

Done.
___
*[`Examples/aks-python-helloworld/README.rst` line 26 at r1](https://reviewable.io/reviews/gramineproject/contrib/6#-N3U7rScCL7s8reyIRku:-N3V01Zj5K0yR_5mv5yL:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/78f548c7c1fab987b5e8cbfd2d1348374ca01d86/Examples/aks-python-helloworld/README.rst#L26)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`-c` is wrong here, should be just removed.
</blockquote></details>

Done.
___
*[`Examples/aks-python-helloworld/README.rst` line 42 at r1](https://reviewable.io/reviews/gramineproject/contrib/6#-N3U8Gf72jxmqK1fhXfZ:-N3V02VIEl99aiWx7lsV:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/78f548c7c1fab987b5e8cbfd2d1348374ca01d86/Examples/aks-python-helloworld/README.rst#L42)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You already have this file with exactly the same contents. Please just remove this bullet item and the corresponding code snippet.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-01 16:37 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/6)* status: 0 of 4 files reviewed, 12 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @dimakuv, and @mythi)

___
*[`Examples/aks-python-helloworld/gsc-aks-python-deployment.yaml` line 20 at r1](https://reviewable.io/reviews/gramineproject/contrib/6#-N3UEXZQ1AHgg7JD7bcB:-N3V6yu5BN1TW-GD8WuH:b-9bp4nw) ([raw file](https://github.com/gramineproject/contrib/blob/78f548c7c1fab987b5e8cbfd2d1348374ca01d86/Examples/aks-python-helloworld/gsc-aks-python-deployment.yaml#L20)):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@mythi - The pod isn't starting with this change (status Pending). This is what i gave `sgx.intel.com/epc: "512Mi"`


<!-- Sent from Reviewable.io -->

2022-06-01 16:46 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/6)* status: 0 of 4 files reviewed, 12 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @dimakuv, and @mythi)

___
*[`Examples/aks-python-helloworld/gsc-aks-python-deployment.yaml` line 20 at r1](https://reviewable.io/reviews/gramineproject/contrib/6#-N3UEXZQ1AHgg7JD7bcB:-N3V8uWeBcOv4PnqZ6p2:b-ob2sh3) ([raw file](https://github.com/gramineproject/contrib/blob/78f548c7c1fab987b5e8cbfd2d1348374ca01d86/Examples/aks-python-helloworld/gsc-aks-python-deployment.yaml#L20)):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

@mythi - The pod isn't starting with this change (status Pending). This is what i gave `sgx.intel.com/epc: "512Mi"`
</blockquote></details>

works with `sgx.intel.com/epc: "10Mi"` , and `sgx.enclave_size = "512M"`


<!-- Sent from Reviewable.io -->

2022-06-01 16:52 UTC, mythi reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/6)* status: 0 of 4 files reviewed, 12 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @dimakuv)

___
*[`Examples/aks-python-helloworld/gsc-aks-python-deployment.yaml` line 20 at r1](https://reviewable.io/reviews/gramineproject/contrib/6#-N3UEXZQ1AHgg7JD7bcB:-N3V8iVB2nliSo_S9yGE:b-dy782e) ([raw file](https://github.com/gramineproject/contrib/blob/78f548c7c1fab987b5e8cbfd2d1348374ca01d86/Examples/aks-python-helloworld/gsc-aks-python-deployment.yaml#L20)):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

works with `sgx.intel.com/epc: "10Mi"` , and `sgx.enclave_size = "512M"`
</blockquote></details>

I see. Do you follow this guide https://docs.microsoft.com/en-us/azure/confidential-computing/confidential-enclave-nodes-aks-get-started or how is the cluster set up? what do you get with "kubectl get node -o json| jq .items[].status.allocatable"


<!-- Sent from Reviewable.io -->

2022-06-01 16:53 UTC, dimakuv requested changes
> Reviewed 3 of 4 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/6)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib)

___
*[`Examples/aks-python-helloworld/README.md` line 2 at r3](https://reviewable.io/reviews/gramineproject/contrib/6#-N3V93ad-GHVsmuwJKgw:-N3V93ad-GHVsmuwJKgx:b-7z4orw) ([raw file](https://github.com/gramineproject/contrib/blob/21e8944e0626951f32551e6aa6f221dd5ecbd5f3/Examples/aks-python-helloworld/README.md#L2)):*
> ```Markdown
> Graminizing Python Docker image
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> ```

You need to change to Markdown formatting. Currently it doesn't render at all: https://github.com/aneessahib/contrib/tree/aks-python/Examples/aks-python-helloworld

Just follow the format of other examples, e.g. https://raw.githubusercontent.com/aneessahib/contrib/aks-python/Examples/aks-attestation/README.md
___
*[`Examples/aks-python-helloworld/README.md` line 12 at r4](https://reviewable.io/reviews/gramineproject/contrib/6#-N3V9Jjt7o-f8jAX8Bq8:-N3V9Jjt7o-f8jAX8Bq9:bly3ons) ([raw file](https://github.com/gramineproject/contrib/blob/2ff5a6a173ee17a488b118e17553cf27fac044db/Examples/aks-python-helloworld/README.md#L12)):*
> ```Markdown
>    This example relies on insecure arguments provided at runtime and should not
>    be used production. To use trusted arguments, please see `GSC documentation
>    <https://gramine.readthedocs.io/projects/gsc>`__.
> ```

The `warning` thing doesn't work in Markdown. Simply reformat to:
```
*Warning:* this example relies on insecure arguments provided at runtime and should not
be used in production. To use trusted arguments, please see [GSC documentation](https://gramine.readthedocs.io/projects/gsc/).
```
___
*[`Examples/aks-python-helloworld/README.md` line 14 at r4](https://reviewable.io/reviews/gramineproject/contrib/6#-N3V9igBDZimZ2nicZA9:-N3V9igBDZimZ2nicZAA:bx92pno) ([raw file](https://github.com/gramineproject/contrib/blob/2ff5a6a173ee17a488b118e17553cf27fac044db/Examples/aks-python-helloworld/README.md#L14)):*
> ```Markdown
>    <https://gramine.readthedocs.io/projects/gsc>`__.
> 
> #. Pull Python image::
> ```

`#.` doesn't work in Markdown. Simply `-`.
___
*[`Examples/aks-python-helloworld/README.md` line 14 at r4](https://reviewable.io/reviews/gramineproject/contrib/6#-N3V9l102hV5jl2fmApo:-N3V9l102hV5jl2fmApp:bd7tzgc) ([raw file](https://github.com/gramineproject/contrib/blob/2ff5a6a173ee17a488b118e17553cf27fac044db/Examples/aks-python-helloworld/README.md#L14)):*
> ```Markdown
>    <https://gramine.readthedocs.io/projects/gsc>`__.
> 
> #. Pull Python image::
> ```

`::` doesn't work in Markdown. Simply `:`.


<!-- Sent from Reviewable.io -->

2022-06-01 18:05 UTC, mythi reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/6)* status: 3 of 4 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @dimakuv)

___
*[`Examples/aks-python-helloworld/gsc-aks-python-deployment.yaml` line 20 at r1](https://reviewable.io/reviews/gramineproject/contrib/6#-N3UEXZQ1AHgg7JD7bcB:-N3VQOd1AsuAZe53rLHb:b6j3hcd) ([raw file](https://github.com/gramineproject/contrib/blob/78f548c7c1fab987b5e8cbfd2d1348374ca01d86/Examples/aks-python-helloworld/gsc-aks-python-deployment.yaml#L20)):*
> Going by this I have only 58MB of usable EPC? 

oh, looks like it. is this a DCsv2 instance?


<!-- Sent from Reviewable.io -->

2022-06-02 06:48 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/6)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @mythi)

___
*[`Examples/aks-python-helloworld/gsc-aks-python-deployment.yaml` line 20 at r1](https://reviewable.io/reviews/gramineproject/contrib/6#-N3UEXZQ1AHgg7JD7bcB:-N3Y8pHp2JZ88P-dpPkI:bb2490x) ([raw file](https://github.com/gramineproject/contrib/blob/78f548c7c1fab987b5e8cbfd2d1348374ca01d86/Examples/aks-python-helloworld/gsc-aks-python-deployment.yaml#L20)):*
> Going by this I have only 58MB of usable EPC? Yet everything works with 10MiB resource, and 512M enclave size.

Just a note: the enclave size (`sgx.enclave_size`) is about *virtual memory*, whereas EPC is about *physical memory*. One can multiplex as much virtual memory on a small amount of physical memory, no issues here. So 512MB of enclave size is multiplexed on 10MB of physical EPC -- this is totally fine, just has a performance penalty.
___
*[`Examples/aks-python-helloworld/README.md` line 9 at r6](https://reviewable.io/reviews/gramineproject/contrib/6#-N3Y9NL82XYCEw_J8881:-N3Y9NL82XYCEw_J8882:b-q2g8xz) ([raw file](https://github.com/gramineproject/contrib/blob/c1b62888fd5dda8e5dd55f270a5516dc6fd34edd/Examples/aks-python-helloworld/README.md#L9)):*
> ```Markdown
>    *Warning:* this example relies on insecure arguments provided at runtime and
>    should not be used production. To use trusted arguments, please see
>    [GSC documentation] (https://gramine.readthedocs.io/projects/gsc).
> ```

This link doesn't render well: https://github.com/aneessahib/contrib/tree/aks-python/Examples/aks-python-helloworld

This is because you have a space between `[GSC documentation]` and `(https://...)`. Please remove the space, and everything will render fine.
___
*[`Examples/aks-python-helloworld/README.md` line 9 at r6](https://reviewable.io/reviews/gramineproject/contrib/6#-N3Y9Wc4DjOkipGlWPK-:-N3Y9Wc4DjOkipGlWPK0:b-u23xqe) ([raw file](https://github.com/gramineproject/contrib/blob/c1b62888fd5dda8e5dd55f270a5516dc6fd34edd/Examples/aks-python-helloworld/README.md#L9)):*
> ```Markdown
>    *Warning:* this example relies on insecure arguments provided at runtime and
>    should not be used production. To use trusted arguments, please see
>    [GSC documentation] (https://gramine.readthedocs.io/projects/gsc).
> ```

There is no need to have a 3-space indentation for these lines. Please remove the indentation.
___
*[`Examples/aks-python-helloworld/README.md` line 11 at r6](https://reviewable.io/reviews/gramineproject/contrib/6#-N3Y9hMh8Znl6mQoNnHD:-N3Y9hMh8Znl6mQoNnHE:bbrq73o) ([raw file](https://github.com/gramineproject/contrib/blob/c1b62888fd5dda8e5dd55f270a5516dc6fd34edd/Examples/aks-python-helloworld/README.md#L11)):*
> ```Markdown
>    [GSC documentation] (https://gramine.readthedocs.io/projects/gsc).
> 
> ## Pull Python image:
> ```

This "section formatting" looks ugly: https://github.com/aneessahib/contrib/tree/aks-python/Examples/aks-python-helloworld

Please just use the bullet item list, like this:
```
- Pull Python image:

    docker pull python

- Graminize the Python image using GSC, and allow insecure runtime arguments:

    ./gsc build --insecure-args python python.manifest

... and so on ....
```


<!-- Sent from Reviewable.io -->

2022-06-02 07:32 UTC, mythi reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/6)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib)

___
*[`Examples/aks-python-helloworld/gsc-aks-python-deployment.yaml` line 20 at r1](https://reviewable.io/reviews/gramineproject/contrib/6#-N3UEXZQ1AHgg7JD7bcB:-N3YGzMX-ZD0Cc-b-OVK:b-dg7g1b) ([raw file](https://github.com/gramineproject/contrib/blob/78f548c7c1fab987b5e8cbfd2d1348374ca01d86/Examples/aks-python-helloworld/gsc-aks-python-deployment.yaml#L20)):*
> multiplexed on 10MB of physical EPC -- this is totally fine, just has a performance penalty.

not 10MB but 58MB (which is the amount of EPC available on that node), right? there will be unexpected issues in the future when the EPC backing store is properly accounted from the containers' mem cgroup and containers have memory limits set. That's why I think it would be a good example to request EPC based on what the enclave size is. But the reality is that any value smaller than the max EPC capacity on the node will work today.


<!-- Sent from Reviewable.io -->

2022-06-02 07:49 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/6)* status: 3 of 4 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @dimakuv)

___
*[`Examples/aks-python-helloworld/gsc-aks-python-deployment.yaml` line 20 at r1](https://reviewable.io/reviews/gramineproject/contrib/6#-N3UEXZQ1AHgg7JD7bcB:-N3YNtxp6QeAEPYd_m10:baf3023) ([raw file](https://github.com/gramineproject/contrib/blob/78f548c7c1fab987b5e8cbfd2d1348374ca01d86/Examples/aks-python-helloworld/gsc-aks-python-deployment.yaml#L20)):*
<details><summary><i>Previously, mythi (Mikko Ylinen) wrote…</i></summary><blockquote>

> multiplexed on 10MB of physical EPC -- this is totally fine, just has a performance penalty.
not 10MB but 58MB (which is the amount of EPC available on that node), right? there will be unexpected issues in the future when the EPC backing store is properly accounted from the containers' mem cgroup and containers have memory limits set. That's why I think it would be a good example to request EPC based on what the enclave size is. But the reality is that any value smaller than the max EPC capacity on the node will work today.
</blockquote></details>

@mythi Standard_DC2s_v2
___
*[`Examples/aks-python-helloworld/README.md` line 9 at r6](https://reviewable.io/reviews/gramineproject/contrib/6#-N3Y9NL82XYCEw_J8881:-N3YMsd_Di-FDNqFp9AM:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/c1b62888fd5dda8e5dd55f270a5516dc6fd34edd/Examples/aks-python-helloworld/README.md#L9)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This link doesn't render well: https://github.com/aneessahib/contrib/tree/aks-python/Examples/aks-python-helloworld

This is because you have a space between `[GSC documentation]` and `(https://...)`. Please remove the space, and everything will render fine.
</blockquote></details>

Done.
___
*[`Examples/aks-python-helloworld/README.md` line 9 at r6](https://reviewable.io/reviews/gramineproject/contrib/6#-N3Y9Wc4DjOkipGlWPK-:-N3YMu1FAyUauBxZ5lYn:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/c1b62888fd5dda8e5dd55f270a5516dc6fd34edd/Examples/aks-python-helloworld/README.md#L9)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

There is no need to have a 3-space indentation for these lines. Please remove the indentation.
</blockquote></details>

Done.
___
*[`Examples/aks-python-helloworld/README.md` line 11 at r6](https://reviewable.io/reviews/gramineproject/contrib/6#-N3Y9hMh8Znl6mQoNnHD:-N3YMwlb9bbhInVHD2be:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/c1b62888fd5dda8e5dd55f270a5516dc6fd34edd/Examples/aks-python-helloworld/README.md#L11)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This "section formatting" looks ugly: https://github.com/aneessahib/contrib/tree/aks-python/Examples/aks-python-helloworld

Please just use the bullet item list, like this:
```
- Pull Python image:

    docker pull python

- Graminize the Python image using GSC, and allow insecure runtime arguments:

    ./gsc build --insecure-args python python.manifest

... and so on ....
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-02 07:52 UTC, dimakuv reviewed
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/6)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/6#-N3YOeaZ44V8GtfCaGZp:-N3YOeaZ44V8GtfCaGZq:bgunbml) (no related file):*
Looks good to me now! Thanks!

@mkow Could you please review, and ask one more ITL person to review?

___
___
*[`Examples/aks-python-helloworld/gsc-aks-python-deployment.yaml` line 20 at r1](https://reviewable.io/reviews/gramineproject/contrib/6#-N3UEXZQ1AHgg7JD7bcB:-N3YORKv6-Hv9Lw_HROe:b1wwgj7) ([raw file](https://github.com/gramineproject/contrib/blob/78f548c7c1fab987b5e8cbfd2d1348374ca01d86/Examples/aks-python-helloworld/gsc-aks-python-deployment.yaml#L20)):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

@mythi Standard_DC2s_v2
</blockquote></details>

Thanks @mythi for clarification. Well, since it doesn't work for at least some CC VM instances, let's keep at `10Mi` for now.


<!-- Sent from Reviewable.io -->

2022-06-02 08:04 UTC, mythi reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/6)* status: 3 of 4 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @dimakuv)

___
*[`Examples/aks-python-helloworld/gsc-aks-python-deployment.yaml` line 20 at r1](https://reviewable.io/reviews/gramineproject/contrib/6#-N3UEXZQ1AHgg7JD7bcB:-N3YRMIA9bWeQN3qjgyS:bdoj9ep) ([raw file](https://github.com/gramineproject/contrib/blob/78f548c7c1fab987b5e8cbfd2d1348374ca01d86/Examples/aks-python-helloworld/gsc-aks-python-deployment.yaml#L20)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Thanks @mythi for clarification. Well, since it doesn't work for at least some CC VM instances, let's keep at `10Mi` for now.
</blockquote></details>

Agree, 10Mi is fine. (FWIW, DCsv3 instances went GA last week and you'll get more EPC... )


<!-- Sent from Reviewable.io -->

2022-06-02 12:27 UTC, mkow submitted a review, later dismissed
> Reviewed 2 of 4 files at r2, 1 of 1 files at r4, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/6)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @aneessahib)



<!-- Sent from Reviewable.io -->

2022-06-02 14:29 UTC, woju requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/6)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @aneessahib)

___
*[`Examples/aks-python-helloworld/gsc-aks-python-deployment.yaml` line 17 at r8](https://reviewable.io/reviews/gramineproject/contrib/6#-N3Zmtah3Qh2P0e-FPGa:-N3Zmtah3Qh2P0e-FPGb:bs6gyl2) ([raw file](https://github.com/gramineproject/contrib/blob/2d37149e6fb70e512e92a4ab75e674d96a9464f1/Examples/aks-python-helloworld/gsc-aks-python-deployment.yaml#L17)):*
> ```YAML
>           image:  <dockerhubusername>/gsc-aks-python
>           imagePullPolicy: Always
>           args: ["-c", "print('HelloWorld!')"]
> ```

I object to putting `args:` in a deployment, because there isn't a case where this would be useful in production and teaches people insecure habits. Can't `print('Hello, world!')` be put in a file and properly measured? At least this needs a comment that this is in fact insecure and not for production.


<!-- Sent from Reviewable.io -->

2022-06-02 17:42 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/6)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @woju)

___
*[`Examples/aks-python-helloworld/gsc-aks-python-deployment.yaml` line 17 at r8](https://reviewable.io/reviews/gramineproject/contrib/6#-N3Zmtah3Qh2P0e-FPGa:-N3_Uj34A8uZKEEk9-yM:btossze) ([raw file](https://github.com/gramineproject/contrib/blob/2d37149e6fb70e512e92a4ab75e674d96a9464f1/Examples/aks-python-helloworld/gsc-aks-python-deployment.yaml#L17)):*
> Can't `print('Hello, world!')` be put in a file and properly measured?

Not really, because here we're using GSC, and it actually expects arguments to be defined in the original Docker image. But we're using the original Docker image from DockerHub (the classic `python` image), which has no arguments. So GSC has no "simple" way of putting args in a file.

Two correct ways to implement this would be:
1. have `loader.argv = ["-c", "print('HelloWorld!')"]` in the manifest -- but Gramine still doesn't have this feature...
2. create a new Docker image based on the original Python Docker image, with a sole change of adding these args to the `ENTRYPOINT`.

The first one is impossible, the second one is too cumbersome for a simple example.

So I vote for a inline comment here `WARNING: providing args in the deployment file is insecure!`


<!-- Sent from Reviewable.io -->

2022-06-03 07:09 UTC, dimakuv reviewed
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/6)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @woju)



<!-- Sent from Reviewable.io -->

2022-06-07 10:37 UTC, woju submitted a review, later dismissed
> Reviewed 1 of 4 files at r2, 1 of 1 files at r8, 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/6)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2022-06-07 11:19 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/6)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/contrib/6#-N3U4fTg9fjaVDnueaHT):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-07 12:12 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/6)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-06-07 13:06 UTC, merged