[Curated-Apps] Use buildtype arg as debug flag is removed in GSC
gramineproject/contrib pull request #60
Opened 2023-10-19 07:42 UTC by jkr0103

Latest GSC doesn't support `--debug` flag- instead supports `--buildtype` with values `release`, `debug` and `debugoptimized`.
This PR is to adapt the changes in GSC. Also now Curated-Apps uses `argparse` for processing the arguments.

2023-10-19 11:30 UTC, dimakuv requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/60)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @jkr0103)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/contrib/60#-Nh6evRZD9m2MWwzRFp7):*
Please add backticks around `buildtype` and `debug`

Well, let's just rephrase:
```
[Curated-Apps] Use `--buildtype` instead of `--debug` in GSC

The `--debug` flag was recently removed from GSC and superseded
by `--buildtype`.
```
___
*[`Intel-Confidential-Compute-for-X/curate.py` line 306 at r1](https://reviewable.io/reviews/gramineproject/contrib/60#-Nh6gjs57seJJSwyHiv3:-Nh6gjs57seJJSwyHiv4:b-rv73l6) ([raw file](https://github.com/gramineproject/contrib/blob/26ad6b85c222d033db596effabbac6c5996eba69/Intel-Confidential-Compute-for-X/curate.py#L306)):*
> ```Python
> def curate_gsc_image(args):
>     base_image_name = args.base_image_name
>     workload_type = args.workload_type
> ```

Why do you introduce helper variables for these two, but not the other two (`args.test` and `args.buildtype`)? Please either introduce helper variables for **all** or for **none**.
___
*[`Intel-Confidential-Compute-for-X/curate.py` line 326 at r1](https://reviewable.io/reviews/gramineproject/contrib/60#-Nh6gOfX5bEFisGslgzl:-Nh6gOfX5bEFisGslgzm:bjnp343) ([raw file](https://github.com/gramineproject/contrib/blob/26ad6b85c222d033db596effabbac6c5996eba69/Intel-Confidential-Compute-for-X/curate.py#L326)):*
> ```Python
> 
>     if args.test:
>         create_test_image(docker_socket, workload_type, base_image_name, image_distro, args.buildtype,
> ```

Overflows the 100 char limit
___
*[`Intel-Confidential-Compute-for-X/curate.py` line 543 at r1](https://reviewable.io/reviews/gramineproject/contrib/60#-Nh6fljZ1M2OpWNL1_lx:-Nh6fljZ1M2OpWNL1_ly:bonfk6x) ([raw file](https://github.com/gramineproject/contrib/blob/26ad6b85c222d033db596effabbac6c5996eba69/Intel-Confidential-Compute-for-X/curate.py#L543)):*
> ```Python
> 
> parser = argparse.ArgumentParser()
> parser.add_argument('workload_type', help='Type of workload (refer to workload/sub-directory for'
> ```

You need to add a space after `for`, otherwise you'll have `forfull` in the output
___
*[`Intel-Confidential-Compute-for-X/curate.py` line 544 at r1](https://reviewable.io/reviews/gramineproject/contrib/60#-Nh6g8oQCOrSXXzfeN3y:-Nh6g8oQCOrSXXzfeN3z:b-rpytpx) ([raw file](https://github.com/gramineproject/contrib/blob/26ad6b85c222d033db596effabbac6c5996eba69/Intel-Confidential-Compute-for-X/curate.py#L544)):*
> ```Python
> parser = argparse.ArgumentParser()
> parser.add_argument('workload_type', help='Type of workload (refer to workload/sub-directory for'
>                        'full list of supported workload types) e.g. redis.')
> ```

Can you copy-paste the exact line that was in the README? I liked that description.
___
*[`Intel-Confidential-Compute-for-X/curate.py` line 545 at r1](https://reviewable.io/reviews/gramineproject/contrib/60#-Nh6gBrm3zhURIkWi021:-Nh6gBrm3zhURIkWi022:b-rpytpx) ([raw file](https://github.com/gramineproject/contrib/blob/26ad6b85c222d033db596effabbac6c5996eba69/Intel-Confidential-Compute-for-X/curate.py#L545)):*
> ```Python
> parser.add_argument('workload_type', help='Type of workload (refer to workload/sub-directory for'
>                        'full list of supported workload types) e.g. redis.')
> parser.add_argument('base_image_name', help='Base image name to be graminized.')
> ```

Can you copy-paste the exact line that was in the README? I liked that description.
___
*[`Intel-Confidential-Compute-for-X/curate.py` line 546 at r1](https://reviewable.io/reviews/gramineproject/contrib/60#-Nh6g5UX7hwe8kZupvr6:-Nh6g5UX7hwe8kZupvr7:bqaua05) ([raw file](https://github.com/gramineproject/contrib/blob/26ad6b85c222d033db596effabbac6c5996eba69/Intel-Confidential-Compute-for-X/curate.py#L546)):*
> ```Python
>                        'full list of supported workload types) e.g. redis.')
> parser.add_argument('base_image_name', help='Base image name to be graminized.')
> parser.add_argument('--test', action='store_true',
> ```

You can also add a short form `-t` here, since you have a short form for `buildtype`
___
*[`Intel-Confidential-Compute-for-X/README.md` line 92 at r1](https://reviewable.io/reviews/gramineproject/contrib/60#-Nh6fS5O9eAGuFZONv1y:-Nh6fS5O9eAGuFZONv1z:bxeq3hl) ([raw file](https://github.com/gramineproject/contrib/blob/26ad6b85c222d033db596effabbac6c5996eba69/Intel-Confidential-Compute-for-X/README.md#L92)):*
> ```Markdown
> ```
> 
> For detailed usage information
> ```

Please add `:` at the end
___
*[`Intel-Confidential-Compute-for-X/util/curation_script.sh` line 132 at r1](https://reviewable.io/reviews/gramineproject/contrib/60#-Nh6fXmz4SBlC1pLiuYY:-Nh6fXmz4SBlC1pLiuYZ:b761pn7) ([raw file](https://github.com/gramineproject/contrib/blob/26ad6b85c222d033db596effabbac6c5996eba69/Intel-Confidential-Compute-for-X/util/curation_script.sh#L132)):*
> ```Shell
>     sed -i 's|ubuntu:.*|'$distro'"|' config.yaml
> 
>     ./gsc build $cmdline_flag -b $1 $app_image_x  $WORKLOAD_DIR/$app_image_manifest
> ```

Can we use a full form `--buildtype`? I also forget what these short forms stand for.


<!-- Sent from Reviewable.io -->

2023-10-19 13:53 UTC, mkow requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/60)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @jkr0103)



<!-- Sent from Reviewable.io -->

2023-10-23 07:34 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/60)* status: 0 of 3 files reviewed, 9 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/contrib/60#-Nh6evRZD9m2MWwzRFp7):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add backticks around `buildtype` and `debug`

Well, let's just rephrase:
```
[Curated-Apps] Use `--buildtype` instead of `--debug` in GSC

The `--debug` flag was recently removed from GSC and superseded
by `--buildtype`.
```
</blockquote></details>

Done.
___
*[`Intel-Confidential-Compute-for-X/curate.py` line 306 at r1](https://reviewable.io/reviews/gramineproject/contrib/60#-Nh6gjs57seJJSwyHiv3:-NhQRn5FD0VFIo-_UM0R:b1936ts) ([raw file](https://github.com/gramineproject/contrib/blob/26ad6b85c222d033db596effabbac6c5996eba69/Intel-Confidential-Compute-for-X/curate.py#L306)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do you introduce helper variables for these two, but not the other two (`args.test` and `args.buildtype`)? Please either introduce helper variables for **all** or for **none**.
</blockquote></details>

These variables had multiple occurances but other two had only one or two, now I created helper variable for all.
___
*[`Intel-Confidential-Compute-for-X/curate.py` line 326 at r1](https://reviewable.io/reviews/gramineproject/contrib/60#-Nh6gOfX5bEFisGslgzl:-NhQRyg86ZTDWz9Qs0Ua:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/26ad6b85c222d033db596effabbac6c5996eba69/Intel-Confidential-Compute-for-X/curate.py#L326)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Overflows the 100 char limit
</blockquote></details>

Done.
___
*[`Intel-Confidential-Compute-for-X/curate.py` line 543 at r1](https://reviewable.io/reviews/gramineproject/contrib/60#-Nh6fljZ1M2OpWNL1_lx:-NhQRztSBkR3aPMPp9Mk:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/26ad6b85c222d033db596effabbac6c5996eba69/Intel-Confidential-Compute-for-X/curate.py#L543)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You need to add a space after `for`, otherwise you'll have `forfull` in the output
</blockquote></details>

Done.
___
*[`Intel-Confidential-Compute-for-X/curate.py` line 544 at r1](https://reviewable.io/reviews/gramineproject/contrib/60#-Nh6g8oQCOrSXXzfeN3y:-NhQS-VnExlOK15a9WWM:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/26ad6b85c222d033db596effabbac6c5996eba69/Intel-Confidential-Compute-for-X/curate.py#L544)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can you copy-paste the exact line that was in the README? I liked that description.
</blockquote></details>

Done.
___
*[`Intel-Confidential-Compute-for-X/curate.py` line 545 at r1](https://reviewable.io/reviews/gramineproject/contrib/60#-Nh6gBrm3zhURIkWi021:-NhQS-zX32PUsF5sL3hO:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/26ad6b85c222d033db596effabbac6c5996eba69/Intel-Confidential-Compute-for-X/curate.py#L545)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can you copy-paste the exact line that was in the README? I liked that description.
</blockquote></details>

Done.
___
*[`Intel-Confidential-Compute-for-X/curate.py` line 546 at r1](https://reviewable.io/reviews/gramineproject/contrib/60#-Nh6g5UX7hwe8kZupvr6:-NhQS0RR-kxg7fz2FWl9:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/26ad6b85c222d033db596effabbac6c5996eba69/Intel-Confidential-Compute-for-X/curate.py#L546)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You can also add a short form `-t` here, since you have a short form for `buildtype`
</blockquote></details>

Done.
___
*[`Intel-Confidential-Compute-for-X/README.md` line 92 at r1](https://reviewable.io/reviews/gramineproject/contrib/60#-Nh6fS5O9eAGuFZONv1y:-NhQS1Ll4ipfyoAhKUKc:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/26ad6b85c222d033db596effabbac6c5996eba69/Intel-Confidential-Compute-for-X/README.md#L92)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add `:` at the end
</blockquote></details>

Done.
___
*[`Intel-Confidential-Compute-for-X/util/curation_script.sh` line 132 at r1](https://reviewable.io/reviews/gramineproject/contrib/60#-Nh6fXmz4SBlC1pLiuYY:-NhQS26z6-f_VG-5I8jf:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/26ad6b85c222d033db596effabbac6c5996eba69/Intel-Confidential-Compute-for-X/util/curation_script.sh#L132)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can we use a full form `--buildtype`? I also forget what these short forms stand for.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-23 09:24 UTC, dimakuv approved these changes
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/60)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`Intel-Confidential-Compute-for-X/curate.py` line 306 at r1](https://reviewable.io/reviews/gramineproject/contrib/60#-Nh6gjs57seJJSwyHiv3:-NhQq2U9EY_3FayP-bdP:b8gypn3) ([raw file](https://github.com/gramineproject/contrib/blob/26ad6b85c222d033db596effabbac6c5996eba69/Intel-Confidential-Compute-for-X/curate.py#L306)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

These variables had multiple occurances but other two had only one or two, now I created helper variable for all.
</blockquote></details>

Thanks, this way it is more readable (at least to me).


<!-- Sent from Reviewable.io -->

2023-10-24 07:15 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/60)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2023-10-25 11:38 UTC, merged