Add end to end GSC image curation package for better user experience
gramineproject/contrib pull request #7
Opened 2022-08-22 13:42 UTC by aneessahib

Signed-off-by: aneessahib <anees.a.sahib@intel.com>
This application will provide step-by-step guidance in creating your own custom containers protected by Gramine. 
This application will provide step-by-step guidance in creating your own custom containers protected by Gramine. The commentary window to the right will provide more context for each of the steps.

The target deployment environment is assumed to be an Azure Confidential compute instance with out of tree DCAP driver. Following stages are involved in the GSC image curation:
- Enclave Signing Key
- Attestation
- Secret Provisioning
- Encrypted Files
- Environment Variables
- Runtime Arguments
- Execution & Debug

2022-08-26 11:33 UTC, dimakuv requested changes
> Reviewed 19 of 28 files at r1, 7 of 7 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/7)* status: all files reviewed, 40 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/7#-NAOqmDV4DscKOLPu6W6:-NAOqmDV4DscKOLPu6W7:ba4glm1) (no related file):*
It would be *really* helpful to add a PDF presentation that explains what this is, how it is supposed to be used, plus the slides with a complete walk-through of all the steps in this curation script.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/7#-NAOvFL187_a6zX4J8s1:-NAOvFL187_a6zX4J8s2:b-8v8zrf) (no related file):*
I see no reason to call the directory `verifier_image/`. Just rename it to `verifier/`.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/7#-NAOvMttBvH89FWd7mjk:-NAOvMttBvH89FWd7mjl:b-f52so7) (no related file):*
I would create a directory called `util/` or something, and put internal files there: `config.yaml`, `constants.py`, `curation_script.sh`.

___
___
*[`GSC-Image-Curation/.gitignore` line 3 at r3](https://reviewable.io/reviews/gramineproject/contrib/7#-NAOtDiAEQCscD27bbB_:-NAOtDiAEQCscD27bbBa:b-upo67z) ([raw file](https://github.com/gramineproject/contrib/blob/c2401566b780a71ea25e07737bd132a8c0375fed/GSC-Image-Curation/.gitignore#L3)):*
> ```ignore
> __pycache__/
> commands.txt
> *.log
> ```

All gitignore files that are specific to the current directory should start with `/`. So here the first two entries should be prepended with `/`
___
*[`GSC-Image-Curation/config.yaml` line 3 at r3](https://reviewable.io/reviews/gramineproject/contrib/7#-NAOoTA37yjphZ-RVIiB:-NAOoTA37yjphZ-RVIiC:b-f2299g) ([raw file](https://github.com/gramineproject/contrib/blob/c2401566b780a71ea25e07737bd132a8c0375fed/GSC-Image-Curation/config.yaml#L3)):*
> ```YAML
> # Specify the OS distro. Currently tested distros are
> # ``ubuntu:18.04``, ``ubuntu:20.04``, ``ubuntu:21.04`` and ``centos:8``.
> Distro: "ubuntu:18.04"
> ```

Can we make this tunable? At least Ubuntu 18 and 20 (and in the near future 22) should be tunable.
___
*[`GSC-Image-Curation/config.yaml` line 32 at r3](https://reviewable.io/reviews/gramineproject/contrib/7#-NAOofUKBo1nIuN3NthM:-NAOofUKBo1nIuN3NthN:b-4fcnqi) ([raw file](https://github.com/gramineproject/contrib/blob/c2401566b780a71ea25e07737bd132a8c0375fed/GSC-Image-Curation/config.yaml#L32)):*
> ```YAML
> SGXDriver:
>     Repository: "https://github.com/intel/SGXDataCenterAttestationPrimitives.git"
>     Branch:     "DCAP_1.11 && cp -r driver/linux/* ."
> ```

This should be also tunable. This is currently specific to Ubuntu 18. But for Ubuntu 20 and beyond, this is not needed (on MS Azure CC, I mean).

You can add one more setting in your Curation script: "What OS distro do you want?" And based on the answer -- 18 or 20 -- update this file, or even generate it on the fly.
___
*[`GSC-Image-Curation/constants.py` line 1 at r3](https://reviewable.io/reviews/gramineproject/contrib/7#-NAOp0gP20Z4Q5MvkKlM:-NAOp0gP20Z4Q5MvkKlN:bqvo4rp) ([raw file](https://github.com/gramineproject/contrib/blob/c2401566b780a71ea25e07737bd132a8c0375fed/GSC-Image-Curation/constants.py#L1)):*
> ```Python
> #!/usr/bin/env python
> ```

FYI: I did a quick high-level review. Didn't look at this file in details.
___
*[`GSC-Image-Curation/curate.py` line 1 at r3](https://reviewable.io/reviews/gramineproject/contrib/7#-NAOpBcYCWQ9IP7W_Zq2:-NAOpBcYCWQ9IP7W_Zq3:b-uf1xtf) ([raw file](https://github.com/gramineproject/contrib/blob/c2401566b780a71ea25e07737bd132a8c0375fed/GSC-Image-Curation/curate.py#L1)):*
> ```Python
> #!/usr/bin/python
> ```

Can you add a top-level comment as to how this works? I would like to have an overview of the technicalities of these scripts, how they interact with each other, etc.

I think this would be the best way to have such technical information.
___
*[`GSC-Image-Curation/curate.py` line 21 at r3](https://reviewable.io/reviews/gramineproject/contrib/7#-NAOpM_t9bIu8DCN4gqt:-NAOpM_t9bIu8DCN4gqu:b-xmrygr) ([raw file](https://github.com/gramineproject/contrib/blob/c2401566b780a71ea25e07737bd132a8c0375fed/GSC-Image-Curation/curate.py#L21)):*
> ```Python
> from sys import argv
> 
> def initwindows():
> ```

Could you visually split the two functionalities present in this script? We have "GUI interface" functions and "Technical" functions here intermixed.

I suggest to group GUI-interface functions together, under one comment `# ------- GUI curses interface ----------`. And technical functions under another comment `# ----- docker interactions ---------`
___
*[`GSC-Image-Curation/curate.py` line 116 at r3](https://reviewable.io/reviews/gramineproject/contrib/7#-NAOplWF0qB9In9-_BdW:-NAOplWF0qB9In9-_BdX:bgs39h4) ([raw file](https://github.com/gramineproject/contrib/blob/c2401566b780a71ea25e07737bd132a8c0375fed/GSC-Image-Curation/curate.py#L116)):*
> ```Python
>             if default:
>                 file = default
>                 return file   
> ```

Please remove trailing whitespace everywhere.
___
*[`GSC-Image-Curation/curate.py` line 182 at r3](https://reviewable.io/reviews/gramineproject/contrib/7#-NAOpsqEC-sUxw3BHe5H:-NAOpsqEC-sUxw3BHe5I:b-bz9gzz) ([raw file](https://github.com/gramineproject/contrib/blob/c2401566b780a71ea25e07737bd132a8c0375fed/GSC-Image-Curation/curate.py#L182)):*
> ```Python
>         sign_file = update_user_input()
>         if sign_file == 'n':
>             key_path = 'no-sign'
> ```

These seem to be some hard-coded magic keywords? Please put a comment at the top of this function explaining this.
___
*[`GSC-Image-Curation/curate.py` line 223 at r3](https://reviewable.io/reviews/gramineproject/contrib/7#-NAOq6xt5bagryZJFFr9:-NAOq6xt5bagryZJFFrA:b-xzytdd) ([raw file](https://github.com/gramineproject/contrib/blob/c2401566b780a71ea25e07737bd132a8c0375fed/GSC-Image-Curation/curate.py#L223)):*
> ```Python
> 
>     # Checking if debug flag is specified by the user
>     if argv[1] == '-d':
> ```

Is this for internal-debugging purposes? Please add a top-level comment in this file, listing all internal arguments possible in this script.
___
*[`GSC-Image-Curation/curate.py` line 278 at r3](https://reviewable.io/reviews/gramineproject/contrib/7#-NAOqRZp9WGbNVdAmtad:-NAOqRZp9WGbNVdAmtae:ba88rnf) ([raw file](https://github.com/gramineproject/contrib/blob/c2401566b780a71ea25e07737bd132a8c0375fed/GSC-Image-Curation/curate.py#L278)):*
> ```Python
>         update_user_input()
> 
> #   Obtain enclave signing key
> ```

Please make style of comments uniform -- sometimes `#` starts from beginning of line, sometimes `#` is intended
___
*[`GSC-Image-Curation/curate.py` line 286 at r3](https://reviewable.io/reviews/gramineproject/contrib/7#-NAOqZYVErvKepLYzGjQ:-NAOqZYVErvKepLYzGjR:b-uc4qk7) ([raw file](https://github.com/gramineproject/contrib/blob/c2401566b780a71ea25e07737bd132a8c0375fed/GSC-Image-Curation/curate.py#L286)):*
> ```Python
> 
>     # Remote Attestation with RA-TLS
>     update_user_and_commentary_win_array(user_console, guide_win, attestation_prompt, \
> ```

`\` is not needed in Python. Here and everywhere.
___
*[`GSC-Image-Curation/curation_script.sh` line 2 at r3](https://reviewable.io/reviews/gramineproject/contrib/7#-NAOr0GF-vSiPy1MXQt3:-NAOr0GF-vSiPy1MXQt4:bgg9xbm) ([raw file](https://github.com/gramineproject/contrib/blob/c2401566b780a71ea25e07737bd132a8c0375fed/GSC-Image-Curation/curation_script.sh#L2)):*
> ```Shell
> #!/bin/bash
> echo printing args $0 $@
> ```

Please add a top-level comment that explains:
- What this Bash script does, in steps
- Why it is separated from `curate.py`, and at which point `curate.py` calls into this Bash script
- All arguments to this Bash script and their descr [...]

2022-08-30 17:12 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/7)* status: 0 of 41 files reviewed, 40 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/7#-NAOqmDV4DscKOLPu6W6:-NAjgeXo6Kyw2GyVLeNA:bq0efpf) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

It would be *really* helpful to add a PDF presentation that explains what this is, how it is supposed to be used, plus the slides with a complete walk-through of all the steps in this curation script.
</blockquote></details>

Working on this.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/7#-NAOvFL187_a6zX4J8s1:-NAjghm14j1fi9ww4prR:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I see no reason to call the directory `verifier_image/`. Just rename it to `verifier/`.
</blockquote></details>

Done.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/7#-NAOvMttBvH89FWd7mjk:-NAjgj5s--yivki0jP6N:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would create a directory called `util/` or something, and put internal files there: `config.yaml`, `constants.py`, `curation_script.sh`.
</blockquote></details>

Done.

___
___
*[`GSC-Image-Curation/config.yaml` line 3 at r3](https://reviewable.io/reviews/gramineproject/contrib/7#-NAOoTA37yjphZ-RVIiB:-NAjiZn11Nws6_d3GjnF:b-v2dv6s) ([raw file](https://github.com/gramineproject/contrib/blob/c2401566b780a71ea25e07737bd132a8c0375fed/GSC-Image-Curation/config.yaml#L3)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can we make this tunable? At least Ubuntu 18 and 20 (and in the near future 22) should be tunable.
</blockquote></details>

I am now informing the user in the first screen itself about the system config being available at config.yaml , and that he can modify it as per his environment. Would this be enough?
___
*[`GSC-Image-Curation/config.yaml` line 32 at r3](https://reviewable.io/reviews/gramineproject/contrib/7#-NAOofUKBo1nIuN3NthM:-NAjivedBJ7K-ZINyUIk:b-7ropln) ([raw file](https://github.com/gramineproject/contrib/blob/c2401566b780a71ea25e07737bd132a8c0375fed/GSC-Image-Curation/config.yaml#L32)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This should be also tunable. This is currently specific to Ubuntu 18. But for Ubuntu 20 and beyond, this is not needed (on MS Azure CC, I mean).

You can add one more setting in your Curation script: "What OS distro do you want?" And based on the answer -- 18 or 20 -- update this file, or even generate it on the fly.
</blockquote></details>

ditto
___
*[`GSC-Image-Curation/curate.py` line 1 at r3](https://reviewable.io/reviews/gramineproject/contrib/7#-NAOpBcYCWQ9IP7W_Zq2:-NAjgwWB8pyxlZMjMFPn:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/c2401566b780a71ea25e07737bd132a8c0375fed/GSC-Image-Curation/curate.py#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can you add a top-level comment as to how this works? I would like to have an overview of the technicalities of these scripts, how they interact with each other, etc.

I think this would be the best way to have such technical information.
</blockquote></details>

Done.
___
*[`GSC-Image-Curation/curate.py` line 21 at r3](https://reviewable.io/reviews/gramineproject/contrib/7#-NAOpM_t9bIu8DCN4gqt:-NAjgy4w4NXUqOiCEVtZ:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/c2401566b780a71ea25e07737bd132a8c0375fed/GSC-Image-Curation/curate.py#L21)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you visually split the two functionalities present in this script? We have "GUI interface" functions and "Technical" functions here intermixed.

I suggest to group GUI-interface functions together, under one comment `# ------- GUI curses interface ----------`. And technical functions under another comment `# ----- docker interactions ---------`
</blockquote></details>

Done.
___
*[`GSC-Image-Curation/curate.py` line 116 at r3](https://reviewable.io/reviews/gramineproject/contrib/7#-NAOplWF0qB9In9-_BdW:-NAjh-T97VzcaLMax2X_:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/c2401566b780a71ea25e07737bd132a8c0375fed/GSC-Image-Curation/curate.py#L116)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove trailing whitespace everywhere.
</blockquote></details>

Done.
___
*[`GSC-Image-Curation/curate.py` line 182 at r3](https://reviewable.io/reviews/gramineproject/contrib/7#-NAOpsqEC-sUxw3BHe5H:-NAjh3E312VCZzYQoFDj:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/c2401566b780a71ea25e07737bd132a8c0375fed/GSC-Image-Curation/curate.py#L182)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

These seem to be some hard-coded magic keywords? Please put a comment at the top of this function explaining this.
</blockquote></details>

Done.
___
*[`GSC-Image-Curation/curate.py` line 223 at r3](https://reviewable.io/reviews/gramineproject/contrib/7#-NAOq6xt5bagryZJFFr9:-NAjh5ANErvC_lEawiav:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/c2401566b780a71ea25e07737bd132a8c0375fed/GSC-Image-Curation/curate.py#L223)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Is this for internal-debugging purposes? Please add a top-level comment in this file, listing all internal arguments possible in this script.
</blockquote></details>

Done.
___
*[`GSC-Image-Curation/curate.py` line 278 at r3](https://reviewable.io/reviews/gramineproject/contrib/7#-NAOqRZp9WGbNVdAmtad:-NAjh6mU8keVhhTm5YVL:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/c2401566b780a71ea25e07737bd132a8c0375fed/GSC-Image-Curation/curate.py#L278)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please make style of comments uniform -- sometimes `#` starts from beginning of line, sometimes `#` is intended
</blockquote></details>

Done.
___
*[`GSC-Image-Curation/curate.py` line 286 at r3](https://reviewable.io/reviews/gramineproject/contrib/7#-NAOqZYVErvKepLYzGjQ:-NAjh88K7wfi_VezAvmp:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/c2401566b780a71ea25e07737bd132a8c0375fed/GSC-Image-Curation/curate.py#L286)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`\` is not needed in Python. Here and everywhere.
</blockquote></details>

Done.
___
*[`GSC-Image-Curation/curation_script.sh` line 2 at r3](https://reviewable.io/reviews/gramineproject/contrib/7#-NAOr0GF-vSiPy1MXQt3:-NAjizX8Bcd9jCGfr0YI:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/c2401566b780a71ea25e07737bd132a8c0375fed/GSC-Image-Curation/curation_script.sh#L2)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add a top-level comment that explains:
- What this Bash script does, in steps
- Why it is separated from `curate.py`, and at which point `curate.py` calls into this Bash script
- All arguments to this Bash script and their descriptions
</blockquote></details>

Done.
___
*[`GSC-Image-Curation/curation_script.sh` line 121 at r3](https://reviewable.io/reviews/gramineproject/contrib/7#-NAOrJ804pEbGa-sSDBJ:-NAjj3jT5WH55B9jwRFU:b-qr59ad) ([raw file](https://github.com/gramineproject/contrib/blob/c2401566b78 [...]

2022-08-30 17:52 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/7)* status: 0 of 41 files reviewed, 40 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @dimakuv)

___
*[`GSC-Image-Curation/.gitignore` line 3 at r3](https://reviewable.io/reviews/gramineproject/contrib/7#-NAOtDiAEQCscD27bbB_:-NAjsJ2V2fJIUBEQ9ZGl:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/c2401566b780a71ea25e07737bd132a8c0375fed/GSC-Image-Curation/.gitignore#L3)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

All gitignore files that are specific to the current directory should start with `/`. So here the first two entries should be prepended with `/`
</blockquote></details>

Done.
___
*[`GSC-Image-Curation/README.md` line 29 at r3](https://reviewable.io/reviews/gramineproject/contrib/7#-NAOscz-8uytExEeQfls:-NAjsM3u1WQpZZzrAch3:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/c2401566b780a71ea25e07737bd132a8c0375fed/GSC-Image-Curation/README.md#L29)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do you have `sudo` everywhere? This is bad, and GSC doesn't require sudo at all. (Docker can and should be run in non-root mode these days.)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-31 09:19 UTC, dimakuv requested changes
> Reviewed 7 of 22 files at r5, 1 of 3 files at r7, 1 of 1 files at r9, 1 of 2 files at r10, 1 of 1 files at r11, 7 of 9 files at r12, 1 of 21 files at r13, 2 of 2 files at r15, 16 of 16 files at r16, 3 of 3 files at r17, 1 of 1 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/7)* status: all files reviewed, 54 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/7#-NAn0c742UEC4y9MTCfF:-NAn0c742UEC4y9MTCfG:b-63lm5o) (no related file):*
By the way, why do we call it `GSC-Image-Curation`? Shouldn't it be just `Curated-Apps`?

___
___
*[`GSC-Image-Curation/.gitignore` line 1 at r17](https://reviewable.io/reviews/gramineproject/contrib/7#-NAn-Ejs9fcsnUvSrwXD:-NAn-Ejt8LPyynDVt4jD:b-o4501l) ([raw file](https://github.com/gramineproject/contrib/blob/073b0d2a31471a8dc7ca60444c6305c646f18542/GSC-Image-Curation/.gitignore#L1)):*
> ```ignore
> /util/__pycache__/
> ```

This item should be removed from here, and instead put in a `util/.gitignore` new file.
___
*[`GSC-Image-Curation/config.yaml` line 3 at r3](https://reviewable.io/reviews/gramineproject/contrib/7#-NAOoTA37yjphZ-RVIiB:-NAn8s4E4Cr_U0SEYr2v:bxmu6q1) ([raw file](https://github.com/gramineproject/contrib/blob/c2401566b780a71ea25e07737bd132a8c0375fed/GSC-Image-Curation/config.yaml#L3)):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

I am now informing the user in the first screen itself about the system config being available at config.yaml , and that he can modify it as per his environment. Would this be enough?
</blockquote></details>

But why so complicated? Isn't the whole purpose of this curation script to *decrease* the number of files the user has to touch (to one)?

I would strongly consider creating this file on the fly by your curation script, and making these params tunable.
___
*[`GSC-Image-Curation/curate.py` line 223 at r3](https://reviewable.io/reviews/gramineproject/contrib/7#-NAOq6xt5bagryZJFFr9:-NAn4PSzDMHxKnoHpQcr:bd1a70d) ([raw file](https://github.com/gramineproject/contrib/blob/c2401566b780a71ea25e07737bd132a8c0375fed/GSC-Image-Curation/curate.py#L223)):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Please rename `d` to `debug`
___
*[`GSC-Image-Curation/curate.py` line 2 at r17](https://reviewable.io/reviews/gramineproject/contrib/7#-NAn0njG3XVodi5zgLHC:-NAn0njG3XVodi5zgLHD:b4dn8i5) ([raw file](https://github.com/gramineproject/contrib/blob/073b0d2a31471a8dc7ca60444c6305c646f18542/GSC-Image-Curation/curate.py#L2)):*
> ```Python
> #!/usr/bin/python
> # This file will provide step-by-step guidance in creating your own custom containers protected
> ```

`file` -> `script`
___
*[`GSC-Image-Curation/curate.py` line 2 at r17](https://reviewable.io/reviews/gramineproject/contrib/7#-NAn0rhuDOryzNcgj6-Q:-NAn0rhuDOryzNcgj6-R:b-9vb5nz) ([raw file](https://github.com/gramineproject/contrib/blob/073b0d2a31471a8dc7ca60444c6305c646f18542/GSC-Image-Curation/curate.py#L2)):*
> ```Python
> #!/usr/bin/python
> # This file will provide step-by-step guidance in creating your own custom containers protected
> ```

`your own custom containers` -> `custom Docker images`
___
*[`GSC-Image-Curation/curate.py` line 3 at r17](https://reviewable.io/reviews/gramineproject/contrib/7#-NAn0w2h4Vcutgh4nTFZ:-NAn0w2h4Vcutgh4nTF_:bcy525r) ([raw file](https://github.com/gramineproject/contrib/blob/073b0d2a31471a8dc7ca60444c6305c646f18542/GSC-Image-Curation/curate.py#L3)):*
> ```Python
> #!/usr/bin/python
> # This file will provide step-by-step guidance in creating your own custom containers protected
> # by Gramine. User will be prompted for input at every stage, and once the application has all
> ```

`the application` -> `the script`
___
*[`GSC-Image-Curation/curate.py` line 5 at r17](https://reviewable.io/reviews/gramineproject/contrib/7#-NAn108W1aw14fvFOLut:-NAn108W1aw14fvFOLuu:b-4ravf6) ([raw file](https://github.com/gramineproject/contrib/blob/073b0d2a31471a8dc7ca60444c6305c646f18542/GSC-Image-Curation/curate.py#L5)):*
> ```Python
> # by Gramine. User will be prompted for input at every stage, and once the application has all
> # the details, it will call a separate curation script (util/curation_script.sh) that takes the
> # user provided inputs to create the graminized container image using GSC. This python file also
> ```

`container image` -> `Docker image` ("container" and "image" are two mutually exclusive terms, they cannot be used together -- the former means "the environment that is started from the image, and does some runtime processing" whereas the latter means "the prepared environment that is stored on hard drive, and a container will be started from it").
___
*[`GSC-Image-Curation/curate.py` line 5 at r17](https://reviewable.io/reviews/gramineproject/contrib/7#-NAn1X6X204dc6wVaJEV:-NAn1X6X204dc6wVaJEW:b-eqqdib) ([raw file](https://github.com/gramineproject/contrib/blob/073b0d2a31471a8dc7ca60444c6305c646f18542/GSC-Image-Curation/curate.py#L5)):*
> ```Python
> # by Gramine. User will be prompted for input at every stage, and once the application has all
> # the details, it will call a separate curation script (util/curation_script.sh) that takes the
> # user provided inputs to create the graminized container image using GSC. This python file also
> ```

`This python file` -> `This script`
___
*[`GSC-Image-Curation/curate.py` line 8 at r17](https://reviewable.io/reviews/gramineproject/contrib/7#-NAn2A-G52CWQk4ClBwZ:-NAn2A-G52CWQk4ClBw_:bp4fgm7) ([raw file](https://github.com/gramineproject/contrib/blob/073b0d2a31471a8dc7ca60444c6305c646f18542/GSC-Image-Curation/curate.py#L8)):*
> ```Python
> # calls into a remote attestation verifier server generation script
> # (verifier/verifier_helper_script.sh) that will generate the verifier images, whose responsibility
> # would be to verify the SGX quotes sent by the graminized container image.
> ```

`...calls into a script to generate the verifier Docker image (for SGX remote attestation). The generated verifier Docker image is supposed to be started together with the graminized Docker image, to verify the SGX attestation evidence (SGX quote) sent by the latter image.`
___
*[`GSC-Image-Curation/curate.py` line 9 at r17](https://reviewable.io/reviews/gramineproject/contrib/7#-NAn2C3a-xQYvwHexR1P:-NAn2C3a-xQYvwHexR1Q:b-drfqm2) ([raw file](https://github.com/gramineproject/contrib/blob/073b0d2a31471a8dc7ca60444c6305c646f18542/GSC-Image-Curation/curate.py#L9)):*
> ```Python
> # (verifier/verifier_helper_script.sh) that will generate the verifier images, whose responsibility
> # would be to verify the SGX quotes sent by the graminized container image.
> # Following are the command line parameters accepted by this file
> ```

Please add a new line before this paragraph. Hard to read.
___
*[`GSC-Image-Curation/curate.py` line 9 at r17](https://reviewable.io/reviews/gramineproject/contrib/7#-NAn2FX885tiBxk_s-Om:-NAn2FX885tiBxk_s-On:bxeq3hl) ([raw file](https://github.com/gramineproject/contrib/blob/073b0d2a31471a8dc7ca60444c6305c646f18542/GSC-Image-Curation/curate.py#L9)):*
> ```Python
> # (verifier/verifier_helper_script.sh) that will generate the verifier images, whose responsibility
> # would be to verify the SGX quotes sent by the graminized container image.
> # Following are the command line parameters accepted by this file
> ```

Please add `:` at the end
___
*[`GSC-Image-Curation/curate.py` line 10 at r17](https://reviewable.io/reviews/gramineproject/contrib/7#-NAn2MA2BLLAw0XEaB-5:-NAn2MA2BLLAw0XEaB-6:bumj2tb) ([raw file](https://github.com/gramineproject/contrib/blob/073b0d2a31471a8dc7ca60444c6305c646f18542/GSC-Image-Curati [...]

2022-09-01 10:31 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/7)* status: 39 of 41 files reviewed, 54 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @dimakuv)

___
*[`GSC-Image-Curation/curate.py` line 2 at r17](https://reviewable.io/reviews/gramineproject/contrib/7#-NAn0njG3XVodi5zgLHC:-NAsJyWC1LHjz24vBExI:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/073b0d2a31471a8dc7ca60444c6305c646f18542/GSC-Image-Curation/curate.py#L2)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`file` -> `script`
</blockquote></details>

Done.
___
*[`GSC-Image-Curation/curate.py` line 2 at r17](https://reviewable.io/reviews/gramineproject/contrib/7#-NAn0rhuDOryzNcgj6-Q:-NAsJyoe4tgP_eVsCu09:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/073b0d2a31471a8dc7ca60444c6305c646f18542/GSC-Image-Curation/curate.py#L2)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`your own custom containers` -> `custom Docker images`
</blockquote></details>

Done.
___
*[`GSC-Image-Curation/curate.py` line 3 at r17](https://reviewable.io/reviews/gramineproject/contrib/7#-NAn0w2h4Vcutgh4nTFZ:-NAsK-jU6-xez9GK8TVc:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/073b0d2a31471a8dc7ca60444c6305c646f18542/GSC-Image-Curation/curate.py#L3)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`the application` -> `the script`
</blockquote></details>

Done.
___
*[`GSC-Image-Curation/curate.py` line 5 at r17](https://reviewable.io/reviews/gramineproject/contrib/7#-NAn108W1aw14fvFOLut:-NAsK3HbBynM-til0wlG:bpz8gpr) ([raw file](https://github.com/gramineproject/contrib/blob/073b0d2a31471a8dc7ca60444c6305c646f18542/GSC-Image-Curation/curate.py#L5)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`container image` -> `Docker image` ("container" and "image" are two mutually exclusive terms, they cannot be used together -- the former means "the environment that is started from the image, and does some runtime processing" whereas the latter means "the prepared environment that is stored on hard drive, and a container will be started from it").
</blockquote></details>

Got it. thanks
___
*[`GSC-Image-Curation/curate.py` line 5 at r17](https://reviewable.io/reviews/gramineproject/contrib/7#-NAn1X6X204dc6wVaJEV:-NAsKAW_5UfK0HpAWc6d:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/073b0d2a31471a8dc7ca60444c6305c646f18542/GSC-Image-Curation/curate.py#L5)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`This python file` -> `This script`
</blockquote></details>

Done.
___
*[`GSC-Image-Curation/curate.py` line 8 at r17](https://reviewable.io/reviews/gramineproject/contrib/7#-NAn2A-G52CWQk4ClBwZ:-NAsKP04BDMStjTCBanO:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/073b0d2a31471a8dc7ca60444c6305c646f18542/GSC-Image-Curation/curate.py#L8)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`...calls into a script to generate the verifier Docker image (for SGX remote attestation). The generated verifier Docker image is supposed to be started together with the graminized Docker image, to verify the SGX attestation evidence (SGX quote) sent by the latter image.`
</blockquote></details>

Done.
___
*[`GSC-Image-Curation/curate.py` line 9 at r17](https://reviewable.io/reviews/gramineproject/contrib/7#-NAn2C3a-xQYvwHexR1P:-NAsKPi13QJ4mIC_4ke-:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/073b0d2a31471a8dc7ca60444c6305c646f18542/GSC-Image-Curation/curate.py#L9)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add a new line before this paragraph. Hard to read.
</blockquote></details>

Done.
___
*[`GSC-Image-Curation/curate.py` line 9 at r17](https://reviewable.io/reviews/gramineproject/contrib/7#-NAn2FX885tiBxk_s-Om:-NAsKQ938KnoN3yvf37f:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/073b0d2a31471a8dc7ca60444c6305c646f18542/GSC-Image-Curation/curate.py#L9)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add `:` at the end
</blockquote></details>

Done.
___
*[`GSC-Image-Curation/curate.py` line 10 at r17](https://reviewable.io/reviews/gramineproject/contrib/7#-NAn2MA2BLLAw0XEaB-5:-NAsKVgU5kM_pXYHSseE:b-hyijst) ([raw file](https://github.com/gramineproject/contrib/blob/073b0d2a31471a8dc7ca60444c6305c646f18542/GSC-Image-Curation/curate.py#L10)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't get it? "Type of workload" and "base image to be graminized" are two different things. So what exactly is meant by this? Is it the same thing (the base Docker image), or "type of workload" may refer to something else?
</blockquote></details>

type of workload = `redis` - this will tell the script to go pull a manifest from the `redis/` folder. 
base image to be graminized =  the actual Docker image that needs to be graminized.
We're modifying the command to make it explicit, like `python3 curate.py redis redis:7.0.0`
___
*[`GSC-Image-Curation/curate.py` line 12 at r17](https://reviewable.io/reviews/gramineproject/contrib/7#-NAn2Yfr0tmLGtOWqphu:-NAsO-8-79ISIorIikVo:bw693m6) ([raw file](https://github.com/gramineproject/contrib/blob/073b0d2a31471a8dc7ca60444c6305c646f18542/GSC-Image-Curation/curate.py#L12)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please rename this `d` to `debug`. Also, is this the *third* argument? What if I want to run a non-test image with `debug`? How do I type my command?
</blockquote></details>

I'm following `-d` just the way we run gsc build with debug `gsc build -d ..` . You can use this options with both test and non test modes.
`python3 curate.py -d redis/redis:7.0.0 test`
`python3 curate.py -d redis/redis:7.0.0`

So now the question, do we need to change to `debug` ?
___
*[`GSC-Image-Curation/curate.py` line 44 at r17](https://reviewable.io/reviews/gramineproject/contrib/7#-NAn2viV-yWII_xnuGd_:-NAsPVib8mKqO4KmsFkS:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/073b0d2a31471a8dc7ca60444c6305c646f18542/GSC-Image-Curation/curate.py#L44)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please make the indentation more readable. Typically, arguments on the next line start right-below the arguments on the first line. Like this:
```
    guide_win = curses.newwin(guide_win_height, guide_win_width, title_height,
                              int(screen_width/2))
```
</blockquote></details>

Done.
___
*[`GSC-Image-Curation/curate.py` line 44 at r17](https://reviewable.io/reviews/gramineproject/contrib/7#-NAn36En9nV5gOvCe3ZV:-NAsPW3e5UakxeR8rYD4:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/073b0d2a31471a8dc7ca60444c6305c646f18542/GSC-Image-Curation/curate.py#L44)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please don't have spaces between the function (`int`) and its arguments.
</blockquote></details>

Done.
___
*[`GSC-Image-Curation/curate.py` line 115 at r17](https://reviewable.io/reviews/gramineproject/contrib/7#-NAn3LBN3ZiNXOvMRA17:-NAsPYsADkbXm-cfjohR:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/073b0d2a31471a8dc7ca60444c6305c646f18542/GSC-Image-Curation/curate.py#L115)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Remove whitespace
</blockquote></details>

Done [...]

2022-09-01 12:26 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/7)* status: all files reviewed, 40 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @dimakuv)

___
*[`GSC-Image-Curation/curate.py` line 10 at r17](https://reviewable.io/reviews/gramineproject/contrib/7#-NAn2MA2BLLAw0XEaB-5:-NAszG9TA9QOkZzngcbS:bgt6w4i) ([raw file](https://github.com/gramineproject/contrib/blob/073b0d2a31471a8dc7ca60444c6305c646f18542/GSC-Image-Curation/curate.py#L10)):*
> We're modifying the command to make it explicit, like `python3 curate.py redis redis:7.0.0`

Yes, please. It was very non-obvious to me.
___
*[`GSC-Image-Curation/curate.py` line 12 at r17](https://reviewable.io/reviews/gramineproject/contrib/7#-NAn2Yfr0tmLGtOWqphu:-NAszMQT5mkPXZN9LV2a:bilswe2) ([raw file](https://github.com/gramineproject/contrib/blob/073b0d2a31471a8dc7ca60444c6305c646f18542/GSC-Image-Curation/curate.py#L12)):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

I'm following `-d` just the way we run gsc build with debug `gsc build -d ..` . You can use this options with both test and non test modes.
`python3 curate.py -d redis/redis:7.0.0 test`
`python3 curate.py -d redis/redis:7.0.0`

So now the question, do we need to change to `debug` ?
</blockquote></details>

GSC has two forms for the flag: the short form `-d`, and the long form `--debug`. I personally use `--debug`.

Either provide the same two forms, or just use `--debug`. Only `-d` is hard to understand.
___
*[`GSC-Image-Curation/curate.py` line 115 at r17](https://reviewable.io/reviews/gramineproject/contrib/7#-NAn3LBN3ZiNXOvMRA17:-NAszajJBDm540c4t5X_:bfhqml6) ([raw file](https://github.com/gramineproject/contrib/blob/073b0d2a31471a8dc7ca60444c6305c646f18542/GSC-Image-Curation/curate.py#L115)):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done.
___
*[`GSC-Image-Curation/curate.py` line 197 at r17](https://reviewable.io/reviews/gramineproject/contrib/7#-NAn3gRCAwlvKwrCsWPG:-NAszf7VEPykZ8xHxz-J:br02lkj) ([raw file](https://github.com/gramineproject/contrib/blob/073b0d2a31471a8dc7ca60444c6305c646f18542/GSC-Image-Curation/curate.py#L197)):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I also changed the text, which you missed in my comment (sorry, it was not obvious). Please replace your text with my proposed text too.
___
*[`GSC-Image-Curation/README.md` line 6 at r17](https://reviewable.io/reviews/gramineproject/contrib/7#-NAn5EmmDQVy2BGJiZPZ:-NAszxPJBZ-31UMlPO1r:b-26ws46) ([raw file](https://github.com/gramineproject/contrib/blob/073b0d2a31471a8dc7ca60444c6305c646f18542/GSC-Image-Curation/README.md#L6)):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Please use Markdown formatting for links:
```
... [GSC tool](https://github.com/gramineproject/gsc)
```
___
*[`GSC-Image-Curation/README.md` line 5 at r21](https://reviewable.io/reviews/gramineproject/contrib/7#-NAszu2g-4auboXUEJGQ:-NAszu2g-4auboXUEJGR:bf92z7n) ([raw file](https://github.com/gramineproject/contrib/blob/9d1e7a4e4ab32bf17d64d929bcd4856247db6d5c/GSC-Image-Curation/README.md#L5)):*
> ```Markdown
> The Gramine Curated applications project provides an interactive script that helps to transform any
> Docker image to a graminized one, packing features such as attestation and beyond, necessary for
> enabling end-to-end usescases securely. The interactive script asks users for specific
> ```

`usescases` -> `use cases`
___
*[`GSC-Image-Curation/README.md` line 11 at r21](https://reviewable.io/reviews/gramineproject/contrib/7#-NAt-IE50JZEujguCkp5:-NAt-IE50JZEujguCkp6:bpog2ed) ([raw file](https://github.com/gramineproject/contrib/blob/9d1e7a4e4ab32bf17d64d929bcd4856247db6d5c/GSC-Image-Curation/README.md#L11)):*
> ```Markdown
> (for e.g. `redis/` directory), understand how they work, and then use them as the basis for their
> own workloads. The script also provides a `test` functionality where, with a single command, users
> can generate a test non-production Graminized image purely for experimentation and learning.
> ```

`a test` -- this is not descriptive, so just remove it.

I would also add that this graminized image is signed by a dummy key.
___
*[`GSC-Image-Curation/README.md` line 32 at r21](https://reviewable.io/reviews/gramineproject/contrib/7#-NAt-oJg6kBvSgeGZnMb:-NAt-oJhCkxn3W3TPFn9:bfh8kz1) ([raw file](https://github.com/gramineproject/contrib/blob/9d1e7a4e4ab32bf17d64d929bcd4856247db6d5c/GSC-Image-Curation/README.md#L32)):*
> ```Markdown
> 
> #### To generate a custom graminized image, follow the below. This will launch an interactive application
> that will take inputs to create a curated graminized image.
> ```

This doesn't render as you expected it to render: https://github.com/aneessahib/contrib/tree/aneessahib/gsc_image_curation/GSC-Image-Curation#to-generate-a-custom-graminized-image-follow-the-below-this-will-launch-an-interactive-application

Also, why do you do `####`? No need for it at all.
___
*[`GSC-Image-Curation/README.md` line 49 at r21](https://reviewable.io/reviews/gramineproject/contrib/7#-NAt-yMq6rQOQfg1ITX3:-NAt-yMq6rQOQfg1ITX4:bjqo5ml) ([raw file](https://github.com/gramineproject/contrib/blob/9d1e7a4e4ab32bf17d64d929bcd4856247db6d5c/GSC-Image-Curation/README.md#L49)):*
> ```Markdown
> #### To generate a custom graminized image, follow the below.
> This will launch an interactive script that will take inputs to create a curated graminized
> image.
> ```

ditto (weird rendering)
___
*[`GSC-Image-Curation/README.md` line 58 at r21](https://reviewable.io/reviews/gramineproject/contrib/7#-NAt00bq2UW3OtaMJ3i8:-NAt00bq2UW3OtaMJ3i9:b6jwps5) ([raw file](https://github.com/gramineproject/contrib/blob/9d1e7a4e4ab32bf17d64d929bcd4856247db6d5c/GSC-Image-Curation/README.md#L58)):*
> ```Markdown
>     .
>     ├── curate.py               # Entry file for curation that the user runs as explained above
>     ├── redis/                  # Contents to help curate.py with GSC Redis curation.
> ```

You missed this dot at the end of the line


<!-- Sent from Reviewable.io -->

2022-09-01 17:25 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/7)* status: 38 of 41 files reviewed, 40 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @dimakuv)

___
*[`GSC-Image-Curation/config.yaml` line 3 at r3](https://reviewable.io/reviews/gramineproject/contrib/7#-NAOoTA37yjphZ-RVIiB:-NAu3Egz0Zgre68RWqE9:b-ilynca) ([raw file](https://github.com/gramineproject/contrib/blob/c2401566b780a71ea25e07737bd132a8c0375fed/GSC-Image-Curation/config.yaml#L3)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

But why so complicated? Isn't the whole purpose of this curation script to *decrease* the number of files the user has to touch (to one)?

I would strongly consider creating this file on the fly by your curation script, and making these params tunable.
</blockquote></details>

My problem with this is - the distro is not really the base OS of the VM, its the base OS of the target container - which can be anything regardless of the VM being on  18.04 or 20.04. 
The distro can be anything that GSC is capable of handling today - 18.04, 20.04, centos etc. Do we provide all of these options to the user? The only factor that is VM specific is the kernel - and in our case if the DCAP driver is OOT or in-kernel. Makes sense?


<!-- Sent from Reviewable.io -->

2022-09-02 18:16 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/7)* status: 19 of 47 files reviewed, 40 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/7#-NAn0c742UEC4y9MTCfF:-NAysKWU2Q1FeX3y3cGF:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

By the way, why do we call it `GSC-Image-Curation`? Shouldn't it be just `Curated-Apps`?
</blockquote></details>

Done.

___
___
*[`GSC-Image-Curation/.gitignore` line 1 at r17](https://reviewable.io/reviews/gramineproject/contrib/7#-NAn-Ejs9fcsnUvSrwXD:-NAyrEpO4_sf-uozg3K4:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/073b0d2a31471a8dc7ca60444c6305c646f18542/GSC-Image-Curation/.gitignore#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This item should be removed from here, and instead put in a `util/.gitignore` new file.
</blockquote></details>

Done.
___
*[`GSC-Image-Curation/pytorch/README.md` line 10 at r17](https://reviewable.io/reviews/gramineproject/contrib/7#-NAn7xab1vX8jB9s8u1O:-NAyrIeODhM7VgpRLeUb:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/073b0d2a31471a8dc7ca60444c6305c646f18542/GSC-Image-Curation/pytorch/README.md#L10)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please re-wrap to 100 chars. Please also use the correct Markdown formatting for bullet-list items (use correct indentation).
</blockquote></details>

Done.
___
*[`GSC-Image-Curation/pytorch/base_image_helper/README.md` line 1 at r17](https://reviewable.io/reviews/gramineproject/contrib/7#-NAn8CMy5qRmNGp-pTyO:-NAyrJQC2B8c-Z6Bm8Sb:b-wm6k4y) ([raw file](https://github.com/gramineproject/contrib/blob/073b0d2a31471a8dc7ca60444c6305c646f18542/GSC-Image-Curation/pytorch/base_image_helper/README.md#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do we show two examples? Who cares about plaintext files? Shouldn't we just have one example -- with encrypted files?
</blockquote></details>

We were asked to provide this. Many are newbies wanting to just try things as quick as they can.
___
*[`GSC-Image-Curation/pytorch/base_image_helper/README.md` line 13 at r17](https://reviewable.io/reviews/gramineproject/contrib/7#-NAn8JvBD38Clwhd2ivS:-NAysD0H-7UwSqZY4ra_:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/073b0d2a31471a8dc7ca60444c6305c646f18542/GSC-Image-Curation/pytorch/base_image_helper/README.md#L13)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This should be the first paragraph (after `This directory contains...`) because these are prerequisites. Otherwise the user may start reading and doing `bash ./helper.sh encrypt`, and this won't work because the user didn't have read the next para and didn't install Gramine. Please move.
</blockquote></details>

Done.
___
*[`GSC-Image-Curation/redis/README.md` line 7 at r17](https://reviewable.io/reviews/gramineproject/contrib/7#-NAn8iKk1nqPa5q3MhL0:-NAys7oQ-X2_ydWImMOT:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/073b0d2a31471a8dc7ca60444c6305c646f18542/GSC-Image-Curation/redis/README.md#L7)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please re-wrap to 100 chars. Please also use the correct Markdown formatting for bullet-list items (use correct indentation).
</blockquote></details>

Done.
___
*[`GSC-Image-Curation/curate.py` line 223 at r3](https://reviewable.io/reviews/gramineproject/contrib/7#-NAOq6xt5bagryZJFFr9:-NAysv_A2J0j-wSggVhK:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/c2401566b780a71ea25e07737bd132a8c0375fed/GSC-Image-Curation/curate.py#L223)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please rename `d` to `debug`
</blockquote></details>

Done.
___
*[`GSC-Image-Curation/curate.py` line 10 at r17](https://reviewable.io/reviews/gramineproject/contrib/7#-NAn2MA2BLLAw0XEaB-5:-NAysMO-5sYCr6Ft1-G3:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/073b0d2a31471a8dc7ca60444c6305c646f18542/GSC-Image-Curation/curate.py#L10)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> We're modifying the command to make it explicit, like `python3 curate.py redis redis:7.0.0`

Yes, please. It was very non-obvious to me.
</blockquote></details>

Done.
___
*[`GSC-Image-Curation/curate.py` line 12 at r17](https://reviewable.io/reviews/gramineproject/contrib/7#-NAn2Yfr0tmLGtOWqphu:-NAysNoh-IdEPLvQ5yBY:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/073b0d2a31471a8dc7ca60444c6305c646f18542/GSC-Image-Curation/curate.py#L12)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

GSC has two forms for the flag: the short form `-d`, and the long form `--debug`. I personally use `--debug`.

Either provide the same two forms, or just use `--debug`. Only `-d` is hard to understand.
</blockquote></details>

Done.
___
*[`GSC-Image-Curation/curate.py` line 115 at r17](https://reviewable.io/reviews/gramineproject/contrib/7#-NAn3LBN3ZiNXOvMRA17:-NAyscCg8qDrvgzE9E1h:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/073b0d2a31471a8dc7ca60444c6305c646f18542/GSC-Image-Curation/curate.py#L115)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Not done.
</blockquote></details>

Done.
___
*[`GSC-Image-Curation/curate.py` line 197 at r17](https://reviewable.io/reviews/gramineproject/contrib/7#-NAn3gRCAwlvKwrCsWPG:-NAzLYkA9E3vyXDUxuVe:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/073b0d2a31471a8dc7ca60444c6305c646f18542/GSC-Image-Curation/curate.py#L197)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I also changed the text, which you missed in my comment (sorry, it was not obvious). Please replace your text with my proposed text too.
</blockquote></details>

Done.
___
*[`GSC-Image-Curation/README.md` line 34 at r3](https://reviewable.io/reviews/gramineproject/contrib/7#-NAOsXHG5OY4J3Xrc9vW:-NAz56bXC1eT9co6Z8eB:b-l9j5i8) ([raw file](https://github.com/gramineproject/contrib/blob/c2401566b780a71ea25e07737bd132a8c0375fed/GSC-Image-Curation/README.md#L34)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't get it. So you have a single argument -- `redis/<your image>`. How does the script understand that it needs to pick up the redis manifest? Shouldn't you have *two arguments* then?
</blockquote></details>

changed to two arguments.
___
*[`GSC-Image-Curation/README.md` line 6 at r17](https://reviewable.io/reviews/gramineproject/contrib/7#-NAn5EmmDQVy2BGJiZPZ:-NAzPQoY1Xz3yieqW5eW:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/073b0d2a31471a8dc7ca60444c6305c646f18542/GSC-Image-Curation/README.md#L6)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please use Markdown formatting for links:
```
... [GSC tool](https://github.com/gramineproject/gsc)
```
</blockquote></details>

Done.
___
*[`GSC-Image-Curation/README.md` line 18 at r17](https://reviewable.io/reviews/gramineproject/contrib/7#-NAn5ej38yroFdhCOWgM:-NAzPUkE3SH-7hS94_gM:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/073b0d2a31471a8dc7ca60444c6305c646f18542/GSC-Image-Curation/README.md#L18)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

If I underst [...]

2022-09-22 09:48 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/7)* status: 19 of 47 files reviewed, 41 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/7#-NCZaMHc3Ji7TIdItgfK:-NCZaMHc3Ji7TIdItgfL:bdihyd3) (no related file):*
How can I test this locally?

___


<!-- Sent from Reviewable.io -->

2022-09-22 14:42 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/7)* status: 19 of 47 files reviewed, 40 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @dimakuv)

___
*[`GSC-Image-Curation/config.yaml` line 3 at r3](https://reviewable.io/reviews/gramineproject/contrib/7#-NAOoTA37yjphZ-RVIiB:-NC_buUuCNd0psfGK8Z7:b-ru6pk1) ([raw file](https://github.com/gramineproject/contrib/blob/c2401566b780a71ea25e07737bd132a8c0375fed/GSC-Image-Curation/config.yaml#L3)):*
Why are we talking about the VM? I don't care about the VM, I only care about the Docker base OS.

> The distro can be anything that GSC is capable of handling today - 18.04, 20.04, centos etc. Do we provide all of these options to the user?

Yes, why not. I still don't see a roadblock to move from (a) asking users to change `config.yaml` to (b) asking users 1-2 questions and generating `config.yaml` on the fly. The former is cumbersome for users. The latter is more user-friendly.

Also, why are we discussing this? It seems that you already implemented this requested change?
___
*[`Curated-Apps/util/config.yaml.template` line 1 at r27](https://reviewable.io/reviews/gramineproject/contrib/7#-NC_d3R8Cqqu4mQR0hFM:-NC_d3R8Cqqu4mQR0hFN:b9lfzfo) ([raw file](https://github.com/gramineproject/contrib/blob/468eef2bbdcca2eda4168b10e8eb8ec3443765d2/Curated-Apps/util/config.yaml.template#L1)):*
> ```
> # Specify the OS distro. For Eg. ``ubuntu:18.04``, ``ubuntu:20.04``.
> ```

You should change this to smth like
```
# DO NOT CHANGE! BELOW WILL BE REPLACED BY THE CURATION SCRIPT!
```
___
*[`Curated-Apps/util/curation_script.sh` line 73 at r27](https://reviewable.io/reviews/gramineproject/contrib/7#-NC_dXfF6bNPnyBgDCkM:-NC_dXfF6bNPnyBgDCkN:b8b3g1u) ([raw file](https://github.com/gramineproject/contrib/blob/468eef2bbdcca2eda4168b10e8eb8ec3443765d2/Curated-Apps/util/curation_script.sh#L73)):*
> ```Shell
>     cd gsc
>     cp ../util/config.yaml.template config.yaml
>     sed -i 's|ubuntu:.*|'$distro'"|' config.yaml
> ```

What about changing the SGX driver config in this file?


<!-- Sent from Reviewable.io -->

2022-09-23 05:21 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/7)* status: 19 of 47 files reviewed, 40 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/7#-NCZaMHc3Ji7TIdItgfK:-NCcmAX-0E60cVWfMG9H:b-83354o) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

How can I test this locally?
</blockquote></details>

Updated PR description

___
___
*[`GSC-Image-Curation/config.yaml` line 3 at r3](https://reviewable.io/reviews/gramineproject/contrib/7#-NAOoTA37yjphZ-RVIiB:-NCclzMSCNLPXTQ2vPYB:b-l9vxb6) ([raw file](https://github.com/gramineproject/contrib/blob/c2401566b780a71ea25e07737bd132a8c0375fed/GSC-Image-Curation/config.yaml#L3)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why are we talking about the VM? I don't care about the VM, I only care about the Docker base OS.

> The distro can be anything that GSC is capable of handling today - 18.04, 20.04, centos etc. Do we provide all of these options to the user?

Yes, why not. I still don't see a roadblock to move from (a) asking users to change `config.yaml` to (b) asking users 1-2 questions and generating `config.yaml` on the fly. The former is cumbersome for users. The latter is more user-friendly.

Also, why are we discussing this? It seems that you already implemented this requested change?
</blockquote></details>

Yes correct. 
___
*[`Curated-Apps/util/config.yaml.template` line 1 at r27](https://reviewable.io/reviews/gramineproject/contrib/7#-NC_d3R8Cqqu4mQR0hFM:-NCcmEP51FucCJfuQ9N5:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/468eef2bbdcca2eda4168b10e8eb8ec3443765d2/Curated-Apps/util/config.yaml.template#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You should change this to smth like
```
# DO NOT CHANGE! BELOW WILL BE REPLACED BY THE CURATION SCRIPT!
```
</blockquote></details>

Done.
___
*[`Curated-Apps/util/curation_script.sh` line 73 at r27](https://reviewable.io/reviews/gramineproject/contrib/7#-NC_dXfF6bNPnyBgDCkM:-NCcmG527wA16uwio5t8:bgbo0rv) ([raw file](https://github.com/gramineproject/contrib/blob/468eef2bbdcca2eda4168b10e8eb8ec3443765d2/Curated-Apps/util/curation_script.sh#L73)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What about changing the SGX driver config in this file?
</blockquote></details>

We are leaving this at `DCAP_1.11` . This works on both Ubuntu 18.04 as well as Ubuntu 20.04 VMs (Even though Ubuntu 20.04 VMs come with in-kernel).


<!-- Sent from Reviewable.io -->

2022-09-23 07:03 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/7)* status: 19 of 47 files reviewed, 39 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/7#-NCd7qCMELwCua4yiRwS:-NCd7qCMELwCua4yiRwT:bvpmxyf) (no related file):*
Something wrong is happenning. Reproducer:
```bash
# delete all Docker images and containers, for purity of this experiment
~/gramineproject/contrib/Curated-Apps$ docker system prune --all

# let's check that there are no images
~/gramineproject/contrib/Curated-Apps$ docker images -a
REPOSITORY   TAG       IMAGE ID   CREATED   SIZE

# start the Curation script
~/gramineproject/contrib/Curated-Apps$ python3 curate.py redis redis
Warning: Cannot find application Docker image `redis`.
Fetching from Docker Hub ...

... takes very long time ...

# let's check what Docker images we have
~/gramineproject/contrib/Curated-Apps$ docker images -a
REPOSITORY   TAG                IMAGE ID       CREATED       SIZE
redis        4-alpine           e3dd0e49bca5   2 years ago   20.4MB
redis        4.0-alpine         e3dd0e49bca5   2 years ago   20.4MB
redis        4.0.14-alpine      e3dd0e49bca5   2 years ago   20.4MB
redis        4                  191c4017dcdd   2 years ago   89.3MB
redis        4.0                191c4017dcdd   2 years ago   89.3MB
redis        4.0.14             191c4017dcdd   2 years ago   89.3MB
redis        3                  87856cc39862   3 years ago   76MB
redis        3.2                87856cc39862   3 years ago   76MB
redis        3-alpine           6e94a98d3442   3 years ago   22.9MB
redis        3.2-alpine         6e94a98d3442   3 years ago   22.9MB
redis        3.2.12-alpine      6e94a98d3442   3 years ago   22.9MB
redis        4.0.11-alpine      05097a3a0549   3 years ago   30MB
redis        4.0.11-alpine3.8   05097a3a0549   3 years ago   30MB
... and more and more, all possible versions of Redis images! ...
```

I stopped the Curation script after ~15 minutes, it was still not finished and just downloaded all Redis images and polluted my hard drive. Please fix this.

___


<!-- Sent from Reviewable.io -->

2022-09-23 07:08 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/7)* status: 19 of 47 files reviewed, 39 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/7#-NCd7qCMELwCua4yiRwS:-NCd9zciD5nJjhTbF8W7:b-ysyfy6) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Something wrong is happenning. Reproducer:
```bash
# delete all Docker images and containers, for purity of this experiment
~/gramineproject/contrib/Curated-Apps$ docker system prune --all

# let's check that there are no images
~/gramineproject/contrib/Curated-Apps$ docker images -a
REPOSITORY   TAG       IMAGE ID   CREATED   SIZE

# start the Curation script
~/gramineproject/contrib/Curated-Apps$ python3 curate.py redis redis
Warning: Cannot find application Docker image `redis`.
Fetching from Docker Hub ...

... takes very long time ...

# let's check what Docker images we have
~/gramineproject/contrib/Curated-Apps$ docker images -a
REPOSITORY   TAG                IMAGE ID       CREATED       SIZE
redis        4-alpine           e3dd0e49bca5   2 years ago   20.4MB
redis        4.0-alpine         e3dd0e49bca5   2 years ago   20.4MB
redis        4.0.14-alpine      e3dd0e49bca5   2 years ago   20.4MB
redis        4                  191c4017dcdd   2 years ago   89.3MB
redis        4.0                191c4017dcdd   2 years ago   89.3MB
redis        4.0.14             191c4017dcdd   2 years ago   89.3MB
redis        3                  87856cc39862   3 years ago   76MB
redis        3.2                87856cc39862   3 years ago   76MB
redis        3-alpine           6e94a98d3442   3 years ago   22.9MB
redis        3.2-alpine         6e94a98d3442   3 years ago   22.9MB
redis        3.2.12-alpine      6e94a98d3442   3 years ago   22.9MB
redis        4.0.11-alpine      05097a3a0549   3 years ago   30MB
redis        4.0.11-alpine3.8   05097a3a0549   3 years ago   30MB
... and more and more, all possible versions of Redis images! ...
```

I stopped the Curation script after ~15 minutes, it was still not finished and just downloaded all Redis images and polluted my hard drive. Please fix this.
</blockquote></details>

Ok thats a first. Then its best to follow the good practice to specify the exact image with the tag. please try `python3 curate.py redis redis:7.0.0`

___


<!-- Sent from Reviewable.io -->

2022-09-23 07:16 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/7)* status: 19 of 47 files reviewed, 38 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/7#-NCd7qCMELwCua4yiRwS:-NCdBxBv-K3hEhVh6E-c:bhegh10) (no related file):*
> python3 curate.py redis redis:7.0.0

 This works. I see you already updated the PR description with this, thanks.

___


<!-- Sent from Reviewable.io -->

2022-09-23 07:45 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/7)* status: 19 of 47 files reviewed, 39 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @dimakuv)

___
*[`Curated-Apps/util/constants.py` line 32 at r29](https://reviewable.io/reviews/gramineproject/contrib/7#-NCdIOc83G7djYSjM56n:-NCdIOc83G7djYSjM56o:b-2ii83j) ([raw file](https://github.com/gramineproject/contrib/blob/c5de43c76fb3c69034d056a7c0f4bec4aa716df2/Curated-Apps/util/constants.py#L32)):*
> ```Python
>                         'Fetching from Docker Hub ...\n\n')
> log_progress = 'You may monitor {} for detailed progress\n\n'
> title = "Curate  Your  Own  Gramine  Shielded  Container (GSC) Image !!!"
> ```

Please simply `Curate a Gramine Shielded Container (GSC) image`

The screaming `!!!` was annoying to see :)


<!-- Sent from Reviewable.io -->

2022-09-23 08:04 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/7)* status: 19 of 47 files reviewed, 52 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/7#-NCdK-6yEipkQ6Q8bIWJ:-NCdK-6yEipkQ6Q8bIWK:b-wjsldz) (no related file):*
I don't see what I type in the script. Is this normal? Why does this happen? It seems to be black font on black background, which obviously is invisible.

I run on my local machine bare-metal with Ubuntu 20.04 (*not* on an Azure VM).

___
___
*[`Curated-Apps/util/constants.py` line 43 at r29](https://reviewable.io/reviews/gramineproject/contrib/7#-NCdJKfx3PvkxIZsTHto:-NCdJKfyBQrZ9DvsTA4l:b1ezsv5) ([raw file](https://github.com/gramineproject/contrib/blob/c5de43c76fb3c69034d056a7c0f4bec4aa716df2/Curated-Apps/util/constants.py#L43)):*
> ```Python
> 
> index = ['The target deployment environment is assumed to be an Azure Confidential compute'
>          ' instance having out of tree DCAP driver.','Following stages are involved in the'
> ```

Is the part about "out of tree SGX DCAP driver" true? Can we remove this detail? I think it's not true since we support Azure Ubuntu 20.04, which has an in-kernel driver.
___
*[`Curated-Apps/util/constants.py` line 46 at r29](https://reviewable.io/reviews/gramineproject/contrib/7#-NCdJNpwAMxccGOsnqFT:-NCdJNpwAMxccGOsnqFU:bgz6ecs) ([raw file](https://github.com/gramineproject/contrib/blob/c5de43c76fb3c69034d056a7c0f4bec4aa716df2/Curated-Apps/util/constants.py#L46)):*
> ```Python
>          ' GSC image curation:', '1. Distro Selection', '2. Enclave Signing Key', '3. Attestation',
>           '4. Secret Provisioning', '5. Runtime Arguments', '6. Environment Variables',
>            '7. Encrypted Files','8. Execution & Debug']
> ```

A more logical sequence to me:
1. Distro selection
2. Runtime arguments (*should be renamed to `Command-line arguments`*)
3. Environment variables
4. Encrypted files
5. Attestation
6. Secret provisioning
7. Execution & debug
8. Enclave signing (*I prefer to remove `key` part from here*)
___
*[`Curated-Apps/util/constants.py` line 64 at r29](https://reviewable.io/reviews/gramineproject/contrib/7#-NCdKa_91KpM_IR1Autb:-NCdKa_A7seJNMhjTJEO:b-ly51ox) ([raw file](https://github.com/gramineproject/contrib/blob/c5de43c76fb3c69034d056a7c0f4bec4aa716df2/Curated-Apps/util/constants.py#L64)):*
> ```Python
> attestation_prompt = ['>> Remote Attestation:' , 'To enable remote attestation using Azure DCAP'
>                          ' client libs, use another terminal to copy the ca.crt, server.crt, and'
>                          ' server.key certificates to Curated-Apps/verifier/ssl directory',
> ```

I don't have such directory. Is this normal? Or this text is stale? Or am I supposed to create the `ssl/` subdirectory -- if yes, please explain it here.
___
*[`Curated-Apps/util/constants.py` line 68 at r29](https://reviewable.io/reviews/gramineproject/contrib/7#-NCdKop5ANlKWttx28lO:-NCdKop5ANlKWttx28lP:bfpqihn) ([raw file](https://github.com/gramineproject/contrib/blob/c5de43c76fb3c69034d056a7c0f4bec4aa716df2/Curated-Apps/util/constants.py#L68)):*
> ```Python
>                          ' a decryption key for encrypted files.',
>                          '- Type done and press CTRL+G when ready, OR',
>                          '- Type test and press CTRL+G to create test certificates',
> ```

Please add `OR` at the end of this line
___
*[`Curated-Apps/util/constants.py` line 70 at r29](https://reviewable.io/reviews/gramineproject/contrib/7#-NCdKvDw0tvmU5SJNLO3:-NCdKvDw0tvmU5SJNLO4:bdtbx46) ([raw file](https://github.com/gramineproject/contrib/blob/c5de43c76fb3c69034d056a7c0f4bec4aa716df2/Curated-Apps/util/constants.py#L70)):*
> ```Python
>                          '- Type test and press CTRL+G to create test certificates',
>                          '- OR press CTRL+G to skip attestation']
> attestation_help = ['This step enables the host enclave to communicate to a remote verifier over'
> ```

What is the "host enclave"? I suggest simply `enclave` or `Gramine enclave`

Please fix all the mentions of `host enclave` in this PR
___
*[`Curated-Apps/util/constants.py` line 75 at r29](https://reviewable.io/reviews/gramineproject/contrib/7#-NCdLCP_1N7w6Eo382Z0:-NCdLCP_1N7w6Eo382Z1:b-4c05a7) ([raw file](https://github.com/gramineproject/contrib/blob/c5de43c76fb3c69034d056a7c0f4bec4aa716df2/Curated-Apps/util/constants.py#L75)):*
> ```Python
>                     ' to provide a set of certificates and keys to enable the attestation flow.'
>                     ' The CA certificate will be used to TLS authenticate the verifier during the'
>                     ' Remote Attestation TLS (RA_TLS) flow. A test sample set of RA-TLS keys and'
> ```

`RA_TLS` -> `RA-TLS`

Also, why do you explain what RA-TLS only at this line? There is a mention of RA-TLS before, please move it there.
___
*[`Curated-Apps/util/constants.py` line 92 at r29](https://reviewable.io/reviews/gramineproject/contrib/7#-NCdLjny8JHZtOPhwRpe:-NCdLjny8JHZtOPhwRpf:b-7fw0w6) ([raw file](https://github.com/gramineproject/contrib/blob/c5de43c76fb3c69034d056a7c0f4bec4aa716df2/Curated-Apps/util/constants.py#L92)):*
> ```Python
>                        " attestation."]
> encryption_key_prompt = 'Please provide the path to the key used for the encryption.'
> arg_input = ['>> Runtime Arguments:', 'Specify docker run-time arguments here in a single string.'
> ```

`run-time arguments` -> `command-line arguments`

Please replace this everywhere in this PR
___
*[`Curated-Apps/util/constants.py` line 93 at r29](https://reviewable.io/reviews/gramineproject/contrib/7#-NCdLaVb0SNTHBYQUKL4:-NCdLaVb0SNTHBYQUKL5:b-t2iehg) ([raw file](https://github.com/gramineproject/contrib/blob/c5de43c76fb3c69034d056a7c0f4bec4aa716df2/Curated-Apps/util/constants.py#L93)):*
> ```Python
> encryption_key_prompt = 'Please provide the path to the key used for the encryption.'
> arg_input = ['>> Runtime Arguments:', 'Specify docker run-time arguments here in a single string.'
>              ' for e.g., if your docker runtime is ', 'docker run -it <image_name> arg1 arg2'
> ```

`for e.g.,` -> `For example,`
___
*[`Curated-Apps/util/constants.py` line 94 at r29](https://reviewable.io/reviews/gramineproject/contrib/7#-NCdLt7DAaFXJ3A7Adw-:-NCdLt7DAaFXJ3A7Adw0:bbhfc0c) ([raw file](https://github.com/gramineproject/contrib/blob/c5de43c76fb3c69034d056a7c0f4bec4aa716df2/Curated-Apps/util/constants.py#L94)):*
> ```Python
> arg_input = ['>> Runtime Arguments:', 'Specify docker run-time arguments here in a single string.'
>              ' for e.g., if your docker runtime is ', 'docker run -it <image_name> arg1 arg2'
>              + color_set, 'then the arguments that needs to be provided here is', 'arg1 arg2'
> ```

`here is` -> `here are`
___
*[`Curated-Apps/util/constants.py` line 101 at r29](https://reviewable.io/reviews/gramineproject/contrib/7#-NCdM6yR4r5nQ9LaaQcv:-NCdM6yR4r5nQ9LaaQcw:b-nxyvvz) ([raw file](https://github.com/gramineproject/contrib/blob/c5de43c76fb3c69034d056a7c0f4bec4aa716df2/Curated-Apps/util/constants.py#L101)):*
> ```Python
> 
> env_input = ['>> Runtime Environments:', 'Please specify a list of env variables and respective'
>              ' values separated by comma', 'Accepted format:', 'name="Xyz",age="20"' + color_set,
> ```

Separating by comma is dangereous if not done right.

Will this be correctly parsed?
```
KMP_AFFINITY="granularity=fine,noverbose,compact,1,0",SECOND_VAR="blabla"
```
___
*[`Curated-Apps/util/constants.py` line 104 at r29](https://reviewable.io/reviews/gramineproject/contrib/7#-NCdMSrJ2dFZrgLIGZIK:-NCdMSrJ2dFZrgLIGZIL:b68rv9i) ([raw file](https://github.com/gramineproject/contrib/blob/c5de43c76fb3c69034d056a7c0f4bec4aa716df2/Curated-Apps/util/constants.py#L104) [...]

2022-09-23 08:13 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/7)* status: 19 of 47 files reviewed, 52 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @dimakuv)

___
*[`Curated-Apps/util/constants.py` line 46 at r29](https://reviewable.io/reviews/gramineproject/contrib/7#-NCdJNpwAMxccGOsnqFT:-NCdOsPbByDtujlBXscz:b-r24esn) ([raw file](https://github.com/gramineproject/contrib/blob/c5de43c76fb3c69034d056a7c0f4bec4aa716df2/Curated-Apps/util/constants.py#L46)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

A more logical sequence to me:
1. Distro selection
2. Runtime arguments (*should be renamed to `Command-line arguments`*)
3. Environment variables
4. Encrypted files
5. Attestation
6. Secret provisioning
7. Execution & debug
8. Enclave signing (*I prefer to remove `key` part from here*)
</blockquote></details>

What is "Execution and debug"? I didn't see this step. Or do you mean -- generation of the final curated image? Please rename then.


<!-- Sent from Reviewable.io -->

2022-09-23 08:27 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/7)* status: 19 of 47 files reviewed, 56 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/7#-NCdQT6N19V5bWmzK8d_:-NCdQT6N19V5bWmzK8da:b-51o6wj) (no related file):*
When I added some `blabla` arguments in one of the steps, it resulted in this `entry_script_redis.sh`:
```
#!/bin/bash

"docker-entrypoint.sh"bla bla bla bla --protected-mode no --save ''
```

This is clearly wrong.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/7#-NCdRuoW7xKsTM1GEsZY:-NCdRuoW7xKsTM1GEsZZ:bcu34kc) (no related file):*
The curation script generated `commands.txt` like this:
```
docker run  --device=/dev/sgx/enclave -it gsc-redis:7.0.0
```

Where is `-v /var/run/aesmd/aesm.socket:/var/run/aesmd/aesm.socket`?

Also, why do you include `-it` argument (which is used for "interactive sessions") -- Redis is not interactive at all...

___
___
*[`Curated-Apps/util/constants.py` line 123 at r29](https://reviewable.io/reviews/gramineproject/contrib/7#-NCdPBiK-S6oc508ovey:-NCdPBiK-S6oc508ovez:bc3o9kv) ([raw file](https://github.com/gramineproject/contrib/blob/c5de43c76fb3c69034d056a7c0f4bec4aa716df2/Curated-Apps/util/constants.py#L123)):*
> ```Python
>               './gsc info-image {}\n\n'
>               'Run the image(s) as shown below:\n')
> debug_run_messg = ('In the event of failures during runtime, run with debug flag (if not already)'
> ```

`(if not already) ` -- add a space at the end, otherwise it "merges" with `to get more...`
___
*[`Curated-Apps/util/curation_script.sh` line 120 at r27](https://reviewable.io/reviews/gramineproject/contrib/7#-NCdPsGZ6D0XnBWM_ufn:-NCdPsGZ6D0XnBWM_ufo:b-sb80u6) ([raw file](https://github.com/gramineproject/contrib/blob/468eef2bbdcca2eda4168b10e8eb8ec3443765d2/Curated-Apps/util/curation_script.sh#L120)):*
> ```Shell
>     signing_key_path="enclave-key.pem"
>     grep -qxF 'sgx.file_check_policy = "allow_all_but_log"' $app_image_manifest ||
>      echo 'sgx.file_check_policy = "allow_all_but_log"' >> $app_image_manifest
> ```

What is this logic with adding `allow_all_but_log`? This makes no sense to me here.


<!-- Sent from Reviewable.io -->

2022-09-23 08:54 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/7)* status: 19 of 47 files reviewed, 68 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @dimakuv)

___
*[`Curated-Apps/pytorch/base_image_helper/README.md` line 8 at r29](https://reviewable.io/reviews/gramineproject/contrib/7#-NCdXZL5ASt3EC_HNpHF:-NCdXZL5ASt3EC_HNpHG:bpyszli) ([raw file](https://github.com/gramineproject/contrib/blob/c5de43c76fb3c69034d056a7c0f4bec4aa716df2/Curated-Apps/pytorch/base_image_helper/README.md#L8)):*
> ```Markdown
>   on your machine.
> - File Encryption is done using `gramine-sgx-pf-crypt` tool which is part of
>   [gramine installation](https://gramine.readthedocs.io/en/latest/quickstart.html#install-gramine).
> ```

`gramine` -> `Gramine`
___
*[`Curated-Apps/README.md` line 8 at r29](https://reviewable.io/reviews/gramineproject/contrib/7#-NCdU6Sl0y5hUdNBWK3j:-NCdU6Sl0y5hUdNBWK3k:b-8dpie0) ([raw file](https://github.com/gramineproject/contrib/blob/c5de43c76fb3c69034d056a7c0f4bec4aa716df2/Curated-Apps/README.md#L8)):*
> ```Markdown
> requirements, and submits the user inputs to the [GSC tool](https://github.com/gramineproject/gsc).
> A list of workload examples are provided below for reference. One can easily extend these reference
> examples to supporting more workloads by inspecting the contents of any of the reference workloads
> ```

`to supporting` -> `to support`
___
*[`Curated-Apps/README.md` line 9 at r29](https://reviewable.io/reviews/gramineproject/contrib/7#-NCdUG2aAhOTS9Y8o1kj:-NCdUG2aAhOTS9Y8o1kk:b6uj1jd) ([raw file](https://github.com/gramineproject/contrib/blob/c5de43c76fb3c69034d056a7c0f4bec4aa716df2/Curated-Apps/README.md#L9)):*
> ```Markdown
> A list of workload examples are provided below for reference. One can easily extend these reference
> examples to supporting more workloads by inspecting the contents of any of the reference workloads
> (for e.g. `redis/` directory), understand how they work, and then use them as the basis for their
> ```

`for e.g.` -> `e.g., `
___
*[`Curated-Apps/README.md` line 24 at r29](https://reviewable.io/reviews/gramineproject/contrib/7#-NCdV0ps8b7EDs7t4II9:-NCdV0ps8b7EDs7t4IIA:bhu8hi3) ([raw file](https://github.com/gramineproject/contrib/blob/c5de43c76fb3c69034d056a7c0f4bec4aa716df2/Curated-Apps/README.md#L24)):*
> ```Markdown
> encrypted files support.
> 
> ## Interactive script usage:
> ```

Please remove `:` from the end
___
*[`Curated-Apps/README.md` line 25 at r29](https://reviewable.io/reviews/gramineproject/contrib/7#-NCdV5lD7nBpXdkoZDge:-NCdV5lD7nBpXdkoZDgf:b-gjpmtu) ([raw file](https://github.com/gramineproject/contrib/blob/c5de43c76fb3c69034d056a7c0f4bec4aa716df2/Curated-Apps/README.md#L25)):*
> ```Markdown
> 
> ## Interactive script usage:
> `python3 curate.py <workload type> <base image name> <optional args>`
> ```

Please add `$` before `python3 ...`
___
*[`Curated-Apps/README.md` line 30 at r29](https://reviewable.io/reviews/gramineproject/contrib/7#-NCdW-ur3DnoYJwNG9lq:-NCdW-ur3DnoYJwNG9lr:b-6e36k7) ([raw file](https://github.com/gramineproject/contrib/blob/c5de43c76fb3c69034d056a7c0f4bec4aa716df2/Curated-Apps/README.md#L30)):*
> ```Markdown
>     | Required?| Argument           | Description/Possible values                                        |
>     |----------|--------------------|--------------------------------------------------------------------|
>     |    Yes   | `<Workload type>`  | Provide type of workload e.g., redis or pytorch etc..              |
> ```

Please remove `etc.`, it's already clear that there may be different workloads
___
*[`Curated-Apps/README.md` line 34 at r29](https://reviewable.io/reviews/gramineproject/contrib/7#-NCdUmTMBVmD2Cq3H-XQ:-NCdUmTMBVmD2Cq3H-XR:b-pibodl) ([raw file](https://github.com/gramineproject/contrib/blob/c5de43c76fb3c69034d056a7c0f4bec4aa716df2/Curated-Apps/README.md#L34)):*
> ```Markdown
>     | Optional | 'debug'            | To generate graminized image with debug symbols for debugging.     |
>     | Optional | 'test'             | To generate no-production image with a test enclave signing key.   |
>     |----------------------------------------------------------------------------------------------------|
> ```

Was this supposed to be rendered like this: https://github.com/aneessahib/contrib/tree/aneessahib/gsc_image_curation/Curated-Apps#interactive-script-usage ?

If you want this to be a proper table, I think you need to remove the 4-spaces indentation here.
___
*[`Curated-Apps/README.md` line 40 at r29](https://reviewable.io/reviews/gramineproject/contrib/7#-NCdWYMsAYyo-N5mB9TM:-NCdWYMsAYyo-N5mB9TN:b-qzfx8e) ([raw file](https://github.com/gramineproject/contrib/blob/c5de43c76fb3c69034d056a7c0f4bec4aa716df2/Curated-Apps/README.md#L40)):*
> ```Markdown
> ### Redis
> 
> To generate a non-production test graminized image
> ```

Add `:`
___
*[`Curated-Apps/README.md` line 44 at r29](https://reviewable.io/reviews/gramineproject/contrib/7#-NCdWQCH4qSkj-wOO_8E:-NCdWQCH4qSkj-wOO_8F:b-812zej) ([raw file](https://github.com/gramineproject/contrib/blob/c5de43c76fb3c69034d056a7c0f4bec4aa716df2/Curated-Apps/README.md#L44)):*
> ```Markdown
> `$ python3 ./curate.py redis redis:7.0.0 test`
> 
> To generate a custom graminized image, follow the below. This will launch an interactive application
> ```

`follow the below` -> `type the following`
___
*[`Curated-Apps/README.md` line 53 at r29](https://reviewable.io/reviews/gramineproject/contrib/7#-NCdWeD7CcdvUVkMzQGf:-NCdWeD7CcdvUVkMzQGg:baplf6e) ([raw file](https://github.com/gramineproject/contrib/blob/c5de43c76fb3c69034d056a7c0f4bec4aa716df2/Curated-Apps/README.md#L53)):*
> ```Markdown
> User is expected to first have his base image `<base_image_with_pytorch>` ready with PyTorch and
> the necessary application files built into this image. `/pytorch` directory contains sample
> dockerfiles and instructions to create a test pytorch base image. This base image is then passed to
> ```

`pytorch` -> `PyTorch`
___
*[`Curated-Apps/README.md` line 56 at r29](https://reviewable.io/reviews/gramineproject/contrib/7#-NCdWiGz3CARYP1_QzFB:-NCdWiGz3CARYP1_QzFC:bt0vtzx) ([raw file](https://github.com/gramineproject/contrib/blob/c5de43c76fb3c69034d056a7c0f4bec4aa716df2/Curated-Apps/README.md#L56)):*
> ```Markdown
> the curation application `curate.py` as shown below.
> 
> To generate a non-production test graminized image
> ```

Add `:` at the end
___
*[`Curated-Apps/verifier/verifier_helper_script.sh` line 8 at r29](https://reviewable.io/reviews/gramineproject/contrib/7#-NCdXzJsEP13EZKPgwxU:-NCdXzJsEP13EZKPgwxV:bjipxpp) ([raw file](https://github.com/gramineproject/contrib/blob/c5de43c76fb3c69034d056a7c0f4bec4aa716df2/Curated-Apps/verifier/verifier_helper_script.sh#L8)):*
> ```Shell
> # The input parameters in sequence are below:
> #   Argument                      Expected
> #   number                         Value
> ```

You can remove these two lines with "column names" (Argument number and Exptected value) -- it is obvious without these lines


<!-- Sent from Reviewable.io -->

2022-09-25 00:45 UTC, mkow requested changes
Disclaimer, for the record: I only did a very light review, as this is `contrib` repository (i.e. unofficial).
Overall it seems super hacky and of terrible quality, if we'd ever want to upstream this it will need to be completely rewritten.

> Reviewed 16 of 16 files at r16, 3 of 3 files at r17, 7 of 28 files at r23, 1 of 11 files at r27, 1 of 2 files at r30, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/7#-:-NClqgFN2LhwgqjEimqz:b-2q0laj)* status: 28 of 47 files reviewed, 94 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/7#-NAOqmDV4DscKOLPu6W6:-NClqvam0HeLENwf1CmU:btvo7zn) (no related file):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

Working on this.
</blockquote></details>

Isn't the very point of this script to be kind of a tutorial / configuration wizard? Adding a presentation to it seems like writing a tutorial how to follow some other tutorial ;)

___
___
*[`-- commits` line 2 at r30](https://reviewable.io/reviews/gramineproject/contrib/7#-NClruBW0XxRR_Q2Gvzy):*
We don't state the reason for the change in the one-liner, it's supposed to be super concise and clearly say _what is the change_ made by this commit.



_Suggestion:_
```
Add end-to-end GSC image curation tool
```
___
*[`-- commits` line 118 at r30](https://reviewable.io/reviews/gramineproject/contrib/7#-NClsHIHDNFuOz_JWO7X):*
Why there are commits from other people on this branch? Who's actually the author of this change?
___
*[`Curated-Apps/curate.py` line 7 at r30](https://reviewable.io/reviews/gramineproject/contrib/7#-NClsxacDJK0yQLkYTOQ:-NClsxacDJK0yQLkYTOR:b51xruq) ([raw file](https://github.com/gramineproject/contrib/blob/d6d5794ed332ba8a9081855d37b90f05d1ef6aa9/Curated-Apps/curate.py#L7)):*
> ```Python
> # user provided inputs to create the graminized Docker image using GSC. This script also calls into
> # a script to generate the verifier Docker image (for SGX remote attestation). The generated
> # verifier Docker image is supposed to be started together with the graminized Docker image, to
> ```

This is dangerously wrong, it sounds like both images should be run on the same machine...



_Code quote:_
```Python
verifier Docker image is supposed to be started together with the graminized Docker image
```
___
*[`Curated-Apps/curate.py` line 10 at r30](https://reviewable.io/reviews/gramineproject/contrib/7#-NCltIgU0wPsc5eR9cHt:-NCltIgU0wPsc5eR9cHu:b-11n2xj) ([raw file](https://github.com/gramineproject/contrib/blob/d6d5794ed332ba8a9081855d37b90f05d1ef6aa9/Curated-Apps/curate.py#L10)):*
> ```Python
> # verify the SGX attestation evidence (SGX quote) sent by the latter image.
> 
> # Following are the command line parameters accepted by this file:
> ```

Why some configs are passed through cmdline args and some through interactive prompts? This makes no sense to me.
___
*[`Curated-Apps/curate.py` line 11 at r30](https://reviewable.io/reviews/gramineproject/contrib/7#-NCltWYo-KrLLzFhM4GS:-NCltWYo-KrLLzFhM4GT:b-a4miw8) ([raw file](https://github.com/gramineproject/contrib/blob/d6d5794ed332ba8a9081855d37b90f05d1ef6aa9/Curated-Apps/curate.py#L11)):*
> ```Python
> 
> # Following are the command line parameters accepted by this file:
> #|--------------------------------------------------------------------------------------------------|
> ```

Line too long, ditto below
___
*[`Curated-Apps/curate.py` line 14 at r30](https://reviewable.io/reviews/gramineproject/contrib/7#-NCltb5kEArD15bUoQtY:-NCltb5kEArD15bUoQtZ:b-t3w6id) ([raw file](https://github.com/gramineproject/contrib/blob/d6d5794ed332ba8a9081855d37b90f05d1ef6aa9/Curated-Apps/curate.py#L14)):*
> ```Python
> #| Required?| Argument         | Description/Possible values                                        |
> #|----------|------------------|--------------------------------------------------------------------|
> #|    Yes   | <Workload type>  | Provide type of workload e.g., redis or pytorch etc..              |
> ```

double period



_Code quote:_
```Python
 etc.. 
```
___
*[`Curated-Apps/curate.py` line 14 at r30](https://reviewable.io/reviews/gramineproject/contrib/7#-NCluB4OCjxXco-GzsCW:-NCluB4PAbXHZdE43tJM:undefined) ([raw file](https://github.com/gramineproject/contrib/blob/d6d5794ed332ba8a9081855d37b90f05d1ef6aa9/Curated-Apps/curate.py#L14)):*
> ```Python
> #| Required?| Argument         | Description/Possible values                                        |
> #|----------|------------------|--------------------------------------------------------------------|
> #|    Yes   | <Workload type>  | Provide type of workload e.g., redis or pytorch etc..              |
> ```





_Suggestion:_
```Python
e.g.
```
___
*[`Curated-Apps/curate.py` line 16 at r30](https://reviewable.io/reviews/gramineproject/contrib/7#-NCltuXIBwi1IeaCEzEJ:-NCltuXIBwi1IeaCEzEK:bdj5qxy) ([raw file](https://github.com/gramineproject/contrib/blob/d6d5794ed332ba8a9081855d37b90f05d1ef6aa9/Curated-Apps/curate.py#L16)):*
> ```Python
> #|    Yes   | <Workload type>  | Provide type of workload e.g., redis or pytorch etc..              |
> #|    Yes   | <base image name>| Base image name to be graminized.                                  |
> #| Optional | 'debug'          | To generate graminized image with debug symbols for debugging.     |
> ```

If this is insecure then you have to state it explicitly.
___
*[`Curated-Apps/curate.py` line 17 at r30](https://reviewable.io/reviews/gramineproject/contrib/7#-NCltohU--3bwNvQDdsX:-NCltohU--3bwNvQDdsY:undefined) ([raw file](https://github.com/gramineproject/contrib/blob/d6d5794ed332ba8a9081855d37b90f05d1ef6aa9/Curated-Apps/curate.py#L17)):*
> ```Python
> #|    Yes   | <base image name>| Base image name to be graminized.                                  |
> #| Optional | 'debug'          | To generate graminized image with debug symbols for debugging.     |
> #| Optional | 'test'           | To generate no-production image with a test enclave signing key.   |
> ```





_Suggestion:_
```Python
non-production
```
___
*[`Curated-Apps/curate.py` line 79 at r30](https://reviewable.io/reviews/gramineproject/contrib/7#-NClug-2BAalTd1wxoHr:-NClug-2BAalTd1wxoHs:b-jztq3v) ([raw file](https://github.com/gramineproject/contrib/blob/d6d5794ed332ba8a9081855d37b90f05d1ef6aa9/Curated-Apps/curate.py#L79)):*
> ```Python
> 
> def resize_screen(screen_height, screen_width):
>     subprocess.call(["echo","-e",f"\x1b[8;{screen_height};{screen_width}t"])
> ```

You use `'` and `"` completely randomly in this script.



_Code quote (i):_
```Python
"echo"
```



_Code quote (ii):_
```Python
f'\nInsufficient or incorrect arguments.\n'
```
___
*[`Curated-Apps/curate.py` line 79 at r30](https://reviewable.io/reviews/gramineproject/contrib/7#-NClvB113zLNBVyKmkSc:-NClvB113zLNBVyKmkSd:b4qymi0) ([raw file](https://github.com/gramineproject/contrib/blob/d6d5794ed332ba8a9081855d37b90f05d1ef6aa9/Curated-Apps/curate.py#L79)):*
> ```Python
> 
> def resize_screen(screen_height, screen_width):
>     subprocess.call(["echo","-e",f"\x1b[8;{screen_height};{screen_width}t"])
> ```

Do you really need to start a new process to write to stdout?
___
*[`Curated-Apps/curate.py` line 80 at r30](https://reviewable.io/reviews/gramineproject/contrib/7#-NClv1nBCcBLX7Trc7d-:-NClv1nBCcBLX7Trc7d0:b-7wsukp) ([raw file](https://github.com/gramineproject/contrib/blob/d6d5794ed332ba8a9081855d37b90f05d1ef6aa9/Curated-Apps/curate.py#L80)):*
> ```Python
> def resize_screen(screen_height, screen_width):
>     subprocess.call(["echo","-e",f"\x1b[8;{screen_height};{screen_width}t"])
>     time.sleep(0.35)
> ```

Ouch. This is too much even for `contrib` repo.
___
*[`Curated-Apps/curate.py` line 87 at r30](https://reviewable.io/ [...]

2022-09-25 19:30 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/7)* status: 27 of 48 files reviewed, 94 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @dimakuv, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/7#-NAOqmDV4DscKOLPu6W6:-NCpymNYBQGzw3XIbO5e:bhozjsa) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Isn't the very point of this script to be kind of a tutorial / configuration wizard? Adding a presentation to it seems like writing a tutorial how to follow some other tutorial ;)
</blockquote></details>

I agree. But Dmitrii insisted we keep this. @dimakuv  - any change in thoughts? :)

___
*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/7#-NCdQT6N19V5bWmzK8d_:-NCpzIiW2EQPxr2Y8A2C:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

When I added some `blabla` arguments in one of the steps, it resulted in this `entry_script_redis.sh`:
```
#!/bin/bash

"docker-entrypoint.sh"bla bla bla bla --protected-mode no --save ''
```

This is clearly wrong.
</blockquote></details>

Done.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/7#-NCdRuoW7xKsTM1GEsZY:-NCpzK4X-gWgPRLpIEmG:b-6tnlr) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The curation script generated `commands.txt` like this:
```
docker run  --device=/dev/sgx/enclave -it gsc-redis:7.0.0
```

Where is `-v /var/run/aesmd/aesm.socket:/var/run/aesmd/aesm.socket`?

Also, why do you include `-it` argument (which is used for "interactive sessions") -- Redis is not interactive at all...
</blockquote></details>

For Redis - Without `-it` , the terminal becomes unusable (CTRL+C etc) too doesn't work. I prefer leaving the option to the user.
For `aesm.socket` - we dont provide attestation feature with 'test' option passed as a command-line parameter. Hence we leave this out of the run instructions.  

___
___
*[`-- commits` line 118 at r30](https://reviewable.io/reviews/gramineproject/contrib/7#-NClsHIHDNFuOz_JWO7X):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why there are commits from other people on this branch? Who's actually the author of this change?
</blockquote></details>

Jitender and Veena co-authors this PR with me. I have given them access to my branch.
___
*[`Curated-Apps/pytorch/base_image_helper/README.md` line 8 at r29](https://reviewable.io/reviews/gramineproject/contrib/7#-NCdXZL5ASt3EC_HNpHF:-NCq4Tj8-xDVFG8WUZMc:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/c5de43c76fb3c69034d056a7c0f4bec4aa716df2/Curated-Apps/pytorch/base_image_helper/README.md#L8)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`gramine` -> `Gramine`
</blockquote></details>

Done.
___
*[`Curated-Apps/curate.py` line 7 at r30](https://reviewable.io/reviews/gramineproject/contrib/7#-NClsxacDJK0yQLkYTOQ:-NCq-YlzCxvL59iuNQNV:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/d6d5794ed332ba8a9081855d37b90f05d1ef6aa9/Curated-Apps/curate.py#L7)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This is dangerously wrong, it sounds like both images should be run on the same machine...
</blockquote></details>

Done.
___
*[`Curated-Apps/curate.py` line 10 at r30](https://reviewable.io/reviews/gramineproject/contrib/7#-NCltIgU0wPsc5eR9cHt:-NCq-ZSF03i6w5KvnPMZ:bibfcaa) ([raw file](https://github.com/gramineproject/contrib/blob/d6d5794ed332ba8a9081855d37b90f05d1ef6aa9/Curated-Apps/curate.py#L10)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why some configs are passed through cmdline args and some through interactive prompts? This makes no sense to me.
</blockquote></details>

Yes this was done on purpose. Asking too many questions through interactive prompts could tire the user. So the script takes all the easy stuff through cmdline, and the interactive stuff deals with more complex situations (for eg attestation.. secret prov.. enc files etc etc).
___
*[`Curated-Apps/curate.py` line 11 at r30](https://reviewable.io/reviews/gramineproject/contrib/7#-NCltWYo-KrLLzFhM4GS:-NCq00Su0EWEFWcljqEO:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/d6d5794ed332ba8a9081855d37b90f05d1ef6aa9/Curated-Apps/curate.py#L11)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Line too long, ditto below
</blockquote></details>

Done.
___
*[`Curated-Apps/curate.py` line 14 at r30](https://reviewable.io/reviews/gramineproject/contrib/7#-NCltb5kEArD15bUoQtY:-NCq010f41iLV5wFoI7z:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/d6d5794ed332ba8a9081855d37b90f05d1ef6aa9/Curated-Apps/curate.py#L14)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

double period
</blockquote></details>

Done.
___
*[`Curated-Apps/curate.py` line 14 at r30](https://reviewable.io/reviews/gramineproject/contrib/7#-NCluB4OCjxXco-GzsCW:-NCq0XiC3CASOWXg8_gv:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/d6d5794ed332ba8a9081855d37b90f05d1ef6aa9/Curated-Apps/curate.py#L14)):*
> ```Python
> #| Required?| Argument         | Description/Possible values                                        |
> #|----------|------------------|--------------------------------------------------------------------|
> #|    Yes   | <Workload type>  | Provide type of workload e.g., redis or pytorch etc..              |
> ```

Done.
___
*[`Curated-Apps/curate.py` line 16 at r30](https://reviewable.io/reviews/gramineproject/contrib/7#-NCltuXIBwi1IeaCEzEJ:-NCq01xBE_RhYLTj1Z21:bnzqsfc) ([raw file](https://github.com/gramineproject/contrib/blob/d6d5794ed332ba8a9081855d37b90f05d1ef6aa9/Curated-Apps/curate.py#L16)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

If this is insecure then you have to state it explicitly.
</blockquote></details>

Not insecure. Throughout the script, "insecure" is called wherever test configs are in play.
___
*[`Curated-Apps/curate.py` line 17 at r30](https://reviewable.io/reviews/gramineproject/contrib/7#-NCltohU--3bwNvQDdsX:-NCq0YRJEmTwdUJ_Ywa6:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/d6d5794ed332ba8a9081855d37b90f05d1ef6aa9/Curated-Apps/curate.py#L17)):*
> ```Python
> #|    Yes   | <base image name>| Base image name to be graminized.                                  |
> #| Optional | 'debug'          | To generate graminized image with debug symbols for debugging.     |
> #| Optional | 'test'           | To generate no-production image with a test enclave signing key.   |
> ```

Done.
___
*[`Curated-Apps/curate.py` line 79 at r30](https://reviewable.io/reviews/gramineproject/contrib/7#-NClug-2BAalTd1wxoHr:-NCq0_6k70pXi2_H6GMc:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/d6d5794ed332ba8a9081855d37b90f05d1ef6aa9/Curated-Apps/curate.py#L79)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

You use `'` and `"` completely randomly in this script.
</blockquote></details>

Done.
___
*[`Curated-Apps/curate.py` line 79 at r30](https://reviewable.io/reviews/gramineproject/contrib/7#-NClvB113zLNBVyKmkSc:-NCq0_o1Eg48AfQGhf2X:bugn1a4) ([raw file](https://github.com/gramineproject/contrib/blob/d6d5794ed332ba8a9081855d37b90f05d1ef6aa9/Curated-Apps/curate.py#L79)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Do you really need to start a new process to write to stdout?
</blockquo [...]

2022-09-25 21:26 UTC, mkow requested changes
> Reviewed 1 of 6 files at r33, 1 of 5 files at r34, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/7)* status: 28 of 48 files reviewed, 90 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @dimakuv)

___
*[`-- commits` line 118 at r30](https://reviewable.io/reviews/gramineproject/contrib/7#-NClsHIHDNFuOz_JWO7X):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

Jitender and Veena co-authors this PR with me. I have given them access to my branch.
</blockquote></details>

Then you'll need to add `Co-authored-by` and proper sign-offs to the final commit.
___
*[`Curated-Apps/curate.py` line 10 at r30](https://reviewable.io/reviews/gramineproject/contrib/7#-NCltIgU0wPsc5eR9cHt:-NCqOaYQCPb4tDdT26jk:b-55v5p8) ([raw file](https://github.com/gramineproject/contrib/blob/d6d5794ed332ba8a9081855d37b90f05d1ef6aa9/Curated-Apps/curate.py#L10)):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

Yes this was done on purpose. Asking too many questions through interactive prompts could tire the user. So the script takes all the easy stuff through cmdline, and the interactive stuff deals with more complex situations (for eg attestation.. secret prov.. enc files etc etc).
</blockquote></details>

Uh, still doesn't make sense to me, but I won't block on this.
___
*[`Curated-Apps/curate.py` line 16 at r30](https://reviewable.io/reviews/gramineproject/contrib/7#-NCltuXIBwi1IeaCEzEJ:-NCqOrPm7edyc3Vr9sVv:b3m92y7) ([raw file](https://github.com/gramineproject/contrib/blob/d6d5794ed332ba8a9081855d37b90f05d1ef6aa9/Curated-Apps/curate.py#L16)):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

Not insecure. Throughout the script, "insecure" is called wherever test configs are in play.
</blockquote></details>

What does this option do exactly?
___
*[`Curated-Apps/curate.py` line 79 at r30](https://reviewable.io/reviews/gramineproject/contrib/7#-NClvB113zLNBVyKmkSc:-NCqPYLK4eqQShZMWzps:bove06c) ([raw file](https://github.com/gramineproject/contrib/blob/d6d5794ed332ba8a9081855d37b90f05d1ef6aa9/Curated-Apps/curate.py#L79)):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

Yes. Tried other options and nothing worked to resize the terminal. 
</blockquote></details>

How's that possible? This makes no sense.
___
*[`Curated-Apps/curate.py` line 80 at r30](https://reviewable.io/reviews/gramineproject/contrib/7#-NClv1nBCcBLX7Trc7d-:-NCqPyTC-qogO0MBV_VE:b-5qpt1x) ([raw file](https://github.com/gramineproject/contrib/blob/d6d5794ed332ba8a9081855d37b90f05d1ef6aa9/Curated-Apps/curate.py#L80)):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

This value was arrived at after extensive testing (initial values where about 50ms). This seem like a safe delay to let the screen resize before we start rendering text to it. In future we can look at implementing this better (event/callback based if supported).
</blockquote></details>

Please never ever synchronize things via `sleep()`, it doesn't matter that you've tested this on your machines.
___
*[`Curated-Apps/curate.py` line 229 at r30](https://reviewable.io/reviews/gramineproject/contrib/7#-NClyqk-19umE8R7rN2F:-NCqSiEV68QikQMIagda:b-1yh2p) ([raw file](https://github.com/gramineproject/contrib/blob/d6d5794ed332ba8a9081855d37b90f05d1ef6aa9/Curated-Apps/curate.py#L229)):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

Yes I agree in principle. But Gramine would throw a non prod warning as well - in this case. Is'nt that sufficient? We're just trying to get the user up and running with minimal time assuming he/she doesn't have all the information handy to begin with. 
</blockquote></details>

This warning will appear on the deployed machine, and likely right after it will receive some secrets. Please change the defaults or the workflow. It can't be that by pressing "Next" n-times you get something which is insecure.
___
*[`Curated-Apps/curate.py` line 248 at r30](https://reviewable.io/reviews/gramineproject/contrib/7#-NClz_OkAUhDs2vAvuF2:-NCqTMuxDTcbkqZtUKDL:bzeqlkn) ([raw file](https://github.com/gramineproject/contrib/blob/d6d5794ed332ba8a9081855d37b90f05d1ef6aa9/Curated-Apps/curate.py#L248)):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

Default option is no attestation (or skip attestation) - why's this considered insecure as far a host enclave is concerned?
</blockquote></details>

What's "a host enclave"?
Does "lack of attestation" here imply lack of any secret provisioning?
___
*[`Curated-Apps/curate.py` line 33 at r34](https://reviewable.io/reviews/gramineproject/contrib/7#-NCqP1AZ2ahsv4GDaskE:-NCqP1AZ2ahsv4GDaskF:undefined) ([raw file](https://github.com/gramineproject/contrib/blob/a90256e4c3aecc71c920b93ab999950b26871d7f/Curated-Apps/curate.py#L33)):*
> ```Python
> from sys import argv
> 
> # Following are the command line parameters accepted by this file:
> ```





_Suggestion:_
```Python
accepted by this script:
```
___
*[`Curated-Apps/curate.py` line 38 at r34](https://reviewable.io/reviews/gramineproject/contrib/7#-NCqP9JL5bC2BUHW2b09:-NCqP9JL5bC2BUHW2b0A:b-ppmqgm) ([raw file](https://github.com/gramineproject/contrib/blob/a90256e4c3aecc71c920b93ab999950b26871d7f/Curated-Apps/curate.py#L38)):*
> ```Python
> | Required?| Argument         | Description/Possible values                                   |
> |----------|------------------|---------------------------------------------------------------|
> |    Yes   | <Workload type>  | Provide type of workload e.g. redis or pytorch                |
> ```

Why "<Workload type>" is capitalized, but "<base image name>" isn't?



_Code quote (i):_
```Python
<Workload type>
```



_Code quote (ii):_
```Python
<base image name>
```
___
*[`Curated-Apps/curate.py` line 197 at r34](https://reviewable.io/reviews/gramineproject/contrib/7#-NCqQefm5vcrziXvETST:-NCqQefm5vcrziXvETSU:bn4c59f) ([raw file](https://github.com/gramineproject/contrib/blob/a90256e4c3aecc71c920b93ab999950b26871d7f/Curated-Apps/curate.py#L197)):*
> ```Python
>         win.addstr(f'For more info, look at the log file here: {log_file}')
>         win.getch()
>         sys.exit(-1)
> ```

I don't think negative exit codes are documented/supported officially on Linux.
___
*[`Curated-Apps/curate.py` line 214 at r34](https://reviewable.io/reviews/gramineproject/contrib/7#-NCqSSqY3feWxSr53-c2:-NCqSSqY3feWxSr53-c3:b-oiot14) ([raw file](https://github.com/gramineproject/contrib/blob/a90256e4c3aecc71c920b93ab999950b26871d7f/Curated-Apps/curate.py#L214)):*
> ```Python
>         user_console.erase()
>         update_user_and_commentary_win_array(user_console, guide_win, encrypted_files_prompt,
>          encypted_files_help)
> ```

Again, why do you keep indenting everything randomly? Please configure your IDE/editor properly...
___
*[`Curated-Apps/curate.py` line 231 at r34](https://reviewable.io/reviews/gramineproject/contrib/7#-NCqTGmB5fMesq-04QqL:-NCqTGmB5fMesq-04QqM:b1yby4v) ([raw file](https://github.com/gramineproject/contrib/blob/a90256e4c3aecc71c920b93ab999950b26871d7f/Curated-Apps/curate.py#L231)):*
> ```Python
>         else:
>             user_console.erase()
>             update_user_and_commentary_win_array(user_console, guide_win, key_prompt, signing_key_help)
> ```

line too long
___
*[`Curated-Apps/curate.py` line 242 at r34](https://reviewable.io/reviews/gramineproject/contrib/7#-NCqTZN206UN-a5ylVRA:-NCqTZN35U-Dpp_bWmDx:b-ciixnx) ([raw file](https://github.com/gramineproject/contrib/blob/a90256e4c3aecc71c920b93ab999950b26871d7f/Curated-Apps/curate.py#L242)):*
> ```Python
>             user_consol [...]

2022-09-26 08:21 UTC, dimakuv requested changes
> Reviewed 11 of 28 files at r23, 5 of 11 files at r27, 1 of 1 files at r29, 3 of 9 files at r31, 1 of 6 files at r32, 2 of 6 files at r33, 4 of 5 files at r34, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/7)* status: all files reviewed, 38 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/7#-NAOqmDV4DscKOLPu6W6:-NCskSbBB2mAqlWB0Rs7:b-kjaivj) (no related file):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

I agree. But Dmitrii insisted we keep this. @dimakuv  - any change in thoughts? :)
</blockquote></details>

I still think that an explanation would be useful. Of course, this can be done after we merge this PR (we'll need to work more on this Curated Apps script anyway, so several follow-up PRs are needed).

I am resolving this current comment anyway. The PDF/presentation can be postponed.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/7#-NCdK-6yEipkQ6Q8bIWJ:-NCskjFO6xFsVKA4xP0s:b7xuvyd) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't see what I type in the script. Is this normal? Why does this happen? It seems to be black font on black background, which obviously is invisible.

I run on my local machine bare-metal with Ubuntu 20.04 (*not* on an Azure VM).
</blockquote></details>

Update: this may be because I use `tmux`. I'll check without it.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/7#-NCdRuoW7xKsTM1GEsZY:-NCskwwT894Gjp9Xq3Or:bs52rjl) (no related file):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

For Redis - Without `-it` , the terminal becomes unusable (CTRL+C etc) too doesn't work. I prefer leaving the option to the user.
For `aesm.socket` - we dont provide attestation feature with 'test' option passed as a command-line parameter. Hence we leave this out of the run instructions.  
</blockquote></details>

Got it. Makes sense.

___
___
*[`-- commits` line 118 at r30](https://reviewable.io/reviews/gramineproject/contrib/7#-NClsHIHDNFuOz_JWO7X):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Then you'll need to add `Co-authored-by` and proper sign-offs to the final commit.
</blockquote></details>

By the way, I can do this during final rebase.
___
*[`Curated-Apps/pytorch/base_image_helper/README.md` line 19 at r34](https://reviewable.io/reviews/gramineproject/contrib/7#-NCsojhE3d_hEKNoPcHM:-NCsojhE3d_hEKNoPcHN:b-53vu0h) ([raw file](https://github.com/gramineproject/contrib/blob/a90256e4c3aecc71c920b93ab999950b26871d7f/Curated-Apps/pytorch/base_image_helper/README.md#L19)):*
> ```Markdown
>   encrypted files.
> 
> Please refer `Curated-Apps/README.md` to curate the image created in above steps with GSC.
> ```

`refer` -> `refer to`
___
*[`Curated-Apps/redis/README.md` line 1 at r34](https://reviewable.io/reviews/gramineproject/contrib/7#-NCsp1Qe5plOicrOojLv:-NCsp1Qe5plOicrOojLw:b7dz8pj) ([raw file](https://github.com/gramineproject/contrib/blob/a90256e4c3aecc71c920b93ab999950b26871d7f/Curated-Apps/redis/README.md#L1)):*
> ```Markdown
> This directory contains artifacts which helps in creating curated GSC Redis image, as explained
> ```

`helps` -> `help`
___
*[`GSC-Image-Curation/config.yaml` line 32 at r3](https://reviewable.io/reviews/gramineproject/contrib/7#-NAOofUKBo1nIuN3NthM:-NCspCyI1yUeIFgxJN8a:b-agne02) ([raw file](https://github.com/gramineproject/contrib/blob/c2401566b780a71ea25e07737bd132a8c0375fed/GSC-Image-Curation/config.yaml#L32)):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

ditto what? Sorry, I can't find the corresponding discussion you're referring to.
___
*[`Curated-Apps/curate.py` line 10 at r30](https://reviewable.io/reviews/gramineproject/contrib/7#-NCltIgU0wPsc5eR9cHt:-NCslXFM8h6Ky2eN-HPK:b-oaluwf) ([raw file](https://github.com/gramineproject/contrib/blob/d6d5794ed332ba8a9081855d37b90f05d1ef6aa9/Curated-Apps/curate.py#L10)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Uh, still doesn't make sense to me, but I won't block on this.
</blockquote></details>

I think the additional point is that "normal users" will never use `test` and `debug` options. These options are purely for "developers".
___
*[`Curated-Apps/curate.py` line 18 at r34](https://reviewable.io/reviews/gramineproject/contrib/7#-NCsleYB5pdraqXNUG22:-NCsleYB5pdraqXNUG23:bsuas13) ([raw file](https://github.com/gramineproject/contrib/blob/a90256e4c3aecc71c920b93ab999950b26871d7f/Curated-Apps/curate.py#L18)):*
> ```Python
> import os
> import os.path
> import platform;
> ```

No need for a `;`, please remove
___
*[`Curated-Apps/curate.py` line 197 at r34](https://reviewable.io/reviews/gramineproject/contrib/7#-NCqQefm5vcrziXvETST:-NCsmUoI6GQsBGYUb-Co:b4qxuua) ([raw file](https://github.com/gramineproject/contrib/blob/a90256e4c3aecc71c920b93ab999950b26871d7f/Curated-Apps/curate.py#L197)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I don't think negative exit codes are documented/supported officially on Linux.
</blockquote></details>

+1, just use `sys.exit(1)` as it was before.
___
*[`Curated-Apps/README.md` line 34 at r29](https://reviewable.io/reviews/gramineproject/contrib/7#-NCdUmTMBVmD2Cq3H-XQ:-NCsnyBn53Pfyd0V6yfX:b-ylpi2x) ([raw file](https://github.com/gramineproject/contrib/blob/c5de43c76fb3c69034d056a7c0f4bec4aa716df2/Curated-Apps/README.md#L34)):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

Yes - The table gets messed up real bad without those 4-spaces.
</blockquote></details>

Ok, whatever.
___
*[`Curated-Apps/README.md` line 62 at r34](https://reviewable.io/reviews/gramineproject/contrib/7#-NCsoEZl0juzqqJyp4UE:-NCsoEZl0juzqqJyp4UF:b-q4fgcc) ([raw file](https://github.com/gramineproject/contrib/blob/a90256e4c3aecc71c920b93ab999950b26871d7f/Curated-Apps/README.md#L62)):*
> ```Markdown
> `$ /bin/bash "helper.sh"`
> `$ cd ../..`
> `$ python3 ./curate.py pytorch pytorch-encrypted test`
> ```

This looks ugly and unexpected (see https://github.com/aneessahib/contrib/tree/aneessahib/gsc_image_curation/Curated-Apps#pytorch)

Please instead of four single-backtick lines, use a three-backticks 4-line code snippet.
___
*[`Curated-Apps/pytorch/base_image_helper/helper.sh` line 25 at r34](https://reviewable.io/reviews/gramineproject/contrib/7#-NCsodz-9Sb4xK1gXotB:-NCsodz-9Sb4xK1gXotC:b-53vu0h) ([raw file](https://github.com/gramineproject/contrib/blob/a90256e4c3aecc71c920b93ab999950b26871d7f/Curated-Apps/pytorch/base_image_helper/helper.sh#L25)):*
> ```Shell
> 
> echo -e '\n\nCreated base image `$image_name`.'
> echo -e 'Please refer `Curated-Apps/README.md` to curate the above image with GSC.\n'
> ```

`refer` -> `refer to`
___
*[`Curated-Apps/pytorch/base_image_helper/wrap_key` line  at r30](https://reviewable.io/reviews/gramineproject/contrib/7#-NCm3S6F1e5Yl63NKSQT:-NCsoq94A49QdnZXX3ej:byymkaf) ([raw file](https://github.com/gramineproject/contrib/blob/d6d5794ed332ba8a9081855d37b90f05d1ef6aa9/Curated-Apps/pytorch/base_image_helper/wrap_key#L)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

It was deleted from that example for a reason. If you want a test key then generate a random one.
</blockquote></details>

To satisfy Michal's request, please use something like this command (https://github.com/gramineproject/gramine/blob/4f259b80ed4c40e7cccde70e822d378754dacb97/CI-Examples/ra-tls-secret-prov/Makefile#L158-L159), adding it [...]

2022-09-26 18:02 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/7)* status: 29 of 50 files reviewed, 37 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @dimakuv, and @mkow)

___
*[`Curated-Apps/redis/README.md` line 1 at r34](https://reviewable.io/reviews/gramineproject/contrib/7#-NCsp1Qe5plOicrOojLv:-NCuw_1iE8hb0rjQw89N:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/a90256e4c3aecc71c920b93ab999950b26871d7f/Curated-Apps/redis/README.md#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`helps` -> `help`
</blockquote></details>

Done.
___
*[`GSC-Image-Curation/config.yaml` line 32 at r3](https://reviewable.io/reviews/gramineproject/contrib/7#-NAOofUKBo1nIuN3NthM:-NCuvpPp9NmDhUx-Mtvk:b2abjan) ([raw file](https://github.com/gramineproject/contrib/blob/c2401566b780a71ea25e07737bd132a8c0375fed/GSC-Image-Curation/config.yaml#L32)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto what? Sorry, I can't find the corresponding discussion you're referring to.
</blockquote></details>

As in we earlier clarified in another comment that we can leave this as is with DCAP_1.11 since it works on both 18.04 and 20.04 Azure VM.
___
*[`Curated-Apps/curate.py` line 16 at r30](https://reviewable.io/reviews/gramineproject/contrib/7#-NCltuXIBwi1IeaCEzEJ:-NCuwqRh1NtQ2KLynmVD:buvrwy3) ([raw file](https://github.com/gramineproject/contrib/blob/d6d5794ed332ba8a9081855d37b90f05d1ef6aa9/Curated-Apps/curate.py#L16)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What does this option do exactly?
</blockquote></details>

Are you talking about `test` option? What we do is `sgx.file_check_policy = allow_all_but_log` . Two benefits of doing this - short manifest (since its only test), and Gramine inherently throws a non-prod warning at run-time. 
___
*[`Curated-Apps/curate.py` line 79 at r30](https://reviewable.io/reviews/gramineproject/contrib/7#-NClvB113zLNBVyKmkSc:-NCusnSW5bP2ScSduNHm:btlhies) ([raw file](https://github.com/gramineproject/contrib/blob/d6d5794ed332ba8a9081855d37b90f05d1ef6aa9/Curated-Apps/curate.py#L79)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

How's that possible? This makes no sense.
</blockquote></details>

There are other ways to write to stdout the same thing, but fails to resize. Didnt spend more time on this after we got something working. 
___
*[`Curated-Apps/curate.py` line 80 at r30](https://reviewable.io/reviews/gramineproject/contrib/7#-NClv1nBCcBLX7Trc7d-:-NCutWZZ1-DRUi9IVj9o:bmpybn2) ([raw file](https://github.com/gramineproject/contrib/blob/d6d5794ed332ba8a9081855d37b90f05d1ef6aa9/Curated-Apps/curate.py#L80)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please never ever synchronize things via `sleep()`, it doesn't matter that you've tested this on your machines.
</blockquote></details>

Yes I agree in principle. We will have to check if there are other ways to synchronize using the python curses framework but this will take time. 
___
*[`Curated-Apps/curate.py` line 229 at r30](https://reviewable.io/reviews/gramineproject/contrib/7#-NClyqk-19umE8R7rN2F:-NCuu5-20TVIK4eXM3OQ:b-mqvv9x) ([raw file](https://github.com/gramineproject/contrib/blob/d6d5794ed332ba8a9081855d37b90f05d1ef6aa9/Curated-Apps/curate.py#L229)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This warning will appear on the deployed machine, and likely right after it will receive some secrets. Please change the defaults or the workflow. It can't be that by pressing "Next" n-times you get something which is insecure.
</blockquote></details>

Ok. Removed insecure default option. User will have to type `test` to proceed with an insecure flow
___
*[`Curated-Apps/curate.py` line 248 at r30](https://reviewable.io/reviews/gramineproject/contrib/7#-NClz_OkAUhDs2vAvuF2:-NCuuFV6-tS1FMrZR9cN:b-9u1hcs) ([raw file](https://github.com/gramineproject/contrib/blob/d6d5794ed332ba8a9081855d37b90f05d1ef6aa9/Curated-Apps/curate.py#L248)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What's "a host enclave"?
Does "lack of attestation" here imply lack of any secret provisioning?
</blockquote></details>

Host enclave refers to the deployed GSC image. Lack of attestation means `sgx.remote_attestation` is not specified in manifest.
___
*[`Curated-Apps/curate.py` line 18 at r34](https://reviewable.io/reviews/gramineproject/contrib/7#-NCsleYB5pdraqXNUG22:-NCusjnJ9k3E_7MPQESf:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/a90256e4c3aecc71c920b93ab999950b26871d7f/Curated-Apps/curate.py#L18)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

No need for a `;`, please remove
</blockquote></details>

Done.
___
*[`Curated-Apps/curate.py` line 33 at r34](https://reviewable.io/reviews/gramineproject/contrib/7#-NCqP1AZ2ahsv4GDaskE:-NCuslFiA27WQU2rAdMX:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/a90256e4c3aecc71c920b93ab999950b26871d7f/Curated-Apps/curate.py#L33)):*
> ```Python
> from sys import argv
> 
> # Following are the command line parameters accepted by this file:
> ```

Done.
___
*[`Curated-Apps/curate.py` line 38 at r34](https://reviewable.io/reviews/gramineproject/contrib/7#-NCqP9JL5bC2BUHW2b09:-NCusmG_6JsHYPMT7yoB:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/a90256e4c3aecc71c920b93ab999950b26871d7f/Curated-Apps/curate.py#L38)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why "<Workload type>" is capitalized, but "<base image name>" isn't?
</blockquote></details>

Done.
___
*[`Curated-Apps/curate.py` line 197 at r34](https://reviewable.io/reviews/gramineproject/contrib/7#-NCqQefm5vcrziXvETST:-NCuu1B20gXgXSQ3y-d8:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/a90256e4c3aecc71c920b93ab999950b26871d7f/Curated-Apps/curate.py#L197)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1, just use `sys.exit(1)` as it was before.
</blockquote></details>

Done.
___
*[`Curated-Apps/curate.py` line 214 at r34](https://reviewable.io/reviews/gramineproject/contrib/7#-NCqSSqY3feWxSr53-c2:-NCuu3HNBIGJOwSw8LUD:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/a90256e4c3aecc71c920b93ab999950b26871d7f/Curated-Apps/curate.py#L214)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Again, why do you keep indenting everything randomly? Please configure your IDE/editor properly...
</blockquote></details>

Done.
___
*[`Curated-Apps/curate.py` line 231 at r34](https://reviewable.io/reviews/gramineproject/contrib/7#-NCqTGmB5fMesq-04QqL:-NCuuBgA9OTJo-dZIIf3:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/a90256e4c3aecc71c920b93ab999950b26871d7f/Curated-Apps/curate.py#L231)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

line too long
</blockquote></details>

Done.
___
*[`Curated-Apps/curate.py` line 242 at r34](https://reviewable.io/reviews/gramineproject/contrib/7#-NCqTZN206UN-a5ylVRA:-NCuujbA9qStosDaqYE-:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/a90256e4c3aecc71c920b93ab999950b26871d7f/Curated-Apps/curate.py#L242)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

again...
</blockquote></details>

Done.
___
*[`Curated-Apps/curate.py` line 252 at r34](https://reviewable.io/reviews/gramineproject/contrib/7#-NCqTcKGEkL44dbgRSG5:-NCuuk6P8SBuYdPesBlC:b-896fix) ([raw file [...]

2022-09-26 18:51 UTC, dimakuv requested changes
> Reviewed 3 of 11 files at r35, 16 of 18 files at r36, 2 of 2 files at r37, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/7)* status: all files reviewed, 42 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/7#-NCdK-6yEipkQ6Q8bIWJ:-NCv11Ao8kMohji_Yfo9:b-7ll3i6) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Update: this may be because I use `tmux`. I'll check without it.
</blockquote></details>

I still can't see what I type, even without `tmux`. (I use Putty.) Well, whatever, looks like a problem on my side that we can resolve later.

___
___
*[`Curated-Apps/workloads/pytorch/README.md` line 3 at r37](https://reviewable.io/reviews/gramineproject/contrib/7#-NCv5K599BJqpja6s99z:-NCv5K599BJqpja6s9A-:b-z9sj5q) ([raw file](https://github.com/gramineproject/contrib/blob/aa9b9d8e73cc40ccd59478b25a5d6f90f6971aa7/Curated-Apps/workloads/pytorch/README.md#L3)):*
> ```Markdown
> # Gramine Curated PyTorch
> In the following two sections, we explain how a Docker image for the protected PyTorch version can
> be build and how the image can be executed.
> ```

`be build` -> `be built`
___
*[`Curated-Apps/workloads/pytorch/README.md` line 27 at r37](https://reviewable.io/reviews/gramineproject/contrib/7#-NCv5cOD4P6cLfAsZAl3:-NCv5cOD4P6cLfAsZAl4:b-x2t9lu) ([raw file](https://github.com/gramineproject/contrib/blob/aa9b9d8e73cc40ccd59478b25a5d6f90f6971aa7/Curated-Apps/workloads/pytorch/README.md#L27)):*
> ```Markdown
>  2. Generate the test confidential compute image based on the `pytorch-encrypted` image as shown
>     below:
>     `$ python3 ./curate.py pytorch pytorch-encrypted test`
> ```

These subbullets do not render as you expected: https://github.com/aneessahib/contrib/tree/aneessahib/gsc_image_curation/Curated-Apps/workloads/pytorch

You need to have 4 spaces of indentation, not 1.
___
*[`Curated-Apps/workloads/pytorch/README.md` line 38 at r37](https://reviewable.io/reviews/gramineproject/contrib/7#-NCv6AyD8BEmOzjVvzKB:-NCv6AyD8BEmOzjVvzKC:b-rx747g) ([raw file](https://github.com/gramineproject/contrib/blob/aa9b9d8e73cc40ccd59478b25a5d6f90f6971aa7/Curated-Apps/workloads/pytorch/README.md#L38)):*
> ```Markdown
> 
> - Follow the output of the image build script `curate.py` to run the generated Docker image
> - The example used here was tested on a Standard_DC8s_v3 Azure VM.
> ```

The current bullet list doesn't make sense. The first sentence repeats what was already said in the previous section. Please replace this whole section's text with this:
```
This example was tested on a Standard_DC8s_v3 Azure VM.

Follow the output of the `curate.py` script to run the generated Docker image(s).
```
___
*[`Curated-Apps/workloads/pytorch/README.md` line 41 at r37](https://reviewable.io/reviews/gramineproject/contrib/7#-NCv6bcW7j0ts-ztoxbW:-NCv6bcW7j0ts-ztoxbX:b7dz8pj) ([raw file](https://github.com/gramineproject/contrib/blob/aa9b9d8e73cc40ccd59478b25a5d6f90f6971aa7/Curated-Apps/workloads/pytorch/README.md#L41)):*
> ```Markdown
> 
> ## Contents
> This sub-directory contains artifacts which helps in creating curated GSC Redis image, as explained
> ```

`helps` -> `help`
___
*[`Curated-Apps/workloads/pytorch/README.md` line 41 at r37](https://reviewable.io/reviews/gramineproject/contrib/7#-NCv6dWA7et2_N2nqgGl:-NCv6dWA7et2_N2nqgGm:b-szcu02) ([raw file](https://github.com/gramineproject/contrib/blob/aa9b9d8e73cc40ccd59478b25a5d6f90f6971aa7/Curated-Apps/workloads/pytorch/README.md#L41)):*
> ```Markdown
> 
> ## Contents
> This sub-directory contains artifacts which helps in creating curated GSC Redis image, as explained
> ```

`Redis` -> `PyTorch`
___
*[`Curated-Apps/workloads/pytorch/README.md` line 49 at r37](https://reviewable.io/reviews/gramineproject/contrib/7#-NCv7lBWD4AKSV4HfRKY:-NCv7lBWD4AKSV4HfRKZ:b-so3813) ([raw file](https://github.com/gramineproject/contrib/blob/aa9b9d8e73cc40ccd59478b25a5d6f90f6971aa7/Curated-Apps/workloads/pytorch/README.md#L49)):*
> ```Markdown
>     |                                       dockerfile `redis-gsc.dockerfile` that includes
>     |                                       user-provided inputs such as `ca.cert` file and
>     |                                       run-time arguments into the graminized PyTorch image.
> ```

`command-line arguments`
___
*[`Curated-Apps/workloads/pytorch/README.md` line 50 at r37](https://reviewable.io/reviews/gramineproject/contrib/7#-NCv6hVa-sTXUxsyz-PQ:-NCv6hVa-sTXUxsyz-PR:b-riqiw2) ([raw file](https://github.com/gramineproject/contrib/blob/aa9b9d8e73cc40ccd59478b25a5d6f90f6971aa7/Curated-Apps/workloads/pytorch/README.md#L50)):*
> ```Markdown
>     |                                       user-provided inputs such as `ca.cert` file and
>     |                                       run-time arguments into the graminized PyTorch image.
>     +-- redis.manifest.template           # Template used by `curation_script.sh` to create a
> ```

`redis.manifest.template` -> `pytorch.manifest.template`
___
*[`Curated-Apps/workloads/redis/README.md` line 3 at r37](https://reviewable.io/reviews/gramineproject/contrib/7#-NCv7HW8BZ9fPtlqewzB:-NCv7HW8BZ9fPtlqewzC:b-bial0a) ([raw file](https://github.com/gramineproject/contrib/blob/aa9b9d8e73cc40ccd59478b25a5d6f90f6971aa7/Curated-Apps/workloads/redis/README.md#L3)):*
> ```Markdown
> # Gramine Curated Redis
> In the following two sections, we explain how a Docker image for the protected Redis version can be
> build and how the image can be executed.
> ```

`build` -> `built`
___
*[`Curated-Apps/workloads/redis/README.md` line 16 at r37](https://reviewable.io/reviews/gramineproject/contrib/7#-NCv7MsE6jFC9O1Cib66:-NCv7MsE6jFC9O1Cib67:bhdj6nq) ([raw file](https://github.com/gramineproject/contrib/blob/aa9b9d8e73cc40ccd59478b25a5d6f90f6971aa7/Curated-Apps/workloads/redis/README.md#L16)):*
> ```Markdown
>    `$ cd contrib/Curated-Apps`
> 
> 3. To generate a preconfigured confidential compute image for redis, execute the following script:
> ```

`redis` -> `Redis`
___
*[`Curated-Apps/workloads/redis/README.md` line 28 at r37](https://reviewable.io/reviews/gramineproject/contrib/7#-NCv7XDyE35TPLVQrDw8:-NCv7XDyE35TPLVQrDw9:b-rx747g) ([raw file](https://github.com/gramineproject/contrib/blob/aa9b9d8e73cc40ccd59478b25a5d6f90f6971aa7/Curated-Apps/workloads/redis/README.md#L28)):*
> ```Markdown
> 
> - Follow the output of the image build script `curate.py` to run the generated Docker image
> - The test example used here was tested on a Standard_DC2s_v2 Azure VM.
> ```

The current bullet list doesn't make sense. The first sentence repeats what was already said in the previous section. Please replace this whole section's text with this:
```
This example was tested on a Standard_DC8s_v3 Azure VM.

Follow the output of the `curate.py` script to run the generated Docker image(s).
```
___
*[`Curated-Apps/workloads/redis/README.md` line 37 at r37](https://reviewable.io/reviews/gramineproject/contrib/7#-NCv7bcB6CTjgDQhRZ6g:-NCv7bcB6CTjgDQhRZ6h:b-nci6ub) ([raw file](https://github.com/gramineproject/contrib/blob/aa9b9d8e73cc40ccd59478b25a5d6f90f6971aa7/Curated-Apps/workloads/redis/README.md#L37)):*
> ```Markdown
>     +-- redis-gsc.dockerfile.template      # Template used by `curation_script.sh` to create a
>     |                                        wrapper dockerfile `redis-gsc.dockerfile` that
>     |                                        dockerfile `redis-gsc.dockerfile` that includes
> ```

Too many `that`? Please improve this sentence.
___
*[`Curated-Apps/workloads/redis/README.md` line 39 at r37](https://reviewable.io/reviews/gramineproject/contrib/7#-NCv7hkh8fnw5J4xuxI7:-NCv7hkh8fnw5J4xuxI8:b-so3813) ([raw f [...]

2022-09-26 20:38 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/7)* status: 41 of 50 files reviewed, 42 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @dimakuv, and @mkow)

___
*[`Curated-Apps/workloads/pytorch/README.md` line 3 at r37](https://reviewable.io/reviews/gramineproject/contrib/7#-NCv5K599BJqpja6s99z:-NCvUlGW8-NU3N0Dmn1G:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/aa9b9d8e73cc40ccd59478b25a5d6f90f6971aa7/Curated-Apps/workloads/pytorch/README.md#L3)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`be build` -> `be built`
</blockquote></details>

Done.
___
*[`Curated-Apps/workloads/pytorch/README.md` line 27 at r37](https://reviewable.io/reviews/gramineproject/contrib/7#-NCv5cOD4P6cLfAsZAl3:-NCvUnad4mmK5aOT1rPY:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/aa9b9d8e73cc40ccd59478b25a5d6f90f6971aa7/Curated-Apps/workloads/pytorch/README.md#L27)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

These subbullets do not render as you expected: https://github.com/aneessahib/contrib/tree/aneessahib/gsc_image_curation/Curated-Apps/workloads/pytorch

You need to have 4 spaces of indentation, not 1.
</blockquote></details>

Done.
___
*[`Curated-Apps/workloads/pytorch/README.md` line 38 at r37](https://reviewable.io/reviews/gramineproject/contrib/7#-NCv6AyD8BEmOzjVvzKB:-NCvUqkw93q8eXnxj-Qz:bb8t8s1) ([raw file](https://github.com/gramineproject/contrib/blob/aa9b9d8e73cc40ccd59478b25a5d6f90f6971aa7/Curated-Apps/workloads/pytorch/README.md#L38)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The current bullet list doesn't make sense. The first sentence repeats what was already said in the previous section. Please replace this whole section's text with this:
```
This example was tested on a Standard_DC8s_v3 Azure VM.

Follow the output of the `curate.py` script to run the generated Docker image(s).
```
</blockquote></details>

Is that what you expect?
___
*[`Curated-Apps/workloads/pytorch/README.md` line 41 at r37](https://reviewable.io/reviews/gramineproject/contrib/7#-NCv6bcW7j0ts-ztoxbW:-NCvV627A9cfGeuI1RFL:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/aa9b9d8e73cc40ccd59478b25a5d6f90f6971aa7/Curated-Apps/workloads/pytorch/README.md#L41)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`helps` -> `help`
</blockquote></details>

Done.
___
*[`Curated-Apps/workloads/pytorch/README.md` line 41 at r37](https://reviewable.io/reviews/gramineproject/contrib/7#-NCv6dWA7et2_N2nqgGl:-NCvV7dx7Lze1TZlYHKJ:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/aa9b9d8e73cc40ccd59478b25a5d6f90f6971aa7/Curated-Apps/workloads/pytorch/README.md#L41)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`Redis` -> `PyTorch`
</blockquote></details>

Done.
___
*[`Curated-Apps/workloads/pytorch/README.md` line 49 at r37](https://reviewable.io/reviews/gramineproject/contrib/7#-NCv7lBWD4AKSV4HfRKY:-NCvV8II08YU7fhbnYPT:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/aa9b9d8e73cc40ccd59478b25a5d6f90f6971aa7/Curated-Apps/workloads/pytorch/README.md#L49)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`command-line arguments`
</blockquote></details>

Done.
___
*[`Curated-Apps/workloads/pytorch/README.md` line 50 at r37](https://reviewable.io/reviews/gramineproject/contrib/7#-NCv6hVa-sTXUxsyz-PQ:-NCvV9VQCYx-UIi5YYu-:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/aa9b9d8e73cc40ccd59478b25a5d6f90f6971aa7/Curated-Apps/workloads/pytorch/README.md#L50)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`redis.manifest.template` -> `pytorch.manifest.template`
</blockquote></details>

Done.
___
*[`Curated-Apps/workloads/redis/README.md` line 3 at r37](https://reviewable.io/reviews/gramineproject/contrib/7#-NCv7HW8BZ9fPtlqewzB:-NCvVGR7E4NV5YlMFlpZ:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/aa9b9d8e73cc40ccd59478b25a5d6f90f6971aa7/Curated-Apps/workloads/redis/README.md#L3)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`build` -> `built`
</blockquote></details>

Done.
___
*[`Curated-Apps/workloads/redis/README.md` line 16 at r37](https://reviewable.io/reviews/gramineproject/contrib/7#-NCv7MsE6jFC9O1Cib66:-NCvVPou87K0WnRDdwIW:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/aa9b9d8e73cc40ccd59478b25a5d6f90f6971aa7/Curated-Apps/workloads/redis/README.md#L16)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`redis` -> `Redis`
</blockquote></details>

Done.
___
*[`Curated-Apps/workloads/redis/README.md` line 28 at r37](https://reviewable.io/reviews/gramineproject/contrib/7#-NCv7XDyE35TPLVQrDw8:-NCvVRCWAq6S5stv-erz:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/aa9b9d8e73cc40ccd59478b25a5d6f90f6971aa7/Curated-Apps/workloads/redis/README.md#L28)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The current bullet list doesn't make sense. The first sentence repeats what was already said in the previous section. Please replace this whole section's text with this:
```
This example was tested on a Standard_DC8s_v3 Azure VM.

Follow the output of the `curate.py` script to run the generated Docker image(s).
```
</blockquote></details>

Done.
___
*[`Curated-Apps/workloads/redis/README.md` line 37 at r37](https://reviewable.io/reviews/gramineproject/contrib/7#-NCv7bcB6CTjgDQhRZ6g:-NCvVUOn0mij05pwbqOE:bi98s75) ([raw file](https://github.com/gramineproject/contrib/blob/aa9b9d8e73cc40ccd59478b25a5d6f90f6971aa7/Curated-Apps/workloads/redis/README.md#L37)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Too many `that`? Please improve this sentence.
</blockquote></details>

Ah sorry. Some copy paste error
___
*[`Curated-Apps/workloads/redis/README.md` line 39 at r37](https://reviewable.io/reviews/gramineproject/contrib/7#-NCv7hkh8fnw5J4xuxI7:-NCvVicu3pY5FGwy1uxb:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/aa9b9d8e73cc40ccd59478b25a5d6f90f6971aa7/Curated-Apps/workloads/redis/README.md#L39)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`command-line arguments`
</blockquote></details>

Done.
___
*[`Curated-Apps/curate.py` line 484 at r37](https://reviewable.io/reviews/gramineproject/contrib/7#-NCv43QWBJJiURBtv9CO:-NCvTIK96TW46mdzH-uk:b-tdoi5f) ([raw file](https://github.com/gramineproject/contrib/blob/aa9b9d8e73cc40ccd59478b25a5d6f90f6971aa7/Curated-Apps/curate.py#L484)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What is this `{custom_cmd_info}`? When I did a quick test, the output looked like this:
```
Execute below command to deploy the curated GSC image.:
$ docker run ...
```

Can we simply remove this `{custom_cmd_info}` from here?
</blockquote></details>

Renamed `custom_cmd_info` to `custom_image_dns_info` to make it a little more clear. This gets filled up only in the case when the user has opted to generate his own remote verifier, informing the user that he needs provide the verifier address at run-time.  In the test option, this variable evaluates to nothing as we are filling the remote verifier server ourselves with `localhost:4433` .
___
*[`Curated-Apps/README.md` line 16 at r37](https://reviewable.io/reviews/gramineproject/contrib/7#-NCv54yH2sHKfJVOiUTl:-NCvUKSv7IJ [...]

2022-09-26 21:31 UTC, mkow requested changes
> Reviewed 1 of 28 files at r23, 1 of 3 files at r39, 3 of 6 files at r40, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/7)* status: 45 of 50 files reviewed, 25 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @dimakuv, and @mkow)

___
*[`Curated-Apps/curate.py` line 10 at r30](https://reviewable.io/reviews/gramineproject/contrib/7#-NCltIgU0wPsc5eR9cHt:-NCvar2O6jT1lFhAtsgA:b-o9jl2q) ([raw file](https://github.com/gramineproject/contrib/blob/d6d5794ed332ba8a9081855d37b90f05d1ef6aa9/Curated-Apps/curate.py#L10)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I think the additional point is that "normal users" will never use `test` and `debug` options. These options are purely for "developers".
</blockquote></details>

IMO "test" sounds like something very useful for normal users. If I'd use this for the first time I'd probably select "test" to test how this tool works ;)
___
*[`Curated-Apps/curate.py` line 16 at r30](https://reviewable.io/reviews/gramineproject/contrib/7#-NCltuXIBwi1IeaCEzEJ:-NCvbRxR8KBvKrVCOcSJ:b-50xiri) ([raw file](https://github.com/gramineproject/contrib/blob/d6d5794ed332ba8a9081855d37b90f05d1ef6aa9/Curated-Apps/curate.py#L16)):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

Are you talking about `test` option? What we do is `sgx.file_check_policy = allow_all_but_log` . Two benefits of doing this - short manifest (since its only test), and Gramine inherently throws a non-prod warning at run-time. 
</blockquote></details>

No, this comment was placed at the line describing "debug".
___
*[`Curated-Apps/curate.py` line 80 at r30](https://reviewable.io/reviews/gramineproject/contrib/7#-NClv1nBCcBLX7Trc7d-:-NCvca0C2nNRVxbxOBjS:b-o3udox) ([raw file](https://github.com/gramineproject/contrib/blob/d6d5794ed332ba8a9081855d37b90f05d1ef6aa9/Curated-Apps/curate.py#L80)):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

Yes I agree in principle. We will have to check if there are other ways to synchronize using the python curses framework but this will take time. 
</blockquote></details>

???
Anyways, unblocking. But this whole script is really terrible...


<!-- Sent from Reviewable.io -->

2022-09-26 21:38 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/7)* status: 45 of 50 files reviewed, 25 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @dimakuv, and @mkow)

___
*[`Curated-Apps/curate.py` line 16 at r30](https://reviewable.io/reviews/gramineproject/contrib/7#-NCltuXIBwi1IeaCEzEJ:-NCviOPI14q1odWZX2aH:b-itad7b) ([raw file](https://github.com/gramineproject/contrib/blob/d6d5794ed332ba8a9081855d37b90f05d1ef6aa9/Curated-Apps/curate.py#L16)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

No, this comment was placed at the line describing "debug".
</blockquote></details>

Ah, all that "debug" does, is "gsc build" with debug flags. 
https://gramine.readthedocs.io/projects/gsc/en/latest/#cmdoption-gsc-build-d 


<!-- Sent from Reviewable.io -->

2022-09-26 21:49 UTC, mkow requested changes
> Reviewed 2 of 9 files at r31, 1 of 11 files at r35, 11 of 18 files at r36, 1 of 2 files at r37, 1 of 3 files at r39, 3 of 6 files at r40, 1 of 1 files at r41.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/7)* status: all files reviewed, 24 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @dimakuv)

___
*[`Curated-Apps/curate.py` line 16 at r30](https://reviewable.io/reviews/gramineproject/contrib/7#-NCltuXIBwi1IeaCEzEJ:-NCvlJzo-FHcfNxyeqGR:b-dgc1km) ([raw file](https://github.com/gramineproject/contrib/blob/d6d5794ed332ba8a9081855d37b90f05d1ef6aa9/Curated-Apps/curate.py#L16)):*
> Not insecure.

> Compile Gramine with debug flags and debug output.

Gramine debug output _is_ insecure (leaks secrets).


<!-- Sent from Reviewable.io -->

2022-09-26 21:58 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/7)* status: all files reviewed, 24 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @dimakuv, and @mkow)

___
*[`Curated-Apps/curate.py` line 16 at r30](https://reviewable.io/reviews/gramineproject/contrib/7#-NCltuXIBwi1IeaCEzEJ:-NCvmzZO9dm-3VK0agDw:b-1lmxoj) ([raw file](https://github.com/gramineproject/contrib/blob/d6d5794ed332ba8a9081855d37b90f05d1ef6aa9/Curated-Apps/curate.py#L16)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> Not insecure.

> Compile Gramine with debug flags and debug output.

Gramine debug output _is_ insecure (leaks secrets).
</blockquote></details>

Ah, now I see what your saying. Yes - we have called this out in the `debug` argument description. 


<!-- Sent from Reviewable.io -->

2022-09-26 22:17 UTC, mkow submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/7)* status: all files reviewed, 23 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @dimakuv)



<!-- Sent from Reviewable.io -->

2022-09-27 06:39 UTC, dimakuv requested changes
> Reviewed 2 of 3 files at r39, 5 of 6 files at r40, 1 of 1 files at r41, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/7)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @aneessahib)

___
*[`Curated-Apps/curate.py` line 484 at r37](https://reviewable.io/reviews/gramineproject/contrib/7#-NCv43QWBJJiURBtv9CO:-NCxdrR_EQbXFPRDSqxE:bw1xpfd) ([raw file](https://github.com/gramineproject/contrib/blob/aa9b9d8e73cc40ccd59478b25a5d6f90f6971aa7/Curated-Apps/curate.py#L484)):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

Renamed `custom_cmd_info` to `custom_image_dns_info` to make it a little more clear. This gets filled up only in the case when the user has opted to generate his own remote verifier, informing the user that he needs provide the verifier address at run-time.  In the test option, this variable evaluates to nothing as we are filling the remote verifier server ourselves with `localhost:4433` .
</blockquote></details>

I was talking about weird formatting of `.:` when `{custom_image_dns_info}` is empty. Whatever, we'll fix it later.
___
*[`Curated-Apps/README.md` line 57 at r37](https://reviewable.io/reviews/gramineproject/contrib/7#-NCv4qMDDHbxIQJhsIGD:-NCxe3-RBw7ly-ZotmfT:b-bxt42m) ([raw file](https://github.com/gramineproject/contrib/blob/aa9b9d8e73cc40ccd59478b25a5d6f90f6971aa7/Curated-Apps/README.md#L57)):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done. You still have `worloads` (typo, you miss the letter `k`)


<!-- Sent from Reviewable.io -->

2022-09-27 06:40 UTC, dimakuv reviewed
> Reviewed 1 of 6 files at r40.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/7)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @aneessahib)



<!-- Sent from Reviewable.io -->

2022-09-27 07:46 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/7)* status: 38 of 50 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @dimakuv, and @mkow)

___
*[`Curated-Apps/README.md` line 57 at r37](https://reviewable.io/reviews/gramineproject/contrib/7#-NCv4qMDDHbxIQJhsIGD:-NCxuNSW19-ra5-UBDLz:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/aa9b9d8e73cc40ccd59478b25a5d6f90f6971aa7/Curated-Apps/README.md#L57)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Not done. You still have `worloads` (typo, you miss the letter `k`)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-27 08:10 UTC, dimakuv approved these changes
> Reviewed 12 of 12 files at r42, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/7)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @aneessahib)



<!-- Sent from Reviewable.io -->

2022-09-27 09:38 UTC, dimakuv approved these changes
> Reviewed 7 of 7 files at r43, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/7)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @aneessahib)



<!-- Sent from Reviewable.io -->

2022-09-27 09:59 UTC, dimakuv approved these changes
> Reviewed 1 of 28 files at r23, 2 of 2 files at r44, 1 of 1 files at r45, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/7)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @aneessahib and @mkow)

___
*[`-- commits` line 2 at r30](https://reviewable.io/reviews/gramineproject/contrib/7#-NClruBW0XxRR_Q2Gvzy):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

We don't state the reason for the change in the one-liner, it's supposed to be super concise and clearly say _what is the change_ made by this commit.
</blockquote></details>

Done
___
*[`-- commits` line 118 at r30](https://reviewable.io/reviews/gramineproject/contrib/7#-NClsHIHDNFuOz_JWO7X):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

By the way, I can do this during final rebase.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-09-27 10:15 UTC, mkow approved these changes
> Reviewed 7 of 12 files at r42, 4 of 7 files at r43, 2 of 2 files at r44, 1 of 1 files at r45, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/7)* status: all files reviewed, 1 unresolved discussion (waiting on @aneessahib)



<!-- Sent from Reviewable.io -->

2022-09-27 11:09 UTC, dimakuv approved these changes
> Dismissed @aneessahib from a discussion.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/7)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-09-27 11:29 UTC, merged