[Integrations/azure] Re-enable proxy support in libcurl
gramineproject/contrib pull request #74
Opened 2024-01-16 17:24 UTC by dimakuv

For minimization purposes, libcurl is built with most features disabled. One of the disabled features was proxy support. This made libcurl-based dependencies, such as RA-TLS libs, unusable in proxy-restricted environments (e.g. with a company-wide proxy). This commit re-enables proxy support, which increases the size of `libcurl.a` by ~7%.

This commit is the same as commit "[curl] Re-enable proxy support in libcurl" in the core Gramine repo. See https://github.com/gramineproject/gramine/pull/1720

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/contrib/74)

2024-01-16 17:24 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/74)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/74#-NoIIQDBDFTt_OafknDV:-NoIIQDCBX0jmrzfB3Ud:bhm00ne) (no related file):*
Requires https://github.com/gramineproject/contrib/pull/72 (it is based on top of it). Blocking for now.

___


<!-- Sent from Reviewable.io -->

2024-01-17 02:08 UTC, kailun-qin approved these changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/74)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2024-01-17 14:42 UTC, woju requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/74)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`Integrations/azure/ra_tls_maa/subprojects/packagefiles/curl-8.4.0/compile.sh` line 56 at r1](https://reviewable.io/reviews/gramineproject/contrib/74#-NoMrTG6-jbsFusI4TPy:-NoMrTG6-jbsFusI4TPz:b-j6gp17) ([raw file](https://github.com/gramineproject/contrib/blob/07ffe02db4503f187eddcd4334c2ce04c98f7900/Integrations/azure/ra_tls_maa/subprojects/packagefiles/curl-8.4.0/compile.sh#L56)):*
> ```Shell
>         --disable-pop3                              \
>         --disable-progress-meter                    \
>         --disable-proxy                             \
> ```

Instead of just removing the option and commenting, if you want to make it explicit, you should probably write `--enable-proxy` and don't comment above. Everyone know, what proxy is, and why it's needed.



_Suggestion:_
```Shell
--enable-proxy
```


<!-- Sent from Reviewable.io -->

2024-01-17 15:01 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/74)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/74#-NoIIQDBDFTt_OafknDV:-NoMw9B28KmeW9fJOs1T:bhudpvr) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Requires https://github.com/gramineproject/contrib/pull/72 (it is based on top of it). Blocking for now.
</blockquote></details>

Merged now.

___
___
*[`Integrations/azure/ra_tls_maa/subprojects/packagefiles/curl-8.4.0/compile.sh` line 56 at r1](https://reviewable.io/reviews/gramineproject/contrib/74#-NoMrTG6-jbsFusI4TPy:-NoMwBBnBWCgb5ZqF9eA:b-l4ult) ([raw file](https://github.com/gramineproject/contrib/blob/07ffe02db4503f187eddcd4334c2ce04c98f7900/Integrations/azure/ra_tls_maa/subprojects/packagefiles/curl-8.4.0/compile.sh#L56)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Instead of just removing the option and commenting, if you want to make it explicit, you should probably write `--enable-proxy` and don't comment above. Everyone know, what proxy is, and why it's needed.
</blockquote></details>

Done, good idea.


<!-- Sent from Reviewable.io -->

2024-01-17 15:04 UTC, kailun-qin approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/74)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @woju)



<!-- Sent from Reviewable.io -->

2024-01-17 16:34 UTC, woju approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/74)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2024-01-18 07:42 UTC, merged