[Integrations/intel] Add RA-TLS/SecretProv libs for ITA
gramineproject/contrib pull request #75
Opened 2024-01-17 14:58 UTC by dimakuv

This commit adds the sources, documentation and tests for `libra_tls_verify_ita.so` and `libsecret_prov_verify_ita.so` libraries, used for integration of Gramine with Intel Trust Authority (ITA, formerly Project Amber).

The sources and the build system are largely based on the Microsoft Azure Attestation (MAA) RA-TLS libs found in the same repository. However, ITA turned out to have substantial differences from MAA, thus we decided to have separate sources for MAA and ITA (in contrast to e.g. creating ITA as a series of patches to MAA).

See for context:
- https://github.com/gramineproject/contrib/issues/73
- https://github.com/gramineproject/contrib/pull/59

Fixes #73.

2024-01-17 15:28 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/75)* status: 0 of 8 files reviewed, 16 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/75#-NoMwbjpBRzn7-53bGek:-NoMwbjq0WUduq2VXppZ:b-id9hef) (no related file):*
Requires https://github.com/gramineproject/contrib/pull/74 to be merged first.

___
___
*[`-- commits` line 15 at r1](https://reviewable.io/reviews/gramineproject/contrib/75#-NoMwffG6F9e7sDb-1kG):*
@bigdata-memory Can you ACK that you co-authored this PR? I took your original PR and modified it significantly. Just write "ACK" if you acknowledge.
___
*[`-- commits` line 16 at r1](https://reviewable.io/reviews/gramineproject/contrib/75#-NoMwmgc7BDNoVjPN5ma):*
@ScottR-Intel Can you ACK that you co-authored this PR? I took your original minimal patch as a base. Just write "ACK" if you acknowledge.
___
*[`Integrations/intel/ra_tls_ita/meson.build` line 8 at r1](https://reviewable.io/reviews/gramineproject/contrib/75#-NoMx84RADmoCd1UVcfr:-NoMx84RADmoCd1UVcfs:bn3w5j) ([raw file](https://github.com/gramineproject/contrib/blob/3888fc936898762b2d385c1d725420554c1a0222/Integrations/intel/ra_tls_ita/meson.build#L8)):*
> ```Meson
>     'ra-tls-ita',
>     'c', 'cpp',
>     version: '0.1',
> ```

Should we change the version to something more meaningful, like v1.6? I don't know; I would prefer to have this "alpha version" `0.1`.
___
*[`Integrations/intel/ra_tls_ita/README.md` line 1 at r1](https://reviewable.io/reviews/gramineproject/contrib/75#-NoMxVh_8igWkRt0KaEn:-NoMxVh_8igWkRt0KaEo:b-3z6u3w) ([raw file](https://github.com/gramineproject/contrib/blob/3888fc936898762b2d385c1d725420554c1a0222/Integrations/intel/ra_tls_ita/README.md#L1)):*
> ```Markdown
> ## Intel Trust Authority (ITA)
> ```

FYI: It is easier to read this in a rendered form: https://github.com/gramineproject/contrib/tree/dimakuv/add-intel-trust-authority/Integrations/intel/ra_tls_ita
___
*[`Integrations/intel/ra_tls_ita/README.md` line 61 at r1](https://reviewable.io/reviews/gramineproject/contrib/75#-NoMxZz8AbuxSL5Krnxn:-NoMxZz8AbuxSL5Krnxo:bsiz95a) ([raw file](https://github.com/gramineproject/contrib/blob/3888fc936898762b2d385c1d725420554c1a0222/Integrations/intel/ra_tls_ita/README.md#L61)):*
> ```Markdown
> - Attester claims
>   - `attester_type` (expected to be "SGX")
>   - TODO
> ```

Forgot to update the claims list. Check not only Attester Claims, but others too.
___
*[`Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c` line 25 at r1](https://reviewable.io/reviews/gramineproject/contrib/75#-NoMxk2W2R7BpP3eg9TE:-NoMxk2W2R7BpP3eg9TF:b-nanqxt) ([raw file](https://github.com/gramineproject/contrib/blob/3888fc936898762b2d385c1d725420554c1a0222/Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c#L25)):*
> ```C
>  *   `https://api.trustauthority.intel.com`.
>  * - {portalUrl} is the ITA portal URL (that releases certificates), e.g.
>  *   `https://portal.trustauthority.intel.com`.
> ```

TODO(myself): Ask the ITA team why there are two separate URLs for JWTs and for JWKs (certificates).
___
*[`Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c` line 535 at r1](https://reviewable.io/reviews/gramineproject/contrib/75#-NoMyaXh0cvrc08KrXia:-NoMyaXh0cvrc08KrXib:bsoscqj) ([raw file](https://github.com/gramineproject/contrib/blob/3888fc936898762b2d385c1d725420554c1a0222/Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c#L535)):*
> ```C
>     size_t request_json_size = quote_b64_size + runtime_data_b64_size;
> 
>     char* ita_policy_ids = getenv(RA_TLS_ITA_POLICY_IDS);
> ```

TODO(myself): Ask the ITA team what fields should actually be sent in the POST attestation request?

We add `quote` (required), `runtime_data` (optional) and `policy_ids` (optional), and we DO NOT add `verifier_nonce`, `event_log` and `inittime_data`.
___
*[`Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c` line 542 at r1](https://reviewable.io/reviews/gramineproject/contrib/75#-NoMzj8tEYCj4i7CQiuW:-NoMzj8tEYCj4i7CQiuX:bmx60q3) ([raw file](https://github.com/gramineproject/contrib/blob/3888fc936898762b2d385c1d725420554c1a0222/Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c#L542)):*
> ```C
>         request_json_size += strlen(ita_policy_ids) + strlen(request_json_fmt) + 1;
>     } else if (ita_policy_ids) {
>         /* RA_TLS_ITA_POLICY_IDS envvar specifies a single policy ID (must add double-quotes) */
> ```

TODO(myself): Ask the ITA team what is the expected flow for `policy_ids`? Does it make sense to allow more than one? Does it make sense to NOT have any?
___
*[`Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c` line 981 at r1](https://reviewable.io/reviews/gramineproject/contrib/75#-NoN-OG14R9Q2chxwCsS:-NoN-OG14R9Q2chxwCsT:b-4l66v) ([raw file](https://github.com/gramineproject/contrib/blob/3888fc936898762b2d385c1d725420554c1a0222/Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c#L981)):*
> ```C
>      * SGX-specific verification of the token-signing certificate. We rely on the fact that
>      * obtaining the token-signing certificate happens via a protected HTTPS connection to a
>      * well-known ITA portal, so the certificate is considered trusted.
> ```

TODO(myself): Ask the ITA team about these issues.

1. Will there be an SGX-based ITA service? How do we verify it?
2. For the non-SGX ITA service, hwere do we get the complete chain of ITA `certs/`certificates (I only get one cert from my developer ITA service), and how do we get the Root CA certificate as the root of trust?
___
*[`Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c` line 1023 at r1](https://reviewable.io/reviews/gramineproject/contrib/75#-NoN0Enq07Z6vJzCLUIE:-NoN0Enq07Z6vJzCLUIF:b5t9s05) ([raw file](https://github.com/gramineproject/contrib/blob/3888fc936898762b2d385c1d725420554c1a0222/Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c#L1023)):*
> ```C
>     int not_before_time_with_slack = not_before_time->valueint > 60
>                                          ? not_before_time->valueint - 60
>                                          : not_before_time->valueint;
> ```

TODO(myself): Ask the ITA team about why there is a slack in the ITA service. In my experiments, the service is ~5 seconds earlier than my local machine (i.e., `not_before_time` is failing if I don't add the 60-second slack).
___
*[`Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c` line 1033 at r1](https://reviewable.io/reviews/gramineproject/contrib/75#-NoN0RrD09gBG65HVzzp:-NoN0RrD09gBG65HVzzq:b-gp234m) ([raw file](https://github.com/gramineproject/contrib/blob/3888fc936898762b2d385c1d725420554c1a0222/Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c#L1033)):*
> ```C
> 
>     /* b. verify Verifier claims: policy_ids_matched, policy_ids_unmatched; we don't care about
>      *    verifier_nonce, verifier_instance_ids */
> ```

TODO(myself): Ask the ITA team what's the point of `verifier_nonce`? What additional security guarantees does it provide, must we add it to our ITA integration?
___
*[`Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c` line 1038 at r1](https://reviewable.io/reviews/gramineproject/contrib/75#-NoN0_HxDyXuO85315Lo:-NoN0_HxDyXuO85315Lp:bnvuee) ([raw file](https://github.com/gramineproject/contrib/blob/3888fc936898762b2d385c1d725420554c1a0222/Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c#L1038)):*
> ```C
> 
>     /* FIXME: What should we actually do with policies? Do we fail verification if at least one
>      *        policy is unmatched? */
> ```

TODO(myself): Ask the ITA team how to react to matched/unmatched policies.
___
*[`Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c` line 1074 at r1](https://reviewable.io/reviews/gramineproject/contrib/75#-NoN0fFUBZRbIg87KHbS:-NoN0fFV08dHRnDy9Ljo:bq2ib5g) ([raw file](https://github.com/gramineproject/contrib/blob/3888fc936898762b2d385c1d725420554 [...]

2024-01-18 08:16 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/75)* status: 0 of 8 files reviewed, 14 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/75#-NoMwbjpBRzn7-53bGek:-NoQcq-fA3T5wei2nfg2:bb6un1j) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Requires https://github.com/gramineproject/contrib/pull/74 to be merged first.
</blockquote></details>

Done

___
___
*[`Integrations/intel/ra_tls_ita/README.md` line 61 at r1](https://reviewable.io/reviews/gramineproject/contrib/75#-NoMxZz8AbuxSL5Krnxn:-NoQb52a3uXHr7x0TLpX:bb6un1j) ([raw file](https://github.com/gramineproject/contrib/blob/3888fc936898762b2d385c1d725420554c1a0222/Integrations/intel/ra_tls_ita/README.md#L61)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Forgot to update the claims list. Check not only Attester Claims, but others too.
</blockquote></details>

Done
___
*[`Integrations/intel/ra_tls_ita/README.md` line 69 at r1](https://reviewable.io/reviews/gramineproject/contrib/75#-NoQbDCu-ptjBWALyPpo:-NoQbDCu-ptjBWALyPpp:b-lnqrnb) ([raw file](https://github.com/gramineproject/contrib/blob/3888fc936898762b2d385c1d725420554c1a0222/Integrations/intel/ra_tls_ita/README.md#L69)):*
> ```Markdown
>   - `sgx_isvsvn` (verified against `RA_TLS_ISV_SVN`)
>   - `sgx_report_data` (verified to contain the hash of the RA-TLS public key)
> - (note that EAT and Verifier claims are currently not verified)
> ```

TODO(myself): Ask the ITA team to fix the EAT table: https://docs.trustauthority.intel.com/main/articles/concept-attestation-tokens.html#eat-claims
___
*[`Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c` line 1256 at r1](https://reviewable.io/reviews/gramineproject/contrib/75#-NoN13hNEIYVRLHhFC_u:-NoQbaJI4HL0Q3Sl7W7r:bb6un1j) ([raw file](https://github.com/gramineproject/contrib/blob/3888fc936898762b2d385c1d725420554c1a0222/Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c#L1256)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Oops, must fix.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-01-18 12:54 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/75)* status: 0 of 8 files reviewed, 16 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c` line 542 at r1](https://reviewable.io/reviews/gramineproject/contrib/75#-NoMzj8tEYCj4i7CQiuW:-NoRDQZO13zhUEWaD8vL:b66yp23) ([raw file](https://github.com/gramineproject/contrib/blob/3888fc936898762b2d385c1d725420554c1a0222/Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c#L542)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

TODO(myself): Ask the ITA team what is the expected flow for `policy_ids`? Does it make sense to allow more than one? Does it make sense to NOT have any?
</blockquote></details>

Some refs with explanations:
- https://docs.trustauthority.intel.com/main/articles/howto-manage-attestation-policies.html
- https://docs.trustauthority.intel.com/main/articles/howto-author-custom-policy.html

TLDR: It seems the typical flow for Gramine would be to fail if at least one unmatched policy is detected. Ask the ITA team if they think this is reasonable. (We can augment Gramine later to provide an envvar knob for this behavior.)

UPDATE: Here's a great summary of policies and what to do with them: https://docs.trustauthority.intel.com/main/articles/integrate-relying-party.html#background-check-policy-ids
___
*[`Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c` line 981 at r1](https://reviewable.io/reviews/gramineproject/contrib/75#-NoN-OG14R9Q2chxwCsS:-NoRYXwCBvA580FmPkDK:bhb0oy4) ([raw file](https://github.com/gramineproject/contrib/blob/3888fc936898762b2d385c1d725420554c1a0222/Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c#L981)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

TODO(myself): Ask the ITA team about these issues.

1. Will there be an SGX-based ITA service? How do we verify it?
2. For the non-SGX ITA service, hwere do we get the complete chain of ITA `certs/`certificates (I only get one cert from my developer ITA service), and how do we get the Root CA certificate as the root of trust?
</blockquote></details>

Some explanations on option 1 are given here: https://docs.trustauthority.intel.com/main/articles/utility-faithful-verifier.html. Unfortunately, this Faithful Verifier tool is a stand-alone tool. Also, the ITA service "correct token generation evidence" is in the form of a blockchain ledger, so nothing simple as I was expecting (an SGX quote with some known MRSIGNER or MRENCLAVE).

Additional info on Faithful Verifier tool and what guarantees it provides to the Relying Party: https://docs.trustauthority.intel.com/main/articles/integrate-relying-party.html#faithful-verification-verifier
___
*[`Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c` line 1033 at r1](https://reviewable.io/reviews/gramineproject/contrib/75#-NoN0RrD09gBG65HVzzp:-NoRElGoCb0mVGDz_29W:b-x0t9b2) ([raw file](https://github.com/gramineproject/contrib/blob/3888fc936898762b2d385c1d725420554c1a0222/Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c#L1033)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

TODO(myself): Ask the ITA team what's the point of `verifier_nonce`? What additional security guarantees does it provide, must we add it to our ITA integration?
</blockquote></details>

After reading the ITA documentation, I'm still not sure what's the purpose of `verifier_nonce`.

Some refs:
- https://docs.trustauthority.intel.com/main/articles/concept-patterns.html?tabs=passport
___
*[`Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c` line 1038 at r1](https://reviewable.io/reviews/gramineproject/contrib/75#-NoN0_HxDyXuO85315Lo:-NoREowoELmak6HfmLAN:b-kt3z11) ([raw file](https://github.com/gramineproject/contrib/blob/3888fc936898762b2d385c1d725420554c1a0222/Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c#L1038)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

TODO(myself): Ask the ITA team how to react to matched/unmatched policies.
</blockquote></details>

See my other comment. Duplicating:

Some refs with explanations:
- https://docs.trustauthority.intel.com/main/articles/howto-manage-attestation-policies.html
- https://docs.trustauthority.intel.com/main/articles/howto-author-custom-policy.html

TLDR: It seems the typical flow for Gramine would be to fail if at least one unmatched policy is detected. Ask the ITA team if they think this is reasonable. (We can augment Gramine later to provide an envvar knob for this behavior.)
___
*[`Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c` line 1138 at r1](https://reviewable.io/reviews/gramineproject/contrib/75#-NoN0tcVCUeh95JgcD_s:-NoRE3a4CjxNB91wKwUo:b-4fc2cx) ([raw file](https://github.com/gramineproject/contrib/blob/3888fc936898762b2d385c1d725420554c1a0222/Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c#L1138)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We're just printing advisory IDs (known HW/SW vulnerabilities). Can we do more? I don't think so.
</blockquote></details>

Some refs with explanations:
- https://docs.trustauthority.intel.com/main/articles/concept-platform-tcb.html#alloweddisallowed-security-advisories-policy

TLDR: It seems the typical flow is to create a separate appraisal policy that checks against allowed and disallowed Advisory IDs. So just printing Advisory IDs is fine; they are supposed to be reflected in Matched/Unmatched Policy IDs anyway.
___
*[`Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c` line 987 at r2](https://reviewable.io/reviews/gramineproject/contrib/75#-NoR_PiaDCa5o1rlWBgY:-NoR_PiaDCa5o1rlWBgZ:bt8r0rs) ([raw file](https://github.com/gramineproject/contrib/blob/4fabe1866502bd322745c2fbeca6174796bd373f/Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c#L987)):*
> ```C
>      * We verified the header & signature of the received JWT, can trust its payload. See claims at
>      * https://docs.trustauthority.intel.com/main/articles/concept-attestation-tokens.html#token-body
>      */
> ```

The official guidance from ITA is here: https://docs.trustauthority.intel.com/main/articles/integrate-relying-party.html#attestation-token-verification.

Our implementation adheres to these guidelines, except this one: **Check the lists of matched and unmatched policies**. After I get an authoritative reply on what should RA-TLS policy be on these policies, I'll consider my implementation to follow all guidelines.
___
*[`Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c` line 1038 at r2](https://reviewable.io/reviews/gramineproject/contrib/75#-NoR_x7gCiuRx1J3-V11:-NoR_x7h63D8zShS7_9Q:bsszeyw) ([raw file](https://github.com/gramineproject/contrib/blob/4fabe1866502bd322745c2fbeca6174796bd373f/Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c#L1038)):*
There are also **signed policies**: https://docs.trustauthority.intel.com/main/articles/integrate-relying-party.html#signed-policy-verification

From this docs:
> In many instances it will be acceptable for the RP to trust the policy IDs alone. If elevated trust is required, the RP should verify the matched policy IDs by requesting a copy of the signed policy stored in the Intel Trust Authority database. An RP can verify that both the policy ID and hash have the expected values.
> As of this writing, the only way to get a signed policy is by using the [GET **RetrievePolicy**](https://docs.trustauthority.intel.com/main/restapi/restapi-policy-management.html) REST API ...

We could potentially implement this "signed policy" verification. But for now I'd just add a FIXME comment. This seems to be a not-yet-finalized flow in ITA.


<!-- Sent from Reviewable.io -->

2024-01-24 16:32 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/75)* status: 0 of 8 files reviewed, 16 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`-- commits` line 15 at r1](https://reviewable.io/reviews/gramineproject/contrib/75#-NoMwffG6F9e7sDb-1kG):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@bigdata-memory Can you ACK that you co-authored this PR? I took your original PR and modified it significantly. Just write "ACK" if you acknowledge.
</blockquote></details>

@bigdata-memory Ping
___
*[`-- commits` line 16 at r1](https://reviewable.io/reviews/gramineproject/contrib/75#-NoMwmgc7BDNoVjPN5ma):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@ScottR-Intel Can you ACK that you co-authored this PR? I took your original minimal patch as a base. Just write "ACK" if you acknowledge.
</blockquote></details>

@ScottR-Intel Ping


<!-- Sent from Reviewable.io -->

2024-01-30 15:57 UTC, ScottR-Intel commented
Ack

2024-01-30 15:58 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/75)* status: 0 of 8 files reviewed, 15 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`-- commits` line 16 at r1](https://reviewable.io/reviews/gramineproject/contrib/75#-NoMwmgc7BDNoVjPN5ma):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@ScottR-Intel Ping
</blockquote></details>

Done (in a top-level comment)


<!-- Sent from Reviewable.io -->

2024-01-30 17:12 UTC, bigdata-memory commented
> > _[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/75)_ status: 0 of 8 files reviewed, 16 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)
> 
> _[a discussion](https://reviewable.io/reviews/gramineproject/contrib/75#-NoMwbjpBRzn7-53bGek:-NoMwbjq0WUduq2VXppZ:b-id9hef) (no related file):_ Requires #74 to be merged first.
> 
> _[`-- commits` line 15 at r1](https://reviewable.io/reviews/gramineproject/contrib/75#-NoMwffG6F9e7sDb-1kG):_ @bigdata-memory Can you ACK that you co-authored this PR? I took your original PR and modified it significantly. Just write "ACK" if you acknowledge.
> 
> _[`-- commits` line 16 at r1](https://reviewable.io/reviews/gramineproject/contrib/75#-NoMwmgc7BDNoVjPN5ma):_ @ScottR-Intel Can you ACK that you co-authored this PR? I took your original minimal patch as a base. Just write "ACK" if you acknowledge.
> 
> _[`Integrations/intel/ra_tls_ita/meson.build` line 8 at r1](https://reviewable.io/reviews/gramineproject/contrib/75#-NoMx84RADmoCd1UVcfr:-NoMx84RADmoCd1UVcfs:bn3w5j) ([raw file](https://github.com/gramineproject/contrib/blob/3888fc936898762b2d385c1d725420554c1a0222/Integrations/intel/ra_tls_ita/meson.build#L8)):_
> 
> > ```meson
> >     'ra-tls-ita',
> >     'c', 'cpp',
> >     version: '0.1',
> > ```
> 
> Should we change the version to something more meaningful, like v1.6? I don't know; I would prefer to have this "alpha version" `0.1`.
> 
> _[`Integrations/intel/ra_tls_ita/README.md` line 1 at r1](https://reviewable.io/reviews/gramineproject/contrib/75#-NoMxVh_8igWkRt0KaEn:-NoMxVh_8igWkRt0KaEo:b-3z6u3w) ([raw file](https://github.com/gramineproject/contrib/blob/3888fc936898762b2d385c1d725420554c1a0222/Integrations/intel/ra_tls_ita/README.md#L1)):_
> 
> > ```
> > ## Intel Trust Authority (ITA)
> > ```
> 
> FYI: It is easier to read this in a rendered form: https://github.com/gramineproject/contrib/tree/dimakuv/add-intel-trust-authority/Integrations/intel/ra_tls_ita
> 
> _[`Integrations/intel/ra_tls_ita/README.md` line 61 at r1](https://reviewable.io/reviews/gramineproject/contrib/75#-NoMxZz8AbuxSL5Krnxn:-NoMxZz8AbuxSL5Krnxo:bsiz95a) ([raw file](https://github.com/gramineproject/contrib/blob/3888fc936898762b2d385c1d725420554c1a0222/Integrations/intel/ra_tls_ita/README.md#L61)):_
> 
> > ```
> > - Attester claims
> >   - `attester_type` (expected to be "SGX")
> >   - TODO
> > ```
> 
> Forgot to update the claims list. Check not only Attester Claims, but others too.
> 
> _[`Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c` line 25 at r1](https://reviewable.io/reviews/gramineproject/contrib/75#-NoMxk2W2R7BpP3eg9TE:-NoMxk2W2R7BpP3eg9TF:b-nanqxt) ([raw file](https://github.com/gramineproject/contrib/blob/3888fc936898762b2d385c1d725420554c1a0222/Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c#L25)):_
> 
> > ```c
> >  *   `https://api.trustauthority.intel.com`.
> >  * - {portalUrl} is the ITA portal URL (that releases certificates), e.g.
> >  *   `https://portal.trustauthority.intel.com`.
> > ```
> 
> TODO(myself): Ask the ITA team why there are two separate URLs for JWTs and for JWKs (certificates).
> 
> _[`Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c` line 535 at r1](https://reviewable.io/reviews/gramineproject/contrib/75#-NoMyaXh0cvrc08KrXia:-NoMyaXh0cvrc08KrXib:bsoscqj) ([raw file](https://github.com/gramineproject/contrib/blob/3888fc936898762b2d385c1d725420554c1a0222/Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c#L535)):_
> 
> > ```c
> >     size_t request_json_size = quote_b64_size + runtime_data_b64_size;
> > 
> >     char* ita_policy_ids = getenv(RA_TLS_ITA_POLICY_IDS);
> > ```
> 
> TODO(myself): Ask the ITA team what fields should actually be sent in the POST attestation request?
> 
> We add `quote` (required), `runtime_data` (optional) and `policy_ids` (optional), and we DO NOT add `verifier_nonce`, `event_log` and `inittime_data`.
> 
> _[`Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c` line 542 at r1](https://reviewable.io/reviews/gramineproject/contrib/75#-NoMzj8tEYCj4i7CQiuW:-NoMzj8tEYCj4i7CQiuX:bmx60q3) ([raw file](https://github.com/gramineproject/contrib/blob/3888fc936898762b2d385c1d725420554c1a0222/Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c#L542)):_
> 
> > ```c
> >         request_json_size += strlen(ita_policy_ids) + strlen(request_json_fmt) + 1;
> >     } else if (ita_policy_ids) {
> >         /* RA_TLS_ITA_POLICY_IDS envvar specifies a single policy ID (must add double-quotes) */
> > ```
> 
> TODO(myself): Ask the ITA team what is the expected flow for `policy_ids`? Does it make sense to allow more than one? Does it make sense to NOT have any?
> 
> _[`Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c` line 981 at r1](https://reviewable.io/reviews/gramineproject/contrib/75#-NoN-OG14R9Q2chxwCsS:-NoN-OG14R9Q2chxwCsT:b-4l66v) ([raw file](https://github.com/gramineproject/contrib/blob/3888fc936898762b2d385c1d725420554c1a0222/Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c#L981)):_
> 
> > ```c
> >      * SGX-specific verification of the token-signing certificate. We rely on the fact that
> >      * obtaining the token-signing certificate happens via a protected HTTPS connection to a
> >      * well-known ITA portal, so the certificate is considered trusted.
> > ```
> 
> TODO(myself): Ask the ITA team about these issues.
> 
> 1. Will there be an SGX-based ITA service? How do we verify it?
> 2. For the non-SGX ITA service, hwere do we get the complete chain of ITA `certs/`certificates (I only get one cert from my developer ITA service), and how do we get the Root CA certificate as the root of trust?
> 
> _[`Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c` line 1023 at r1](https://reviewable.io/reviews/gramineproject/contrib/75#-NoN0Enq07Z6vJzCLUIE:-NoN0Enq07Z6vJzCLUIF:b5t9s05) ([raw file](https://github.com/gramineproject/contrib/blob/3888fc936898762b2d385c1d725420554c1a0222/Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c#L1023)):_
> 
> > ```c
> >     int not_before_time_with_slack = not_before_time->valueint > 60
> >                                          ? not_before_time->valueint - 60
> >                                          : not_before_time->valueint;
> > ```
> 
> TODO(myself): Ask the ITA team about why there is a slack in the ITA service. In my experiments, the service is ~5 seconds earlier than my local machine (i.e., `not_before_time` is failing if I don't add the 60-second slack).
> 
> _[`Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c` line 1033 at r1](https://reviewable.io/reviews/gramineproject/contrib/75#-NoN0RrD09gBG65HVzzp:-NoN0RrD09gBG65HVzzq:b-gp234m) ([raw file](https://github.com/gramineproject/contrib/blob/3888fc936898762b2d385c1d725420554c1a0222/Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c#L1033)):_
> 
> > ```c
> >     /* b. verify Verifier claims: policy_ids_matched, policy_ids_unmatched; we don't care about
> >      *    verifier_nonce, verifier_instance_ids */
> > ```
> 
> TODO(myself): Ask the ITA team what's the point of `verifier_nonce`? What additional security guarantees does it provide, must we add it to our ITA integration?
> 
> _[`Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c` line 1038 at r1](https://reviewable.io/reviews/gramineproject/contrib/75#-NoN0_HxDyXuO85315Lo:-NoN0_HxDyXuO85315Lp:bnvuee) ([raw file](https://github.com/gramineproject/contrib/blob/3888fc936898762b2d385c1d725420554c1a0222/Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c#L1038)):_
> 
> > ```c
> >     /* FIXME: What should we actually do with policies? Do we fail verification if at least one
> >      *        policy is unmatched? */
> > ```
> 
> TODO(myself): Ask the ITA team how to react to matched/unmatched policies.
> 
> _[`Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c` line 1074 at r1](https://reviewable.io/reviews/gramineproject/contrib/75#-NoN0fFUBZRbIg87KHbS:-NoN [...]

2024-01-30 19:06 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/75)* status: 0 of 8 files reviewed, 14 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`-- commits` line 15 at r1](https://reviewable.io/reviews/gramineproject/contrib/75#-NoMwffG6F9e7sDb-1kG):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@bigdata-memory Ping
</blockquote></details>

Done (in a top-level comment)


<!-- Sent from Reviewable.io -->

2024-02-06 14:17 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/75)* status: 0 of 8 files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

___
*[`Integrations/intel/ra_tls_ita/meson.build` line 8 at r1](https://reviewable.io/reviews/gramineproject/contrib/75#-NoMx84RADmoCd1UVcfr:-NpyiXz9DZwrs7VBTwFq:b-56kfem) ([raw file](https://github.com/gramineproject/contrib/blob/3888fc936898762b2d385c1d725420554c1a0222/Integrations/intel/ra_tls_ita/meson.build#L8)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Should we change the version to something more meaningful, like v1.6? I don't know; I would prefer to have this "alpha version" `0.1`.
</blockquote></details>

Done. I'm keeping as `0.1`.
___
*[`Integrations/intel/ra_tls_ita/README.md` line 69 at r1](https://reviewable.io/reviews/gramineproject/contrib/75#-NoQbDCu-ptjBWALyPpo:-Npyf3ag6MF5Nicc2BkZ:b-mmkbn7) ([raw file](https://github.com/gramineproject/contrib/blob/3888fc936898762b2d385c1d725420554c1a0222/Integrations/intel/ra_tls_ita/README.md#L69)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

TODO(myself): Ask the ITA team to fix the EAT table: https://docs.trustauthority.intel.com/main/articles/concept-attestation-tokens.html#eat-claims
</blockquote></details>

Done, the table was fixed.
___
*[`Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c` line 25 at r1](https://reviewable.io/reviews/gramineproject/contrib/75#-NoMxk2W2R7BpP3eg9TE:-NpyfEELEnaaesIQ_p16:b-xmfw3r) ([raw file](https://github.com/gramineproject/contrib/blob/3888fc936898762b2d385c1d725420554c1a0222/Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c#L25)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

TODO(myself): Ask the ITA team why there are two separate URLs for JWTs and for JWKs (certificates).
</blockquote></details>

Done. The answer is:
- the `api.` endpoint is for REST API
- the `portal.` endpoint hosts static info, no REST API
___
*[`Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c` line 535 at r1](https://reviewable.io/reviews/gramineproject/contrib/75#-NoMyaXh0cvrc08KrXia:-NpyfVeB48Xky3x4abU6:bvgh964) ([raw file](https://github.com/gramineproject/contrib/blob/3888fc936898762b2d385c1d725420554c1a0222/Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c#L535)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

TODO(myself): Ask the ITA team what fields should actually be sent in the POST attestation request?

We add `quote` (required), `runtime_data` (optional) and `policy_ids` (optional), and we DO NOT add `verifier_nonce`, `event_log` and `inittime_data`.
</blockquote></details>

Done, the last two are not important, and the `verifier_nonce` we don't use because in the RA-TLS model (which uses the "background check" attestation) the nonce (the proof of freshness of the SGX quote) is already included in the RA-TLS handshake: the SGX quote contains the User Report Data which is the hash of the public key generated inside this SGX enclave, so it is fresh and bound to this particular SGX enclave.
___
*[`Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c` line 542 at r1](https://reviewable.io/reviews/gramineproject/contrib/75#-NoMzj8tEYCj4i7CQiuW:-Npyfq47CEII2hgKefzT:b-341rg8) ([raw file](https://github.com/gramineproject/contrib/blob/3888fc936898762b2d385c1d725420554c1a0222/Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c#L542)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Some refs with explanations:
- https://docs.trustauthority.intel.com/main/articles/howto-manage-attestation-policies.html
- https://docs.trustauthority.intel.com/main/articles/howto-author-custom-policy.html

TLDR: It seems the typical flow for Gramine would be to fail if at least one unmatched policy is detected. Ask the ITA team if they think this is reasonable. (We can augment Gramine later to provide an envvar knob for this behavior.)

UPDATE: Here's a great summary of policies and what to do with them: https://docs.trustauthority.intel.com/main/articles/integrate-relying-party.html#background-check-policy-ids
</blockquote></details>

Done.

It is good to implement both flows: without `policy_ids` (then default policies bound to the API key are used) and with `policy_ids` (then only these policies are checked).

Also, the common case is to FAIL if at least one unmatched policy is detected. This is implemented now in my code. (This we may change in the future, when a need arises.)
___
*[`Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c` line 981 at r1](https://reviewable.io/reviews/gramineproject/contrib/75#-NoN-OG14R9Q2chxwCsS:-NpygQzz-vC1UZiumSlR:b-jivh7b) ([raw file](https://github.com/gramineproject/contrib/blob/3888fc936898762b2d385c1d725420554c1a0222/Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c#L981)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Some explanations on option 1 are given here: https://docs.trustauthority.intel.com/main/articles/utility-faithful-verifier.html. Unfortunately, this Faithful Verifier tool is a stand-alone tool. Also, the ITA service "correct token generation evidence" is in the form of a blockchain ledger, so nothing simple as I was expecting (an SGX quote with some known MRSIGNER or MRENCLAVE).

Additional info on Faithful Verifier tool and what guarantees it provides to the Relying Party: https://docs.trustauthority.intel.com/main/articles/integrate-relying-party.html#faithful-verification-verifier
</blockquote></details>

Done. Currently we skip both checks (for an SGX-based ITA service, and traversing the whole chain of ITA certificates). We rely on the token-signing certificate, as explained in the comment.
___
*[`Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c` line 1023 at r1](https://reviewable.io/reviews/gramineproject/contrib/75#-NoN0Enq07Z6vJzCLUIE:-Npygi-5BpITQ6-avsS-:bwh5hdd) ([raw file](https://github.com/gramineproject/contrib/blob/3888fc936898762b2d385c1d725420554c1a0222/Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c#L1023)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

TODO(myself): Ask the ITA team about why there is a slack in the ITA service. In my experiments, the service is ~5 seconds earlier than my local machine (i.e., `not_before_time` is failing if I don't add the 60-second slack).
</blockquote></details>

Done. No clear answer here, so let's keep the 60-second slack.
___
*[`Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c` line 1033 at r1](https://reviewable.io/reviews/gramineproject/contrib/75#-NoN0RrD09gBG65HVzzp:-NpygnrhCzH2XRskxFHd:b-z7a4nm) ([raw file](https://github.com/gramineproject/contrib/blob/3888fc936898762b2d385c1d725420554c1a0222/Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c#L1033)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

After reading the ITA documentation, I'm still not sure what's the purpose of `verifier_nonce`.

Some refs:
- https://docs.trustauthority.intel.com/main/articles/concept-patterns.html?tabs=passport
</blockquote></details>

Done. `verifier_nonce` is useful to prevent replay attacks. More specifically, the relying party wants to make sure that it never receives an already-seen SGX quote from some SGX enclave.

In the [passport model](https://docs.trustauthority.intel.com/main/articles/concept-patterns.html?tabs=passport) (not currently used in RA-TLS), the relying party receives the Attestation Token that was generated by the ITA service. Without the `verifier_nonce` (and the corresponding preliminary step shown on the linked di [...]

2024-02-06 14:18 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/75)* status: 0 of 8 files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/75#-Npym0pa-W2QEBs8SO9E:-Npym0pa-W2QEBs8SO9F:b4id5gn) (no related file):*
Btw, the OpenID configuration URL for ITA is this: https://portal.trustauthority.intel.com/.well-known/openid-configuration

___


<!-- Sent from Reviewable.io -->

2024-02-14 09:05 UTC, woju requested changes
> Reviewed 3 of 8 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/75)* status: 4 of 8 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/75#-Nqanv3p8lN1YMDi4ejg:-Nqanv3p8lN1YMDi4ejh:b-upka4h) (no related file):*
Needs modifications to `debian/` to also build `Package: gramine-ratls-ita`.

___
___
*[`Integrations/intel/ra_tls_ita/.gitignore` line 6 at r3](https://reviewable.io/reviews/gramineproject/contrib/75#-Nqar0IU1mRzU_HdHZdl:-Nqar0IU1mRzU_HdHZdm:b-8jhzpo) ([raw file](https://github.com/gramineproject/contrib/blob/77251266fa5ff2fb967fd21150799d9f8398c4bd/Integrations/intel/ra_tls_ita/.gitignore#L6)):*
> ```ignore
> 
> # the `subprojects` dir is copied from the MAA RA-TLS plugin as-is
> /subprojects
> ```

No. Plz see thread in README.
___
*[`Integrations/intel/ra_tls_ita/README.md` line 114 at r3](https://reviewable.io/reviews/gramineproject/contrib/75#-NqYPsWxCuHzOPVXAsfq:-NqYPsWxCuHzOPVXAsfr:bra27a8) ([raw file](https://github.com/gramineproject/contrib/blob/77251266fa5ff2fb967fd21150799d9f8398c4bd/Integrations/intel/ra_tls_ita/README.md#L114)):*
> ```Markdown
> 
> The library sets the same environment variables as `ra_tls_verify_ita.so`,
> namely `RA_TLS_ITA_JWT` and `RA_TLS_ita_SET_OF_JWKS`.
> ```

Is this lower case `ita` or upper case like above?



_Code quote:_
```Markdown
ita
```
___
*[`Integrations/intel/ra_tls_ita/README.md` line 123 at r3](https://reviewable.io/reviews/gramineproject/contrib/75#-Nqanfa72HQ2ywcj8SqV:-Nqanfa72HQ2ywcj8SqW:b3f1cmv) ([raw file](https://github.com/gramineproject/contrib/blob/77251266fa5ff2fb967fd21150799d9f8398c4bd/Integrations/intel/ra_tls_ita/README.md#L123)):*
> ```Markdown
> have many commonalities in the build process:
> ```sh
> cp -r ../../azure/ra_tls_maa/subprojects ./
> ```

No, please don't. If you must, you can probably symlink them. Or if not, I'd say you can merge those into one meson project.


<!-- Sent from Reviewable.io -->

2024-02-14 09:16 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/75)* status: 4 of 8 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/75#-NqatM0MB2nz2GGqWwWA:-NqatM0N8647OJ4_hh8D:bakubum) (no related file):*
FYI I've wrote a draft PR that enables this in Scaffolding: gramineproject/gramine-scaffolding#9.

___


<!-- Sent from Reviewable.io -->

2024-02-16 09:58 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/75)* status: 2 of 9 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/75#-Nqanv3p8lN1YMDi4ejg:-NqlJbS77UrPoElSeG9g:bq9hiq) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Needs modifications to `debian/` to also build `Package: gramine-ratls-ita`.
</blockquote></details>

@woju Am I supposed to do this in this PR, or you'll do it in a follow-up PR?

___
___
*[`Integrations/intel/ra_tls_ita/.gitignore` line 6 at r3](https://reviewable.io/reviews/gramineproject/contrib/75#-Nqar0IU1mRzU_HdHZdl:-NqlKZ5_CiXSo-QIxmpg:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/77251266fa5ff2fb967fd21150799d9f8398c4bd/Integrations/intel/ra_tls_ita/.gitignore#L6)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

No. Plz see thread in README.
</blockquote></details>

Done.
___
*[`Integrations/intel/ra_tls_ita/README.md` line 114 at r3](https://reviewable.io/reviews/gramineproject/contrib/75#-NqYPsWxCuHzOPVXAsfq:-NqlKxWO09BICE1PRyjP:b-ibso4u) ([raw file](https://github.com/gramineproject/contrib/blob/77251266fa5ff2fb967fd21150799d9f8398c4bd/Integrations/intel/ra_tls_ita/README.md#L114)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Is this lower case `ita` or upper case like above?
</blockquote></details>

Done, copy-paste fail. It must be all-capitals of course.
___
*[`Integrations/intel/ra_tls_ita/README.md` line 123 at r3](https://reviewable.io/reviews/gramineproject/contrib/75#-Nqanfa72HQ2ywcj8SqV:-NqlKa2A5su5R8ErX5FA:bs4zcqp) ([raw file](https://github.com/gramineproject/contrib/blob/77251266fa5ff2fb967fd21150799d9f8398c4bd/Integrations/intel/ra_tls_ita/README.md#L123)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

No, please don't. If you must, you can probably symlink them. Or if not, I'd say you can merge those into one meson project.
</blockquote></details>

Done. Using a symlink.


<!-- Sent from Reviewable.io -->

2024-02-16 10:22 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/75)* status: 2 of 9 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/75#-NqlQw4B19eZpkBEdCs8:-NqlQw4B19eZpkBEdCs9:b-flgpgf) (no related file):*
FYI: Tested again (on 16. Feb 2024), everything works.

___


<!-- Sent from Reviewable.io -->

2024-02-19 16:33 UTC, woju reviewed
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/75)* status: 5 of 9 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/75#-Nqanv3p8lN1YMDi4ejg:-Nr1CQv0BN3MgD-KL_BL:blo3uwb) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@woju Am I supposed to do this in this PR, or you'll do it in a follow-up PR?
</blockquote></details>

IDK, how do you prefer? I can do that, when I finish fixing gramineproject/gramine-scaffolding#3

___


<!-- Sent from Reviewable.io -->

2024-02-20 07:38 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/75)* status: 5 of 9 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/75#-Nqanv3p8lN1YMDi4ejg:-Nr4RlHh3nzX7GOG9GkF:bibs4c6) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

IDK, how do you prefer? I can do that, when I finish fixing gramineproject/gramine-scaffolding#3
</blockquote></details>

Ideally you do it, because I'm terrible at packaging.

___


<!-- Sent from Reviewable.io -->

2024-02-22 09:04 UTC, woju submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/75)* status: 5 of 9 files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/75#-Nqanv3p8lN1YMDi4ejg:-NrF2aFN7NBQHxYSZXzO:bheinxg) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ideally you do it, because I'm terrible at packaging.
</blockquote></details>

#79 — I'm resolving here

___


<!-- Sent from Reviewable.io -->

2024-03-11 01:55 UTC, mkow requested changes
> Reviewed 1 of 8 files at r1, 2 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/75)* status: 5 of 9 files reviewed, 7 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`Integrations/intel/ra_tls_ita/README.md` line 77 at r4](https://reviewable.io/reviews/gramineproject/contrib/75#-Nsf9FdECesjU9SiQwje:-Nsf9FdECesjU9SiQwjf:b-x7zm9j) ([raw file](https://github.com/gramineproject/contrib/blob/db00bc51ed06bb56ed3da4b6e3299a1990072265/Integrations/intel/ra_tls_ita/README.md#L77)):*
> ```Markdown
>   - `sgx_isvsvn` (verified against `RA_TLS_ISV_SVN`)
>   - `sgx_report_data` (verified to contain the hash of the RA-TLS public key)
> - (note that EAT claims are currently not verified)
> ```

What are EAT claims? I couldn't find it in the ITA docs and it's not present in the glossary there.
___
*[`Integrations/intel/ra_tls_ita/README.md` line 98 at r4](https://reviewable.io/reviews/gramineproject/contrib/75#-NsfAQgwEZ9uoqBhTPjd:-NsfAQgwEZ9uoqBhTPje:b-7bl00y) ([raw file](https://github.com/gramineproject/contrib/blob/db00bc51ed06bb56ed3da4b6e3299a1990072265/Integrations/intel/ra_tls_ita/README.md#L98)):*
>  If not specified, no attestation policies [...] are evaluation.

Something wrong here? Maybe "are evaluated"?
___
*[`Integrations/intel/ra_tls_ita/README.md` line 100 at r4](https://reviewable.io/reviews/gramineproject/contrib/75#-NsfAs0t4IasFVn--Izp:-NsfAs0t4IasFVn--Izq:blcrqq8) ([raw file](https://github.com/gramineproject/contrib/blob/db00bc51ed06bb56ed3da4b6e3299a1990072265/Integrations/intel/ra_tls_ita/README.md#L100)):*
> ```Markdown
>   default policy that verifies the SGX platform) are evaluation. Can be
>   specified as a single policy or as a comma-separated set of policies. In the
>   latter case, each policy must be surrounded by double quotes.
> ```

Could you give some examples of both syntaxes? Sounds a bit suspicious that the syntax changes depending on the number of items, what are the exact parsing rules?
___
*[`Integrations/intel/ra_tls_ita/README.md` line 121 at r4](https://reviewable.io/reviews/gramineproject/contrib/75#-NsfC-Ox0QZeB4DzllAX:-NsfC-OyBDkSvB5xRv18:undefined) ([raw file](https://github.com/gramineproject/contrib/blob/db00bc51ed06bb56ed3da4b6e3299a1990072265/Integrations/intel/ra_tls_ita/README.md#L121)):*
> ```Markdown
> 
> To build the `ra_tls_verify_ita.so` and `secret_prov_verify_ita.so` libraries,
> we use the meson build system:
> ```





_Suggestion:_
```Markdown
we use the Meson build system:
```
___
*[`Integrations/intel/ra_tls_ita/README.md` line 144 at r4](https://reviewable.io/reviews/gramineproject/contrib/75#-NsfCNW2BXEUuyZkihtG:-NsfCNW2BXEUuyZkihtH:undefined) ([raw file](https://github.com/gramineproject/contrib/blob/db00bc51ed06bb56ed3da4b6e3299a1990072265/Integrations/intel/ra_tls_ita/README.md#L144)):*
> ```Markdown
> examples available in Gramine.
> 
> To be able to run these tests, the machine must run on the SGX enabled host, with
> ```





_Suggestion:_
```Markdown
on a host with SGX support
```
___
*[`Integrations/intel/ra_tls_ita/README.md` line 147 at r4](https://reviewable.io/reviews/gramineproject/contrib/75#-NsfCgF16uJDXHQ-warX:-NsfCgF16uJDXHQ-warY:b-dcyca4) ([raw file](https://github.com/gramineproject/contrib/blob/db00bc51ed06bb56ed3da4b6e3299a1990072265/Integrations/intel/ra_tls_ita/README.md#L147)):*
> on top of Gramine v1.6 repo

TODO: Update to 1.6.2 after its release.


<!-- Sent from Reviewable.io -->

2024-03-11 08:52 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/75)* status: 4 of 9 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @woju)

___
*[`Integrations/intel/ra_tls_ita/README.md` line 77 at r4](https://reviewable.io/reviews/gramineproject/contrib/75#-Nsf9FdECesjU9SiQwje:-NsgeUVCEcEcHYqtrfFt:btxo1hw) ([raw file](https://github.com/gramineproject/contrib/blob/db00bc51ed06bb56ed3da4b6e3299a1990072265/Integrations/intel/ra_tls_ita/README.md#L77)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What are EAT claims? I couldn't find it in the ITA docs and it's not present in the glossary there.
</blockquote></details>

https://docs.trustauthority.intel.com/main/articles/concept-attestation-tokens.html#eat-claims

Do you want me to add a hyperlink to this page in the README?
___
*[`Integrations/intel/ra_tls_ita/README.md` line 98 at r4](https://reviewable.io/reviews/gramineproject/contrib/75#-NsfAQgwEZ9uoqBhTPjd:-Nsgf2tqAbKF92iyeK7F:b7v7wkk) ([raw file](https://github.com/gramineproject/contrib/blob/db00bc51ed06bb56ed3da4b6e3299a1990072265/Integrations/intel/ra_tls_ita/README.md#L98)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

>  If not specified, no attestation policies [...] are evaluation.

Something wrong here? Maybe "are evaluated"?
</blockquote></details>

Done. Yeah, typo
___
*[`Integrations/intel/ra_tls_ita/README.md` line 100 at r4](https://reviewable.io/reviews/gramineproject/contrib/75#-NsfAs0t4IasFVn--Izp:-Nsgfxk2B8m6QXyBLRfx:bm7lv6r) ([raw file](https://github.com/gramineproject/contrib/blob/db00bc51ed06bb56ed3da4b6e3299a1990072265/Integrations/intel/ra_tls_ita/README.md#L100)):*
Done, gave examples.

> Sounds a bit suspicious that the syntax changes depending on the number of items, what are the exact parsing rules?

https://github.com/gramineproject/contrib/blob/dimakuv/add-intel-trust-authority/Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c#L535-L549

See also https://docs.trustauthority.intel.com/main/restapi/restapi-attestation.html, `policy_ids` field. (It is in JSON format, and the feild is an [Array of Strings](https://stackoverflow.com/questions/5293555/how-do-you-represent-a-json-array-of-strings).)

I agree that this is contrived. How would you better modify it, given the following considerations:
- The final string is JSON
- User will specify **no policy** or **one policy** 95% of the time
- We want to add the flexibility of adding more policies (should be a rare case) in this PR, but I can also remove this feature from this PR and only re-add it when need arises (if at all)
- We want to make life of the user simple, so in the common one-policy case, we allow to omit the double quotes

Please tell me which course of action you prefer.
___
*[`Integrations/intel/ra_tls_ita/README.md` line 121 at r4](https://reviewable.io/reviews/gramineproject/contrib/75#-NsfC-Ox0QZeB4DzllAX:-Nsgh8AaACH8zrc4qaON:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/db00bc51ed06bb56ed3da4b6e3299a1990072265/Integrations/intel/ra_tls_ita/README.md#L121)):*
> ```Markdown
> 
> To build the `ra_tls_verify_ita.so` and `secret_prov_verify_ita.so` libraries,
> we use the meson build system:
> ```

Done.
___
*[`Integrations/intel/ra_tls_ita/README.md` line 144 at r4](https://reviewable.io/reviews/gramineproject/contrib/75#-NsfCNW2BXEUuyZkihtG:-NsghFJT70MfEef6prs-:b-8xznpp) ([raw file](https://github.com/gramineproject/contrib/blob/db00bc51ed06bb56ed3da4b6e3299a1990072265/Integrations/intel/ra_tls_ita/README.md#L144)):*
> ```Markdown
> examples available in Gramine.
> 
> To be able to run these tests, the machine must run on the SGX enabled host, with
> ```

Done. You and your dislike of the word `enabled` :)
___
*[`Integrations/intel/ra_tls_ita/README.md` line 147 at r4](https://reviewable.io/reviews/gramineproject/contrib/75#-NsfCgF16uJDXHQ-warX:-NsghJ-f1--jc4Zu3DPe:bebrt1w) ([raw file](https://github.com/gramineproject/contrib/blob/db00bc51ed06bb56ed3da4b6e3299a1990072265/Integrations/intel/ra_tls_ita/README.md#L147)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> on top of Gramine v1.6 repo

TODO: Update to 1.6.2 after its release.
</blockquote></details>

Will do


<!-- Sent from Reviewable.io -->

2024-03-14 18:13 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/75)* status: 3 of 9 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

___
*[`Integrations/intel/ra_tls_ita/README.md` line 147 at r4](https://reviewable.io/reviews/gramineproject/contrib/75#-NsfCgF16uJDXHQ-warX:-Nsy9pJn6yCv5MIyVtyc:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/db00bc51ed06bb56ed3da4b6e3299a1990072265/Integrations/intel/ra_tls_ita/README.md#L147)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Will do
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-19 02:09 UTC, mkow requested changes
> Reviewed 3 of 8 files at r1, 1 of 3 files at r4, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/75)* status: 8 of 9 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`Integrations/intel/ra_tls_ita/README.md` line 77 at r4](https://reviewable.io/reviews/gramineproject/contrib/75#-Nsf9FdECesjU9SiQwje:-NtJNaHf34lvEsH6gjTz:b-nx2ncf) ([raw file](https://github.com/gramineproject/contrib/blob/db00bc51ed06bb56ed3da4b6e3299a1990072265/Integrations/intel/ra_tls_ita/README.md#L77)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

https://docs.trustauthority.intel.com/main/articles/concept-attestation-tokens.html#eat-claims

Do you want me to add a hyperlink to this page in the README?
</blockquote></details>

Yes please, it seems hard to find otherwise in ITA docs.
___
*[`Integrations/intel/ra_tls_ita/README.md` line 100 at r4](https://reviewable.io/reviews/gramineproject/contrib/75#-NsfAs0t4IasFVn--Izp:-NtJP3Xj-7BJcqcreBiN:be41j6) ([raw file](https://github.com/gramineproject/contrib/blob/db00bc51ed06bb56ed3da4b6e3299a1990072265/Integrations/intel/ra_tls_ita/README.md#L100)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done, gave examples.

> Sounds a bit suspicious that the syntax changes depending on the number of items, what are the exact parsing rules?

https://github.com/gramineproject/contrib/blob/dimakuv/add-intel-trust-authority/Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c#L535-L549

See also https://docs.trustauthority.intel.com/main/restapi/restapi-attestation.html, `policy_ids` field. (It is in JSON format, and the feild is an [Array of Strings](https://stackoverflow.com/questions/5293555/how-do-you-represent-a-json-array-of-strings).)

I agree that this is contrived. How would you better modify it, given the following considerations:
- The final string is JSON
- User will specify **no policy** or **one policy** 95% of the time
- We want to add the flexibility of adding more policies (should be a rare case) in this PR, but I can also remove this feature from this PR and only re-add it when need arises (if at all)
- We want to make life of the user simple, so in the common one-policy case, we allow to omit the double quotes

Please tell me which course of action you prefer.
</blockquote></details>

But why multi-entry policy requires doublequotes, but a single entry doesn't? I assume the only reason for using quotes is to allow specifying policy names which contain `,`?
___
*[`Integrations/intel/ra_tls_ita/README.md` line 144 at r4](https://reviewable.io/reviews/gramineproject/contrib/75#-NsfCNW2BXEUuyZkihtG:-NtJPZh67EXZcHsgHB0K:b-qri5eb) ([raw file](https://github.com/gramineproject/contrib/blob/db00bc51ed06bb56ed3da4b6e3299a1990072265/Integrations/intel/ra_tls_ita/README.md#L144)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. You and your dislike of the word `enabled` :)
</blockquote></details>

I like it, just only when it's used as "enabled" vs "disabled" ;) I really don't like how people at Intel replace every possible verb with "enable" because it sounds fancy :P
___
*[`Integrations/intel/ra_tls_ita/src/secret_prov_verify_ita.c` line 9 at r6](https://reviewable.io/reviews/gramineproject/contrib/75#-NtJSFfP0eeOFlQIWMAD:-NtJSFfP0eeOFlQIWMAE:b-23f595) ([raw file](https://github.com/gramineproject/contrib/blob/13ea9d996d8819bc2dcec636dd5fdf490b90b25b/Integrations/intel/ra_tls_ita/src/secret_prov_verify_ita.c#L9)):*
> ```C
>  * This file contains the dummy references to secret_prov_verify exported functions (this is to
>  * force symbols from libsecret_prov_verify.a to be exported in our ITA version; note that by
>  * default unused symbols from a linked static library are *not* exported).
> ```

Hmm, but they are in `secret_prov.map` marked as global?
Anyways, isn't this a problem with ra-tls? Why is it worked around here?


<!-- Sent from Reviewable.io -->

2024-03-19 15:58 UTC, mkow requested changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/75)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c` line 24 at r6](https://reviewable.io/reviews/gramineproject/contrib/75#-NtJTiC32QCvfzVj1nbJ:-NtJTiC32QCvfzVj1nbK:b-1ci9hw) ([raw file](https://github.com/gramineproject/contrib/blob/13ea9d996d8819bc2dcec636dd5fdf490b90b25b/Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c#L24)):*
> that releases certificates

What do you mean by that? Sends them back from API? Publishes somewhere?
___
*[`Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c` line 141 at r6](https://reviewable.io/reviews/gramineproject/contrib/75#-NtMFcvT9pXIpvlF5Mtg:-NtMFcvT9pXIpvlF5Mth:b-dsmyd7) ([raw file](https://github.com/gramineproject/contrib/blob/13ea9d996d8819bc2dcec636dd5fdf490b90b25b/Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c#L141)):*
> ```C
>     replace_char(dst, dlen, '+', '-');
>     replace_char(dst, dlen, '/', '_');
>     replace_char(dst, dlen, '=', '\0');
> ```

This replacement changes the output length, but we don't update `*olen`?
___
*[`Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c` line 145 at r6](https://reviewable.io/reviews/gramineproject/contrib/75#-NtLngV4BtHTbouh08bQ:-NtLngV4BtHTbouh08bR:b-vsweea) ([raw file](https://github.com/gramineproject/contrib/blob/13ea9d996d8819bc2dcec636dd5fdf490b90b25b/Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c#L145)):*
> ```C
> }
> 
> static int mbedtls_base64url_decode(uint8_t* dst, size_t dlen, size_t* olen, const uint8_t* src,
> ```

Why is there "mbedtls" in the name here if it's our own function? It's misleading IMO.
ditto for other places like that
___
*[`Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c` line 214 at r6](https://reviewable.io/reviews/gramineproject/contrib/75#-NtLzNm_2dGdmHATarSg:-NtLzNm_2dGdmHATarSh:undefined) ([raw file](https://github.com/gramineproject/contrib/blob/13ea9d996d8819bc2dcec636dd5fdf490b90b25b/Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c#L214)):*
> ```C
>  *
>  * \param[in] buffer   Single HTTP header.
>  * \param[in] size     Together with \a count a size of \a buffer.
> ```





_Suggestion:_
```C
Together with \a count the size of \a buffer.
```
___
*[`Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c` line 218 at r6](https://reviewable.io/reviews/gramineproject/contrib/75#-NtLzlZ5AYbFGJb-f8mE:-NtLzlZ5AYbFGJb-f8mF:b-yi3y24) ([raw file](https://github.com/gramineproject/contrib/blob/13ea9d996d8819bc2dcec636dd5fdf490b90b25b/Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c#L218)):*
> ```C
>  * \param[in] context  User data pointer (of type struct ita_response).
>  *
>  * \returns \a size * \a count
> ```

Shouldn't this be a part of the implementation, not documentation? Here it should say what is the meaning of the return value, I think.
ditto in other places



_Code quote:_
```C
* \returns \a size * \a count
```
___
*[`Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c` line 322 at r6](https://reviewable.io/reviews/gramineproject/contrib/75#-NtM6Wa13e4JH0CkokIX:-NtM6Wa13e4JH0CkokIY:bcl5mbe) ([raw file](https://github.com/gramineproject/contrib/blob/13ea9d996d8819bc2dcec636dd5fdf490b90b25b/Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c#L322)):*
> ```C
>     }
> 
>     curl_ret = curl_easy_setopt(context->curl, CURLOPT_SSLVERSION, CURL_SSLVERSION_TLSv1_2);
> ```

Why not TLS 1.3? Or even better, `CURL_SSLVERSION_MAX_DEFAULT`?
___
*[`Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c` line 558 at r6](https://reviewable.io/reviews/gramineproject/contrib/75#-NtMGLKQ2Zq1mgUfa5Ke:-NtMGLKQ2Zq1mgUfa5Kf:bco6rx5) ([raw file](https://github.com/gramineproject/contrib/blob/13ea9d996d8819bc2dcec636dd5fdf490b90b25b/Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c#L558)):*
> ```C
> 
>     ret = snprintf(request_json, request_json_size, request_json_fmt, quote_b64, runtime_data_b64,
>                    ita_policy_ids ? ita_policy_ids : /*unused dummy*/"");
> ```

This snprintf lacks proper escaping.
___
*[`Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c` line 1140 at r6](https://reviewable.io/reviews/gramineproject/contrib/75#-NtMO5UtDunzTRr9RHmE:-NtMO5UuBRyajNe_0lMw:undefined) ([raw file](https://github.com/gramineproject/contrib/blob/13ea9d996d8819bc2dcec636dd5fdf490b90b25b/Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c#L1140)):*
> ```C
>     }
> 
>     /* d. Verify Intel SGX claims; we currently don't use sgx_config_id, sgx_collateral */
> ```





_Suggestion:_
```C
sgx_config_id and sgx_collateral
```
___
*[`Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c` line 1225 at r6](https://reviewable.io/reviews/gramineproject/contrib/75#-NtMOje83YD_DXHPOD1O:-NtMOje83YD_DXHPOD1P:b-2aeu2b) ([raw file](https://github.com/gramineproject/contrib/blob/13ea9d996d8819bc2dcec636dd5fdf490b90b25b/Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c#L1225)):*
> ```C
>     ERROR("--- JWT is ```%s``` ---\n", token_b64->valuestring);
>     ERROR("--- set_of_jwks is ```%s``` ---\n", set_of_jwks);
> #endif
> ```

Debugging leftover?


<!-- Sent from Reviewable.io -->

2024-04-11 15:35 UTC, mkow requested changes
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/75)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`Integrations/intel/ra_tls_ita/README.md` line 100 at r4](https://reviewable.io/reviews/gramineproject/contrib/75#-NsfAs0t4IasFVn--Izp:-Nv9hze80AULIDE1zZLK:b-hri8fl) ([raw file](https://github.com/gramineproject/contrib/blob/db00bc51ed06bb56ed3da4b6e3299a1990072265/Integrations/intel/ra_tls_ita/README.md#L100)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> But why multi-entry policy requires doublequotes, but a single entry doesn't? I assume the only reason for using quotes is to allow specifying policy names which contain `,`?

Yes, exactly. The only reason is because in multi-entry case, we must comply with the parsing rules. E.g. this is a legit list of Policy IDs:
```
RA_TLS_ITA_POLICY_IDS="me, myself, and I","spaces in this policy","normal_policy"`
```
</blockquote></details>

Ok, but these doublequotes and commas are two separate things: one is to allow broader charset in policy names and the other is to allow more entries. The current version is weird, because it's either a single entry without quotes, or multiple with quotes. So, how do these parse?
```
RA_TLS_ITA_POLICY_IDS=a,c
RA_TLS_ITA_POLICY_IDS="a"
RA_TLS_ITA_POLICY_IDS="a",c
```

Why not just always require the doublequotes?
___
*[`Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c` line 24 at r6](https://reviewable.io/reviews/gramineproject/contrib/75#-NtJTiC32QCvfzVj1nbJ:-NvCkUj51nHPak0Z76z0:b-rq4cqu) ([raw file](https://github.com/gramineproject/contrib/blob/13ea9d996d8819bc2dcec636dd5fdf490b90b25b/Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c#L24)):*
> If you're confused about my top-level comments in this file

No, only this very sentence I pinned my comment at. So, it seems there are 2 confusing things here: the verb "releases" is just wrong here because it means something else, and these are not certificates but public keys formatted as JWK.
___
*[`Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c` line 558 at r6](https://reviewable.io/reviews/gramineproject/contrib/75#-NtMGLKQ2Zq1mgUfa5Ke:-NvClptS9aqkQXk8dmB1:b-4a7pp) ([raw file](https://github.com/gramineproject/contrib/blob/13ea9d996d8819bc2dcec636dd5fdf490b90b25b/Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c#L558)):*
> So I guess you mean that item 3 is potentially dangerous? But what do you want to do with this? Also, isn't it the responsibility of the receiver side (i.e. the ITA attestation provider web service) to parse and verify this field upon receival of the HTTPS REST request?

Yes, this one. It's not dangerous in terms of security, as the value is probably trusted, but it's just a terrible idea to segfault when the user puts a `%` sign in the policy environment variable.
___
*[`Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c` line 146 at r7](https://reviewable.io/reviews/gramineproject/contrib/75#-NvCl0889dxCJtTgRFb9:-NvCl0889dxCJtTgRFbA:bhmb3ki) ([raw file](https://github.com/gramineproject/contrib/blob/49fd6de7ae5706319cc1e9913b4a80264e02b0ae/Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c#L146)):*
> ```C
>     while (dst[len] != '\0')
>         len++;
>     *olen = len + 1;
> ```

just use strlen()?


<!-- Sent from Reviewable.io -->

2024-04-12 14:25 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/75)* status: 7 of 9 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`Integrations/intel/ra_tls_ita/README.md` line 100 at r4](https://reviewable.io/reviews/gramineproject/contrib/75#-NsfAs0t4IasFVn--Izp:-NvHa3JuBpWysarPqL-g:bn28wkq) ([raw file](https://github.com/gramineproject/contrib/blob/db00bc51ed06bb56ed3da4b6e3299a1990072265/Integrations/intel/ra_tls_ita/README.md#L100)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Ok, but these doublequotes and commas are two separate things: one is to allow broader charset in policy names and the other is to allow more entries. The current version is weird, because it's either a single entry without quotes, or multiple with quotes. So, how do these parse?
```
RA_TLS_ITA_POLICY_IDS=a,c
RA_TLS_ITA_POLICY_IDS="a"
RA_TLS_ITA_POLICY_IDS="a",c
```

Why not just always require the doublequotes?
</blockquote></details>

Done, requiring doublequotes now (and printing an error when didn't find)
___
*[`Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c` line 24 at r6](https://reviewable.io/reviews/gramineproject/contrib/75#-NtJTiC32QCvfzVj1nbJ:-NvHcrnj8rqsgACwCPVJ:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/13ea9d996d8819bc2dcec636dd5fdf490b90b25b/Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c#L24)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> If you're confused about my top-level comments in this file

No, only this very sentence I pinned my comment at. So, it seems there are 2 confusing things here: the verb "releases" is just wrong here because it means something else, and these are not certificates but public keys formatted as JWK.
</blockquote></details>

Done.
___
*[`Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c` line 558 at r6](https://reviewable.io/reviews/gramineproject/contrib/75#-NtMGLKQ2Zq1mgUfa5Ke:-NvHf8cU4D151fRcHRbq:bv18g0f) ([raw file](https://github.com/gramineproject/contrib/blob/13ea9d996d8819bc2dcec636dd5fdf490b90b25b/Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c#L558)):*
> but it's just a terrible idea to segfault when the user puts a `%` sign in the policy environment variable

I don't understand, what will segfault? The `request_json_fmt` (format) string does *not* have user-supplied strings. It's our code that hard-codes this string.

If the user puts `%` in `RA_TLS_ITA_POLICY_IDS` envvar, it will end up in `ita_policy_ids`. But why would we care about one of the `snprintf()` arguments?

---

A simple reproducer to double-check there's no segfault in this code:
```c
#include <stdio.h>
#include <string.h>
#include <stdlib.h>

int main(void) {
    char* quote_b64 = "bla";
    char* runtime_data_b64 = "bla";
    size_t quote_b64_size = strlen(quote_b64) + 1;
    size_t runtime_data_b64_size = strlen(runtime_data_b64) + 1;
    size_t request_json_size = quote_b64_size + runtime_data_b64_size;

    char* ita_policy_ids = "some %s string";

    char* request_json_fmt = "{\"quote\": \"%s\", \"runtime_data\": \"%s\","
        " \"policy_ids\": [%s]}";
    request_json_size += strlen(ita_policy_ids) + strlen(request_json_fmt) + 1;

    char* request_json = malloc(request_json_size);
    int ret = snprintf(request_json, request_json_size, request_json_fmt, quote_b64, runtime_data_b64,
                   ita_policy_ids ? ita_policy_ids : /*unused dummy*/"");
    if (ret < 0 || (size_t)ret >= request_json_size) {
        printf("OH NOOO");
    }

    printf("%s\n", request_json);
    return 0;
}
```

Output:
```
$ cc -Wall -Wextra -O3   -c -o helloworld.o helloworld.c

$ ./helloworld
{"quote": "bla", "runtime_data": "bla", "policy_ids": [some %s string]}
```
___
*[`Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c` line 146 at r7](https://reviewable.io/reviews/gramineproject/contrib/75#-NvCl0889dxCJtTgRFb9:-NvHcuVkB8JRHT67Rhha:b-gjhm4f) ([raw file](https://github.com/gramineproject/contrib/blob/49fd6de7ae5706319cc1e9913b4a80264e02b0ae/Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c#L146)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

just use strlen()?
</blockquote></details>

Using `strlen()` leads to an annoying type casting of `uint8_t <-> char*`. I just really don't want to perform typecasts or write comments about this.

If you insist, I'll change to `strlen()` with a type cast, but I dislike it a lot.


<!-- Sent from Reviewable.io -->

2024-04-13 14:24 UTC, mkow requested changes
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/75)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c` line 558 at r6](https://reviewable.io/reviews/gramineproject/contrib/75#-NtMGLKQ2Zq1mgUfa5Ke:-NvMpRcZClEeeluyHStQ:b-r2ycj5) ([raw file](https://github.com/gramineproject/contrib/blob/13ea9d996d8819bc2dcec636dd5fdf490b90b25b/Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c#L558)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> but it's just a terrible idea to segfault when the user puts a `%` sign in the policy environment variable

I don't understand, what will segfault? The `request_json_fmt` (format) string does *not* have user-supplied strings. It's our code that hard-codes this string.

If the user puts `%` in `RA_TLS_ITA_POLICY_IDS` envvar, it will end up in `ita_policy_ids`. But why would we care about one of the `snprintf()` arguments?

---

A simple reproducer to double-check there's no segfault in this code:
```c
#include <stdio.h>
#include <string.h>
#include <stdlib.h>

int main(void) {
    char* quote_b64 = "bla";
    char* runtime_data_b64 = "bla";
    size_t quote_b64_size = strlen(quote_b64) + 1;
    size_t runtime_data_b64_size = strlen(runtime_data_b64) + 1;
    size_t request_json_size = quote_b64_size + runtime_data_b64_size;

    char* ita_policy_ids = "some %s string";

    char* request_json_fmt = "{\"quote\": \"%s\", \"runtime_data\": \"%s\","
        " \"policy_ids\": [%s]}";
    request_json_size += strlen(ita_policy_ids) + strlen(request_json_fmt) + 1;

    char* request_json = malloc(request_json_size);
    int ret = snprintf(request_json, request_json_size, request_json_fmt, quote_b64, runtime_data_b64,
                   ita_policy_ids ? ita_policy_ids : /*unused dummy*/"");
    if (ret < 0 || (size_t)ret >= request_json_size) {
        printf("OH NOOO");
    }

    printf("%s\n", request_json);
    return 0;
}
```

Output:
```
$ cc -Wall -Wextra -O3   -c -o helloworld.o helloworld.c

$ ./helloworld
{"quote": "bla", "runtime_data": "bla", "policy_ids": [some %s string]}
```
</blockquote></details>

Ah, sorry, I got lost in this discussion, it was only about escaping of the final JSON string, so, it's not that bad.
Could you then at least check that policy ID is a proper JSON string and can't break anything when pasted here? (i.e. no escaping, just error out on bad characters, i.e. just improve the check above)
___
*[`Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c` line 146 at r7](https://reviewable.io/reviews/gramineproject/contrib/75#-NvCl0889dxCJtTgRFb9:-NvMoxMG1uGVGvPc7_-d:bhowzob) ([raw file](https://github.com/gramineproject/contrib/blob/49fd6de7ae5706319cc1e9913b4a80264e02b0ae/Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c#L146)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Using `strlen()` leads to an annoying type casting of `uint8_t <-> char*`. I just really don't want to perform typecasts or write comments about this.

If you insist, I'll change to `strlen()` with a type cast, but I dislike it a lot.
</blockquote></details>

Ah, that was the reason. Ok, let's leave it as is then.


<!-- Sent from Reviewable.io -->

2024-04-15 10:12 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/75)* status: 8 of 9 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c` line 558 at r6](https://reviewable.io/reviews/gramineproject/contrib/75#-NtMGLKQ2Zq1mgUfa5Ke:-NvWENma4_0H994v_DUC:b-cxboz4) ([raw file](https://github.com/gramineproject/contrib/blob/13ea9d996d8819bc2dcec636dd5fdf490b90b25b/Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c#L558)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Ah, sorry, I got lost in this discussion, it was only about escaping of the final JSON string, so, it's not that bad.
Could you then at least check that policy ID is a proper JSON string and can't break anything when pasted here? (i.e. no escaping, just error out on bad characters, i.e. just improve the check above)
</blockquote></details>

Done

Note there is no cJSON public API to check for a properly formatted JSON string value. So instead I check the whole JSON request.

I also verified that this whole thing works.


<!-- Sent from Reviewable.io -->

2024-04-18 08:10 UTC, woju requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/75)* status: 8 of 9 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c` line 558 at r6](https://reviewable.io/reviews/gramineproject/contrib/75#-NtMGLKQ2Zq1mgUfa5Ke:-NvkE21w2qdskcYyhOJ0:b3dlk8z) ([raw file](https://github.com/gramineproject/contrib/blob/13ea9d996d8819bc2dcec636dd5fdf490b90b25b/Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c#L558)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done

Note there is no cJSON public API to check for a properly formatted JSON string value. So instead I check the whole JSON request.

I also verified that this whole thing works.
</blockquote></details>

If it's not too late, you can also define the environment variable as containing JSON list, so it would be something like:
```sh
RA_TLS_ITA_POLICY_IDS='["a","c"]'
```
That would actually be nicer:
- from the point of documentation: you can document it as the field in relevant JSON object in the ITA documentation, and don't need to special-case the single value (user would always need to provide JSON array);
- from the POV of user (scaffolding), I'll just `json.dumps()`, and won't have to strip `[]`, just for it to be re-added in your code.

Then to check the correctness, just parse just the contents of the environment variable, not the whole object. If it parses, you can certainly format it into the bigger object.


<!-- Sent from Reviewable.io -->

2024-04-18 08:20 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/75)* status: 8 of 9 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

___
*[`Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c` line 558 at r6](https://reviewable.io/reviews/gramineproject/contrib/75#-NtMGLKQ2Zq1mgUfa5Ke:-NvkHgy76o7tmIFZLNq8:bfpqg8k) ([raw file](https://github.com/gramineproject/contrib/blob/13ea9d996d8819bc2dcec636dd5fdf490b90b25b/Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c#L558)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

If it's not too late, you can also define the environment variable as containing JSON list, so it would be something like:
```sh
RA_TLS_ITA_POLICY_IDS='["a","c"]'
```
That would actually be nicer:
- from the point of documentation: you can document it as the field in relevant JSON object in the ITA documentation, and don't need to special-case the single value (user would always need to provide JSON array);
- from the POV of user (scaffolding), I'll just `json.dumps()`, and won't have to strip `[]`, just for it to be re-added in your code.

Then to check the correctness, just parse just the contents of the environment variable, not the whole object. If it parses, you can certainly format it into the bigger object.
</blockquote></details>

Yes, this suggestion from @woju makes perfect sense to me (hopefully it won't be too confusing for end users).

@mkow What do you think? If you also agree, I'll implement the JSON list.


<!-- Sent from Reviewable.io -->

2024-04-22 09:25 UTC, mkow requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/75)* status: 8 of 9 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @woju)

___
*[`Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c` line 558 at r6](https://reviewable.io/reviews/gramineproject/contrib/75#-NtMGLKQ2Zq1mgUfa5Ke:-Nw43IFu9QWBTsARgD93:b-ovwawk) ([raw file](https://github.com/gramineproject/contrib/blob/13ea9d996d8819bc2dcec636dd5fdf490b90b25b/Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c#L558)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, this suggestion from @woju makes perfect sense to me (hopefully it won't be too confusing for end users).

@mkow What do you think? If you also agree, I'll implement the JSON list.
</blockquote></details>

Good idea!
___
*[`Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c` line 566 at r9](https://reviewable.io/reviews/gramineproject/contrib/75#-Nw46Egj0sLNtrDRyIOH:-Nw46Egj0sLNtrDRyIOI:b-26kbok) ([raw file](https://github.com/gramineproject/contrib/blob/161ea0fb3793aa42a58efd34f8b2ce3175f54727/Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c#L566)):*
This is bad, you should check `RA_TLS_ITA_POLICY_IDS` _before_ you use it (i.e. before you paste it into another string), not after. And especially not concatenate it with the rest and then check everything, this feels like checking for buffer size after the buffer overflow already happened :P

And I also think that this is what @woju actually meant, see:

> Then to check the correctness, just parse just the contents of the environment variable, not the whole object. If it parses, you can certainly format it into the bigger object.


<!-- Sent from Reviewable.io -->

2024-04-22 09:27 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/75)* status: 8 of 9 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c` line 566 at r9](https://reviewable.io/reviews/gramineproject/contrib/75#-Nw46Egj0sLNtrDRyIOH:-Nw47HY38CIn54oMKvE8:b-ne685n) ([raw file](https://github.com/gramineproject/contrib/blob/161ea0fb3793aa42a58efd34f8b2ce3175f54727/Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c#L566)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This is bad, you should check `RA_TLS_ITA_POLICY_IDS` _before_ you use it (i.e. before you paste it into another string), not after. And especially not concatenate it with the rest and then check everything, this feels like checking for buffer size after the buffer overflow already happened :P

And I also think that this is what @woju actually meant, see:

> Then to check the correctness, just parse just the contents of the environment variable, not the whole object. If it parses, you can certainly format it into the bigger object.
</blockquote></details>

Yep, exactly.


<!-- Sent from Reviewable.io -->

2024-04-22 09:42 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/75)* status: 7 of 9 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

___
*[`Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c` line 558 at r6](https://reviewable.io/reviews/gramineproject/contrib/75#-NtMGLKQ2Zq1mgUfa5Ke:-Nw4ATJC5QCDu5xH9fcZ:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/13ea9d996d8819bc2dcec636dd5fdf490b90b25b/Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c#L558)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Good idea!
</blockquote></details>

Done.
___
*[`Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c` line 566 at r9](https://reviewable.io/reviews/gramineproject/contrib/75#-Nw46Egj0sLNtrDRyIOH:-Nw4AU7-7wzsGaAeQujS:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/161ea0fb3793aa42a58efd34f8b2ce3175f54727/Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c#L566)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Yep, exactly.
</blockquote></details>

Done.
___
*[`Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c` line 544 at r10](https://reviewable.io/reviews/gramineproject/contrib/75#-Nw4Aocf-3w6QAWvr0hY:-Nw4Aocf-3w6QAWvr0hZ:bqw17eq) ([raw file](https://github.com/gramineproject/contrib/blob/991c6882b983ddb2032778bb81423d075680566f/Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c#L544)):*
> ```C
>         /* sanity check that RA_TLS_ITA_POLICY_IDS specifies a JSON array of policy IDs (strings) */
>         cJSON* ita_policy_ids_parsed_check = cJSON_Parse(ita_policy_ids);
>         if (!ita_policy_ids_parsed_check || !cJSON_IsArray(ita_policy_ids_parsed_check)) {
> ```

FYI: I don't verify that all items in the JSON array are strings since this is quite a bit of additional code. This should be enough for our purposes I think.


<!-- Sent from Reviewable.io -->

2024-04-22 09:50 UTC, woju reviewed
> Reviewed 1 of 2 files at r10.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/75)* status: 8 of 9 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c` line 544 at r10](https://reviewable.io/reviews/gramineproject/contrib/75#-Nw4Aocf-3w6QAWvr0hY:-Nw4Bmd5ESSCDK32PHdK:bo6uvov) ([raw file](https://github.com/gramineproject/contrib/blob/991c6882b983ddb2032778bb81423d075680566f/Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c#L544)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

FYI: I don't verify that all items in the JSON array are strings since this is quite a bit of additional code. This should be enough for our purposes I think.
</blockquote></details>

I think that's OK.


<!-- Sent from Reviewable.io -->

2024-04-22 10:08 UTC, mkow requested changes
> Reviewed 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/75)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`Integrations/intel/ra_tls_ita/README.md` line 104 at r10](https://reviewable.io/reviews/gramineproject/contrib/75#-Nw4GV3RAUj2m0vrESD0:-Nw4GV3RAUj2m0vrESD1:beeofuc) ([raw file](https://github.com/gramineproject/contrib/blob/991c6882b983ddb2032778bb81423d075680566f/Integrations/intel/ra_tls_ita/README.md#L104)):*
> ```Markdown
> 
>   - `RA_TLS_ITA_POLICY_IDS=[ "Policy1" ]` -- single policy,
>   - `RA_TLS_ITA_POLICY_IDS=[ "Policy1","Policy2","Policy3" ]` -- set of three
> ```

IMO a bit weird spacing, but whatever (that you space around square braces but not after comma, it's usually both or none I think).
___
*[`Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c` line 549 at r10](https://reviewable.io/reviews/gramineproject/contrib/75#-Nw4GJKv5jXbAW87BBkp:-Nw4GJKv5jXbAW87BBkq:undefined) ([raw file](https://github.com/gramineproject/contrib/blob/991c6882b983ddb2032778bb81423d075680566f/Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c#L549)):*
> ```C
>             goto out;
>         }
>         free(ita_policy_ids_parsed_check);
> ```





_Suggestion:_
```C
cJSON_Delete(ita_policy_ids_parsed_check);
```


<!-- Sent from Reviewable.io -->

2024-04-22 11:22 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/75)* status: 7 of 9 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

___
*[`Integrations/intel/ra_tls_ita/README.md` line 104 at r10](https://reviewable.io/reviews/gramineproject/contrib/75#-Nw4GV3RAUj2m0vrESD0:-Nw4XnT790gMLgdTXb_o:bb6un1j) ([raw file](https://github.com/gramineproject/contrib/blob/991c6882b983ddb2032778bb81423d075680566f/Integrations/intel/ra_tls_ita/README.md#L104)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

IMO a bit weird spacing, but whatever (that you space around square braces but not after comma, it's usually both or none I think).
</blockquote></details>

Done
___
*[`Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c` line 549 at r10](https://reviewable.io/reviews/gramineproject/contrib/75#-Nw4GJKv5jXbAW87BBkp:-Nw4XaJ24W7NevxdV20b:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/991c6882b983ddb2032778bb81423d075680566f/Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c#L549)):*
> ```C
>             goto out;
>         }
>         free(ita_policy_ids_parsed_check);
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-04-22 22:33 UTC, mkow approved these changes
> Reviewed 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/75)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2024-04-23 07:35 UTC, woju approved these changes
> Reviewed 1 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/75)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2024-04-23 07:50 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/75)* status: all files reviewed, 1 unresolved discussion (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/75#-Nw8viYNEtiYPQAiItqq:-Nw8viYNEtiYPQAiItqr:bu28gxm) (no related file):*
Working: need to perform a final test of this rebased PR.

___


<!-- Sent from Reviewable.io -->

2024-04-23 08:22 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/75)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/75#-Nw8viYNEtiYPQAiItqq:-Nw92Dkq0HzLduCLdhdD:b9lyu4m) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Working: need to perform a final test of this rebased PR.
</blockquote></details>

Done, it works.

___


<!-- Sent from Reviewable.io -->

2024-04-23 11:11 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/75)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-04-23 11:31 UTC, merged