[Curated-Apps] Move to Gramine v1.6.1
gramineproject/contrib pull request #81
Opened 2024-03-01 08:02 UTC by jkr0103

1. Curated Apps moves to Gramine V1.6.1
2. With the new release of Gramine, old released packages are removed which always breaks verifier. With this PR, packages are downloaded from github and used.

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/contrib/81)

2024-03-03 13:12 UTC, mkow requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/81)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @jkr0103)

___
*[`Intel-Confidential-Compute-for-X/verifier/verifier.dockerfile.template` line 24 at r1](https://reviewable.io/reviews/gramineproject/contrib/81#-Ns3RCleAtGyCa7LS5qj:-Ns3RCleAtGyCa7LS5qk:baei7vv) ([raw file](https://github.com/gramineproject/contrib/blob/373bb72fac1faf77837670dd440b56133ef17b1d/Intel-Confidential-Compute-for-X/verifier/verifier.dockerfile.template#L24)):*
> ```
>     python3-jinja2 \
>     python3-tomli \
>     python3-tomli-w
> ```

Why moving to 1.6.1 requires this change?
___
*[`Intel-Confidential-Compute-for-X/verifier/verifier.dockerfile.template` line 43 at r1](https://reviewable.io/reviews/gramineproject/contrib/81#-Ns3RPa5BOs1EU3Q1ZoD:-Ns3RPa5BOs1EU3Q1ZoE:b-5y8ly9) ([raw file](https://github.com/gramineproject/contrib/blob/373bb72fac1faf77837670dd440b56133ef17b1d/Intel-Confidential-Compute-for-X/verifier/verifier.dockerfile.template#L43)):*
> ```
> 
> RUN wget https://github.com/gramineproject/gramine/releases/download/v1.6.1/gramine-ratls-dcap_1.6.1_amd64.deb \
>     && dpkg -i gramine-ratls-dcap_1.6.1_amd64.deb
> ```

Does this still check the packages' signatures?


<!-- Sent from Reviewable.io -->

2024-03-04 07:07 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/81)* status: 1 of 3 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`Intel-Confidential-Compute-for-X/verifier/verifier.dockerfile.template` line 24 at r1](https://reviewable.io/reviews/gramineproject/contrib/81#-Ns3RCleAtGyCa7LS5qj:-Ns7Ez2AB-azstZx58hi:bbfls4t) ([raw file](https://github.com/gramineproject/contrib/blob/373bb72fac1faf77837670dd440b56133ef17b1d/Intel-Confidential-Compute-for-X/verifier/verifier.dockerfile.template#L24)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why moving to 1.6.1 requires this change?
</blockquote></details>

It seems `apt` by default installs the dependent packages but `dpkg` doesn't. With `dpkg`, we get below dependency errors:

```
Preparing to unpack gramine_1.6.1_amd64.deb ...
Unpacking gramine (1.6.1) ...
[91mdpkg: dependency problems prevent configuration of gramine:
 gramine depends on libprotobuf-c1; however:
  Package libprotobuf-c1 is not installed.
 gramine depends on python3; however:
  Package python3 is not installed.
 gramine depends on python3 (>= 3.10) | python3-pkg-resources; however:
  Package python3 is not installed.
  Package python3-pkg-resources is not installed.
 gramine depends on python3-click (>= 6.7); however:
  Package python3-click is not installed.
 gramine depends on python3-cryptography; however:
  Package python3-cryptography is not installed.
 gramine depends on python3-jinja2; however:
  Package python3-jinja2 is not installed.
 gramine depends on python3-pyelftools; however:
  Package python3-pyelftools is not installed.
 gramine depends on python3-tomli (>= 1.1.0); however:
  Package python3-tomli is not installed.
 gramine depends on python3-tomli-w (>= 0.4.0); however:
  Package python3-tomli-w is not installed.
```
___
*[`Intel-Confidential-Compute-for-X/verifier/verifier.dockerfile.template` line 43 at r1](https://reviewable.io/reviews/gramineproject/contrib/81#-Ns3RPa5BOs1EU3Q1ZoD:-Ns7GyZG98puMfQxDpFN:b-jh8w63) ([raw file](https://github.com/gramineproject/contrib/blob/373bb72fac1faf77837670dd440b56133ef17b1d/Intel-Confidential-Compute-for-X/verifier/verifier.dockerfile.template#L43)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Does this still check the packages' signatures?
</blockquote></details>

No, it doesn't check the package's signatures.


<!-- Sent from Reviewable.io -->

2024-03-04 07:24 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/81)* status: 1 of 3 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @jkr0103 and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/81#-Ns7L68r1f9TjrQiorpr:-Ns7L68r1f9TjrQiorps:bm1xm6g) (no related file):*
I don't understand this change. Why? We do have Gramine v1.6.1 in apt repositories, why this change?

> With this PR, packages are downloaded from github and used.

But this way is strictly worse / unsafe than using proper signed packages from our apt repos.

___


<!-- Sent from Reviewable.io -->

2024-03-04 08:37 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/81)* status: 1 of 3 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @jkr0103 and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/81#-Ns7L68r1f9TjrQiorpr:-Ns7b-x48v7QResuxvYe:b-1yemqu) (no related file):*
> Everytime we have new released packages, verifier breaks as old release packages are removed.

Why does the verifier break?

___


<!-- Sent from Reviewable.io -->

2024-03-04 08:46 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/81)* status: 1 of 3 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/81#-Ns7L68r1f9TjrQiorpr:-Ns7cu7I7NASlDJiE9L_:bh99kwn) (no related file):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

Gramine `v1.6` package is not found in the apt repositories as it's replaced with`v1.6.1`
</blockquote></details>

verifier build fails with below error:
```
Step 6/15 : RUN env DEBIAN_FRONTEND=noninteractive apt-get update     && env DEBIAN_FRONTEND=noninteractive apt-get install -y     libsgx-dcap-default-qpl=1.16.100.2-jammy1     gramine=1.6
 ---> Running in e3f9bb281d08
Hit:1 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:2 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:3 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Get:4 https://download.01.org/intel-sgx/sgx_repo/ubuntu jammy InRelease [1236 B]
Hit:5 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Get:6 https://download.01.org/intel-sgx/sgx_repo/ubuntu jammy/main amd64 Packages [64.0 kB]
Get:7 https://packages.gramineproject.io jammy InRelease [3275 B]
Get:8 https://packages.gramineproject.io jammy/main amd64 Packages [1059 B]
Fetched 69.6 kB in 2s (30.5 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
Package gramine is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Version '1.6' for 'gramine' was not found
The command '/bin/sh -c env DEBIAN_FRONTEND=noninteractive apt-get update     && env DEBIAN_FRONTEND=noninteractive apt-get install -y     libsgx-dcap-default-qpl=1.16.100.2-jammy1     gramine=1.6' returned a non-zero code: 100

```

___


<!-- Sent from Reviewable.io -->

2024-03-04 08:50 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/81)* status: 1 of 3 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/81#-Ns7L68r1f9TjrQiorpr:-Ns7dSffClQ-yKcF5St_:b-8mk11) (no related file):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

verifier build fails with below error:
```
Step 6/15 : RUN env DEBIAN_FRONTEND=noninteractive apt-get update     && env DEBIAN_FRONTEND=noninteractive apt-get install -y     libsgx-dcap-default-qpl=1.16.100.2-jammy1     gramine=1.6
 ---> Running in e3f9bb281d08
Hit:1 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:2 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:3 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Get:4 https://download.01.org/intel-sgx/sgx_repo/ubuntu jammy InRelease [1236 B]
Hit:5 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Get:6 https://download.01.org/intel-sgx/sgx_repo/ubuntu jammy/main amd64 Packages [64.0 kB]
Get:7 https://packages.gramineproject.io jammy InRelease [3275 B]
Get:8 https://packages.gramineproject.io jammy/main amd64 Packages [1059 B]
Fetched 69.6 kB in 2s (30.5 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
Package gramine is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Version '1.6' for 'gramine' was not found
The command '/bin/sh -c env DEBIAN_FRONTEND=noninteractive apt-get update     && env DEBIAN_FRONTEND=noninteractive apt-get install -y     libsgx-dcap-default-qpl=1.16.100.2-jammy1     gramine=1.6' returned a non-zero code: 100

```
</blockquote></details>

@woju I just learned that apt doesn't understand ranges (i.e. "equal to or greather than") for versions of packages: https://askubuntu.com/questions/916598/how-to-install-a-package-greater-than-or-equal-to-a-particular-version

How do people work around this limitation? How can @jkr0103 resolve this problem? If there's nothing smarter than ditching apt and doing e.g. `wget github.com ...`, then I'll be fine with this PR.

___


<!-- Sent from Reviewable.io -->

2024-03-06 15:59 UTC, woju requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/81)* status: 1 of 3 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/81#-Ns7L68r1f9TjrQiorpr:-NsJPPGR-hnHqGw33WNt:bpfh4xf) (no related file):*
> I tried that but it failed as Gramine packages in github are not signed.

This is correct. `dpkg-sig` is not a widely used tool, because in Debian world (incl. Ubuntu) what is signed is the *repository* (with packages' hashes); packages themselves are not signed individually.

> I just learned that apt doesn't understand ranges (i.e. "equal to or greather than") for versions of packages:

Standard stack overflow. The second answer in the link is correct, not the (accepted) first one: `apt-get satisfy 'gramine (>= 1.6)'` (note `satisfy` instead of `install`, and funny syntax from `debian/control`, with whitespace and parens). But that answer could be even worse in this situation, see below.

@jkr0103 I still don't understand this sentence:

> We want to get out of the situation where verifier breaks with new release of Gramine.

Do you mean verified *build* is breaking?

Because verifier does break anyway when you update gramine in the workload. You need verified matching the workload 1=1 (or 1.6=1.6, or 1.6.1=1.6.1, you get the point). This PR changes nothing in this regard. When update comes, you just need to update `gramine` package everywhere, in workloads and in verifiers. It's as simple as that.

So let's suppose instead on `install gramine=1.6` you wrote `satisfy 'gramine (>= 1.6)'` like Dmitrii suggested. Suppose further that we've merged this PR and you've rebuilt verifier. Now, say I pushed 1.7 Gramine and you didn't change verifier because you didn't need to change anything else, right? If you have cached previous version, note that the dockerfile didn't change (1.7 >= 1.6 is true), so `docker build` uses cached layer and you've still built a verifier with 1.6.1 and it's still broken.

So IDK if this is really what you want. If you follow Dmitrii's suggestion, you need to purge docker cache on every build. I bet someone someday will forget to do this. Admittedly you'll get the expected result of "verifier build always succeeds", but in some cases you get incorrect build results. I don't think this is local extremum that you want to optimise for.

___


<!-- Sent from Reviewable.io -->

2024-03-06 16:49 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/81)* status: 1 of 3 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/81#-Ns7L68r1f9TjrQiorpr:-NsJbu5Q9NU0nhD2lmfx:bk952a0) (no related file):*
>Because verifier does break anyway when you update gramine in the workload.

I think we misunderstood the main issue here. We are not changing gramine in workload. Verifier breaks without any change in contrib code with the release of Gramine v1.6.1 packages.

`install gramine=1.6` results in below error with verifier build:

```
E: Version '1.6' for 'gramine' was not found
```

`satisfy 'gramine (>= 1.6)'` is also not a solution. This would create a situation in contrib where Gramine is v1.61. but GSC is still v1.6 and both might not be compatible.

Best would be existing code e.g. `install gramine=1.6` works or some other way which doesn't forces to changes the Gramine version in verifier and also keeping the GSC and Gramine versions same.

___


<!-- Sent from Reviewable.io -->

2024-03-06 17:37 UTC, woju requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/81)* status: 1 of 3 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/81#-Ns7L68r1f9TjrQiorpr:-NsJm_Yz2OWB59e4f_Z6:b18whgx) (no related file):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

>Because verifier does break anyway when you update gramine in the workload.

I think we misunderstood the main issue here. We are not changing gramine in workload. Verifier breaks without any change in contrib code with the release of Gramine v1.6.1 packages.

`install gramine=1.6` results in below error with verifier build:

```
E: Version '1.6' for 'gramine' was not found
```

`satisfy 'gramine (>= 1.6)'` is also not a solution. This would create a situation in contrib where Gramine is v1.61. but GSC is still v1.6 and both might not be compatible.

Best would be existing code e.g. `install gramine=1.6` works or some other way which doesn't forces to changes the Gramine version in verifier and also keeping the GSC and Gramine versions same.
</blockquote></details>

If you do not change gramine in workload (I understand this means you don't rebuild container with workload so gramine is left as it was), then you can also just not rebuild verifier container and it will remain as it was. I think you can't possibly rebuild workload container without updating gramine packages to 1.6.1, because it will fail in the same way as the verifier fails here, won't it?

GSC was updated to use 1.6.1 about 2 weeks ago: https://github.com/gramineproject/gsc/commit/95edc1de0a656e56eee7d21ef5bb83347b4f3ada. Does this matter for the purpose of this conversation?

Or am I missing some important scenario? It is ever necessary to rebuild the verifier container without rebuilding workload container?

Second question: Do you even need exactly matching versions? Reading just `verifier.dockerfile.template`, I think what you need Gramine packages for is RA-TLS libraries needed to build `server_dcap`. RA-TLS format it pretty stable, so unless it changes (or there's a vulnerability) you don't need to update it and `satisfy` might be OK (then in the dependency you put the first version after incompatible change or after security fix).

___


<!-- Sent from Reviewable.io -->

2024-03-06 18:08 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/81)* status: 1 of 3 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/81#-Ns7L68r1f9TjrQiorpr:-NsJv6HC8Ge9MgjKBnlU:b9can14) (no related file):*
>I think you can't possibly rebuild workload container without updating gramine packages to 1.6.1, because it will fail in the same way as the verifier fails here, won't it?

Workload build is done using GSC V1.6 and not with Gramine packages, hence workload build doesn’t have any issue.

Anybody clone contrib freshly and try workload and verifier build, workload build succeeds but verifier build fails. This is the scenario we are trying to fix.


>Do you even need exactly matching versions?

As of now I don’t see any issue, but in future we might face, until then we can go with ‘satisfy 'gramine (>= 1.6)'’ if others are also fine?

___


<!-- Sent from Reviewable.io -->

2024-03-07 07:50 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/81)* status: 1 of 3 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/81#-Ns7L68r1f9TjrQiorpr:-NsMt35rADaGVEk5_krk:b-xd8z7o) (no related file):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

>I think you can't possibly rebuild workload container without updating gramine packages to 1.6.1, because it will fail in the same way as the verifier fails here, won't it?

Workload build is done using GSC V1.6 and not with Gramine packages, hence workload build doesn’t have any issue.

Anybody clone contrib freshly and try workload and verifier build, workload build succeeds but verifier build fails. This is the scenario we are trying to fix.


>Do you even need exactly matching versions?

As of now I don’t see any issue, but in future we might face, until then we can go with ‘satisfy 'gramine (>= 1.6)'’ if others are also fine?
</blockquote></details>

So after reading the conversation, I think the best is to just do `apt install gramine`

___


<!-- Sent from Reviewable.io -->

2024-03-07 10:38 UTC, dimakuv commented
PR https://github.com/gramineproject/contrib/pull/82 superseded this one and was already merged. We can close this PR.

2024-03-07 10:38 UTC, closed without merging