[Curated-Apps] Auto fetch latest release tag
gramineproject/contrib pull request #83
Opened 2024-03-11 06:41 UTC by jkr0103

With the new release of Gramine, old packages are replaced with new packages which use to cause verifier's build failure.

We always needed a PR to fix it after every Gramine release.

This issue was fixed partially with PR #82 where Gramine would use latest release package but GSC is still on old release.

Curated apps would still fail i GSC and Gramine versions are not same and also not compatible.

This PR tries to minimize the difference of releases used for GSC and Gramine as latest tags are fetched automatically.

There could be the issue again if there is time gap in creating the latest release tags for Gramine and GSC and in that time a user curate the apps. We can think of placing a policy for creating Gramine and GSC tags at the same time.

2024-03-11 07:27 UTC, dimakuv approved these changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/83)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @jkr0103)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/83#-NsgO_zoB76pKXrfVEHP:-NsgO_zoB76pKXrfVEHQ:b-nr1xbk) (no related file):*
> We can think of placing a policy for creating Gramine and GSC tags at the same time.

Gramine and GSC tags are typically created in ~12 hours difference (first Gramine tag, then GSC tag). You're right, we can probably have a strict rule to bound this time difference.

Btw, isn't it **three projects**?
1. Gramine repo
2. GSC repo
3. Examples repo

@woju How do other projects deal with two packages/sub-projects that depend on each other? How are they updated simulteneously?

___
*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/83#-NsgP4bm8mku63Jmph2z:-NsgP4bm8mku63Jmph3-:biz3f6m) (no related file):*
The PR looks good to me.

___


<!-- Sent from Reviewable.io -->

2024-03-11 11:29 UTC, woju submitted a review, later dismissed
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/83)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/83#-NsgO_zoB76pKXrfVEHP:-NshBgfa8oEK7ZhfdBQQ:b58hlkb) (no related file):*
> How do other projects deal with two packages/sub-projects that depend on each other? How are they updated simulteneously?

Varies per project (and project scale), but for our case I think we have 2 options: either think carefully about dependencies' specifications (like, in some situations it's OK to have a bit older Gramine version, we can specify `>=`, not `=`), or accept the fact that we need to update downstream repos whenever version change happens upstream. This doesn't happen instantly, but it's possible to just be better at releasing, have more automation (like my not-yet-merged script) and do it more often, so we as a project will be more proficient in doing it faster.

There are other solutions, for problems of bigger scale (either more repos or circular dependencies) distros have some solutions and those vary wildly. Fedora and the rest of RPM world have flag days, so they just announce that something will break across a given point in time. Debian has something called „transitions” (https://release.debian.org/transitions/), where they coordinate some changes between upstream and downstream packages by taking advantage of deb's more powerful and complicated model of dependency specification.

I suggest to use `>=` and/or `<<` dependencies where possible, and if not possible, then think why and what to do next. I don't think we've arrived at a point where we need other solutions yet. In the meantime we can try to smooth the release process. Like here, this PR essentially suggests to use latest existing release, possibly slightly old, and I think it's correct.

___


<!-- Sent from Reviewable.io -->

2024-03-11 13:08 UTC, mkow requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/83)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @dimakuv and @jkr0103)

___
*[`Intel-Confidential-Compute-for-X/util/curation_script.sh` line 129 at r1](https://reviewable.io/reviews/gramineproject/contrib/83#-Nshc0ViBYFpVv1owIy_:-Nshc0VjD8020n0eU2tP:b-45hsvx) ([raw file](https://github.com/gramineproject/contrib/blob/a5b73aa5e68077fe11de4ce412444ddfa2879909/Intel-Confidential-Compute-for-X/util/curation_script.sh#L129)):*
> ```Shell
>     git clone https://github.com/gramineproject/gsc.git
>     cd gsc
>     git checkout $(git tag --sort=taggerdate | tail -1)
> ```

This assumes that we only tag official releases and will break if someone adds a tag for something else. A fix suggested by Dmitrii: `git tag --list 'v*.*' --sort=taggerdate | tail -1`
___
*[`Intel-Confidential-Compute-for-X/verifier/verifier.dockerfile.template` line 29 at r1](https://reviewable.io/reviews/gramineproject/contrib/83#-NshcAxk3hEIVKxxeJ2Y:-NshcAxk3hEIVKxxeJ2Z:b-7ropln) ([raw file](https://github.com/gramineproject/contrib/blob/a5b73aa5e68077fe11de4ce412444ddfa2879909/Intel-Confidential-Compute-for-X/verifier/verifier.dockerfile.template#L29)):*
> ```
> 
> RUN git clone https://github.com/gramineproject/gramine.git \
>     && cd gramine && git checkout $(git tag --sort=taggerdate | tail -1)
> ```

ditto
___
*[`Intel-Confidential-Compute-for-X/workloads/pytorch/base_image_helper/helper.sh` line 15 at r1](https://reviewable.io/reviews/gramineproject/contrib/83#-NshcEoH4e3vL_6vsEsn:-NshcEoH4e3vL_6vsEso:b-7ropln) ([raw file](https://github.com/gramineproject/contrib/blob/a5b73aa5e68077fe11de4ce412444ddfa2879909/Intel-Confidential-Compute-for-X/workloads/pytorch/base_image_helper/helper.sh#L15)):*
> ```Shell
> git clone https://github.com/gramineproject/examples.git
> cd examples/pytorch
> git checkout $(git tag --sort=taggerdate | tail -1)
> ```

ditto


<!-- Sent from Reviewable.io -->

2024-03-12 03:17 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/83)* status: 0 of 3 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @woju)

___
*[`Intel-Confidential-Compute-for-X/util/curation_script.sh` line 129 at r1](https://reviewable.io/reviews/gramineproject/contrib/83#-Nshc0ViBYFpVv1owIy_:-Nske_GU0w9oWveUUhqk:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/a5b73aa5e68077fe11de4ce412444ddfa2879909/Intel-Confidential-Compute-for-X/util/curation_script.sh#L129)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This assumes that we only tag official releases and will break if someone adds a tag for something else. A fix suggested by Dmitrii: `git tag --list 'v*.*' --sort=taggerdate | tail -1`
</blockquote></details>

Done.
___
*[`Intel-Confidential-Compute-for-X/verifier/verifier.dockerfile.template` line 29 at r1](https://reviewable.io/reviews/gramineproject/contrib/83#-NshcAxk3hEIVKxxeJ2Y:-Nskebea9vL8S2Ql6jMc:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/a5b73aa5e68077fe11de4ce412444ddfa2879909/Intel-Confidential-Compute-for-X/verifier/verifier.dockerfile.template#L29)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`Intel-Confidential-Compute-for-X/workloads/pytorch/base_image_helper/helper.sh` line 15 at r1](https://reviewable.io/reviews/gramineproject/contrib/83#-NshcEoH4e3vL_6vsEsn:-NskechH391b6WhmvJ6Z:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/a5b73aa5e68077fe11de4ce412444ddfa2879909/Intel-Confidential-Compute-for-X/workloads/pytorch/base_image_helper/helper.sh#L15)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-12 07:26 UTC, dimakuv approved these changes
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/83)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2024-03-13 09:33 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/83)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2024-03-13 09:34 UTC, woju approved these changes
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/83)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-03-13 09:36 UTC, merged